### ISSUE TITLE
サクラエディタの対応OS に関して検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#100]
サクラエディタの対応OS に関して検討する

ヘルプに記載の対応 OS は
http://sakura-editor.sourceforge.net/htmlhelp2/HLP000003.html

```
OS 日本語版 Windows 2000/XP/2003/Vista/7/8
Windowsが快適に動くCPUがお奨め
画面解像度800*600以上がお奨め
64bit版のバイナリも公開しています。
ただし機能的違いは一切ありません。
また、32ビットDLLのPPA/Migemoは利用できません。
```

**Comment by m-tmatma** [comment]
開発者で推測するより、現在使用している OS と 対応してほしい OS を
アンケートで聞くというのがいいのかも。
https://github.com/sakura-editor/sakura/issues/71#issuecomment-395761186

参考情報
https://hep.eiz.jp/google-form-one-answer/

**Comment by berryzplus** [comment]
もし対応希望が少なければ windows 7 まで一気に引き上げてしまいたいです。
現行 windows 10 には windows 7 から導入された基本機能が結構あることと、
windows vista のサポート期限が既に切れていることが理由です。

**Comment by KENCHjp** [comment]
そのOSで動くことを知っている人はそこに何が書いてあっても動かすと思うので、
既にサポートが切れているOSは削除するのが正しい姿かなと思います。

**Comment by m-tmatma** [comment]
> もし対応希望が少なければ windows 7 まで一気に引き上げてしまいたいです。

私も　windows 7 以降でいいと思ってます。

サポートが切れた OS を使い続けたい人は、(稼働実績のある)古いバージョンのサクラエディタを
使えばいいと思っています。

**Comment by kobake** [comment]
同じく 7 以降に同意です。
古いWindowsバージョンへの対応を熱烈にやってくれるコミッタがいるなら別ですが、現状はそうでもないので。ドッグフーディングできない対応はやろうとしてもたぶんおざなりになります。

**Comment by KageShiron** [comment]
7より前を打ち切るなら、2000～Vista用の最終バージョンを2.3.2.1などとしてリリースしたいですね。

 次回リリースのバージョン番号の決定 #71

その他、レガシーな部分をいくつか探してみました。

* PPAマクロ→DLLの対応がXPまで
* bregexp.dll→すでに2.0.0.0系では使えない?bregonig.dll決め打ちで良いのでは
* JScriptのバージョンを最新に上げるといろいろ便利かも
http://subtech.g.hatena.ne.jp/mayuki/20111216/1324015296

**Comment by kobake** [comment]
> 7より前を打ち切るなら、2000～Vista用の最終バージョンを2.3.2.1などとしてリリースしたいですね。

理想としてはそうなのですが、2000 用のビルドできる人がいるかどうか微妙ですね。
Win2000 で VS2003 あたりがインストールされている環境があれば可能かもしれません。

それが難しそうだったらせめて 2.3.2.0 の exe は既にあるので、それをインストーラパッケージにしたものを配布するくらいでしたら対応は難しくない（？）かもしれません。

> bregexp.dll→すでに2.0.0.0系では使えない?bregonig.dll決め打ちで良いのでは

bregonig 決め打ちで良いと思います。

bregexp については SourceForge の sakura-editor 領域にあったものをそのまま移行してきましたが、たぶんサクラエディタコミュニティとしてはこれをメンテナンスすることは無い気がするので、このリポジトリについては原作者の Tatsuo Baba さんの GitHub アカウントがあればそこに移したいお気持ちです。

**Comment by kobake** [comment]
> 2000 用のビルドできる人

novice さんが ANSI 版のメンテを粛々とやっておられたようなので、もしかしたら彼なら可能かも、と思っています。こちらの GitHub 側に顔を出してくれることを気長に期待してます。

**Comment by KageShiron** [comment]
一応Visual Studio Subscriptionあるので、手元ビルドはできそうです。

**Comment by k-takata** [comment]
> このリポジトリについては原作者の Tatsuo Baba さんの GitHub アカウントがあればそこに移したいお気持ちです。

サクラエディタのbregexpは関数が2個ほど追加された改造版です。なので、原作者に管理してもらうべきものではないです。
今後メンテする予定はないというのであれば、リポジトリ自体をarchivedに設定するのがよいでしょう。

**Comment by kobake** [comment]
> 一応Visual Studio Subscriptionの環境が使えそうなので、手元でしたらビルドできそうです。

おお、ありがたいです。折を見てお願いさせてください。

> サクラエディタのbregexpは関数が2個ほど追加された改造版です。なので、原作者に管理してもらうべきものではないです。
> 今後メンテする予定はないというのであれば、リポジトリ自体をarchivedに設定するのがよいでしょう。

なるほど……。とりあえず archive しておきました。

ちなみに今 archive の機能初めて知りました。
いろんな人が関わってもらうといろんな知識が得られて良いですねぇ 😃

**Comment by k-takata** [comment]
なお、bregexpにはいくつかバグが見つかっています。
http://k-takata.o.oo7.jp/diary/2007-06.html#25b

**Comment by kobake** [comment]
おおお……

**Comment by k-takata** [comment]
bregexpのプロジェクトの説明が「SourceForgeから移行 」になっていますが、「Bregexp.dll for SAKURA」等に変えておいた方がいいと思います。(1回archiveを解除する必要があるかもしれません。)

**Comment by kobake** [comment]
変えておきました。

**Comment by KENCHjp** [comment]
この子もクローズで大丈夫そうですか？

**Comment by kobake** [comment]
OSのサポート範囲はある程度意識定まったと思ってますが、このIssueのクローズ条件はREADMEとWebにOSサポート範囲を明記することにするのが良いと思います。

READMEはいつ書き換えても良いとして、Webの書き換えタイミングは要検討かなーと思ってます。次リリースのタイミングに合わせるのが良いのかな、とか。ご意見あればください。

**Comment by m-tmatma** [comment]
Win8 や　Win8.1 で動作確認できる環境をお持ちのかたはいますか?
現状では Win7 とWin10 しか動作確認してないと思います。

動作確認してないものを対応していますと、いうのは気が引ける。
多分動くみたいなことしか言えないような。

**Comment by KENCHjp** [comment]
一応、8.1のVirtualBOXバイナリはあるようなので、英語OSですが日本語化はすぐできるので、環境作れます。

8の環境作れないのでどなたももってなければ、いっそ除外かなと？？？

OS 日本語版 Windows 2000/XP/2003/Vista/7/8
↓
OS 日本語版 Windows 7/8.1/10

**Comment by berryzplus** [comment]
PPAマクロは廃止しても困らないんでしたっけ？

**Comment by berryzplus** [comment]
> じゃあ、代替え用意しなくていいのかって議論はあるのかもしれませんが。

内部的に「キーマクロ」と統合されてて（ずいぶん昔に実装されてる）、
ppa.dllがある場合だけppaが動く構造になってるようです。

poor-pascal for applicationsで書いたマクロを持ってない人にとっては、
「拡張子ppaのキーマクロ」が使えなくなるだけなので代替はいらんような・・・

**Comment by KENCHjp** [comment]
>「拡張子ppaのキーマクロ」が使えなくなるだけなので代替はいらんような・・・

その線で進めましょう。
ppa.dllはソースも公開されていないようなので、巻き取れないし。。。
Delphiの64bit版コンパイラ持ってないし。。。

**Comment by KENCHjp** [comment]
![8 1](https://user-images.githubusercontent.com/39618965/45914597-efeac800-be81-11e8-8084-7009ee03f859.PNG)
8.1環境作れました。とりあえずインストーラー動かして起動確認まではしました。

**Comment by arigayas** [comment]
Windows 8.1のサポートは続いてますが Windows 8 のサポートは8.1が出たせいか終わったので対応OSから外しても良いと思います。
ご存じですか? OS にはサポート期限があります! - Microsoft atLife → https://www.microsoft.com/ja-jp/atlife/article/windows10-portal/eos.aspx
![image](https://user-images.githubusercontent.com/11251874/45916267-2c2c2180-be9e-11e8-98b6-60c652d0cc21.png)

 ### Delphiの64bit版
> Delphiの64bit版コンパイラ持ってないし。。。金出さないと手に入らないし。。。

Delphi のコミュニティ版が今年の7月にリリースされて
年商5000ドル以下までならProfessionalと同等の物が手には入るようになりましたよ。
つまりWindows 32&64bit/macOS/iOS/Androidを作成できるようになりました。
[「Delphi」「C++Builder」のフル機能を無償で ～“Community Edition”が発表](https://forest.watch.impress.co.jp/docs/news/1133620.html)

**Comment by KENCHjp** [comment]
>年商5000ドル以下までならProfessionalと同等の物が手には入るようになりましたよ。

まじすか、Starter editionとか、ころころ変わってて、結局、前のStertereditionだと32bitだけなんすよね開発できるの。

ちょっと調べてみます。

とはいえ、PPAには役に立たないかもしれませんが・・・

@arigayas さんありがとうございます。

**Comment by m-tmatma** [comment]
https://www.appveyor.com/docs/windows-images-software/
には Delphi は含まれてないです。

インストールされているかもしれませんが、されていない可能性が高い。

**Comment by KENCHjp** [comment]
@arigayas さん、よくよく見たらあれですね、Community Editionって１年ライセンスのやつですね。
記事によると毎年更新できるってかいてありますが、エンバカデロって何やるかわからないですからねぇ。。。

**Comment by arigayas** [comment]
@KENCHjp Community Editionって１年ライセンスのやつです。来年も使えるのか不安があるのはエンバカデロってまだ信頼性が低いですよね・・・。

**Comment by berryzplus** [comment]
これ、結論出てる（一応、Windows7以降）ので閉じておきます。
