### ISSUE TITLE
ファイルのシンボリックリンクを開くとファイルを更新していないのに「ファイルが更新されました」というメッセージボックスが表示される

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#1010]
## 問題内容
タイトルの通りですが、シンボリックリンクをサクラエディタにドロップしてファイルを開くと「ファイルが更新されました」というメッセージボックスがファイルを更新していないのに表示されます。`再読込` ボタンを何度押しても同じメッセージボックスが続けて表示されます。

## 再現手順
- シンボリックリンクをサクラエディタのウィンドウにドロップする
  - もしくは右クリックメニューの `SAKURA Editorで開く`
- ファイルを開いた後に何も操作をしないでも、「ファイルが更新されました」というメッセージボックスが表示される

## 再現頻度
必ず再現する

## 問題のカテゴリ
- プログラムの動作上の問題

## 環境情報
- OS バージョン

```
サクラエディタ   v2.4.0.2181 64bit dev Alpha Version
(GitHash 5ac4567ca1c1704718d34a79c58e5d304b59591c)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V_A641916 WPR WIN601/I800/C000/N601
      Last Modified: 2019/8/24 05:05:04
```

## スクリーンショット

![image](https://user-images.githubusercontent.com/1131125/63633833-6ba05680-c689-11e9-8de9-8d1aa1171463.png)

**Comment by berryzplus** [comment]
むむっ！ label が bug ですね・・・！
これはバグなんでしょうか？とメンドクサイ質問をしてみたりしてｗ

単にシンボリックリンクという比較的新しいwindowsの機能に、これまで対応しとらんかった、というだけの話なので、バグじゃ～～～、原因究明じゃ～～～、横展じゃ～～～と騒ぐのは違うような気がします。

いずれにしろ、対応は歓迎します :smiley:

**Comment by beru** [comment]
> むむっ！ label が bug ですね・・・！
> これはバグなんでしょうか？とメンドクサイ質問をしてみたりしてｗ
> 
> 単にシンボリックリンクという比較的新しいwindowsの機能に、これまで対応しとらんかった、というだけの話なので、バグじゃ～～～、原因究明じゃ～～～、横展じゃ～～～と騒ぐのは違うような気がします。

過去の状況がどうであれ現時点での動作があるべきものから外れている場合にはバグと見なしています。

別に過去に誰が作成したとか責任とかそういう事を考えた事は無くて、ただ単に現状の動作を改善したいだけです。

あとバグの定義について哲学的な議論をするつもりはありません。

**Comment by berryzplus** [comment]
哲学的な議論をしたいわけじゃないです。

ユーザー視点でみてバグなのは事実なので、それはそれで良いです。
ただ、一方的に作者の落ち度かというと違うと思うので、
あとでこのissueを見る人のために参考意見を書いただけです。

**Comment by beru** [comment]
> ユーザー視点でみてバグなのは事実なので、それはそれで良いです。
> ただ、一方的に作者の落ち度かというと違うと思うので、
> あとでこのissueを見る人のために参考意見を書いただけです。

作者に落ち度はありません。フリーソフトなので保証等は何もありません。

**Comment by beru** [comment]
「過去に実装していた時には問題が起きえなく想定外だった。今になって事情が変わってそこに問題が発生してもバグというレッテルを貼るのは酷」という考えは何か状況に対して余計な人情や感情を入れている気がします。

もちろん誰もがどういう考えや言論をしようと自由なんですが、自分が github のラベルを貼り続ける事に対して自己弁護する自由も有る筈…、、ﾌﾞﾂﾌﾞﾂ

**Comment by berryzplus** [comment]
この話題は既に雑談モードに突入している（結論はどっちでもいい）と思ってます :smile: 

> フリーソフトなので保証等は何もありません。

サクラエディタは、何気に「業務利用」が多いように感じています。
保証等はないんですが、ないんですが、ないんですが・・・（笑

OS機能追加に対応する、という観点で見た時に、他の機能がシンボリックリンクに対応しているのか対応してないのかを整理して、必要なら対応を行うためのissueを立てたほうがよいのかも知れません。話題に出てませんが、たぶんハードリンク(win2k以降)にも完全には対応しとらんですよね・・・。

まぁ、このissue自体はPRがマージできたら閉じて構わないと思ってます。

**Comment by beru** [comment]
> サクラエディタは、何気に「業務利用」が多いように感じています。
> 保証等はないんですが、ないんですが、ないんですが・・・（笑

そうですね…怖いユーザーを怒らせてしまうと何が有るか分からないですね。。仮に法的責任は百歩譲って無いとしても道義的責任、社会的責任、連帯責任が有る！と言い張られて天誅とかポアとかタイヤネックレスされてしまいそうでｶﾞﾀｶﾞﾀ震えています…。

> OS機能追加に対応する、という観点で見た時に、他の機能がシンボリックリンクに対応しているのか対応してないのかを整理して、必要なら対応を行うためのissueを立てたほうがよいのかも知れません。話題に出てませんが、たぶんハードリンク(win2k以降)にも完全には対応しとらんですよね・・・。

まぁフリーソフトだし対応したい人がすれば良いのではないかと考えています。自分はシンボリックリンクは便利さを感じて使ってますが、ハードリンクは使いどころが分からず使ってません。ハードリンクに関して完全どころか一部でも（サクラエディタが）対応しているのかさえ把握していません。

> まぁ、このissue自体はPRがマージできたら閉じて構わないと思ってます。

はい。PR の本文の関連チケットのところに `close #このIssue番号` と書いて自動的に閉じるようにしておきました。
