### ISSUE TITLE
Source-Code annotation language (SAL) の記述が正しいか確認する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#102]
Source-Code annotation language (SAL)

- https://github.com/sakura-editor/sakura/pull/51#issuecomment-394239753
- https://msdn.microsoft.com/ja-jp/library/hh916383.aspx
- https://msdn.microsoft.com/ja-jp/library/ms182032.aspx
- https://msdn.microsoft.com/en-us/library/ms182032.aspx
- https://blogs.msdn.microsoft.com/devschool/2013/09/09/ccx-source-code-annotation-language-sal/

**Comment by m-tmatma** [comment]
@berryzplus  さん

https://github.com/sakura-editor/sakura/pull/51#issuecomment-394239753
にコメント書かれているのがこのチケットの発端ですが、いかがですか?

検討する時間取れそうですか?

**Comment by berryzplus** [comment]
この issue の意図がよくわかってないんです。

https://github.com/sakura-editor/sakura/pull/51#issuecomment-394239753
のコメントの内容は、
既にSALが使われてる箇所があったんだけど、変数名間違ってるから機能してないね、
という話です。

個人的には Windowsプログラムでは SAL を使うのが「良識」だと思っています。
ただ、プロジェクトとして「SAL 必須」は、なんか違う気がします。
すでにあるSALの書き間違いを正すだけならやってもいいかもしれないです。

SALは関数についての付加情報をシグニチャに含めることを強要する仕組みです。
記述するのは面倒ですし、コードの見映えも悪くなる傾向です。
その代償として、VC++による静的解析を利用できるメリットを受けられるわけですが。

一律でやらないのであれば issue を立てて動く目的がよくわからんのです。

**Comment by berryzplus** [comment]
これ、閉じておきますね。

ちなみに発端となった「正しくないSAL」は、この commit で修正されました。
https://github.com/sakura-editor/sakura/commit/726fcd897a6de3d3feddb066e311b630c9a99e83#diff-0b3fdecc411692198516f23eca957b2c

その後、この commit でしれっと削除されてしまったため、継続して議論する余地がなくなってしまいました。
https://github.com/sakura-editor/sakura/commit/24641efd53b8717ef40f69c46ea9922f55b8af97#diff-0b3fdecc411692198516f23eca957b2c

なので、閉じます。
