### ISSUE TITLE
旧SFのオンラインヘルプのgithub.ioへのリダイレクト状況について

### ISSUE THREAD

**Issue by cugra** [sakura-editor/sakura#1024]
## 問題内容
旧V2ヘルプURL( http://sakura-editor.sourceforge.net/htmlhelp2/ )は
新ヘルプURL( https://sakura-editor.github.io/help/ )にリダイレクトされるのに、
旧V1ヘルプURL( http://sakura-editor.sourceforge.net/htmlhelp/ )はリダイレクトされません。

またここからは旧SF時代からの問題ですが、未だにGoogle等の検索エンジンで、
V2ヘルプではなくV1ヘルプが検索によく引っ掛かります。
V1はオンラインヘルプ公開を停止して、ヘルプファイルのダウンロード提供のみに
した方が良いと思います。

## 問題のカテゴリ
- ドキュメントの問題
- GitHub 関連の問題
- その他の問題

**Comment by berryzplus** [comment]
これ確か、 @kobake さんがやってたよな～と思いつつ、検索してみたら issue が残っていました。

https://github.com/sakura-editor/sakura-editor.github.io/issues/23 SourceForge の htmlhelp2 アクセスを GitHub Pages の領域へリダイレクトさせる
手順も全部残っていそう。

sourceforge.net の v1 ヘルプ領域へのアクセスを、
GitHub Pages の v2 ヘルプ領域に一律でリダイレクトする
という作業内容であれば、問題なく実施できそうです。

## 課題事項

- それでいいんだっけ？
  - Web上で v1 ヘルプにアクセスする方法がなくなりますが、それでいいんでしたっけ？
- 他に方法はないんだっけ？
  - Web上に v1 ヘルプを残しつつ、かつ、SourceForge.net のドキュメントが Obsolete であると知らせられる代替手段はないんでしたっけ？
    - やり方はいくらでもある気がします。
    - 全ページ `<H1>` タグの下に定型のメッセージ＋リンクを挿入するとか 。
    - 全ページ `<HEAD>` タグの中にリダイレクト用のスクリプトを仕込んで、javascript で「v1 ヘルプの内容は古くなっています。OKボタンをクリックすると、自動的に最新版ページ(GitHub Pages)に移動します。(Ok/Cancel)」とやるとか 。
- 誰がやれるんだっけ？
  - SourceForgeプロジェクトでAdminな人です。 ← @KENCHjp さん、 @kobake さん、 @m-tmatma さん
  - おいらは確か無理なはずです。 ← 把握してない :sob:

ここ最近の参加状況からすると、どうしたいかを確定させた上で @KENCHjp さんに適用作業をお願いする感じですね。

**Comment by cugra** [comment]
>Web上で v1 ヘルプにアクセスする方法がなくなりますが、それでいいんでしたっけ？
全く問題が無いとは言えませんが、未だにあえてV1系を使っている人はそれなりのITスキルがあると思いますので、
V1のURL跡地に、
https://sourceforge.net/projects/sakura-editor/files/help/
か
https://sourceforge.net/projects/sakura-editor/files/help/1.6.7.0/
へのリンクを残しておけば自分でヘルプファイルをダウンロードできるのではないでしょうか。

なお私が懸念しているのは、例えば「サクラエディタ ヘルプ 改行コードについて」でググった時に、
V1のヘルプしかヒットせずV2.1.0.0以降に導入されたNEL,LS,PSの情報が追加された方のヘルプにアクセスできないことです。

![Screenshot_20190901-214241_Chrome Dev](https://user-images.githubusercontent.com/39867484/64076749-a2b6dd80-cd03-11e9-8360-a8a38296d465.jpg)

**Comment by berryzplus** [comment]
困りごと(=懸念事項)的には、問答無用でv2側にリダイレクトさせたほうが都合が良さそうですね。

リダイレクト時にv1側からの転送であることを分かるようにしたら・・・

う～む、なんかメンドクサイ実装を入れなきゃいけない感じだとCHMソースとの兼ね合いがあるので実現可能性が下がっていきそうです。

そうすると、とりあえず v1(sf.net) ⇒ v2(GitHub Pages) の問答無用リダイレクトを仕込んで様子を見る感じになりそうな気配・・・というかきっとブレない。お願いできますか？　＞ @KENCHjp さん

**Comment by KENCHjp** [comment]
がんばります！

**Comment by KENCHjp** [comment]
私事ですが、今日から事務所が秋葉原から新川崎へ移動したのでバタバタしております。
作業すると週末になりそうですが、方向としては、

v1(sf.net)のページをv2(GitHub.Pages)へ問答無用リダイレクトして（help2と同じやり方）、
v2側のページになにがしかv1ヘルプ用のリンクを作っておくって感じですかね。

**Comment by KENCHjp** [comment]
>v2側のページになにがしかv1ヘルプ用のリンクを作っておくって感じですかね。

こっちについては、
https://sakura-editor.github.io/
ここにv1helpへのダウンロードリンクがあるから、特になにもしないでいいっすかね。
ならv1(sf.net)のリダイレクションをいじるのに集中します。

**Comment by berryzplus** [comment]
さよならメイド…:sob:

とりあえず、v1配下へアクセスされたら一律で一律でリダイレクトしとけばいいと思います。

そしたらgoogleの検索インデックスが更新されてくはず。

v1のファイルは消してもいいし残しといてもいいと思います。そこはリダイレクト解除を織り込むかどうかの違いかな、と。

**Comment by berryzplus** [comment]
なんか余計なこと書いて混乱させてしまってる気がするので補足です。

> v1(sf.net)のページをv2(GitHub.Pages)へ問答無用リダイレクトして（help2と同じやり方）、
> v2側のページになにがしかv1ヘルプ用のリンクを作っておくって感じですかね。

「help2と同じやり方」で大丈夫と思ってます。
リンクのほうは、その気になればダウンロードできるから作らなくてよいはずです。

**Comment by KENCHjp** [comment]
>さよならメイド…😭

そうなんす、行けずじまいでしたメイド、呼び込みメイドの目の保養も終了( ﾉД`)ｼｸｼｸ…

>とりあえず、v1配下へアクセスされたら一律で一律でリダイレクトしとけばいいと思います。

了解です！

**Comment by KENCHjp** [comment]
本件対応しました。
http://sakura-editor.sourceforge.net/htmlhelp/
http://sakura-editor.sourceforge.net/htmlhelp/HLP000030.html
にアクセスして各々
https://sakura-editor.github.io/help/
https://sakura-editor.github.io/help/HLP000030.html
こちらへリダイレクションされることを確認しました。

/home/project-web/sakura-editor/htdocs/.htaccess
を.htaccess.20190907にコピーしたのち、.htaccessに

```
# 2019/09/07 GitHub Issue https://github.com/sakura-editor/sakura/issues/1024
Redirect permanent /htmlhelp/ https://sakura-editor.github.io/help/
```
を追記。

/home/project-web/sakura-editor/htdocs/htmlhelp/
を
/home/project-web/sakura-editor/htdocs/htmlhelp.bk20190907/
へリネームしました。
とりあえずググってヘルプがうまく検索されるようになったらどなたか本Issueクローズおなしゃす。

**Comment by KENCHjp** [comment]
いま気づきましたが、

https://sakura-editor.github.io/help/

ヘルプのリンクが、SFになってますね。

**Comment by berryzplus** [comment]
> いま気づきましたが、
> https://sakura-editor.github.io/help/
> ヘルプのリンクが、SFになってますね。

このissueでやろうとしていた内容、という認識です。
https://github.com/sakura-editor/sakura-editor.github.io/issues/47

@m-tmatma さんが忙しくなってしまったみたいなので放置中ですが、どっかで対応せにゃならんと思っとります。っていうか、誤植とか放置状態なのでｗ

**Comment by KENCHjp** [comment]
了解です。
誤植もそうですが、バージョンアップにヘルプ追随させるのはやっぱり専属の人ほしいっすよねぇ。

**Comment by KENCHjp** [comment]
「サクラエディタ ヘルプ 改行コードについて」でググって、github側のヘルプが一番上にヒットするようになったので、閉じます！
![キャプチャ](https://user-images.githubusercontent.com/39618965/71426849-e2129b00-26f3-11ea-9f9c-ec384de5308c.PNG)
