### ISSUE TITLE
タイプ別カラー一覧の色指定リストの背景色の範囲がDPI未対応

### ISSUE THREAD

**Issue by usagisita** [sakura-editor/sakura#1031]
## 問題内容

タイプ別設定のカラー、色指定リストの背景色がDPI変更に未対応で色の幅がおかしいです。
2018/09/30の dd0b3177 の考慮漏れだと思います。

## 再現手順
DPIを100%以外にします。
タイプ別設定のカラータブを表示します。
「テキスト」などの水色の背景色が文字色の部分に掛かっています。

## 再現頻度
DPIを100%以外にすれば、100%

## 問題のカテゴリ
- プログラムの動作上の問題

## 環境情報
- OS バージョン
Windows 8.1 Home 64bit
- サクラエディタバージョン
v2.4.0.2214 32bit dev
- PC情報
特になし
## スクリーンショット

![タイプ別設定カラータブ](https://user-images.githubusercontent.com/40428610/64078270-7440fe80-cd13-11e9-816b-63525d1d4e82.png)

**Comment by berryzplus** [comment]
#499 を見ればいいですね(自己解決

**Comment by berryzplus** [comment]
この問題の対処はどんな感じですか？

#499 のbefore / after のキャプチャに、既にこのissueで指摘されてる現象が出ています。

気付かずにapproveしといてアレですが、言われてみれば「ああ、そうね。」です。

直すのは多分簡単なんだけど説明するのがめんどくさい感じです。

**Comment by berryzplus** [comment]
一番簡単に直せる方法でPR作ってみました。

**Comment by berryzplus** [comment]
これ、結局対処しとらんですね。対応要です。
