### ISSUE TITLE
Unicode一本化対応の残課題を拾い集めてissueを立てる

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1038]
（自由記述）

## 目的
#1034 でもらった指摘のうち、いくつか対応を見送ったものがあります。
せっかくなので対応していきたいんですが、漏れそうなので
とりあえず「タスクを拾い上げる」の issue を立ててみます。

## 拾い上げたタスク
拾ったタスクは、PRかissueを作ってそちらに引き継いでいきます。
(ここは後で更新していく予定)

## 完了条件
タスクを拾い切ったら終わり。

**Comment by berryzplus** [comment]
とりあえず拾うだけ拾ってみました。


- https://github.com/sakura-editor/sakura/pull/1034#discussion_r321993414
  - TCHAR 使ってるところは全て wchar_t に置き換える ⇒ 完了
  - WindowsAPI の呼び出しは wchar_t* 渡しているところではマクロ経由では無く W 系を直接呼ぶようにする ⇒ 保留
- https://github.com/sakura-editor/sakura/pull/1034#issuecomment-529240638
  - mingw の build に失敗していて、_wcstok が無いみたいです。wcstok はあるっぽいですが。 ⇒ 完了
  - プラットフォームの違いを吸収するプリプロセッサマクロを置くヘッダファイルがどこかにあればそこにマクロ追加するのが良いと思います。 ⇒ 保留
- https://github.com/sakura-editor/sakura/pull/1034#discussion_r322030660
  - 実行ファイル名の末尾の数字で編集する文字コード種別を設定する機能が有る事を初めて知りました…。
    - ヘルプに記載するか、要らない機能として削るか要検討だと思います。
- https://github.com/sakura-editor/sakura/pull/1034#discussion_r322494951
  - 多言語対応の事を考えるとエラーメッセージもリソース文字列から取得するべきな気がします。 ⇒ 保留
- https://github.com/sakura-editor/sakura/pull/1034#issuecomment-530024854
  - 変なマクロ見付けました。 ⇒ 保留
- https://github.com/sakura-editor/sakura/pull/1034#pullrequestreview-286831231
  - TcharReceiver クラスですが継続して使う必要は有るのでしょうか？もし無いのであればこの機会に削ってしまうのが良いと思いました。
    - 対応済みですが、tcharの名前が付くファイルが他にもある気がします。そのあたりの精査が未実施なので要検討だと思います。
- https://github.com/sakura-editor/sakura/pull/1034#issuecomment-530463871
  - auto_ 系のオーバーロードされた関数 ⇒ 保留
  - W系のWindowsAPIの呼び出しに変える ⇒ 保留

**Comment by berryzplus** [comment]
そのまま issue 立てられる感じの簡単な話題があんまりなくて、どうしようか悩み中。
閉じずに残しておけば、そのうち「対応する/対応しない」を整理するときが来るんではないかと思うのでしばらく放置する感じでいきます。

**Comment by cugra** [comment]
> * [#1034 (comment)](https://github.com/sakura-editor/sakura/pull/1034#discussion_r322030660)
>   
>   * 実行ファイル名の末尾の数字で編集する文字コード種別を設定する機能が有る事を初めて知りました…。
>     
>     * ヘルプに記載するか、要らない機能として削るか要検討だと思います。

ヘルプに記載が無いのは知りませんでしたが以前からWikiに使い方が書かれているので、
機能削除すると困る人が少しはいるかもしれません。
http://sakura.qp.land.to/?FAQ%2F51
http://sakura.qp.land.to/?%A5%B3%A5%DE%A5%F3%A5%C9%A5%E9%A5%A4%A5%F3%A5%AA%A5%D7%A5%B7%A5%E7%A5%F3

**Comment by beru** [comment]
> > * [#1034 (comment)](https://github.com/sakura-editor/sakura/pull/1034#discussion_r322030660)
> >   
> >   * 実行ファイル名の末尾の数字で編集する文字コード種別を設定する機能が有る事を初めて知りました…。
> >     
> >     * ヘルプに記載するか、要らない機能として削るか要検討だと思います。
> 
> ヘルプに記載が無いのは知りませんでしたが以前からWikiに使い方が書かれているので、
> 機能削除すると困る人が少しはいるかもしれません。
> http://sakura.qp.land.to/?FAQ%2F51
> http://sakura.qp.land.to/?%A5%B3%A5%DE%A5%F3%A5%C9%A5%E9%A5%A4%A5%F3%A5%AA%A5%D7%A5%B7%A5%E7%A5%F3

それじゃあ削除しないで残しておく方が良いかもですね。
ヘルプに記載を追加するのはタスクとしてどっかに積んでおいて…（しばらくすると忘れる）。

**Comment by berryzplus** [comment]
#1081 でコマンドライン解析のテストを書いてみて思ったんですが、現状のコードだと「ファイル名から文字コードを判別する機能」が正しく動いていることを保証するテストが書きづらいんですよね。

- 現状の構造
  - 指定したコマンドラインからオプションを解析する処理の内部でファイル名を取得し、コード番号が含まれていたら文字コードを設定する
- 理想的（？）な構造
  - コマンドライン解析とファイル名解析を分けて、文字コード指定の優先度を明確にする
  - コマンドライン解析を呼び出すと、常にファイル名解析が実行されてしまうので、パフォーマンス的に不利になっています。
  - ファイル名解析部分を外出しにすれば、ファイル名解析の妥当性を単体で検証できるようになります。

とりあえず、まだすぐに何かをする感じの話じゃないですけど。

**Comment by berryzplus** [comment]
対応する目途がないのでいったん閉じてしまいます。
