### ISSUE TITLE
[改善要望] Windows 10 のスタートメニューに対応してほしい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#104]
## 目的
サクラエディタを windows 10 で使うときの利便性を向上させる。

## 経緯
インストーラでインストールしたサクラエディタを、
スタートメニューから見付けられない人を見かけた。
windows 10 のスタートメニューを眺めてみると、
実行ファイルを起動するリンクが直接並べてあるものが多い。
他アプリの起動になれた人にとっては確かに探しづらいかもしれないと感じた。

## 問題
windows 10 ではスタートメニューの表示方法が変わったので従来通りだと少し合わない。
![2018-06-11 4](https://user-images.githubusercontent.com/3253151/41237788-ebe8b1ee-6d83-11e8-9b2f-b76136be21d1.jpg)

## 対応策
インストーラにwindowsのバージョン判定を仕込み、
win10の場合だけスタートメニュー作成方法を変えるようにする。

## 担当メンバー
* 時間がとれる人
* windows scripting host の script が書ける人
* Inno Setup 5(pascal script)を 修正できる人
  **立候補歓迎です** :smile:

## 実施時期
x64対応が落ち着いてから開始。

**Comment by KENCHjp** [comment]
画像が張ってあるスタートメニューにあまり違和感がないのですが(すいません)、

サクラエディタ（フォルダ）
　サクラエディタ
　設定フォルダ
　ヘルプファイル

となっているのを具体的にはどうなったらWindows10っぽいんでしょうか。

サクラエディタ
サクラエディタ（フォルダ）
　設定フォルダ
　ヘルプファイル

こう？

**Comment by berryzplus** [comment]
> サクラエディタ
> サクラエディタ（フォルダ）
> 　設定フォルダ
> 　ヘルプファイル

基本そのイメージで合ってます。

どうも、文字ではなくアイコンで探してるっぽいので
フォルダアイコンでなくアプリアイコンを上に出すようにできないかと考えています。

**Comment by berryzplus** [comment]
この状態をサクラエディタと認識できないっぽいことへの対策。
![2018-06-11 3](https://user-images.githubusercontent.com/3253151/41259841-9cb3c6b8-6dc4-11e8-8e8a-4eaaea15243d.jpg)

**Comment by KENCHjp** [comment]
一応三点該当してますが能力が伴うかとGitHub超不慣れが足かせ。
一つ質問ですがWSHはなぜに必要なのでしょう？

**Comment by berryzplus** [comment]
WMI経由でバージョンチェックするためです

**Comment by KENCHjp** [comment]
ScriptにGetWindowVersionEx関数がありますが、これ例の偽装さてるってやつでしたっけ？
インストーラーも偽装される？

**Comment by berryzplus** [comment]
Windows apiのgetversionexと内部で繋がってるなら同じ挙動になる認識です。2ケタのバージョン番号が返ると困るアプリのための思いやり仕様と認識しております。

Manifestでwin10対応を埋め込んであげれば回避できる認識ですが、せっかくなのでwmiで取得するケースを作っておきたいという願望的な動機です。

**Comment by m-tmatma** [comment]
インストーラの知識があるのであれば、
#67  、Appveyor  対応、およびインストーラ構築に
必要な手順の文章化もお願いしたいです。

**Comment by m-tmatma** [comment]
#106 も要ります。

**Comment by KENCHjp** [comment]
berryzplus さん、インストーラーの挙動の話にまず限定しませんか？
インストーラー挙動であればgetversionex使うのに問題があるようにおもえないのですが。
逆に偽装を意図的にされた場合はそのように振る舞えばいいだけのようにおもうのですがいかがでしょう？

WMIについてはそんなに難しくないかとおもうので調べれるかとおもいますが、Innoの中のPascalで呼ぶ方法を見つけてもC++に貢献できる気があまりしないのですがいかがでしょう？（笑）

なんか勘違いしてますか？

**Comment by KENCHjp** [comment]
m-tmatma さん

インストーラーについては技術的な面と各リポジトリのバイナリとスタティックなコンテンツをどう管理していくかの話が中心なのかなと思いますが、一旦運用のたたきみたいなのまとめてみましょうか。

Appveyor 対応は私のスキル不足のハードル高そうですが、いい機会なのでインストーラーのリソースもすくないし初brunchでも切ってみようかなと。。。できるかなぁ（笑）

**Comment by KENCHjp** [comment]
>なんか勘違いしてますか?
やっぱ勘違いしてるのはわたしのようですね。
マニフェストがないとまともにWindows10かどうかわからない話ってことですかね。
であるならば、インストーラーは別な方法でWindows10かどうか調べないといけないってことですね
失礼しました。

**Comment by berryzplus** [comment]
> インストーラーの挙動の話にまず限定しませんか？

すみません。勘違いしてるのぼくのほうかもしれません。

インストール時に「jsとかvbsなどの外部スクリプトを呼び出すのは簡単」だと思ってました。
inno setupについてはサンプルをベースに少し作ってみたことがあるくらいで詳しくはないです。

バージョンがwindows10の場合の挙動を変えたいので、
バージョン6とか返ってくるのだとするとまずいです。
一度、普通の方法で試してみたいんですが、お願いできますか？

**Comment by KENCHjp** [comment]
>インストール時に「jsとかvbsなどの外部スクリプトを呼び出すのは簡単」だと思ってました。

出来なくはないと思いますが、インストーラーってExe単体でうごかすじゃないっすかぁ。インストーラーと外部VBSおとせっとは格好わるいし。
exe実行して外部ファイルつくってうごかすのもなぁと。

WMI動かす手段はあると思うので挙動含めやってみますね。
新しいWIPか#67に状況ぶら下げたほうがいいかしら。。。

**Comment by m-tmatma** [comment]
> インストーラーについては技術的な面と各リポジトリのバイナリとスタティックなコンテンツをどう管理していくかの話が中心なのかなと思いますが、一旦運用のたたきみたいなのまとめてみましょうか。

少しずつできるところからやっていけばいいと思います。
外部モジュールの管理方法に関しては #81 のチケットを作っています。

> appveyor 対応は私のスキル不足のハードル高そうですが、いい機会なのでインストーラーのリソースもすくないし初brunchでも切ってみようかなと。。。できるかなぁ（笑）

メンバーが知っていることであれば教えられますし、
全員が知っていなくても  https://github.com/appveyor/ci/issues で質問できます。
英語に抵抗があれば、代理で質問してもいいです。

**Comment by m-tmatma** [comment]
@KENCHjp  さん

> m-tmatma さん

特定のユーザに対してコメントする場合はユーザー名の先頭にアットマークをつけて
送るようにするとそのユーザーに通知が行くようになるので便利です。
(自動的にユーザーの選択肢が出てきます。この一覧にない人の場合は直接入力すれば OK です)

コメントを書く欄の上のところで右から二番の アットマークを押しても同様です。

https://blog.github.com/2011-03-23-mention-somebody-they-re-notified/

**Comment by KENCHjp** [comment]
@m-tmatma さん　＆　皆さん

いろいろ有難うございます。
スマホからだと今一歩うまく行かなくて、ぼちぼちやっていきます。

**Comment by k-takata** [comment]
Inno Setupは使ったことがないのですが、公式の履歴によると、5.5.6からWin10用のmanifestが含まれているようですね。
http://jrsoftware.github.io/issrc/whatsnew.htm

**Comment by KENCHjp** [comment]
@k-takata さんまじすか。
こりゃ本腰っすね。

**Comment by KENCHjp** [comment]
@berryzplus さん、出来たんですけど、
![win10](https://user-images.githubusercontent.com/39618965/41505046-cbe47e80-723a-11e8-8e30-7202e47d83f5.png)
↑こうなるんですが、いいっすかね？

**Comment by KENCHjp** [comment]
クローズでいいすか？

**Comment by berryzplus** [comment]
> クローズでいいすか？

OKです。ご対応ありがとうございました。
