### ISSUE TITLE
githash.h が無いためにローカルビルドが失敗します。

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#1041]
## 問題内容
最近のサクラエディタを体験してみようと思ってローカルビルドを試したら、githash.h が無いためにローカルビルドが失敗します。

## 再現手順
1. TOPページから `Download ZIP` をクリックして zipファイルを適当な場所にダウンロードします。
![image](https://user-images.githubusercontent.com/11251874/64922159-f39bfb00-d806-11e9-98a5-b96c60a02fe3.png)
2. ダウンロードしたzipファイルを適当に展開します。
3. Visual Studio 2017 を起動します。
4. 展開したフォルダから `sakura.sln` を Visual Studio 2017 で開きます。
5.  `sakura.sln` を読み込み終わったら `Ctrl + F5` でビルドを開始します。
6. ビルドに失敗します。

> 3>x:\github-sourcecodes\sakura-editor\sakura-master-2019-0915\sakura_core\version.h(5): fatal error C1083: include ファイルを開けません。'githash.h':No such file or directory (ソース ファイルをコンパイルしています ..\sakura_core\_main\WinMain.cpp)
> 3>CDropTarget.cpp
> 3>プロジェクト "sakura.vcxproj" のビルドが終了しました -- 失敗。
> ========== ビルド: 2 正常終了、1 失敗、0 更新不要、0 スキップ ==========

![image](https://user-images.githubusercontent.com/11251874/64922268-4de98b80-d808-11e9-84b0-29edca07892e.png)

## 再現頻度
100％

## 問題のカテゴリ

- ビルドの問題
  - ローカルビルド

## 環境情報
- OS バージョン
  Windows 10 Pro 64bit
- Visual Studio のバージョンは 2017 Community です。

**Comment by berryzplus** [comment]
すみません。zip版でやってる人はいないのでメンテされてないです。

zip版からビルドするには、コマンドラインからgithash.batを実行する必要があります。

```cmd
sakura\githash.bat .\sakura_core
```

ドキュメント更新せにゃならんですが、放置気味です。

トラブルなしでやりたい場合はgit cloneでやるのがおすすめです。

**Comment by arigayas** [comment]
> 
> 
> すみません。zip版でやってる人はいないのでメンテされてないです。
> 
> zip版からビルドするには、コマンドラインからgithash.batを実行する必要があります。
> 
> ```batchfile
> sakura\githash.bat .\sakura_core
> ```
> 
> ドキュメント更新せにゃならんですが、放置気味です。
> 
> トラブルなしでやりたい場合はgit cloneでやるのがおすすめです。

報告です。
> X:\GitHub-SourceCodes\Sakura-Editor\sakura-master-2019-0915\sakura>githash.bat .\sakura_core
> 
> ---- Make githash.h ----
> find-tools.bat
> |- CMD_GIT=C:\Program Files\Git\cmd\git.exe
> |- CMD_7Z=C:\Program Files\7-Zip\7z.exe
> |- CMD_HHC=
> |- CMD_ISCC=
> |- CMD_CPPCHECK=
> |- CMD_DOXYGEN=
> |- CMD_VSWHERE=C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
> |- CMD_MSBUILD=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\amd64\MSBuild.exe
> |- CMD_CMAKE=C:\Program Files\CMake\bin\cmake.exe
> end
> NOTE: No .git directory
> checking GIT_SHORT_COMMIT_HASH, GIT_COMMIT_HASH
> 指定されたパスが見つかりません。
> GIT_SHORT_COMMIT_HASH :
> GIT_COMMIT_HASH       :
> TEMP_GIT_SHORT_COMMIT_HASH :
> TEMP_GIT_COMMIT_HASH       :
> GIT_REMOTE_ORIGIN_URL :
> GIT_TAG_NAME          :
> APPVEYOR_URL          :
> APPVEYOR_REPO_NAME    :
> APPVEYOR_ACCOUNT_NAME :
> APPVEYOR_PROJECT_SLUG :
> APPVEYOR_BUILD_VERSION:
> APPVEYOR_BUILD_NUMBER :
> GITHUB_COMMIT_URL           :
> GITHUB_COMMIT_URL_PR_HEAD   :
> APPVEYOR_SHORTHASH_PR_HEAD  :
> APPVEYOR_BUILD_URL          :
> 指定されたファイルが見つかりません。
> .\sakura_core\githash.h was updated.

バッチファイルを実行してビルドをしてみましたが、
上記のスクリーンショットと同じエラーになりました。
`include ファイルを開けません。'githash.h':No such file or directory`

**Comment by berryzplus** [comment]
すみません。言葉が足りませんでした。

> X:\GitHub-SourceCodes\Sakura-Editor\sakura-master-2019-0915\sakura>githash.bat .\sakura_core

これが原因です。

> `X:\GitHub-SourceCodes\Sakura-Editor\sakura-master-2019-0915\sakura>githash.bat ..\sakura_core`

とするか

> `X:\GitHub-SourceCodes\Sakura-Editor\sakura-master-2019-0915>sakura\githash.bat .\sakura_core`

で試してみてください。

**Comment by berryzplus** [comment]
いまのtestプロジェクトはgit環境でのビルドを前提にしているため、
tests1.vcxprojのビルドは必ず失敗するので設定マネージャで無効にしたらよいと思います。

**Comment by arigayas** [comment]
ビルド出来ました！
![image](https://user-images.githubusercontent.com/11251874/64924026-0caea700-d81b-11e9-9092-83c7c0fc21c1.png)

> X:\GitHub-SourceCodes\Sakura-Editor\sakura-master-2019-0915\sakura>githash.bat ..\sakura_core
> 
> ---- Make githash.h ----
> NOTE: No .git directory
> checking GIT_SHORT_COMMIT_HASH, GIT_COMMIT_HASH
> GIT_SHORT_COMMIT_HASH :
> GIT_COMMIT_HASH       :
> TEMP_GIT_SHORT_COMMIT_HASH :
> TEMP_GIT_COMMIT_HASH       :
> GIT_REMOTE_ORIGIN_URL :
> GIT_TAG_NAME          :
> APPVEYOR_URL          :
> APPVEYOR_REPO_NAME    :
> APPVEYOR_ACCOUNT_NAME :
> APPVEYOR_PROJECT_SLUG :
> APPVEYOR_BUILD_VERSION:
> APPVEYOR_BUILD_NUMBER :
> GITHUB_COMMIT_URL           :
> GITHUB_COMMIT_URL_PR_HEAD   :
> APPVEYOR_SHORTHASH_PR_HEAD  :
> APPVEYOR_BUILD_URL          :
>         1 個のファイルを移動しました。
> ..\sakura_core\githash.h was updated.

Closeでしょうか？
それともドキュメントが更新されるまでCloseしない感じでしょうか？

判断はお任せします。

**Comment by berryzplus** [comment]
> Closeでしょうか？

Closeでいいと思います。

ドキュメントの置き場所は2箇所あります。
PR⇒approve⇒マージの手順が要る場所と、手順が要らない場所です。

- [build.md](https://github.com/sakura-editor/sakura/blob/master/build.md) 
  - PRしてapproveもらってマージが必要。
- [SAKURA editor wikiページ](https://github.com/sakura-editor/sakura/wiki)
  - 書いたら即反映される。

個人的には「ドキュメントが置いていかれる主原因」はコレだと思っています。
・ドキュメント修正とコード修正では、PR作成に必要なスキルセットが違う。
・ドキュメント修正とコード修正では、レビューに必要なスキルセットが違う。
・ドキュメント修正にはレビューが必要だが、機能を変更しない修正は必要性や妥当性の検証がしづらいのでスルーされてしまう。

ドキュメントは、有志が勝手に編集して、なんかおかしいところがあったら適宜修正する、というスタイルでもいいような気がします。

で、今書いた内容は、PRの趣旨とはまったく関係ないので、やっぱりCloseでいいんじゃないかと思います。

**Comment by berryzplus** [comment]
ドキュメント用の画像を貼ります。

![2019-09-16 (1)](https://user-images.githubusercontent.com/3253151/64934379-5df38080-d885-11e9-85bf-30de6c739095.png)

![2019-09-16 (2)](https://user-images.githubusercontent.com/3253151/64934382-65b32500-d885-11e9-9000-89e4b03022f6.png)

![2019-09-16 (3)](https://user-images.githubusercontent.com/3253151/64934385-6c419c80-d885-11e9-8a37-16cd11c656a2.png)

![2019-09-16 (4)](https://user-images.githubusercontent.com/3253151/64934391-71065080-d885-11e9-836a-47b31550cf19.png)

**Comment by berryzplus** [comment]
うーむ。後回し！ 😭 
wikiのほうにドキュメント書いて、書き終わったらCloseするつもりです。

**Comment by arigayas** [comment]
> うーむ。後回し！ 😭
> wikiのほうにドキュメント書いて、書き終わったらCloseするつもりです。

了解しました。

**Comment by berryzplus** [comment]
一応書いたので閉じます。
https://github.com/sakura-editor/sakura/wiki/How-To-Build

**Comment by arigayas** [comment]
ページ作成お疲れさまでした。
