### ISSUE TITLE
DEBUGのUSE_LEAK_CHECK_WITH_CRTDBGを有効にするとコンパイルエラー

### ISSUE THREAD

**Issue by usagisita** [sakura-editor/sakura#1045]
## 問題内容
build_config.hの`#define USE_LEAK_CHECK_WITH_CRTDBG` を有効にすると
`new (std::nothrow)` などの記述がマクロ展開に失敗してコンパイルエラーになります。
しかし、最近追加されたcomコンポーネント操作関連のクラスで依然エラーがでるので、もう使いようがない気がします。

## 再現手順
デバッグビルドでbuild_config.hでUSE_LEAK_CHECK_WITH_CRTDBGのコメントアウトを外して#defineで定義します。

## 再現頻度
100%

## 問題のカテゴリ

- ビルドの問題
  - ローカルビルド

## 環境情報
- OS バージョン
無関係
- サクラエディタバージョン
無関係、github移行後いつからか
- PC情報
無関係

メモリーリークを追跡できる、簡単な代替方法があれば、それでもかまいません。
どこかのドキュメントにさらっと書いてあると、なおうれしいです。
VS 2017にはCommunityでもメモリーリーク検出などができる機能があるらしいということは小耳にはさみました。

**Comment by beru** [comment]
Visual Leak Detector は新しめのVisual Studio への対応がいまいちっぽいですね。。
https://social.msdn.microsoft.com/Forums/vstudio/en-US/2757577d-923b-4c35-9500-fb44ee60aee4/what-happened-to-vld?forum=visualstudiogeneral

**Comment by berryzplus** [comment]
> build_config.hの#define USE_LEAK_CHECK_WITH_CRTDBG を有効にすると
> new (std::nothrow) などの記述がマクロ展開に失敗してコンパイルエラーになります。

これは、どうすべきなんですかね？

issueを素直に読むと `new(std::nothrow)` をやめたい、に取れます。
使えていた開発環境の機能が使えなくなったのだから、
revertしてくれ、というのは分かる気がします。
ただ、「 `new(std::nothrow)` をやめる≒現代のC++規格を使わない」だと思います。

C++を使うな、は流石にイヤなので、別の解決策を探ることになります。
なんとかしてリークチェックを使えるようにする方法を考えてみます。

ビルドエラーの原因はこの部分です。
https://github.com/sakura-editor/sakura/blob/8b1f784c67c14d56f19411e690a6905181039e6f/sakura_core/config/build_config.h#L98-L100

「これが原因」と言われれば、少し気がラクになります。[大昔のVC++6.0](https://stackoverflow.com/questions/521133/are-define-new-debug-new-and-undef-this-file-etc-actually-necessary) で開発したことがある人なら分かるかも知れません。コードにいくつか不審点があって、「元々やり方がマズいんじゃないか？」と予想できるからです。

不審点
- 普通は独自定義したクラスのcppに書くべきマクロ定義を、共通ヘッダーで行っています。これは、自分達が作ったコード以外のinlineコードにも影響を与える書き方なのでよろしくないです。今起きているビルドエラーの問題は、まさに自分達が作ってないコードに影響を与えてしまった結果でもあります。
- MSVCRTDのメモリアロケーション関数には強力なデバッグ機構が備わっています。本来、_malloc_dbgというデバッグ版関数が存在しているので、自前で書くならnewのオーバーロードではなく_malloc_dbgを呼ぶべきなんじゃないかと思います。

というか、[MSVCRTDを使ったメモリリークの検出方法](https://docs.microsoft.com/en-us/visualstudio/debugger/finding-memory-leaks-using-the-crt-library) は、公式ドキュメントに具体的に解説されている内容です。端的にいって、build_config.hの記載は間違っていると思います。

以上のモロモロを踏まえて、総合的にどうすべきか・・・・

とっととPR出せよ、と言われそうな気がしないでもないですが、どう考えますか？

**Comment by usagisita** [comment]
使えるようになるならなるで、それならうれしいです。
一応要望としては、そっちはなかばあきらめていて「代替案の募集」です。あと結局使えないなら、オプションの削除です。

**Comment by beru** [comment]
> Visual Leak Detector は新しめのVisual Studio への対応がいまいちっぽいですね。。
> https://social.msdn.microsoft.com/Forums/vstudio/en-US/2757577d-923b-4c35-9500-fb44ee60aee4/what-happened-to-vld?forum=visualstudiogeneral

Visual Leak Detector v2.5.1 ですが問題無く VS2017 で使えました。
昔からあるCRTのデバッグ機能と比べて大分快適です。

**Comment by berryzplus** [comment]
> 使えるようになるならなるで、それならうれしいです。

#1051 のマージにより、使えるようになりました。
現状、起動して終了するだけならメモリリークを起こさないようなので、
検証コードを入れないと効果を見ることはできないんですけど :smile:

> Visual Leak Detector v2.5.1 ですが問題無く VS2017 で使えました。
> 昔からあるCRTのデバッグ機能と比べて大分快適です。

Visual Leak Detector の話は、使ったことがないのでよく分からんです。
[chocolatey パッケージが存在する](https://chocolatey.org/packages/visualleakdetector) ようなので「えいやっ！」で組み込んでしまうのもアリかもしれません。

こんな感じで ExecutablePath を定義してやれば、 https://social.msdn.microsoft.com/Forums/vstudio/en-US/2757577d-923b-4c35-9500-fb44ee60aee4/what-happened-to-vld?forum=visualstudiogeneral の手順を msbuild に組み込むことも可能だと思います。
https://github.com/sakura-editor/sakura/blob/08298ea30b26241b6b19617342e4f4f70e908677/tests/googletest.targets#L5-L6

変更内容がちょっとめんどくさそうなので、当座「そういうやり方もある」を心に留め置く感じかなぁ・・・と思っています。

閉じるかどうかの判断は丸投げします :smiley:

**Comment by usagisita** [comment]
対処、ありがとうございます。Closeしておきます。

**Comment by beru** [comment]
> Visual Leak Detector の話は、使ったことがないのでよく分からんです。

https://kinddragon.github.io/vld/
のページにリンクが張られているインストーラーをDLしてインストール後に
https://github.com/KindDragon/vld/releases/download/v2.5.1/vld-2.5.1-setup.exe

sakura プロジェクトのプロパティの VC++ Directories の Include Directories に下記のパスを追加します。
`C:\Program Files (x86)\Visual Leak Detector\include`

その後プロジェクト内のどれか一つの cpp ファイルに下記の記述を追加します。
```cpp
#include <vld.h>
```

あとはリークするコードをどこかに試しに仕込んでビルドしてから実行して終了すると、開発環境の Output ウィンドウにメモリリーク情報のレポート出力が行われます。

> [chocolatey パッケージが存在する](https://chocolatey.org/packages/visualleakdetector) ようなので「えいやっ！」で組み込んでしまうのもアリかもしれません。

ビルドプロセスが重くなるのは個人的に嫌です…。
