### ISSUE TITLE
HTML Help のビルドを appveyor で行う

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#106]
HTML Help のビルドが　appveyor でできるか調べる

**Comment by berryzplus** [comment]
実行ファイルの名前は hhc.exe 。配布パッケージ名は HTML workshop 1.3 なはず。
appveyor の tool list には含まれていないようです。

インストールされてるかどうかは不明ですね・・・
https://code.launchpad.net/~tomasgroth/openlp/packaging-appveyor-update/+merge/323635
https://github.com/urho3d/Urho3D/issues/910

実験してみて動くのであれば使えるのかもです。
存在しない場合、インストールするのは無理そう。（UAC制御ありのインストーラになってたはず）

**Comment by m-tmatma** [comment]
聞いてみました。
appveyor/ci#2439

**Comment by m-tmatma** [comment]
質問しましたが、インストールされてました。
https://ci.appveyor.com/project/m-tmatma/sakura/build/1.0.96/job/uyrot8hnqlpfdsw8

確認してから質問したら良かった。

**Comment by m-tmatma** [comment]
以下でコンパイルできました。

"C:\Program Files (x86)\HTML Help Workshop\hhc.exe" help\macro\macro.HHP
"C:\Program Files (x86)\HTML Help Workshop\hhc.exe" help\plugin\plugin.hhp
"C:\Program Files (x86)\HTML Help Workshop\hhc.exe" help\sakura\sakura.hhp

簡単なのでやってしまいます。

**Comment by kobake** [comment]
おおお。よろしくお願いします！

**Comment by m-tmatma** [comment]
#123 で対応しました。

ハマりどころは hhc は成功すると 1 を返して、失敗すると 0 を返す。
なんでやねん。

**Comment by kobake** [comment]
hhc の謎流儀……(´Д｀)

ご対応ありがとうございました！

**Comment by KENCHjp** [comment]
>ハマりどころは hhc は成功すると 1 を返して、失敗すると 0 を返す。

だれが作ったんやそのコマンド。。。
