### ISSUE TITLE
[保留中] windows7 の AeroSnapに対応させる

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#107]
## 目的
windows7 の AeroSnapに対応させる。

## 経緯
タブを表示中のサクラエディタをエアロスナップさせた状態で、
別のタブに切り替えるとエアロスナップが解除されてしまう。

関連するissues
#45, #47, #65 

当初は、過去の貢献者が残した暫定パッチを取り込むつもりのPRを作成したが、
何も手を加えずに取り込むことが難しいことを認識したので方針を転換し、
わたし ( @berryzplus ) が代理コミットについて一旦レビューを行い、
修正コミットを積んだうえで再度 PR を行うこととしました。

## 対応予定について
少し時間をかけてレビュアーと仮想レビュイーの自作自演のやり取りを行った後、
最終的にberryzplusがコミットできると判断した時点でタイトルのWIPを外します。
今週いっぱいくらいかけるつもりです。
　↓
思考過程を紹介できるほど余裕がなかったので、
単純にぼくが修正した内容についてコメントしただけのPRになってしまいました。
ようやくレビュー可能な状態(=ぼくがOK出せる状態)にできたので、
このissueはそちらが完了次第閉じようと思います。

よろしくお願いします。

**Comment by berryzplus** [comment]
> Issue に WIP 付ける慣習ってありましたっけ。

了解です。今回は両方につけます。
よろしくお願いします。

**Comment by beru** [comment]
こちらもう PR 作成されていますか？
WIP でも良いので忘れないうちに上げておいていただけると機能が入る可能性が高まると思うのでありがたいです。

**Comment by berryzplus** [comment]
作成してPRして、誰もレビュしてくれないもんでwin10でしばらく動作確認してたら、想定しない現象が起きました。

で、よくよく調べてみたらその現象はwindowsバージョンの違いによって起きているらしいことがわかりました。さらに、どうも起動遅延の原因の１つが、エアロスナップ対応にも影響を与えてそうなことが分かりました。

対応を完遂するには、大規模変更に寛容な空気作りが必須と考えています。あとはコードじゃなくアプリ仕様を把握できるような何かが必要です。

とりあえず、不具合系の対応で最優先と考えてるのは桁数取得マクロの話で、不具合対応を口実に心臓部をx64 readyにしてしまいたいと考えております。

**Comment by beru** [comment]
あ、 #120 がそうでしたか。すでにPR作られてたんですね。失礼しました。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394
