### ISSUE TITLE
プログラム起動時に assert が発生する

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#1073]
## 問題内容

https://github.com/sakura-editor/sakura/commit/9ef3305a5f3027a0f591b72f7419f9fc2e95886c#commitcomment-35453908  で @oooonduke さんが報告してくれた問題です。

プログラム起動時に下記の内容のメッセージボックスが表示されます。

```
---------------------------
sakura
---------------------------
assert
d:\projects\sakura\sakura_core\doc\cdoclistener.cpp(132):
pcDoc
---------------------------
OK   
---------------------------
```

## 再現手順
- ビルドする
- 起動する

## 再現頻度
毎回

## 問題のカテゴリ
- プログラムの動作上の問題

## スクリーンショット

問題発生時のコールスタック<br>
![image](https://user-images.githubusercontent.com/1131125/66648915-cad11f00-ec67-11e9-899d-f9d055e70d86.png)

## 関連PR

#1070

**Comment by berryzplus** [comment]
動作確認してないのがバレバレですね。
これは申し訳ない。

めげずに後続の改善案を提案していく所存です。

**Comment by beru** [comment]
#1074 が merge されたので close します。
