### ISSUE TITLE
ヘルプのPNGのファイルサイズが無駄に大きい

### ISSUE THREAD

**Issue by Rukoto** [sakura-editor/sakura#1083]
## 問題内容
- ヘルプのPNGのファイルサイズが無駄に大きい
- ComCustmenu.pngはそもそもPNGじゃない

## 問題のカテゴリ
- ドキュメントの問題

## 詳細な説明
無劣化・表示が同一・ファイルサイズ削減可能の3点を満たす51個のPNGファイルについて、
以下のアプリケーションを順番に用いて目一杯最適化してサイズダウンしました。
・optipng Ver.0.7.7
・PngOptimizer Ver.2.51

WinMergeの画像比較で同一表示となることを確認してあります。
置き換えるだけで約1.5MBのサイズ削減のメリットがあります。

あまりにサイズ差があったので不思議に思い、処理前後を比較したところ、
HLP000087.htmlで参照されているComCustmenu.pngに関して、
中身がBMPで拡張子だけPNGとなっているようでした。

画像の差し替えだけでContributorというのは違う気がしたので、
添付のZIPをご確認いただき、問題なければコミットしていただきたく思います。

[images.zip](https://github.com/sakura-editor/sakura/files/3787219/images.zip)

**Comment by beru** [comment]
画像の差し替えだけでも contribution ですよ。
コミットメッセージにわしが育てたのAAを入れても approve します。

**Comment by KENCHjp** [comment]
むしろ、ヘルプやホームページ廻りを積極的に修正していただける方大募集中です。

**Comment by Rukoto** [comment]
ご返答ありがとうございます。
ドキュメントのメンテナンスに関してもいろいろ考えておりましたが、
もしかしたらお手伝いすることもあるかもしれません。

とりあえず本件は近いうちに Pull request します。

**Comment by beru** [comment]
PR作成ありがとうございます。
#1085 を merge したのでこの issue を close します。
