### ISSUE TITLE
appveyor の成果物の zip 圧縮を検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#109]
https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy
で appveyor の Artifacts が 6ヶ月の保存期間を過ぎたら削除されるポリシーが公開された。
(2018/6/17 から有効)

→ 多分 appveyor のディスク容量を圧迫しているんではないかと想像する。

オープンソースプロジェクトに対してタダで提供していただいていることに感謝しているので
appveyor のディスク容量の負担を減らすために zip 圧縮を検討する。

appveyor 上で 7z コマンドが利用可能なみたいで、7z コマンドを使えば zip 圧縮できる模様。
https://www.appveyor.com/docs/packaging-artifacts/#packaging-multiple-files-in-different-locations-into-a-single-archive

**Comment by m-tmatma** [comment]
になみに zip 形式よりも 7z 形式のほうが圧縮率が高い。

https://sevenzip.osdn.jp/ で インストーラをダウンロードしてインストールするだけだけど
標準で対応していないのですこしユーザーのハードルは上がる。

CI から直でダウンロードしようとしているユーザーには問題ないかもしれないが。

**Comment by kobake** [comment]
うーん、確かにフリープランには感謝しているのですけど、僕らみたいな1プロジェクトがディスク圧迫を気にしても仕方ないような。
利用者目線での利便性を上げるために圧縮するのであれば賛成ですが、そうでなければそこにコストを払うのはどうだろう、という気持ちです。

自分が AppVeyor の中の人だとしたら、成果物は内部的には全部自動圧縮しておいて、ダウンロード時にだけ展開するように組みますね。そういうふうに全体のパフォーマンスチューニングするのであればコストと効果が見合う可能性はあると思っています。

**Comment by m-tmatma** [comment]
#114 で 成果物を zip 圧縮を行うようにした。

対応のメリット
- ダウンロード時間の短縮
- ダウンロードした成果物の exe を実行したときに Smart Screen でブロックされなくなる(みたい)

成果物にビルド番号につけるというアイデアがあるが保留中
- https://github.com/sakura-editor/sakura/pull/114#issuecomment-397121879
- https://github.com/sakura-editor/sakura/pull/114#issuecomment-397156121

**Comment by kobake** [comment]
既存の有名なプロダクトがどのような方針を採っているのか気になってます

**Comment by m-tmatma** [comment]
> 成果物にビルド番号につけるというアイデアがあるが保留中

#165 で登録した。
