### ISSUE TITLE
オフ会の提案

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#110]
諸々コントリビュータが増えていることは好ましいことです。ただ、個人個人でスタンスのブレがやや気になっています。

プロジェクトをスムーズに回して行くためにはある程度スタンスの方向性を合わせて行くことが必要に感じています。

都合の良い場所、都合の良い時間帯を確保してざっくり方向性を合わせる会合を開けたら良いと思っているのですがいかがでしょうか。リモート参加の参加を歓迎します。

**Comment by KENCHjp** [comment]
オフ会ですか、懐かしいですね。
パソコン通信時代に遠征も度々行ったことがありますが結婚してから全然っす（笑）

集まれる時間や場所や各々の事情などは、
公に晒すのははばかれるかと思いますが、
詳細はSlackでチャンネル作って調整ってかんじですかね？
いわゆる懇談会としてのオフ会じゃないとすると自由参加にすると、 @kobake さんの気になるズレをIssueで協議するのとあんまり変わらないかもしれませんし。

このプロジェクトは参加できる方が各々の都合の中からちょっとづつ貢献度して頂いてるかと思うので、ある程度スタンスのブレは有って当然かなと思っておりますが、
気づいたらまた誰もいないってことも避けたいので、オフ会参加不参加にかかわらず疎外感を産まないように、逆にプレッシャーも産まないように、チームの空気づくりと情報共有出来ればなと。

**Comment by kobake** [comment]
この Issue は僕が寝ぼけて書いてしまったものなので一旦スルーでお願いしやす(´Д｀)
