### ISSUE TITLE
Python用の強調キーワードがデフォルトで欲しい

### ISSUE THREAD

**Issue by 7-rate** [sakura-editor/sakura#1106]
## 要望機能
現状デフォルトではPython用の強調キーワードがありません。(スクショ参照の通り)
ユーザーが個別に設定もできますが、開発環境が違うと一々設定するのも面倒です。
Pythonはメジャーな言語でもあるのでデフォルトで強調キーワードのセットが欲しいところです。

## スクリーンショット

![image](https://user-images.githubusercontent.com/22238784/69901561-b3402800-13c6-11ea-9287-feed3e500f43.png)

**Comment by berryzplus** [comment]
👍 

どっか有名サイト（＝公式？）からキーワード拾ってきて「これで！」と提案してもらえれば「それで！」にしていく感じでいいかと思います。キーワードはやっぱり、ある程度使う人が選定するのが良いと思いますんで。（と、読み書きできるが普段はほぼ使わない人がゆう :smile;

**Comment by KENCHjp** [comment]
私も、Pythonは最近サンプル作った程度なので、どなたか有識者いらっしゃると助かります。

**Comment by 7-rate** [comment]
ではこれで！というものを。
Pythonで使うキーワードは下記のように出力できますので、これでお願いします。
![image](https://user-images.githubusercontent.com/22238784/69961264-dbf32980-154e-11ea-8d21-7982b24f4100.png)

テキスト
False
None
True
and
as
assert
break
class
continue
def
del
elif
else
except
finally
for
from
global
if
import
in
is
lambda
nonlocal
not
or
pass
raise
return
try
while
with
yield

**Comment by m-tmatma** [comment]
たしか　#314　で実装したはずです。
ただ過去の　sakura.ini はアップグレードしないです。
新規インストールだと使えます

**Comment by berryzplus** [comment]
そういえば これ との関連性がどうなのか気になってます。
https://github.com/sakura-editor/sakura/blob/e5172cb526f26ad18ec5754282886b6270459588/installer/sinst_src/keyword/python_2.5.kwd#L1

ファイル名からして Python2 系のキーワード？

あんまり使わないのでほぼ知らんのですが、 Python には 2系 と 3系 があって、名目的には 2系 は Obsolete(=古い形式なので使わないでね。) になってるらしいです。

#314 はアウトライン解析を使えるようにした話だから、ギリギリで「違う話」なのかなぁ・・・。

**Comment by m-tmatma** [comment]
#314 の修正の中でキーワードの追加も入ってます。
差分を見てもらえるとわかります。
ただキーワードが必要充分かは確認した方がいいと思います

**Comment by arigayas** [comment]
Pythonについて全く知らないですが、
7-rate さんが提案したキーワードより #314 の修正の中で追加されたキーワード の方が3つ(下記の3つ)多いですね。

- async
- await
- self

**Comment by k-takata** [comment]
aync, await は Python 3.5 から予約語になったはずですが、上のリストにはないですね。Python 3.8 で同じコマンドを実行したところ、リストに出てきました。
self は慣習的に C++ で言うところの this のようなものですが、キーワードではなく別の名前を使うこともできます。（普通は self を使いますが。）
なお、Python 3 からは print は予約語ではなくなりました。

**Comment by berryzplus** [comment]
同じ話なんですね。
レビュー的当ですんません。

要するに、要望したキーワードは既に入ってるってことになるぽいです。

何かしないと有効にならないみたいですが。

closeで良いのかな？

**Comment by arigayas** [comment]
[最新のソースコード](https://github.com/sakura-editor/sakura/archive/master.zip) をダウンロードしてビルドしたスクリーンショットです。
![image](https://user-images.githubusercontent.com/11251874/70331907-ca2dc100-1883-11ea-8fb4-abb4b1dc09bd.png)

Closeで良いと思います。

**Comment by 7-rate** [comment]
新規インストールだとデフォルトで入っているのですね。
お騒がせしました。closeします。
