### ISSUE TITLE
Azure PipelinesのMinGWビルドが失敗している

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1108]
## 問題内容
直近の Azure Pipelines のMinGWビルドが立て続けに失敗しています。

https://github.com/sakura-editor/sakura/pull/1104/checks?check_run_id=327038617
https://github.com/sakura-editor/sakura/pull/1105/checks?check_run_id=327142466
https://github.com/sakura-editor/sakura/pull/1107/checks?check_run_id=327140853

原因は chocolatey の msys2 パッケージがダウンロードできないことによるものです。

何故そうなったのか？が不明なので現状はただモヤモヤするのみですが、
ビルド失敗の状況が続くようであればなんらかの対処が必要と考えられます。

## 再現手順
不明

## 再現頻度
不明

## 問題のカテゴリ
- ビルドの問題
  - Azure Pipelines

## 環境情報
CIビルドの問題なのでPC環境関係ないっす。

**Comment by berryzplus** [comment]
chocolateyリポジトリへのアクセス過多が原因だったっぽいです。
[今さっき再試行したビルドが成功してる](https://dev.azure.com/sakuraeditor/sakura/_build/results?buildId=1137)っぽくて、さっきまで [ここ](https://chocolatey.org/packages/msys2) が表示できてなかったのが回復している・・・。

いま google で azure pipelines msys2 を検索するとこれが 1つ目 に表示されます。
https://github.com/microsoft/azure-pipelines-image-generation/issues/440

なお、 azure pipelines 運営側の視点に立つと、「ビルド開始時に chocolatey で msys2 をインストールする」はちょっと違うっぽいです。ビルド環境をカスタマイズするための仕組みとして agent というのがあるので、**それを使ってね♬** ということらしいです。 

で、そこまで分かったところであることに気付きました。
sakura-editor の azure pipelines の設定を弄るのに必要な権限を持ってなかったです 😢 

<img src="https://user-images.githubusercontent.com/3253151/69910476-aa476900-144f-11ea-88bd-04332371540d.png" width="600" alt="https://dev.azure.com/sakuraeditor/" />

@KENCHjp さんに診てもらったら分かるのかな・・・
もしかすると @m-tmatma さんでないとアクセスできないとこの設定かも知らんです。

----
問題なくビルド通ったみたいなんで、chocolatey レポジトリの障害に巻き込まれたビルドの再実行は、順次行って回復させてく感じになります。

**Comment by berryzplus** [comment]
ちなみに昨日から時々、

```
/azp run
```

とコメントしているのは、 azule pipelines のリビルドコマンドです。

権限まわりは色々と面倒くさいので、ナシで運用できるならそれに越したことはないと思っています。まぁ、インターネットで公開しているものである以上、「権限制御なし」ってわけにもいかないことは承知しているのですが。

**Comment by m-tmatma** [comment]
> @KENCHjp さんに診てもらったら分かるのかな・・・
> もしかすると @m-tmatma さんでないとアクセスできないとこの設定かも知らんです。

ご無沙汰です。

https://dev.azure.com/sakuraeditor/sakura/_settings/projectOverview
の画面で、administrator を追加できるのですが、

@berryzplus さんはおそらく GitHub アカウントで azure pipelines にログインしていると
思うのですが、登録しようとしてもユーザーが見つからないというエラーになりました。

@KENCHjp さんは検索して見つかったので admin に追加しました。

**Comment by KENCHjp** [comment]
@m-tmatma さんおつかれさまです。
すいません、ここ見落としてました。
追加でやる必要あれば引き続きウォッチします。
m(_._)m

**Comment by KENCHjp** [comment]
なんか、怒られますね。アクセスすると。

>401 - Uh-oh, you do not have access.
>Your account, [メールアドレス] is not authorized to view this page. Make sure the URL is correct and your account has access. View a list of your organizations here. You may request access by contacting the admin.

**Comment by berryzplus** [comment]
> ご無沙汰です。
> https://dev.azure.com/sakuraeditor/sakura/_settings/projectOverview
> の画面で、administrator を追加できるのですが、
> @berryzplus さんはおそらく GitHub アカウントで azure pipelines にログインしていると
思うのですが、登録しようとしてもユーザーが見つからないというエラーになりました。

お久しぶりです。

自分でも試してみましたがGitHub連携のアカウントの本人確認ができていないようでした。
たぶんGitHubのアカウントしか使わないのでこちらで入りたいです。

メールアドレスの確認を実施したので、そのうち使えるようになるんじゃないかな、と。
（何故か即反映されなくて「さっすがマイクロソフト！」ということにして放置モード中です。

**Comment by berryzplus** [comment]
GitHubアカウントのメールアドレスを「公開」にしてなかったのが原因だったようです。
メアドコピペで追加できるようになったはず・・・。（複数アカウント持ってるのでやってみた(^^;

**Comment by m-tmatma** [comment]
> GitHubアカウントのメールアドレスを「公開」にしてなかったのが原因だったようです。
> メアドコピペで追加できるようになったはず・・・。（複数アカウント持ってるのでやってみた(^^;

出てきませんでした

**Comment by berryzplus** [comment]
こちらからは @m_tmatma さんが見えるようなので invite してみました :smiley:
仮で作った organization だから何もないですが、adminにもできたっぽい・・・。

先週始め(=コメント書いてた時)に見たのとUIが変わったように感じるのは気のせいだろうか？

**Comment by m-tmatma** [comment]
> https://dev.azure.com/sakuraeditor/sakura/_settings/projectOverview
> の画面で、administrator を追加できるのですが、

上記の画面は、プロジェクトにユーザーを追加する設定でした。

https://dev.azure.com/sakuraeditor/_settings/users
でユーザーを追加できるので、 @berryzplus さんを invite しました。

ユーザーを追加できるのは organization の owner のみのようです。

**Comment by berryzplus** [comment]
https://dev.azure.com/sakuraeditor を参照できるようになったみたいです。
権限の話は解決のようです。

何気に、メンバーが5人より多くなってるのでライセンス的なアレが大丈夫かチラッと気になりました。基本5人 + vsライセンスに紐づいたアカウント数×5人 が上限だったと思うので、いまんとこセーフだと思っていますが、もし足りなくなったら紐付け変更とかしたほうがいいのかな、と。

hosted-agentを使った方式の検証はまだ全然やれてないので issue 自体はしばらく残る感じです。

**Comment by berryzplus** [comment]
chocolatey リポジトリの障害が再発中・・・。
https://dev.azure.com/sakuraeditor/sakura/_build/results?buildId=1173&view=logs

msys2 最新を入れると、MinGWツールセットのバージョンが v9.2.0 になるはずなんだけど、
従来版 v9.1.0 と v9.2.0 の差異がどうなっているかは未検証。
というか、gccビルドバージョンが変なタイミングで落ちるらしいって情報も未検証だったり。

**Comment by berryzplus** [comment]
う～む。やはり再発中・・・。

**Comment by k-takata** [comment]
> 原因は chocolatey の msys2 パッケージがダウンロードできないことによるものです。

最新 Azure Pipelines 環境では msys2 がインストール済みなので、本現象は起きなくなったはず。
ということで閉じちゃいます。
