### ISSUE TITLE
「ツールバーを表示」などに関する問題

### ISSUE THREAD

**Issue by glassonion0323** [sakura-editor/sakura#1109]
いつも使用させて頂いています。
不具合と思われる現象を確認しましたので連絡します。

## 問題内容
現象1. 「ツールバーを表示」から「ミニマップを表示」のいずれかの設定後、ウィンドウの最大化が記憶されていません。
現象2. 「ツールバーを表示」から「ミニマップを表示」のいずれかのボタンをツールバーに追加するとサクラエディタが起動しません。

## 再現手順
現象1
1. サクラエディタを最大化表示にして一度終了します。
2. サクラエディタを再び起動すると、最大化状態で起動します。
3. 「設定」メニューから「ツールバーを表示（表示中のツールバーを隠す）」から「ミニマップを表示（表示中のミニマップを隠す）」のいずれかの設定後、サクラエディタを一度終了します。
4. ウィンドウが最大化されていない状態で起動します。
（3.の設定後、一度ウィンドウの最大化を解除し、再度最大化すると再起動後も最大化状態になります）

現象2
1. sakura.iniをバックアップしておきます。
2. 「ツールバーを表示」から「ミニマップを表示」のいずれかのボタンをツールバーに追加して、サクラエディタを一度終了します。
3. サクラエディタを再び起動しようとしても起動しません。
4. sakura.iniをバックアップしていたものに戻すと正常に起動します。

2.3.1.0で確認したところ、上記の2現象は発生しないようです。

## 再現頻度
上記手順を行えば毎回再現。

## 問題のカテゴリ
- プログラムの動作上の問題
  - Appveyor ビルド版

## 環境情報
- OS バージョン
Windows 7 64 bit （Windows 10 64 bit でも同じ現象を確認。）
- サクラエディタバージョン
サクラエディタ v2.4.0.2398
先日まで2.3.1.0で使っていた。Ver2.4.0 beta2 (sakura-build2398-Win32-Release-Exe.zip) をダウンロードして上書き。

**Comment by KENCHjp** [comment]
デグレってる感じですね。
今試せないので、再現確認したら、一旦Beta2破棄します。

**Comment by KENCHjp** [comment]
再現手順で
現象1・・・再現しました。
現象2・・・再現しました。。。。がなんかちょっと挙動が怪しかったです。おそらく古いIniファイルが残ってたからかもしれませんが、初期起動した後閉じて再度開いたら、ツールバーがまっさらになってて、そこから「ミニマップを表示」を追加して再起動するとトレイアイコンにはアイコンが居ましたが画面が表示されず、しばらく待っていると、

![キャプチャ1](https://user-images.githubusercontent.com/39618965/70130885-bb4ce000-16c4-11ea-85ff-466fb1899974.PNG)

こんなんが表示されました。ただこれはiniファイルが古いのが残っていたせいかもしれません。

**Comment by k-takata** [comment]
> 今試せないので、再現確認したら、一旦Beta2破棄します。

リリース物を削除するという意味でしょうか。もしそうだとしたら、Betaは正式リリース前のバグ報告を受けるための仮リリースだと思うので、削除はしないべきだと思います。（というよりBetaを出した意味がありましたね。）

**Comment by berryzplus** [comment]
現象1については、共有メモリに何かを書き込んでる雰囲気を感じますが具体的にはなんも分かってないです。

現象2についてはちょっとだけ分かったことがあるので共有してみます。

原因は **ヌルぽ** ですね（核心
https://github.com/sakura-editor/sakura/blob/e5172cb526f26ad18ec5754282886b6270459588/sakura_core/func/Funccode.cpp#L1304

```	case F_SHOWMINIMAP:			return pCEditWnd->GetMiniMap().GetHwnd() != NULL; ```

ツールバーに「ウインドウ表示切替系」のアイコンを追加すると、
上記引用部分が `pCEditWnd` に値がセットされる「前」に呼ばれてしまうようです。
（この処理は、

値がセットされる前のアドレスは nullptr なので、参照しようとすれば 一般保護違反(Access Violation) が発生します。

サクラエディタの編集ウインドウ作成処理は、「わかりやすくする」ために標準的なWindows API実装と異なる方式になっています。

- 通常の仕様： あらゆるウインドウイベントをウインドウプロシージャで処理する。
- サクラ仕様： ウインドウ作成イベントはイベント実行しない。
  - 編集ウインドウの作成中にイベントを受け付けると、プログラマが想定しない割り込みが入って煩雑になるため（と思われる）
  - 編集ウインドウの初期化が完了するまでは、編集ウインドウの初期化完了を前提とする処理を呼び出してはならない（仕様）

所感
雰囲気「最初っからじゃね？」です。

つまり **ツールバーに「ウインドウ表示切替系」のアイコンを追加すると起動できない** は v2.4 で作りこんだ「新規バグ」ではなく、元からあったバグなんじゃないかな？と思いました。報告的に「v2.3.1では出てない」ってことだったのでその辺りは謎です。

裏は取ってないので、ただの想像です。

ぼくは犯人に興味はなくって、どうしたら「これで解決！」と言えるかが気になっています。

正攻法なら、「サクラ仕様のウインドウ初期化をやめる」だと思います。
それだと変更が重たすぎるので、どこかで妥協点を探る感じになると思っています。
どうあるのが「正しいか？」というメンドクサイ系の話になるので結論がでにくいのかなぁ・・・。

**Comment by KENCHjp** [comment]
@k-takata さん
>削除はしないべきだと思います。（というよりBetaを出した意味がありましたね。）

誤解を生む表現ですいません。おっしゃる通りリリース物はそのままにしようとおもっています。

ブランチ切ったリポジトリを不具合対応したmasterから切りなおしたほうがいいかと思っての発言でしたが、修正をリリースブランチにマージしてもいいんすよね。。。Git的にどっちがいいでしょう？（決めの問題？）

@berryzplus さん
確認どうもです。
>雰囲気「最初っからじゃね？」です。

お、であれば、不具合あるにしろこのままリリース突入しようかなと思います。
今のところ年内目標（21か22日あたり）で、最低限ホームページの修正をコミット積んでおいて、
リリース終わったら、master側へヘルプの修正反映させて、v2.4.1に上げようかというのが算段でございます。

**Comment by k-takata** [comment]
> Git的にどっちがいいでしょう？

そういう意味でしたら了解です。masterの修正を全て取り込むのであればマージでいいのではないでしょうか。（特定の修正のみを取り込むにはcherry-pickがありますが。）

**Comment by KENCHjp** [comment]
>masterの修正を全て取り込むのであればマージでいいのではないでしょうか。

了解です。既存不具合との話もあり、もうちょっと様子見て対応方法決めようと思います。

**Comment by KENCHjp** [comment]
とはいえ、落ちちゃうのを気づいてて放置は、ちょっと気が引けますね・・・

**Comment by berryzplus** [comment]
## 現象を誤解していたことに気付く、なう。

> 3.「設定」メニューから「ツールバーを表示（表示中のツールバーを隠す）」から「ミニマップを表示（表示中のミニマップを隠す）」のいずれかの設定後、サクラエディタを一度終了します。

**「ツールバーを表示（表示中のツールバーを隠す）」から「ミニマップを表示（表示中のミニマップを隠す）」のいずれか** と言ってるものと https://github.com/sakura-editor/sakura/issues/1109#issuecomment-561672237 で **「ウインドウ表示切替系(コマンド)」** と表現している機能は等価ですね。気付いてなかったです・・・。（合ってたんですが。

## 現象1 の分析

発生理由はこれっすね。
https://github.com/sakura-editor/sakura/blob/ee281f7837b3d99460a00ed201b31c370b406d5c/sakura_core/window/CEditWnd.cpp#L1044-L1051

> ツールバーの表示ON/OFFを行うとちらつきが発生する事への対策

と書いてあるんで、その通りの理由で実装された処理と思われます。
一度 0 を指定して WM_SIZE してから `m_nWinSizeType` を指定して WM_SIZE しています。
この `m_nWinSizeType` が「ウインドウが最大化されている」という情報なんですけど、
一回目の呼出で呼び出される `CEditWnd::OnSize2` の中で値が書き換わってしまうので(´・ω・｀)

呼出前に値をバックアップすることで事象は回避できそうです。

## 現象2 の分析

結局、裏は取ってません。（マテ

「ここを修正したら回避できる！」という箇所を見付けたので一旦報告。
https://github.com/sakura-editor/sakura/blob/ee281f7837b3d99460a00ed201b31c370b406d5c/sakura_core/func/Funccode.cpp#L1272-L1277

`pCEditWnd` というのが編集ウインドウを参照するポインタ変数です。
現象2 の問題は、このポインタが NULL になってしまった結果の ”ぬるぽオチ” でした。

`CEditWnd` はシングルトンなので、インスタンスの初回生成より後のタイミングであれば `CEditWnd::getInstance()` 呼出によってポインタを得ることができます。

引用コードをよく見ると、getInstanceした値ではなくて、GetHwnd でクラスに関連付けられた生Windowハンドルをゲットして、 GetWindowLongPtr で生Windowsハンドルに関連付けられた　USERDATA をゲットしています。

同じ結果を取得するのに無駄なことをしているわけではなく、おそらく仕様に基づいたコードだと思われます。（編集ウインドウの初期化が終わる前に編集ウインドウが必要な処理を行ってはならないという仕様）

`CEditWnd::getInstance()` の戻り値を直接使うようにすることで事象は回避できそうです。
