### ISSUE TITLE
前回の作業状態を復元する機能が欲しい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1122]
## 要望機能
プログラム起動時に、前回の作業状態を復元する機能が欲しいです。

VS Codeでは、ファイルをたくさん開いた状態でOSを終了させたあと、
再度開くと前回終了時の作業状態が未保存の編集内容を含めて再現されます。
そんな感じの挙動になってくれたら嬉しいな、と思います。

おそらく、アンドゥ・リドゥのための作業履歴を活用して実現されているので、
サクラエディタでも不可能じゃないと思っています。

大枠のフローはこんな感じ

アプリケーション終了イベントでファイル単位に作業履歴を一時フォルダに保存
　　↓
アプリケーション起動イベントで作業履歴を検出したら対象ファイル全部を開く
　　↓
ファイル読込完了イベントでファイルの作業履歴を検出したら読み込んで復元する

実現できれば「Windowsからのサインアウト時に編集中のファイルがあると、サクラエディタがサインアウトをブロックしてしまう」という長年の課題を解決できるように思っています。

**Comment by takke** [comment]
個人的にめちゃめちゃ欲しいです。

私は普段、常に開いておきたいファイルが5つくらいあります。現在は、それらのファイルをショートカットにしてフォルダに放り込んでおき、Windows が起動したらサクラエディタを起動し、そのフォルダからショートカットをサクラエディタにD&Dして、ファイルを開いた状態を再現しています。

「タブの状態を保存する機能」があればいいのかなと思っていましたが「前回の作業状態を復元する機能」のほうが便利ですね。
私は作業履歴にはこだわらないのでタブの状態だけでも復元できるようになるとありがたいです。

**Comment by berryzplus** [comment]
おお、反応ありがとうございます。:smile:

意外と需要ないんだな～と思って閉じようかと思って気付きました。
開いているタブの復元だけであれば4年くらい前に Moca さんが作った実装がネットのどこなに転がってる気がします。当時、いいね♪とだけ反応した微かな記憶があるんですけど、今探しても見つからないのでHPと一緒に消失してしまった感じです。

何からの方法でタブ一覧を保存しておいて、
何らかの方法で一覧の順番通りにファイル（＝タブ）を開くことができれば
実現できると思っています。
作業状態復元はオマケですね・・・。

せっかくなので年内投下を目指して実装を検討してみることにしまっす。

**Comment by berryzplus** [comment]
あけおめっす。

結局18:00から紅白見はじめて、そのまま「生さだ」を見る展開に突入した感じでした。
久々に生で「風に立つライオン」聴いたけど、良かったなぁ・・・

みなさんの年始休みが終わらないうちの投下を目指して作業は続けていきたいと思っています。

**Comment by cugra** [comment]
ググったらMocaさんのアルファ版パッチはSFに残っていました。
https://sourceforge.net/p/sakura-editor/patchunicode/989/

**Comment by berryzplus** [comment]
年始休み中の対応は、無理でした...orz

@cugra さん、情報ありがとうございます。
コード見て見ました・・・セッションという機能なのかな？

Windowsの正規の技術ネタの世界では、
ユーザーがログインしてからログアウトするまでをセッションと呼んでいますが、
それをサクラエディタにもってきた感じなのかな？と思いました。

手前実装ではタブグループを保存する、というイメージでやっています。
タブグループの保存だけであれば一応うごくんですけど、
作業状態保存を前提に作り始めた実装なんで、現状で出すと色々マズそうです。

- 単純なタブ保存だと「開いていたファイルを開きなおす」になります。
- Grep検索結果とか未保存の「無題1(更新)」とかは捨てる感じになります。
- Windows xpの新機能 query end session に中途半端に対応してしまったので、未保存の変更が有無を言わさず捨てられてしまいます。　←これ、超マズい。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394

**Comment by takke** [comment]
悲しいですが仕方ないですね。。
