### ISSUE TITLE
tag に対するビルドで成果物名にタグ名が付与されていない

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#1125]
## 問題内容
tag に対するビルドで成果物名にタグ名が付与されていない

## 再現手順

https://github.com/sakura-editor/sakura/releases/tag/v2.4.0-beta3
の assets から ダウンロードする成果物の zip ファイル名を確認する。

https://github.com/sakura-editor/sakura/releases/tag/v2.4.0-beta2
も同様

https://github.com/sakura-editor/sakura/releases/tag/v2.4.0-beta
も同様

## 再現頻度

3/3

## 問題のカテゴリ

- ビルドの問題
  - Appveyor

## 環境情報

関係なし

## スクリーンショット

https://ci.appveyor.com/project/sakuraeditor/sakura/builds/29703433/job/vy0u8lck547tdg83/artifacts

<img width="802" alt="artifacts" src="https://user-images.githubusercontent.com/5567450/71702858-03226c80-2e15-11ea-8917-cb78be62f490.png">

https://github.com/sakura-editor/sakura/releases/tag/v2.4.0-beta3

<img width="822" alt="artifacts2" src="https://user-images.githubusercontent.com/5567450/71702845-f6057d80-2e14-11ea-8a7a-a0c3d43aed5d.png">

**Comment by m-tmatma** [comment]
以下で GIT_TAG_NAME を参照するが、

https://github.com/sakura-editor/sakura/blob/7a77024d982789baa986860ffa38d1ab9da906de/zipArtifacts.bat#L53-L66


 GIT_TAG_NAME は githash.bat で設定される。

https://github.com/sakura-editor/sakura/blob/7a77024d982789baa986860ffa38d1ab9da906de/sakura/githash.bat#L47-L52

#876 でデグレしたかも

**Comment by berryzplus** [comment]
ギクッ！・・・（githash.bat呼出し周りは弄った気がする

原因はともかく、意図と違う動きになってるのはいくないですね。

azure pipelinesに限った話ですが、
子batchが設定した環境変数を親batchで拾えないようになってるような気がします。
親から子はOKだけど、兄弟は無理っぽい。
まぁ、なんかやりかたはあるのかもですけど。

**Comment by m-tmatma** [comment]
#1127 を作成

**Comment by m-tmatma** [comment]
#1127 で対応
