### ISSUE TITLE
VS2019 で単体テスト CNativeW.AppendStringWithFormatting でクラッシュする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#1141]
## 問題内容

VS2019 で単体テスト CNativeW.AppendStringWithFormatting でクラッシュする

## 再現手順

VS2019 で #1140 で ビルドに失敗する箇所をコメントアウトしてビルドする

https://github.com/sakura-editor/sakura/blob/967b9c3e83b573083657b41f6e0a35f2de362da3/sakura_core/mem/CNativeW.cpp#L97-L99

tests1.exe を実行する。

## 再現頻度

100%

## 問題のカテゴリ

- 単体テストの問題 あるいはコードの問題

## 環境情報

単体テスト

**Comment by m-tmatma** [comment]
pszFormat  が null のテストで失敗しているみたい。
間違い。

**Comment by berryzplus** [comment]
失敗した理由が出力されるはず。
再現したazure pipelinesの結果とかあったら教えてください。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/blob/967b9c3e83b573083657b41f6e0a35f2de362da3/sakura_core/mem/CNativeW.cpp#L97-L99

をコメントアウトしてビルドして実行して、

テスト側のコードはそのままにしたので、

https://github.com/sakura-editor/sakura/blob/967b9c3e83b573083657b41f6e0a35f2de362da3/tests/unittests/test-cnative.cpp#L329

で落ちたのが理由です。

**Comment by berryzplus** [comment]
う～ん・・・そりゃそうなるわな・・・と思いました。

例外が投げられることを期待するテストを残したまま、
例外を投げるほうのコードをコメントアウトしたら、
「例外が投げられずに続行しました」とテスト失敗になるのは当然なわけで。

対応の必要がある、と誤解してコメントしましたが closed で対応不要ってことなんすね。
