### ISSUE TITLE
tools/find-tools.bat にログを入れると ISCC.exe の検索に失敗する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#1148]
## 問題内容

tools/find-tools.bat にログを入れると ISCC.exe の検索に失敗する

https://github.com/sakura-editor/sakura/pull/1143#issuecomment-573589231

以下のようなログを入れると

```
echo ^|- NUM_VSVERSION=%NUM_VSVERSION%
echo ^|- PARAM_VSVERSION=%PARAM_VSVERSION%
echo ^|- CMAKE_G_PARAM=%CMAKE_G_PARAM%
```

https://github.com/sakura-editor/sakura/pull/1143#issuecomment-573599954
のように  ISCC.exe の検索に失敗する

でも以下だと問題ない。
https://github.com/sakura-editor/sakura/pull/1143#issuecomment-573611155

```
echo NUM_VSVERSION=%NUM_VSVERSION%
echo PARAM_VSVERSION=%PARAM_VSVERSION%
echo CMAKE_G_PARAM=%CMAKE_G_PARAM%
```

## 再現手順

上記のログを入れたうえで appveyor でビルドする。

## 再現頻度

100%

## 問題のカテゴリ
- ビルドの問題
  - Appveyor

**Comment by berryzplus** [comment]
## 検証1
テスト用に選択したmaster
https://github.com/sakura-editor/sakura/commit/5c39c84cac4049979f4a67f27b554c860694beb1

ログを入れたコミット
https://github.com/berryzplus/sakura/commit/c188b699d54c1ffe2516f57f276dd300a871df16

## 結果1
再現。
https://ci.appveyor.com/project/berryzplus/sakura/builds/30199587/job/8btsst643tf6drcc

## 検証2
1行削ってみる
https://github.com/berryzplus/sakura/commit/fab1767692adbccd606476b902696263f2b42d97

## 結果2
こうなった。（ISCC.exeの値が入った。） https://ci.appveyor.com/project/berryzplus/sakura/build/job/ftronrfip4m749fd
```
find-tools.bat
NUM_VSVERSION 15
|- CMD_GIT=C:\Program Files\Git\cmd\git.exe
|- CMD_7Z=C:\Program Files\7-Zip\7z.exe
|- CMD_HHC=C:\Program Files (x86)\HTML Help Workshop\hhc.exe
|- CMD_ISCC=C:\Program Files (x86)\Inno Setup 5\ISCC.exe
|- CMD_CPPCHECK=
|- CMD_DOXYGEN=
|- CMD_VSWHERE=C:\ProgramData\chocolatey\bin\vswhere.exe
|- CMD_MSBUILD=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
|- CMD_CMAKE=C:\Program Files (x86)\CMake\bin\cmake.exe
|- NUM_VSVERSION=15
|- PARAM_VSVERSION=/p:VisualStudioVersion=15.0
end
do nothing
```

## 検証2の結果から推測できること
1.  `echo ^|- CMAKE_G_PARAM=%CMAKE_G_PARAM%` のどこかにNGパターンがある？
2. 定義できる環境変数の最大数(=MAX値)を超えてる？

どっちや？

なんとなく、推測2が原因だと都合が良いので、それを検証してみることにする。

## 検証3
削除する行を変えてみる
https://github.com/berryzplus/sakura/commit/abd5618a1aa37ab53957db99e129775e1869db09

## 結果3
こうなった（結果2とほぼ同じ） https://ci.appveyor.com/project/berryzplus/sakura/build/job/sxf7uxelrn5xxxsh
```
find-tools.bat
NUM_VSVERSION 15
|- CMD_GIT=C:\Program Files\Git\cmd\git.exe
|- CMD_7Z=C:\Program Files\7-Zip\7z.exe
|- CMD_HHC=C:\Program Files (x86)\HTML Help Workshop\hhc.exe
|- CMD_ISCC=C:\Program Files (x86)\Inno Setup 5\ISCC.exe
|- CMD_CPPCHECK=
|- CMD_DOXYGEN=
|- CMD_VSWHERE=C:\ProgramData\chocolatey\bin\vswhere.exe
|- CMD_MSBUILD=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
|- CMD_CMAKE=C:\Program Files (x86)\CMake\bin\cmake.exe
|- PARAM_VSVERSION=/p:VisualStudioVersion=15.0
|- CMAKE_G_PARAM=Visual Studio 15 2017
end
do nothing
```

## 検証3の結果から推測できること
1.  `echo ^|- CMAKE_G_PARAM=%CMAKE_G_PARAM%` にNGパターンが含まれているわけではなさそう。
2. 定義できる環境変数の最大数(=MAX値)を超えてる？

結果が同じになるなら、検証3の出力のほうが好みです。

しかし、NUM_VSVERSIONを出さないようにしたのに、
先頭にNUM_VSVERSIONが出てるのはなんだろう？

**Comment by berryzplus** [comment]
> しかし、NUM_VSVERSIONを出さないようにしたのに、
> 先頭にNUM_VSVERSIONが出てるのはなんだろう？

これですね。
https://github.com/sakura-editor/sakura/blob/5c39c84cac4049979f4a67f27b554c860694beb1/tools/find-tools.bat#L206-L208

このログ、要らんですね（別件

**Comment by m-tmatma** [comment]
> このログ、要らんですね（別件

#1157 を作成しました。

**Comment by berryzplus** [comment]
#1167 で問題自体は解決しているので、いったん閉じてしまいます。
