### ISSUE TITLE
Visaul Studio 2017 と Visaul Studio 2019 を両方インストールしている環境で build-sln x64 Release でビルドすると "__GSHandlerCheck_EH4" は未解決です。のエラーになる

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#1164]
## 問題内容

Visaul Studio 2017 と Visaul Studio 2019 を両方インストールしている環境で build-sln x64 Release でビルドすると "__GSHandlerCheck_EH4" は未解決です。のエラーになる

```
"D:\gitwork\SakuraEditor\sakura\sakura4\sakura.sln" (Build ターゲット) (1) ->
"D:\gitwork\SakuraEditor\sakura\sakura4\tests\unittests\tests1.vcxproj" (既定のターゲット) (6) ->
(Link ターゲット) ->
  gtest.lib(gtest-all.cc.obj) : error LNK2001: 外部シンボル "__GSHandlerCheck_EH4" は未解決です。 [D:\gitwork\SakuraEditor\sakura\sa
kura4\tests\unittests\tests1.vcxproj]
  (ProjectDir)..\..\..\build\x64\Release\unittests\tests1.exe : fatal error LNK1120: 1 件の未解決の外部参照 [D:\gitwork\SakuraEdi
tor\sakura\sakura4\tests\unittests\tests1.vcxproj]
```

## 再現手順

1. Visaul Studio 2017 と Visaul Studio 2019 を両方インストールする
2. build-sln x64 Release  でビルドする。

## 再現しない手順1

1. Visaul Studio 2017 と Visaul Studio 2019 を両方インストールする
2. build-sln Win32 Release  でビルドする。

## 再現しない手順2

1. Visaul Studio 2017 と Visaul Studio 2019 を両方インストールする
2. Visaul Studio 2017 で sakura.sln を開いてソリューションをビルドで x64 の Release をビルドする。

## 再現頻度

100%

## 問題のカテゴリ

- ビルドの問題
  - ローカルビルド

## 環境情報

Visaul Studio 2017 15.9.19
Visaul Studio 2017 16.4.3

**Comment by m-tmatma** [comment]
googletest のビルドで "Visual Studio 15  Win64" が使われている。

```
InitializeBuildStatus:
  "AlwaysCreate" が指定されたため "x64\Release\tests1.tlog\unsuccessfulbuild" を作成しています。
MakeGoogleTestBuildDir:
  ディレクトリ "D:\gitwork\SakuraEditor\sakura\sakura5\tests\build\x64\Release\googletest" を作成しています。
BuildGoogleTest:
  D:\gitwork\SakuraEditor\sakura\sakura5\tests\googletest.build.cmd D:\gitwork\SakuraEditor\sakura\sakura5\tests\googletest\ "Visual Studio 15  Win64" Release "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community/VC/Auxiliary/Build/vcvarsall.bat" x86_amd64
  **********************************************************************
  ** Visual Studio 2019 Developer Command Prompt v16.4.3
  ** Copyright (c) 2019 Microsoft Corporation
  **********************************************************************
  [vcvarsall.bat] Environment initialized for: 'x86_x64'
  -- The C compiler identification is MSVC 19.24.28315.0
  -- The CXX compiler identification is MSVC 19.24.28315.0
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx86/x64/cl.exe
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.24.28314/bin/Hostx86/x64/cl.exe -- works
```

**Comment by m-tmatma** [comment]
> googletest のビルドで "Visual Studio 15 Win64" が使われている。

"Visual Studio 15  Win64" となっており、 15 と x64 の間に空白が二つある。

Win64 の前に空白がある。

https://github.com/sakura-editor/sakura/blob/a48fdb5ff3f7fffd7f282025f19f349356f44895/tests/googletest.targets#L46

ただビルドには Ninja が使われており、これは問題の一部。

**Comment by berryzplus** [comment]
報告感謝。

導入したときに vs2017 × vs2019 × Win32 × x64 × Debug/Release の 32 環境のテストはやってるはずなんですけど・・・。（漏れてたんですね。

> > googletest のビルドで "Visual Studio 15 Win64" が使われている。
> 
> "Visual Studio 15 Win64" となっており、 15 と x64 の間に空白が二つある。
> 
> Win64 の前に空白がある。

`Visual Studio 15 2017 Win64` を生成すべきところ、
`Visual Studio 15  Win64` となっているように見えます。

つまり、productlineversion=2017が取れてないんではないかと。

**Comment by berryzplus** [comment]
この課題が気になっているので整理してみたいと思います。

## 何が問題か？
> Visaul Studio 2017 と Visaul Studio 2019 を両方インストールしている環境で build-sln x64 Release でビルドすると "__GSHandlerCheck_EH4" は未解決です。のエラーになる
　　↓
色々はしょると **ビルドできない** ですね。

なんかエラーが出てビルドができない、という話。

問題内容が分かったところで、次へ。

## 何が起きているのか？

> Visaul Studio 2017 と Visaul Studio 2019 を両方インストールしている環境で build-sln x64 Release でビルドすると "__GSHandlerCheck_EH4" は未解決です。のエラーになる
　　↓
色々はしょると **ビルドエラーが起きている** ですね。

発生事象が「ビルドエラー」だと詳細がよくわからんので、
もう一段回「何が起きたか？」をブレイクダウンしてみます。

ビルドエラーの詳細を確認するには、エラーコードを探します。

> error LNK2001: 外部シンボル "__GSHandlerCheck_EH4" は未解決です。 

`LNK2001` これっすね。

エラーコードをググるとこんなページが見つかると思います。
[リンカー ツール エラー LNK2001 | Microsoft Docs](https://docs.microsoft.com/ja-jp/cpp/error-messages/tool-errors/linker-tools-error-lnk2001?view=vs-2019)

`LNK2001` はリンクツールのエラーだということが分かりました。

「外部シンボルが未解決です。」なので、
`*.lib` の指定が足りないか、LIBの指定が誤っているということです。
※この部分は、ビルドエラーに対処した過去の経験から導き出される結論です。

googletestのビルドでは個別に`*.lib`の指定をしていないので、
参照するシンボルはすべてシステムライブラリ or Cランタイムライブラリになります。
つまり、リンカエラーの原因は **LIBの指定が誤っている** です。

## なんでこうなったのか？
`find-tools.bat` の変更で `/p:VisualStudioVersion` を導入したときの考慮漏れですね。

つまり、https://github.com/sakura-editor/sakura/issues/1164#issuecomment-575957882 で言及しているgoogletestビルド機構の導入時のテストが漏れてたわけでなくって、後から壊したってことになります。

googletestのビルド部分は、LIBパスが確実に設定されるようにするために VC++ 付属の `vcvarsall.bat` を呼び出す構造になっています。

https://github.com/sakura-editor/sakura/blob/2545777559bffaedf9c4e481fb8937fab2586bdb/tests/googletest.targets#L49

`$(VSInstallRoot)/VC/Auxiliary/Build/vcvarsall.bat` が問題箇所。

ここのビルド機構を作った当時は、
vs2017でビルドするときはvs2017を使う。
vs2019でビルドするときはvs2019を使う。
で住み分けてたんです。

発生事象をよく見ると分かるんですけど、
現在は `NUM_VERSION=15(=vs2017)` の場合でも
vs2019を使ってビルドしているっぽいんです。

## さて、どうしようか？
バグってるにしても `/p:VisualStudioVersion` ってなんかカッコいいので、いったん保留。

**Comment by berryzplus** [comment]
## 結論
#1143 ビルドに使用する Visual Studio のバージョンを指定できるようにする

の根拠になっている `MsBuild.exe` に `/p:VisualStudioVersion=15` を渡すと、バージョン15（＝vs2017）でコンパイルしてくれる、がマボロシだったってことかな？という結論に至りました。

冷静に考えて、build-sln.bat x64 Releaseしたときに使われるバージョンは15なのに、使われているC++ツールセットのバージョンが16なのが、まずおかしいですよね。

カッコよくても意図した通りに動かなかったらイミネっす・・・。
