### ISSUE TITLE
「アウトライン解析(トグル) 」でトグルしない場合がある

### ISSUE THREAD

**Issue by yoshinrt** [sakura-editor/sakura#1175]
## 問題内容
アウトラインウィンドウがドッキング状態 && ( 拡張子が .c または .cpp ) の場合に，「アウトライン解析(トグル) 」でアウトラインウィンドウが閉じない．

## 再現手順
1. サクラエディタを起動し F11 でアウトラインウィンドウを表示します
1. アウトラインウィンドウがドッキングしていない場合は，ドッキングさせます
1. ヘルプ→コマンド一覧→検索系→アウトライン解析 (トグル) を実行します．通常であればアウトライン解析ウィンドウが閉じますが，このとき開いているファイルが .c, .cpp の場合は，アウトライン解析ウィンドウが閉じないようです．

## 再現頻度
100%

## 問題のカテゴリ

- プログラムの動作上の問題

## 環境情報
- OS バージョン
Win10 Pro build 1903

- サクラエディタバージョン
```
サクラエディタ   v2.4.0.2576 32bit dev
(GitHash b3278eb2cd41edf11c5e8c9ad2126d48677c9475)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2020/1/27 11:53:29
```

- PC情報

**Comment by KENCHjp** [comment]
報告ありがとうございます。
確認します。

**Comment by berryzplus** [comment]
報告ありがとうございます。

現象を再現できたのでデバッグしてみたところ、
どうも仕様バグっぽい気配がただよってきたので
いったん途中経過を共有します。

----
## 調査過程

調査は sakura_rc.rc をファイル内検索してみることから始めました。

何故そんなことをするかというと、
サクラエディタのすべての機能には「機能ID」が振られていて、
機能IDには必ず「メニューラベル」が定義されているからです。

「アウトライン解析（トグル）」にも当然、機能IDがあります。
検索により、機能IDが F_OUTLINE_TOGGLE であると分かりました。

```
C:\work\sakura\sakura_core\sakura_rc.rc(2586):    F_OUTLINE               "アウトライン解析..."
C:\work\sakura\sakura_core\sakura_rc.rc(2587):    F_OUTLINE_TOGGLE        "アウトライン解析(トグル)..."
```

今度は F_OUTLINE_TOGGLE をソースコード全体で grepします。

サクラエディタには、メニューコマンドやキー操作を、
内部的な「機能ID」に変換する処理ブロックがあり、
変換後の機能IDを見て処理を振り分けています。

ある機能の処理の開始点を探すには、
機能IDをgrepしてヒットした結果を順に眺めるのが効率が良いと思います。

`CViewCommander::Command_FUNCLIST` がアウトライン解析のエントリメソッドのようです。


## 原因箇所
ここのif条件が成立せずに「閉じる」が実行されないようです。
https://github.com/sakura-editor/sakura/blob/b3278eb2cd41edf11c5e8c9ad2126d48677c9475/sakura_core/cmd/CViewCommander_Outline.cpp#L79-L85

> 開いているものと種別が同じなら閉じる．異なれば再解析

何やら難しいことが書いてあります。

`CDlgFuncList::CheckListType`は開いているファイルの「アウトライン種別」と引数で渡した「アウトライン種別」が等しい場合に true を返すメソッドのようです。

引数で渡す「アウトライン種別」はベタ書きになっているので常に -1 です。
報告されたケース、.cppファイルを開いたときの「アウトライン種別」は 16 です。
種別が異なるので、トグルは作動しない「仕様通り（？）」の挙動になっている、と :cry:

さて、ここからどうしましょ。

**Comment by KENCHjp** [comment]
2.3.2.0でも再現しますね（デグレではなさそう）。
＞さて、ここからどうしましょ。
txtファイルとかとの挙動の差を見比べるとか。

**Comment by berryzplus** [comment]
どう修正したらいいか分かりました。

----

## 調査過程(続き)
> ＞さて、ここからどうしましょ。
> txtファイルとかとの挙動の差を見比べるとか。

確認してみました。
txtファイルを開いたときは、引数で渡されたはずの「アウトライン種別」が3でした。
.txtファイルを開いた時の「アウトライン種別」は 3 なので、この場合アウトラインが閉じられます。

なんでやねんっ！
と引数の更新箇所を調べたところ、
すぐそばでタイプ別設定のデフォルトを入れてる行がありました。
https://github.com/sakura-editor/sakura/blob/b3278eb2cd41edf11c5e8c9ad2126d48677c9475/sakura_core/cmd/CViewCommander_Outline.cpp#L60-L64

では、.cppはどうか？と再確認してみました。
引数のアウトライン種別が 1(OUTLINE_C_CPP) になっていました。（見間違いだたかしら :cry:
.cppを開いたときのアウトライン種別は 16(OUTLINE_CPP) なので、やっぱりズレています。

タイプ別設定(.cpp)のデフォルト値は 1(OUTLINE_C_CPP) みたいです。
https://github.com/sakura-editor/sakura/blob/b3278eb2cd41edf11c5e8c9ad2126d48677c9475/sakura_core/types/CType_Cpp.cpp#L62

なんとなく、引数のアウトライン種別を 1(OUTLINE_C_CPP) に補正しているのが間違いのような気がします。

で、OUTLINE_C_CPP の宣言を見返してみました。
https://github.com/sakura-editor/sakura/blob/b3278eb2cd41edf11c5e8c9ad2126d48677c9475/sakura_core/types/CType.h#L42-L46

なんか書いてあります。・・・自動判別だとっ！

自動判別というからには、何らかの条件で動的に .c と .cpp を振り分けてそうです。
種別がOUTLINE_C_CPPだった場合、そのまま使ってはいかんような気がします。

アウトライン種別に OUTLINE_CPP を代入している箇所を検索してみました。
https://github.com/sakura-editor/sakura/blob/b3278eb2cd41edf11c5e8c9ad2126d48677c9475/sakura_core/types/CType_Cpp.cpp#L345-L362

・・・こいつや。犯人こいつや！


問答無用で修正しても良さそう（＝仕様バグじゃなく単なる実装漏れ）ですね.,..orz

## 修正方法
C/C++の自動判別コードを個別の関数に抽出し、
アウトライン解析（トグル）のコードからも呼ばせるようにすればいい。
