### ISSUE TITLE
64bit or 32bit を確認できるように「ヘルプ」→「バージョン」で表示するべき It is better to display 32bit or 64bit by clicking "help" and "version" information.

### ISSUE THREAD

**Issue by wawashington** [sakura-editor/sakura#1178]
It is better to display 32bit or 64bit by clicking "help" and "version" information.
64bit or 32bit を確認できるように「ヘルプ」→「バージョン」で表示するべき

現行の使用では使っているサクラエディタが32bitか64bitかを確認することができません。
Current version can not tell the users are using 32bit or 64bit version of sakura editor

**Comment by wawashington** [comment]
プログラム改正の際に参考にお願いします

**Comment by berryzplus** [comment]
In latest version, you can find the build-version here.
[<img width="300" src="https://user-images.githubusercontent.com/3253151/73457265-bf406a00-43b6-11ea-97c1-371793003265.png" />](https://user-images.githubusercontent.com/3253151/73457265-bf406a00-43b6-11ea-97c1-371793003265.png)

64bit version can not run on 32bit windows.
32bit version can run on 64bit windows.

SAKURA editor's 64bit version is still be experimental build.

you can get the latest version(include pre-release versions) here.
https://github.com/sakura-editor/sakura/releases

**Comment by arigayas** [comment]
Closeで良いと思います。

**Comment by KENCHjp** [comment]
Close致します。
