### ISSUE TITLE
設定項目がなかったらデフォルト設定を使うようにしたい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1188]
## 問題内容
設定項目がなかったらデフォルト設定を使うようにしたい

ぼんやりとした課題で申し訳ないのですが、設定項目がなかったらデフォルト設定を使うようにすることでサクラエディタの使い勝手を改善したいです。

前提知識として、サクラエディタの設定機構について概説します。
1. サクラエディタを起動すると、バックグランドプロセスが1つ生成されます。
2. バックグラウンドプロセスは、エディタ設定を同期させるためのもので、システム内に1つだけ作成されます。
3. バックグラウンドプロセスは、最初にデフォルト設定を構築します。
4. バックグラウンドプロセスは、sakura.iniの存在をチェックします。
5. sakura.iniが存在していたら設定を読み込みます。（ **デフォルト設定が上書きされます。** ）
6. sakura.iniが存在しなかったらデフォルト設定をsakura.iniに書き出します。
7. バックグラウンドプロセスは、プロセス終了時に設定をsakura.iniに書き出します。

読めなかった場合の挙動は、設定項目によってまちまちです。
- デフォルト設定を破棄し、空設定で上書きするもの（ツールバーやメニューなど）
- 特定の設定項目が読めない場合、設定を上書きしないようなガードが入っているもの（キー割り当てなど）

上書きガードが入っていない理由は不明ですが、予想される理由はこんな感じ。
- 単なる手抜き（フリーソフトなんで、しゃあないっす！ :smile:）。
- インフラクラス(CDataProfile) が読み取り失敗の検出に対応していない。
- 設定の有効/無効判断に使うキーを決めるのがめんどかった。

とりあえず、できることから対策を進めていきたいので当面は「インフラクラス(CDataProfile) が読み取り失敗の検出に対応していない」を解決するための作業を進めていく感じです。

## 再現手順
問題事象のごく一部ですが、再現できる手順を1つ紹介します。

1. [GitHub Release](https://github.com/sakura-editor/sakura/releases) から最新モジュール(Exe.zip)をダウンロードします。
2. ダウンロードしたExe.zipをテキトーなフォルダに展開します。
3. 起動しているサクラエディタを全終了させます。
4. Exe.zipを展開してできた sakura.exe をダブルクリックで起動します。（sakura.iniが出力されます。）
5. 起動したサクラエディタを×で閉じて終了させます。（sakura.iniが更新されます。）
6. sakura.iniを開いて `[Toolbar]` セクションを削除します。
7. Exe.zipを展開してできた sakura.exe を再度ダブルクリックで起動します。
8. ボタンが1つもないツールバーが表示されるのを確認できると思います。（再現）

ツールバーセクションの例
```ini
[Toolbar]
bToolBarIsFlat=1
nTBB[000]=1
nTBB[001]=25
nTBB[002]=3
nTBB[003]=4
nTBB[004]=0
nTBB[005]=33
nTBB[006]=34
nTBB[007]=0
nTBB[008]=87
nTBB[009]=88
nTBB[010]=0
nTBB[011]=225
nTBB[012]=226
nTBB[013]=227
nTBB[014]=228
nTBB[015]=229
nTBB[016]=230
nTBB[017]=0
nTBB[018]=232
nTBB[019]=0
nTBB[020]=264
nTBB[021]=265
nTBB[022]=266
nTBB[023]=0
nTBB[024]=346
nToolBarButtonNum=25
```

## 再現頻度
100%

## 問題のカテゴリ
- 仕様の問題

## 環境情報
環境に依存しない問題なので対象外

## スクリーンショット
なし

**Comment by ds14050** [comment]
ユーザーがすべてのツールバーボタンを削除した状態とどう区別しますか？

Thunderbird というメーラーを使っていますが、縦方向に余白を作るために
空のツールバーを表示しています。

**Comment by ds14050** [comment]
セルフツッコミ。

nToolBarButtonNum=0 という設定が存在しないなどの不備で検知できそう。
お節介で馬鹿な道具になることを心配していますが、この件は当たらなそう。

**Comment by berryzplus** [comment]
> nToolBarButtonNum=0 という設定が存在しないなどの不備で検知できそう。

強調キーワードの上書きガードがそんな感じになっていたはずです。

「CDataProfileが読み取り失敗を検知できない」とは言っても、「設定項目がない」を検出するのは現状でも可能なので、設定項目によってはそういう上書きガードが「既にある」わけです。

全体的に対応ができれば、たとえば「メニュー設定をデフォルトに戻したい」の解決策として、メニューセクションをザクッと削るだけでデフォルトに戻せるのかな、という壮大な目論見です。

**Comment by ds14050** [comment]
>メニューセクションをザクッと削るだけでデフォルトに戻せるのかな、という壮大な目論見です。

たぶんリセットボタンを設定ダイアログに付けた方が有用です。

それはそれとして、最近アウトラインウィンドウが見えなくなる不都合な設定値が明らかになりました。エディタを堅牢にする、正常動作する条件を拡大するための変更は応援します。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394
