### ISSUE TITLE
[要望] 「ファイル(F)」→「開き直す(W)」のサブメニューに「読み取り専用で開き直す」を追加して欲しい

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#1189]
## 要望機能
「ファイル(F)」→「開き直す(W)」のサブメニューの「開き直す(W)」のすぐ下に「読み取り専用で開き直す」を追加して欲しいです。
追記がよくされるログファイル等をサクラエディタで開く時にも有益な機能だと思います。

いつもはあるファイル(*.pas)を他のソフト(Delphi)で開いているけど、
時々、サクラエディタで開いた後に読み取り専用で開き直したくなる時があるのですが、
いちいち開いているファイルを

1. 「ファイル(F)」→「開く(O)」をクリック
2. 「ファイルを開く」ダイアログボックスで「ファイル名」を探してから選択して、
3. 「読み取り専用ファイルとして開く(R)」にチェックを入れて「開く(O)」ボタンをクリックして完了。

この手間がメニューにあればかなり減ると思います。

## スクリーンショット
スクリーンショットの赤矢印の位置に「読み取り専用で開き直す」を追加して欲しいです。
![image](https://user-images.githubusercontent.com/11251874/74105654-18708080-4ba3-11ea-980e-13d745adeaf6.png)

**Comment by ds14050** [comment]
機能としては  メインメニュー > 設定(&O) > ビューモード(&R) と同じですか？

自分は Ctrl+R ……は置換ダイアログだから、Ctrl+V ……は貼り付けだから、Ctrl+Shift+R でいいや、という感じでショートカットキーを割り当てています。

**Comment by arigayas** [comment]
> 機能としては メインメニュー > 設定(&O) > ビューモード(&R) と同じですか？

たぶんこれと同じですw
欲しい機能がこの位置にあって気付かなかったってことは位置が悪いかな？

**Comment by ds14050** [comment]
うまく整理と使い分けができるようにはなっていないのが残念ですが、サクラエディタにはビューモードと上書き禁止として区別される２つの状態があります。

* 上書き禁止
* * ファイルに読み取り専用属性が付いていると適用される。
* * エディタで内容の編集が可能。
* * 上書き保存できない。
* ビューモード
* * ファイルシステム属性とは無関係なエディタのモード
* * エディタで内容の編集ができない。
* * 上書き保存できない。

>位置が悪いかな？

属性の帰属から考えてファイルメニューにあってもいいのかなと思うのですが、自分がそこにあってほしいと思うものは、ビューモードではなくて上書き禁止モードなんですね。読み取り専用属性とは無関係に上書き禁止モードを適用したいと、以前から要望を持っていました。

**Comment by ds14050** [comment]
**訂正** ver.2.2.0.1 より後のどこかのバージョンから上書き禁止モードでも編集ができなくなっているみたいです。残念です。タイトルバーを見ることで「上書き禁止」と「ビューモード」の２つのモードが区別できるのですが、実質的な差異がわからなくなってしまいました。編集できないのが残念です。

実質的に１つのモードしかないのなら、ファイルメニューにある項目がビューモードのようなものを指定するものであっても致し方ないでしょうね。

**Comment by arigayas** [comment]
上書き禁止は、サクラエディタでも他のソフトでも上書き保存が禁止になっているファイルの状態で
ビューモードは、サクラエディタではファイルの編集や上書き保存を禁止して、他のソフトではファイルの編集や上書き保存が可能なファイルの状態かな？と思いました。

ファイル属性に「読み取り専用」フラグを付けた状態で
サクラエディタVer. 2.3.2.0で開いて
テキストを選択した状態で「右クリックメニュー」は
![image](https://user-images.githubusercontent.com/11251874/74135831-55cf1f80-4c30-11ea-8298-892b72a88264.png)
こうなるんですね。
ちなみにビューモードでも同じでした。

**Comment by usagisita** [comment]
>ver.2.2.0.1 より後のどこかのバージョンから上書き禁止モードでも編集ができなくなっている

ちょっと気になって調べてみました。
ソースコードと最近の変更履歴を追ってよくわからなくて、いろいろ見てみた感じでは、
[共通設定]-[ファイル]タブ-「上書き禁止検出時は編集禁止にする」がON(デフォルトでONです)になっていると、読み取り専用ファイルを開いた時に編集不可になるみたいです。
チェックをOFFにしたら編集できました。
(違ってたらごめんなさい)

**Comment by ds14050** [comment]
(ビューモードと区別される)上書き禁止モードは健在だったのですね。お騒がせしました> @usagista さん。

メニュー項目の何がどこにあったらわかりやすいかは主観と慣れですから何とも言えません。設定で変更できるのですから、初期値は気易く変えてもいいんじゃないでしょうか。……と書きつつメニューの設定画面を見たところ、「ビューモード」という項目はしれっと「ファイル操作系」に入ってるんですね。「開き直す」と同じカテゴリです。

**Comment by arigayas** [comment]
スクリーンショットを撮ったので貼っておきますw

![image](https://user-images.githubusercontent.com/11251874/74151845-61324300-4c50-11ea-873f-06aa749d0951.png)

**Comment by berryzplus** [comment]
メインメニューのデフォルト設定値は、
utf-8でエンコードされたcsvテキストリソースとして添付されていた気がします。

サクラエディタのプログラム内の機能コードは、基本的には列挙型 EFunctionCode で扱われているのである程度メンテしやすくなっています。「ファイルを開く」の機能コードは30102で覚えにくいですが、列挙値ならば F_FILEOPEN です。列挙値のほうなら、ギリで覚えられないこともないっていいう・・・。

メニュー定義をコンパイラを通さないcsvテキストで行うことにより機能コードがマジックナンバーになってしまい、メンテしづらくなっているのかも知れません。

関係ないですが、おいらのサクラエディタのCtrl+Shift+RはGrep置換に割り当たっています。
使い方は人それぞれっすね:smiley:

**Comment by arigayas** [comment]
まとめると「ビューモード」の配置の初期値を
「メインメニュー」 > 「設定(&O)」 > 「ビューモード(&R) 」
から
「メインメニュー」 > 「ファイル(&F)」 > 「開き直す(&W)」 > 「ビューモード(&R) 」
に変更で良いのでしょうか？

**Comment by ds14050** [comment]
ビューモードが元々ファイル操作系にカテゴライズされているのだから、
「設定」の中にあったのは何かの間違いで、「ファイル」メニューの中に
再編成してもいいのではないか、その方がわかりやすいと思います、という
ふうにまとめては？

ビューモードと開き直すはどちらもファイル操作系として同列であり、上下関係ではないと思います。

(初期は違うように書いていましたが、)ビューモードは上書き禁止を包含していますから、ユーザーがイメージする操作対象としてファイルを想定するのはありだと思います。

**Comment by ds14050** [comment]
黙らせてしまったので補足します。

ファイルを開くダイアログに「読み取り専用ファイルとして開く」チェックボックスがあるのは、自動実行マクロに悪さをさせないことを考えると、他にタイミングがないことが理解できます。

これはファイルを開く側の論理・都合であり、逆向きの、ビューモードを有効にするのにファイルを開く(開き直す)必要があるという事情からそうなっているわけではありません。これは、ビューモードのオンオフがアンドゥバッファや更新フラグをクリアしないという観察結果から推定されます。

@arigayas さんはファイルを開くダイアログでしか機能を知らなかったために、「開き直す」の下に「読み取り専用で開き直す(=ビューモードを指定することと同じ)」が欲しいと要望しましたが、私の視点では、ビューモードを有効にするためにファイルを開くダイアログを使用したり、「開き直す」のサブメニューを探すということは、思いもよらないことです。

仮に「上下分割状態でファイルを開く」というチェックボックスが隣にあったと考えてみて下さい。「上下に分割」コマンドを「開き直す」の下に配置するのでしょうか。

**Comment by arigayas** [comment]
@ds14050 さんは

> 私の視点では、ビューモードを有効にするためにファイルを開くダイアログを使用したり、「開き直す」のサブメニューを探すということは、思いもよらないことです。

「開き直す(&W)」の下に「ビューモード(&R) 」を絶対に置いて欲しいと言うわけではないのと
「開き直す(&W)」をクリックして「ビューモード(&R) 」に切り替えるのはちょっと手間だと思ったので
![image](https://user-images.githubusercontent.com/11251874/74667573-d53b9080-51e6-11ea-9809-5f2721c22eae.png)

保存して閉じる(&E)
閉じる(&C)
閉じて(無題)(&R)
閉じて開く(&L)
開き直す(&W)

のグループのどこに移動するのが良いと思いましたがいかがでしょうか？

@berryzplus さん
PRを作っていただいたのにすみません。

**Comment by ds14050** [comment]
>どこに移動するのが良いと思いましたがいかがでしょうか？

ファイルメニューの直下のどこかというところまでしか考えていませんでした。検討したところでは

* ファイルのプロパティ
* ブラウズ

と同じグループが適当なのではないかと思いました。(開く・保存するグループを今以上にごちゃごちゃさせたくない。印刷グループに混ぜるには場違い感。現在開いているファイルが操作の対象である、雑多なところに放り込んでおこう)

> @berryzplus さん PRを作っていただいたのにすみません。

なんの結論が出たわけではありませんよ。私には「メインメニュー「ビューモード」の初期配置位置が論理的に妥当な位置になります」ということの論理に見当がついていませんし、決定権もありません。

**Comment by arigayas** [comment]
> 印刷グループに混ぜるには場違い感

激しく同意します。
少し考えてみたところ、開き直す(＆W)の下が良いかな？と思ってます。

![image](https://user-images.githubusercontent.com/11251874/74676593-ad095d00-51f9-11ea-8cf3-1bfeaf00db05.png)





> ファイルメニューの直下のどこかというところまでしか考えていませんでした。検討したところでは
> 
>     * ファイルのプロパティ
>     * ブラウズ
> 
> 
> と同じグループが適当なのではないかと思いました。

具体的にはどの位置に追加されるのが良いと思われますか？

**Comment by ds14050** [comment]
> 具体的にはどの位置に追加されるのが良いと思われますか？

そこまでいくとあとは感覚の問題なので、どこでもいい、です。

すでにちらっと書きましたが、ビューモードと上書き禁止モードを区別して使い分けたい気持ちがありますから、計画もない先のことですが、プロパティとブラウズの間に挿入してしまうと、上書き禁止モードとビューモードの２つを独立してグループ化するのに支障があるかな、という予想ができるだけです。

**Comment by ds14050** [comment]
どこが最適だと思うかはすでに述べましたが、次点は保存メニューの再下段あたりです。

ビューモードのメニュー項目はアイコンによってトグル状態を表現していますから、ビューモードにより保存が禁止されていることが、位置の近接性により気付きやすくなります。

**Comment by berryzplus** [comment]
> どこが最適だと思うかはすでに述べましたが

明言しとらんので確認のために訊いてるだけかと思います。

**Comment by ds14050** [comment]
> > どこが最適だと思うかはすでに述べましたが
> 明言しとらんので確認のために訊いてるだけかと思います。

@arigayas さんにもこれを補足訂正するコメントが必要でしょうか？

「すでに述べた」とは直前の自身のコメント( https://github.com/sakura-editor/sakura/issues/1189#issuecomment-587352401 )を指しています。「保存メニューの最下段」という補欠候補を挙げるにあたり、優先順位を勘違いされたくないので念のために枕として書いたものです。

**Comment by berryzplus** [comment]
> > > どこが最適だと思うかはすでに述べましたが
> > 
> > 明言しとらんので確認のために訊いてるだけかと思います。
> 
> @arigayas さんにもこれを補足訂正するコメントが必要でしょうか？
> 
> 「すでに述べた」とは直前の自身のコメント( https://github.com/sakura-editor/sakura/issues/1189#issuecomment-587352401 )を指しています。「保存メニューの最下段」という補欠候補を挙げるにあたり、優先順位を勘違いされたくないので念のために枕として書いたものです。

う～む。https://github.com/sakura-editor/sakura/issues/1189#issuecomment-587352401 では「どこでもいい」と言ってるように見えます。

どこでもいいと言う人が、何故「開き直す」の下じゃダメだと言えるのか分からんです。

どこか適切な場所があると思ってるから「思いもよらない」が出てきたはず。
じゃあそれはどこよ？に対して明言がないから質問が付いたと理解します。

**Comment by ds14050** [comment]
> う～む。#1189 (comment) では「どこでもいい」と言ってるように見えます。

@arigayas さんにもこれを補足訂正するコメントが必要でしょうか？

私は「そこまでいくと～(略)～どこでもいい」と書きました。そこまでがどこまでかは @arigayas さんのコメント( https://github.com/sakura-editor/sakura/issues/1189#issuecomment-587104761 )にある通りです。

**Comment by ds14050** [comment]
> 何故「開き直す」の下じゃダメだと言えるのか分からんです。

ダメとは言っていませんがそうする理由があるとも思っていません。

理由が示されていないので想像するしかありませんが、@arigayas さんは自身のこれまでの習慣に基づいて「開き直す」の下を候補にしています。

しかしビューモードとファイルを開く操作に関連がないことは https://github.com/sakura-editor/sakura/issues/1189#issuecomment-586878615 で述べました。

ファイルを開いた後でビューモードを指定するよりはファイルを開くダイアログのチェックボックスを使用した方がいい理由を同じコメントに書きました。

ビューモードを有効にしてからファイルを開く操作をした場合にビューモードは解除されます。開き直した場合は解除されませんが、ビューモードが目的なら後から開き直す理由がありません。

以上、３点書きました。開き直すの下に移動する道理がないこと、ミスリーディングになりかねないこと、実用的な理由がないこと。

**Comment by berryzplus** [comment]
で、結局どこやねんっｗ

「このグループ」とまでしか書いてないから「どこ？」って訊いてます。
メインメニュー設定と同じ「ブラウズの次」でいいんですよね？

**Comment by arigayas** [comment]
蛇足ですが
> 少し考えてみたところ、開き直す(＆W)の下が良いかな？と思ってます。
> 
> ![image](https://user-images.githubusercontent.com/11251874/74676593-ad095d00-51f9-11ea-8cf3-1bfeaf00db05.png)
> 


私が`開き直す(＆W)`のサブメニューに置いて欲しいと言っていたのに
上位のメニューの`ファイル(＆F)`の直下のメニュー上に変更しようと思ったのは
ビューモードの有効/無効するのにクリック数を減らした方が良いと思ったからです。

**Comment by arigayas** [comment]
> すでにちらっと書きましたが、ビューモードと上書き禁止モードを区別して使い分けたい気持ちがありますから、計画もない先のことですが、プロパティとブラウズの間に挿入してしまうと、上書き禁止モードとビューモードの２つを独立してグループ化するのに支障があるかな、という予想ができるだけです。

私としては
* ファイルのプロパティ
* ブラウズ

の間だけではなく、この2つの上や下にも選択肢があると思ってました。
解りにくくてごめんなさいです。

---
> 理由が示されていないので想像するしかありませんが、@arigayas さんは自身のこれまでの習慣に基づいて「開き直す」の下を候補にしています。

開いていたファイルを`読み取り専用`として`開き直す`って意味で
`開き直す(＆W)`のサブメニューに`ビューモード`を置いて欲しいと言ったのですが1つ前で撤回しました。

---
> どこが最適だと思うかはすでに述べましたが、次点は保存メニューの最下段あたりです。

よく解らなかったですがこういうことですか？
![image](https://user-images.githubusercontent.com/11251874/74792920-1c6a7400-5302-11ea-997d-085abfa2a395.png)

**Comment by ds14050** [comment]
> > どこが最適だと思うかはすでに述べましたが、次点は保存メニューの最下段あたりです。
>
> よく解らなかったですがこういうことですか？

そういうことです。

しかしそれは次点です。使用頻度の高くなさそうなメニューをあまり上の方に持っていきたくはありませんし、他の保存メニューに比べても異質です。

> @arigayas「開いていたファイルを読み取り専用として開き直すって意味で開き直す(＆W)のサブメニューにビューモードを置いて欲しいと言ったのですが1つ前で撤回しました。

１つ前ではなくこの時点ですよね？> https://github.com/sakura-editor/sakura/issues/1189#issuecomment-587104761

親切に画像も添付されているので間違いなく理解しています。逆に私の言葉が誤解させていますが、「@arigayas さんは自身のこれまでの習慣に基づいて「開き直す」の下を候補にしています。」の下とは、サブメニューのことではなく画像で示された通りの下です。

> @arigayas「私が開き直す(＆W)のサブメニューに置いて欲しいと言っていたのに上位のメニューのファイル(＆F)の直下のメニュー上に変更しようと思ったのはビューモードの有効/無効するのにクリック数を減らした方が良いと思ったからです。

開き直すの隣であるべき理由はありますか？ それは習慣や、機能に対するこれまでの限定された理解とは異なる理由ですか？

> @berryzplus「で、結局どこやねんっｗ

> @arigayas「私としては ファイルのプロパティ ブラウズ の間だけではなく、この2つの上や下にも選択肢があると思ってました。

その通りです。間に挿入するのは将来に多少の不都合が予想されるので上か下が望ましいけれど、実際のところそこまでの詳細は「どこでもいい」のです。

----

振り返るとこれまで書いていませんでしたが、私の素の意見は「現在の設定メニューの下で問題ない」というものです。ビューモードがそこにある理由は理解できるつもりです。

設定メニューの中にはエディタの一時的な状態(モード)を変更するコマンドが集められています。ビューの分割状態は例外的にウィンドウメニューの中にありますが、ツールバーやステータスバーの表示状態、エンターキーで入力される改行のコード、折り返し方法などです。ビューモードというのもエディタが持つモードのひとつです。だからそこにあります。

しかしそれは実装者に寄った見方だと思うから、歩み寄る余地があると考えました。

> 設定で変更できるのですから、(メニュー項目の)初期値は気易く変えてもいいんじゃないでしょうか。

> 「ビューモード」という項目はしれっと「ファイル操作系」に入ってるんですね。「開き直す」と同じカテゴリです。

> ビューモードは上書き禁止を包含していますから、ユーザーがイメージする操作対象としてファイルを想定するのはありだと思います。

などが私自身の考えや見つけたヒントであることは間違いありませんが、歩み寄る姿勢を示すことを第一の目的としています。

**Comment by arigayas** [comment]
前半部分は後日に。

---

まとめると @ds14050 さんは`ビューモード`の位置を変える必要がないということですね？
でも歩み寄って`ビューモード`の位置を変えるのなら
![image](https://user-images.githubusercontent.com/11251874/74798087-26936f00-5310-11ea-84a7-f32559c0e945.png)
という感じでしょうか？

**Comment by berryzplus** [comment]
やっと繋がったw

当初の提案は既に破棄されてると思いますが、一旦閉じてはどうでしょう。

**Comment by arigayas** [comment]
@ds14050 さんのコメントを待ってから閉じます。

**Comment by ds14050** [comment]
ファイルメニューの中に置く理由も設定メニューの中に置く理由もあると思うから、望む人がいるならファイルメニューの中に移動する案も支持しています。

開き直すのサブメニューに移動して欲しいという当初案から開き直すの下へという要望の変更理由は、クリックのしやすさとして理解できました。別件ですが私もこれに同調しています。「[実装して使ってみたんですが、私はトップの階層にあったほうが使いやすいと思いました。  サブメニューをたどるのがめんどくさい。](https://github.com/sakura-editor/sakura/issues/1100#issuecomment-578383602)」

しかし、なぜ開き直すのサブメニューなのか、なぜ開き直すの下なのかという理由はまだ聞けていないように思います。

だから想像するのですが、PR の概要欄に書いてあるように、ビューモードを設定するのにダイアログを使って同名のファイルを開き直す操作しか知らなかった頃の名残でしかないのではないかと。それだけなら @arigayas さんの個人的事情であり、多くの人の使いやすさに繋がりません。

どうして元の場所がだめで新しい場所に移動してきたのか、言われなくても予想できることが一番に、説明されて納得できることが二番目に求められると思います。それでなければ移動しない方がいいということになります。

**Comment by arigayas** [comment]
> 別件ですが私もこれに同調しています。「実装して使ってみたんですが、私はトップの階層にあったほうが使いやすいと思いました。 サブメニューをたどるのがめんどくさい。」

物によっては同意する可能性は高いと思います。

> なぜ開き直すの下なのかという理由はまだ聞けていないように思います。

開き直すのすぐそばだからという単純な理由です。

> しかし、なぜ開き直すのサブメニューなのか
> だから想像するのですが、PR の概要欄に書いてあるように、ビューモードを設定するのにダイアログを使って同名のファイルを開き直す操作しか知らなかった頃の名残でしかないのではないかと。

ご想像の通りです。

> どうして元の場所がだめで新しい場所に移動してきたのか、言われなくても予想できることが一番に、説明されて納得できることが二番目に求められると思います。それでなければ移動しない方がいいということになります。

元の場所が駄目だと思ったのは自分が見逃していたのが大きいです。
つまり 元の場所の 設定(&O) → ビューモードってサクラエディタ自体というか全体に対しての設定だと思っていたのでそんなに見ていませんでした。

スクリーンショットの赤枠で囲った部分の
![image](https://user-images.githubusercontent.com/11251874/74893150-0080d400-53cf-11ea-9b34-bd8d6cac41c2.png)

- 挿入/上書きモードの切り替え(&I)
- ビューモード(&R)
- 文字コードセット指定(&A)
- 入力改行コード指定(＆E)

って現在開いているファイルに対する設定なので ファイル(＆F)に移動するのが良いのでは？と膨らみました。

**Comment by ds14050** [comment]
考えてもらいたいのでもう少し語ります。ファイルメニューに移動することは支持するのに @arigayas さんの要望を全面的には支持しない理由の説明にもなっています。

自分の中でもはっきりさせていなかったので暗黙の前提としてしまっていましたが、私はメニュー項目の適正位置を考えるにあたり

1. 予測可能で見つけやすいこと
2. 納得感があって覚えやすいこと
3. 使いやすいこと

を尺度として持っています。今回はさらに、@arigayas さんという誤った学習をしてしまった人の実例を前にして、もう少し目立つ位置にあれば第二第三の @arigayas さんを減らすことができるのではないかと考えました。そのためのファイルメニューへの移動です。

> @arigayas「元の場所が駄目だと思ったのは自分が見逃していたのが大きいです。

だからこの点で私と @arigayas さんの現状認識は一致しています。しかし対策案でずれがあります。

注意してもらいたいのは、私にとって @arigayas さんの事例は４番目に追加されたファクターに過ぎないということです。それも、誤った学習をしてしまった人のためではなく、誤った学習をしてしまわないためのメニュー構成を考えています。それでなければ効用が最初から特定の対象に限られてしまいます。

----

以下各論です。

サブメニューに配置するというのはクリックのしにくさだけでなく見つけにくさにもつながりますから支持できません。だから要望の修正は良かったと思います。

開き直すの側というのは誤った学習をした人にとって予測が容易なのかもしれませんが、これまで「設定」>「ビューモード」を使用していたユーザーにとって予測や納得ができる位置であるという説明は受けていません。そして先ほど書いたように、「誤った学習をしてしまった人のためではなく、誤った学習をしてしまわないためのメニュー構成を考えています。」

----

> って現在開いているファイルに対する設定なので ファイル(＆F)に移動するのが良いのでは？と膨らみました。

それを言ってしまうと、ファイルメニューの項目数には妥当な上限がありますし、サブメニューは使い勝手の悪さにつながりますから、ファイルに関する一時的な状態の設定は設定メニューの中のファイルに関するグループの中にまとめておこう(※現状)という結論に道を開きます。

**Comment by berryzplus** [comment]
今のままの位置でいいんじゃね？に1票です。

読み取り専用を「モード」と捉えるなら設定で正しい気がするからです。

**Comment by arigayas** [comment]
ビューモードの位置の変更はしない　という結論でOKです。

**Comment by berryzplus** [comment]
> 今のままの位置でいいんじゃね？に1票です。
> 
> 読み取り専用を「モード」と捉えるなら設定で正しい気がするからです。

別解として `読み取り専用は「モード」じゃねーよ` という考え方もできます。

「モードじゃない」の根拠は、設定変更がエディタ全体に伝播しないからです。
「設定」メニューにある他の設定は、設定変更すると変更がエディタ全体に伝播します。

読み取り専用の設定がエディタ全体に伝播すると、状況によっては困ると思います。

読み取り専用モードは、ある意味でモードだと思います。
でも、ある意味で他のモードと違う特性を持っています。
その特性（モードがファイルに帰属する、設定が保存されない）をどう扱うかで結論は変わってくるのかな、と思っています。（このissueは終わりで良いですが :smile:

**Comment by ds14050** [comment]
私は https://github.com/sakura-editor/sakura/issues/1189#issuecomment-588007390 において「モード」をエディタの一時的な状態と定義して使用しました。例として挙げたのは「ビューの分割状態」「ツールバーやステータスバーの表示状態」「エンターキーで入力される改行のコード」「折り返し方法」です。ツールバーやステータスバーの表示状態を挙げたのは失敗でした。それだけは、設定の変更がすべてのエディタウィンドウに伝播し、ini に保存されます。しかしそれ以外は特定のドキュメントにしか影響しない一時的な状態です。そういうものを指して「モード」と呼びました。「[ファイルに関する一時的な状態](https://github.com/sakura-editor/sakura/issues/1189#issuecomment-588586251)」という表現も使用しました。

@arigayas さんは https://github.com/sakura-editor/sakura/issues/1189#issuecomment-588569260 において、「設定(&O) → ビューモードってサクラエディタ自体というか全体に対しての設定だと思っていた」と書いたあとで、ビューモードを含む複数の項目を「現在開いているファイルに対する設定」として括りだし、設定メニューからファイルメニューに移動するのがふさわしい候補だと示唆しました。@arigayas さんは要望を出した時点でビューモードがエディタ全体に伝播する設定ではなくファイルに帰属するものだと理解していました。

つまりどういうことかというと、「エディタ全般に影響が伝播するもの」としての「モード」の話を、私と @arigayas さんはしていません。当初から論点がファイルメニューに移動するというところにあったように、「モードがファイルに帰属する」、必然的に「設定が保存されない」(※例外はMRU付随情報)、ビューモードの話を最初からしています。

**Comment by berryzplus** [comment]
なんかすんませんね。 @ds14050 さんが誤った理解で素っ頓狂なコメントしてるとは、1㍈も思っとらんです。何を思ってわざわざ敵対的な書き方をしてるのか、理解不能ではありますが :smile:

- ファイルに帰属する保存されない設定を「モード」と呼ぶ。
- 設定メニューの下半分は元々ファイルに帰属してるから現状でいい。

「～と同じ」は「そこにある理由」として充分だと思うので、結論は変わらずです。

ただ、「設定」と「モード」がベツモノならば、グループ分けを組みなおす検討をしてみるのもよいと思います。歩み寄ってみた理由はそこにあったのかな、と把握しました。

そして、「～で開き直す」というメニューはおかしい気がしてきました。
だって、「文字コード」は「モード」じゃないですか。

「開き直す」だけならI/O操作なので、「ファイル」メニューなのはいいと思います。
「SJISで開き直す」は文字コードの変更がメインのように思います。
モードを変えただけでは反映されないエディタ表示を更新するために開き直してるだけな気がします。

ということを考えてみたわけですが、いまんとこ具体的にどうするかのアクションを起こす予定はしていません。

**Comment by ds14050** [comment]
> 何を思ってわざわざ敵対的な書き方をしてるのか、理解不能ではありますが

「敵対的」というのは受け取る方の解釈ですからご自由に。「わざわざ」というのは邪推ですから慎むように。

弁解がましいことをひとつ書くなら、曖昧さを残さずにはっきりとくどいほどに書ききらないと伝わらないだろうと考えているということがあります。オブラートに包んではこれっぽっちも伝わらない相手であると考えています。

> そして、「～で開き直す」というメニューはおかしい気がしてきました。だって、「文字コード」は「モード」じゃないですか。

言葉の定義からは間違っていませんが、文字コードの変更とファイルを開く操作とは不可分です。それがビューモードと文字コードの違いです。仮にビューモードの適用がファイルを開く操作と不可分であったなら、#1204 に道理がありました。そのへんは https://github.com/sakura-editor/sakura/issues/1189#issuecomment-586878615 の第三第四段落に書きました。

----

モードと呼ぶには文字コードの変更は重い操作です。ファイルを開く操作に与えられたパラメータというのが実際のところです。ファイルを構成するバイト列の解釈が変わるわけですから、内部テキストデータが根底から変わります。その上に構築された関連データも影響を受けます。文字コードを変更する一番のユースケースはファイルを開いた直後の文字化けが明らかになったときでしょうから、ファイルを開く操作と一体でもあまり不都合がないと考えられます。

どのようにして２つを分離するのか、分離してどれだけ嬉しいことがあるのかをまず考えるのがいいでしょうね。

**Comment by berryzplus** [comment]
嫌味のつもりがないのは了解。

サクラエディタは、生データから内部データへの変換を可逆変換となるように行っています。

たとえばShift-JISとしてファイルを読み込む場合、
- A⇒W変換した文字がW⇒A変換できたら「ただの文字」として解釈します。  
変換はShift-JIS変換なので、たまたま逆変換できただけなら化けて表示されます。
- A⇨W変換できなかったら、その文字(1byte)を下位サロゲート領域に退避します。  
退避された文字は、`0xDCAA` のように不正なユニコード文字となるので表示は化けます。
- A⇨W変換できてもW⇒A変換できなかったら、その文字(1byte)も下位サロゲート領域に退避します。  
退避された文字は、`0xDCAA` のように不正なユニコード文字となるので表示は化けます。  ※1

これはサクラエディタの基本要件である **編集データを保存することができる** を満たすためのカラクリです。「編集データを保存することができる」が意味するのは、「編集しなかったデータを改変しない」を含んでいると思いますので、適切なカラクリだと思っています。

※1 歴史的な経緯でShift-JISにはA⇨W変換できてもW⇒A変換できない文字がたくさん存在しています。サクラエディタではそれらの文字を正しく表示することができません・・・つまり、Shift-JISには完全には対応できていません。

はなしが明後日の方向に飛んでしまいましたが、サクラエディタに限っていえば、文字コードを変えるのにデータを読み直す必要はないと思っています。

読み直さなくても、持ってるデータ裏返せば元データになるじゃん？

メニューに「変換」ってグループがありますが、
あれらも持ってるデータが裏返し可能なことを利用した機能です。

たぶん、読込み時自動実行マクロを気にしてるかなと思うんですけど、必ずしも「読む必要」がないのなら読まない方向にすすんでもいいんじゃないかと思っています。

結局、「SJISで開き直す」が分かりやすいんで表示するメニューは変えないんでしょうがｗ
