### ISSUE TITLE
行単位のCut, Copy時のクリップボードのモード

### ISSUE THREAD

**Issue by yoshinrt** [sakura-editor/sakura#119]
サクラエディタのクリップボードには行単位，ブロック，それ以外 (文字単位) の区別 (以下モードと表記します) がありますが，行単位のコマンドであっても，実際にクリップボードに入るデータのモードは
- マウスで行番号ドラッグによる行単位選択→Ctrl+X：文字単位モード
- 選択範囲内全行コピー コマンド：文字単位モード
- 選択せず Ctrl+X：行単位モード

等，揃っていないように見えます．
個人的には 行単位モード に揃えたいのですが，いかがでしょうか．

**Comment by berryzplus** [comment]
こんにちは。
選択とコピーに関する仕様はかなり複雑だと認識しています。
可能であれば整理をしていきたいなぁ、とは感じているのですが
まだ手が回っていない状態です。不明点のご報告は大歓迎です。

ただ、ご提示いただいた３種類については「正しい」というのが私見です。
理由は、行コピーという機能は「無選択状態で」コピーコマンドを発行した場合にカーソル行をクリップボードに入れる機能と認識しているためです。
例示の中では３番目だけが無選択、他は選択がある状態です。

クリップボードの中身を確認されているので、
[clipspy](https://www.codeproject.com/Articles/168/ClipSpy) のようなツールもご存じかと思います。
行コピーの場合、テキストのコピーデータの他にバイナリの付加データが格納されます。
これは visual studio 連携用のデータで、これがある場合とない場合で貼り付け時の動作が変わります。

issueの文面からはこの挙動を認識したうえでの改善要望かどうか判断しかねたので
あえて行コピーを行った場合に期待される動作について書きました。
複数行コピー時にバイナリの付加データをつけた場合にvisual studioがどう反応するかは未検証です。
少なくともサクラエディタとしてはそういうデータ（複数行で行コピー属性を持ったデータ）の貼り付けには対応していない気がします。

**Comment by yoshinrt** [comment]
> これは visual studio 連携用のデータで

これを見て，VS2017 のエディタ触って初めて気づきましたが，未選択状態でCtrl+X，マウスで行番号ドラッグによる行単位選択→Ctrl+X はともに VS2017 と同じ動作だったのですね．
この要望自体が的はずれであったことが理解できました．なのでこの issue は close させていただきます．

> 複数行コピー時にバイナリの付加データをつけた場合にvisual studioがどう反応するかは未検証です。

無理やり複数行の行単位データをクリップボードに貼り付けると，VS2017, サクラエディタともにペースト時は行単位として (少なくとも見た目は) 動作している感じでした．
