### ISSUE TITLE
64bit 版のサクラエディタのファイル名を「sakura64.exe」にして欲しい

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#1198]
## 要望機能

> ６４ビットと３２ビットの区別がわかりやすいように
> ６４ビット版はsakura64.exeとコンパイルしてくれると嬉しい 

サクラエディタふぁんくらぶ part18
https://egg.5ch.net/test/read.cgi/software/1495286392/938
からの要望の転載です。

**Comment by berryzplus** [comment]
改名することで分かりやすくなるシチュエーションがイメージできませんでした。
64bit版のファイル名をsakura64.exeに変えると、なにが分かりやすくなるんですかね？

2chにもレス付いてますが、サクラエディタには「実行ファイル名に数字が含まれていたら、その数字に対応する内部コードセット番号を文字コード未指定時のデフォルト選択とする」という誰得仕様が実装されとります。

内部コードセット64番は存在しないので、
ファイルを開くときは常に内部的なエラー状態になると予想されます。
（文字コード指定が異常な場合にフォールバックしてるかどうかは見てないっす。）

"sakura64.exe -C 99 %1" みたいなショートカット作れば回避できなくはないっすけど、普通に不便なんじゃないかと思ったりします。

**Comment by arigayas** [comment]
改名の利点は32bit 版と64bit 版を同じフォルダに置いた時に判断が付く事ぐらいでしょうか？
と思ってissue登録してみましたが

> 2chにもレス付いてますが、サクラエディタには「実行ファイル名に数字が含まれていたら、その数字に対応する内部コードセット番号を文字コード未指定時のデフォルト選択とする」という誰得仕様が実装されとります。

誰得仕様が邪魔ですね・・・。

**Comment by berryzplus** [comment]
エラー時フォールバックしてますね。
`sakura64.exe` に改名しても当面問題は出なさそうです。

https://github.com/sakura-editor/sakura/blob/0287672319be695e1348843341d01e7b2d64acbc/sakura_core/CReadManager.cpp#L51-L63

`IsValidCodeOrCPType` というのが、認識できる文字コードをチェックする関数です。
異常値だったら判定されたタイプ別設定のデフォルトを選択するようになってます。

ちなみに `sakura64.exe` で使う場合、設定ファイルは `sakura64.ini` になります。
用意しなかった場合は勝手にその名前のiniが生成されます。
オススメはできないけど、その配置でやって正しく動作させる方法がないわけじゃなさそうです。

**Comment by k-takata** [comment]
何のために64bit版と32bit版を区別したいのだろうというのが気になるところです。（そもそも64bit版は正式リリースされてないわけですが）

**Comment by KENCHjp** [comment]
>何のために64bit版と32bit版を区別したいのだろうというのが気になるところです。（そもそも64bit版は正式リリースされてないわけですが）

Office製品なんかはインストーラ等でなにBit版かわかるかもしれませんが、sakura.exeの場合はexe単体で持ち込む場面も多いので(私の周り)、将来的に正式リリースされたらファイル名でわかった方がいいかなって思われてるのかなと。

ただ仕事で使う場合、32Bit環境はほぼ無いと思うので（かな？）、
64Bit版SAKURAを間違って32BitOS環境に持ち込む場面はほぼほぼないのかも。
VM環境とかで32Bit環境が残ってるところはあるのかもしれませんけど。。。

exeファイルのプロパティの詳細情報でわかればいいのかもしれませんね。

**Comment by arigayas** [comment]
exe ファイルのプロパティの詳細情報 の「ファイルの説明」にも「サクラエディタ 64bit版」ってあるのが良いのかもしれません。

ローカルビルド版のexe ファイルのプロパティの詳細情報
![image](https://user-images.githubusercontent.com/11251874/74616940-eac0a400-516d-11ea-8564-1c1e3cc80b92.png)

**Comment by berryzplus** [comment]
生成時のファイル名をsakura64.exeにすると元のファイル名に表示される感じですかね。後で試してみます。

**Comment by berryzplus** [comment]
> 生成時のファイル名をsakura64.exeにすると元のファイル名に表示される感じですかね。後で試してみます。

試してみました。
　↓
「元のファイル名」は `sakura.exe` のままです。
　↓
リソーススクリプトのバージョン情報をチェックしてみました。
　↓
https://github.com/sakura-editor/sakura/blob/0287672319be695e1348843341d01e7b2d64acbc/sakura_core/sakura_rc.rc#L2155-L2157

ここに入れる値をdefineしてあげれば「元ファイル名」に `sakura64.exe` を表示させることは可能です。出力ファイル名を `sakura.exe` のまま据え置いた状態で、です。

たぶん、 32bit なのか 64bit なのか、実行してみるまで分からない、って状況がマズいって話だと思うので、検討してみる価値はあると思います。

**Comment by KENCHjp** [comment]
＞実行してみるまで分からない

はい、んで、製品バージョンのところでわかるからいいかなぁって思ったのですが、いかがでしょう？（すいません、伝え方が悪くて）

**Comment by arigayas** [comment]
64bit版サクラエディタのファイル名が sakura64.exe となっていれば、
ファイルをクリックして製品バージョンを確認しなくてもわかるのは便利だと思います。


---
あと妄想なのですが、今後64bit版サクラエディタがalpha版じゃなく正式版としてリリースされたら
32bit版と64bit版サクラエディタのインストーラーは別々に作るのでしょうか？
それとも(実現可能か知りませんが)インストーラーに32bit版と64bit版を同梱してユーザーにインストールしたいバージョンを選んでもらうのでしょうか？

**Comment by KENCHjp** [comment]
>ファイルをクリックして製品バージョンを確認しなくてもわかるのは便利だと思います。

サクラエディタを外部から呼び出している人は少ないかもしれませんが、もしそういうのがあると、環境によって32Bitのサクラを呼び出すときと、64Bitのサクラを呼び出す分岐が発生するかなとか。

個人的には同梱はしない（インストーラー別作成）かと思っております。
一般的なソフトもインストーラー別な方がおおいんじゃないかしら。

**Comment by beru** [comment]
ユーザー側でシンボリックリンク作成すれば済む話な気がしますけど、そういうのも面倒くさいという事かなぁ。。ある程度多数のユーザーが必要としている事でなければ開発側が対応するべきではないと思います。

**Comment by arigayas** [comment]
> ユーザー側でシンボリックリンク作成すれば済む話な気がしますけど、そういうのも面倒くさいという事かなぁ。。ある程度多数のユーザーが必要としている事でなければ開発側が対応するべきではないと思います。

シンボリックリンクという概念を知らないユーザーもいますし、
シンボリックリンク作成はちょっと面倒くさいです・・・。

**Comment by berryzplus** [comment]
https://github.com/sakura-editor/sakura/issues/1198#issuecomment-587053328 で言ってる「元のファイル名」を「sakura-x64.exe」にするってい対応を「`sakura.rc2`を導入する」にかこつけてやってみるのはどうでしょう？

**Comment by m-tmatma** [comment]
> 何のために64bit版と32bit版を区別したいのだろうというのが気になるところです。（そもそも64bit版は正式リリースされてないわけですが）

@arigayas さんは、ご自身の利用シーンで
区別したいと思うのはどんな時ですか？

チケット登録されたので、何か思うところがあったのかと思いますが、何か想定してるものはありますか？

**Comment by arigayas** [comment]
サクラエディタの32bit版と64bit版を同じフォルダに入れおいて、
大きなテキストファイルを開きたい時には64bit版を使いたいと思いました。

使用目的は違いますがCrystalDiskMark6 は32bit版と64bit版を同じフォルダに入れてますね。
![image](https://user-images.githubusercontent.com/11251874/81460594-4f295780-91e1-11ea-93ea-87d97baacbe3.png)

**Comment by m-tmatma** [comment]
> 大きなテキストファイルを開きたい時には64bit版を使いたいと思いました。

常に 64bit 版使えばいいんじゃないかと思うのですが、
逆にめんどくさくないですか?

**Comment by arigayas** [comment]
> 常に 64bit 版使えばいいんじゃないかと思うのですが、
> 逆にめんどくさくないですか?

確かにそうですが64bit版が正式リリースされるまでは併用しようかな？と思っていたのです。

**Comment by m-tmatma** [comment]
ということは、このチケットの要望機能は、
正式リリースされたら、いらなくなるということですか?

**Comment by arigayas** [comment]
そうですね。

将来的に64bit版のみがリリースされるようになったら、このissueは不要になりますが、
しばらくは32bit版も一緒にリリースされると思うので
それまでは sakura64.exe があったらちょっとだけわかりやすいと思ってます。


別件ですがサクラエディタのインストーラー版の32bit版と64bit版を両方インストールした場合、
`プログラムと機能`のウィンドウで32bit版と64bit版か区別が付かないと思いました。
![image](https://user-images.githubusercontent.com/11251874/81474614-a65f1480-9241-11ea-9fd7-f62e005968cc.png)

**Comment by berryzplus** [comment]
> 別件ですがサクラエディタのインストーラー版の32bit版と64bit版を両方インストールした場合、`プログラムと機能`のウィンドウで32bit版と64bit版か区別が付かないと思いました。

インストーラの改善は必要っぽいですね。
ちょっと違う話になっちゃいますけど :smiley:

**Comment by m-tmatma** [comment]
> 別件ですがサクラエディタのインストーラー版の32bit版と64bit版を両方インストールした場合、
> `プログラムと機能`のウィンドウで32bit版と64bit版か区別が付かないと思いました。
> ![image](https://user-images.githubusercontent.com/11251874/81474614-a65f1480-9241-11ea-9fd7-f62e005968cc.png)

#1293 で対処済み

**Comment by berryzplus** [comment]
結局、タイトルに 64bit って出るからいいじゃんね、が結論だと思うので閉じておきます。
