### ISSUE TITLE
ツールバーのアイコン 2.4.0にアップデートしたら今まで使えてたのが使えなくなって全部空白になった

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#1243]
https://egg.5ch.net/test/read.cgi/software/1495286392/971

https://egg.5ch.net/test/read.cgi/software/1495286392/973

**Comment by arigayas** [comment]
971名無しさん＠お腹いっぱい。2020/04/19(日) 23:33:30.90ID:7TDePxMq0
> ツールバーのアイコンって、my_icons.bmpの名前で本体と同じ場所に置けばよかったはずだよね？
> 2.4.0にアップデートしたら今まで使えてたのが使えなくなって全部空白になったんだけど 

973名無しさん＠お腹いっぱい。2020/04/20(月) 00:05:42.97ID:ehl1ZmaL0
> どういうことかというとビットマップのサイズを32x15で
> それぞれ割った数(少数以下切捨て)がアイコンの縦と横の幅になる
> その縦と横が同じでないすなわち正方形でないとエラーになるようになってる
> でもってそのエラーをフォローするコードはないので真っ白透明になる
> 528/32=16.5→16
> 240/15=16
> 特に昔のやつ縦幅が239以下とか足りないとアウト

**Comment by berryzplus** [comment]
要約すると、この1文の対応をしたら良いと言ってるのかな？

> でもってそのエラーをフォローするコードはないので真っ白透明になる

ここの処理のことを言ってそうな気がする・・・。
https://github.com/sakura-editor/sakura/blob/2c80b73a2416eb411fe03df9b1703f28143a5854/sakura_core/uiparts/CImageListMgr.cpp#L600-L606

呼び出し元はコレだから、ここのif文が間違ってるのね。
https://github.com/sakura-editor/sakura/blob/2c80b73a2416eb411fe03df9b1703f28143a5854/sakura_core/uiparts/CImageListMgr.cpp#L156-L161

わかんないけど、これをやれ、と言ってるのかな？
https://github.com/sakura-editor/sakura/blob/2c80b73a2416eb411fe03df9b1703f28143a5854/sakura_core/uiparts/CImageListMgr.cpp#L102-L115

コメント内容の修正を行えば、少なくとも真っ白になる事態は解消できそうです。

**Comment by beru** [comment]
#1261 が merge されて問題が解消したと思うので close します。
