### ISSUE TITLE
正式リリース版バイナリのレガシーOSとの互換性

### ISSUE THREAD

**Issue by Xanardi** [sakura-editor/sakura#1253]
## 問題内容
Windows Ver.5.x系(XP等)で起動不能。
ビルドオプションでXPサポートが無効化されている?

## 再現手順
Windows XPでバイナリを実行する

## 再現頻度
100%

## 問題のカテゴリ
- 仕様の問題
- プログラムの動作上の問題
  - 正式リリース版
- ビルドの問題
- ドキュメントの問題

## 環境情報
- OS バージョン
Windows XP Pro.
- サクラエディタバージョン
サクラエディタ   v2.4.0.2686 32bit (tag v2.4.0)
(GitHash 782347a4a1134d64786741dc893469a7b2e9fc79)

**Comment by k-takata** [comment]
[トップページ](https://sakura-editor.github.io/)より、

> Ver. 2.4.0.0 以降のバージョンは MS Windows 10 で動作します。

MS による XP のサポートはとっくの昔に終わっていますので、XP は動作対象から外すことになりました。どうしても XP で使う必要がある場合は 2.3.2.0 以前を使ってください。

**Comment by Xanardi** [comment]
了解です。
添付のヘルプファイルにも動作対象として記載が残っていたので。

**Comment by KENCHjp** [comment]
ヘルプファイル修正いたします。

**Comment by beru** [comment]
#1254 でヘルプの記載を更新したので close します。
