### ISSUE TITLE
sakura.iss に記載の URL を更新する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#126]
sakura.iss に記載の URL を更新する

https://github.com/sakura-editor/sakura/blob/11cb42171426e63f07cea280cfe412c975762fa6/installer/sakura.iss#L7-L9

**Comment by m-tmatma** [comment]
#180 の前にやったらよかった。

**Comment by m-tmatma** [comment]
#180 の cf44ff59b1885c89d840d75dbd0f5926d4177df8 で iss ファイルの共通化を行った。

**Comment by m-tmatma** [comment]
```
AppPublisherURL=https://sakura-editor.github.io/
AppSupportURL=https://github.com/sakura-editor/sakura/issues
AppUpdatesURL=https://github.com/sakura-editor/sakura/releases
```

かな?

**Comment by m-tmatma** [comment]
Windows 10 ではサポートリンク表示するの難しい

### サポートリンク表示する方法

1. `コントロールパネル` を表示する
2. 右上のドロップダウンで `カテゴリ` を選ぶ
3. `プログラムのアンインストール`を選ぶ
4. `Alt` キーを押す
5. `表示`を選ぶ
6. `詳細表示の設定`を選ぶ
7. `サポートリンク`、`ヘルプリンク`、`更新プログラム情報リンク` にチェックを入れて OK を押す。

`コントロールパネルを表示する方法`

- https://www.pasoble.jp/windows/10/088117.html
- コマンドから `control `と入力する

**Comment by KENCHjp** [comment]
私も最初どこにでるんだろうっておもったのですが、プログラムのアンインストール一覧画面で、クリックするとでますよ。
![default](https://user-images.githubusercontent.com/39618965/42129179-0ae94152-7cf8-11e8-936c-e34d02b883a5.PNG)
