### ISSUE TITLE
GitHub Actions を導入する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#1263]
## 要望機能
GitHub Actions を導入する

https://github.com/sakura-editor/sakura/pull/1259 で第一弾を導入したが、残件を記載する。

- [ ] ドキュメント
- [x] Azure Pipelines や Appveyor ビルドで取得している各種環境変数 (#1183) には対応していない
- [x] #922 には対応できないので、chm および installer のビルドは無効化している
- [x] Artifacts が一括して一つの zip にまとめられるが、個別にダウンロードできるようにする
- [x] microsoft/setup-msbuild@v1.0.0 で自動的に Visual Studio 2019 が選択される。

**Comment by k-takata** [comment]
GHA を導入したのはいいのですが、Azure Pilelines や AppVeyor との使い分けはどうしていく予定でしょうか。同じ処理を別々の CI で流すのは計算資源の無駄遣いですし。
GHA の並列数は 20、Azure Pipelines は 10、AppVeyor は 1 なので、GHA に移行するのも選択肢の1つかもしれません。
あとは、今後リリースを自動作成するような場合には GHA が楽かもしれません。

**Comment by m-tmatma** [comment]
> GHA を導入したのはいいのですが、Azure Pilelines や AppVeyor との使い分けはどうしていく予定でしょうか。同じ処理を別々の CI で流すのは計算資源の無駄遣いですし。

使ってみて考えようと思います。
まだ実験中というスタンスです。

> GHA の並列数は 20、Azure Pipelines は 10、AppVeyor は 1 なので、GHA に移行するのも選択肢の1つかもしれません。

同時実行数もメリットの一つですが、
GitHub Actions は GitHub ユーザーなら別途何かアカウントを作成しなくても使えるというメリットがあります。

AppVeyor  は chm のコンパイルに必要なので、 #922 を解決できない限り切れないです。
GitHub Actions は独自の dockerfile を指定して自前の container を使えるので locale を日本語に設定して、ビルドすれば、 #922 を解決できるんじゃないかと期待しています。

**Comment by berryzplus** [comment]
> GHA

女子、というか主婦が好きなビタミンの類かと思いました。
GitHubActionsですね...

このissueの出口政策が見えないっす。

- ドキュメント
  - 何のドキュメントでしょうか？
- Azure Pipelines や Appveyor ビルドで取得している各種環境変数 (#1183) には対応していない
  - 「先にそっちやろうぜ？」といいたい感じです。
- #922 には対応できないので、chm および installer のビルドは無効化している
  - 何故「無効化」している？
  - 実行不可なのは英語環境での日本語chmのビルド「だけ」なはずでinstallerビルドは頑張ればできるような気がします。
- Artifacts が一括して一つの zip にまとめられるが、個別にダウンロードできるようにする
  - せっかく小分けにして名前を付けてzip化してるのに Win32-Release.zip みたいになる...orz
  - ダウンロードしてみてビビりました。是非対応してほしいです。（他力
- microsoft/setup-msbuild@v1.0.0 で自動的に Visual Studio 2019 が選択される。
  - 詳細を理解していませんが、vs2017があるのにvs2019が選択される？
  - build-sln.batのオプションはちゃんと動くぞ、何故だ？

出口、何気に重要・・・・。

**Comment by m-tmatma** [comment]
> * Azure Pipelines や Appveyor ビルドで取得している各種環境変数 (#1183) には対応していない

試せてないけどこんな感じ?
https://help.github.com/ja/actions/configuring-and-managing-workflows/using-environment-variables


|||ローカルビルド|GitHub Actions で利用できる固有変数|固有変数以外の依存|
|--|--|--|--|--|
|GIT_COMMIT_HASH|git の commit Hash|◎|-|-|
|GIT_SHORT_COMMIT_HASH|git の commit Hash 短縮形|◎|-|-|
|GIT_REMOTE_ORIGIN_URL|git remote origin URL|◎|-|-|
|GIT_TAG_NAME|git の tag|◎|-|-|
|CI_ACCOUNT_NAME|CI のアカウント名|×|GITHUB_REPOSITORY から作り出す?|-|
|CI_BUILD_NUMBER|CI のビルド番号 (数値)|×|GITHUB_RUN_NUMBER|-|
|CI_BUILD_URL|CI のビルドURL|×|不明|-|
|CI_BUILD_VERSION|CI のビルドバージョン (文字列)|×|GITHUB_RUN_NUMBER|-|
|CI_REPO_NAME|リポジトリ名|×|GITHUB_REPOSITORY|-|
|GITHUB_COMMIT_URL|GitHub の Commit URL|×|-|CI_REPO_NAME<br>GIT_COMMIT_HASH|
|GITHUB_PR_HEAD_URL|GitHub の PR の Head の URL|×|GITHUB_REF あるいは GITHUB_HEAD_REF|-|
|GITHUB_PR_HEAD_COMMIT|GitHub の PR の Head Revision|×|GITHUB_REF から作り出す?|-|
|GITHUB_PR_HEAD_SHORT_COMMIT|GitHub の PR の Head Revision 短縮形|×|GITHUB_REF から作り出す?|-|
|GITHUB_PR_NUMBER|GitHub の PR 番号|×|GITHUB_REF から作り出す?|-|
|DEV_VERSION|開発バージョンかどうか|◎|-|-|

https://github.com/sakura-editor/sakura/blob/86d6f8f38d1d863ada09b40fbdf578ee4e8f9bf8/ci-build.md
の表をもとに構成

**Comment by m-tmatma** [comment]
> Artifacts が一括して一つの zip にまとめられるが、個別にダウンロードできるようにする
> * せっかく小分けにして名前を付けてzip化してるのに Win32-Release.zip みたいになる...orz
> * ダウンロードしてみてビビりました。是非対応してほしいです。（他力

#1285 で作成。でも制限がある。

**Comment by m-tmatma** [comment]
> microsoft/setup-msbuild@v1.0.0 で自動的に Visual Studio 2019 が選択される。
> * 詳細を理解していませんが、vs2017があるのにvs2019が選択される？
> * build-sln.batのオプションはちゃんと動くぞ、何故だ？

検索対象の visual studio を引数で指定できるみたいです。あまり確認できてません。

**Comment by berryzplus** [comment]
> microsoft/setup-msbuild@v1.0.0 で自動的に Visual Studio 2019 が選択される。

この件deprecatedなので対処済みにマークしてしまいます。

**Comment by berryzplus** [comment]
> Artifacts が一括して一つの zip にまとめられるが、個別にダウンロードできるようにする

この件は既に 別issue(#1486) で検討を始めているので対処済みにマークします。

**Comment by berryzplus** [comment]
全タスク完了につき、issuを閉じてしまいます。
