### ISSUE TITLE
Pull Request Template に入れた(必須)とか(省略可)を外したい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1287]
## 問題内容
PRが読みづらくなった気がします。

## 問題の経緯

#1266 Pull Request Template をシンプルにする

- (必須) = 必ずいれてね♪
- (省略可) = 省略してもいいっすよ。

これらの情報は Pull Request を作成する人に向けた情報で、
Pull Requestを読む人にとってはあんまし要らない情報な気がします。

`(必須)の入力欄に何にも書いとらんやんけ！`

というのがレビューの基準になったとしても、
単にリクエストを見るだけの人にとってはいらんような気がします。

## 提案内容
必須とか省略可の部分を以前のようにコメントに戻しませんか？

## 再現手順
1. sakura-editor/sakura をforkする
2. なんかコミットしてpushする
3. forkしたリポジトリのbranchesで`new pull request`ボタンを押す
4. previewする

## 再現頻度
100%

## 問題のカテゴリ
- GitHub 関連の問題

## 環境情報
なし。

## スクリーンショット
たとえば これ ⇒ https://github.com/sakura-editor/sakura/pull/1283

**Comment by k-takata** [comment]
私も https://github.com/sakura-editor/sakura/pull/1277#issuecomment-624439681 に書いたとおり、同意見です。

**Comment by m-tmatma** [comment]
いいと思います。
