### ISSUE TITLE
2.4.0のインストーラー版：プログラムと機能でSAKURA Editorをクリックするとデバッグ版のアイコンが表示される

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#1288]
## 問題内容
2.4.0のインストーラーでインストールした`プログラムと機能`で`SAKURA Editor`をクリックするとデバッグ版のアイコンが表示されます。

## 再現手順

1. https://github.com/sakura-editor/sakura/releases/download/v2.4.0/sakura-tag-v2.4.0-build2686-782347a-Win32-Release-Installer.zip をダウンロードして解凍します。
2. sakura_install2-4-0-2686-x86.exe をダブルクリックして実行してインストールを完了します。
3. スタートボタン→Windows システムツール→コントロールパネルにあるプログラムと機能を開きます。
4. インストールされたSAKURA Editor(サクラエディタ)をクリックします。

## スクリーンショット
![image](https://user-images.githubusercontent.com/11251874/81466382-35513a00-920c-11ea-9824-edf1fc0d884f.png)

## 再現頻度
不明

## 問題のカテゴリ
インストーラー

- プログラムの動作上の問題
  - 正式リリース版
- ビルドの問題
  - Azure Pipelines
  - Appveyor

## 環境情報
- OS バージョン
Windows 10 
- サクラエディタバージョン
サクラエディタ   v2.4.0.2686 32bit (tag v2.4.0)
(GitHash 782347a4a1134d64786741dc893469a7b2e9fc79)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2020/4/18 20:55:02

**Comment by berryzplus** [comment]
なんでやねん！ｗ

デバッグ版アイコンは、リリースビルドのsakura.exeには含まれてすらいないはず。

考えられる原因は、Windowsによるキャッシュ。
デバッグ版sakura.exeを繰り返し実行したことにより、Windowsが認識するsakura.exeがデバッグ版のほうに切り替わってしまった、とか。

解決策は・・・なんやろ？

**Comment by arigayas** [comment]
64bit版や32bit版のインストールを仮想マシンで何度か行ったのでキャッシュが残ったかもしれません(汗)

Windows10のバグでしょうか？

**Comment by arigayas** [comment]
新たに[仮想マシンのイメージ](https://developer.microsoft.com/ja-jp/windows/downloads/virtual-machines/)をダウンロードしてVirtualBoxで動かして
サクラエディタ v2.4.0をインストールしてみました。
![image](https://user-images.githubusercontent.com/11251874/81469803-0cd43a80-9222-11ea-946a-18cb6804d7a9.png)

Windows10のアイコンキャッシュが原因かもしれないですね・・・。

**Comment by berryzplus** [comment]
デバッグ版をインストールしたときのキャッシュが残ったから青くなってたみたい、という結論ですね。

インストーラーというのはそもそも、当該アプリに関して充分なリテラシーを持たない人向けに、初期導入作業を簡略化するための仕組みなので、デバッグ版アプリをインストールできるインストーラーを公開してしまっていることがマズい気がします。

インストーラー自体のデバッグ目的を否定する理由はないんですが、CIの組み込みバッチに頼らずにビルドできる人でなければインストーラーのデバッグなどできないと思うので「不要」と断定してもよい気はします。

いずれにしろ、継続調査の必要はないと思うので閉じてしまうことにします。

**Comment by arigayas** [comment]
Closeしていただきありがとうございました。

**Comment by m-tmatma** [comment]
> デバッグ版をインストールしたときのキャッシュが残ったから青くなってたみたい、という結論ですね。
> 
> インストーラーというのはそもそも、当該アプリに関して充分なリテラシーを持たない人向けに、初期導入作業を簡略化するための仕組みなので、デバッグ版アプリをインストールできるインストーラーを公開してしまっていることがマズい気がします。
> 
> インストーラー自体のデバッグ目的を否定する理由はないんですが、CIの組み込みバッチに頼らずにビルドできる人でなければインストーラーのデバッグなどできないと思うので「不要」と断定してもよい気はします。
> 
> いずれにしろ、継続調査の必要はないと思うので閉じてしまうことにします。

https://github.com/sakura-editor/sakura/pull/1403 で成果物のアップを Release 版に限定しました。
