### ISSUE TITLE
innosetup-5.6.1-unicode.exe で Unknown constant "sendto" のエラーでインストーラの作成に失敗する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#129]
innosetup-5.6.1-unicode.exe で Unknown constant "sendto" のエラーでインストーラの作成に失敗する
innosetup-5.5.9-unicode.exe ではエラーは発生しない。

http://files.jrsoftware.org/is/5/ で innosetup-5.5.9-unicode.exe をダウンロードして回避することは可能

ただ appveyor が innosetup-5.6.1-unicode.exe にアップデートされると困るのでそれまでに解決する。

**Comment by m-tmatma** [comment]
エラーメッセージ

```
Error on line 86 in C:\...\installer\sakura.iss: Unknown constant "sendto".

Use two consecutive "{" characters if you are trying to embed a single "{" and not a constant.
Compile aborted.
```

**Comment by m-tmatma** [comment]
https://github.com/m-tmatma/sakura/blob/a84fac8b1ea52a878e3261bf1e0faf16254dbdeb/installer/sakura.iss#L86

{sendto}  を {usersendto} に名前変更したら 5.6.1 でビルドが通ったが、
今度は 5.5.9 でビルドが通らなくなる。

仕様を変えるなら移行期間を設けてどちらでもいけるようにしないと駄目だろうと思う。

**Comment by m-tmatma** [comment]
http://www.jrsoftware.org/newsgroups.php
で質問を投げることが可能みたい。

Inno Setup のソース自体は
https://github.com/jrsoftware/issrc
で管理されているぽい。

**Comment by m-tmatma** [comment]
> http://www.jrsoftware.org/newsgroups.php
> で質問を投げることが可能みたい。

innosetup-5.5.9-unicode.exe と innosetup-5.6.1-unicode.exe の両方に対応できる方法が
あればいいのだが。

**Comment by KENCHjp** [comment]
>仕様を変えるなら移行期間を設けてどちらでもいけるようにしないと駄目だろうと思う。

激しく同意。過去のスクリプトが動かんくなる。。。

**Comment by m-tmatma** [comment]
> innosetup-5.5.9-unicode.exe と innosetup-5.6.1-unicode.exe の両方に対応できる方法が
> あればいいのだが。

考えられる対策
1. innosetup-5.5.9-unicode.exe と innosetup-5.6.1-unicode.exe が両方インストールできるか調べて可能であれば appveyor に両方インストールしてもらうように頼む
2. appveyor が innosetup-5.6.1-unicode.exe に切り替えるまで待つ。古い仕様の対応は諦める
3. setup.iss の中でバージョンチェックして、両対応できないか調べる
4. Inno Setup に要求して、innosetup-5.6.2 で {sendto} がエラーにならないようにして、と要求する。
  (innosetup-5.6.2 が出るまでは appveyor に更新しないでとお願いしておく)

最後の選択肢が一番いいが。

**Comment by m-tmatma** [comment]
> 4. Inno Setup に要求して、innosetup-5.6.2 で {sendto} がエラーにならないようにして、と要求する。
> (innosetup-5.6.2 が出るまでは appveyor に更新しないでとお願いしておく)

5. 自分で修正する PR を投げる

もありますね。

**Comment by m-tmatma** [comment]
appveyor/ci#2444 で `Inno Setup version 5.6.1` にアップデートする要求が
出されていたので反対意見を書いておいた。

**Comment by m-tmatma** [comment]
InnoSetup にも要求送っておいた。
http://news.jrsoftware.org/read/article.php?id=106216&group=jrsoftware.innosetup#106216

**Comment by m-tmatma** [comment]
毎回 URL を調べなくていいように wiki にまとめた。

- https://github.com/sakura-editor/sakura/wiki/InnoSetup
- https://github.com/sakura-editor/sakura/wiki/Appveyor

**Comment by berryzplus** [comment]
う～む。大変な感じになっていますね。お疲れ様です。
C++でいうこんな感じのことが iss でもできればよいのですが。

```C++
#if _MSC_VER > 1000
#pragma once
#endif
```

できるなら新旧どちらか環境向けにラッパーを用意してあげればよいはずなので。

**Comment by k-takata** [comment]
http://www.jrsoftware.org/ispphelp/index.php?topic=predefinedvars
`PREPROCVER` が使えるかどうか…

**Comment by berryzplus** [comment]
こんな感じになりますかね？

```
#if PREPROCVER < [iss pre-proccessor 5.6.1のバージョン]
#define usersendto sendto
#endif
```

sendto が右クリックメニュー「送る」に表示するショートカットを入れるフォルダのことだということに今更気付いたわけですが(^-^;

**Comment by KENCHjp** [comment]
PREPROCVER使えそうですが、ビット操作入りそうでつらいなぁ（というか今日はもうぼちぼち電池切れ）

PREPROCVER | int. Returns the 32-bit encoded version of ISPP. Highest byte holds the major version, lowest byte holds the build number.

http://www.jrsoftware.org/ispphelp/index.php?topic=if

でもこの仕様変更対応をゴリゴリこっちでコーディングして対応するのもなんか納得がいかない気がするのは私だけ？？？
http://www.jrsoftware.org/ishelp/index.php?topic=consts
usersendtoは他のuserなんたらとちがって、usersendtoしかなさそうだから、sendtoのままでもいい気がする。。。

**Comment by m-tmatma** [comment]
iss ファイル側でなんとかする方法は、これから作成する iss ファイルには
対応できるのですが、過去に作ったファイルには効果ないので
Inno Setup 側または appveyor 側でなんとかしたいです。

**Comment by m-tmatma** [comment]
> こんな感じになりますかね？
> #if PREPROCVER < [iss pre-proccessor 5.6.1のバージョン]
> #define usersendto sendto
> #endif
> 
> sendto が右クリックメニュー「送る」に表示するショートカットを入れるフォルダのことだということに今更気付いたわけですが(^-^;

これとやることは一緒ですが、
作者から提案のあった workaround を実装してみた。
3085ae3d801ee3ed83f797129169046cd88e37f2

5.5.9  と 5.6.1 で動くことを確認した。

**Comment by m-tmatma** [comment]
どうしようかな、とりあえず動いたし、appveyor と InnoSetup への要求を取り下げるか?
あるいは他の人のためにあくまでも過去互換性を維持してもらうようにがんばるか?

**Comment by KENCHjp** [comment]
@m-tmatma さん
能動的に動けるなら、待つよりGo.がいいと思います！

**Comment by m-tmatma** [comment]
> iss ファイルを変更しないで対応する方法がないか質問した。
> http://news.jrsoftware.org/read/article.php?id=106218&group=jrsoftware.innosetup#106218

追加の回答が来るかしばらく待ってから考えよう。

**Comment by m-tmatma** [comment]
> 追加の回答が来るかしばらく待ってから考えよう。

動いたことは伝えたほうがいいので、コメント書いた。
更に、過去互換性を維持するように改めて送っておいた。

http://news.jrsoftware.org/read/article.php?id=106220&group=jrsoftware.innosetup#106220

**Comment by KENCHjp** [comment]
@m-tmatma さんお疲れ様です。
これ非常に参考になります。

**Comment by m-tmatma** [comment]
> 更に、過去互換性を維持するように改めて送っておいた。

変えるつもりはなさそう。
http://news.jrsoftware.org/read/article.php?id=106221&group=jrsoftware.innosetup#106221

**Comment by m-tmatma** [comment]
追加で送ってみた。
http://news.jrsoftware.org/read/article.php?id=106222&group=jrsoftware.innosetup#106222

**Comment by KENCHjp** [comment]
しゃーない。
でも言い続けることは大事です。

**Comment by m-tmatma** [comment]
一応送ってみた。でも聞き入れないだろうな。
http://news.jrsoftware.org/read/article.php?id=106228&group=jrsoftware.innosetup#106228

**Comment by m-tmatma** [comment]
http://www.jrsoftware.org にアクセスできない。

**Comment by m-tmatma** [comment]
> http://www.jrsoftware.org にアクセスできない。

https://github.com/jrsoftware/issrc によると

`**NOTE** Currently the main Inno Setup web site is down. The 5.6.1 binaries can be downloaded from GitHub under releases. -`

とある。

**Comment by m-tmatma** [comment]
> http://www.jrsoftware.org にアクセスできない。

復活したみたいだ。

http://news.jrsoftware.org/read/thread.php?group=jrsoftware.innosetup
は更新ないみたいだ。

**Comment by m-tmatma** [comment]
#176 でマージ済み

**Comment by KENCHjp** [comment]
とりあえず、こちらもクローズかな？

**Comment by berryzplus** [comment]
クローズで良いと思います。
自分のコミットで参照してることになってるのは、リベース失敗による誤りです。
