### ISSUE TITLE
インストーラー版の32bit版と64bit版を両方インストールした場合、 プログラムと機能のウィンドウで32bit版と64bit版か区別が付かない

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#1292]
https://github.com/sakura-editor/sakura/issues/1198#issuecomment-626174405 をissue登録しました。

## 問題内容
インストーラー版の32bit版と64bit版を両方インストールした場合、 
プログラムと機能のウィンドウで32bit版と64bit版か簡単に区別が付かないので、
アンインストール時に手間が確認する発生してしまいます。

例えば今まではVer2.4.0 の 32bit版をインストールして使っていた人がVer2.4.0 の64bit版を使うようになった場合、
現状ではbitの表記がなくビルド番号が同じだと区別が付かずに設定を色々行った32bit版のバージョンを誤ってアンインストールする可能性あるかもしれません。
## スクリーンショット
![image](https://user-images.githubusercontent.com/11251874/81474614-a65f1480-9241-11ea-9fd7-f62e005968cc.png)

## 再現手順

1. 32bit版の[Ver2.4.0 のインストーラー版](https://github.com/sakura-editor/sakura/releases/download/v2.4.0/sakura-tag-v2.4.0-build2686-782347a-Win32-Release-Installer.zip) をダウンロードしてインストールします。
2. 64bit版の [2.4.1 Beta2のテストビルド](https://ci.appveyor.com/project/sakuraeditor/sakura/builds/32726239) Releaseビルドをダウンロードしてインストールします。
3. コントロールパネルの`プログラムと機能`を表示して`SAKURA Editor`の表記がある位置までスクロールさせます。

## 再現頻度
100％？

## 問題のカテゴリ

- インストーラー

- 仕様の問題
- プログラムの動作上の問題
  - 正式リリース版
  - Appveyor ビルド版

## 環境情報
- OS バージョン
Windows 10 [Version 10.0.18363.778] 仮想マシンのイメージ
- サクラエディタバージョン
32bit版は 2.4.0 Release版
64bit版は [2.4.1 Beta2のテストビルド](https://ci.appveyor.com/project/sakuraeditor/sakura/builds/32726239) Releaseビルド

**Comment by m-tmatma** [comment]
#1293 マージしました。

**Comment by arigayas** [comment]
改善を確認しました！
![image](https://user-images.githubusercontent.com/11251874/81493362-c1319780-92da-11ea-9752-f86c36a1c75e.png)

x86 って何ですか？という質問が来る気がしましたが
ドキュメントに書いておけば良いと思うので見なかったことに・・・。

**Comment by m-tmatma** [comment]
インストーラのファイル名と同じにしました

**Comment by arigayas** [comment]
なるほど。
