### ISSUE TITLE
(master で) Azure Pipelines の MinGW が失敗している 

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#1298]
## 問題内容
(master で) Azure Pipelines の MinGW が失敗している 

## 再現手順
https://dev.azure.com/sakuraeditor/sakura/_build/results?buildId=1721&view=results

## 再現頻度
50 % くらい?

NG https://dev.azure.com/sakuraeditor/sakura/_build/results?buildId=1712&view=results
OK https://dev.azure.com/sakuraeditor/sakura/_build/results?buildId=1713&view=results
OK https://dev.azure.com/sakuraeditor/sakura/_build/results?buildId=1715&view=results
NG https://dev.azure.com/sakuraeditor/sakura/_build/results?buildId=1719&view=results

## 問題のカテゴリ

- ビルドの問題
  - Azure Pipelines

**Comment by berryzplus** [comment]
ちょい調べてみました。
build-1712とbuild-1719は現象が違いますね。

build-1712 = msys2のダウンロードに失敗する、いつものやつ。
build-1719 = msys2のダウンロードに成功しているのに失敗する、新しいパターン。

じゃ、何が起きたのか？
ログの中に原因っぽいものを見つけました。

| ビルド番号 | ビルドに使ったgccのバージョン | 結果 |
| -- | -- | -- |
| build-1713 | downloading mingw-w64-x86_64-gcc-9.3.0-2-any.pkg.tar.xz... | 成功 |
| build-1719 | downloading mingw-w64-x86_64-gcc-10.1.0-1-any.pkg.tar.zst... | 失敗 |

暫定策としては `MinGW gccのバージョンを 9.3 に固定する` が選択できそうです。
