### ISSUE TITLE
OSDNより転載： 「タイプ別設定」等ダイアログ内の「ヘルプ」ボタンが機能しない

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#1302]
## 問題内容
以下OSDNより取り急ぎ転載。
「タイプ別設定」等ダイアログ内の「ヘルプ」ボタンが機能しない - サクラエディタ - OSDN
https://ja.osdn.net/projects/sakura-editor/forums/34071/42329/

環境は以下の通りです
windows10 1901 (ビルド 18363.778)
サクラエディタ v2.4.0.2686 32bit (tag v2.4.0)
インストール: インストーラ版をダウンロードが解凍し
できたファイルのプロパティでブロックの解除後実行

回避方法はあるでしょうか?
インストールし方等に問題等があれば指摘をお願いします

よろしくお願いします 

## 再現頻度
100％

## 問題のカテゴリ
- 仕様の問題
- プログラムの動作上の問題
  - 正式リリース版
- ドキュメントの問題

## 環境情報
- OS バージョン
Windows 10
- サクラエディタバージョン
 2.4.0.2686

**Comment by KENCHjp** [comment]
@arigayas さん
転載ありがとうございます。

**Comment by berryzplus** [comment]
で、この件ウチでは再現せんのですが、再現した人います？
再現せんので何をもって「機能しない」といってるのかが不明です・・・。

**Comment by beru** [comment]
自分の環境ではHTMLヘルプのポップアップヘルプは機能しています。

**Comment by KENCHjp** [comment]
OSDNに追試ありましたね。
https://ja.osdn.net/projects/sakura-editor/forums/34071/42329/#forum-message-84988

**Comment by KENCHjp** [comment]
こっちのVMの環境で、v2.4.1-beta2入れて試してみましたが、再現しますね。

サクラエディタ   v2.4.1.2815 32bit (tag v2.4.1-beta2)
(GitHash 3fc1936ff06f6f61260d05d029b421f255659a72)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2020/5/12 07:52:20

ヘルプメニューの目次とヘルプキーワード検索は生きてます（ヘルプ立ち上がる）
[設定]-[共通設定]ダイアログのヘルプボタンは効かないです。

**Comment by berryzplus** [comment]
機能しない＝ボタンを押しても何も起きない
と理解しました。

しかも、単体でヘルプを表示させようとすると表示できて、
何も起きてないように見える場合でもファイルはロックされている、と。

ということは [v2.4.1-beta2](https://github.com/sakura-editor/sakura/releases/tag/v2.4.1-beta2
) のsakura.chm がデータ的に壊れてる可能性があります。
実際試してみました・・・再現しました。

デバッグビルドで動かしてみると、
エラーダイアログで `[map] section がない` と言われました。

このバージョンのsakura.chmだとエラーは出ないっす。
`sakura-tag-release_issue1125-test-2.4.0-test2-build2458-f542cc894ad630041164161a9a07648ce4cb86f8-Win32-Release-Exe`

なんか変えましたっけ？　＞sakura.chm生成まわり。

**Comment by berryzplus** [comment]
調査結果一旦の結論

chmファイルの生成がぶっ壊れています。

少なくとも v2.4.0-beta4 以降はファイルが壊れていて、[現在のmasterビルド](https://ci.appveyor.com/project/sakuraeditor/sakura/branch/master/job/lk1c63cp11vk612a/artifacts)でも再現しています。

原因になったコミットはまだ特定できていないっす。

sakura-tag-v2.4.0-alpha1-build1699-2582c34c-Win32-Release-Exe

のchmが壊れていないことまでは確認済みっす。
（v2.4.0-beta～v2.4.0-beta3は構造がよくわからんかったので検証してないっす）。

**Comment by KENCHjp** [comment]
おお、確認あざーす。ただ、2.4.1に入れるならbeta3つくりますが、2.4.1は緊急度合い高いかなとおもうので、本体不具合なければ、いったん来週2.4.1リリースして、本件は2.4.2へ廻したいかなと。

**Comment by beru** [comment]
「ヘルプ」ボタンってダイアログの右下のボタンの事だったんですね。
ウィンドウのタイトルバーの右上にある？アイコンの事かと勘違いしていました。

サクラエディタ   v2.4.1.2790 32bit で動作確認したらこちらの環境でも無反応でヘルプが表示されませんでした。

**Comment by berryzplus** [comment]
sakura.chm を古いのに入れ替えれば「ヘルプ」ボタンが動くので、CHMのビルド問題と考えられます。 #1303 で試した感じ、たぶんローカルのCHMビルドで再現するんじゃないかと思います。

ローカルで試せよ！ｗ　って感じなんですけど、pythonにパスが通ってないと動かないっぽくて再現確認が難航しております・・・。

**Comment by beru** [comment]
AppVeyor から artifacts を落とそうと思ったんですが古いのはもう見れないですね。

現時点では [1.0.2382](https://ci.appveyor.com/project/sakuraeditor/sakura/builds/28895348/job/jpl4jn15k1acdldx/artifacts) は `The build job does not contain any artifacts.` と表示されてしまい、[1.0.2383](https://ci.appveyor.com/project/sakuraeditor/sakura/builds/28903706/job/15urkkhj4v671ok7/artifacts) はファイルが見れます。

**Comment by beru** [comment]
[build2383](https://ci.appveyor.com/api/buildjobs/15urkkhj4v671ok7/artifacts/sakura-PR1090-build2383-Win32-Release-Installer.zip) だとヘルプボタンを押すとヘルプが表示されます。

**Comment by berryzplus** [comment]
原因は #1129 くさいんですが、確証なしっす。

**Comment by beru** [comment]
変換済みのデータに対して変換しようとしてツール（ChmSourceConverter？）が例外をはいていた事が問題で対策を入れたのが #1129 みたいですね。

思い付くのは既に入力のファイルが UTF-8 なら例外を吐かずに skip するように ChmSourceConverter を変更するぐらいです。

**Comment by m-tmatma** [comment]
#1304 で #1129 を revert する draft PR を作ってみました。
これで再現するか、しないかを確認したら関係するかわかるはずです。

**Comment by berryzplus** [comment]
ああ、beruさんの表 https://github.com/sakura-editor/sakura/issues/1302#issuecomment-629593235 で build2460 が #1129 に対応してて、build2462 が その次のマージビルドなんで #1129 が原因なのは確定だと思っています。

で、`なんでや～～～っ！` と色々いじってみたら `sakura.hh` の生成先が 新しい生成先 に直ってないのが分かって、ローカルで試してみたら そこだけ修正したCHMが正常に表示できるのを確認できた感じです。

**Comment by berryzplus** [comment]
検証できるように #1305 投げました。

**Comment by m-tmatma** [comment]
> 検証できるように #1305 投げました。

こっちでもやってみて同じエラーになっていたので、修正したつもりのものを #1306 で投げました。

**Comment by m-tmatma** [comment]
> > 検証できるように #1305 投げました。
> 
> こっちでもやってみて同じエラーになっていたので、修正したつもりのものを #1306 で投げました。

修正確認できました。

**Comment by m-tmatma** [comment]
#1306 で修正しました。

**Comment by arigayas** [comment]
お疲れさまでした。
