### ISSUE TITLE
Installer のx64 対応を行う

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#131]
Installer のx64 対応を行う

#124　でインストーラの作成実験を行ったが、
x64 用に　iss ファイルを用意すれば x64 用のインストーラを作成できた。

#130 の対応が完了したら、対応を行う。

**Comment by m-tmatma** [comment]
#132 の後で対応予定

**Comment by m-tmatma** [comment]
https://shimaji.exblog.jp/12409088/
あたりが参考になる。

x86 版の iss ファイルと x86 版の iss ファイルの両方を登録する場合
更新漏れがないことを保証するために x86 版の iss ファイルと x86 版の iss ファイルの違いが
ArchitecturesInstallIn64BitMode か ArchitecturesAllowed だけであることを appveyor で
チェックしたほうが良さそう。

**Comment by arigayas** [comment]
> x86 版の iss ファイルと x86 版の iss ファイルの両方を登録する場合
> 更新漏れがないことを保証するために x86 版の iss ファイルと x86 版の iss ファイルの違いが

どちらか一方が x64 版でしょうか？

**Comment by m-tmatma** [comment]
http://www.jrsoftware.org/ispphelp/index.php?topic=include
の機能を使って x86 版と x64 版で iss ファイルの共通部分を抽出して
対応できるかもしれない。
(ただこれは後でリファクタリングネタとすればいいと思う)

**Comment by m-tmatma** [comment]
対応自体は終わっていて #180 で PR を作成している。

**Comment by m-tmatma** [comment]
#180 完了
