### ISSUE TITLE
検索ダイアログ等でのCtrl+BackSpaceの動作変更要望

### ISSUE THREAD

**Issue by 7-rate** [sakura-editor/sakura#1311]
## やりたいこと(=実現したいこと)

検索ダイアログやGrepダイアログ等でCtrl+BackSpaceを押下すると添付画像のような文字が入力されます。
通常のエディタであれば単語単位での削除になるため、検索ダイアログ等でも同様の動作にしてほしいです。

v2.2.0.1でも同様の動作であるため、v2.4.0.0でのデグレ等ではないようです。

## スクリーンショット 

![2020-05-20_10h12_02](https://user-images.githubusercontent.com/22238784/82394272-91755300-9a83-11ea-84d7-d6b8b4209586.png)

**Comment by arigayas** [comment]
[誤変換して確定した文字を確定前の状態に戻す － ＠IT](https://www.atmarkit.co.jp/fwin2k/win2ktips/843typing/typing.html)

かな漢字変換に**ATOK**を使っていると Ctrl+BackSpace にショートカットキーが割り振られているので発生しませんでしたが、**Microsoft IME** に切り替えると発生しました。

使用OS；Windows 10 1909
試したサクラエディタのバージョン：サクラエディタ   Ver. 2.3.2.0

**Comment by beru** [comment]
https://superuser.com/a/332034

> A few people in the early days of the Internet Explorer group used the Brief editor, which uses Ctrl+Backspace as the shortcut key to delete the previous word, and they liked it so much that one of them added it to the autocomplete handler. Therefore, **any edit control that uses SHAutoComplete** will gain this secret Ctrl+Backspace hotkey.

だそうです。

**Comment by kasumikagari** [comment]
superuserの回答通り、Win32のコントロールでは記号が入力されるのが普通です。
一方でWPFとWinUIにおける同種のコントロールでは単語削除として受け付けてくれます。
MicrosoftとしてはWindowsの標準ショートカットキーとして取り入れる方針だが、互換性の問題からWin32に実装されていないと考えられ、独自に実装してもOSのUI標準から逸脱することはないはずです。

他のソフトウェアのダイアログについても少しだけ調べてみたところ、メモ帳とMeryではいずれも記号が入力されました。
その中で興味深かったのがNotepad++の実装で、Win32のコントロールを利用しながら検索ダイアログに限って単語削除が機能します。
コントロールをサブクラス化してWM_CHARを捕まえる手法で実装されていまして、これに倣えばサクラエディタでも同じことが実現できますが、この処理を仕込んだ特定のダイアログでしか機能しないという問題は残ります。

**Comment by kasumikagari** [comment]
個人的にも実現してほしいので試しに作ってみようかと思ったのですが、 ddc4117a で既にコンボボックスをサブクラス化する処理が組み込まれていますね。

これを利用するとして気になった点
- `SComboBoxItemDeleter` から改名する必要がある。複数のダイアログで使用されているのでやや難儀です。
- EditとListBoxのハンドルを取得するためにComboBoxそのものをサブクラス化しているが、Vista以降では`GetComboBoxInfo`で取得可能。
- `SComboBoxItemDeleter`を`CDialog`派生の各クラスのメンバとして持たせている理由が判然としません。サブクラスプロシージャ内からしか参照されないなら`WM_DESTROY`でdeleteしても良いのでは？

**Comment by k-kagari** [comment]
#1470 で以下の画面のコンボボックスに単語削除機能を追加しました。
- 検索・置換ダイアログ
- Grep・Grep置換ダイアログ
- 外部コマンド実行ダイアログ
- ツールバーの検索ボックス

（Issue閉じるのを忘れてました。すみませんでした）
