### ISSUE TITLE
sakura.iss を UTF-8 にする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#132]
sakura.iss を　UTF-8　にする

http://www.jrsoftware.org/ishelp/index.php?topic=unicode
によると
`Unicode Inno Setup supports UTF-8 encoded .iss files (but not UTF-16).`
とある。

x64 対応(#131) の前に入れる?

**Comment by berryzplus** [comment]
日本語がちょこちょこ入ってるので変更レビューで文字化けすることを考えて変えたいです。
なんか「処理構造が違うよ！」と読み取れる注意書きがあるのが気になっています。
なにも変更せずに変換できるなら x64 対応の前がいいと思います。

**Comment by berryzplus** [comment]
#130 見ましたが、GitHubのWebサイトで見た状態で化けてますね。
可能なら変換を先に済ませたい・・・。

**Comment by m-tmatma** [comment]
> 可能なら変換を先に済ませたい・・・。

それだと #130 でコンフリクトするので手間が増えます。

**Comment by m-tmatma** [comment]
#81　の方針が決まったら、appveyor でのインストーラの対応及び
#130 をサクッといれられるのですが。

**Comment by m-tmatma** [comment]
#170 で対応済み。
