### ISSUE TITLE
Grep置換ダイアログでホットキーが重複している

### ISSUE THREAD

**Issue by 7-rate** [sakura-editor/sakura#1323]
## 問題内容
Grep置換ダイアログでAlt+Rキーが重複しています。
どちらかを変更したほうが良いかと思います。(使用頻度的には結果出力形式-結果のみ(R)を変更したほうが良いかと思います。)
![2020-06-16_22h28_46](https://user-images.githubusercontent.com/22238784/84780809-fe4b2100-b020-11ea-8d63-c38f4e4ce828.png)
実際の動作は結果出力形式-結果のみ(R)にカーソルが飛んでいき、置換実行されません。

## 再現手順
Grep置換ダイアログを開く。

## 再現頻度
100%

## 問題のカテゴリ
- 仕様の問題

## 環境情報
- OS バージョン
 Windows 10 Pro 64bit 
- サクラエディタバージョン
サクラエディタ   
v2.4.0.2686 32bit (tag v2.4.0)
(GitHash 782347a4a1134d64786741dc893469a7b2e9fc79)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2020/4/18 20:55:02

**Comment by beru** [comment]
割り当て状況を調べてみました。

キー | 見出し1 | 見出し2
:--: | -- | --
A | 文字コードセット(&A) |  
B | 上フォルダ(&B) |  
C | 英大文字と小文字を区別する(&C) |  
D | フォルダの初期値をカレントフォルダにする(&D) |  
E | 正規表現(&E) |  
F |   |  
G | ファイル毎最初のみ検索(&G) |  
H |   |  
I | ファイル毎(&I) |  
J | クリップボードから貼り付ける(&J) |  
K | バックアップ作成(&K) |  
L | 該当行(&L) |  
M | ノーマル(&M) |  
N | 置換前(&N) |  
O | フォルダ(&O) |  
P | 該当部分(&P) |  
Q | 現在編集中のファイルから検索(&Q) |  
R | 結果のみ(&R) | 置換(&R)
S | サブフォルダからも検索する(&S) |  
T | ファイル(&T) |  
U | 現フォルダ(&U) |  
V | ベースフォルダ表示(&V) |  
W | 単語単位で探す(&W) |  
X | キャンセル(&X) |  
Y | フォルダ毎に表示(&Y) |  
Z | 置換後(&Z) |  
2 | CP(&2) |  
  | 除外ファイル |  
  | 除外フォルダ |

**Comment by berryzplus** [comment]
Grep置換の「置換」ボタンを押したときの動作は「すべて置換」です。

なので、ユーザビリティ的に「置換(&A)」とするのが良いと思います。

|ラベル|旧|新|
|--|--|--|
|置換(&R)|R|A|
|文字コードセット(&A)|A|C|
|英大文字と小文字を区別する(&C)|C|I|
|ファイル毎(&I)|I|F|

あと「キャンセル(&X)」を割り当ててるのは勿体ないです。既定のショートカットESCを使えるからです。

余ったXとHを使って
除外ファイル(&X)
除外フォルダ(&H)
とするのはどうでしょう。

**Comment by beru** [comment]
その変更で問題無いと思います。あと変更するなら「Grep置換」と「Grep」の両方を合わせた方が良い気がします。あと英語版リソースも…。

**Comment by berryzplus** [comment]
> あと変更するなら「Grep置換」と「Grep」の両方を合わせた方が良い気がします。

それは確かにその通り。
変更するなら、似たようなものを合わせて変更したほうがよいと思います。

ただ、Grep置換ダイアログの「置換」ボタンの動作は「すべて検索」ですが、Grepダイアログの「検索」ボタンの動作は「すべて検索」なので、Alt+Aを割り当ててしまうとなんか変な気がします。

GrepとGrep置換は合わせる方向で、もう少し整理したほうが良さそうに思いました。

**Comment by suconbu** [comment]
https://github.com/sakura-editor/sakura/pull/1431 で Grep / Grep 置換ダイアログのアクセラレータキー割り当てを変更しました。
これにより、問題点とされていた R キーの重複が解消できましたのでクローズします。
