### ISSUE TITLE
履歴とお気に入りの管理ダイアログのタブをCtrl+Tabで切り替えたい

### ISSUE THREAD

**Issue by kazasaku** [sakura-editor/sakura#1324]
## やりたいこと(=実現したいこと)

サクラエディタの編集画面、共通設定ダイアログ、タイプ別設定ダイアログは、「Ctrl + Tab」及び「Ctrl + Shift + Tab」のキーバインドでタブを切り替えることができます。
一方で、履歴とお気に入りの管理ダイアログではこのキーバインドでタブを切り替えることはできず、代わりにボタンなどのフォーカスが移動します。
しかし、フォーカスの移動自体は「Tab」及び「Shift + Tab」でも可能です。

履歴とお気に入りの管理ダイアログのタブにおいても「Ctrl + Tab」にてタブを切り替えられるようにして、ほかのダイアログと操作感を統一することはできないでしょうか？

当方の環境は以下の通りです。
　Windows 10 Pro 64bit, バージョン2004, ビルド19041.329
　サクラエディタ v2.4.1.2849 32bit

初めてのissue投稿のため、情報不足かもしれません。
その際はご指摘いただけると幸いです。よろしくお願いいたします。

**Comment by KENCHjp** [comment]
投稿ありがとうございます。
このような統一感を持たせるご指摘歓迎いたします。
他にもお気づきに点ございましたらお気軽に投稿いただければ幸いです。

修正はメンバーのパワー次第なところはありますが、賛同されている方もいらっしゃいますので、気長にお待ちいただければと思います。

**Comment by berryzplus** [comment]
共通設定とタイプ別設定はプロパティーシートというWindowsが提供する組み込みダイアログ(Windowsエクスプローラーのプロパティダイアログと同じもの)を使っていて、キーバインドを独自にゴリゴリやっているわけじゃないです。

履歴とお気に入りの管理ダイアログは、普通のダイアログにタブコントロールを貼り付けたものなので、キー割り当てを実現するには「ゴリゴリやる」か「プロパティシートで組みなおす」かのどちらかになると思います。

**Comment by kasumikagari** [comment]
> 履歴とお気に入りの管理ダイアログは、普通のダイアログにタブコントロールを貼り付けたものなので、キー割り当てを実現するには「ゴリゴリやる」か「プロパティシートで組みなおす」かのどちらかになると思います。

WM_KEYDOWN でゴリゴリやりたいところですが、VK_TAB は WS_TABSTOP 処理のためにシステム側で食われる仕様でして…。
本気で実現するならプロパティーシートしかないかもしれません。

**Comment by berryzplus** [comment]
ちゃんと調べないで書くので嘘かも知らんですが・・・。

システムに食われるキーイベントも、wm_syskeydownで拾えます。
通常の方法では拾えないメッセージもメッセージフックを使えば「拾えない」ってことはないっす。

システム組み込みの既存手法があるのに自前でゴリゴリするのはアフォだと思いますけどね。

**Comment by kazasaku** [comment]
情報提供ありがとうございます。

まさか新しいコメントが付くとは思っていなかったので、試したことを書き残しておきます。
次の方法ではできないようでした。

- CDlgFavorite::DispatchEvent()にてWM_SYSKEYDOWNを捕捉し、Ctrl(+Shift)+Tabであるか判定
- WM_KEYDOWNの時に呼ばれるCDialog::OnKeyDown()をオーバーライド
   - CDlgFavorite::OnKeyDown関数を用意し、この中でCtrl(+Shift)+Tabであるか判定
- WM_NOTIFYの時に呼ばれるCDlgFavorite::OnNotify()にて
   - 既にあるLVN_KEYDOWN用の処理を拡張し、Ctrl(+Shift)+Tabであるか判定
   - 新たにTCN_KEYDOWNを捕捉するようにし、Ctrl(+Shift)+Tabであるか判定
