### ISSUE TITLE
2.4.1のヘルプ：「Windows 10 でのファイル拡張子関連付け」「Grep」「Grep置換」の画像がやたら大きくて見づらい。

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#1325]
## 問題内容
5chの掲示板（サクラエディタふぁんくらぶ part19 → https://egg.5ch.net/test/read.cgi/software/1587603412/102 ）より転載
> 2.4.1のヘルプ、「Windows 10 でのファイル拡張子関連付け」「Grep」「Grep置換」
の画像がやたら大きくて見づらい。 

ほとんどのヘルプの画像ファイルの横幅は1000px以下なのに指摘されたヘルプは1100px以上あります。
![image](https://user-images.githubusercontent.com/11251874/85639182-e0398c80-b6c2-11ea-8740-19a5efd8ce8f.png)

## 再現手順
「Windows 10 でのファイル拡張子関連付け」
https://sakura-editor.github.io/help/HLP000374.html
「Grep」
https://sakura-editor.github.io/help/HLP000067.html
「Grep置換」
https://sakura-editor.github.io/help/HLP000362.html

## 再現頻度
100％

## 問題のカテゴリ
- ドキュメントの問題

## 環境情報
- OS バージョン
Windows 10
- サクラエディタバージョン
2.4.1

**Comment by berryzplus** [comment]
たしかにちょっと大きいですね。

> 1833 x 1218

現代の標準的ディスプレイのサイズは `1920 x 1080` ですが、この画像サイズではヘルプビューアを最大化していも目次ビューの幅によって見切れてしまう場合がありそうです。

とりあえずの方針として、大きすぎる画像は縮小する、のかな。

**どれくらいに？** って、`縮小なしで印刷してA4縦に収まるサイズ(max=595px)` がいいなぁ、と言ってみます。

**Comment by k-takata** [comment]
HiDPI 200%の環境でキャプチャした画像を載せてあるのだと思いますが、100%の環境でキャプチャし直すか、面倒ならば半分のサイズに縮小するのがよいのではないでしょうか。

**Comment by berryzplus** [comment]
幅が奇数なんで、半分にしようとすると割り切れないっていう...（　￣Д￣)ああああ

**Comment by beru** [comment]
CSSで相対単位でサイズ指定するのはどうでしょうか？

**Comment by arigayas** [comment]
ファイルサイズも大きい3ファイルはリサイズした方が良いと思います。

- FileAssoc-3-Application.png
- FileAssoc-4-DefaultApp.png
- FileAssoc-5-ChooseDefaultApp.png

**Comment by arigayas** [comment]
関連するissueとして「 Grep置換ダイアログでホットキーが重複している #1323 」がある事を明記しておきますね。

**Comment by arigayas** [comment]
藤 -Resizer- v3.8.0a という画像リサイズソフトにて縦横共に50％縮小しました。
「Grep」「Grep置換」の画像はホットキーの重複しているissueがCloseしてからスクリーンショットを撮るのが良いと思ったのでやってません。


### FileAssoc-1-StartMenu.png
![resized_FileAssoc-1-StartMenu](https://user-images.githubusercontent.com/11251874/85934491-16bf1380-b91e-11ea-925f-deb4c36fa0d1.png)
### FileAssoc-2-Setting.png
![resized_FileAssoc-2-Setting](https://user-images.githubusercontent.com/11251874/85934501-3c4c1d00-b91e-11ea-8c1e-91f8736e70f9.png)

### FileAssoc-3-Application.png
![resized_FileAssoc-3-Application](https://user-images.githubusercontent.com/11251874/85934505-453cee80-b91e-11ea-901c-afd6b2598314.png)


### FileAssoc-4-DefaultApp.png
![resized_FileAssoc-4-DefaultApp](https://user-images.githubusercontent.com/11251874/85934507-4a01a280-b91e-11ea-882e-bd7aa22dfa27.png)

### FileAssoc-5-ChooseDefaultApp.png
![resized_FileAssoc-5-ChooseDefaultApp](https://user-images.githubusercontent.com/11251874/85934511-4d952980-b91e-11ea-8f98-4636a47332b9.png)

### FileAssoc-6-ChooseDefaultApp.png
![resized_FileAssoc-6-ChooseDefaultApp](https://user-images.githubusercontent.com/11251874/85934513-5128b080-b91e-11ea-9243-04115e783088.png)

### FileAssoc-7-ChooseDefaultAppTxt.png
![resized_FileAssoc-7-ChooseDefaultAppTxt](https://user-images.githubusercontent.com/11251874/85934515-571e9180-b91e-11ea-8da4-addb2c3817f0.png)

### FileAssoc-8-ChooseDefaultAppTxt.png
![resized_FileAssoc-8-ChooseDefaultAppTxt](https://user-images.githubusercontent.com/11251874/85934517-5ab21880-b91e-11ea-9d2f-d5c24d5df310.png)

### FileAssoc-9-ChooseTxt-Sakura.png
![resized_FileAssoc-9-ChooseTxt-Sakura](https://user-images.githubusercontent.com/11251874/85934518-5e459f80-b91e-11ea-8605-4edad497a9b3.png)


## ファイルサイズや解像度
![image](https://user-images.githubusercontent.com/11251874/85934534-8af9b700-b91e-11ea-912a-8d4c4513334e.png)

**Comment by beru** [comment]
画像ファイルには手を入れずに、HTML側で相対サイズ指定を入れるやり方の対処を #1328 で行いました。

**Comment by arigayas** [comment]
(´；ω；`)

**Comment by beru** [comment]
(◞≼☉≽◟◞౪◟◞≼☉≽◟)

**Comment by arigayas** [comment]
> (◞≼☉≽◟◞౪◟◞≼☉≽◟)

怖いww

**Comment by k-takata** [comment]
DPI 100%でキャプチャーしてみた。

1.
![assoc1](https://user-images.githubusercontent.com/840186/85936671-cfde1780-b937-11ea-8e47-ac4ac9a8e734.png)

2.
![assoc2](https://user-images.githubusercontent.com/840186/85936685-e4221480-b937-11ea-8461-55256ba7d6f4.png)

3.
![assoc3](https://user-images.githubusercontent.com/840186/85936689-ea17f580-b937-11ea-917a-5c48d5989f18.png)

4.
![assoc4](https://user-images.githubusercontent.com/840186/85936694-f308c700-b937-11ea-943c-8eb713fde2e5.png)

5.
![assoc5](https://user-images.githubusercontent.com/840186/85936697-f9973e80-b937-11ea-8379-2bd09f551e15.png)

6.
![assoc6](https://user-images.githubusercontent.com/840186/85936703-0025b600-b938-11ea-93d2-c1587075a0a4.png)

7.
![assoc7](https://user-images.githubusercontent.com/840186/85936994-a1ae0700-b93a-11ea-8b5b-eb595ec3b7cf.png)

8.
![assoc8](https://user-images.githubusercontent.com/840186/85937011-a96dab80-b93a-11ea-888d-36bcef88b6b6.png)

9.
![assoc9](https://user-images.githubusercontent.com/840186/85937024-b25e7d00-b93a-11ea-92fb-3fb8f915dc9f.png)

もうちょっとウィンドウ幅を狭くしてもよかったかな？

**Comment by arigayas** [comment]
ウィンドウ幅は1000px以下にするのが良さそう。

Microsoftの「ペイント」でルーラー表示させればウィンドウ幅は測りやすいと思います。

**Comment by beru** [comment]
> HiDPI 200%の環境でキャプチャした画像を載せてあるのだと思いますが、100%の環境でキャプチャし直すか、面倒ならば半分のサイズに縮小するのがよいのではないでしょうか。

- FileAssoc-1-StartMenu.png
- FileAssoc-2-Setting.png
- FileAssoc-3-Application.png
- FileAssoc-4-DefaultApp.png
- FileAssoc-5-ChooseDefaultApp.png
- FileAssoc-6-ChooseDefaultApp.png
- FileAssoc-7-ChooseDefaultAppTxt.png
- FileAssoc-8-ChooseDefaultAppTxt.png
- FileAssoc-9-ChooseTxt-Sakura.png

はディスプレイ設定の表示スケール 150% でキャプチャ

- Grep.png
- GrepReplace.png

はディスプレイ設定の表示スケール 200% でキャプチャ

したように思えます。

その他の画像は昔にスクリーンショットが取られたものだと思いますが、表示スケールは 100% のいわゆる HiDPI ではないものだと思います。

----

@arigayas さんがやったように大きい画像を縮小したり、@k-takata さんがやったように表示スケール 100% の設定でスクリーンショットを取った画像に差し替えれば、画像がやたら大きくてみづらい問題は解消されます。

ただしそもそもどうしてこういう問題が起きるのかを認識する必要があります。

**Comment by beru** [comment]
# ディスプレイの解像度 1920 x 1080、表示スケール 100%

今現在最も多くのユーザーが使っていると思われる設定で確認します。

## Chrome ブラウザ

ヘルプのファイルをChromeブラウザで開いた際のスクリーンショットを紹介します。なお `バージョン: 83.0.4103.116（Official Build） （64 ビット）` で確認しています。

### HLP000074.html

![image](https://user-images.githubusercontent.com/1131125/85945824-39cbe080-b97b-11ea-9e2f-c039cb42418a.png)

### HLP000374.html

![image](https://user-images.githubusercontent.com/1131125/85946064-cdea7780-b97c-11ea-88da-134b9d6d8fe0.png)

画像がやたら大きくてみづらいです。

## hh.exe (Microsoft® HTML ヘルプの実行可能ファイル)

hh.exe というのはサクラエディタのヘルプのファイル sakura.chm を表示するのに使われるWindows標準のアプリです。

### HLP000074.html

![image](https://user-images.githubusercontent.com/1131125/85945997-6a604a00-b97c-11ea-974f-570a1ee46871.png)

### HLP000374.html

![image](https://user-images.githubusercontent.com/1131125/85946152-3e919400-b97d-11ea-8060-9ee3a8955e48.png)

ブラウザで表示するのと同様に画像がやたら大きくてみづらいです。

**Comment by beru** [comment]
# ディスプレイの解像度 3840 x 2160、表示スケール 200%

次にいわゆる 4K と呼ばれている解像度で確認します。この解像度だと表示スケールを上げないと表示が小さすぎて操作しにくいので 200% とかに設定する事が多いです。

## Chrome ブラウザ

### HLP000074.html

![image](https://user-images.githubusercontent.com/1131125/85946242-02126800-b97e-11ea-8536-ebc1c77d023b.png)

ChromeブラウザはOSの表示スケールに合わせて画像を拡大して表示してくれます。

### HLP000374.html

![image](https://user-images.githubusercontent.com/1131125/85946244-10f91a80-b97e-11ea-8f02-a11fa98dc95d.png)

画像が拡大して表示されるので画像がやたら大きくてみづらいです。

## hh.exe (Microsoft® HTML ヘルプの実行可能ファイル)

### HLP000074.html

![image](https://user-images.githubusercontent.com/1131125/85946293-61707800-b97e-11ea-9301-cec47ccb13c7.png)

画像が引き延ばされずに小さく表示されます。

### HLP000374.html

![image](https://user-images.githubusercontent.com/1131125/85946308-7947fc00-b97e-11ea-97ae-f779a18b9b73.png)

**Comment by beru** [comment]
一般的に使われているChrome等のウェブブラウザでは、サイズを特に指定していなかったり、px(ピクセル)でサイズ指定した画像タグの表示要素はOSの表示スケールの設定に合わせて拡大して表示されています。

拡張子が chm のヘルプファイルを表示するビューワーは画像を拡大せずにそのまま表示します。なのでDPI 100% の環境でキャプチャした画像を DPI 200% の環境で表示すると小さく表示されて見辛いです。

なので https://github.com/sakura-editor/sakura/issues/1325#issuecomment-650567489 でコメントした通り、相対単位のサイズ指定を全ての画像タグに入れる変更を入れるのが適切な対応だと思います。そうする事で色々なDPIの表示環境でヘルプの画像が極端に小さくまたは大きく表示される問題を緩和出来るのではないかと。

**Comment by berryzplus** [comment]
この issue と直接関係ない話ですが・・・。

> 「Windows 10 でのファイル拡張子関連付け」
> https://sakura-editor.github.io/help/HLP000374.html

このトピックって、目次に追加し忘れてますね。
目次にはトピック一覧の役割もあると思うので、追加しとくのがベターだと思います。

ヘルプってたぶん、こんな感じに使うものだと思います。
<img alt="HLP000374" src="https://user-images.githubusercontent.com/3253151/85947114-cda1aa80-b983-11ea-9ec1-1a26ae525e06.png" width="595" />
こうしてみると、画像幅以外にもツッコミどころたくさんあるような気がしないでもない・・・。

**Comment by beru** [comment]
#1328 を Merge したので Close します。
