### ISSUE TITLE
単体テストで x64 Debug で CDlgProfileMgr.TrySelectProfile_001 で assert になる

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#1334]
## 問題内容

* [x] 単体テストで x64 Debug で CDlgProfileMgr.TrySelectProfile_001 で assert になる
https://github.com/sakura-editor/sakura/blob/4cd308f9f524935997e5974bd3ad566fe21c5e7d/sakura_core/CSelectLang.cpp#L102-L103
* [ ] assert がポップアップで表示される。

## 再現手順

master をチェックアウトして以下を実行する

`tests\build-and-test.bat x64 Debug
`

## 問題のカテゴリ

- 単体テスト

## スクリーンショット

![image](https://user-images.githubusercontent.com/5567450/86522500-c0138580-be99-11ea-9c4d-cb082ddf1095.png)

**Comment by m-tmatma** [comment]
以下を入れてみたが、変わらなかった。

```
		_CrtSetReportMode( _CRT_WARN  , _CRTDBG_MODE_FILE );
		_CrtSetReportMode( _CRT_ERROR , _CRTDBG_MODE_FILE );
		_CrtSetReportMode( _CRT_ASSERT, _CRTDBG_MODE_FILE );
		_CrtSetReportFile( _CRT_WARN  , _CRTDBG_FILE_STDERR );
		_CrtSetReportFile( _CRT_ERROR , _CRTDBG_FILE_STDERR );
		_CrtSetReportFile( _CRT_ASSERT, _CRTDBG_FILE_STDERR );

```

https://docs.microsoft.com/en-us/previous-versions/visualstudio/visual-studio-2010/1y71x448(v=vs.100)?redirectedfrom=MSDN
https://www.keicode.com/windows/win16.php

**Comment by berryzplus** [comment]
端的には「単体テストで文字列リソースを利用できるようにする #1275」が `CMakeLists.txt` に反映されていないことが原因であると考えられます。

ここのライブラリ参照に `*.res` を追加してやれば `CMakeLists.txt` に #1275 相当の対処を行えます。
https://github.com/sakura-editor/sakura/blob/ff24e991212b9792801fac4331687306fa15a402/tests/unittests/CMakeLists.txt#L36

個人的には「`CMakeLists.txt` は MinGW 専用です」でいいような気もしますが・・・。

あと、「おま環」だと思うのですが、現状の master ff24e991212b9792801fac4331687306fa15a402 で上記コマンドを実行した場合、ビルドが通りませんでした。#1322 の Draft PR でビルド通るように修正してみたので、折を見て修正反映していきたいです。

**Comment by m-tmatma** [comment]
@berryzplus 
assert がポップアップで表示される。
に関しても修正したいですが、
原因わかりますか？

**Comment by berryzplus** [comment]
> assert がポップアップで表示される。
> に関しても修正したいですが、
> 原因わかりますか？

事象がよくわかってないかも知れません。

#1337 でポップアップは出なくなると思うんですが、そういうことじゃない？
assert(false)のときにポップアップさせたくない、と言ってる気がしました。

**Comment by m-tmatma** [comment]
出なくなるのはそれでいいのですが、

もし別の問題でassertが出たときにポップアップではなく、コンソール出力させて、ブロッキングさせないようにしたいです。

**Comment by berryzplus** [comment]
> もし別の問題でassertが出たときにポップアップではなく、コンソール出力させて、ブロッキングさせないようにしたいです。

う～ん・・・。assertってのはそういうもの（＝前提が成立しなかったら即時終了させる）なので、`止めたくないならassert使わなきゃ良かろう` な気がしないでもないです。

ただ、サクラエディタはassertマクロを独自にカスタムしてるので、標準的なC言語ランタイムの挙動を上書きできないこともないです。
https://github.com/sakura-editor/sakura/blob/851d652c1710ebc0d49695cab1db5e72d70a6983/sakura_core/debug/Debug2.h#L41-L47

ここで `MessageBoxA` を呼ばないようにすれば、ブロックせずに即時終了します。
https://github.com/sakura-editor/sakura/blob/851d652c1710ebc0d49695cab1db5e72d70a6983/sakura_core/debug/Debug2.cpp#L29-L35

どちらかというと、assertしないようにしてくのがベターだと思いますが、対策できないことはないって感じです。

**Comment by m-tmatma** [comment]
なるほど独自で上書きしてたんですね。

問題は、単体テストはコンソールアプリで、
ci から呼ぶ前提なのにダイアログを出していることであって、プログラムの動きを止めることではないです。

ci に優しくないことです。

**Comment by m-tmatma** [comment]
コンソールアプリだと、assert の内容を標準出力あるいはエラー出力に、表示して、ユーザー操作なく終了するのが期待値なのに、ユーザーがokを押さないと、終了しないのが問題です。

**Comment by berryzplus** [comment]
MessageBox関数はWindows APIですが、サクラエディタは多言語対応のためにこのAPI関数の呼び出しをラップしています。

あえてグローバルなフラグ変数を定義して、テストプログラムから呼び出した場合にはメッセージボックスを出さないように追加のカスタマイズを行うことができそうです。
http://opencv.jp/googletestdocs/advancedguide.html#adv-global-setup-teardown

`stderr` が存在していたら（≒stderrのハンドルが有効だったら）メッセージボックスを出さないってやり方もできそうです。

ちょっと裏取りが要ると思うんですけど、メッセージボックスの表示によってテストプログラムの実行がブロックされた場合はCIの実行がタイムアウトになって「CIとしては正常に異常を検知して終了」するような気がします。もちろん、それを良しとするかどうかは別な話ですけど。

**Comment by m-tmatma** [comment]
タイムアウトを待つ方法だと、メッセージボックスの表示内容、つまりassertの内容がciで確認できないのでやりたいことができてないです。

**Comment by m-tmatma** [comment]
エディタ本体の場合に有効になるフラグを用意して、それが有効な場合にダイアログを出すようにしたら、簡単で確実だと思います

**Comment by m-tmatma** [comment]
↑ winwain でセットするような感じで
