### ISSUE TITLE
英語化不足

### ISSUE THREAD

**Issue by Celeter** [sakura-editor/sakura#1335]
## 問題内容

sakuraのタイトルバーで「デスクトップ」を翻訳していない。

## 再現手順

OS：英語版 Windows 10 64bit
デスクトップに新しいファイルを作成した後、
タイトルバーで「デスクトップ」を翻訳していない。
![desk](https://user-images.githubusercontent.com/48249130/86734539-a3777900-c064-11ea-8814-c462ea00ff30.png)

**Comment by m-tmatma** [comment]
英語版 OS でも同じですね。

![image](https://user-images.githubusercontent.com/5567450/87850697-259d5280-c92d-11ea-85ff-3e54f48ca7a4.png)

**Comment by m-tmatma** [comment]
↑ 間違っていたので訂正しました。

**Comment by berryzplus** [comment]
これは `ファイル名表示` という機能です。
特定の環境変数と一致するパスを `sakura.ini` に設定された通りに置換します。

<details>
<summary>sakura.iniの該当部分抜粋</summary>
<pre><code>
[Nickname]
ArrNum=7
From00=%DeskTop%\
From01=%Personal%\
From02=%Cache%\Content.IE5\
From03=%TEMP%\
From04=%Common DeskTop%\
From05=%Common Documents%\
From06=%AppData%\
To00=デスクトップ\
To01=マイドキュメント\
To02=IEキャッシュ\
To03=TEMP\
To04=共有デスクトップ\
To05=共有ドキュメント\
To06=アプリデータ\
bShortPath=1
nShortPathMaxWidth=100
</code></pre>
</details>

とりあえず、こいつら↓を `LS` マクロを使う方式にしたら暫定対処になるかもです。
https://github.com/sakura-editor/sakura/blob/4042535ab77e6cfed29156dc13c4410f15299007/sakura_core/env/CShareData.cpp#L594-L607

誤） `wcscpy( sFileName.m_szTransformFileNameTo[0],   L"デスクトップ\\" );`
正） `wcscpy( sFileName.m_szTransformFileNameTo[0],   LS( STR_TRANSNAME_DESKTOP ) );`

本質的には、そもそもそういう問題じゃなくて？と思っていて、`英語化不足` というより`多言語対応の方針に問題がある` なんじゃないかと考えています。

**Comment by berryzplus** [comment]
...ツッコミ待ち。

**Comment by berryzplus** [comment]
ただ待ってもダメかも知れないので考える材料を撒いときます。


①標準インストール（≒日本語設定）でファイル名表示を確認するとこうなっています。
[<img alt="ファイル名表示の設定" src="https://user-images.githubusercontent.com/3253151/87877560-0a5c4100-ca1a-11ea-8316-9b3c2a731b37.png" width="600" />](https://user-images.githubusercontent.com/3253151/87877560-0a5c4100-ca1a-11ea-8316-9b3c2a731b37.png)

②ここで、言語を英語に切り替えます。OKで設定ダイアログを閉じるのを忘れないでください。
[<img alt="言語の変更（日本語⇒English）" src="https://user-images.githubusercontent.com/3253151/87877657-79d23080-ca1a-11ea-970e-dd2d74bc1749.png" width="600" />](https://user-images.githubusercontent.com/3253151/87877657-79d23080-ca1a-11ea-970e-dd2d74bc1749.png)

③UIが英語化されたのを確認してから設定を確認すると、こんな風になっています。
[<img alt="Filename Displayの設定" src="https://user-images.githubusercontent.com/3253151/87877704-c584da00-ca1a-11ea-8920-b6278136e4ad.png" width="600" />](https://user-images.githubusercontent.com/3253151/87877704-c584da00-ca1a-11ea-8920-b6278136e4ad.png)

挙動がissueでの報告と異なっている原因は、このコードにあります。言語変更前にリソースから取得する文字列の一覧をキャッシュしておき、変更後にキャッシュに該当する文字列をリソース（＝変更後の言語）で置換しています。
https://github.com/sakura-editor/sakura/blob/a55d9e2b260befef6e3f2f175ec8ec502673bc74/sakura_core/_main/CControlTray.cpp#L602-L612

issueで指摘されている不具合（？）の混入契機は #749 `新規インストール時に言語設定に英語を適用する処理方法の変更` と考えられるので、たぶんなんか対応せにゃならん感じかと思います。

**Comment by berryzplus** [comment]
@Celeter さん
#1350 がapproveされたのでマージします。
修正により、英語OSで新規インストールした場合に日本語設定が残る不具合は解消されます。
既にインストールしてあるサクラエディタの場合、一度日本語に変え絵から英語に戻してみてください。
