### ISSUE TITLE
共通設定のウィンドウタブから他の設定タブに移動すると落ちる

### ISSUE THREAD

**Issue by Suzakura** [sakura-editor/sakura#1339]
## 問題内容
共通設定のウィンドウから他の設定タブに移動すると必ずサクラエディタが落ちてしまいます。

## 再現手順
[共通設定]-[ウィンドウ]
ウィンドウタブを選択した後はどの設定タブを押しても同じように問題が発生します。

## 再現頻度
100%再現可能です。

## 問題のカテゴリ
- 仕様の問題

## 環境情報
- OS バージョン

Windows10 Home 64bit版
- サクラエディタバージョン

v2.4.2.2904 32bit dev
v2.4.1.2849 32bit (tag v2.4.1)では再現せず。
- PC情報

**Comment by beru** [comment]
インストーラーのリンクです。
https://ci.appveyor.com/api/buildjobs/o6q61xk26gnvop99/artifacts/sakura-build2904-851d652-Win32-Release-Installer.zip

自分の環境でも再現しました。

**Comment by beru** [comment]
版   | 再現するか
-----|----
v2.4.2.2904 | する
v2.4.2.2879 | する
v2.4.2.2858 | する
v2.4.2.2854 | しない

という事で #1307 で行われた変更 74a06756ba0e8e80914855ade32e6a230e7b7831 に問題があるようです。

**Comment by berryzplus** [comment]
報告ありがとうございます。原因調査します。

**Comment by berryzplus** [comment]
原因わかりました。

`CSelectLang::InitializeLanguageEnvironment` が呼ばれないのが原因で、言語リストの先頭を `at` して落ちています。

対策は、この関数が常に呼ばれるようにしてやれば良いです。

**Comment by Suzakura** [comment]
無事解決致しましたので閉じました。

ありがとうございました！
