### ISSUE TITLE
ツールバーに設定された「検索（ボックス）」の表示場所がおかしい

### ISSUE THREAD

**Issue by Suzakura** [sakura-editor/sakura#1343]
## 問題内容

sakura-editor/management-forum#83
▲こちらでも発信させて頂いていますが、未修正のバグのようなのでこちらにも報告しておきます。
ツールバーに表示設定された「検索（ボックス）」が本来表示されるべき場所ではなく、ツールバー左上端に表示されてしまう問題が発生しています。
「検索（ボックス）」の下には別のツールバーアイコンが「検索（ボックス）」の下に隠れてしまっていますので、そのツールバーアイコンをクリックすることが出来ません。
本来「検索（ボックス）」が表示されるべき場所は空白（スペース）が確保されています。

## 再現手順

[共通設定]-[ツールバー] にて「検索（ボックス）」をツールバーに表示するように設定する。

## 再現頻度

100%再現可能です。

## 問題のカテゴリ

- 仕様の問題

## 環境情報
- OS バージョン

　　Windows10 Home 64bit版
- サクラエディタバージョン

　　v2.4.1.2849 32bit (tag v2.4.1)
　　sakura-editor/sakura#1313 で修正された v2.4.2.2904 32bit dev でも再現されます。
　　v2.3.2.0 では再現されませんでした。

- PC情報

　　特になし

## スクリーンショット

![87118699-019b9a80-c2b7-11ea-9a0a-e08bbd3d7912](https://user-images.githubusercontent.com/1965971/87215606-189fc280-c373-11ea-856a-47ee1bbdc7f2.PNG)

**Comment by berryzplus** [comment]
最新[master](https://github.com/sakura-editor/sakura/commit/5e9dd8faa1e88fa2a74639abbb9c0571d9d74f56)で再現できませんでした。
[<img alt="image" title="開発版最新 Win32 - Release" src="https://user-images.githubusercontent.com/3253151/87222492-deecad00-c3ae-11ea-8227-d4ba2cc6e378.png" width="500" />](https://user-images.githubusercontent.com/3253151/87222492-deecad00-c3ae-11ea-8227-d4ba2cc6e378.png)

iniの問題かも知れないので、試したiniの該当部分を載せておきます。
<details>
<summary>sakura.ini(Toolbar設定)</summary>
<pre>
<code>[Toolbar]
bToolBarIsFlat=1
nTBB[000]=246
nTBB[001]=1
nTBB[002]=25
nTBB[003]=3
nTBB[004]=4
nTBB[005]=0
nTBB[006]=33
nTBB[007]=34
nTBB[008]=0
nTBB[009]=87
nTBB[010]=88
nTBB[011]=0
nTBB[012]=384
nTBB[013]=225
nTBB[014]=226
nTBB[015]=227
nTBB[016]=228
nTBB[017]=229
nTBB[018]=230
nTBB[019]=0
nTBB[020]=232
nTBB[021]=0
nTBB[022]=264
nTBB[023]=265
nTBB[024]=266
nTBB[025]=0
nTBB[026]=346
nToolBarButtonNum=27</code>
</pre>
</details>

一通り解決したら再度リリースしないと、ツールバー折り返しができない問題が残ってしまいますね・・・。

**Comment by Suzakura** [comment]
追加報告です。
ツールバーに「検索（ボックス）」を追加する場所は「ツールバー折返」より後ろに設置した時のみに発生します。

**Comment by berryzplus** [comment]
> 「検索（ボックス）」を「ツールバー折返」より後ろに設置した時にのみ発生します。

つまりそれは「検索（ボックス）」を2つ配置したってことですよね？

ツールバー内に同一IDのボタンが複数あるのが原因と思われます。
v2.3.2.0で再現しない理由は分からんです...orz

**Comment by berryzplus** [comment]
違ってそうですね。

ツールバー折り返しの後に「検索（ボックス）」を配置すると、1行目に表示されてしまうってことですかね。

それならば原因調査して対策ができそうです。

**Comment by Suzakura** [comment]
ややこしい説明で申し訳ございません。

> ツールバー折り返しの後に「検索（ボックス）」を配置すると、1行目に表示されてしまうってことですかね。

そうです。ツールバー折り返しの後に検索ボックスを配置すると1桁目に表示されてしまいます。
ツールバー折り返しより前に配置した場合はちゃんと配置した場所に表示されます。

**Comment by berryzplus** [comment]
原因が分かりました。

https://github.com/sakura-editor/sakura/blob/5e9dd8faa1e88fa2a74639abbb9c0571d9d74f56/sakura_core/window/CMainToolBar.cpp#L337-L339

3つ目の引数で コンボボックスの垂直位置を指定しているのですが、ここの指定で2行目以降が指定される事態が考慮されていません。現状の指定にオフセット位置 `rc.top` を加えてやれば 2行目 にコンボボックスを配置した場合にも対応できそうです。

**Comment by Suzakura** [comment]
v2.4.2.2918 32bit dev にてバグ修正を確認致しました。
ありがとうございます！

問題解決致しましたので、一旦閉じさせていただきます。

**Comment by k-takata** [comment]
#1345 はまだ master に取り込まれていないので、閉じるのはまだ早かった気もします。（まあ、reopenするほどでもないでしょうが。）（さらに言えば、#1345 が master に取り込まれれば、こちらは自動的にcloseされるようになっていました。）

**Comment by berryzplus** [comment]
いま #1345 をマージしてきたので、このままcloseで良いと思われます。

**Comment by Suzakura** [comment]
> #1345 が master に取り込まれれば、こちらは自動的にcloseされるようになっていました。

はぅあっ⁈
そうだったのですね。
masterの最新<https://ci.appveyor.com/project/sakuraeditor/sakura/branch/master からのダウンロード物>に反映されているようでしたし、issuesを発行した自分が責任をもって閉じなくちゃいけないものと勝手に思い込んでおりました。

ホント、失礼いたしました。

**Comment by beru** [comment]
> masterの最新<https://ci.appveyor.com/project/sakuraeditor/sakura/branch/master からのダウンロード物>に反映されているようでしたし、issuesを発行した自分が責任をもって閉じなくちゃいけないものと勝手に思い込んでおりました。

Issue の作成者が、問題が解決した後にその Issue を閉じる責任があるかどうかについてですが、もちろんそうしていただくに越したことは無いですが、努力義務未満のものだと思います。github には色々なプロジェクトがありますが、その中にはもしかしたら4桁の数の Issues が放置されてるものさえあるかもしれません。

あと些細な事ですが正確にはコメント https://github.com/sakura-editor/sakura/issues/1343#issuecomment-657183979 時点で確認された v2.4.2.2918 ビルドは、まだ master にマージされる前のPRのブランチ `feature/adjust_searchbox` のものだと思います。

https://ci.appveyor.com/project/sakuraeditor/sakura/history を見ると下記のような表示がありますが、
![image](https://user-images.githubusercontent.com/1131125/87442744-9ee82d00-c62f-11ea-8bbd-7a145572eabe.png)
左向きの矢印（←）の左側にはマージ先の `master` ブランチ、右側にはPRブランチ `feature/adjust_searchbox` が書かれています。情報量が多いので読み取るのが難しいですね。

なおPRの説明のコメント中にキーワード付きで Issue の番号を指定する事で、PRがマージされた時に指定した Issueを自動的に Close する事が出来ます。#1345 の説明を見ると `fixes #1343` という記載が有るので多分それがその役目を果たしています。

github や gitlab だけでなく昔から存在する RedMine や Trac のようなチケット駆動開発のプロジェクト管理ツールの頃から、SVN や Git 等の版管理ソフトのコミットメッセージの中にキーワード付きでチケットの番号を指定する事で、関連付けたりチケットを閉じるなどの色々なアクションを行う事が出来る機能が存在し利用されています。

**Comment by Suzakura** [comment]
beruさん、ありがとうございます！
凄く勉強になります。

> https://ci.appveyor.com/project/sakuraeditor/sakura/history を見ると下記のような表示がありますが、
> ![image](https://user-images.githubusercontent.com/1131125/87442744-9ee82d00-c62f-11ea-8bbd-7a145572eabe.png)
> 左向きの矢印（←）の左側にはマージ先の master ブランチ、右側にはPRブランチ feature/adjust_searchbox が書かれていま>す。情報量が多いので読み取るのが難しいですね。

なるほど。 https://ci.appveyor.com/project/sakuraeditor/sakura/history のその部分を確認すればmaster ブランチへのマージ前かどうかが分かるんですね！

まだまだGitHubに不慣れなところもありますが、少しずつ慣れていきたいと思います。
また、色々と教えて下さい♪
