### ISSUE TITLE
インストーラーで「起動時に常駐」チェックした場合の挙動

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#135]
実はいまでも起きてるかもしれない事実。
インストーラーで起動時に常駐をチェックすると、
スタートアップにショートカットが作られます。
オプションにNOWINがついてます。
タスクトレイを使わない設定にすると、
おそらく起動してすぐ落ちてるのではないかとおもわれます。

次回リリースは、タスクトレイの常駐をOffにするのがデフォルトかと思うので、
この事象が最初から顕著化すると想像します。

対策は、
１　インストーラーのこの項目を削除する。
２　インストーラーで常駐Onのiniファイルをつくる。（要検証）
３　なにもしない

どうしましょ。

**Comment by berryzplus** [comment]
ちゃんと確認しなきゃですが、その場合の動作はwindows起動してから最初のサクラエディタが終了するまで常駐、という動きになるのではないかと思います。

当面1で良いと思います。開発でなんども動かしてますが管理プロセスの起動は常駐させなきゃいけないほど遅くはないと思っています。

余裕があればインストーラで細々してあげる方式ですが、後日対応でもいいのかなと思います。

**Comment by berryzplus** [comment]
> プロセス見る限りスタートアップショートカット起動しても起動されない（すぐ落ちてる？）もようです。

（　￣Д￣）ええっ！　・・・　確認中

**Comment by berryzplus** [comment]
> > プロセス見る限りスタートアップショートカット起動しても起動されない（すぐ落ちてる？）もようです。
> 
> （　￣Д￣）ええっ！　・・・　確認中

確認完了。

GitHubから落としたソースをビルドしたやつでやって見た限りでは、
```sakura.exe -NOWIN``` を常駐しない設定で起動した場合は、
後続で起動してきたエディタ画面が終了した直後まで居座る動きになるようでした。

https://github.com/sakura-editor/sakura/blob/11cb42171426e63f07cea280cfe412c975762fa6/sakura_core/_main/CControlTray.cpp#L530-L533

MYWM_DELETE_ME はエディタ終了監視のタイマーから投げられるメッセージで、
エディタ終了監視は1つ以上のエディタが「終了」しない限りこのメッセージを投げないようです。

**Comment by berryzplus** [comment]
はぅ・・・検討違い。

```sakura.exe -NOWIN``` で起動できるプロセスは、プロファイルを分けない限り1システム1つだけです。たぶん、共有メモリのマップファイルを開きにいって、開けなくて落ちてるんではないかと。

**Comment by KENCHjp** [comment]
平たく言うと、設計不良ってこと？

**Comment by berryzplus** [comment]
う～む・・・。コードをもう一度よく確認してみたんですけど、これは設計不良というよりコーディングミスな気がしてきました。なので、一旦バグとして Pull Request 投げることにしました。@kobake さんのご意見も聞きたい感じです。

**Comment by kobake** [comment]
あ、すみません、メンション今気づきました。

> ２　インストーラーで常駐Onのiniファイルをつくる。（要検証）

これに一票です。

> 「常駐しない」設定でも「 sakura.exe -NOWIN 」したらエディタなしで常駐します。

これを問題とみなすかどうかは、、、判断むずいですね、、、ちょっと考えます

**Comment by KENCHjp** [comment]
これ、結局実装は元に戻ってるんでしたっけ？？？
実装大変だからって感じなら、いったんインストーラーで対応します？
@berryzplus さん。

**Comment by KENCHjp** [comment]
@berryzplus さん。
失礼しました、これexe単体で動かしたときのデフォルト挙動を気にしていたのでインストーラーの話じゃなかったですね失礼しました。

**Comment by berryzplus** [comment]
> これ、結局実装は元に戻ってるんでしたっけ？？？

「バグ修正でなく仕様変更が必要」ということになり、PRは破棄しました。

いったんは「常駐設定の内容と関係なく`sakura.exe -NOWIN`したらサクラを開いて閉じるまで常駐します」というのが現状の仕様です。

この issue はまだ閉じられないと思っています。

**Comment by KENCHjp** [comment]
>この issue はまだ閉じられないと思っています。

了解です。

**Comment by berryzplus** [comment]
このissueの成果。
デフォルト設定が「常駐しない」に変わりました。
残タスクないようなので閉じておきます。
