### ISSUE TITLE
ビルド要件のドキュメントが古くなっている

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1357]
ビルド要件のドキュメントが古くなっています。

どっかで対応しておきたいです。

**Comment by berryzplus** [comment]
## 見えている不具合箇所

> Visual Studio Install options required
> Windows SDK
> Windows XP Support for C++
> Windows 8.1 SDK と UCRT SDK
> C++ に関する Windows XP サポート

- windows SDK ではなく windows 10 SDK が必要。
  - 必要なバージョンはvisual studioのバージョンによって異なる。
- xpサポートが重複して書かれている（英語表記と日本語表記が両方記載されている）
- xpサポートはもはや不要。
- windows 8.1 SDK は不要になった。
- Universal CRT SDK が不要になったかどうかは要調査。

**Comment by kazasaku** [comment]
夜分遅くに失礼します。
たまたまPCにVisual Studioが入っていなかったので、インストールついでに調べてみました。

次の環境にて最新のmasterをビルドしてみました。
- Windows 10 Pro（バージョン:2004、ビルド:19041.450、64ビット）
- Visual Studio Installer バージョン:2.7.3064.805
- Visual Studio Community 2019（バージョン:16.7.2）

結果から言えば、次のワークロード・コンポーネントを追加すると実行ファイルのビルドに成功しました。
（ビルドした実行ファイルで普段通りの作業ができることも一応確認しました。）
- C++ によるデスクトップ開発 ["Microsoft.VisualStudio.Workload.NativeDesktop"]
- MSVC v142 - VS 2019 C++ x64/x86 ビルド ツール (v14.27) ["Microsoft.VisualStudio.Component.VC.Tools.x86.x64"]
- Windows 10 SDK (10.0.18362.0) ["Microsoft.VisualStudio.Component.Windows10SDK.18362"]
- Windows 用 C++ CMake ツール ["Microsoft.VisualStudio.Component.VC.CMake.Project"]

> xpサポートはもはや不要。
> windows 8.1 SDK は不要になった。
> Universal CRT SDK が不要になったかどうかは要調査

「C++ に関する Windows XP サポート（["Microsoft.VisualStudio.Component.WinXP"]）」と、「Windows Universal CRT SDK（["Microsoft.Component.VC.Runtime.UCRTSDK"]）」はVS2019でも利用できますが、前述の通り選択していません。
また、次のコンポーネントはVS2019にありませんでした。
 - Windows 8.1 SDK と UCRT SDK ["Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Win81"]
 - Windows 8.1 SDK ["Microsoft.VisualStudio.Component.Windows81SDK"]
 - C++ に関する Windows XP サポート ["Microsoft.VisualStudio.ComponentGroup.NativeDesktop.WinXP"]
※名称は同じですが、コンポーネントIDが違います。

余談ですが、サクラエディタの.vsconfigにて、CMakeツールのコンポーネントIDが2回記述されており重複しています。

以上、ご報告させていただきます。

※参考にしたページ
①：Visual Studio Community 2017 のコンポーネント ディレクトリ
https://docs.microsoft.com/ja-jp/visualstudio/install/workload-component-id-vs-community?view=vs-2017
②：Visual Studio Community 2019 のコンポーネント ディレクトリ
https://docs.microsoft.com/ja-jp/visualstudio/install/workload-component-id-vs-community?view=vs-2019

**Comment by berryzplus** [comment]
@kazasaku さん　報告ありがとうございます。どこかで `.vsconfig` を更新せねば・・・。

**Comment by sanomari** [comment]
初めてソリューションを開いたときに、プロジェクトを読み込めませんでした。

vs2019なのでwindows 10 SDKの17763は入れていませんでした。
でも.vsconfigに記載されているので「不足コンポーネントがある」と認識されたのではないかと。
ただ、vs2019では18362のwin10SDKが使われてるみたいなので、なにかが変です。

**Comment by kazasaku** [comment]
sanomari様、お疲れ様です。

MS公式サイトにあるVS2017のワークロード一覧にはSDKバージョン18362がないので、
VS2017を想定している.vsconfigなら17763が指定されていてもOKだと思います。
一応、前述の報告の際にどちらでもビルドできることを確認してあります。

**Comment by sanomari** [comment]
kazasakuさん
vs2017はもう消してしまったので使ってないです。
17763をアンインストールして試してみたところ、メッセージが出ていてもビルドはできるようでした。
プロジェクトロードに失敗した気がしたんですが再現しませんでした。

**Comment by kazasaku** [comment]
#1623 にて記述の更新を行いました。
なお、ビルド要件をREADME.mdに記載する必要性を #1441 で検討中です。
