### ISSUE TITLE
コマンドラインオプション「-WQ(INIファイルを出力して即終了)」が使えない

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1377]
## 問題内容

コマンドラインオプション「-WQ(INIファイルを出力して即終了)」が機能していません。
https://sakura-editor.github.io/help/HLP000109.html

## 再現手順

`-WQ` オプションを指定してサクラエディタを起動します。
（Releaseビルドの場合、何も起きません。Debugビルドの場合、クラッシュを告げるダイアログが出ます。）

期待結果は、sakura.iniが作成されていなければ作成する、です。
（何もおきません。）

## 再現頻度

100%

## 問題のカテゴリ

- プログラムの動作上の問題
  - 正式リリース版
  - Azure Pipelines ビルド版
  - Appveyor ビルド版
  - ローカルビルド版

## 環境情報
- OS バージョン  
利用するOSバージョンに関係なく発生する不具合です。
- サクラエディタバージョン  
v2.0.0より前から存在する不具合のようです。  
原因コミットは https://github.com/sakura-editor/sakura/commit/24557f0da2135d2c288747a9189520843999cd58 です。
- PC情報  
利用するPCに関係なく発生する不具合です。

**Comment by berryzplus** [comment]
不具合の混入時期から、ver2.0(Unicode版)では一度も動いたことのないコマンドラインオプションです。

いちおう #1363 で修正方法は提示していますが、`直すんじゃなくて機能削除`でもいいのかなぁ、と思っています。

どうしたいです？

ご意見を募りたいと思っています。

**Comment by k-takata** [comment]
> いちおう #1363 で修正方法は提示していますが、

どのコミットがこれに当たるのかが分かりませんでした。

で、-WQ が何のために用意されていたかというと、ヘルプによると、

> -WQ 通常は使用しません(SakuExtとの連動専用)

SakuExt が何かというと、
https://sourceforge.net/p/sakura-editor/wiki/ExtTools/
> インストーラパッケージに含まれる拡張子関連付けツールです．
サクラエディタ用に特化していますが，コマンドラインベースで汎用の拡張子関連付けツールとしても利用可能．

インストーラーがあるので誰も使ってなさそう。

`-WQ` の自体はマクロで代用可能と思われる。
```
sakura.exe -M="ExitAll()" -MTYPE=js
```

**Comment by berryzplus** [comment]
> > いちおう #1363 で修正方法は提示していますが、
> 
> どのコミットがこれに当たるのかが分かりませんでした。

rebaseして整理したときに削ってしまっていました。
ここ https://github.com/sakura-editor/sakura/pull/1363#issuecomment-672667798 に書いてる通り `getInstanceを削るだけの修正` で、直ると言えば直ります。

|-|記述|コメント|
|--|--|--|
|変更前|`CFileNameManager::getInstance()->GetIniFileNameDirect`|マージ時の誤記と思われる。|
|変更後|`CFileNameManager::GetIniFileNameDirect`|staticメソッドを呼ぶ。|

個人的には、いままで使えてなかったなら直さなくても良くね？に傾きかけています。

----

ちなみにサクラエディタインストーラーの拡張子関連付けは、無条件で UAC 制御化のシステムレジストリ領域に書き込む旧い仕様なので、どこかでユーザー権限インストールのあるべき姿を検討して反映してやる必要がありそうです。

タイプ別一覧に内臓されてる拡張子関連付け機構はユーザーレジストリにも対応してた気がするんですが、こちらは UAC 権限昇格に対応しとらんのでそれはそれで改善の余地があるはずっす。
