### ISSUE TITLE
appveyor でサイレントインストールのテストを行う

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#139]
appveyor でサイレントインストールのテストをしたい
http://www.jrsoftware.org/ishelp/index.php?topic=setupcmdline

**Comment by berryzplus** [comment]
「appveyorで」なので閉じておきます。

このissueはAppveyor対応の残課題です。
#1809 でAppveyorを廃止する提案をあげています。
提案は「CIで」に置き換え可能と思います。
→Appveyorでの対応を提案するこのissueは混乱を招きそうです。
