### ISSUE TITLE
未解決のissueが多過ぎる(気がする...)

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1394]
## 問題内容

未解決の issue が多過ぎる気がします。
[<img alt="image" src="https://user-images.githubusercontent.com/3253151/92403079-b1806d80-f16b-11ea-83dd-ca16cee19741.png" width="600" />](https://user-images.githubusercontent.com/3253151/92403079-b1806d80-f16b-11ea-83dd-ca16cee19741.png)

どれくらい貯めといていいものか知らんですが、200件オーバーは多いと思います。

未解決 issue が多いことによる弊害は以下のように考えています。
1. 新しい issue を追加しづらい。（精神的に）
1. 新しい issue を追加しても解決されないのではないか？という疑念を与えてしまう。
1. 未解決 issue が多い（≒バグが多い）でイメージが良くない。

対策のところに書いたリンクをたどれば、どんな未解決 issue があるかはすぐに確認できるのですが、ぼくが認識する限りだと解決済みなのに未解決のまま残っているものが結構ありそうです。

というわけで、ちょっと腰を入れて未解決 issue 潰しをしてみようかと思って issue 立てることにしました。
（stale pull request の整理は勝手にやっちゃったんですけどね :smile: ）

## 問題のカテゴリ

- その他の問題

## 対策
[wiki](https://github.com/sakura-editor/sakura/wiki) に貼られてる [全然更新されていないチケット](https://github.com/sakura-editor/sakura/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-asc) の クエリ を活用して、解決済み issue を片っ端から閉じてしまいます。

## 対策目標
目標は 81 件以下です。

ただの 81 件ではないです。
issue内容を9つ以内のカテゴリに分類し、カテゴリごとに9件以内に収める、の 81 件です。
（「9」は「7プラスマイナス2の法則」から来ていますが、原典は読んどらんです・・・。）

たぶんまぁ、理論的に体系付けられた対処は難しいと思うので、
ざっくりと 100 件未満 をクリアできたら OK なんじゃないかと思っています。

## 対応期限
未解決 issue が多い、という issue が「未解決で残る」と悲しいので、期限を切っておきたいと思います。
仮に 2020/09/30 時点で未解決だった場合、目標を達成できてなくても閉じることにします。

**Comment by beru** [comment]
問題無いと思います。もし特定の Issue が閉じられるのが問題だと感じる人がいればその人が再度 Open して何らかの対処をすれば良いだけの話なので。

**Comment by berryzplus** [comment]
作業始めてみましたが、なかなか減らない...orz

**Comment by berryzplus** [comment]
これ以上は無理、というところまで作業してみました。

現時点で残数 `191` です。

簡単な PR で解決できそうなものが数件あったので、継続して対応していきたいと思います。

**Comment by beru** [comment]
ちなみに下記のプロジェクトは Issues が現時点で 3.8k もあります。

https://github.com/tensorflow/tensorflow

これだけ数が多いと、自分が抱えている問題が既に報告されていないか検索して探そうとしてもヒットする候補が多すぎて分かり難いです。。検索スキルが低かったり母国語が英語でないからというのも理由としてあると思いますが…。

**Comment by berryzplus** [comment]
> ちなみに下記のプロジェクトは Issues が現時点で 3.8k もあります。
> 
> https://github.com/tensorflow/tensorflow
> 
> これだけ数が多いと、自分が抱えている問題が既に報告されていないか検索して探そうとしてもヒットする候補が多すぎて分かり難いです。。検索スキルが低かったり母国語が英語でないからというのも理由としてあると思いますが…。

tensorflowって確か、GitHubで最も活発なプロジェクトですよね・・・。
これは機械学習のためのライブラリらしくてかなり特殊です。

* サクラエディタと異なり、あらゆるOSに対応している。
  * サクラエディタは windows 7 以降のみの対応です。
* サクラエディタと異なり、あらゆるCPUに対応している。
  * サクラエディタは x86 と x86_64 のみの対応です。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394

**Comment by beru** [comment]
> tensorflowって確か、GitHubで最も活発なプロジェクトですよね・・・。
> これは機械学習のためのライブラリらしくてかなり特殊です。

vscode のプロジェクトは Issues の数が 5k+ でもっと多い事を確認しました。

https://github.com/microsoft/vscode

Open と Closed の 比率を見ると Closed の比率がかなり高いので、放置状態の Issue はどんどん Close してしまうのが自然なのかもしれないですね。
