### ISSUE TITLE
OSDN転載: 不具合：アウトライン解析のエンバグ

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#1404]
https://ja.osdn.net/projects/sakura-editor/forums/34071/42977/ からの転載です。

> サクラエディタのver2.3.2.0以降のアウトライン解析では、出力形式が「ツリー表示」になっているもの(「WZ階層付きテキスト」など)は、すべてのツリーがたたまれた状態で表示され、最後のトップレベルのタイトル項目が選択された状態になってしまいます。
そのため、アウトライン解析の結果から現在のカーソル行がどのタイトルに含まれているかを知ることができません。

> ver2.3.1.0以前では、現在のカーソル行位置の直近のタイトル項目が選択されて、ツリーがその項目まで展開されて表示されていました。

> アウトライン解析で出力形式が「リスト表示」になっているもの(「C/C++」など)であれば、ver2.3.1.0以前と同じく現在のカーソル行近くのタイトル項目が選択された状態になります。

> アウトライン解析系のプラグイン(Javascriptアウトラインなど)でも同様な動きなので、ツリー表示に関する不具合の混入ではないかと思われます。
> もしも、仕様変更であればすみませんが、アウトライン解析を利用したファイル内でのジャンプはよく利用していたので非常に不便に思っており、これが理由でいまだにver2.3.1.0を使用しています。

**Comment by berryzplus** [comment]
これ、言ってる意味が分からなくて OSDN にもコメントしたんですけど、
アウトライン解析の選択行追従 #1398 で直っていたりするんですかね？　＞　@suconbu さん

**Comment by suconbu** [comment]
@berryzplus さん

まず指摘現象を確認すべく ver2.3.1.0 と ver2.3.2.0 それぞれで動きを見てみましたが、
どちらもカーソル行があるノードまで展開されるという同じ挙動をしていて違いを見つけることができませんでした。
発生有無がデータに依存するんでしょうかね……？

#1398 では追従時にツリーの展開状態を維持する動作としました (https://github.com/sakura-editor/sakura/pull/1398#issuecomment-691489997) ので、もし指摘に書かれている現象が発生していたとしてもこの PR では改善されないのかなと思いました。

**Comment by beru** [comment]
お、それじゃあ既に修正済みだったんですね。
ご指摘ありがとうございます。
