### ISSUE TITLE
サクラエディタのコマンドライン引数でファイル名がMAXPATH超に長すぎるとうんともすんとも言わずに落ちて消える

### ISSUE THREAD

**Issue by usagisita** [sakura-editor/sakura#1406]
## 問題内容

超長い引数のファイル名を指定して実行すると、あら不思議、何も表示されないし、何も起きません。
いや、そんな機会ないだろう、といえばまあそうなのですが、一応何も起きないのはどうかと思います。

## 再現手順
sakura.exe "超長いファイル名(省略するよ).txt"

## 再現頻度

100%、いつもそう。

## 問題のカテゴリ

- プログラムの動作上の問題
  - 正式リリース版

## 環境情報
- OS バージョン Windows 8.1 64bit 日本語

- サクラエディタバージョン 2.4.1.0くらい

- PC情報

## スクリーンショット

画面には、特に何も表示されません。

**Comment by usagisita** [comment]
CCommandLine::ParseCommandLineの問題です。
WCHAR	szPath[_MAX_PATH]; なのが根本原因ですがパスが扱えないのはいいんです。
「MAX_PATH以上長いファイルは開けない」と警告されるパターンやメッセージリソースもあるので、中途半端です。
""で囲まれていないファイル名の場合は、
https://github.com/sakura-editor/sakura/blob/d884ae4d3539382ea3963e4c24b79ba0197c9c0c/sakura_core/_main/CCommandLine.cpp#L253
ここのループで、_countof(szPath)されているので、おそらく大丈夫っぽいです。
問題は""で囲まれたタイプで、
https://github.com/sakura-editor/sakura/blob/d884ae4d3539382ea3963e4c24b79ba0197c9c0c/sakura_core/_main/CCommandLine.cpp#L305
https://github.com/sakura-editor/sakura/blob/d884ae4d3539382ea3963e4c24b79ba0197c9c0c/sakura_core/_main/CCommandLine.cpp#L312
この2箇所が現在は _s 系なので、残念ながら即死亡します。

**Comment by berryzplus** [comment]
これ、どうしたいです？

> この2箇所が現在は _s 系なので、残念ながら即死亡します。

その言い方だと `wcscpy_s` を辞めて `wcscpy` にしたらみんなハッピーってことになっちゃうんですが、違うはずです。

即時終了するのは `_s系` を使うメリットです。
もし  `wcscpy_s` を辞めて `wcscpy` にすると、バッファオーバーランに気付くことができず、状況により落ちたり落ちなかったりする怪しげなバグに悩まされる結果になると思います。

**Comment by usagisita** [comment]
当たり前ですが、別にwcscpyにしろという意味ではないです。
バッファに入りきらないときは、エラーメッセージを通知して、長いパスは無効として無視して、サクラエディタが正常起動してほしいです。
ちょっと作業してみましたが、パス解釈の仕様が難解で、あとエラーメッセージ出すにもコマンドラインは最大32,767文字らしいので、大量の長すぎるパスが指定されていると、エラーメッセージが何回も出て非常にうっとうしいということが分かったりして、どうしようか困っています。32767/260=126回でしょうか。
CreateProcessW function lpCommandLine
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw

それから＞ for( i = 0; i < _countof( szPath ); ++i ){　ここですが配列ならこれでいいけれど文字列なので、はみ出すときはNUL終端できてないようで、これはこれで問題ありみたいです。

**Comment by berryzplus** [comment]
どこが問題ってことにしますか？

と聞いたほうがよいのかな？

* バッファが小さいこと（小さいのか？）
* 長いパスが指定されることを考慮してないこと
* 想定外時に何もメッセージが出ないこと
* 想定外時に終了すること（エラー時に終了したらいかんのか？）

個人的には、長いパスが指定されることを考慮にいれてメッセージを出して終了させるようにしたらスマートに実装できると思います。

**Comment by berryzplus** [comment]
> バッファに入りきらないときは、エラーメッセージを通知して、長いパスは無効として無視して、サクラエディタが正常起動してほしいです。

こういうことができるか検討・・・

> sakura.exe 「オプション」「長すぎるパス」

メッセージ表示：長すぎるパス

「長すぎるパス」を除外したコマンドラインを作り再起動。自身は終了。

> sakura.exe 「オプション」

これなら問題なく起動できる・・・はず。
