### ISSUE TITLE
VMessageBoxFのバッファ長

### ISSUE THREAD

**Issue by usagisita** [sakura-editor/sakura#1416]
## 問題内容

マクロのテストしていて思ったのですが、ダイアログに表示するエラーメッセージが16000文字は多すぎると思います。
なんか前にも、書いたような気がするんですが、ちょっとよく分からないので、聞いてみます。

## 再現手順

関数 VMessageBoxF()
https://github.com/sakura-editor/sakura/blob/b1fc7a546aac0625526e6c795dd5211db916371a/sakura_core/util/MessageBoxF.cpp#L99
普段使いの範囲とくにInfoMessageなどのメッセージ表示で、頑張って16000文字も画面に表示する必要性ってあるんだろうか……と思いまして。
実際にマクロのエラー表示経由で16000文字を表示してみると、メッセージボックスの描画または計算に、うちでは5秒以上10秒近くかかることがあります。ちょっとハングアップしたのかと思いました。
ちなみに、はみ出した分は、切り捨てられるので、落ちることはないようです。

VMessageBoxFの場合は、将来のロングファイル名*2+200文字+余裕分で倍にするぐらいあれば、十分じゃないかなと思います。ファイル名が2,000文字までにするなら、4,400ですね。
NTFSのファイル名の長さって最大は……えっっと 32,767 ですね。逆に足りないなんて....。どうしましょうか？

目視で見えなくても、Ctrl+Cでコピーできるから有用だという、意見もあると思います。
しかしマクロのInfoMsg系ではソースのInfoMessage(ややこしい)ではなくMessageBoxという名のWrap_MessageBoxを使っていて、このような制限を受けないので、大丈夫そうです。

けち臭い話をすると、VMessageBoxFの処理をたどりWrap_MessageBoxのstd::wstringで再度コピーされて文字別倍ドンなんですね。

```js
// sakura_macro_VMessageF.js
var msg = '';
for(i = 0; i < 160*2; i++){
	// スペースなし50文字
	msg += 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
}
msg += '\n[END]●●●●●●●●●★';
// InfoMessage→VMessageF→Wrap_MessageBox
InsFile('\nInsFile 1\n' + msg);
// Wrap_MessageBox
InfoMsg('\nInfoMsg 2\n' + msg);
msg = '';
for(i = 0; i < 160*2; i++){
	// スペースあり50文字
	msg += 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa '; 
}
msg += '\n[END]●●●●●●●●●★';
InfoMsg('\nInfoMsg 3\n' + msg);
msg = '';
for(i = 0; i < 4400; i++){
	msg += 'a'; 
}
msg += '\n[END]●●●●●●●●●★';
InfoMsg('\nInfoMsg 4\n' + msg);
```
1つめはInsFileです。誤記じゃないです。

メッセージボックス
>file open error [
InsFile 1
aaaaaaaaaaaaaa .......(16000文字続く)......aaaaaaaaa

というふうに16000文字で切れて表示されます。表示まで遅いです。

>InfoMsg 2
aaaaaaaaaaaaaa .......(16000文字続く)......aaaaaaaaa
>[END]●●●●●●●●●●

Ctrl+Cによると16000文字を超えても最後まで表示、コピーできます。表示まで遅いです。

>InfoMsg 3
aaaaaaaaaaaaaa .......(途中スペースあり、16000文字続く)......aaaaaaaaa
>[END]●●●●●●●●●●

しかしaaaaaaの50文字目ごとを1スペースに置換したものは、1秒もかからないで表示できます。

>InfoMsg 4
>aaaaaaaaaaaaaa .......(途中スペースなし、4400文字続く)......aaaaaaaaa
>[END]●●●●●●●●●●

4400文字なら、こちらの環境なら1秒程度で表示可能でした。
FullHDの120%で画面には入りきっています。
上限にはマシンスペック差が多分にあるとは思います。

## 再現頻度

当方の環境では、100%
環境依存していそう

## 問題のカテゴリ

- 仕様の問題
- プログラムの動作上の問題

## 環境情報
- OS バージョン Windows.8.1

- サクラエディタバージョン (Dev version) 2.4.2.0

- PC情報

うちではintel core i7 のHDGraphicsです。もっと高級グラボや、Win10では違うかもしれません。

**Comment by usagisita** [comment]
ぎゃあタイトルを誤記してしまいました。正しくはVMessageFです。コピペすればよかったです。

**Comment by k-takata** [comment]
タイトルは、タイトルの右横の `Edit` ボタンから編集可能です。

> 将来のロングファイル名

話の本筋とは全然関係ないのですが、`MAX_PATH` 文字扱えるのがロングファイル名で、それよりも長いパス名はロングファイル名ではなくロングパス名です。ロングパス名になっても、ディレクトリ内の個々のファイル名は 255 文字が最大です。

**Comment by usagisita** [comment]
Editボタン確かにありますね。
用語は統一して書かないと混乱してくるから、そういう指摘は助かります。
ありがとうございます。
ロングパス名、ロングパス名、ロングパス名……

**Comment by berryzplus** [comment]
> マクロのテストしていて思ったのですが、ダイアログに表示するエラーメッセージが16000文字は多すぎると思います。
> なんか前にも、書いたような気がするんですが、ちょっとよく分からないので、聞いてみます。

根拠は知らないです。

8000の2倍じゃね？と思いますが、それはそれで `なんでやねん！` です。

個人的には「動的確保（≒確保失敗時はなんも出ない）で十分」だと思っております。

**Comment by usagisita** [comment]
動的確保でももちろんいいと思います。
今のコードは厳密にいうならスレッドセーフでもないですし。
ただし、行メモリとかのメモリー確保エラーのメッセージ出したいなら、やっぱり事前に確保していると安心感はあります。
気にしてるのは、上限のメモリではなく、描写文字数と描写計算の処理時間のほうなんです。
何が起こるか分からない待ち時間は正直、辛いものがあります。

**Comment by berryzplus** [comment]
> 気にしてるのは、上限のメモリではなく、描写文字数と描写計算の処理時間のほうなんです。

本文にあったマクロをパフォーマンスプロファイラにかけてみた感じ、サクラエディタの本体コードが原因で速度低下しているわけではなさそうな感じ（≒サクラエディタの本体コード以外、つまり C Runtime Library で時間がかかっている？）でした。
[sakura_macro_VMessageF.zip](https://github.com/sakura-editor/sakura/files/5293844/sakura_macro_VMessageF.zip)

確保文字列長が長いことにより発生する速度低下要因は、いくつかあると思います。

1. sprintf の フォーマット文字列 は1文字ずつ解析されるので長いと時間がかかるっす。
1. tchar_vsnprintf_s の フォーマット文字列解析 は標準よりも遅いっす。
1. Wrap_MessageBox 内で行っている std::wstring() のコピーが無駄っす。

まとめて対処しようとすると結構複雑になって、理解が難しくなる(#1351)っす。

個々の問題の対策をしていく感じなら、そんなに難しい修正にはならないと思います。

**Comment by usagisita** [comment]
Info3のメッセージ説明、蟻→あり
Info4のメッセージ説明、蟻→なし
の誤記だけなおしました。誤解を与えていたらすみません。

追加の新しいテスト用マクロ
```JavaScript
var msg = '';
for(i = 0; i < 160*2; i++){
	// スペースあり50文字
	msg += 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa ';  // ←ここにスペースがある
}
msg += '\n[END]●●●●●●●●●★';
InsFile('\nInsFile 5\n' + msg); // 追加
```
InsFile 1 とInfoMsg 2 だけだとよく分からないなら、このInsFile 5を実行してみると、よりはっきりしてきます。
これはInfoMsg3と同じデータで、スペース区切りです。これでInsFileを実行するとすぐ表示されます。
すなわち、犯人はVMessageBoxFでのsprintfとtchar_vsnprintf_sではありません。多少は遅いかもしれませんが、ループではなく1回実行されるだけでは感じられるほど遅くはないでしょう。
InfoMsg 3を見れば、約1秒で表示されました。ということで文字列の内容が関係ないWrap_MessageBoxの処理も犯人ではないということです。
sprintfやtchar_vsnprintf_sの%sでの文字列、std::wstring(str)としてコピーした時に、文字列の内容によって速度差が出ることがあるでしょうか。
フォーマット書式によって差がある可能性はないとはいいませんが、今回はInsFile1と5では同じ書式です。

| 名前| 関数 |空白文字|文字数|時間|
| ------------- | ------------- |------------- |------------- |------------- |
| InsFile 1  | VMessageBoxF  |なし|16000|10秒|
| InfoMsg 2 |  Wrap_MessageBox |なし|16000|10秒|
| InfoMsg 3 | Wrap_MessageBox  |あり|16000|1秒|
| InfoMsg 4 | Wrap_MessageBox  |なし|4000|1秒ちょっと|
| InsFile 5 | VMessageBoxF  |あり|16000|1秒|

16000文字でも、空白文字があればWrap_MessageBoxもVMessageBoxFも遅くないです。
出力文字数は同じなので、CランタイムとかSTLとかアロケーターとかが原因ではないっぽいということになります。
推定される遅い犯人は、グラフィックドライバとかDirectWriteだかGDIだかメッセージボックス内部の実装です。
どうしてもこれでテストが足りないなら、直接::MessageBoxの本体に16000個の「aaaa」と、それに50個に1個をスペースに置き換えた文字列を直接指定して比較、計測することくらいでしょうか。
OS側が遅いとなるとできることは、最大文字数を減らすくらいしかない(もしくは勝手に改行や空白を途中に入れるとかの)微妙な修正しかなさそうな感じ、ということになります。

というのが、僕の推測です。
それで最初に戻って、16000文字を4000か5000文字ぐらいに減らしたらどうでしょうか、という提案になります。
どうでしょう。

**Comment by berryzplus** [comment]
う～む、言いたいことは分かってきたように思います。
最大文字数を小さい値に変更する、でいい気がしてきました。

気にしているのは 4000文字 の根拠が弱いことです。

> VMessageBoxFの場合は、将来のロングファイル名*2+200文字+余裕分で倍にするぐらいあれば、十分じゃないかなと思います。ファイル名が2,000文字までにするなら、4,400ですね。

この基準でいくと、4000文字＝1300 × 2 ＋ 200 ＋ 200ということになり、 
「ロングパス名の想定は1300文字まで」の根拠が不明です。
 
実施している測定内容を見た感想なんですが、
`user32.dll` の `MessageBoxEx` に問題があると確信してますよね？ :smile:

`MessageBoxEx` は、指定された言語のメッセージダイアログテンプレートを元に、 `渡された文字列を表示するのに適切なサイズ` のダイアログを表示する関数です。メッセージが一定文字数を超えるとダイアログ表示前のサイズ調整がうまく機能せず、ダイアログ表示後にサイズ合わせを行っているのではないか？（しかも表示し切れない文字数だから何度もリトライが入って無駄に時間がかかってしまうのではないか？）と考えると 16,000文字 を表示させようとしたときに異常な時間がかかる理由を説明できる気がします。50文字ごとに空白が含まれたときに速度が改善する理由もこれで説明できます。
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxexw

計測結果が 2点間比較（現在の値 16,000文字 と 4000文字 の 2点間比較）になっているんですが、パフォーマンス分析をしたい場合は3点以上を計測して傾向を見せたほうが伝わりやすいような気がします。たんに `time = N × chars` な一次式に基づく遷移なのか、ある値を超えたると爆発的に時間がかかるようになる遷移なのかで判断は分かれてきます。

ぼくの予測では後者で、4096文字あたりに壁があるんではないかと思っています。（試してないっす。）

**Comment by usagisita** [comment]
4000文字の根拠は確かに薄いですね。
実際、4000文字くらいならうちの画面には収まるし、だいたいのメッセージでほぼ切れないかな、くらいの感覚だけで話していたものなので。
計測点の話もたいへん参考になります。
さて腰が痛くなってきたけど、どうしたものか。

**Comment by usagisita** [comment]
```JavaScript
for(var loop = 0; loop <= 24; loop+=2){
	var msg = '';
	for(i = 0; i < loop*1000/50; i++){
		// スペースなし50文字
		msg += 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa';
	}
	msg += '\n[END]●●●●●●●●●★';
	InfoMsg('InfoMsg ' + loop*1000 + '\n' + msg);
}
```
文字数（固定分を除く)
InfoMsg 0文字 すぐ
InfoMsg 2000文字 すぐ
InfoMsg 4000文字 1秒未満
InfoMsg 6000文字 2秒
InfoMsg 8000文字 3秒
InfoMsg 10000文字 4秒はみ出し
InfoMsg 12000文字 6秒 はみ出し
InfoMsg 14000文字 8秒 はみ出し
InfoMsg 16000文字 10秒 はみ出し
InfoMsg 18000文字 12秒 はみ出し
InfoMsg 20000文字 16秒 はみ出し
InfoMsg 22000文字 20秒 はみ出し
InfoMsg 24000文字 23秒 はみ出し
時間は手計測なので誤差があります。何回か計測してだいたいの数値です。
だんだん増えるのがアルゴリズム上の問題なのかCPUが熱くなってクロックが下がっているとかの原因かは判断しにくいですが、増えていくのは本当のようです。
こんな感じになりました。ご一考くださいませ。

**Comment by berryzplus** [comment]
表示遅延の傾向は一次式的で、1秒未満で表示できる 4000文字 を変更後最大値の候補とする、で問題なさそうに思います。


> 時間は手計測なので誤差があります。何回か計測してだいたいの数値です。

ウインドウフックを使って表示が完了した直後にOKで閉じる改造をしてやれば計測可能かもです。
callwndprocret で WM_PAINT とかを捕まえて PostMessage してやれば・・・。
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowshookexw

必要なの？というところが気になるとこですが。
