### ISSUE TITLE
管理・運用向け掲示板の運用場所の検討

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#142]
管理・運用周りの伝達や話し合いをする場所を用意したいと考えています。

タイトルには「掲示板」と入れましたが、広義の掲示板という意味で捉えてください。良いソリューションがあればそれを採用します。

### 「ラベルを使いませんか? #70」より引用
@kobake
> 今後の「こういうラベル追加しました」みたいなちょっとした連絡はどこに書くのが適切ですかね。ラベル追加に限らずちょっとした連絡全般を書く場について。
> 
> いくつか案は出しておきますが、もっと良い案あればください。
> 
> (案1) 略
> (案2) Team Discussion で連絡する … Team 所属外の人に情報が見えないのは微妙。できる限り情報はオープンにしたい。
> (案3) OSDNフォーラムで連絡する … せっかく開発者コミュニケーションが GitHub に集約されつつあるのに OSDN 側に場を分散するのはちょっと嫌。
> (案4) Slack で連絡する … Slack 参加者以外に伝わらないのは微妙だが、一応誰でも参加できる場ではある。
> (案5) 諸連絡用のリポジトリを作って例外的にそこの Issues を連絡掲示板的用途として使う … あんまりそういうの見たことないですが。sakura リポジトリの Issues を汚すよりはマシ。
> (案X) 他、もっと良い案あればください。
> 
> ちなみにこれが「仕事」であれば僕は (案4) を採用します。

　

@KENCHjp
> Team Discussionは役割がかぶりますよねぇ。同じ理由でOSDNはもうエンドユーザとの情報交換にしぼったほうがいいきがしています（あっちの会議室の開発管理フォーラム消してもいいかなと、開発メンバーもOSDNにアカウント無い人もいますし）
> 通知って意味なら、Notificationsに表示される何かであればなんでも良い気がしてるのですが、そもそも未読を０にしない人もいるみたいだし。。。
> Issueはやっぱりそこに的があると当てたくなるのが性（サガ）なので、消したいですよね。
> うちの会社メンバー（仕事場がバラバラ）だと、チーム共通のグランドルール掲示板（ポータルRedmineだったり、客先だとExcelだったりします)でWhat's Newお知らせ＆MLへメール流すです。
> 
> 掲示板っていうとここだとWikiっすかね、Wikiページの更新をウォッチしてNotificationsとかに表示されるといいのかな。
> Issueって運用系ってあまり混ざらない方がいいのかなってのも同意です。

　

@kobake
> 一方的な告知であれば Wiki もアリですが、どちらかというと相互にコメントし合える場が欲しいですねぇ

　

@m-tmatma
> https://qiita.com/methane/items/78a90c6efb1a7c4da57d
> の記事では別のリポジトリを作って、フォーラムを
> 提供する方法を提案しています。
> (オリジナルは https://medium.com/@methane/why-you-must-not-ask-questions-on-github-issues-51d741d83fde)
> 
> あと、https://gitter.im/ も紹介しています。

　

@KENCHjp
> 情報交換専用リポジトリ作ってでIssueで通知でもいいかなぁなんて。
> 名前は、ryouzanpakuとかtoranoanaとかtreasureboxでもいいですが、べたにinformationっすかね。

　

@KageShiron
> Team Discussionは一般公開できないのか・・・

　

@kobake
> リポジトリでやるとしたら名前は
> information
> forum
> discussion
> あたりですかねぇ

## 現時点での提案
いろいろ考えましたが、「management-forum」という名前のリポジトリを作成し、そこの Issues を掲示板代わりに使うのはどうでしょうか。

- リポジトリ自体はオープンに運用するので誰でも閲覧可能・投稿可能
- @sakura-editor/sakura-developers チームを management-forum の Collaborator として追加することで、少なくとも @sakura-editor/sakura-developers の方々には自動的に通知が行くようになる
- 通知いらない人は Watch を手動で外してもらう
- @sakura-editor/sakura-developers チーム外の人で内容をウォッチしたい人は手動で Watch を付けてもらう
- 重要伝達事項については明示的に @sakura-editor/sakura-developers メンションを付けて発言することで、Watch 外しているコアメンバーに対しても通知を飛ばすこともできる（ただし濫用は控える）

**Comment by KENCHjp** [comment]
いいと思います（ああ、梁山泊とか虎の穴とかボケなきゃよかった^^;;;;;;)

**Comment by kobake** [comment]
異論なさそうであれば明日くらいの判断を目途に「management-forum」リポジトリ作っちゃいます

**Comment by kobake** [comment]
みなさんリアクションありがとうございます。
今からフォーラム用リポジトリ作っちゃいます！

**Comment by kobake** [comment]
フォーラム用リポジトリ作りました！
https://github.com/sakura-editor/management-forum/

今後はこの management-forum の Issues を管理・運用関連の掲示板として活用することにしましょう。
