### ISSUE TITLE
Grepダイアログ部品配置の改善提案

### ISSUE THREAD

**Issue by suconbu** [sakura-editor/sakura#1426]
# 不便に感じていること

Grep ダイアログを使う際、変更したい設定の部品がある場所を探してしまう時がちょくちょくあります。(あれ、正規表現どこだっけ……など)
Grep は比較的よく使う機能だと考えているので、できるだけそんな操作上のロスをなくせればいいなと思い Issue をたてました。
https://github.com/sakura-editor/sakura/issues/1248 と共通する点ありそうです。

# 提案内容

今ある部品はそのまま残しつつも、置き場所を工夫することで上に書いた不便は解消できると考え、

* 関連する部品同士は近い場所に集める
* 使用頻度の高そうなものほど上に方に配置

という方針で配置を検討してみました。

## 現状 (v2.4.2.0)

![image](https://user-images.githubusercontent.com/11252784/95883931-74387c80-0db6-11eb-8a8d-a3c7c8b08264.png)

## 配置改善案

![image](https://user-images.githubusercontent.com/11252784/95883951-7bf82100-0db6-11eb-9a84-8fe098efd025.png)

ご意見頂ければと思います。よろしくお願いします。

**Comment by arigayas** [comment]
似た機能を集めるという配置換えするだけでも使い勝手は向上するので良いと思います！

**Comment by berryzplus** [comment]
コメントしづらいっすね :smiley:

GrepとGrep置換、Grepと検索はダイアログの項目が似通っているので、Grepで位置を変えるなら他のダイアログにも同様の変更をしていくべきだと思います。（興味がないのでやるのはGrpだけっす、は正しいと思うので一緒にやるべき、とは言いません。）

**Comment by beru** [comment]
新しいレイアウトの方がよさそうに見えますね。

ウィンドウの横方向のリサイズがなんとなく出来ても良さそうな印象を受けますね。

検索対象ファイルの設定で複数のファイルやフォルダを指定する際に1行の入力箇所で指定するの大変なので、Windows10の環境変数のPathの設定時のような画面で編集が出来るといいなと思います。

**Comment by suconbu** [comment]
コメントありがとうございます。

> Grepで位置を変えるなら他のダイアログにも同様の変更をしていくべき

Grep 置換ダイアログについては Grep とほぼ同じ配置をしていることから、Grep を変更する際は一緒にやった方がいいと思っています。
一方で、検索や置換については現状でもよく使いそうなものはまとまって配置されているので、「Grep と統一感なく使いづらい」のような要望が出たらその時に検討、でも良さそうな気がしました。

> 検索対象ファイルの設定で複数のファイルやフォルダを指定する際に1行の入力箇所で指定するの大変

そうですね、物理的に小さなディスプレイで作業している際はかなりつらいので専用の編集画面があるとありがたいと思います。

**Comment by suconbu** [comment]
使いづらいなと思っているのはもしや自分だけ？と不安なところありましたが、
配置変更についてポジティブなご意見を頂けたのでちょっと試作してみます。

ちなみに、皆さんダイアログリソース編集時は GUI エディタではなくテキスト編集でやられているんでしょうか。
*.rc ファイルの内容からするとおそらくそうなのかなと思いますが、サクラエディタにおける標準的？な方法があれば知っておきたいと思いました。

**Comment by beru** [comment]
> ちなみに、皆さんダイアログリソース編集時は GUI エディタではなくテキスト編集でやられているんでしょうか。

自分はそうしてます。編集後の配置の確認ではリソースエディタで見たり実行して確認したりです。
比較的効率は悪いですが、たまにしか変更しないのであまり気にはしてないです。

**Comment by suconbu** [comment]
> 自分はそうしてます。編集後の配置の確認ではリソースエディタで見たり実行して確認したりです。
> 比較的効率は悪いですが、たまにしか変更しないのであまり気にはしてないです。

なるほど。配置をたくさん変更する時は手間がかかりそうですね。
今回は別ファイルでリソースエディタ編集したものから必要な部分だけ元ファイルにマージする方法でやってみます。

**Comment by berryzplus** [comment]
> ちなみに、皆さんダイアログリソース編集時は GUI エディタではなくテキスト編集でやられているんでしょうか。

ほぼ誰もやってないので「標準などない！」が実情である認識っす。

> *.rc ファイルの内容からするとおそらくそうなのかなと思いますが、サクラエディタにおける標準的？な方法があれば知っておきたいと思いました。

こうなってるのは歴史的経緯（途中で英語DLL組み込んだから）かと思っています。

個人的には、直接リソースエディタで編集できるように、リソースエディタで認識できない手書きリソースを rc2 に分離したいと思っています。（GitHubに移る前からずっと言ってるんですが :smiley:

**Comment by suconbu** [comment]
> リソースエディタで認識できない手書きリソースを rc2 に分離

これはやりがいありそうですね。
ダイアログリソースの "ＭＳ Ｐゴシック" -> "Yu Gothic UI" 化と合わせて別途取り組んでみたい課題です。

**Comment by suconbu** [comment]
https://github.com/sakura-editor/sakura/pull/1431 にサンプルを作成しました。

変更点は以下です。
1. 全体的な配置変更
2. 「検索」ボタンの高さを他より少し大きく (通常押すボタンを目立たせる、的を大きくする)
3. 検索場所を「編集中ファイル」か「フォルダ」でラジオボタン式に
4. ラベル文言を一部短縮 (配置の都合により)
5. 「条件」に関連するチェックボックス群 (単語単位, ...) の並びを検索ダイアログを同じに

サンプルで気になるかもしれないと感じた点です。
* 大きい
* 「2」に関してボタンの高さが統一されいないのは賛否ありそう
* 「検索場所」付近のアクセラレータキーがやや直感的でない

![image](https://user-images.githubusercontent.com/11252784/96326948-fef7d080-106f-11eb-80c9-e37692d43dc6.png)

**Comment by beru** [comment]
上のスクリーンショットを見て思った点を書きます。

- ダイアログのマージンが少しだけ大きい気がしました。
- 検索、キャンセル、ヘルプ、の３つのボタンの横幅はもっと狭くても良い気がします。
- ラベルの横幅は、今の日本語表示の場合はもっと詰めても切れない気がします。
- エディトの左側に位置するラベルの位置が少し上寄りになっているように見えます。

文章で書いてもイメージが湧きづらいかもしれないので、実際にこちらで調整して確認した上で画面のスクリーンショットを載せるべきかもしれないですね…。

**Comment by suconbu** [comment]
各部の余白は全体的にもう少し詰められそうですね。詰めれば横方向をもう少しコンパクトにできそうです。

**Comment by arigayas** [comment]
英語版を使ってませんが、英語を当てはめても大丈夫なのか？気になりました。

**Comment by beru** [comment]
[日本語版のリソースファイル](https://github.com/sakura-editor/sakura/blob/c8dc738a9ff699ae722556581e80e01feb94313d/sakura_core/sakura_rc.rc) と [英語版のリソースファイル](https://github.com/sakura-editor/sakura/blob/c8dc738a9ff699ae722556581e80e01feb94313d/sakura_lang_en_US/sakura_lang_rc.rc) は別れているので配置の調整は個別に出来るので大丈夫じゃないかと思います。別の見方をすれば個別に調整する必要があるのでその分の手間は必要です。

あと英語版の優先度は低いと思うので必ずしも同時に対応する必要は無いと個人的に思います。

**Comment by arigayas** [comment]
> [日本語版のリソースファイル](https://github.com/sakura-editor/sakura/blob/c8dc738a9ff699ae722556581e80e01feb94313d/sakura_core/sakura_rc.rc) と [英語版のリソースファイル](https://github.com/sakura-editor/sakura/blob/c8dc738a9ff699ae722556581e80e01feb94313d/sakura_lang_en_US/sakura_lang_rc.rc) は別れているので配置の調整は個別に出来るので大丈夫じゃないかと思います。別の見方をすれば個別に調整する必要があるのでその分の手間は必要です。
> 
> あと英語版の優先度は低いと思うので必ずしも同時に対応する必要は無いと個人的に思います。

英語版はどのみち日本語版が出来たら再度作ることになっているという事で理解しました。
そのうち[中国語版](https://github.com/sakura-editor/sakura/issues/1369)もどなたかが作る事になるんでしょうか。

**Comment by suconbu** [comment]
英語など言語によっては日本語より横に伸びるものもありますので、多言語対応される時の作業性を考えるとあまりギチギチにはしない方がよさそうですね。中国語は日本語より多分全体的に短くなると思うので大丈夫そうですが。

今のところ、今回の改善では GREP と GREP 置換 の日/英それぞれの都合 4 つを対応するつもりでおります。

**Comment by suconbu** [comment]
変更前からですけれど、コンボボックスと他の部品とで縦位置ズレ＋ディスプレイ設定の表示スケールを変えた時の大きさズレが出てしまうようです。
気持ち悪いですが、ダイアログリソースの編集ではどうにもなりそうにないため今回これは放置します……

100% | 150% | 200%
-|-|-
![image](https://user-images.githubusercontent.com/11252784/96366547-386d3080-1183-11eb-99db-c3e3966ed3b0.png) | ![image](https://user-images.githubusercontent.com/11252784/96366558-3c994e00-1183-11eb-9175-3897966a2108.png) | ![image](https://user-images.githubusercontent.com/11252784/96366560-3efba800-1183-11eb-8871-ffa00e3e8379.png)

**Comment by suconbu** [comment]
このあたりの資料も参考にしながら配置作業を進めています。
すべて準拠するのは到底無理な気がするので有用そうな点を摘まみつつ……。
https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-layout

https://github.com/sakura-editor/sakura/pull/1400 でコンボボックスだけ違うフォントが使つようにしたことにより配置の面倒さが向上しています。 (自業自得)

**Comment by suconbu** [comment]
> 今のところ、今回の改善では GREP と GREP 置換 の日/英それぞれの都合 4 つを対応するつもりでおります。

ほぼ仕上がりました。もう少し確認してみておかしな所なければ正式 PR します。

主な変更点：
* チェックボックスを縦並びに (ガイドライン参考、言語違いでの配置を共通化しやすく)
* 英語版の IDD_GREP, IDD_GREP_REPLACE の配置変更/ラベル文言調整
* 英語版のフォントを Segoe UI に (いずれは他の英語版のダイアログも……)

### 表示スケール: 100%
言語 | IDD_GREP | IDD_GREP_REPLACE
-|-|-
日本語 | ![image](https://user-images.githubusercontent.com/11252784/97085480-a8365c00-1658-11eb-97ad-edf422edd690.png) | ![image](https://user-images.githubusercontent.com/11252784/97085485-abc9e300-1658-11eb-9b17-88f2e7932ab8.png)
英語 | ![image](https://user-images.githubusercontent.com/11252784/97085491-b3898780-1658-11eb-9944-8e64177bada0.png) | ![image](https://user-images.githubusercontent.com/11252784/97085493-b5ebe180-1658-11eb-95c1-8e23ff89a5a9.png)

### 表示スケール: 200%
言語 | IDD_GREP | IDD_GREP_REPLACE
-|-|-
日本語 | ![image](https://user-images.githubusercontent.com/11252784/97085501-c8feb180-1658-11eb-80e6-af9548896fd1.png) | ![image](https://user-images.githubusercontent.com/11252784/97085502-cac87500-1658-11eb-89eb-2885f696891d.png)
英語 | ![image](https://user-images.githubusercontent.com/11252784/97085505-cd2acf00-1658-11eb-8dd2-ba42af6ba942.png) | ![image](https://user-images.githubusercontent.com/11252784/97085509-cef49280-1658-11eb-90e4-88b722bf8afa.png)

**Comment by suconbu** [comment]
https://github.com/sakura-editor/sakura/pull/1431 をマージしましたので本 Issue はクローズします。
