### ISSUE TITLE
チャット運用場所の検討

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#143]
掲示板や Issues 等よりもカジュアルに話をする場としてチャット運用を行うことを考えています、というか既に Slack 運用済みなのですが、Slack の性質が（自動招待機能は入れてあるとはいえ）クローズドなので、もう少しオープンなチャットツールに移行したい気持ちがあります。

## 選択肢
- [Slack](https://sakura-editor-slack.herokuapp.com) … これまではここを本運用としていた。それなりに活用されているがまだ参加人数は少ない。
- [Discord](https://discord.gg/MTWB4ut) … 実験運用中。使い勝手は Slack とほぼ変わらず、入室ハードルが低い。
- [Gitter](https://gitter.im/) … kobake のほうで個人的に触ってみた感じとしてはインターフェースが特殊。（個人の感想です）

## 前提
- 必ず参加しなければならないわけではない（チャットで話した内容が全体に周知されるとは考えないこと）
- 開発者・一般ユーザ問わず参加できること

### 「ラベルを使いませんか? #70」より引用
@k-takata
> > Slackって後から参加しても過去にさかのぼれるでしたっけ。

> 無料だと遡れる期間だか件数だかに制限があります。

　

@kobake
> Discord も良さそうです。Slack ライクなインターフェースのオープンなチャット場。
> ↓は試しに作ってみたサクラエディタチャンネルです。
> https://discord.gg/MTWB4ut
> 名前だけ入力すれば即入室可能。追加でメールアドレスとパスワードを登録するとスマホアプリからも操作可能。Slack よりも参入ハードル低そう。
> 
> ログは無期限保存の模様。情報源は reddit ですが。
> https://www.reddit.com/r/discordapp/comments/6vu7mz/for_how_long_are_chat_logs_saved/
> 
> Gitter はちょっと触ってみたのですが個人的には画面がゴチャゴチャしていて初見としてはちょっと抵抗ありました。慣れの問題だと思いますが。

　

@kobake
> 今話している本題ではないのですが、ちょっとしたつぶやきの場という意味でのチャットは運用続けていきたいと思っています（今は Slack ですが Discord のほうが良さそうであればそっちに引っ越しも検討）

　

@KENCHjp
> はい、この前はチャットで助かりましたのであったほうがうれしいです。

　

@KageShiron
> Slackはかなりクローズドなので、Discordの方がマシだとは思います。
> なんか、もっと簡単な(ROMや通りすがりの人にも優しい)チャットツールの選択肢はないものか・・・

## 現時点での提案
今の [Slack](https://sakura-editor-slack.herokuapp.com) を [Discord](https://discord.gg/MTWB4ut) に引っ越すのが良いかな、と思っています。どうでしょうか。

**Comment by KENCHjp** [comment]
運営に関する打ち合わせをオープンにする趣旨はいいかと思うのですが、
顧客（ユーザ）向けに見られたくないような（悪口を言うという意味ではなく、身内ネタというのでもなく）、オープンにしにくい情報をやりとりしたり、サプライズ的なやり取りをしたいってことはないでしょうかね？？？？
いや、そんなものはないんだ全部オープンに出来るんだってことなら、私はどちらでもついていきます。

**Comment by kobake** [comment]
あとDiscordではDMもありますね。KENCHさん宛てにメッセージ送ってみました

**Comment by KENCHjp** [comment]
@kobake さん了解です。後で確認します。

**Comment by kobake** [comment]
@sakura-editor/sakura-developers 
ほとんど独断ですみませんが、チャットツールは Slack から [Discord](https://discord.gg/MTWB4ut) へ移行することとさせてください 🙏 

異論があれば後からでも受け付けます。
しばらくは Slack 領域残しておくので、やっぱ Discord や～めた、っていう判断をあとからしちゃうことも可能といえば可能です。

ただ、いろいろ触ってみた感触としては Discord でぜんぜん問題ない（Slack よりも快適そう）な感じで、異論は出ないだろうと考え今回の結論としました。

完全に Discord がチャット主戦場になったと判断できたタイミングで Slack のほうはログのバックアップをとってどこかにアップロードした上で閉鎖しようと思います。

**Comment by kobake** [comment]
Slack リンクを Discord リンクに差し替える対応等はあとでやります！
