### ISSUE TITLE
テストをビルドするときに毎回googletestがビルドされる。

### ISSUE THREAD

**Issue by sanomari** [sakura-editor/sakura#1433]
## 問題内容

テストをビルドするときに毎回googletestがビルドされる。

## 再現手順

1. visual studioでsakura.slnを開きます。
1. ソリューションのビルドを実行します。（ビルドが実行されます。）  
`4 正常終了、0 失敗、0 更新不要、0 スキップ` と表示されます。
1. もう一度、ソリューションのビルドを実行します。（ビルドが実行されません。）
`0 正常終了、0 失敗、4 更新不要、0 スキップ` と表示されます。
1. テストプロジェクトのファイルをどれか更新します。
1. ソリューションのビルドを実行します。（ビルドが実行されます。）  
`1 正常終了、0 失敗、3 更新不要、0 スキップ` と表示されます。

## 再現頻度

やり方が違うのかも知れませんが、必ずそうなるように見えます。

## 問題のカテゴリ

- ビルドの問題
  - ローカルビルド

## 環境情報
- OS バージョン

- サクラエディタバージョン

- PC情報

**Comment by berryzplus** [comment]
前から気になっていますが誰も気にしてないので放置してあります。

**Comment by beru** [comment]
自分は googletest から doctest に移行して今存在する色々な仕組みを撤廃してすっきりさせたいです。googletest を使うためにビルド周りに手が入っている色々を列挙すると結構長くなるので、正直よくやるなぁ…と思います。

今までに主に @m-tmatma さんや @berryzplus さんが CI や Unit Testing を整備してくれていてインストーラー入手しやすかったりで超有難いんですが、構成の単純さは犠牲になってしまっていると思います。

tools の中の ChmSourceConverter （他に ToolBarTools フォルダ以下のツールも）.NET Framework を使っていますが、久々に違うPCでサクラエディタのビルドを bat ファイルを実行して行うと色々と失敗したりして気付いたりしました。とはいえまぁそれが嫌なら C++ で書き直せばいいだけの話ではありますね。

**Comment by berryzplus** [comment]
doctestｈpython互換の単体テストを作る仕組みですよね。
サクラエディタは単体テストを書けないコードで構成されているので、移行は不可能だと思います。
（移行するには、先に単体テストできるように改修することが前提になります。）

**Comment by sanomari** [comment]
対応ありがとうございました。

**Comment by beru** [comment]
> doctestｈpython互換の単体テストを作る仕組みですよね。

そういう認識ではないです。

https://github.com/onqtam/doctest

の事です。名前が被ってますが…。

> サクラエディタは単体テストを書けないコードで構成されているので、移行は不可能だと思います。
> （移行するには、先に単体テストできるように改修することが前提になります。）

Google Testって一般的なうたい文句は単体テスト用のライブラリだと思いますが、単体テストを書けないコードをそれを使ってテストしてるのも不思議な話ですね。

説明が面倒で自明な行間のごにょごにょの事情できっと移行がOutOf眼中（死語）なんですね。

**Comment by berryzplus** [comment]
> > doctestｈpython互換の単体テストを作る仕組みですよね。
> 
> そういう認識ではないです。

たまたま名前が同じだけなんですね。



> > サクラエディタは単体テストを書けないコードで構成されているので、移行は不可能だと思います。
> > （移行するには、先に単体テストできるように改修することが前提になります。）
> 
> Google Testって一般的なうたい文句は単体テスト用のライブラリだと思いますが、単体テストを書けないコードをそれを使ってテストしてるのも不思議な話ですね。
> 
> 説明が面倒で自明な行間のごにょごにょの事情できっと移行がOutOf眼中（死語）なんですね。

現状で200個くらいのテストケースのうち、単体テストじゃないテストケースは2つだけです。

`単体テストできない設計は設計バグです` という主張はアリだと思うので、
アプリ全体を可能な限りグローバル変数に依存しない書き換えていくリファクタリングもアリだと思います。

まぁ、基本的にミッションインポッシブルだとは思うんですけど。

**Comment by beru** [comment]
> 現状で200個くらいのテストケースのうち、単体テストじゃないテストケースは2つだけです。
> 
> `単体テストできない設計は設計バグです` という主張はアリだと思うので、
> アプリ全体を可能な限りグローバル変数に依存しない書き換えていくリファクタリングもアリだと思います。
> 
> まぁ、基本的にミッションインポッシブルだとは思うんですけど。

そういうリファクタリングをしたいという主張を自分はここでしていないと思いますが、いったい何からそう読み取ったんでしょうか？berryzplus さんの頭の中で導き出した一定の結論を前提とした事が文章として補足されずにいきなり話題に登場している印象を受けます。分かる人なら分かるよね的なノリで進めているのでしょうか？とはいえ想像抜きでの会話なんて無理な事も確かです。

仮に Google Test から doctest に移行するとテストフレームワークの機能差故に実施出来なくなるテストケースが一部あるとしたら、それは省いてしまえば良いのではないかと考えています。それらのテストケースはどうしても取り除きたくはないと言われればそこで話は終了してしまいます。ですがそこまで保守する必要があるテストケースが存在するのかどうかは疑問です…。

自分がGoogle Test から doctest に移行したいって主張しているのは単にビルドシステムのギミックを排除したいからで、それによって発生するテストケースの低減は考慮してません。そんな提案は考慮の価値無しと言われたらそれでこのN回目の話はお終いで、来年も再来年も Google Test を使い続けることになるのかなと思います。

**Comment by berryzplus** [comment]
ビルドシステムのギミックは必要だと思います。

「ビルドシステムのギミックを排除したい」が主張の核心なら、話は終わりです。
「ビルドシステムのギミックなし」を実現することは「絶対に不可能」だからです。
