### ISSUE TITLE
Thank you very much for the free open source program!

### ISSUE THREAD

**Issue by mrkaban** [sakura-editor/sakura#1434]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D1%83/%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%BE%D1%80%D1%8B-%D0%BA%D0%BE%D0%B4%D0%B0/sakura-editor.html).

The project is interesting, so please don't abandon it!

**Comment by beru** [comment]
Пожалуйста. благодарю вас за доброта.

Шоу должно продолжаться!

**Comment by berryzplus** [comment]
SAKURA Editor is published under [zlib-license](https://opensource.org/licenses/zlib-license).
SAKURA Editor издается под zlib-лицензией.

you can use this software with any fee.

拒否する意図はないけど、issueを残しておく意味はなさそうなのでそのうち閉じると思います。

**Comment by mrkaban** [comment]
This is how it says "License: zlib License".
Thank you Friends for the answers and for the translation into Russian!
