### ISSUE TITLE
コメントとクォーテーション文字列の色分けをカラー印刷に反映させたい

### ISSUE THREAD

**Issue by kazasaku** [sakura-editor/sakura#1444]
## 実現したいこと

タイプ別設定でコメントとクォーテーション文字列の色分けが有効な場合、カラー印刷の印字結果に色分けが反映されるようにします。

## 実現するための方法

サクラエディタにおける印刷設定の反映処理では、編集ウィンドウで使用中のタイプ別設定に印刷ページ設定を適用した、印刷用のタイプ別設定が作成されています。
この印刷用タイプ別設定では、次の項目も追加で変更されています。
1. 行コメントデリミタを空文字列(=未設定)にする
2. ブロックコメントデリミタを空文字列(=未設定)にする
3. 文字列区切り記号のエスケープ方法を「0(C/C++言語風)」にする
4. コメントの色分け表示を無効にする
5. シングルクォーテーション文字列の色分け表示を無効にする
6. ダブルクォーテーション文字列の色分け表示を無効にする

なお、ユーザーによって無効化された色分けは印刷結果にも反映されます。上記の変更で影響を受けるのは有効になっている場合のみです。
また、OnChangePrintSetting関数にて色分けの設定更新を行う処理が呼ばれていないため、これらの変更は実際には反映されていません（ [patchunicode#949](https://sourceforge.net/p/sakura-editor/patchunicode/949/) で指摘されています）。

変更案として次の二つを提案します。

### 方法1
- これらの設定変更を行うコードを削除してOnChangePrintSetting関数が色分け設定を変更しないようにする
   - カラー印刷・モノクロ印刷のどちらでも色分けが反映されてしまう現状の動作を新しい仕様として受け入れます。

### 方法2
- これらの設定変更を行うコードをモノクロ印刷の時にだけ実行されるように変更する
   - [patchunicode#949](https://sourceforge.net/p/sakura-editor/patchunicode/949/)はこの方法で対応しています。
   - （色分けの判定を行う[CColorStrategyPool::CheckColorMODE関数](https://github.com/sakura-editor/sakura/blob/d0a92d064b9b13921ee57a0a7a37f66d80364669/sakura_core/view/colors/CColorStrategy.cpp#L250)の判定条件を見た限り、ヒアドキュメントの無効化も含めたほうがよさそうにみえました。）
   - 設定変更が反映されることをカラー印刷で確認して後でモノクロ印刷に限定させるようにしなければ動作をチェックできないと思います。

~~どちらかの対応でPRを提出しようとと思っています。~~ ご検討をお願いします。

**Comment by berryzplus** [comment]
> どちらかの対応でPRを提出しようとと思っています

ぼく個人の見解ですが、印刷機能に関する機能追加・機能変更は時期尚早だと思います。

現状の機能が何をしているかが見えるように整理することが先決ではないかと思っています。

具体的には、複雑度が数百を超える関数をリファクタリングしていくのかな。

「こういう処理があるんですが、処理結果は使われていません。」
というのは、印刷に限らずあちこちに存在しているような気がします。

二択で言ってる前者がこれにあたるなら、いまやってもいいと思います。

**Comment by kazasaku** [comment]
書き方が悪かったです。
コメントの色分けを無効化する処理が機能していないバグが指摘されていて、
1. 現状の動作が正しいとみなして、色分けの設定をしているコードを削る
2. 元の仕様に合わせるためにCColorStrategyPoolの呼び出しを追加する

のどちらかで対応したいという内容なんですが、
さらなる処理の追加を許容できないということであれば削ろうと思います。
最も、手を加えてほしくないと言われると何もしようがないのですが。

**Comment by berryzplus** [comment]
すみません、何言ってるか分からなくなってきました。

提案する側は該当コードを読み込んでいますが、
提案される側は読まずに会話に入るのが普通です。
経験上、提案を聞いてる側をアフォだと思って書くくらいがちょうどいい気がします。

issueの趣旨は「色分けしたい」だと読み取りました。

提案内容をざっくりまとめるとこういうことですよね。
* 常にタイプ別設定通りに色分けするように変える。（≒今回独自？）
* モノクロ時のみタイプ別設定と違う色で色分けするように変える。（≒パッチ？）

「色分けしたい」の目的からすると前者一択な気がいます。

ただ、そうすると印刷時にタイプ別設定と違う色を使おうとしていた理由が気になってきます。
普通に考えると「そうしないと困るから」なんだと思います。
「色分けすることで困りごとを解決できてる」なら後者のアプローチは「必要」なんじゃないかと思います。
困ることが分かっているのに前者のアプローチを採るのは違う気がします。

https://github.com/sakura-editor/sakura/issues/1444#issuecomment-719838987 を見る限りでは、対策はあるけど動いてないって風に読み取れるんですよね。

つまり、モノクロ印刷時に色設定を上書きしなくても誰も困ってない・・・

**Comment by kazasaku** [comment]
> 経験上、提案を聞いてる側をアフォだと思って書くくらいがちょうどいい気がします。

…気をつけます

> 印刷時にタイプ別設定と違う色を使おうとしていた理由

実はこれがわからなくて。

違う色を使うというより、そもそもコメントの色分けはしたくないということなのですが、タイプ別設定でユーザが無効にした場合はその通りに印刷されるので、無効にできなくて困るということもないんです。
モノクロな印刷レイアウトを作成する時の色分け処理を省略したい、というのはありそうですが。

**Comment by kazasaku** [comment]
本提案は取り下げます。
既存パッチの取り扱いは別途。
