### ISSUE TITLE
サクラエディタがNTFSの代替データストリームに対応しているかどうか検証する

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1452]
一足先にマージされてしまいましたが、一応コメントしておきます。

NTFSには代替データストリーム（ADS）というものがあり、ファイル名またはフォルダ名に `:` を続けてストリーム名を指定するものがあります。
`localhost:8080` も `C:\work\test:001.txt` もNTFSであれば、パスとしては正しいです。
この場合.txtは拡張子ではなく、testというファイルの「001.txt」というストリームです。
実際に相対パスのlocalhostや絶対パスでtestというファイルが実在するなら、どちらもメモ帳やサクラエディタで読み書き可能です。
ただし問題はあって、ファイルダイアログでは代替データストリームを正しく扱うことができないんじゃなかったかなと思います。
代替データストリームは、ネットからダウンロードしてきたファイルをマークしたりするZoneIDなどで使われています。
これを「封印」することによって、どれくらいの人が実際に困るかはわからないけれど、今まで一応読み書き可能であったものが、パス指定で開けなくなるんじゃないかな、と思います。
https://github.com/sakura-editor/sakura/blob/8acb720939ed466e7bacdc168da1109b3a6ba5cb/sakura_core/charset/charcode.h#L181
今までの動作では、メッセージでは:がファイル名に使えないと表示されていますが、実際の処理では:をチェックしていません。
OS側の処理として、ドライブレター以外のコロンが2つあったり、パスの途中にあったりした場合はどうなのかとかは、ちょっと知らないです。

_Originally posted by @usagisita in https://github.com/sakura-editor/sakura/pull/1449#issuecomment-720074853_

**Comment by sanomari** [comment]
対応してますね。

代替データストリーム（ADS）について色々調べてみた
https://qiita.com/minr/items/c2393f532b2df35f7a9d

#1449 ではこの機能を殺してしまってるのでマズそうです。
