### ISSUE TITLE
ApiWrap::Combo_GetEditSel の assert 条件が逆ではないか？

### ISSUE THREAD

**Issue by kasumikagari** [sakura-editor/sakura#1460]
https://github.com/sakura-editor/sakura/blob/7cc64972535d163cd5c8c978b74f14b5c734abfb/sakura_core/apiwrap/StdControl.h#L217-L226
222行目と223行目で値がINT_MAX以下に収まるかを確認していますが、比較演算子が逆になっているため必ず失敗します…。

**Comment by beru** [comment]
本当ですね。

引数の型を int から DWORD に変えて assert_warning は削ってしまうのが良いと思います。`Combo_GetEditSel` 関数を利用しているのは１か所しかないですし。

**Comment by berryzplus** [comment]
こっちに書いたほうが分かりやすいですかね。

最新のWindows APIマニュアルによると、メッセージに渡す型の定義が誤っているようです。
https://docs.microsoft.com/ja-jp/windows/win32/controls/cb-geteditsel
https://docs.microsoft.com/en-us/windows/win32/controls/em-getsel

引数型を正しいものに修正し、assertは削除するのが良さそうです。

**Comment by beru** [comment]
#1461 を merge したのでこちらも close して🦓。

**Comment by berryzplus** [comment]
対応ありがとうございました。　←ミスった人。
