### ISSUE TITLE
各項目の間隔について

### ISSUE THREAD

**Issue by nobika31** [sakura-editor/sakura#1462]
## 質問

フォーマットを作成し記事を投稿したところ各項目が詰まって若干見づらく感じます。
各項目の間隔を調整することは可能でしょうか。

## スクリーンショット

![キャプチャ](https://user-images.githubusercontent.com/74276615/98751805-2a1dd780-2404-11eb-9ccb-f24d8772dbb5.JPG)

**Comment by arigayas** [comment]
issueの登録先は**サクラエディタ**のプロジェクトであっていますか？

**Comment by nobika31** [comment]
登録先誤りです。申し訳ありません。
