### ISSUE TITLE
SonarCloudをもっと便利に使えないかなぁという話

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1476]
# 主題
SonarCloudをもっと便利に使えないかなぁ、という話です。

# SonarCloud？何それ？

何それ？と聞かれても、ぼく自身よく知らんです。

とりあえず、ソフトウェア開発における品質分析・保守に活用できるツールっぽいです。

#510 で提案されて、 #674 で導入されました。

詳しくは知らんですが、JAVAで書かれたクラサバの解析ツールSonarQubeをクラウドサービスとして公開したものがSonarCloudらしいです。ただ、公開リポジトリを解析して結果を公開するなら無償利用が可能なので、ここのプロジェクトでは無償ツールの一種として導入した感じです。月額1400円くらい支払えば解析結果を非公開にできるっぽいですがいまのところ需要がないです。

README にバッヂが付いていて毎日 00;00 JST に更新されています。
![image](https://user-images.githubusercontent.com/3253151/100748853-3c010200-3427-11eb-8408-3c8b29f32077.png)
　👆ここの「QualityGate = Failed」ってのがそうです。

これ、日本語で言うと「品質的にリリース不可」って意味です。
普通にガン無視してリリースを行っていたわけですが、たぶんきっと問題アリな気がします。

バッヂをクリックすると品質分析の詳細を見られるようになっています。
このissueを立てる目的は、「問題アリ」をざっくりと認識してもらうことだったりします。

# 絵で見る問題点
詳細ページはこんなんです。
![image](https://user-images.githubusercontent.com/3253151/100747796-da8c6380-3425-11eb-9745-56b75f26ca91.png)

* SonarCloudクライアントを実行しているJDKが古すぎると警告が出ています。
* 336 という数字は SonarCloud 的に「ヤバいレベルの警告の数」らしいです。
* 0% という数字は 単体テスト・機能テスト のカバレッジらしいです。
* 「QualityGate = Failed」です。
* 右上のとこに「警告が2つあります」と出ています。

# その他
過去断面の解析詳細を表示することはできないようです。

毎日のバッチタスクで Win32/x64 と Debug/Release のビルドが走っているんですが、
表示できるのは、たまたま最後に解析された1環境の結果だけです。
どうも環境によって「バグ扱いの警告数」が違うようで、
ある修正の効果があったかどうかを確実に知る方法がない状態になっています。

**Comment by k-kagari** [comment]
> 毎日のバッチタスクで Win32/x64 と Debug/Release のビルドが走っているんですが、
> 表示できるのは、たまたま最後に解析された1環境の結果だけです。
> どうも環境によって「バグ扱いの警告数」が違うようで、
> ある修正の効果があったかどうかを確実に知る方法がない状態になっています。

Win32 Debug のみに絞ることはできませんか？
https://github.com/sakura-editor/sakura/blob/526f51224b5a7c1195bfaf7002f8ab65f55427fb/ci/azure-pipelines/template.job.SonarQube.yml#L15-L23
ここで Win32_Debug 以外の matrix を削除すればそういう感じに動きそうに見えます。

**Comment by k-kagari** [comment]
Bug だと言われているもののうち最高レベルの Blocker は43件で、内訳は以下のような形です。

- 27件 = 文字列操作（範囲外参照の可能性）
- 6件 = 「std::make_unique の戻り値がリークする」という内容の警告（？？）
- 4件 = std::forwardの使い方 (#1477)
- 3件 = 文字以外の配列操作
- 2件 = オブジェクト外への参照を戻り値にしている
- 1件 = 継承元クラスへのスライシング

特に文字列操作についてよく怒られているわけですが、適切に範囲チェックしているのに分析器がそれを検出できてないのが実態であるように見えます。
C文字列を使ってはいけない。すべて std::string にするべきだ。ということを言いたいようですが。
1万9千件もある Code Smell についての警告も大部分がそういう内容ですし、コードベース全体で審査に合格するのはきっと途方もなく大変です…。

PR などで追加・修正した部分だけ Quality Gate 適用できたらいいなあ、と思います。

**Comment by berryzplus** [comment]
> Win32 Debug のみに絞ることはできませんか？

試してみた感じ、できそうです。

ただ、１環境に絞る宛先としては x64 - Release がいいんじゃないかと思っています。

理由は、いくつかあります。
* 開発版としては Win32 - Debug が最も適切に思えますが、「一般向け」で公開するのはこれじゃないです。
* 既存リリース版は Win32 - Release なんですけど、既存の見えてる問題を解決したいわけじゃないです。
* x64 - Debug はぼくが個人的に、ほぼ使ってません。
* x64 - Release をリリースするにあたって、コンパイラ警告を潰す、以外の指標がない状態が長いこと続いています。SonarCloudの対象環境を x64 - Release にしたら、それはリリース判断の指標になりうるんじゃないかと思います。

実際には、そもそもの問題としてSonarCloudの警告に従うのか？があるんですけどね。
（技術的に可能だから使ってみようぜ！にOK出しただけの代物なので。）

**Comment by berryzplus** [comment]
> PR などで追加・修正した部分だけ Quality Gate 適用できたらいいなあ、と思います。

実はこれが可能っぽいんです。
まだちゃんと試せていないんですけど、GitHubActionsに組み込んでPRで修正した部分だけの分析ができる模様。
これができるならPRのレビューにも活用できそうです。
いまんとこ、GitHubActionからSonarCloudしてQualityGateを更新するとこまでの実験しかできとらんです...。
やり方がおかしいのかもですが、QualityGateはRelease版にしかつかないっぽいです。

Quality Gateは元々「過去30日間の修正でコード品質が一定以上、かつ、修正部分のカバレッジが8割以上」という指標らしいです。
　　↓
まて、コードカバレッジを採る方法が確立できとらんやんけ！
　　↓
OpenCppCoverage + plugin でそれっぽいものができることは確認済み。
（出力が気に入らなくてPlugin自作とか始めて横道爆走中・・・）
（要するに、コードカバレッジを採れる方法は見つかっています。）

**Comment by k-kagari** [comment]
どの環境をスキャンするべきかについて意見はありませんので、理由あってx64 Releaseが適当だと思われるのであればそれが良いと思います。

> 実際には、そもそもの問題としてSonarCloudの警告に従うのか？があるんですけどね。
> （技術的に可能だから使ってみようぜ！にOK出しただけの代物なので。）

すべてに従う必要はなさそうですが、何について警告されているかを把握しておくのは有益そうです。
"false positive" や "won't fix" としてマークすればダッシュボード上の警告が減らせる…のかな？（SonarCloudが理解できてない）

> OpenCppCoverage + plugin でそれっぽいものができることは確認済み。
> （出力が気に入らなくてPlugin自作とか始めて横道爆走中・・・）
> （要するに、コードカバレッジを採れる方法は見つかっています。）

期待を込めて完成をお待ちしてます。

**Comment by berryzplus** [comment]
このissueに対する3つ目の変更として「静的解析SonarCloudにキャッシュを使う」を提案しようとしていたんですが、単純には無理そうです。

現在のSonarCloud解析は [ci/azure-pipelines/template.job.SonarQube.yml](https://github.com/sakura-editor/sakura/blob/master/ci/azure-pipelines/template.job.SonarQube.yml) に実装していて、Azure Pipelinesの管理画面からパイプラインのスケジュールビルドを設定することにより実現しています。

なんでそうしているかというと、当初SonarQube解析に1時間近くかかっていたからです。
1時間もかかるような重たい解析をpushやPRのたびに実行させるわけにもいかないのでそうしたはずです。

オイラがやりたかった変更「静的解析SonarCloudにキャッシュを使う」は、
「SonarQubeには時間がかかる」の前提を吹き飛ばしてしまう内容です。
自分のところで試している感じ、静的解析にキャッシュを使うことによりPRのたびに実行しても問題ない速度になります。

|環境|所要時間|説明|
|--|--|--|
|Azure Pipelines(キャッシュなし)|約30分|現状の仕組みと同じもの 👉 [Azure DevOps](https://dev.azure.com/berryzplus/sakura/_build/results?buildId=104&view=results)|
|GitHub Actions(キャッシュあり)|約10分|準備してた仕組み 👉 [GitHub Actions](https://github.com/berryzplus/sakura/runs/1545920609?check_suite_focus=true)|

準備してた仕組みはかなり高速なので、PR時に「そのPRが作り込んだCode Smells」を検出するのに使えそうです。
ただし、従来使用していたSonarScannerが使えなくて代替を探した結果、対象がC/C++だけでなくなってしまい、導入のためにはHTMLヘルプの課題をやっつけてやる必要があります。(HTML関連で3000件くらいBugsレベルが検出されてしまう）
https://sonarcloud.io/dashboard?id=berryzplus_sakura だいぶ対応してみましたが、かなり残っています。

**Comment by berryzplus** [comment]
ローカルリポジトリでコミットごとの静的解析結果を表示できるところまで確認できました。
https://github.com/berryzplus/sakura/runs/1581739720

ただ、これをこのまま導入しようとすると、PRに対するビルド結果が常に×で表示されることになりそうです。

**Comment by berryzplus** [comment]
> ただ、これをこのまま導入しようとすると、PRに対するビルド結果が常に×で表示されることになりそうです。

別に良いか、という結論に至りました。
これまでも「チェック結果が × なPRは通してはならない」みたいなことはしていませんし、
修正対象コードに対するテスト実施状況が確認できるようになるのでむしろプラス方向な気がしてきました。

対策は #1486 と合わせて行う方向で検討しています。

**Comment by berryzplus** [comment]
#1494 マージで活用できる環境は整ったので、あとは #1504 でBugsを潰す話に続きます。
一応、`won't fix`で除外することも視野に入れて進めていきたいです。
