### ISSUE TITLE
GIT_COMMIT_HASH が存在しない場合にバージョン番号が表示されなくなる箇所がある

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#148]
参考
https://github.com/sakura-editor/sakura/pull/147/files
> @m-tmatma 
> GIT_COMMIT_HASH が定義されていないとバージョン情報自体がなくなります。
> GIT_COMMIT_HASH が定義されていないとき GIT_COMMIT_HASH の以外の部分は残すべきだと思います。

**Comment by m-tmatma** [comment]
#147 がマージされた。

**Comment by yoshinrt** [comment]
git インストールがビルド要件でしたら無視してください．
git コマンドが利用できない条件でビルドすると .rc でエラーになるようです．
```
重大度レベル	コード	説明	プロジェクト	ファイル	行	抑制状態
エラー	RC2104	undefined keyword or key name: GIT_SHORT_COMMIT_HASH	sakura_lang_en_US	D:\DDS\sakura\sakura_lang_en_US\sakura_lang_rc.rc	2823	
エラー	RC2104	undefined keyword or key name: GIT_SHORT_COMMIT_HASH	sakura	D:\DDS\sakura\sakura_core\sakura_rc.rc	2821	
```
defdb573 で再現しました．

ご検討をよろしくお願いいたします．
(ちなみに自分は cygwin git を使用しているでビルド時にパスが通っていません)

**Comment by berryzplus** [comment]
gitにパスを通すことはビルド要件である認識です。

**Comment by kobake** [comment]
ビルド要件としては明示してないですが、ZIPでソース一式ダウンロードしてビルドする人もいるので、自分としては git 無くてもビルドできるようにはしておきたいと思っています。

少なくとも少し前の master では git 無しでもビルド出来ていました。

現時点の master について、ちょっとこちらでもビルド試してみますね。

**Comment by berryzplus** [comment]
...(Closed になってるissueに重要っぽいコメントが入ってたのでreopenしました。)

閉じるタイミングはお任せします。

**Comment by kobake** [comment]
#191 で対応しました。これがマージされたらこの Isssue は再クローズします。
