### ISSUE TITLE
[要望] Ctrl+マウスホイールにて変更した場合に表示倍率を表示して欲しい

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#1485]
## やりたいこと(=実現したいこと)
`Ctrl+マウスホイール`にて変更した場合に文字の大きさが変化しますが、
どれくらい表示倍率を変更したのか分からなくて不明なので
`Ctrl+マウスホイール`にて変更した場合に表示倍率を表示して欲しいです。

メモ帳には`Ctrl+マウスホイール`にて変更した場合の表示倍率が表示されてます。
もし、メモ帳と同じようにステータスバーに倍速を表示する実装だったら、
倍率表示の所をダブルクリックしたら倍率指定が出来ると嬉しいです。

## スクリーンショット 
Windows10 20H2 のメモ帳80%
![image](https://user-images.githubusercontent.com/11251874/101975597-17a3f180-3c81-11eb-8b21-ef0993fda317.png)

Windows10 20H2 のメモ帳100%
![image](https://user-images.githubusercontent.com/11251874/101975589-11157a00-3c81-11eb-98a6-68b043dd9850.png)

`UTF-8 BOM付` の所をダブルクリックしたら表示されました。
![image](https://user-images.githubusercontent.com/11251874/101975877-5470e800-3c83-11eb-9ae0-5a8eda2dbe02.png)

## 関連するかもしれないissue
#673 ：Ctrl+マウスホイールにて変更した現在のフォントサイズをフォントダイアログに反映して欲しい

**Comment by suconbu** [comment]
現在の倍率が表示されるようになると、一時的に拡大した後に元に戻す際、きちんと 100% に戻ったことを確認できる点が個人的にうれしいです。

また、倍率の横にポイント数も併記されるとフォントサイズの確認 (何ポイントの時どれぐらいの見た目になるか？) にも使えてさらに便利そうだと思いました。

**Comment by arigayas** [comment]
> また、倍率の横にポイント数も併記されるとフォントサイズの確認 (何ポイントの時どれぐらいの見た目になるか？) にも使えてさらに便利そうだと思いました。

フォントサイズを確認するためにフォントの設定を開く必要がなくなるのは良いですね！

**Comment by arigayas** [comment]
Delphiでどんな感じになるかモックアップを作ってみました。
![image](https://user-images.githubusercontent.com/11251874/102306161-eb4fe400-3fa4-11eb-852e-7207b7d85d06.png)

この要望が採用されたら #673 は取り下げて良いと思ってます。

**Comment by suconbu** [comment]
モックアップ見させて頂いて気づいた所としては、ステータスバーに出すポイント数は、フォント設定でのポイント数にビューの倍率を適用した「相当」の値になるため、この点が誤認されにくい見せ方が良いのかなと思いました。
例えば「nnn % (nn Pt)」のような括弧書きなどはどうでしょうか。

**Comment by arigayas** [comment]
>  例えば「nnn % (nn Pt)」のような括弧書きなどはどうでしょうか。

この表示方法で良いと思います。

**Comment by suconbu** [comment]
フォントサイズを変更している処理を見てみたところ、自分が想像していたものと少し違っていました。

> void CViewCommander::Command_SETFONTSIZE( int fontSize, int shift, int mode )
> 	static const INT sizeTable[] = { 8*10, 9*10, 10*10, (INT)(10.5*10), 11*10, 12*10, 14*10, 16*10, 18*10, 20*10, 22*10, 24*10, 26*10, 28*10, 36*10, 48*10, 72*10 };

Ctrl + マウスホイール操作した時は、この `sizeTable` から「現在のサイズ以上で最も近いもの」を探してその手前/後ろのサイズを選択するようです。
なので、フォント設定でこのテーブルにはないポイント数 (15pt など) を設定していた場合、現仕様ではマウスホイール操作で 100% に戻せないようですね。。

一旦、ポイント数のみ表示できるものを試作してみます。

**Comment by suconbu** [comment]
> Ctrl + マウスホイール操作した時は、この sizeTable から「現在のサイズ以上で最も近いもの」を探してその手前/後ろのサイズを選択するようです。

どうもこのテーブルから探す時、テーブル側の値に DPI が反映されていないようです。(「現在のサイズ」の方は反映済みの値)
ポイント数を表示させるとおかしいことが露呈してしまうため😅まずはこの問題を直した方がよさそうですね。
