### ISSUE TITLE
SAKURA_LANG_RESOURCE の定義の有無が異なる

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#149]
SAKURA_LANG_RESOURCE の定義の有無が異なる

https://github.com/sakura-editor/sakura/blob/847715879382e761048685e5bce091309feffc81/sakura_core/sakura_rc.rc#L3

https://github.com/sakura-editor/sakura/blob/847715879382e761048685e5bce091309feffc81/sakura_lang_en_US/sakura_lang_rc.rc#L3

参考
https://github.com/sakura-editor/sakura/pull/147#issuecomment-398752359

**Comment by berryzplus** [comment]
前後関係よくわかっていないのでわかる方ツッコミよろしくです。

このシンボルは、言語DLLをビルドする時にsakura_coreのヘッダーを使えるようにするためのものだったはずです。

だからcore側でこのシンボルが定義されてたらおかしいはず。

**Comment by berryzplus** [comment]
議題になったマクロの相違点が既に削除されとりますね・・・。

```
すべて検索 "SAKURA_LANG_RESOURCE", 大文字と小文字を区別する, サブ フォルダー, 検索結果 1, ソリューション全体, ""
  C:\work\sakura-editor\sakura\sakura_core\sakura_rc.rc(2168):#ifndef SAKURA_LANG_RESOURCE
  C:\work\sakura-editor\sakura\sakura_core\sakura_rc.rc(2221):#endif	// ! SAKURA_LANG_RESOURCE
  C:\work\sakura-editor\sakura\sakura_core\sakura_rc.rc(4183):#ifndef SAKURA_LANG_RESOURCE
  C:\work\sakura-editor\sakura\sakura_core\sakura_rc.rc(4192):#endif	// ! SAKURA_LANG_RESOURCE
  C:\work\sakura-editor\sakura\sakura_lang_en_US\sakura_lang_rc.rc(2174):#ifndef SAKURA_LANG_RESOURCE
  C:\work\sakura-editor\sakura\sakura_lang_en_US\sakura_lang_rc.rc(2227):#endif	// ! SAKURA_LANG_RESOURCE
  C:\work\sakura-editor\sakura\sakura_lang_en_US\sakura_lang_rc.rc(4194):#ifndef SAKURA_LANG_RESOURCE
  C:\work\sakura-editor\sakura\sakura_lang_en_US\sakura_lang_rc.rc(4203):#endif	// ! SAKURA_LANG_RESOURCE
  一致する行: 8    一致するファイル: 2    検索ファイル総数: 721
```

visual c++での`リソーススクリプト(*.rc)` は自動生成ファイルなので、基本的に「手で編集したらいかんファイル」です。`#ifndef`とかマクロ展開とか楽しく色々やりたい場合には textinclude 3 で `rc2` をインクルードしてそこでやります。

なのでまぁ、基本的に `そのマクロ、存在自体間違ってね？` というのがぼくの見解で・・・

**Comment by berryzplus** [comment]
既に削除済み（≒解決済み）なので閉じときます。
