### ISSUE TITLE
Visual Studio Community 2019 で tests1 を編集すると意図しない変更が挿入される

### ISSUE THREAD

**Issue by k-kagari** [sakura-editor/sakura#1492]
## 問題内容

Visual Studio Community 2019 で tests1 プロジェクトを編集すると、 tests1.vcxproj.filters から coverage.cpp が意図せず削除されます。coverage.cpp は 803805d で追加されたものです。 https://github.com/sakura-editor/sakura/pull/1491#discussion_r546837306 によると、Condition を追加すると消えなくなるようです。

## 再現手順

Visual Studio Community 2019 で tests1 プロジェクトにソースファイルを追加して保存する。

## 問題のカテゴリ

- その他の問題

**Comment by k-kagari** [comment]
tests1.vcxproj と同じ Condition を filters に入れれば勝手に消える現象は再現しなくなるようですが、同時に上位エディションで問題を作ってしまっていないかどうかが検証できません。上位エディションをお持ちの方に一度ご確認をお願いできればと思います。

**Comment by berryzplus** [comment]
試してみました。vcxproj にあるのと同じ Condition を入れるでイケそうです。
