### ISSUE TITLE
Appveyor で sakura editor の organization 用のアカウントを作成してほしい

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#15]
https://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations

Posted by Feodor Fitsner on Jul 19, 2015 @ 04:12 AM のコメント参照

`AppVeyor account is not bound to GitHub organization. Just sign up on https://ci.appveyor.com/signup page. If you mean the URL part https://ci.appveyor.com/project/<organization>/project then this could be updated on https://ci.appveyor.com/account page.
`

**Comment by kobake** [comment]
User name が `sakura-editor` のユーザを作ってみました。が、URLからハイフン削られちゃいました。  
https://ci.appveyor.com/project/sakuraeditor/sakura  
ちょっと悲しい…。

初回ビルドが謎エラーで止まりました。
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.1
```
Build started
Set-WinSystemLocale ja-JP
Start-Sleep -s 5
Restart-Computer
git clone -q --branch=master https://github.com/sakura-editor/sakura.git C:\projects\sakura
fatal: destination path 'C:\projects\sakura' already exists and is not an empty directory.
Command exited with code 128
```

AppVeyor の問題っぽい感じがします。しかしビルド実行し直したらちゃんと進みました。

ちょっと様子見していきます。問題なさそうであれば運用をこちらに切り替えます。

**Comment by kobake** [comment]
AppVeyor の Environment 設定で clone 先のディレクトリパスを明示指定できるみたいだったので、ここで他プロジェクトと被りにくいパスに変更しました。

<img width="770" alt="clone-directory" src="https://user-images.githubusercontent.com/2929454/40841845-dae4ed30-65e6-11e8-88e4-8492551c6225.png">

**Comment by kobake** [comment]
上記対応により `fatal: destination path 'C:\projects\....' already exists and is not an empty directory.` のエラーは出なくなる、はずです。

#33 で README 記載の AppVeyor の URL を kobake のものから sakuraeditor のものに変更しました。

これで本 Issue は対応完了とします。

**Comment by m-tmatma** [comment]
> AppVeyor の Environment 設定で clone 先のディレクトリパスを明示指定できるみたいだったので、ここで他プロジェクトと被りにくいパスに変更しました。

appveyor.yml があると、appveyor.yml の設定が優先されそうに思いますが、
設定は有効に働いていますか? 

変更してからまだビルドしてないですか?

https://www.appveyor.com/docs/appveyor-yml/ によると、
clone_folder: という設定で変更できるみたいです。

また上記サイトで以下のようなコードがコメントとして記載されています。

# version: 1.0.{build}-{branch}

これを設定することでほぼかぶらない用にできるかもしれません。

**Comment by kobake** [comment]
>> AppVeyor の Environment 設定で clone 先のディレクトリパスを明示指定できるみたいだったので、ここで他プロジェクトと被りにくいパスに変更しました。

> appveyor.yml があると、appveyor.yml の設定が優先されそうに思いますが、
> 設定は有効に働いていますか?

ちょうど今エラーが発生していて、見に行ったら前と変わらないエラーが出ていました…

もうちょっと小さいプロジェクトで試行錯誤してみます。解決したつもりになっていたのはちょっと早計でした。

**Comment by m-tmatma** [comment]
> version: 1.0.{build}-{branch}
> これを設定することでほぼかぶらない用にできるかもしれません。

一応補足

これを設定するわけではなく、ここに使われている {build} や {branch} などの変数を
組み合わせて使うという意味です。
