### ISSUE TITLE
Azure Pipelinesの除外パス指定が機能していないらしい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1501]
## 問題内容

#1500 の仕様説明で妙なコメントを見たのでissue化しておきます。

> 変更対象(YAML)の仕様については公式サイトを参照してください。
> https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=azure-devops&tabs=schema%2Cparameter-schema#triggers
> 
> 明記されていませんが、AppveyorともGitHub Actionsとも異なる仕様があるようです。
> 
> パスに指定できるのは、英字で始まる相対パスです。
> パスの一部に*記号を入れることでパターンを指定できます。
> GitHub Actionsと異なり`*`を含むパターンを引用符でくくる必要はありません。
> つまり既存コードにある`'**/*.md'`も機能していません。

## 再現手順

拡張子mdのファイルを編集したコミットをpushします。

拡張子mdのファイルは除外パスに含まれているので、
Azure Pipelineビルドは走らないことが期待されますが、
除外パスが機能してないのでビルドが走ってしまう、ということかと思います。

## 再現頻度

不明です。
言われてみれば、前にREADME.md変更のPR出したときにAzure Pipelinesビルドが走っていたような気がします。

## 問題のカテゴリ
- ビルドの問題
  - Azure Pipelines

## 関連 issue, PR
#1500
#1259

**Comment by berryzplus** [comment]
## 考え得る対策（その１）
先頭がアスタで始まるパターン指定が効かないようなので、
ルート直下に置いたmdファイルは各個別に除外指定を書いたらいいはずです。

ルート直下にはmdファイルが15個もありますので、除外パスを15行追加することになります。

**Comment by berryzplus** [comment]
## 考え得る対策（その２）
mdファイルを除外させるのを諦めます。

問題なのは、mdファイルだけ編集したときにビルドが走ってしまうことではなく、
「mdファイルだけ編集したときはビルドが走らないように見える」のにビルドが走ることです。
※機能しないことが分かっている設定が残っていることが問題です。

Azure Pipelinesでは除外パスが機能しません、ならそれはそれでいいようにも思います。

**Comment by k-takata** [comment]
azpのpathsの仕様はこれかな。
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#paths

> * Wild cards are not supported with path filters.

そうなのか…
