### ISSUE TITLE
AppVeyorのジョブが途中で止まることがある

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#151]
「appveyor で clone に失敗する #43」の問題は #96 の対応によりおそらく解消されたように思われますが、それとは別の問題として、AppVeyorジョブが途中で長時間停止することがある（これは以前にも1回くらい見た覚えがある）ようです。

### ビルドログ
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.200/job/bdvf8n5xt0d8hcc3
```
Build started
Set-WinSystemLocale ja-JP
Start-Sleep -s 5
Restart-Computer
Start-Sleep -s 5        ← ここ以降進んでいない
```

### メッセージ
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.200/job/bdvf8n5xt0d8hcc3/messages
```
Build execution time has reached the maximum allowed time for your plan (60 minutes).
```

このメッセージを見る限り、ジョブ時間が 60min 経過するとタイムアウトとみなされジョブは失敗扱いとなる模様。

以前話していた、「手動でジョブ停止する人間がいないと詰むことがあるのでは」という懸念はタイムアウトの存在により一応払拭されましたが、そもそもジョブが原因不明でスタックするような現象は回避可能であれば対策入れたいですね……

**Comment by m-tmatma** [comment]
以下を登録しました。
- appveyor/ci#2456　(このチケット)
- appveyor/ci#2457　(タイムアウトを短くできるかという質問)

**Comment by kobake** [comment]
渉外活動おつです。助かります！

**Comment by m-tmatma** [comment]
昨日 PR 送ろうと思ったが、このチケットの問題でまだ送ってない。
結構重要な問題だ。

**Comment by m-tmatma** [comment]
以下のチケットが登録された
https://github.com/appveyor/ci/issues/2459

**Comment by m-tmatma** [comment]
どなたか、これ試せますか？
https://github.com/OwenMcDonnell/ProjectA/commit/c6fb53cd9a161f03b1433aaa146b03859272cc41

**Comment by m-tmatma** [comment]
> どなたか、これ試せますか？
> OwenMcDonnell/ProjectA@c6fb53c

#156 で対応しました。

**Comment by m-tmatma** [comment]
#156 がマージされました。
失敗する PR があれば rebase してください。

**Comment by m-tmatma** [comment]
現状、失敗する事例は確認されていない。
しばらく問題なければクローズする。

**Comment by m-tmatma** [comment]
> appveyor/ci#2456　(このチケット)
> appveyor/ci#2457　(タイムアウトを短くできるかという質問)

タイムアウトを短くできるようにしてくれるらしい

https://github.com/appveyor/ci/issues/517#issuecomment-399622573

`OK, we will add decrease option for projects which use AppVeyor workers. Please watch this issue.`

**Comment by m-tmatma** [comment]
https://github.com/m-tmatma/sakura/blob/d887997da1054ee637b762c6825f6bd34850167a/appveyor.yml#L1-L7

で発生

https://ci.appveyor.com/project/m-tmatma/sakura/build/1.0.301

**Comment by m-tmatma** [comment]
↑ 再発したことを報告した。
https://github.com/appveyor/ci/issues/2456#issuecomment-403271302

以下のコメントを貰った。
https://github.com/appveyor/ci/issues/2456#issuecomment-403299903

#241 で PR を作成

**Comment by m-tmatma** [comment]
また発生した。
https://github.com/sakura-editor/sakura/pull/418#issuecomment-420447904

**Comment by m-tmatma** [comment]
> また発生した。
> [#418 (comment)](https://github.com/sakura-editor/sakura/pull/418#issuecomment-420447904)

以下で報告した。
https://github.com/appveyor/ci/issues/2456#issuecomment-420448450

失敗のビルドは以下です。
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.776

**Comment by m-tmatma** [comment]
#482 により、全く発生しなくなるかもしれない。

**Comment by m-tmatma** [comment]
タイムアウトを短くする方法が対応されているみたい。(試してないが)
https://github.com/appveyor/ci/issues/517#issuecomment-429520574

**Comment by m-tmatma** [comment]
いまのところはこの問題は再発してない。

**Comment by berryzplus** [comment]
appveyorの起動時にsystem Localeをja-JPにしていたころに発生してた問題のissueのようです。
当時は各jobの先頭で必ずやっていたのを、現在はhelpのコンパイル時のみに行っています。
とりあえず、困るくらいの遅延は発生していないように思うので一旦閉じてしまいます。
