### ISSUE TITLE
すべてのウィンドウが最小化された状態で「並べて表示」コマンドを実行するとクラッシュする

### ISSUE THREAD

**Issue by k-kagari** [sakura-editor/sakura#1510]
## 問題内容

以下の JScript マクロ2例を実行するとプログラムがクラッシュします。

```
Editor.MinimizeAll();
Editor.TileWinV();  // 上下に並べて表示
```
```
Editor.MinimizeAll();
Editor.TileWinH();  // 左右に並べて表示
```

SonarCloud で Division by zero と指摘されている箇所が原因です。

https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AW8eyhBVak1yqJchwkoz&open=AW8eyhBVak1yqJchwkoz
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&issues=AW8eyhBVak1yqJchwko0&open=AW8eyhBVak1yqJchwko0

## 再現手順

上記のマクロを.jsファイルに保存して実行する。

## 再現頻度

100%（のはず）

## 問題のカテゴリ

- プログラムの動作上の問題

**Comment by berryzplus** [comment]
手で操作して再現できる不具合ではなさそうなので優先度は下げてよいかと思います。

一応、この程度の修正で指摘を消せることまでは確認しています。
https://github.com/berryzplus/sakura/commit/21d6d01d06abae866fe7416f58a5fc2e99d320a5
https://github.com/berryzplus/sakura/commit/2a634610da6b8379f090a145999830a24f0594b4

ここのコードは本来「コントロールプロセス」で管理しているウインドウ情報を、
「エディタプロセス」側で無理やり実行させるために、
自前でnewして確保した配列を用意してデータを受け取っています。
確保したメモリを解放するだけの最小実装は上記になります。

個人的には気に入らないんですけど・・・

**Comment by sanomari** [comment]
簡単に直せるなら直したらいいのではないでしょうか。

> ここのコードは本来「コントロールプロセス」で管理しているウインドウ情報を、
> 「エディタプロセス」側で無理やり実行させるために、
> 自前でnewして確保した配列を用意してデータを受け取っています。
> 確保したメモリを解放するだけの最小実装は上記になります。
> 
> 個人的には気に入らないんですけど・・・

CControlProcessとCNormalProcessの話をしてます？
なんとなく、ウインドウ管理はCControlProcessの役割なのでCNormalProcess側から呼ばれるコードに実装するのは誤っていると言ってる風に読み取りました。そうなの？

ゼロ除算は典型的なよくある不具合なので、さっさと直してしまえばいいと思います。
あるべき姿かどうかは、直したあとでじっくり考えたらいいと思います。

**Comment by berryzplus** [comment]
> > ここのコードは本来「コントロールプロセス」で管理しているウインドウ情報を、
> > 「エディタプロセス」側で無理やり実行させるために、
> > 自前でnewして確保した配列を用意してデータを受け取っています。
> > 確保したメモリを解放するだけの最小実装は上記になります。
> > 個人的には気に入らないんですけど・・・
> 
> CControlProcessとCNormalProcessの話をしてます？
> なんとなく、ウインドウ管理はCControlProcessの役割なのでCNormalProcess側から呼ばれるコードに実装するのは誤っていると言ってる風に読み取りました。そうなの？

たぶん・・・ですが、そうです。
CControlProcessには「コントロールプロセス」の他に「管理プロセス」という説明が付いています。

コントロールプロセスが何かを管理するものだとして、
ウインドウ管理がコントロールプロセスの役割でないとすると、
「何を管理するの？」ってなります。

コントロールプロセスのその他の役割には、
・共有メモリの初期化（≒共通設定のロック）
・タイプ別設定の保持・更新管理
・新規エディタプロセスの起動
・タスクトレイの通知領域へのアイコン登録・維持
があります。

ウインドウ管理がコントロールプロセスの役割であるとすると、
問題が検出されたコードは「そこにそのコードがあること自体が不具合」のような気がします。

> ゼロ除算は典型的なよくある不具合なので、さっさと直してしまえばいいと思います。
> あるべき姿かどうかは、直したあとでじっくり考えたらいいと思います。

では、とりあえずPR作ってみます。
