### ISSUE TITLE
インストーラ：プログラム一覧でのサクラエディタ表示の調整（バージョン番号記載等）

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#152]
安定の @arigayas さんからのご報告です。

https://twitter.com/arigayas/status/1009909801818710017
> @arigayas
> #サクラエディタ のインストーラーってコントロールパネルの「プログラムと機能(Windows10の場合の名称)」の一覧の「バージョン」の数字は表示されるようになるのかな？
![p1](https://user-images.githubusercontent.com/2929454/41746721-648319cc-75e6-11e8-90e4-7d2100ba51ad.jpg)
![p2](https://user-images.githubusercontent.com/2929454/41746725-66752bf8-75e6-11e8-8b5c-4af0e25d8a48.jpg)

たしかに「プログラムと機能」の一覧に表示されるソフトウェア名にはバージョン番号も併せて記載されているのが一般的に思います。特に異論なければ入れましょうか。

スクリーンショットを見た限り、以下の項目の変更するのが良さそうです。
- 名前 … バージョン番号を入れる (#178)
- サポートリンク … URL差し替え (#126)
- ヘルプリンク … URL差し替え (#126)

対応方法はたぶん [sakura-common.iss](https://github.com/sakura-editor/sakura/blob/master/installer/sakura-common.iss) を変えるだけで済みそうです。

```
....
....
AppVerName=sakura editor(サクラエディタ)
....
....
AppPublisherURL=http://sakura-editor.sourceforge.net
AppSupportURL=http://sakura-editor.sourceforge.net
AppUpdatesURL=http://sourceforge.net/projects/sakura-editor/
....
....
```

**Comment by kobake** [comment]
おっと失礼しました。「サポートリンク」でGitHub検索して引っかからなかったもので気づきませんでした。

**Comment by m-tmatma** [comment]
> たしかに「プログラムと機能」の一覧に表示されるソフトウェア名にはバージョン番号も併せて記載されているのが一般的に思います。特に異論なければ入れましょうか。

#178 で対応

**Comment by m-tmatma** [comment]
> サポートリンク … URL差し替え
> ヘルプリンク … URL差し替え
> 
> これに関しては　#126　を登録しています。

#180 のマージ後にやるのがいいと思います。

**Comment by KENCHjp** [comment]
クローズ？

**Comment by kobake** [comment]
バージョン番号記載、URL記載の2要件があり、前者は対応済み、後者はこれから対応？という認識です(見逃してたらごめんなさい)

**Comment by kobake** [comment]
あー、 #180 はバージョンダイアログのURLですね。

本 Issue でいう URL は Windows のインストール済みプログラム一覧画面に表示されるURLのほうで、そこはまた別件なのです。

**Comment by KENCHjp** [comment]
なるほどです。

**Comment by m-tmatma** [comment]
#180 は Installer の x64 対応です。
バージョンダイアログの URL はまた別です。

> 本 Issue でいう URL

に関してはこのチケットが登録される前に、#126 で登録しています。
https://github.com/sakura-editor/sakura/issues/152#issuecomment-399254203

> バージョン番号記載、URL記載の2要件があり、前者は対応済み、後者はこれから対応？という認識です(見逃してたらごめんなさい)

前半は #178 の PR で対応済みで
後半は #126 でまだ対応は入っていません。(昨日コメントを書いてます)

**Comment by m-tmatma** [comment]
> 後半は #126 でまだ対応は入っていません。(昨日コメントを書いてます)

マージ済みです。閉じるの忘れてました。
