### ISSUE TITLE
置換時の検索文字列が正しく設定できない

### ISSUE THREAD

**Issue by yoshinrt** [sakura-editor/sakura#1525]
## 問題内容
Ctrl-R で設定した検索文字列が正しく置換されない

## 再現手順
どこに条件があるのかわからないので細かいですが手順を記載します．

1. https://ci.appveyor.com/api/buildjobs/fnyjq4db1k7woy4q/artifacts/sakura-build3414-06a3ac1-Win32-Release-Exe.zip をダウンロードして解凍
1. sakura.ini が存在する場合は削除
1. sakura.exe を W クリックで起動
1. 添付 [z.txt](https://github.com/sakura-editor/sakura/files/5908826/z.txt) を D&D で開く
1. 1行12桁にカーソル移動
1. Ctrl-R をおす
1. 置換後 に `aaaa` 入力 (置換前 は入力済みから触らない)，オプションは図の通り設定後，すべて置換を押す
![screenshot png](https://user-images.githubusercontent.com/32790691/106555906-d84ba000-6561-11eb-8967-4049f6030933.jpg)
1. 「0個置換しました」になる
1. 再び Ctrl-R で「置換前」のドロップダウンリストを見てみると，「displa」になっているのがわかる

## 再現頻度
100%

## 問題のカテゴリ
- プログラムの動作上の問題
  - Appveyor ビルド版

## 環境情報
- OS バージョン
Win10 Pro 64bit 1909

- サクラエディタバージョン
```
サクラエディタ   v2.4.2.3414 32bit dev
(GitHash 06a3ac1fb027ce00b90df5fa5148f039f29f143c)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2021/2/1 00:10:40
```

**Comment by yoshinrt** [comment]
本 issue とは関係ない & 環境依存かもしれないのですが，sakura.ini を削除して sakura.exe を起動すると，何もメッセージ等を表示せず終了してしまうようです．

**Comment by k-kagari** [comment]
bisect してみました。 c5b4a0fad で挙動が変わっています。

**Comment by k-kagari** [comment]
https://github.com/sakura-editor/sakura/blob/10dda8eebc785423a778b2c14224497a6bbac93a/sakura_core/dlg/CDlgReplace.cpp#L238-L239
この行の実行後、m_strText が displa になることが確認できました。

https://github.com/sakura-editor/sakura/blob/10dda8eebc785423a778b2c14224497a6bbac93a/sakura_core/apiwrap/StdControl.cpp#L38-L43
ここで GetWindowTextW に渡している文字数が足りません。

**Comment by k-kagari** [comment]
検索文字列の問題については #1528 で修正できたと思います。もしできていなければ reopen していただければ…。
