### ISSUE TITLE
文字化け問題

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#155]
以下の文字列で、

無著 Asaṅga    , 310 - 390年頃

世親 Vasubandhu , 4th to 5th

陳那 Dignāga , 480年頃-540年頃

法称 Dharmakīrti    , 7th middle

寂護 Śāntarakṣita    , ?-787年頃

蓮華生 Padmasaṃbhava    , 8世紀後半

Śāntara・kṣita　
のように表示が文字化けする。内部コードは問題なし。
2.3.2.0で確認。

**Comment by KENCHjp** [comment]
ごめんなさい、誤爆です。
フォントを「メイリオ」にしたら大丈夫でした。

**Comment by KENCHjp** [comment]
MSゴシックとか明朝でやったら報告通りの動作だったので事象としてはあってると思います。
ただサロゲートペアとかは別途考慮が必要かなってはなしはでてましたが、
今回の事象とは関係ないのでいったんクローズしました。

**Comment by berryzplus** [comment]
あれ、reopenするつもりなかったのにreopenしてる・・・ので閉じます。
