### ISSUE TITLE
Windows10でタイムスタンプが意図せず更新される

### ISSUE THREAD

**Issue by tenkoh2** [sakura-editor/sakura#1551]
## 問題内容
Windows10でファイルを開いた際、ファイルを編集していないのにタイムスタンプがファイルを開いた時刻に更新されることがある

## 再現手順
Windows10上で、テキストファイルなどをダブルクリック、送る等の操作で開いた際、タイムスタンプが更新されることがある(100%ではない)。

## 再現頻度
体感で、50%以上の頻度で発生する。

## 問題のカテゴリ
- プログラムの動作上の問題
  - 正式リリース版

## 環境情報
- OS バージョン
Windows 10 Home 64bit

- サクラエディタバージョン
v2.4.1.2849 32bit (tag v2.4.1)

**Comment by berryzplus** [comment]
調査をしたいので設定ファイルを共有していただけますか？
履歴関連のセクションは削ってもらって大丈夫です。

予測では、排他ロックをかけた場合に更新が行われているのではないかと考えています。
予測が正しいとすると、最新exe(v2.4.1)でsakura.iniを作り直したら問題は解消されます。

**Comment by tenkoh2** [comment]
[
[sakura.zip](https://github.com/sakura-editor/sakura/files/6033938/sakura.zip)

](url)
設定ファイルを圧縮して添付致します。

**Comment by berryzplus** [comment]
ファイルありがとうございます。調査してみます。

**Comment by tenkoh2** [comment]
最新版でsakura.iniを削除し、作り直しましたが、タイムスタンプが意図せず更新される問題は継続して発生しています。

**Comment by berryzplus** [comment]
> 最新版でsakura.iniを削除し、作り直しましたが、タイムスタンプが意図せず更新される問題は継続して発生しています。

対策どころか調査もしてないので当然ですね。

プログラムソースコードを見た感じ、保存かファイル出力の操作をしない限り「更新日時」のタイムスタンプは更新されなさそうです。

ないと思いますが、タイムスタンプって更新日時ですよね？
※タイムスタンプには３種類あって、アクセス日時は書きこまなくても更新されます。

「ファイルアクセスをなかったことにする」趣旨のコードは組み込まれていないので、問題が「アクセス日時」のタイムスタンプが更新される、であれば「windowsの仕様なので諦めてください」になります。

もっとも、ファイル保存周りのソースコードが超汚いので、ぼくがコードを見誤ってる可能性はゼロじゃないです。

**Comment by tenkoh2** [comment]
> もっとも、ファイル保存周りのソースコードが超汚いので、ぼくがコードを見誤ってる可能性はゼロじゃないです。

確実に見誤っていると思います。


> ないと思いますが、タイムスタンプって更新日時ですよね？

さすがに、ここまで馬鹿にされるとは思っていませんで
した。
更新日時が更新されているから問題にしているに決まっ
ているでしょう？


> 対策どころか調査もしてないので当然ですね。

オープンソースのソフトウェアに対し、調査依頼するだ
けで、自ら調査しなかったことは謝罪します。
しかし、調査スキルがなくて利用しているだけの人間も
多数いるであろうコミュニティで、不具合かもしれない
事象を報告して、このような文句を言われるとは思って
いませんでした。

正直、問題が解決されないのなら、もうこのエディタを
使うことをあきらめて、ほかのエディタを使おうと思い
ます。

以上

**Comment by k-takata** [comment]
今回の件が当てはまるかどうかは知りませんが、アンチウイルスソフトのせいでタイムスタンプが勝手に更新されるという事例があったように思います。

**Comment by berryzplus** [comment]
なんで怒ってるのかまったく分からないです。

> > ないと思いますが、タイムスタンプって更新日時ですよね？
> 
> さすがに、ここまで馬鹿にされるとは思っていませんで
> した。

まぁ確かに調査結果の詳細を書かなかったのは、「書いても理解できんだろう」と思ったからなんですが、タイムスタンプが何を指しているか？は単なる事実確認のつもりでした。

事実確認したらいかんの？

**Comment by berryzplus** [comment]
> > もっとも、ファイル保存周りのソースコードが超汚いので、ぼくがコードを見誤ってる可能性はゼロじゃないです。
> 
> 確実に見誤っていると思います。

根拠があるなら追記しておいてほしいです。

どういう調査をして「ソースコードでは更新日時を触っていない」の結論に至ったかを書いていないのに、「確実に見誤っている」と判断したかが謎です。

自分の見解は「保存周りのソースコードは正しい」で「タイムスタンプが更新される理由は他にある」です。
何故「確実に」見誤っていると言えるか？の根拠があれば、提示しておいてほしいです。

そうでなければ、このコメントを書いた瞬間は
根拠もないのに「確実」とか言えちゃうレベルのザコだったということで、
バカにされてもしゃあなかったってことになります。
※注、馬鹿にする意図は一切ありませんでした。
　「馬鹿にされた」というコメントを見て、「は？何言ってんのコイツ」と思いましたが。

**Comment by tenkoh2** [comment]
> 根拠があるなら追記しておいてほしいです。

現に事象が発生しているのに、「根拠がない」と考えているのが理解できないです。

そもそも、「ファイルを開いた時点でタイムスタンプが更新される」と書いているのに、「保存周りのソースコードを見た」と言っている時点で見当違いです。日本語が理解できていますか？

> そうでなければ、このコメントを書いた瞬間は
> 根拠もないのに「確実」とか言えちゃうレベルのザコだったということで、
> バカにされてもしゃあなかったってことになります。

>>    対策どころか調査もしてないので当然ですね。

などと、人を侮辱するコメントを書いた人間が、何を言っているのですか？

**Comment by berryzplus** [comment]
再現できた人います？

**Comment by arigayas** [comment]
> テキストファイルなどをダブルクリック、送る等の操作

念のため質問です。
サクラエディタのインストーラーがファイルの右クリックメニューに追加する「SAKURA Editorで開く」も含まれていますか？

**Comment by tenkoh2** [comment]
> 再現できた人います？

確かに、再現性がないと調査する価値があんまりない・
・・というより、調査したくてもできませんね。


>     テキストファイルなどをダブルクリック、送る等の操作
> 
> 念のため質問です。
> サクラエディタのインストーラーがファイルの右クリックメニューに追加する「SAKURA Editorで開く」も含まれていますか？

含まれています。
あと、関係あるかわかりませんが、ファイル履歴や検索
語の履歴が保存されていないことがあります。

あと、念のための補足ですが、Windows7 ＋ サクラエデ
ィタの環境では、このような事象が起こったことはあり
ませんでした。

アンチウィルスソフトの話が出てきていましたが、
Windows7でもWindows10でもトレンドマイクロの
ウィルスバスタークラウドを使っています。

サクラエディタのソースコードを読んだことがないので
(というより、自分で事象の調査をしていないので)単な
る予測になってしまうのですが、

サクラエディタのファイルオープン周りの操作 ＋ Windows10のシステムコール ＋ NTFS ＋ α(環境依存の何か)

で、事象が起こっているのではないかと思います。
この予測が当たっているとなると、サクラエディタのソ
ースコードだけでなく、OS やファイルシステムの仕様、
それに環境依存の何かについての調査もしなければなら
ず、再現性の乏しい事象に対する調査としては、労力が
かかりすぎる気がします。

他の方の環境で再現するかはわかりませんが、自分の環
境では確実に再現するので、もう調査はあきらめて、ほ
かのテキストエディタに移行しようかと思っています。

お騒がせしました。

**Comment by arigayas** [comment]
トレンドマイクロのウイルスバスタークラウドをWindows付属のWindows Defenderに切り替えても
再現するのかどうか気になりましたが調査はしないということでしょうか？

_ウイルスバスターって過去にいろいろあった覚えがあるので・・・。_

ちなみに私の環境(Windows10 Pro + Windows Defender)では再現していないようです。

**Comment by tenkoh2** [comment]
> トレンドマイクロのウイルスバスタークラウドをWindows付属のWindows Defenderに切り替えても
> 再現するのかどうか気になりましたが調査はしないということでしょうか？

お騒がせした責任もあるので、調査はしようと思います。

結果が出たら、お知らせ致します。

**Comment by berryzplus** [comment]
調査してない怪しげポイント
* windows 10 の Home Edition が原因ではないか？
* ダブルクリックの関連付けか送るメニューのコマンドラインがおかしくなっていないか？
* 問題が発生するファイルの格納先ストレージが標準的なNTFSフォーマットのSSDではないのではないか？
* ファイル名が8.3形式に収まらないのではないか？
* パス解析に使用しているシェル関数の隠し仕様によりタイムスタンプが変更されているのではないか？

**Comment by usagisita** [comment]
自分は普段osdn側を見ていないのでアレなんですけど、これじゃないんですかね。
https://ja.osdn.net/projects/sakura-editor/forums/34071/42664/
こちらの推測・観察結果ではファイルを開くと「上書き禁止検出」のために「書き込み可能属性」を付けて「書き込んだ振り」をします。
その時「Acronis True Image 2018 の Active Protection」によりファイルのタイムスタンプが更新されるようだ、となっています。
似たような現象が、他のアンチウィルス系ソフトで発生していても、何ら不思議ではありません。
以上、情報共有はしておきたいと思います。よろしくお願いします。

**Comment by tenkoh2** [comment]
・windows 10 の Home Edition が原因ではないか？
  使用しているOS はWindows10 Home であり、Home Edition に問
  題がある場合、影響をもろに受けます。

・ダブルクリックの関連付けか送るメニューのコマンドラインがおかしくなっていないか？
  ダブルクリックの関連付けに関しては、どこを調べればよいかわ
  かりませんでした。レジストリの値とかを見ればよいですか？

  送るメニュー
  リンク先		"C:\Program Files (x86)\sakura\sakura.exe"
  作業フォルダ		"C:\Program Files (x86)\sakura"

・問題が発生するファイルの格納先ストレージが標準的なNTFSフォーマットのSSDではないのではないか？
  ファイルシステムはNTFS ですが、SSD ではなく、ノートパソコ
  ン内蔵のHDD です。
  サクラエディタではSSD が標準となっているのでしょうか？

・ファイル名が8.3形式に収まらないのではないか？
  確かに、8.3形式に収まらないファイルを多数操作していました。
  逆に、8.3形式に収まるファイルで現象が発生していたかは記憶
  が不確かですので、確かめてみます。

・パス解析に使用しているシェル関数の隠し仕様によりタイムスタンプが変更されているのではないか？
  これに関しても、調査の方法がわかりませんでした。

なお、以前に話の出ていたアンチウィルスソフトの件ですが、
Windows 付属のWindows Defender に切り替えても再現しました。

Acronis True Image 2020が私の環境にインストールされているの
で、これが原因かもしれません。
OFF にして試してみます。

**Comment by tenkoh2** [comment]
Acronis True Image 2020をOFFにして試してみたところ、現時点でタイムスタンプの意図しない更新は起きていません。
どうやらこれが原因で間違いないようです。

別サイトとはいえ、既出の問題とは知らず、お騒がせ致しました。

**Comment by arigayas** [comment]
サクラエディタとは関係が無かったみたいなので
この issue の Close をお願いします。
