### ISSUE TITLE
sakura_lang_en_US.dll のバージョンにGitHash が含まれない

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#157]
sakura_lang_en_US.dll にGitHash が含まれない

https://github.com/sakura-editor/sakura/blob/53b1d94a87cfd561ac11d292e92970baaade5de8/sakura_lang_en_US/sakura_lang_rc.rc#L5-L11

https://github.com/sakura-editor/sakura/blob/53b1d94a87cfd561ac11d292e92970baaade5de8/sakura_core/sakura_rc.rc#L5-L12

**Comment by m-tmatma** [comment]
途中で登録されてしまったので、修正しました。

**Comment by m-tmatma** [comment]
#159 の PR 作成した。

**Comment by kobake** [comment]
ご対応ありがとうございました！
