### ISSUE TITLE
CNativeT に auto_sprintf の機能を持たせたい

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#160]
CNativeT に auto_sprintf の機能を持たせたい

現状では auto_sprintf してから CNativeT.AppendString しているが、
CNativeT に auto_sprintf 相当の機能があればバッファの管理、初期化しなくていいし
コードが見やすくなる。

#147 のような初期化漏れに伴う不具合の発生も未然に防げる

**Comment by kobake** [comment]
https://github.com/sakura-editor/management-forum/issues/4
これの結論にもよるかな、とも思ってましたがこれの結論待たずに先に実装入れるコストはほぼ無い（もう実装しちゃってるものあるので）取り入れちゃっても良いかも、というのが今の時点の所感です。

**Comment by m-tmatma** [comment]
#303 で対応済みなのでクローズ
