### ISSUE TITLE
カーソルが先頭行にある状態からさらに PageUp キーを押すと縦線が残る

### ISSUE THREAD

**Issue by suconbu** [sakura-editor/sakura#1617]
## 問題内容
カーソルが先頭行にある状態からさらに PageUp キーを押すと縦線が残ってしまいます。
※ https://github.com/sakura-editor/sakura/pull/1616 の動作確認中に偶然発見しました。

![sakura_vline_bug](https://user-images.githubusercontent.com/11252784/113733207-37ca5580-9735-11eb-8dfa-42a081b34f10.gif)

手持ちのいくつかのバージョンで発生状況を見た結果です。
* ee8234f (2020-05-30) → 発生せず
* 33988ea (2020-10-31) → 発生
* 4a1e2e2 (2021-02-17) → 発生

## 再現手順
1. サクラエディタを起動する。
2. エディタに数文字入力する、または任意のテキストファイルを開く。
3. タイプ別設定で「カーソル位置縦線」を有効にする。
4. カーソルが先頭行にある状態で PageUp を押してからカーソルを左か右に移動する。

## 再現頻度
100%

## 問題のカテゴリ
- プログラムの動作上の問題

## 環境情報
- OS バージョン
Windows 10 Home 64bit
- サクラエディタバージョン
サクラエディタ   v2.4.2.3214 64bit dev Alpha Version
(GitHash 33988ea3c54bc94d4494d214d02be14b4f9a514c)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V_A641916 WPR WIN601/I800/C000/N601
      Last Modified: 2020/10/31 17:49:59

**Comment by beru** [comment]
SHA-1 | Date | 再現するか
-------|-------|-------
388a73620aa904ff0b2257e335698734828ea1a4 | 2020/10/29 | する
2d2f3cb9de8c4bd8ff476b306ae6c5af80273d03 | 2020/09/06 | する
e34c4aa7316df7bc90d714354f61dc74b9a40570 | 2020/09/09 | しない
d3a1a8e74d473ea0c016bb559964f5d5e9596ac4 | 2020/08/02 | しない
40147238dc12b2490466de0dfee78006c8e73cba | 2019/09/02 | しない

という事で自分が行った #1320 の変更が原因で発生した不具合ですね。

**Comment by beru** [comment]
#1619 で対応したのでCloseします。
