### ISSUE TITLE
「SAKURA　EDITORでGrep」が機能しません。

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1626]
## 問題内容

転記します。
https://github.com/sakura-editor/sakura/pull/1624#commitcomment-49502891
> Windows10上で、右クリックで、「SAKURA　EDITORでGrep」を押すと常駐するだけでGrepウィンドウが開きません。私だけでしょうか。
> ※前回コメントからソフトウェア挙動変化を認めたため、前回コメントを削除の上、コメントを再度記述。
> 前々のマージ版ではGrepウィンドウが開きます。この挙動が正しい挙動と思っていたのですが。
> 
> ちなみに検証したのは以下バージョン
> サクラエディタ v2.4.2.3668 64bit dev Alpha Version
> (GitHash e80c6e9ea2b5c74d6371b0bffa40552904f3bca1)
> (GitURL https://github.com/sakura-editor/sakura.git)

@oooonduke さん、ありがとうございます。

## 再現頻度

不明です。

## 問題のカテゴリ
- プログラムの動作上の問題
  - Appveyor ビルド版

## 環境情報
```
  Compile Info: V_A641916 WPR WIN601/I800/C000/N601
  Last Modified: 2021/4/14 11:00:58
```

**Comment by sanomari** [comment]
これって、PRのビルドに対するコメントなんじゃないでしょうか？

「SAKURA EDITORでGrep」ってのがどんな機能か知らないので、修正と関係あるか判断つきませんけれども。

**Comment by berryzplus** [comment]
「SAKURA EDITORでGrep」は、Windowsエクスプローラーに「サクラエディタのコマンドライン」を登録しておくことができるインストーラーの機能です。コマンドラインパラメーターの解釈方法を変えるような変更をすると影響する可能性があります。 #1624 で行っている変更とは関係ありません。

**Comment by sanomari** [comment]
> 「SAKURA EDITORでGrep」は、Windowsエクスプローラーに「サクラエディタのコマンドライン」を登録しておくことができるインストーラーの機能です。コマンドラインパラメーターの解釈方法を変えるような変更をすると影響する可能性があります。 #1624 で行っている変更とは関係ありません。

本当ですか？

なんとなく「検証はしてない」からissue立てたように見えます。

**Comment by sanomari** [comment]
試してみました。

|build|結果|
|-----|----|
|3668|NG|
|3667|NG|
|3665|NG|
|3660|NG|
|[3656](https://ci.appveyor.com/project/sakuraeditor/sakura/builds/38646072)|NG|
|3654|OK|
|3630|OK|

原因は #1618 です。
x64対応準備でCMemoryを触ったのがマズかったみたい。
コマンドラインとCMemoryが頭の中で結びつかなくて、不思議な感じがします。
