### ISSUE TITLE
文字コードを選択して開き直すの実行直後ステータスバーの文字コード名が更新されない

### ISSUE THREAD

**Issue by usagisita** [sakura-editor/sakura#1637]
## 問題内容
タイトルの通りです。
特定の「(文字コード)で開き直す」を実行した直後、ステータスバーの文字コード名が古いままになっています。

## 再現手順
UTF-8でファイルを開きます。
ステータスバーの表示が「UTF-8」であるのを確認します。
「SJISで開き直す」を実行します。
ステータスバーの表示が「SJIS」に更新されるはずがそのままです。
カーソル移動などをすると、更新され「SJIS」に変更されます。

## 再現頻度
最近(一カ月以内くらい)のバージョンでは100%で発生、再現します。
x64/win32はおそらく無関係です。

## 問題のカテゴリ
- プログラムの動作上の問題

**Comment by usagisita** [comment]
開き直すだけでなく、普通にファイルを開いた直後も文字コードが違うなら同じかもしれません。

**Comment by suconbu** [comment]
原因調査に挑戦してみましたが、現象発生時でも updatedRect に設定されている矩形範囲は正しそうで、なぜ表示が更新されないのか分かりませんでした。。
仮で InvalidateRect の第2引数を常に NULL またはクライアント領域全体を指定すると一応現象起きなくなりますね。
https://github.com/sakura-editor/sakura/blob/b96e3228e3470a2a4fbab2c1ea5829ebd77a7c06/sakura_core/view/CCaret.cpp#L875

**Comment by berryzplus** [comment]
> 原因調査に挑戦してみましたが、現象発生時でも updatedRect に設定されている矩形範囲は正しそうで、なぜ表示が更新されないのか分かりませんでした。。

ステータスバーも描画領域に含まれていますか？
編集領域じゃないので、普通に考えて更新対象から漏れてると思います。

> 仮で InvalidateRect の第2引数を常に NULL またはクライアント領域全体を指定すると一応現象起きなくなりますね。

第2引数にNULLを渡すのは、クライアント領域全域を指定するのと等価です。

更新対象領域を算出するのがめんどくさくて全域を再描画するコードばかりになっている結果、
必要のない再描画が発生して「ちらつき」が起きるようになっています。

**Comment by berryzplus** [comment]
ちがうのかな？CCaretの更新領域ってステータスバーも含む？

**Comment by berryzplus** [comment]
メモ： d87aec5 は #1601 の一部みたいです。

**Comment by berryzplus** [comment]
結局 `index++` × 7件の警告を対処しなかったのが問題のような・・・
👆ステータスバーは領域ごとに枠で区切られ番号が付いています。
　index++という書き方はステータスバーを必ず「全域更新」する仕様を前提にしています。
　更新領域をバラすと「変わったところだけ更新」が可能になります。
　描画前後で値が変わる場合に「ちらつき」を感じるのはよほど目のいい人だけです。
　意味なく表示がちらつくわけでなく、値が変わるのだから。

**Comment by beru** [comment]
> 結局 `index++` × 7件の警告を対処しなかったのが問題のような・・・
> 👆ステータスバーは領域ごとに枠で区切られ番号が付いています。
> 　index++という書き方はステータスバーを必ず「全域更新」する仕様を前提にしています。
> 　更新領域をバラすと「変わったところだけ更新」が可能になります。
> 　描画前後で値が変わる場合に「ちらつき」を感じるのはよほど目のいい人だけです。
> 　意味なく表示がちらつくわけでなく、値が変わるのだから。

`index++` という書き方はちょと横着をしていると思いますね。enum を使ってきちんとステータスバーの各パート毎に識別子を用意する方がはっきりしたコードになると思います。識別子用意するのが手間ですけど。

なお `CCaret::ShowCaretPosInfo` の実装では `setStatusText` に代入するラムダ式において `CMainStatusBar::SetStatusText` を呼び出していますが、そこで色々判定をして「変わったところだけ更新」の処理を行っています。更新というのは `SB_SETTEXT` メッセージを呼び出す処理です。更新したパートについて別途 `SB_GETRECT` メッセージを呼び出して取得した RECT 領域を UNION して複数のパートが同時に更新された場合にまとまったRECT領域を用意し、そして後から `InvalidateRect` をそのRECT領域に対して呼び出す事で、複数のパートが同時に変更される場合に個別に描画ではなくまとめて描画が行われるようにしています。

ステータスバーの表示の為だけにややこしい実装になっていますが、こんな事をしているのも標準コントロールのステータスバーのパフォーマンスが低いからです。本来はこんな対策をアプリ開発者が入れるのはちょっと脇道に反れているおかしな事かもしれません。あともし本当に表示のパフォーマンスを良くしたいなら標準コントロールを使うべきではないと思うのですが、その手間を惜しんでます。

ちらつきに関してはケースバイケースなので説明しづらいですが、対策を入れる前は REC の部分は結構ちらつきが目立っていた気がします。そこだけオーナードローで描画のタイミングが異なるからですかね？

**Comment by beru** [comment]
> ちがうのかな？CCaretの更新領域ってステータスバーも含む？

確かに `CCaret` というクラス名はカーソルやキャレットと呼ばれているものの実装のはずなのになんでウィンドウ下部に位置するステータスバーの描画に影響が？って思ってしまいますよね。。

問題の処理のメソッド名が `CCaret::ShowCaretPosInfo` ですがそこの関数コメントには「キャレットの行桁位置およびステータスバーの状態表示の更新」と書かれています。まぁこの処理って `CCaret` クラスのメソッドとして実装するんじゃなくて後で追加するイベントリスナーとして実装する方が良いのかもしれないですね。

**Comment by beru** [comment]
なおちらつきの防止については `CCaret::ShowCaretPosInfo` 以下の処理で色々入れた対策より、ウィンドウ作成時に拡張スタイルに `WS_EX_COMPOSITED` を指定した事の方が効いているような気がします。コードが複雑になるし不具合も入りやすくなるので余計な処理は入れないに越したことは無いという事かもしれないですね…。

**Comment by beru** [comment]
#1642 で `UpdateWindow` 関数の呼び出しを追加する事で `WM_PAINT` メッセージがステータスバーのウィンドウに送られるようにして問題を解消しました。という事でCloseします。もしまだ問題が残ってたらReopenしてください。

**Comment by suconbu** [comment]
対応ありがとうございました。
InvalidateRect から WM_PAINT が出るはず、と思い込んでいました。恐れ入ります😌

**Comment by beru** [comment]
自分も思い込んでました。よくわからないのはキー押しでカーソル移動の場合だと同じ経路の処理でもステータスバーの表示が更新されていた事です。
