### ISSUE TITLE
特定のテキストが読み込まれない

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#1641]
## 問題内容

ファイルを開いても本来表示されるはずの内容が何も表示されない。

https://egg.5ch.net/test/read.cgi/software/1587603412/297

の投稿で初めて知りました。

https://egg.5ch.net/test/read.cgi/software/1587603412/301

の投稿に具体的に確認しやすい内容が書かれていました。

```
----------ここから
A,B,S
C2D =
D2C =
NZ =
Z = [
F = l
----------ここまで (改行は CRLF) 
```

上記の内容を保存したテキストファイルを作って確かに再現する事を確認しました。

[test.txt](https://github.com/sakura-editor/sakura/files/6359543/test.txt)

## 再現手順

ファイルを開く。

## 再現頻度

常に再現

## 問題のカテゴリ

- プログラムの動作上の問題

## 環境情報
- OS バージョン
![image](https://user-images.githubusercontent.com/1131125/115743885-086e4680-a3cd-11eb-8c4a-58e37347bc02.png)

- サクラエディタバージョン
```
サクラエディタ   v2.4.2.0 64bit DEBUG dev Alpha Version
(GitHash d3a1a8e74d473ea0c016bb559964f5d5e9596ac4)
(GitURL git@github.com:sakura-editor/sakura.git)

      Compile Info: V_A641928 WPD WIN601/I800/C000/N601
      Last Modified: 2021/4/23 00:35:41
```

**Comment by beru** [comment]
SHA-1 | OK/NG
-------|------
9713af2ebcfa2921846a1b99aed7b63c96b559e2 | NG
f62f20957ce0c67eb7b3c017e37bfd16c46b1f76 | NG
ab89e267eee28eb589dd94b2aa0e6a160543bbde | OK
4a64e53f398ca112a6b25efa9e45e36ea725e807 | OK

という事で #1618 の変更が関係していそうです。

**Comment by usagisita** [comment]
#1638 が一応そのバグの修正です。
タイトルが分かりにくくてすみません。

**Comment by beru** [comment]
https://github.com/sakura-editor/sakura/blob/9713af2ebcfa2921846a1b99aed7b63c96b559e2/sakura_core/mem/CMemory.cpp#L227-L239

`CMemory::AppendRawData` の実装の判定に不具合がある事を確認しました。

変数 | 値
-----|----
m_nDataBufSize | 8
m_nRawLen |  0
nDataLen | 7

の場合にメモリ確保は行われませんが、メモリのコピーも行われません。

**Comment by beru** [comment]
> #1638 が一応そのバグの修正です。
> タイトルが分かりにくくてすみません。

作成ありがとうございます。今からレビューします。

タイトルが分かりにくいのではなく自分がPR一覧をきちんと確認していなかったんだと思います。

**Comment by beru** [comment]
#1638 が merge されたので close します。
