### ISSUE TITLE
appveyor の成果物にビルド番号を含めるか検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#165]
appveyor の成果物にビルド番号を含めるか検討する

https://github.com/sakura-editor/sakura/pull/114#issuecomment-397121879

```
ローカルでの区別しやすさを考えると
ビルド番号を含めてもいいかも
デメリットはダウンロードしたzip に対して自動で何かしたいときに邪魔になること
```

https://github.com/sakura-editor/sakura/pull/114#issuecomment-397156121

```
> ビルド番号を含めてもいいかも
これの判断は難しいところです。一旦別件として検討しましょう。

```

https://github.com/sakura-editor/sakura/issues/109#issuecomment-397490305

`既存の有名なプロダクトがどのような方針を採っているのか気になってます
`

**Comment by m-tmatma** [comment]
#177 の修正(d265094f695e44ed451a704f583eb9a66a293ac0) に添付のパッチを適用することで可能なのを確認

[build-number-version.patch.txt](https://github.com/sakura-editor/sakura/files/2130487/build-number-version.patch.txt)

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/187#issuecomment-400851184

> 余談ですが個人的にはやっぱり artifacts ZIPファイル名に githash または PR 番号（これは原理的に難しそうな気がする）が含まれているとレビュー都合的にありがたいなーと思っています。

どちらも可能だと思います。

https://github.com/sakura-editor/sakura/issues/167#issuecomment-400837944


を見ていただくと

環境変数で githash は APPVEYOR_PULL_REQUEST_HEAD_COMMIT あるいは APPVEYOR_REPO_COMMIT で取れますし、 PR 番号は APPVEYOR_PULL_REQUEST_NUMBER で取れます。

**Comment by m-tmatma** [comment]
> 環境変数で githash は APPVEYOR_PULL_REQUEST_HEAD_COMMIT あるいは APPVEYOR_REPO_COMMIT で取れますし、 PR 番号は APPVEYOR_PULL_REQUEST_NUMBER で取れます。

上記の環境変数を参照して以下の変数を設定している箇所に追加すればいいです。

https://github.com/sakura-editor/sakura/blob/cb05e16d3084ef24fbf2b3c726ac14180d7e92eb/zipArtifacts.bat#L13

ZIP ファイル名だけ変えたければ以下です。

https://github.com/sakura-editor/sakura/blob/cb05e16d3084ef24fbf2b3c726ac14180d7e92eb/zipArtifacts.bat#L18

**Comment by kobake** [comment]
PR 番号含められるの良いですね。BASENAME, OUTFILE 両方変わっているのが個人的には好ましいです。

**Comment by m-tmatma** [comment]
#199 で対応
