### ISSUE TITLE
先頭行でPageUp・末尾行でPageDownした後のカーソル移動で下線が残る

### ISSUE THREAD

**Issue by kazasaku** [sakura-editor/sakura#1650]
## 問題内容
PageUpキーで先頭行・PageDownキーで末尾行までスクロールした状態で再度そのキーを押し、
それから上下の矢印キーで行を移動したときにカーソルの行位置を示す下線が先頭・末尾行に残ります。

## 再現手順
1. 適当な文書を開く、あるいは作成する
2. PageUpキーで行番号が1行目になっているところ（先頭行）に戻る
3. 再度PageUpキーを押す（既に先頭行にいるのでスクロールしません）
4. 下矢印キーで２行目に移動する

上記手順では、下線が１行目と２行目に表示されます。

## 再現頻度
おそらく常に再現可能です。
一旦矢印キーで左右に移動してから上下移動すれば回避できます。

## 問題のカテゴリ
- プログラムの動作上の問題
  - Appveyor ビルド版

## 環境情報
- OS：Windows 10 Pro 64bit 20H2
- サクラエディタ：
```
サクラエディタ   v2.4.2.3710 32bit dev
(GitHash 6f297b47bcd86344a79cbd1a3e62b1c2da7139d9)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2021/4/26 12:30:56
```

## スクリーンショット
上記手順を再現したときの画面表示。

![スクリーンショット 2021-04-29 150538](https://user-images.githubusercontent.com/67105596/116508580-a47fdc80-a8fc-11eb-9dc2-b671ede10fbe.png)

**Comment by beru** [comment]
自分が行った #1320 の変更以降でこの問題が発生する事を確認しました。

**Comment by beru** [comment]
#1652 を Merge したので Close します。

**Comment by kazasaku** [comment]
ご対応ありがとうございました。
