### ISSUE TITLE
appveyor の成果物をダウンロードしてエクスプローラで解凍して実行すると警告が出る

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#166]
appveyor の成果物をダウンロードしてエクスプローラで解凍して実行すると警告が出る

https://github.com/sakura-editor/sakura/pull/144#issuecomment-399287675

`まだ公知じゃないから、インストーラー動かすとWindows Defenderで警告出ちゃう。`

https://github.com/sakura-editor/sakura/pull/144#issuecomment-399587691

```
でますね。
仕様じゃないっすかね。ネット(ファイル共有も含む)からダウンロードした実行バイナリって警告でますよね。
```

https://github.com/sakura-editor/sakura/pull/144#issuecomment-399600956

```
zip版やインストーラをダウンロードしたら、解凍or実行する前に「許可する」の
チェックを入れるというのを、インストール手順書か何かに書いておくのがよいと思います。
zipでそれをせずに解凍してしまうと、解凍後のファイルもすべてダウンロードしたファイル
として扱われます。

```

https://github.com/sakura-editor/sakura/pull/144#issuecomment-399612488

`エクスプローラーで解凍やドラッグドロップするとフラグが付いたままですが、
ファイラー等でzipを解凍するとこのフラグが消えてるファイルができあがります。
`

**Comment by KENCHjp** [comment]
これ仕様通りでもいいような。

http://www.officedaytime.com/tips/codesigning.html

**Comment by m-tmatma** [comment]
> このIssue仕様通りでもいいような。

ドキュメントに回避策を書くとかを想定しています。

**Comment by KENCHjp** [comment]
>ドキュメントに回避策を書くとかを想定しています。

なるほど。ヘルプのインストール/アンインストールにはその旨記載がないですね。
ただ、インストールしないとヘルプは見られないから、以前OSDN側で消しちゃいましたけど、
インストール方法を掲載するスペースがあるので、そっちにヘルプの内容抜粋と、
このダウンロードした実行ファイルに対する警告が表示される旨記載しましょうか。

**Comment by KENCHjp** [comment]
@kobake さん

デジタル著名はもう企業以外には振り出されなさそうなもしくはえらい金がかかるようなことが、散見されます。
上のリンクの中のさらにリンクに解説があるのをみつけました。
http://www.officedaytime.com/tips/codesigning2.html

**Comment by kobake** [comment]
僕でしたら住所と名前さらすの抵抗ないんですけど、お金かかるのはウ～ン・・・・・・数千円程度だったら出しても良かったんですけど・・・・・・この額は・・・・・・・(´Д｀)

**Comment by KENCHjp** [comment]
http://www.atmarkit.co.jp/fwin2k/win2ktips/647freeca/freeca01.html

これがOSSに使えるのかしりませんが、一応無料のデジタル証明書発行するところがあるようです。
OSS用のデジタル証明書どっかで無料で発行してくれるところがあるのかも。。。

**Comment by kobake** [comment]
おお？探せば可能性ありそうな気もしてきました。時間のあるときにでも漁ってみます

**Comment by kobake** [comment]
> そして著名しても、警告は消えないって落ちが・・・

![](https://user-images.githubusercontent.com/39618965/41752275-78f4a068-7601-11e8-88d0-b6a2676f2a1f.PNG)

この画像を見る限りは「不明な発行元」とあるので、発行元が明示されている＝証明済みの発行者情報が設定されている状態であれば警告出ないのかなーと想像していましたが、どうなんですかね

**Comment by k-takata** [comment]
Vimでも同じようにコード署名に対する要望があるのですが、以前探した限りではOSSで無料で使えるような便利サービスは見当たらなかったので放置ですね。

(WebサイトのHTTPS化と混同している人も結構いましたが、こちらはOSDNとかGitHub pagesが対応してくれたので、今後は問題にならないはず。)

**Comment by berryzplus** [comment]
vimがやらないのにsakuraがやるのも変な気が・・・。
windows発のアプリとしてできることの1つ
と捉えられなくもないので「前向きに検討」に異論はなしです。

**Comment by m-tmatma** [comment]
#169 でドキュメント追加したので閉じる。
