### ISSUE TITLE
バージョン情報で リンクを追加する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#167]
### appveyor のリンク

https://github.com/sakura-editor/sakura/pull/158#issuecomment-399489402

`ハッシュが URL になっているとバイナリとソースコードの対応付けがスムーズにできて、ハッシュを表示する意味が増すと考えましたがいかがでしょうか。`

https://github.com/sakura-editor/sakura/pull/158#issuecomment-399616288

> ハッシュが URL になっているとバイナリとソースコードの対応付けがスムーズにできて、ハッシュを表示する意味が増すと考えましたがいかがでしょうか。

ハッシュに GitHub へのリンクをつけるのは難しいかもしれませんが、
appveyor へのリンクなら可能かもしれません。

以下の環境変数を使って

APPVEYOR_URL
APPVEYOR_REPO_NAME
APPVEYOR_BUILD_VERSION

`%APPVEYOR_URL%/%APPVEYOR_REPO_NAME%/build/%APPVEYOR_BUILD_VERSION%`
とすればいいと思います。

### GitHub のリンク

https://github.com/sakura-editor/sakura/issues/167#issuecomment-400480917
https://github.com/sakura-editor/sakura/issues/167#issuecomment-400535200

仕様案

- リンクは Appveyor ビルドの場合だけつける。
- タグかどうかで絞り込みはしない。
- github のurl はorigin のURL を元に算出する。
- リンクのテキストはハッシュ値とする。
- PR でない場合は、`https://github.com/sakura-editor/sakura/commit/aa17efb3ae227cd4fd320d3d685b98d0d5def7a2`  のような URL にする。
- PR の場合は PR の HEAD 用の hash と ターゲットブランチにマージしたときのハッシュの URL を両方指定できるようにする。
- PR の HEAD 用 の URL は以下の形式とする。
`https://github.com/sakura-editor/sakura/pull/180/commits/6aef9c937526f122092661e7dd818adcc5122530` のような URL にする。
- PR の場合でターゲットブランチにマージしたときのハッシュの URLはPR でない場合と同様
- PR の場合と PR ではない場合の違いは pull/xxx が入るという点と commits と commit となる点
- APPVEYOR_PULL_REQUEST_NUMBER の環境変数で Pull Request の番号と Pull Request かどうかを取得できる

**Comment by m-tmatma** [comment]
Appveyor  の該当ビルドのサイトから 対応する GivHub のコミットへ辿れるので目的は達成できると思います

**Comment by m-tmatma** [comment]
#177 で対応

**Comment by ds14050** [comment]
誘いには乗りませんか。クールですね。それは第２の理由で、第１の理由は github.com へのリンクばっかりいくつもいらないと言われてしまうのを恐れて、とりあえず口を出してみた、です。

便乗して質問を許してください。こういうリンクを生成してはいけない理由がありましたら教えてください。この 197...3c7 はバージョン情報からコピーしました。

    https://github.com/sakura-editor/sakura/tree/19711f8a706f1ab5da2841e510ff931b27c203c7

**Comment by m-tmatma** [comment]
> 便乗して質問を許してください。こういうリンクを生成してはいけない理由がありましたら教えてください。この 197...3c7 はバージョン情報からコピーしました。

https://github.com/sakura-editor/sakura/pull/158#issuecomment-399584133 にも書きましたが、

- 単にコミットハッシュから URL を生成した場合だと push していないコミットや
Clone したリポジトリに対してリンクが無効になること
- appveyor のリンクをつければ、該当のコミットへのリンクに辿れること
- コミットハッシュだけだと同じコミットハッシュに対して何度もビルドしている場合に GitHub のサイトに飛ぶよりも該当の appveyor のビルドに対して飛ぶほうが有益

だからです。

**Comment by ds14050** [comment]
失礼しました！ ペースについていけていません。めげずに追いかけます。

**Comment by m-tmatma** [comment]
@ds14050 さん

よかったら、#177 のレビューお願いします。

**Comment by kobake** [comment]
この PR はマージされることは考えていない想定ですか？（タイトルに「検討する」とあるので）

マージされたくない PR についてはタイトル先頭に `[WIP] ` 付けてもらえると誤マージ防げます。

**Comment by kobake** [comment]
あ、すみません、PR と Issue 見間違えました。忘れてください。

**Comment by m-tmatma** [comment]
タイトル変えました。

**Comment by ds14050** [comment]
git を触った経験がほぼないので、間違いを指摘してもらうことに期待しつつ自分でまとめてみます。

    https://github.com/sakura-editor/sakura/tree/19711f8a706f1ab5da2841e510ff931b27c203c7

こういう、バージョン情報の GitHash に基づいたリンクにアクセスした場合に起こることは……

* 1. 公式リポジトリにコミットオブジェクトが存在せず、404 Not Found が返ってくる。
* 2. コミット時点のソースツリーが表示される。

1 の原因は……

* 1-1. 個人フォークに基づく野良ビルドであった。
* 1-2. 公式リポジトリの PR、ブランチに属するコミットだったが、master にマージされる前に消えてしまった。

2 の場合に考えられることは……

* 2-1. master、ブランチ、タグに連なるコミットである。
* 2-2. PR を構成するコミットである。
* 2-3. まだ削除されていない orphan で、いずれ 1-2 になる。

--------

ソースコードに簡単にアクセスする機能が欲しいのは、バグっぽい挙動を見つけたときにその根拠を指し示す先として利用したいから。サクラエディタに限らず OSS ならそういうことしませんか？ 一番アクセスしやすい master の最新版がその目的に使えないのがいつも面倒。

ビルド単位での差異を気にしたことがないので、「同じコミットハッシュに対して何度もビルドしている場合に GitHub のサイトに飛ぶよりも該当の appveyor のビルドに対して飛ぶほうが有益」な理由がわからない。ビルドが自動化されているならなおのこと、気にするべきどんな差異が生じるだろうか。そしてそれは利用者(※)が気にかける差異だろうか。※GitHub でソースコードを参照するのはかなり普通ではない利用者かもしれないが……

リンクが切れていることそのものが重要な意味を持っていると思う(1-1, 1-2)。そして、リリースされたバイナリでリンクが切れていることはないはず。

2-1 で他のブランチではなく master に属することを確かめる(できれば Web 上の)簡単な方法がないとしたらちょっと微妙(でもちょっとだけ)。

AppVeyor のリンクはアーティファクトが削除されるまでの時限式ではないだろうか。

--------

根本的な認識違いがなければ、上記の理由で「ハッシュに GitHub へのリンクをつけるのは難しい」とは考えていません。(あ、Issue のタイトル変わってる)

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/177#issuecomment-399767158

で  @ds14050 さんは以下のようにコメントしています。

```
APPVEYOR_BUILD_URL にアクセスしてみました。「Project not found or access denied.」と表示されました。
```


> リンクが切れていることそのものが重要な意味を持っていると思う(1-1, 1-2)。

リンクがあってクリックしてリンクが切れていたら、なぜリンクが切れているか深いことは
考えずに @ds14050 さんが最初に思ったように「あ、バグだ」、と捉えると思います。

GitHub よりも appveyor のリンクのほうがいいと思った理由は
Clone であってもappveyor でビルドしたバイナリだとリンク切れにならない、
(appveyor 以外でビルドした場合にはリンク自体表示されない)
appveyor のリンク先から容易に GitHub のソースコードのリンクを辿れるから。

> GitHub のサイトに飛ぶよりも該当の appveyor のビルドに対して飛ぶほうが有益」な理由がわからない。
> AppVeyor のリンクはアーティファクトが削除されるまでの時限式ではないだろうか。

これは、"Artifacts" に対するものと考えています。(成果物の ZIPファイル)
https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy

だからリンク自体は有効だと考えています。

ただ、Artifacts が利用できなくなれば、ユーザーからバグ報告を受けてその時の
Artifacts を取得しようとしても、開発側では再取得できなくなります。
その点で有効性は下がると思います。

> ※GitHub でソースコードを参照するのはかなり普通ではない利用者かもしれないが……

GitHub のソースコードを参照したいというユーザーであればおそらく commit Hash から
GitHub の URL を割り出すことは可能だと思います。


コミットの特定の場所を参照したいのならもローカルに clone した上で
https://visualstudio.github.com/ のプラグインをインストールしておけば
Visaul Studio で permalink を取得することも容易にできます。

ソースコードで右クリックしてメニューから GitHub → "Copy link to Clipboard" を
やれば permalink をクリップボードに取得できます。

単に commit Hash を参照したいだけなら、GitHub に書くときに commit Hash を
貼り付ければいい。

ビルド番号さえわかれば、appveyor の URL は見つけられます。

**appveyor の URL に関しても、GitHub の URL に関しても要らないような気がしてきました。**

**Comment by ds14050** [comment]
切れたリンクはバグに見えるのでなんとしても表示したくないわけですね。その点で AppVeyor の方が有効範囲が広く永続する(？)、と。

m-tmatma さんとは AppVeyer の名前が出てくる時点でスタンスの違いがあると感じていまして、「GitHub の URL を割り出す」ですとか「clone した上で……プラグインをインストールしておけば Visaul Studio で permalink を取得することも容易」などもそうですが、自分の
* 怠惰な利用者の立場で、
* リリースされた最新版の EXE をダウンロードする立場で、
* github.com の master を参照するのと同じかより簡単な方法で、
エディタの不可解な挙動の原因を探って指摘する手段として、対応するソースコードへのリンクが欲しい立場とはずれがあります。

開発者や自分であれこれする人にとっての利便性や有用性などこれっぽっちも考えていないんですね。その人達は自分で何とかするか、自分で何かをした結果としてその状況に直面しているわけだから、「Clone であってもappveyor でビルドしたバイナリだとリンク切れにならない」はメリットではありませんし、「リリースされたバイナリでリンクが切れていることはない」ことさえ正しければ github.com へのリンクの方がダイレクトでクリックが少なくて済むのが良いわけです。

繰り返しですが以下の理由で最低限どちらか、できれば GitHub へのリンクがあれば便利だという考えは変わっていません。バージョン情報の GitHash が飾りでないならやって悪いことはないと思います。どこのリポジトリのコミットオブジェクトを参照しているか判別してリンクにしないぐらいのことはできるといいですけども。

>ソースコードに簡単にアクセスする機能が欲しいのは、バグっぽい挙動を見つけたときにその根拠を指し示す先として利用したいから。サクラエディタに限らず OSS ならそういうことしませんか？ 一番アクセスしやすい master の最新版がその目的に使えないのがいつも面倒。

**Comment by kobake** [comment]
「両方載せる」で良いんじゃないですかね。

GitHash のリンクが無効になるパターンというのはほとんどが「野良ビルド」でしょうから、そこは我々が気にするところではありません。

そもそも一般ユーザは Artifacts からの直接取得ではなく正式リリース版を入手して利用するケースがほとんどかと思います。

**Comment by m-tmatma** [comment]
> github.com の master を参照するのと同じかより簡単な方法で、
> エディタの不可解な挙動の原因を探って指摘する手段として、対応するソースコードへのリンクが欲しい立場とはずれがあります。

例えば github で New issue を選んで githash を貼り付けて、preview すれば github のリンクを取れますし、

https://github.com/sakura-editor/sakura にアクセスして、xxxx commits にアクセスして
適用に hash を選んで、ハッシュの URL の部分をエディタで貼り付ければ目的は達成できます。

> エディタの不可解な挙動の原因を探って指摘する手段として、対応するソースコード
> へのリンクが欲しい立場とはずれがあります。

「エディタの不可解な挙動の原因を探って」というのであればおそらくローカルに git clone して、ビルドして、デバッグ実行するだろうし、

> 開発者や自分であれこれする人にとっての利便性や有用性などこれっぽっちも考えていないんですね。

開発者や自分であれこれする人にとって、git clone するのや上記の作業も特に手間ではないように思います。

> 「リリースされたバイナリでリンクが切れていることはない」ことさえ正しければ github.com へのリンクの方がダイレクトでクリックが少なくて済むのが良いわけです。

私は今は特にリンクを作成することに特に必要性を感じないですが、
@ds14050  さんが PR を作成されて対応される分には特に止めないです。

https://www.appveyor.com/docs/environment-variables/  によれば、

APPVEYOR_REPO_TAG  の変数を参照すればタグかそうでないか判断できそうなので
技術的にはリリースバイナリの場合には、リンクを有効にするがそうでないビルドの
場合はリンクを無効にする対応は可能のようです。

**Comment by m-tmatma** [comment]
では、両方リンクをつけるで対応を検討します。

以下仕様案

リンクは  Appveyor  ビルドの場合だけつける。
タグかどうかで絞り込みはしない。
github のurl はorigin のURL を元に算出する。
リンクのテキストはハッシュ値とする。

**Comment by kobake** [comment]
> リンクは Appveyor ビルドの場合だけつける。
> タグかどうかで絞り込みはしない。
> github のurl はorigin のURL を元に算出する。
> リンクのテキストはハッシュ値とする。

ありがとうございます。
そんな感じの方針で良いと思います。

対応については「今の PR に追加でコミット積む」でも「別 PR として対応する」でも「他の人に対応してもらう」でもどれでも良いと思っています。

**Comment by kobake** [comment]
> 開発者や自分であれこれする人にとって、git clone するのや上記の作業も特に手間ではないように思います。

僕は開発者ですけど効率厨なので手間が減る分にはかなりありがたいです

**Comment by ds14050** [comment]
> github で New issue を選んで githash を貼り付けて……

> APPVEYOR_REPO_TAG の変数を参照すれば……

参考になります。

必要性を感じない作業をボランティアの人が強制されるいわれはありませんので、悪意を感じる(感じさせる)などの感情が生じるとしてもそれはすべてその本人の問題だということを前もってお伝えしておきます。

１点。貼り付けようとする GitHash の末尾に、往々にして閉じ括弧がくっついているのもなんとかしたい対象です。

**Comment by m-tmatma** [comment]
> 悪意を感じる(感じさせる)などの感情が生じるとしてもそれはすべてその本人の問題だということを前もってお伝えしておきます。

これは書く必要のあるコメントですか?

**Comment by m-tmatma** [comment]
https://github.com/m-tmatma/test-git-log-oneline/blob/4e673624e26975cacc153bbc5475a72a9b0363c5/show-rev.bat

のようなバッチファイルで

ブランチでの実行の場合
https://ci.appveyor.com/project/m-tmatma/test-git-log-oneline/build/1.0.21

PR での実行の場合
https://ci.appveyor.com/project/m-tmatma/test-git-log-oneline/build/1.0.22

PR の場合、PR のブランチでの head commit と master 等へマージされたときの commit の両方があるので、PR ではない場合は hash へのリンクだけで、PR の場合は head commit へのリンクと マージしたときの commit の両方のリンクを付けるといいと思う。


> github のurl はorigin のURL を元に算出する。

origin のURLの場合、末尾に .git を含むので文字列操作が必要になる。
APPVEYOR_REPO_NAME の環境変数を使うことで、静的に URL を作ることができる。

**Comment by ds14050** [comment]
m-tmatma さんが必要性を感じないなら何よりですけども、一部分だけでも「他の人に対応してもらう」選択もありですよ、何の義務もありませんよってことです。

**Comment by m-tmatma** [comment]
#210 で commit URL の機能に対応しました。

**Comment by m-tmatma** [comment]
#210 をマージした。
