### ISSUE TITLE
バージョン番号ポリシーの策定

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#168]
「バージョン番号の一番末尾の番号にビルド番号を入れる #153」の Issue により、バージョン番号末尾数字をビルド番号にすることが提案されています。議論の流れからするとこの提案は採用されそうです。

で、バージョン番号全体についてのポリシーもこれを機に定めておきたいです。今までの「なんとなく」ではなく、ちゃんとポリシーを決めて共有して今後にも渡って継続運用できると良いなと思っています。

## バージョン番号の慣習
一般的にですが、バージョン番号は以下のような形式をとることが多いみたいです。

```
MAJOR.MINOR.REVISION.BUILDNUMBER
```

- 参考: https://softwareengineering.stackexchange.com/questions/24987/what-exactly-is-the-build-number-in-major-minor-buildnumber-revision

### MAJOR
2 のままで良いと思う。「2」が Unicode 版であることを示すことにする。

今後ものすごい大きな変化があればここの数字を上げる可能性もあり得ますが、今のところ自分ではまだ想像はできません。

### MINOR
リリース毎にインクリメントしていく。
ただし、旧来よく見かけられた「奇数は開発中の非安定板」「偶数は安定板」というポリシーを採用したい。

- 参考: https://mag.osdn.jp/05/06/15/037257

このポリシーを採用するとすると、
・次のリリースバージョンは「2.4.x.x」
・その後のリリースまでの繋ぎ（リリースはしない途中開発の状態）のバージョンは「2.5.x.x」
・さらに次のリリースバージョンは「2.6.x.x」
となります。

さらに未来の話をするとどんどんインクリメントは行われるので、「2.10.x.x」とか「2.46.x.x」とか「2.100.x.x」みたいなバージョン番号にもなり得ます。個人的にはこれでも良いと思っていますが、これに対して違和感を持つ人がいるとして、その違和感を許容できるかどうかがキモかと思っています。

### REVISION
ここはいわゆるコミット番号（コミット毎にインクリメントされる数値）としたい。

ただ、Subversion の場合にはリビジョンがまさにコミット番号でしたが、今の Git は連番の数値というものは存在しません。が、実際にはビルド時点での「（対象ブランチから見た）全コミット数」をカウントすれば、それがコミット番号の代替となります。この数値を用いたいです。

以下コマンドでコミット数はカウント可。

```
git log --oneline | wc -l | sed -e "s/[ \t]*//g"
```

- 参考: https://toris.io/2014/07/git-revision-number-like-svn/

git情報が存在しない環境でのビルドの場合にはここの数値は「0」とする。

### BUILDNUMBER
AppVeyor のビルド番号。`Build 1.0.200` とあれば、この中の `200` の部分。#153 で議論されている内容。

非AppVeyorビルドの場合にはここの数値は「0」とする。

## ご意見ください
どうでしょうか。上に挙げた内容はあくまでもひとつの提案です。
何かご意見あればください。

**Comment by KENCHjp** [comment]
REVISIONがコミット単位というのは、masterに対してってことですか？
マイナーが上がったら、０リセットする？。。。するのは大変そうっすよね。。。
BUILDNUMBERこっちは、ずっとシーケンシャルに上がっていくってことですよね？

2.48.5128.19827

とかになる可能性あり？

**Comment by m-tmatma** [comment]
> BUILDNUMBERこっちは、ずっとシーケンシャルに上がっていくってことですよね？
> 2.48.5128.19827
> とかになる可能性あり？

各桁16bit までですね。

https://msdn.microsoft.com/en-us/library/aa381058.aspx

FILEVERSION 

`Binary version number for the file. The version consists of two 32-bit integers, defined by four 16-bit integers. For example, "FILEVERSION 3,10,0,61" is translated into two doublewords: 0x0003000a and 0x0000003d, in that order. Therefore, if version is defined by the DWORD values dw1 and dw2, they need to appear in the FILEVERSION statement as follows: HIWORD(dw1), LOWORD(dw1), HIWORD(dw2), LOWORD(dw2).
`

**Comment by m-tmatma** [comment]
APPVEYOR_BUILD_NUMBER がいくつまでいけるかは質問しました。
https://github.com/appveyor/ci/issues/2463

**Comment by kobake** [comment]
> REVISIONがコミット単位というのは、masterに対してってことですか？

master でビルドするのであれば master から見たコミット件数になります。

```
                C   - C
             /               
C - C - C   -  C ← この時点ではコミット件数4件
```

```
                C   - C
             /             ＼
C - C - C   -  C   -   C - M - C ← この時点ではコミット件数9件
```

↑ちょっとすみません、線がずれてますが「M」はマージコミットだと思ってください。


> マイナーが上がったら、０リセットする？。。。するのは大変そうっすよね。。。

0 リセットはしない想定で考えています。

> BUILDNUMBERこっちは、ずっとシーケンシャルに上がっていくってことですよね？
> 
> 2.48.5128.19827
> 
> とかになる可能性あり？

です。そういう想定です。

16bitだとunsignedだと6万件、signedだと3万件程度までしか対応できませんが。
それはそれで時期が来たらまた考え直すくらいで割り切りたいです。

**Comment by berryzplus** [comment]
問題ないと思います。

この方式でいくと、今後バージョンについて話すときは
2.4とか2.5とかMajor + Minorだけで話すイメージになると思っています。

3つ目の数字は GitHub を表示したときに出る nCommits の数字、
https://github.com/sakura-editor/sakura

4つ目の数字は appveyor のビルド番号、
https://ci.appveyor.com/project/sakuraeditor/sakura

となるのでフル桁のバージョン番号は障害対応のときにだけ出てくるようになる認識。

別案としてはリリース時点の年月([yymm](https://msdn.microsoft.com/en-us/library/fe06s4ak.aspx))を2つ目か3つ目に入れて識別する方法を考えました。

リリース年月をバージョンにする方式は Ubuntu と Windows 10 で採用されてる方式です。

どう決めるか、だけの話なので反対意見がなければ @kobake さんの案ですすめてよいと思っています。

**Comment by kobake** [comment]
> この方式でいくと、今後バージョンについて話すときは
> 2.4とか2.5とかMajor + Minorだけで話すイメージになると思っています。

そうですね。この議論においても一旦 REVISION, BUILDNUMBER についてはブレがなさそうなので一旦記載を略しちゃいます。

> リリース年月をバージョンにする方式は Ubuntu と Windows 10 で採用されてる方式です。

知らなかった…。
Ubuntu 17.10 ってあったら 2017年10月版ってことだったんですね…。

https://en.wikipedia.org/wiki/Ubuntu_version_history#Ubuntu_18.10_(Cosmic_Cuttlefish)

この場合は MAJOR を年、MINOR を月としていますね。

`SakuraEditor 18.06.xxxx.xxxx` … これはこれで悪くない気もします…が、めちゃくちゃ番号飛びますねｗ
`SakuraEditor 2.1806.xxxx.xxxx` … これはちょっと数字の意味の汲み取りがわかりにくそう。慣れの問題でもありますが。
`SakuraEditor 2.201806.xxxx.xxxx` … こうできれば年月であることがかなり明確になりますけど、16bit 超えちゃいますね。

MINOR に連番（安定板は偶数）を用いるか年月を用いるかは、なんというか好みの問題ですかね。
これについて他の人のご意見も聞きたいです。

**Comment by berryzplus** [comment]
リリース年月を含めるとしたらwindows10スタイルになると思っています。

https://ja.wikipedia.org/wiki/Microsoft_Windows_10#バージョン履歴

> SakuraEditor 2.1806.xxxx.xxxx … これはちょっと数字の意味の汲み取りがわかりにくそう。慣れの問題でもありますが。

指摘はまったくその通りで、ぼく自身も昨年末くらいまで気付いていませんでした。
fall creator updateのときにバージョン一覧みて、「あ」と思ったクチ・・・。

この方式にするならメジャーを 3 にしてしまったほうが分かりやすいのかも知れません。
いまのノリでいくと 3 に移行するのは時期尚早かな、という所感。

あと、ubuntuもそうなんですが、この形式のバージョンを振るものは、
リリースバージョンに「愛称」をつける慣習があるみたいです。
このへんは Eclipse シリーズとも通じるところがあると思っています。

**Comment by KENCHjp** [comment]
ちなみに、sakura本体で、バージョン番号に依存した処理って無いって思っていいですか。
私のソフトは、過去のdata(Iniファイル)を読むときに内部のバージョン番号によって、中のデータを加工して最新の形式にコンバートする処理があります。
（昔Iniしかなかったので、固定長レコード+末尾可変データみたいな形式だったので、xmlとかyamlとかだったらそんなことしなくてよかったのかもしれませんけど)

**Comment by kobake** [comment]
https://github.com/sakura-editor/sakura/blob/master/sakura_core/config/system_constants.h#L546

一応ここでプロセス間共有メモリ形式のバージョンがあったりしますけど、ソフトウェアのバージョンとは独立した番号になってるので影響無しという認識です。

過去のソフトウェアバージョン番号変更のときにも特段データ形式を意識するようなコミットを見た記憶は無いです。

ini の形式を将来がっつり変更することがあったとしても、そこはソフトウェアバージョンで判定というよりは ini 自体にバージョンを持たせるのが安全で柔軟ではないかな、と思っています。

ところで本 Issue の話とは関係ないですけど、32bit 版と 64bit 版でたぶん共有メモリの構造（数値系のサイズ）が変わると思うので、このあたりは混ざらないように考えておく必要はありそうです。

**Comment by KENCHjp** [comment]
@kobake さん、了解です。

**Comment by kobake** [comment]
パーマリンクおけです

**Comment by kobake** [comment]
パーマリンクに変更しておきました

**Comment by berryzplus** [comment]
> 私のソフトは、過去のdata(Iniファイル)を読むときにiniファイル内のバージョン番号によって、中のデータを加工して最新の形式にコンバートする処理があります。

サクラエディタにも、古いsakura.iniを読み込むときのコンバート処理があったような気がするんですが・・・。
```CShareData_IO::LoadShareData()``` が呼び出してる処理のどこかです。
たしか項目名を読み替える処理だった気がします。
見つからないので「ない」ってことでもいいかな、と。


> ところで本 Issue の話とは関係ないですけど、32bit 版と 64bit 版でたぶん共有メモリの構造（数値系のサイズ）が変わると思うので、このあたりは混ざらないように考えておく必要はありそうです。

これについては対応不要な認識です。
現状のままだと 32bit版 と 64bit版 は干渉しないので、同時に起動させることができます。

https://github.com/sakura-editor/sakura/blob/f2165073f6ae5918318d5cfb0e52292aebef3a73/sakura_core/config/system_constants.h#L60-L65


共有メモリの名前をシンボル定義する際に、x86/x64を識別する名前を含めています。
kobake さんが貼ったリンクの2行下です。

https://github.com/sakura-editor/sakura/blob/f2165073f6ae5918318d5cfb0e52292aebef3a73/sakura_core/config/system_constants.h#L548

ここに載ってるパラメタのいずれかが異なれば同時起動可能です。
Debug/Releaseも同時起動可能 :smile:

**Comment by KageShiron** [comment]
平成30年だから、2.3006・・・！

**Comment by KageShiron** [comment]
GitHub Flowは、サーバーで動かすよう常時本番投入可能なソフトを高速で開発していく手法で、リリースを区切る通常のソフトにはいまいちかみ合わせが悪いらしいです。(イマイチ理解しきれてないですが・・・)

> 仮に ver 2.4 をリリースしたとしたら、リリース直後に master でのバージョン番号を 2.5 に上げてしまって

微修正(例えば、リリース後に特定の環境でインストーラがうまく動かないとか、ヘルプファイルの修正とか)でも2.6をリリースするんでしょうか？

2.4から分岐するにしても、revisionにコミット数が入っていると事前に手順を考えておかないと面倒が生じそう

**Comment by kobake** [comment]
微修正リリースが必要な場合は hotfix として 2.4.aaa.bbb から分岐した 2.4.ccc.ddd をブランチ分けて作る感じを考えていましたが、どういう問題が発生するのかいまいち想像できないです。

aaa よりも ccc は必ず大きい数字になるので、ここが問題になることは考えてないです。

> いまいちかみ合わせが悪いらしいです。(イマイチ理解しきれてないですが・・・)

自分もいまいち理解しきれてないです…。その場その場の思い付き対応でも帳尻合えば良いかなーと楽観的に考えていました。

**Comment by KageShiron** [comment]
多分私の違和感はここらへんです。

- 全く内容の違う2.4.1000.xと、2.5.1000.xが同時に存在して良いのか(別に良い気もしてきた)
- 2.4.1000.xの修正版として2.4.1001.xを一般公開する可能性があるなら、「2.4とか2.5とかMajor + Minorだけで話すイメージになると思っています。」に反しそう

https://postd.cc/gitlab-flow/

によると、masterに入れる→安定版ブランチにCherry Pickが良いらしいです

**Comment by kobake** [comment]
> 全く内容の違う2.4.1000.xと、2.5.1000.xが同時に存在して良いのか(別に良い気もしてきた)

良いと思ってます。

場合によっては 2.4.1010.x と 2.5.1000.x のように、2.4 側の REVISION が大きくなることもあり得ますが。特に混乱は生まれない…はず、と考えています。

> 2.4.1000.xの修正版として2.4.1001.xを一般公開する可能性があるなら、「2.4とか2.5とかMajor + Minorだけで話すイメージになると思っています。」に反しそう。少なくとも、2.4(インストーラ修正版)みたいな名前で公表するのは避けたい

そうですね、当初 hotfix のことは考えていませんでしたが、それ込みで考えると利用者の方々にも REVISION まで含めたバージョンを意識してもらう必要がありそうです。

Issue でバグ報告受けるときにはバージョン番号をぜんぶ書いてもらうように Issue Template で促そうかと考えています。
今草稿中の Issue Template を https://github.com/sakura-editor/sandbox/issues/new?template=1_bug.md から見れます。

> https://postd.cc/gitlab-flow/
> 
> によると、masterに入れる→安定版ブランチにCherry Pickが良いらしいです

ちょっとここはあとで時間あるときに見てみます。

**Comment by m-tmatma** [comment]
`git log --oneline | wc -l | sed -e "s/[ \t]*//g"`

REVISION に関してですが、
windows では wc も sed もないので、HeaderMake や MakefileMake などユーティリティを
作ってビルドに使うように同様に行番号を数える小さなユーティリティを作ればいいと思います。

cygwin とか入れればいいのかもしれませんが、そのために cygwin への依存は入れたくない。

**Comment by kobake** [comment]
もし PowerShell が使えるならそれでやりたいです。自分のほうでやっていた検証は途中で止まってしまってますが。

**Comment by m-tmatma** [comment]
https://qiita.com/cd01/items/da9a36582372e7d0a7f6
こんなサイトありました

**Comment by m-tmatma** [comment]
いけますね。

```
https://ci.appveyor.com/project/m-tmatma/test-git-log-oneline/build/1.0.2
https://github.com/m-tmatma/test-git-log-oneline/blob/551838c3b3a1d27afc32cdd55ea0343af0767136/show-rev.bat
```

**Comment by m-tmatma** [comment]
↑ 間違えました。リンクに変えました。

**Comment by KageShiron** [comment]
>>  全く内容の違う2.4.1000.xと、2.5.1000.xが同時に存在して良いのか(別に良い気もしてきた)
>良いと思ってます。
>場合によっては 2.4.1010.x と 2.5.1000.x のように、2.4 側の REVISION が大きくなることもあり得ますが。特に混乱は生まれない…はず、と考えています。

了解です。自分の頭でリビジョン=ソースコードバージョンぐらいで考えていたので混乱してました^^;

> Issue Template

開発版ではmaster以外のブランチの自己ビルドをバージョン番号からは特定できないので、ハッシュ値も書くように明記したほうが良いかもしれません。(2.5.1000.0はブランチごとに複数存在しえます)

**Comment by kobake** [comment]
> 開発版ではmaster以外のブランチの自己ビルドをバージョン番号からは特定できないので、ハッシュ値も書くように明記したほうが良いかもしれません。(2.5.1000.0はブランチごとに複数存在しえます)

ハッシュ値はあったほうが好ましいですね。

ですが人によっては ZIP からダウンロードしたものをビルドする人もいたりして、そうするとダウンロード時点でのハッシュを覚えていないと、ZIP 解凍物からは Git 関連情報が何もない（2.5.0.0 みたいになる）ので、うーんってところですけど、まぁそれは問題になったときに考えようと思います。

開発途上版をダウンロードする人は AppVeyor 成果物のほうを使ってもらうように README で促すとかは考えています。

**Comment by m-tmatma** [comment]
> Issue でバグ報告受けるときにはバージョン番号をぜんぶ書いてもらうように Issue Template で促そうかと考えています

ヘルプ → バージョン情報 → 情報をコピー
で得られる情報を貼り付けて、とだけ書いておけば必要な情報はすべて得られると思います。

**Comment by m-tmatma** [comment]
↑ ZIP 解凍物 のビルドの場合以外は、です。

**Comment by m-tmatma** [comment]
> APPVEYOR_BUILD_NUMBER がいくつまでいけるかは質問しました。

回答返ってきました。

https://github.com/appveyor/ci/issues/2463#issuecomment-400168660

`Int32 max value, e.g. 2147483647`

**Comment by kobake** [comment]
ビルド番号MAX値でかいですね。これが 16bit 超える時期は相当先だと思いますが、その時期が近付いてきたら何か対策考えましょう。（今の時点で考え始めてもアテが外れる可能性があるので、しばらく運用を続けた後からの検討のほうがより良い案が出ると期待している）

**Comment by m-tmatma** [comment]
> これが 16bit 超える時期は相当先だと思いますが、その時期が近付いてきたら何か対策考えましょう。

REVISION の部分をそのために空けとくという選択肢もあります。

**Comment by kobake** [comment]
REVISION にはコミット番号入れたいですね……。ビルド単位ではなくコミット単位でインクリメントされる値はあったほうが良いです。

BUILDNUMBERについては場合によってはAppVeyorビルド番号を30000で割った余りの数とかでも良いかなと思ったり。本物のビルド番号はバージョンダイアログ表示でも済むところなので。

**Comment by m-tmatma** [comment]
それなら ビルド番号をバージョンの一部に入れるの自体やめてしまって、別途バージョンダイアログ表示でもいいのかも。

**Comment by kobake** [comment]
余りの数を入れるというのは、仮にオーバーフローを考慮したら、という話なのですが、
実際にはこの数字が 16bit 超えるのには10年くらいはかかると思っています。
（あと、これはあまり言いたくないですけど、16bit 超える時期が来るまでに AppVeyor がサービス継続されているかどうかも分からない）

BUILDNUMBER に入れたい別の情報があるならそれも良いのですけど、今のところはビルド番号入れておくということで良いのではと思っています。

**Comment by kobake** [comment]
@sakura-editor/sakura-developers 
一旦 MINOR 番号部についての決を採りたいです。
多数決で方針を確定するわけではないですが、皆さんの意向をお聞きしたいです。

- 1．単純な連番方式 (2.4, 2.5, 2.6, 2.7, 2.8, ....)
- 2．偶数を安定板とする連番方式 (2.4, 2.6, 2.8. ....) (奇数は開発途上版)
- 3．リリース年月による番号 (2018年6月であれば 1806、2020年10月であれば 2010 のような形)
- 4．その他（まだ選択肢がある場合には決を採り直します）

票の入れ方ですが、どれかひとつを選ぶのが難しい場合には、好ましいと思われる順に複数投票してもらっても構わないです。

自分の票は、好ましい順に「2」「3」「1」です。

**Comment by m-tmatma** [comment]
「１．」

**Comment by KageShiron** [comment]
「１.」

**Comment by ds14050** [comment]
1 か 2 です。

**Comment by berryzplus** [comment]
「１．」

**Comment by kobake** [comment]
ご意見ありがとうございます。「1」が多そうですね。

「1」の方針で行くとすると、たとえば 2.4.a.b をリリースした後も 2.4.c.d の形でメンテナンスしていき、随時適当なタイミングで 2.4.e.f をリリースしていく、という感じですかね。大きな変更がある場合のみ MINOR 部をインクリメント（奇数偶数は考えない）する運用イメージが良いでしょうか。

**Comment by KENCHjp** [comment]
>大きな変更がある場合のみ MINOR 部をインクリメント（奇数偶数は考えない）する運用イメージが良いでしょうか。

イメージあってます。

**Comment by kobake** [comment]
「１」を採用する場合のひとつ懸念としては

```
　　　　　　 hotfix 2.4.x リリース
　　　　　　/
2.4.a リリース - 2.4.b 随時コミット - 2.4.c 随時コミット - 2.4.d 随時コミット - 2.4.e リリース
```

というケースが考えられます。

このケースだと 2.4.x が hotfix であることはぱっと見では分からなそう。
（`x` が `e` より小さい数値である可能性は割とある）

**Comment by KENCHjp** [comment]
>（x が e より小さい数値である可能性は割とある）

次リリースは、2.4.yとか。
もしくは、hotfixは、2.4.a.xとか。
もしくは、hotfixは、2.4.bなりなんなり直列とか。
xが存在した時点で小さい値を管理して統制するのは記憶力頼りですよね？

**Comment by kobake** [comment]
`2.4.x` の `x` はリビジョンを想定していましたが、そこの前提も変えてしまいますかね？

**Comment by KENCHjp** [comment]
>2.4.x の x はリビジョン（いわゆるコミット番号であり、人間が決めるものではない）を想定していましたが

あ、なるほど。
自分が理解できてないかとおもいますが、そのときの2.4.bは2.4.xより大きくならないっすか？

**Comment by kobake** [comment]
```
　　　　　　 hotfix 2.4.x リリース
　　　　　　/
2.4.a リリース - 2.4.b 随時コミット - 2.4.c 随時コミット - 2.4.d 随時コミット - 2.4.e リリース
```

過去コミットを端折った図になっていますが、仮にこれが全コミットであると仮定すると、以下のような数値になります(´Д｀)

- a = 1
- b = 2
- c = 3
- d = 4
- e = 5
- x = 2

**Comment by KENCHjp** [comment]
2.4.xリリース後に、2.4.eリリースならば、
2.4.2リリース（hotfix)後に、2.4.5リリースで、逆転しない？(2.4.5でhotfix取り込む)

2.4.eリリース後に、過去にさかのぼって2.4.xにhotfixする場合に、2.4.b～2.4.eがdeadバージョンで、
2.4.f(hotfixを取り込んだ版)を早々にリリース。

こんな流れですか？

**Comment by kobake** [comment]
> 2.4.eリリース後に、過去にさかのぼって2.4.xにhotfixする場合に、2.4.b～2.4.eがdeadバージョンで、
> 2.4.f(hotfixを取り込んだ版)を早々にリリース。

このイメージです。
2.4.d とか 2.4.e とかの準備をしている最中に、既にリリース済みの 2.4.a に致命的な問題があった！というときに臨時で 2.4.a からブランチ分けて 2.4.x を出すようなイメージです

> 2.4.xリリース後に、2.4.eリリースならば、
> 2.4.2リリース（hotfix)後に、2.4.5リリースで、逆転しない？(2.4.5でhotfix取り込む)

逆転はしないのです。ちょっと半角だとずれるので全角で書きますね（そのためちょっと幅の都合で情報削ります。議論の記号も変わってしまってすみません）
```
　　　　　　 ｈｏｔｆｉｘ２．４．ｘ　－－－－
　　　　　／　　　　　　　　　　　　　　　　　＼
２．４．ａ　－　２．４．ｂ　－　２．４．ｃ　－　Ｍ　－　２．４．ｄ　－　２．５．ｓ
```
この例だと、以下のような採番となります。ニュアンス伝わりますでしょうか。

- a = 1
- b = 2
- c = 3
- M = 5
- d = 6
- s = 7
- x = 2

逆転の問題はないとして、ここで致命的な問題になるのは、
hotfix である 2.4.2(x) と、開発途上である 2.4.2(b) の区別がつかないということです。

**Comment by kobake** [comment]
補足しておくと、上記 2.4.x をどのタイミングでブランチ切ったとしても、x は必ず 2 になります。

**Comment by KENCHjp** [comment]
>hotfix である 2.4.2(x) と、開発途上である 2.4.2(b) の区別がつかないということです。

皆さんのバージョン番号に対するアンケートからすると、
hotfixが出で上記懸念に遭遇する頻度よりは、常日頃の今までの慣例のほうが日々の運用的にわかりやすいような気がします。

でも、こういう事例を書いていただけると懸念点のイメージが整理できてよかったです。
で改めて「１．」で。

**Comment by kobake** [comment]
頻度は確かに少ないのですが、その頻度の少なさから得られる恩恵は「ブランチ作業みたいな面倒くさいことをあんまりやらなくて済む」程度かと思っています。

バージョン番号については頻度が少なかろうとも極めて致命的であると考えています。

たとえば 2.4.6 というリリース版が出ている状態で
hotfix を 2.4.2 で出してしまったら、

あえて 2.4.6 を使わずに 2.4.2 が hotfix であることを意識して使おうとしてくれる人ってほとんどいない気がします。アナウンスの仕方で工夫・・・ですかね？

もしくは MINOR 部については「大きな変更がある場合のみ MINOR 部をインクリメント」の前提を崩して、小さな変更であっても常にインクリメントしていく方針にするのであれば、hotfix 版の区別はつきやすくなります。以下のようなイメージです。
```
　　　　　　 ｈｏｔｆｉｘ２．４．ｘ　－－－－
　　　　　／　　　　　　　　　　　　　　　　　＼
２．４．ａ　－　２．５．ｂ　－　２．５．ｃ　－　Ｍ　－　２．５．ｄ　－　２．５．ｓ
```

**Comment by KENCHjp** [comment]
>あえて 2.4.6 を使わずに 2.4.2 が hotfix であることを意識して使おうとしてくれる人ってほとんどいない気がします。アナウンスの仕方で工夫・・・ですかね？

これがどれぐらいの致命的不具合かどうかですが、使ってて致命傷であれば、2.4.2を使ってもらえるかとおもいます。
また、致命傷の場合、いったん2.4.6はリリース（ダウンロードページ等）からは削除して、
2.4.7を出す間の最終リリースは2.4.2を公開していればいいように思いますがいかがでしょう。

これ、例えば2.4.6を使ってるユーザーで特に困ってない（その致命傷の機能に該当しない）人が、
そろそろバージョンアップしようかーみたいな感じで、公サイトに訪れて、まだ2.4.7が公開されてない状態で、2.4.2使ってねってかいてあれば2.4.2にするか2.4.6を使い続けてもいいやって判断して、2.4.7が公開されてれば普段通り2.4.7にアップロードするような。

**Comment by kobake** [comment]
間違えてクローズしちゃってました。reopen.

**Comment by kobake** [comment]
少し考えたのですが、そもそも旧版からのhotfixを考えずに常に最新リリース版からのhotfix切るようにすればリビジョン巻き戻り問題起きなくなりますね。

**Comment by kobake** [comment]
↑(少なくともリリース版に限っては)

**Comment by k-takata** [comment]
独自ルールで悩むくらいなら、[semantic versioning](https://semver.org/lang/ja/) に倣ってもよいのではないでしょうか。現状最も広く使われているルールだと思います。(どちらかというとアプリではなくライブラリを意識したルールですが。)

* 2.4.xx は、基本的には 2.4.0 に対するバグフィックスのみ。(小さな機能追加ぐらいは入れてもいいかも)
* 既に2.4.6をリリースしたなら、2.4系に対するhotifixは2.4.7として出す。(2.4.1から分岐させたりはしない。)
* 機能追加をしたなら次のリリースは 2.5.0。

semantic versioningを使うなら、自動更新するのはビルド番号のみ (a.b.c.d の d のみ) になるでしょう。
（ちなみに今、奇数偶数方式を使っているメジャーなプロジェクトはPerlぐらい？）

**Comment by KENCHjp** [comment]
@k-takata さん、おおそんなのもあるんですね。
勉強なります。

**Comment by KENCHjp** [comment]
[semantic versioning](https://semver.org/lang/ja/) を採用しても「１．」のアンケートと矛盾はないっすね。

**Comment by berryzplus** [comment]
機能が追加されたらマイナーアップということなら次バージョンは2.4確定ですね。

2.3のあとに追加された機能がいくつかあるので。

**Comment by kobake** [comment]
@k-takata 
> 独自ルールで悩むくらいなら、semantic versioning に倣ってもよいのではないでしょうか。現状最も広く使われているルールだと思います。(どちらかというとアプリではなくライブラリを意識したルールですが。)

良いと思います。
今風のルールがあるならそっちに乗っかるのが良さそうですね。

　

@berryzplus 
> 機能が追加されたらマイナーアップということなら次バージョンは2.4確定ですね。
> 
> 2.3のあとに追加された機能がいくつかあるので。

2.4 で良いと思います。

ただ、 @k-takata さんがおっしゃられている、

> 2.4.xx は、基本的には 2.4.0 に対するバグフィックスのみ。(小さな機能追加ぐらいは入れてもいいかも)

という文面からは「小さな機能追加程度であれば MINOR は上げるまでもない」という意味であると自分は汲み取りました。

現時点からの次リリースは割といろいろ変更入ることが想定されるので MINOR は上げる確定で良いと思っていますが、今後も機能が何かしら追加されたからといって MINOR を必ず上げる必要があるかというと、そのあたりは雰囲気で判断になると思います。

**Comment by kobake** [comment]
[semantic versioning](https://semver.org/lang/ja/)、良いと思いますが、皆さんどうでしょう。

> semantic versioningを使うなら、自動更新するのはビルド番号のみ (a.b.c.d の d のみ) になるでしょう。

d 部分はビルド番号で良いでしょうか。
コミット番号という選択肢もあるように思いましたが、いまいちここの番号をどうすべきか判断に迷っています。

**Comment by kobake** [comment]
あと、ひとつ気になっているのが、仮に semantic versioning を採用して 2.4.0.d をリリースしたとして、次のリリースまでの間、2.4.c.d の c 部分の値は維持したままでコミットを積んでいくことになるでしょうか。

個人的には 2.4.0.d をリリースした直後に GitHub ソースコード内のバージョンは 2.4.1.d に上げてしまったほうが、リリース版とそれ以外が区別できてありがたいと思っています。（結局ここで奇数偶数の話のぶり返しになってしまうのですが）

**Comment by KENCHjp** [comment]
>結局ここで奇数偶数の話のぶり返しになってしまうのですが）
「リリース後に上げましょう」はキメなのでいいと思います。
「リリース以外では上げません」は決まってないと思いますので、必ずしも奇数偶数の議論のぶり返しではないと思われます。

**Comment by k-takata** [comment]
実のところ semantic versioningのバージョン表記は、`major.minor.patch(-prerelease)(+buildmetadata)` ですので、`a.b.c.d` という表記は許可されていません。なので厳密に従うならば、例えば以下のようになるでしょう。

* リリース版:
  * 公式なバージョン名は `a.b.c` として、d (ビルド番号or コミット番号)はあくまで補足情報としておく
  * あるいは `a.b.c+d` 表記にする
* プレリリース版:
  * `a.b.c-d` 等の表記にする (`2.4.1-123`, `2.4.1-dev123`, etc.)

(semantic versioningは参考にしただけということにして `a.b.c.d` 表記を通すのもありかもしれませんが。)

> 個人的には 2.4.0.d をリリースした直後に GitHub ソースコード内のバージョンは 2.4.1.d に上げてしまったほうが、リリース版とそれ以外が区別できてありがたいと思っています。

semantic versioningに従うなら、バージョンを上げてしまって、上に書いたように `2.4.1-d` などの表記になればよさそうです。

**Comment by kobake** [comment]
なるほど〜、勉強になります。ご解説ありがとうございます。これをもとにもう少し案練ってみます。

**Comment by berryzplus** [comment]
これ、だいぶ前に決まった認識なので閉じてしまいます。
