### ISSUE TITLE
Appveyorのビルドが遅い

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#1680]
## 問題内容

タイトル通りです。

## 再現手順

CIビルドを開始する（PRを作成する、PRを更新する、PRをマージする）
　👇
Appveyorのキューに入る（ここに時間はかからない
　👇
Appveyorのキューを待つ（1時間近く待つことがある　★問題①
　👇
Appveyorのビルドが実行される（直列で実行される　★問題②
　・vs2017 Win32 Release ダウンロード成果物作成用、10～20分必要
　・vs2017 x64 Release ダウンロード成果物作成用、10～20分必要
　・vs2017 Win32 Debug ビルドログ整形バッチのために実行、10～20分必要　★問題③
　・vs2017 x64 Debug ビルドログ整形バッチのために実行、10～20分必要　★問題④

都合、1時間くらいかかっていて遅いです。

問題①と問題②は、有償プランに切り替えれば解決できる可能性あり。
　有償プランなら同時実行タスクを2以上に設定できます。
　有償プランならキュー待ち時間が短縮されるらしいです。
　「俺が金出す！」という人がいれば解決。
　AzurePilelinesとGitHubActionsでは無償でできるので、なんで？と思いますが。

問題③と問題④は、Debugビルドを止めれば解決できます。
　ビルドを止めるとログ解析バッチが動かなくなります。
　ログ解析バッチの出力をもとにしたPRの実績はないので、影響はないと思います。

## 再現頻度

100%

## 問題のカテゴリ

- ビルドの問題
  - Appveyor

## 環境情報
- OS バージョン

- サクラエディタバージョン

- PC情報

**Comment by k-takata** [comment]
AppVeyorを使い続ける必要があるかという点から検討した方がよいかと思います。
以前はhtml helpがAppVeyorでしかビルドできませんでしたが、Locale Emulatorを使う方法が確立したことで、AppVeyorでなければならない理由はなくなったと思っています。

**Comment by berryzplus** [comment]
> AppVeyorを使い続ける必要があるかという点から検討した方がよいかと思います。
> 以前はhtml helpがAppVeyorでしかビルドできませんでしたが、Locale Emulatorを使う方法が確立したことで、AppVeyorでなければならない理由はなくなったと思っています。

appveyorを止めるには #168 を更新する必要があります。

v.2.4.aa.bbbb
というバージョン番号のうち、
bbbb部分にappveyorのビルド番号（通し番号）を使っています。

妥当な代案を思いつかないので「変えましょう」とも言えず放置しｔる感じです。

可能な方法
・git リポジトリの累積コミット数を表示する（SvnのRev相当
　メリット：Appveyor/Azure Pipelines/GitHub Actionsでビルド番号が揃う。
　デメリット：ビルドにかかる時間が十数秒延びるかも。

**Comment by takke** [comment]
> 可能な方法
> ・git リポジトリの累積コミット数を表示する（SvnのRev相当
> 　メリット：Appveyor/Azure Pipelines/GitHub Actionsでビルド番号が揃う。
> 　デメリット：ビルドにかかる時間が十数秒延びるかも。なんかダサい。

`git log --oneline --no-merges | wc -l` で秒で取れるらしいです。アリだと思います。
