### ISSUE TITLE
Milestone の運用

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#17]
チケットやプルリクエストで Milestone を設定できますが、
Milestone は運用されていないようですが、運用しませんか?

**Comment by kobake** [comment]
どういう単位で運用するイメージでしょう？
OSS でうまく運用できている例ってありますか？

**Comment by m-tmatma** [comment]
こんな感じで考えています。

1. master に対する修正を行うチケット、プルリクエストに対して Milestone を設定する。
2. 次にリリースするバージョンが決まっている場合、そのバージョン名をつける。
   (例: "ver 2.4.0.0" とか)
3. 次にリリースするバージョンが決まっていない場合、"next release" とか暫定的なものを設定する。
   (バージョン番号が決まった時点で、仮の milestone 名を名前変更する)
4. 過去にリリースしたバージョンに対する hotfix の場合、もとにしたバージョンの
   更新であることがわかるバージョン番号の Milestone を振る。

**Comment by kobake** [comment]
ふむふむ。バージョン要件がトップダウンで決まるような所だとマイルストーンが必要な気がしますが、サクラエディタの場合はとりあえず五月雨にコミット積んでいって適当なタイミングでバージョンタグ打つくらいの運用で良いかな～と思ってましたが、どうでしょう。

> 過去にリリースしたバージョンに対する hotfix の場合、もとにしたバージョンの
> 更新であることがわかるバージョン番号の Milestone を振る。

過去バージョンの hotfix を配布するようなことはあまり考えてなくて、とりあえずあるバージョンに何かしらのバグがあって、それが修正されているバージョンが欲しい場合には（それの修正が含まれる）新しいバージョンを使ってもらう、くらいの感覚でいます。

今後大きな機能変更があって分岐が発生する場合には hotfix 運用も考慮する必要がありますが、そこは必要が生じてから考えるくらいで良いかな、と。

**Comment by m-tmatma** [comment]
> サクラエディタの場合はとりあえず五月雨にコミット積んでいって適当なタイミングでバージョンタグ打つくらいの運用で良いかな～と思ってましたが、どうでしょう。

milestone の設定の利点は、リリースノートを書くのが楽になることです。

milestone を設定しておけば、前のリリースからどんな修正をしたかを
チケット、プルリクエスト単位でリストアップできることです。

**Comment by kobake** [comment]
ふむー、試しに運用してみます！

**Comment by kobake** [comment]
next release
https://github.com/sakura-editor/sakura/milestone/1
