### ISSUE TITLE
文字列をすべて置換したときに表示されるメッセージがおかしい

### ISSUE THREAD

**Issue by kazasaku** [sakura-editor/sakura#1701]
## 問題内容
置換前キーワードに一致した箇所を一つずつ置換していき、最後の箇所まで置換したときに表示されるポップアップメッセージの内容にフォーマット指定子のような文字列が出力される。

## 再現手順
1. 任意のファイルを開く
2. 置換前後のキーワードを入力して、「置換」ボタンで1件ずつ置換を行う
3. 最後にマッチしたキーワードを置換したときのポップアップメッセージを確認する

## 再現頻度
上記手順で再現できるときとできないときがあります。

## 問題のカテゴリ
- プログラムの動作上の問題
  - Appveyor ビルド版

## 環境情報
- OS: Windows 10 Pro バージョン21H1 ビルド19043.1083 64ビット版
- サクラエディタ: v2.4.2.3817 32bit dev 9152b834e2a30146662b0713897d2875777e5cab
- PC: DELL Latitude e7270

## スクリーンショット
次のようなメッセージが表示されます。

![スクリーンショット 2021-07-08 011517](https://user-images.githubusercontent.com/67105596/124794816-618c5600-df8a-11eb-9e63-897b4e918bd8.png)

**Comment by kazasaku** [comment]
文字列を検索してみたところ、 #1513 で追加された文字列でした。
使用箇所は次の1か所しかなく、ここで文字列が書き換わっているのかもしれません。
https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/view/CCaret.cpp#L846-L848

**Comment by berryzplus** [comment]
きっついですね。

LSマクロはリソース文字列をテンポラリバッファに格納するようになっていて、テンポラリバッファは使いまわしするようになっていたと思います。

----
const wchar_t* 変数 = LS(リソース識別子);
　👆パッと見で「変数」の内容は変更されないように見える（気のせい
----

だるいっす。。。

**Comment by berryzplus** [comment]
本来表示されるはずのメッセージがこれです。
https://github.com/sakura-editor/sakura/blob/df7c2cd9433b39e8b6154dd877a15d5409bfd214/sakura_core/sakura_rc.rc#L3501

利用箇所(1箇所のみ)です。
https://github.com/sakura-editor/sakura/blob/df7c2cd9433b39e8b6154dd877a15d5409bfd214/sakura_core/cmd/CViewCommander_Search.cpp#L708-L709

不具合原因は、この関数のシグニチャです。
https://github.com/sakura-editor/sakura/blob/df7c2cd9433b39e8b6154dd877a15d5409bfd214/sakura_core/cmd/CViewCommander_Search.cpp#L79-L86

原因を理解できれば対処は簡単ですが、上記の説明では不具合発生のメカニズムを理解できないような気がします。

どこまで説明したら理解できるか分からないのが「だるいなぁ」と思う理由です。

**Comment by kazasaku** [comment]
何とかデバッグ実行中に再現できたので、ステップインしてみました。

1. LSマクロを通じてCLoadStringが呼び出され、引数に指定している文字列がテンポラリバッファにロードされる
    ロードした文字列への参照を引数としてCommand_SEARCH_NEXTが呼ばれる
https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/CSelectLang.h#L155 https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/cmd/CViewCommander_Search.cpp#L709
3. Command_SEARCH_NEXTが呼ばれ、その中でShowCaretPosInfoが呼び出される
https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/cmd/CViewCommander_Search.cpp#L302
4. ShowCaretPosInfoでステータスバーに表示する文字列もテンポラリバッファにロードされる
https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/view/CCaret.cpp#L683 https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/view/CCaret.cpp#L834 https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/view/CCaret.cpp#L837-L841
5. ズーム倍率情報の文字列をバッファにロードしたとき、STR_ERR_CEDITVIEW_CMD11がロードされている領域が上書きされ、データが失われる。
https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/view/CCaret.cpp#L844-L848

**Comment by kazasaku** [comment]
`CLoadString::LoadStringSt()`経由でアクセスしているテンポラリバッファは次のように定義されています
https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/CSelectLang.h#L125-L126 https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/CSelectLang.cpp#L220-L222

バッファサイズが呼び出し回数よりも少なくて寿命が足りないのかもしれませんが、 #1513 のレビューで「フォーマット指定子はリソース化すべきでない」という趣旨のコメントがあり、`STR_STATUS_FONTZOOM_#`自体が不要という理解もできます。
`const wchar_t*`型は`const`とついていながら書き換え可能なので、「変わってほしくない値をこの型で渡すな」という指摘も正しいですし、どこをどう対応するかは判断がつきませんでした。

**Comment by kazasaku** [comment]
CLoadStrBufferが持つデータは`const`修飾されていませんでした。
https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/CSelectLang.h#L115-L118

**Comment by berryzplus** [comment]
> const WCHAR*	pszNotFoundMessage, 

これを、こうする・・・

> const std::wstring& &notFoundMessage, 

もしくは、関数内部の1行目の処理でこうする。

> const std::wstring notFoundMessage(pszNotFoundMessage);

要するに、グローバルなテンポラリバッファを経由されたデータを、
自分が管理できる領域にコピーしてしまえば勝手に書き替えられる事態を回避できます。

知識があやふやなんでアレなんですけど、std::wstring_viewを使うやり方単体ではコピーが発生しないので対策にならんように思います。おそらく最善主は 引数を wstring_view に変える＋ローカルstd::wstringにコピーする、だと思います。

**Comment by suconbu** [comment]
ここの説明がまさに今回のケースが該当していそうで、インスタンスメンバの方を使うべしとありますね。
https://github.com/sakura-editor/sakura/blob/510b40ecd8da5b8a0340663cf8f87d585c0f5b58/sakura_core/CSelectLang.cpp#L237-L243

従うとこのような感じになるでしょうか。
```cpp
/* 次を検索 */
CLoadString strErr;
Command_SEARCH_NEXT( true, true, false, hwndParent, strErr.LoadString( STR_ERR_CEDITVIEW_CMD11 ) );
```
または、
```cpp
/* 次を検索 */
CLoadString strErr( STR_ERR_CEDITVIEW_CMD11 );
Command_SEARCH_NEXT( true, true, false, hwndParent, strErr.GetStringPtr() );
```

**Comment by berryzplus** [comment]
呼出元はLSマクロを使うのが正しい気がします。

リソース読込のコードに統一感がないと、どこでリソース読込してるか探しづらくなるからです。

対策すべきは、リソースから読まれたテンポラリバッファを受け取る関数側で、
たとえば「表示文字列」を受け取る関数はテンポラリバッファの更新を考慮する必要があると思います。

**Comment by berryzplus** [comment]
こういうことです。
https://github.com/sakura-editor/sakura/compare/master...berryzplus:feature/issue1701_workaround

PR作るのダルいのでお願いします。

**Comment by sanomari** [comment]
> こういうことです。
> [master...berryzplus:feature/issue1701_workaround](https://github.com/sakura-editor/sakura/compare/master...berryzplus:feature/issue1701_workaround)

この対応で問題なさそうに見えます。

**Comment by kazasaku** [comment]
他の`LS()`呼び出しを確認していてPRを書いていませんでした。ありがとうございます。

`Command_OPEN_HHPP()/Command_OPEN_CCPP()` による `CEditView::OPEN_ExtFromtoExt()` の呼び出し箇所も似たような使い方をしているように見えます。
b7c6b2356726a1d8d04123d0f90710586f140001 以降渡す必要がなくなったので実害はないはずですが。

**Comment by suconbu** [comment]
> 対策すべきは、リソースから読まれたテンポラリバッファを受け取る関数側で、
> たとえば「表示文字列」を受け取る関数はテンポラリバッファの更新を考慮する必要があると思います。

呼び出し先の関数内で LS マクロを使っているかどうかなんて呼び出し側は知ったことではないのでその通りでした。

LS マクロで一時オブジェクトを生成してやってうまく行かないかなと考えましたけど、LS マクロは代入文でも使われるので駄目でした。。
