### ISSUE TITLE
クリッカブルURL機能から実行可能ファイルを直接実行できるのは仕様かどうか

### ISSUE THREAD

**Issue by k-kagari** [sakura-editor/sakura#1705]
「クリッカブルURL」とは、テキスト中に現れる URL をエディタが認識し、ダブルクリック操作で参照可能にする機能のことです。この機能についてヘルプでは以下のように説明されています。

<blockquote>
テキスト中のURLをダブルクリックすると、Windowsのシェルを介して関連付けされたアプリケーション（Webブラウザ等）にURLを渡します。
URLは以下のものを認識します。関連付けされたアプリケーションがない場合、開くことができません。
</blockquote>

「URLスキームに関連付けされたアプリケーションにURLを渡す」機能であると読み取れますが、この文言は機能の全容を説明していません。`file://C:/Windows/System32/notepad.exe` のように URL が実行可能ファイルを指しているとき、対象ファイルそのものが実行されることになるためです。

この issue で確認したいのは、この「実行可能ファイルを実行する」挙動が意図されたものであるかどうかです。以下の点を懸念しています。

- ユーザーにとって予想できない挙動ではないか？
- 悪用が可能ではないか？

仕様でなければ実行を抑制する修正が必要ですし、仕様とするのであっても警告を表示するなどの改善を加えるのが望ましいではないかと思います。ご意見をお聞かせください。

**Comment by berryzplus** [comment]
「仕様通り」じゃないですかね。
　👆コレは「仕様漏れだと思う」と言ってます。

話がちょっとややこしいんですけど・・・
* 「https:///hostname/path/to/file」をダブルクリックしたときの期待動作は、対象のパスにあるコンテンツがブラウザで取得され、コンテンツタイプに応じて表示されたりダウンロードされたりする、だと思います。
* 「https:///hostname/path/to/file.exe」をダブルクリックしたときの期待動作は、対象のexeがダウンロードされる、だと思います。
* 「file:///hostname/path/to/file.html」をダブルクリックしたときの期待動作は、対象のhtmlがブラウザで表示される、だと思います。
* 「file:///hostname/path/to/file.exe」をダブルクリックしたときの期待動作は、対象のexeがダウンロードされる、だと思います。
* 「file:///C:/path/to/file.exe」をダブルクリックしたときの期待動作は、対象のexeが実行される、だと思います。
* 「C:\\path\\to\\file.exe」をダブルクリックしたときの期待動作は、対象のexeが実行される、だと思います。

クリッカブルURLには引数を指定できないので、この機能を悪用してなんらかの害を与えることが可能か？というと微妙だと思いますが、上記の挙動をギリギリ理解できる程度のPC初心者に対してこの不具合に関連した詐欺行為をはたらいたり精神的な暴行をくわえることは可能かもしれません。

**Comment by sanomari** [comment]
不具合ですね。

クリッカブルURLをクリックしたときの挙動は、関連付けられたプログラムにURLパスを渡して起動することが期待されます。ローカルexeパスに対してはexeそのものが起動してしまうのは期待外れだと思います。

ブラウザで開けるかどうかを判定する関数と指定したローカルファイルパスを関連付けられたプログラムで開く関数を追加すると整理がしやすそうです。

**Comment by sanomari** [comment]
Microsoft Edgeで試してみました。

| パス | 結果 |
| ---- | ---- |
| file:///C:\work\sakura-editor\Win32\Debug\sakura.exe | ダウンロードされる |
| file:///C:\work\sakura-editor\Win32\Debug\sakura.ini | ブラウザで表示される |
| C:\work\sakura-editor\Win32\Debug\sakura.exe | クリッカブルURLにならない |
| C:\work\sakura-editor\Win32\Debug\sakura.ini | クリッカブルURLにならない |

以上より、対処不要と判断します 😄

**Comment by berryzplus** [comment]
> 以上より、対処不要と判断します 😄

・・・であるならクローズ可能と思いますがどうでしょう。
個人的には、想定通りの結果で、j危険性もないように思います。

怪しいのは標準ブラウザが Internet Explorer である場合の挙動ですが、IEは既にマイクロソフトでさえ「利用を推奨しない」と公言している古代のブラウザなので、何か問題があったとしても「使うやつが悪い」で良い気がします。

**Comment by sanomari** [comment]
あれ？対応しますって。

**Comment by Ry0taK** [comment]
本件をメールで報告した者です。
@sanomari 大変申し訳ございません、メールを送信する際にCCへの追加漏れがあり、情報に齟齬が生じてしまっているようです。詳細を記載したメールスレッドのCCへ追加したため、お手数ですがメールの受信ボックスをご確認いただけますでしょうか。
