### ISSUE TITLE
キーボードフォーカスが当たっていないテキストボックスの文字列が選択状態になっていることがある

### ISSUE THREAD

**Issue by yoshinrt** [sakura-editor/sakura#1717]
## 問題内容
どこかの段階で仕様変更があったのでしたらご容赦ください．

Grep 置換ダイアログや，ツールバーの検索ボックス (設定で追加) に過去履歴文字列が現れるとき，キーボードフォーカスが当たっていないにもかかわらず，文字列が選択状態になっています．
他にあるかは未確認です．

![スクリーンショット 2021-08-27 202647](https://user-images.githubusercontent.com/32790691/131120581-4c7f5446-ef93-433a-8f0d-d16e15e41e85.png)

## 期待する動作
- 過去リビジョンに合わせるなら，未選択
- 新しく選択状態の仕様になったのでしたら，灰色選択
  - ツールバーの選択状態は目立つので，できれば未選択が希望です

## 再現手順
1. Grep 置換で何か置換を実行する
1. 再び Grep 置換ダイアログを表示すると，置換前 と 置換後の両方が選択状態

または

sakura 起動直後の状態で，ツールバーに足した検索ボックスの文字列が選択状態

## 再現頻度
100%

## 問題のカテゴリ
- プログラムの動作上の問題

## 環境情報
- OS バージョン
Win10 Pro 64bit

- サクラエディタバージョン
```
サクラエディタ   v2.4.2.1160 32bit dev
(GitHash 2deb79197c608f00897453a762d9178d07fc59e5)
(GitURL https://github.com/sakura-editor/sakura)

      Compile Info: V1929 WPR WIN601/I800/C000/N601
      Last Modified: 2021/7/31 21:13:37
```

**Comment by yoshinrt** [comment]
git bisect してみました．直接の原因ではないかもしれませんが．
Grep ダイアログとツールバーは別のところで挙動の差分が出ました．

- Grep ダイアログ: 4a7b4aa7e0ec0e482b8b50814b8635a5bfa300ff
- ツールバー: 61c5cf849f2cde638cbe4bd33f452fc798af5f94

> Windows側で変則DarkModeにしているんだと思いますが、

タイトルバーの色のことでしたら，Win10 標準の色を変える機能です．(個人用設定→色)
sakura の挙動に関わる変な物は使ってない... はず...

**Comment by usagisita** [comment]
「外部コマンド実行(ファイル名を指定して実行)」の「カレントディレクトリ」でも同様の現象が見られます。
カレントディレクトリのチェックが外れていてグレーダウンしているときも背景の青い表示になります。
なお当方の環境はWin8.1です。
2.3.0.1ぐらいのときは選択状態ではなかったと思います。

**Comment by beru** [comment]
> 「外部コマンド実行(ファイル名を指定して実行)」の「カレントディレクトリ」でも同様の現象が見られます。
> カレントディレクトリのチェックが外れていてグレーダウンしているときも背景の青い表示になります。
> なお当方の環境はWin8.1です。
> 2.3.0.1ぐらいのときは選択状態ではなかったと思います。

こちらの環境 (Windows 10 バージョン 20H2) ではこの現象は見られませんでした。

実装内容を見てみたところ、`CDlgExec::SetData` でコンボボックスのアイテムを追加しているので、`OnCbnDropDown` メソッドを追加して、まだコンボボックスに要素が追加されていない場合（初回）にアイテムを追加するような対策で解消するかもしれないですね。

**Comment by usagisita** [comment]
追加で調査したところ、普段使いの少し古いバージョンでは発生し、master/HEAD最新版では発生しないらしいことが分かりました。
手元のバイナリで残ってるものとbisectで探した感じでは、
aa615db6
* 印刷ページ設定ダイアログのフォントが巨大化する問題を修正
このコミットで修正されたようです。
お手数おかけしました。

**Comment by beru** [comment]
#1719 と #1724 のMergeにより報告された問題は解消したと思うので Close します。
