### ISSUE TITLE
外部コマンド実行でキャンセルした時のメッセージが異なる

### ISSUE THREAD

**Issue by usagisita** [sakura-editor/sakura#1720]
## 問題内容
外部コマンド実行でキャンセルする時、特定操作で

```
(印刷プレビューでのみ使用できます)
終了コード: 0
```

と明らかに関係ないメッセージが表示されます。

## 再現手順
1. 外部コマンド実行で名前「notepad」「標準出力を得る」「アウトプットウィンドウ」でコマンドを実行します。
2. アウトプット画面が表示されたら閉じます。
3. notepadの終了待ちのダイアログをキャンセルします。
4. 2個目の新しくできたアウトプットウィンドウに上記メッセージが表示されます。

## 再現頻度

該当操作なら100%

## 問題のカテゴリ
- 仕様の問題
- プログラムの動作上の問題
  - 正式リリース版
  - Appveyor ビルド版

## 環境情報
- Windows 8.1
- サクラエディタバージョン
サクラエディタ   v2.4.2.3898 32bit dev
(GitHash 369ee0605f73c35290f766906a2e61150d8f3bf0)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2021/7/30 22:21:32

## 原因
https://github.com/sakura-editor/sakura/blob/2deb79197c608f00897453a762d9178d07fc59e5/sakura_core/view/CEditView_ExecCmd.cpp#L573
=> COutputAdapterDefault::OutputW
=> COutputAdapterDefault::OutputBuf
=> m_pCShareData->TraceOutString
と関数を経由しますが、バッファがコピーされる前に(コメント修正済み)画面操作などの要因で、LSのバッファが上書きされるのだと思われます。

**Comment by beru** [comment]
デバッグしてみました。 (現時点の master の HEAD 2deb79197c608f00897453a762d9178d07fc59e5)

```
CEditWndProc
CEditWnd::DispatchEvent
  case WM_ACTIVATEAPP:
CEditWnd::UpdateCaption
CSakuraEnvironment::ExpandParameter
  const wstring	PRINT_PREVIEW_ONLY		= LS( STR_PREVIEW_ONLY );	//L"(印刷プレビューでのみ使用できます)";
CLoadString::LoadStringSt
```

こういう流れでアクティブになった際にタイトルを更新する処理が走りますが、そこで static method の `CSakuraEnvironment::ExpandParameter` を呼び出していてそこの冒頭で `LS` マクロを使ってます。

**Comment by beru** [comment]
#1721 によって報告して頂いた問題は解消されたと思いますのでCloseします。
