### ISSUE TITLE
置換後にタブに変換できない、正規表現使えないような

### ISSUE THREAD

**Issue by misogihagi** [sakura-editor/sakura#1723]
## 問題内容
正規表現にチェックを入れて置換前に「a」とか適当な文字いれて置換後に「¥t」みたいに正規表現いれると
a -> ¥t
みたいにタブにならずに「¥t」の文字列がそのまま置換される。
こんな仕様でしたっけ？

## 問題のカテゴリ

- 仕様の問題
- プログラムの動作上の問題
  - 正式リリース版
## 環境情報
- OS バージョン
Windows 10 Pro 64bit 
- サクラエディタバージョン
サクラエディタ   v2.4.1.2849 32bit (tag v2.4.1)
(GitHash ee8234f65fd7a69116e07e819c6972b246eda926)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2020/5/30 03:10:34

**Comment by usagisita** [comment]
v2.4.2.3898で確認しましたが、\tはタブに置換されました。
`\t` (U+005c)ではなく`¥t` (U+00a5)を使っていると、それはバックスラッシュではないので、タブには置換されないはずです。
あり得る状況としては、\またはtまたは\tが全角になっていると、同様にタブへの置換にはなりません。
そういうことではないですか？

**Comment by misogihagi** [comment]
そのとおりでした！
テレワーク始まって端末変わってからバックスラッシュと思っていたものは円記号でした。
表示は同じなので区別つきませんでした…
chromebook色々面倒ですね…
