### ISSUE TITLE
GB2312のエンコードをできる欲しい

### ISSUE THREAD

**Issue by leehonleon** [sakura-editor/sakura#1725]
## (必須) やりたいこと(=実現したいこと)

エンコードGB2312のファイルを開けたいですが、提供されていません。
ご対応よろしくお願いいたします。

**Comment by usagisita** [comment]
`文字コードセット`の`CP`をONにすると
・`10008 (MAC - 簡体字中国語 GB 2312)`
・`20936 (簡体字中国語 GB2312)`
・'54936 (GB18030 簡体字中国語)'
というのがあると思います。
自動選択はありませんが、手動で選ぶことでおそらく使えると思います。
‘タイプ別設定‘の`ウィンドウ`で`デフォルトの文字コード`に設定することもできます。

**Comment by arigayas** [comment]
`設定(O)` → `文字コードセット指定(A)` で出るダイアログボックス。

### デフォルト：
![image](https://user-images.githubusercontent.com/11251874/133884734-71941722-2c84-4765-98fa-75faf8811521.png)

![image](https://user-images.githubusercontent.com/11251874/133884518-c24a2582-da6c-48b4-9d2d-d089d86c4f3b.png)

### `CP` をON：
![image](https://user-images.githubusercontent.com/11251874/133884745-a25ea320-da9c-4bc6-ae62-923080d1607b.png)
10008 (MAC - 簡体字中国語 GB 2312)
![image](https://user-images.githubusercontent.com/11251874/133884707-9d7664f6-a72f-4ec6-8979-21e51ec8a7f9.png)
20936 (簡体字中国語 GB2312)
![image](https://user-images.githubusercontent.com/11251874/133884788-c03728f5-94d0-4cb6-992a-78c4fc72f1f8.png)
![image](https://user-images.githubusercontent.com/11251874/133884844-fbfe5f7f-7a24-4bbe-8443-48707be6e9d6.png)

サクラエディタ   v2.4.1.2849 32bit (tag v2.4.1)
(GitHash ee8234f65fd7a69116e07e819c6972b246eda926)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2020/5/30 03:10:34

**Comment by leehonleon** [comment]
その機能があるとは良かったですが,gb2312で保存したファイルを開けると自動的にエンコードを読み込んで開けたいです。utfと同じようなこと。

**Comment by berryzplus** [comment]
これは一旦「解決」ですかね？

### 現状
* 既存機能で一応開ける

### 機能改善例
* サクラエディタ独自の「文字コードセット名」に中国語等の文字セットを追加する。
* サクラエディタに指定できる「文字コードセット名」を標準化する（≒既存の独自定義を廃止）。

なんとなく、目的は達成できてそうに見えました。

**Comment by berryzplus** [comment]
解決済みのようなのでクローズします。

追加対応が必要であれば、新しく issue 起こしてください。
