### ISSUE TITLE
トリプルクリック時に次の行の先頭にURLがあるとそれが選択されてしまう

### ISSUE THREAD

**Issue by nishidemasami** [sakura-editor/sakura#1745]
## 問題内容
トリプルクリックで行を選択しようとした時に、次の行の先頭にURLがあると、トリプルクリックした行が選択されず、その次の行の先頭にあるURLの文字列だけが選択されてしまう。
トリプルクリックでそのまま指を離さないでドラッグによる選択をする時にも同様。

## 再現手順
設定：「共通設定」→「編集」タブ→「クリカッブルURL」の「クリックでURLを選択する」にチェックをする。

1行目に文字列、2行目にURLを書く。
1行目をトリプルクリックする。
→1行目が選択されず、2行目のURLの文字列が選択されてしまう。

1行目に文字列、2行目にURLを書く。
1行目をトリプルクリックし、そのまま指を離さずドラッグする。
→選択が1行目からではなく、2行目のURLが起点となって選択されてしまう。

※URLは、「設定」→「タイプ別設定」→「正規表現キーワード」でURLとしている文字列も同様。

## 再現頻度
100%

## 問題のカテゴリ
- 仕様の問題

## 環境情報
- OS バージョン
Windows 10 Pro 64bit
- サクラエディタバージョン
v2.4.1.2849 32bit (tag v2.4.1)
(GitHash ee8234f65fd7a69116e07e819c6972b246eda926)
(GitURL https://github.com/sakura-editor/sakura.git)

よければよろしくおねがいします。

**Comment by beru** [comment]
#1753で対処をしたのでCloseします。
