### ISSUE TITLE
グローバル関数GetEditWnd()の実装を再検討する

### ISSUE THREAD

**Issue by sanomari** [sakura-editor/sakura#1746]
const autoをC style castでconst外ししているため、キャストで強制型変換が可能になっており、もしCEditWnd::getInstance()の部分のコードが、CEditView*とか予期せぬ変な型に変更されたとしても、エラーが検出されなくて、この書き方は若干危険な予感がします。
非constを返すことが確定している以上、pcEditWndはconstで受けずautoだけにしてキャストを削除するか、const_castを使ったほうが安全です。ただconst_castはどうしても取り回しが難しいときに限定的に使うもので、こういうときは前者の対応方法をしたほうがいいと思います。

_Originally posted by @usagisita in https://github.com/sakura-editor/sakura/pull/1744#r731460994_

**Comment by berryzplus** [comment]
このissueで解決したい問題（？）は解決してそうに見えました。

周辺課題が色々ありますが、それば別のissueを起こしたほうが分かりやすいような。
