### ISSUE TITLE
入力補完がEnterで確定できない、補完ウィンドウの幅が不正

### ISSUE THREAD

**Issue by usagisita** [sakura-editor/sakura#1749]
## 問題内容

・入力補完で特定の文字列を確定しようとするとEnterが入力されて補完が確定できない
・補完候補ウィンドウの幅や高さが調整されず、小さいウィンドウが表示されることがある

## 再現手順

STR_BACKUP_CONFORM_MSG1
STR_BACKUP_CONFORM_MSG2
と画面に入力して改行しておきます。
「STR」と入力後、Ctrl+Spaceで入力補完を起動します。
小さい補完画面が表示されます。
「Enter」で確定しようとしても、Enterが入力されてしまい、補完できません。

## 再現頻度

いつも

## 問題のカテゴリ
- プログラムの動作上の問題
  - ローカルビルド版

## 環境情報
- Windows8.1 / 11
- 2.4.2.0(ローカルビルド)
- PC情報
正式リリース版の2.4.1では再現しませんでした。
2020-10-25 2318efb6 以降あたりだと思われます。

## スクリーンショット

なし

https://github.com/sakura-editor/sakura/blob/0dd4391776be5530ef4d0a66e8279ace744d3dd6/sakura_core/apiwrap/StdControl.cpp#L119
ここで「capacity() <= 」で比較していますが、capacityがresizeした領域ぴったりだった場合に、条件が成立してしまい、return falseになってしまいます。
基本的には d4a3547c と同根だと思われます。

**Comment by kazasaku** [comment]
> ・補完候補ウィンドウの幅や高さが調整されず、小さいウィンドウが表示されることがある

25ccc53996d1b4e148cb2fe674c98348e013c22f 以降で発生を確認しました。
