### ISSUE TITLE
バージョン情報で git の commit hash を表示する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#18]
バージョン情報で git の commit hash を表示すると便利だと思います。

[SubWCRev](https://tortoisesvn.net/docs/nightly/TortoiseSVN_ja/tsvn-subwcrev.html) と同様のプログラムで
[GitWCRev](https://tortoisegit.org/docs/tortoisegit/tgit-gitwcrev-keywords.html) というプログラムも存在するが、
TortoiseGit がインストールされていないと使えない。

[Appveyor の Build environment](https://www.appveyor.com/docs/build-environment/#version-control-systems) には
TortoiseGit がリストにはない。

ただ通常の git コマンドだけでも以下のようなバッチファイルで、git の commit hash を
取り出せるので、svnrev.h のようなファイルを作ることも可能だと思う。

```
@echo off
for /f "usebackq" %%s in (`git show -s --format^=%%H`) do (
    set COMMITID=%%s
)

echo %COMMITID%

```

**Comment by m-tmatma** [comment]
#19 でプルリクエスト投げました。

**Comment by berryzplus** [comment]
良いと思います。

GitHub移行作業の一環として、rev表示も新環境に合わせるのが筋かと思います。

Git-showのオプションで最新コミットの情報を出せた気がするのでバッチファイルの中身は要検討かなと思っています。

**Comment by kobake** [comment]
#19 マージ済みなのでこちらも閉じます。
