### ISSUE TITLE
利用するCI/CDサービスを一本化できないか検討する

### ISSUE THREAD

**Issue by kazasaku** [sakura-editor/sakura#1809]
## やりたいこと
利用するCI/CDサービスをGitHub Actionsに一本化したい。

## やりたい理由
1. どのCIサービスでビルドしたか識別できるようにする必要がある
2. 各CIサービスの使い分けが不明確
   - 逆に言えば、複数サービスを併用するなら何かしらの理由で使い分けた方がいいと思っています。
3. AppVeyorは…
   - 並列実行できないため、ビルドの完了を長時間待機しなければならない。
     - 単体テストが増えるにつれて、さらに時間を要するようになるかもしれません。
   - 機能の制約が多いため、自前でいろいろな処理を用意しなければならない。
4. Azure Pipelinesは…
   - ジョブを並列実行するためには追加の申請手続きが必要である。
     https://docs.microsoft.com/en-us/azure/devops/pipelines/licensing/concurrent-jobs?view=azure-devops&tabs=ms-hosted
     > We have temporarily disabled the free grant of parallel jobs for public projects and for certain private projects in new organizations. However, you can request this grant by submitting a request.

## GitHub Actionsを選んだ理由
- GitHubに統合されているため、フォークリポジトリなら特に設定せずとも使えます。
- Azure Pipelinesからフォークされたサービスなので、おおむね同じ使い方ができます。
  - AZPはビルトインタスクが複数定義されいますが、GHAもGitHub Marketplaceに公開されている様々なタスクを利用できます。
  - AZPとGHAは、どちらも [actions/virtual-environments](https://github.com/actions/virtual-environments) の仮想イメージを利用しており、仮想環境のソフトウェア構成が同じです。実行ユーザーにOSの管理者権限が付いてくるのも同様。

## 検討課題
- [ ] parse-buildlog.py の扱い（参照： #1669 ）
- （他に見つかり次第追記しますが、各自でも何かあれば自由に追記してください。）

## 関連
- #10
- https://github.com/sakura-editor/management-forum/issues/65
- #1259 
  - #1263 
- #1687

**Comment by kazasaku** [comment]
（…とりあえず立ててみた。）

**Comment by takke** [comment]
私もGHA一本化がいいと思います。

**Comment by berryzplus** [comment]
一本化は、「誰かが勝手にやる」で良いように思っています。
レビュアーの確保が難しいので、自分はレビュー側に回ります。

前提としてAZPのみで実施しているMinGWビルドをGHAで実施するようにactionsを実装する必要があります。
AppveyorとAzure Pipelinesのビルドを止めるのは、依頼があれば自分が実施できるはずです。（たぶん

AppveyorとAzure Pipelinesのためのバッチは、消してしまったほうが分かりやすい気がしています。
消さなくてもよいですが、ルートフォルダのファイルが多過ぎる問題を緩和するために、少なくともルートフォルダから外したい気がします。

**Comment by berryzplus** [comment]
タスクリストを更新してみました。

**Comment by m-tmatma** [comment]
- [x] Azure Pipeline のみ実装されていた JOB を GitHub Actions に移植
- [x] Azure Pipeline の JOB を削除
- [x] appveyor の JOB を stop 
- [x] appveyor.ymlを削除
- [x] ci/appveyor/* を削除
- [x] appveyor のビルドトリガー設定をoffにする
- [x] azure-pipelines.yml を削除
- [x] ci/azure-pipelines/* を削除
- [x] appveyor_env.pyを削除
- [x] parse-buildlog.batを削除
- [x] parse-buildlog.pyを削除
- [x] SonarQube.md（要更新：内容がAzure Pipelines用のため、削除）
- [x] ci/build-batchfiles.md（要更新）
- [x] ci/build-envvars.md（要更新）
- [x] sakura/githash.bat（要更新：AppVeyor専用の環境変数が残存している）

**Comment by berryzplus** [comment]
SonarQube.mdについては、やり方の最新化も検討したいです。

要点

1. SonarQubeのServerまたはCloudからBuildWrapperをダウンロードする
2. BuildWrapperを使ってプロジェクトをビルドする
3. テストを実行してカバレッジをとる
4. SonarScanを実行してSonarQubeのServerまたはCloudに結果を送信する

やってることは当初から変わっていないのですが、SonarColudがSonarQube Cloudに改名していたり、SonarSourceがGitHub Actions用の [SonarSource/sonarqube-scan-action](https://github.com/SonarSource/sonarqube-scan-action) を公開していたりで若干状況が変わっています。

**Comment by berryzplus** [comment]
sakura/githash.batについてCMakeターゲットにできないか考えてます。
一旦作業を完了させてから考えるのでよいと思ってます。

**Comment by m-tmatma** [comment]
残件

- [ ] SonarQube.md（要更新：GHA用の記述に修正すべき）

**Comment by berryzplus** [comment]
> 残件
> 
> * [ ]  SonarQube.md（要更新：GHA用の記述に修正すべき）

@m-tmatma さん 書いてみました。

https://github.com/berryzplus/sakura-editor/blob/master/tools/SonarQube/README.md

- 開発者が欲しい情報
- 開発者に伝えたい情報
- ユーザーが欲しい情報
- ユーザーに伝えたい情報

SonarQubeのREADMEに含めたいのはどれだ？　ってなって放置している感じです。
