### ISSUE TITLE
googletest による単体テストを導入する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#181]
https://github.com/sakura-editor/management-forum/issues/10

googletest による単体テストを導入する

- googletest は GitHub で管理されているので git submodule で取り込む
- appveyor では git submodule init/git submodule update を実行する
- googletest は cmake でビルドする
- googletest は  https://github.com/google/googletest/releases/tag/release-1.8.0 を使う
- テストコードは tests ディレクトリ以下に配置する
- googletest 本体もtests ディレクトリ以下に配置する
- このチケットのスコープは何らかの単体テストができれば OK とする

**Comment by m-tmatma** [comment]
このチケットのスコープは何らかの単体テストができれば OK とする

**Comment by berryzplus** [comment]
「調査」ってラベルいらないですかね。

なんとなく「UnitTest」のラベルの付け所のイメージがわいてないです。

**Comment by kobake** [comment]
> googletest は cmake でビルドする

コンソールからビルド・実行するイメージですか？

個人的にはテストコードも VS から実行できたほうが手元でのテストの確認がしやすくてありがたいです。

**Comment by kobake** [comment]
あ、すみません、 https://github.com/sakura-editor/management-forum/issues/10#issuecomment-399754538 で言及されてましたね。googletest が cmake しか今後サポートされなそうということであれば仕方ないです。

**Comment by kobake** [comment]
> visual studio でテストコードをデバッグできます。好きなところにブレークポイント張ってデバッグできます。

お、すばらしいです！まさにそこを気にしていました

**Comment by m-tmatma** [comment]
> googletest は  https://github.com/google/googletest/releases/tag/release-1.8.0 を使う

忘れてたけど release-1.8.0 だと、以下の警告が出て、警告がエラーとなる設定なので
ビルドが失敗する。


```
  tests\googletest\googletest\include\gtest\gtest-printers.h(600): warn
ing C4996: 'std::tr1': warning STL4002: The non-Standard std::tr1 namespace and TR1-only machinery are deprecated and w
ill be REMOVED. You can define _SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING to acknowledge that you have received this wa
rning. [tests\build\googletest\googlemock\gtest\gtest.vcxproj]


```

最新版だと
https://github.com/google/googletest/issues/1595
のエラーになる。

PR を投げているけどマージされないまま放置されている。
https://github.com/google/googletest/pull/1606

**Comment by KENCHjp** [comment]
>PR を投げているけどマージされないまま放置されている。

お、これは誰が怠慢なのかな。。。？？？。。。

**Comment by berryzplus** [comment]
> PR を投げているけどマージされないまま放置されている。
> https://github.com/google/googletest/pull/1606

変更箇所の意図が通じてない気配を感じたので応援コメントしてきました。

あのファイルは元々UTF-8っぽいです。
「いったい何を変更したんだ？」とか
「なんで変更が必要なんだ？」とか思われてたのかな、と。

**Comment by m-tmatma** [comment]
> 変更箇所の意図が通じてない気配を感じたので応援コメントしてきました。

ありがとうございます。

> あのファイルは元々UTF-8っぽいです。

違います。

https://github.com/google/googletest/pull/1588 (
https://github.com/google/googletest/commit/b539167cf0254f521b791e908f6d3a5ff3f30245)

で修正されるまでは UTF-8 ではありませんでした。

**Comment by m-tmatma** [comment]
#311 で単体テストの枠組みを導入したのでクローズ。
