### ISSUE TITLE
インストール後、メニューを英語に設定して保存

### ISSUE THREAD

**Issue by birdjumper** [sakura-editor/sakura#1826]
## 問題内容
インストール後、メニューを英語に設定して保存したいですができません。sakura_lang_en_US.dllを利用しています。毎回サクラを起動して、設定する必要があります。

## 再現頻度
毎回起動するとき

- 仕様の問題
- プログラムの動作上の問題

## 環境情報
- OS バージョン
　　- Windows 10 Pro 64bit 
- サクラエディタバージョン
　　- 2.4.1

宜しくお願いします。

**Comment by arigayas** [comment]
自分の環境(*1)では英語に設定(*2)して
サクラエディタの終了時に設定を変更したのを保存しますか？的なメッセージダイアログ(*3)が出て
Yesを選んでサクラエディタを再度起動したら英語のメニューでサクラエディタが起動しました。

なので念のために英語に設定した方法を詳細に書いて欲しいです。

*1
Windows 10 Pro 64bit 日本語版
サクラエディタ   v2.4.1.2849 32bit (tag v2.4.1)
(GitHash ee8234f65fd7a69116e07e819c6972b246eda926)
(GitURL https://github.com/sakura-editor/sakura.git)

Compile Info: V1916 WPR WIN601/I800/C000/N601
Last Modified: 2020/5/30 03:10:34

*2 ： ツールバーの設定→共通設定→共通設定ダイアログの「ウィンドウ」タブの「言語」を「English(United States)」
![image](https://user-images.githubusercontent.com/11251874/163474785-cb1b7d7a-ca5d-484b-9093-c176ca872b13.png)

*3
![image](https://user-images.githubusercontent.com/11251874/163475478-7bf792c7-da0b-4767-b9a8-51c4d5fb4ad6.png)

**Comment by k-takata** [comment]
インストール先や設定の保存先はどこにしてますか？

**Comment by birdjumper** [comment]
arigayasさん

返事が遅くなって失礼しました。

> 自分の環境(*1)では英語に設定(*2)して サクラエディタの終了時に設定を変更したのを保存しますか？的なメッセージダイアログ(*3)が出て Yesを選んでサクラエディタを再度起動したら英語のメニューでサクラエディタが起動しました。

(*1) と（*2）は全く一緒ですが（*3）のものは出ません。

標準のインストールしました。それはだめでしたかなー、、、

**Comment by birdjumper** [comment]
> インストール先や設定の保存先はどこにしてますか？

インストール先：
C:\Program Files (x86)\sakura\sakura.exe

保存先：
あちこちsakura.exe.iniがあるのでどちを利用しているかちょっとわからない、、、

**Comment by berryzplus** [comment]
インストール先が
`C:\Program Files (x86)\sakura\sakura.exe`
なら、`sakura.exe.ini`の場所は
`C:\Program Files (x86)\sakura\sakura.exe.ini`
です。ここ以外の`sakura.exe.ini`は無視されます。

インストーラを使った場合、`sakura.exe.ini`の設定内容は以下です。
https://github.com/sakura-editor/sakura/blob/1c6bc820dce8c8397ecd33aec63dd75ea3dd0ca3/resource/sakura.exe.ini#L26-L28

この設定だと`sakura.ini`の場所は`%APPDATA%\sakura\sakura.ini`です。
※`%USERPROFILE%\Application Data\sakura`を見に行きますがWindowsにリダイレクトされて`%APPDATA%\sakura`になります。

インストーラを使わずにインストールする場合、`sakura.exe.ini`を自分で用意することになります。

**Comment by birdjumper** [comment]
返事が遅くなってすみません。
インストールはインストーラを使いました。
現在「sakura.exe.ini」と「sakura.exe.ini」は以下のディレクトリに入っています：
C:\Program Files (x86)\sakura
この状態で英語メニューの設定を保存できますか？
再インストールをしないといけませんか？
宜しくお願いします。

**Comment by berryzplus** [comment]
インストーラーってこれですかね？
[sakura-tag-v2.4.1-build2849-ee8234f-Win32-Release-Installer.zip](https://github.com/sakura-editor/sakura/releases/download/v2.4.1/sakura-tag-v2.4.1-build2849-ee8234f-Win32-Release-Installer.zip)

`Windows 10 1809`の仮想マシンで試してみた限り、このインストーラーは壊れてなさそうです。
インストーラーの説明に出てきますが、マルチユーザー設定を外すと動かないことが多いです。

**Comment by birdjumper** [comment]
またご返事ありがとうございます。

どのインストーラを使ったか覚えていませんがバージョン情報を見たら：
Sakura Editor   v2.4.1.2849 32bit (tag v2.4.1)
(GitHash ee8234f65fd7a69116e07e819c6972b246eda926)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2020/5/30 03:10:34
があります。
再インストールの必要がありますか？
sakura.iniを編集で対応できますか？
宜しくお願いします。

**Comment by berryzplus** [comment]
> 再インストールの必要がありますか？

一度アンインストールして、再度インストールするのが早いと思います。

> sakura.iniを編集で対応できますか？

`sakura.ini`を編集しても参照されないので効果がないです。
`sakura.exe.ini`の編集なら改善を期待できますが、サクラエディタは`C:\Program Files (x86)`配下のファイルを編集できないのでどこかに一時フォルダにコピーしてから編集し、変更後ファイルを元のフォルダに貼り付ける感じになります。(貼り付け時に管理者権限が必要です。)

ちゃんと説明してませんでしたが、`sakura.exe.ini`と`sakura.ini`は別モノで、役割が異なります。
* `sakura.exe.ini` = マルチユーザー設定ファイル、`sakura.ini` の格納場所を設定します。
  このファイルは`sakura.exe`と同じフォルダに格納する必要があり、格納位置は変更できません。
  ファイルがない場合、`sakura.ini`を`sakura.exe`と同じフォルダに作ろうとしますが、Windows Vista以降では`C:\Program Files (x86)`配下に書き込みできないので設定を保存できなくなってしまいます。
  このファイルで`Multiuser=0`を設定すると、ファイルがないのと同じになります。おそらくコレです。
* `sakura.ini` = 設定ファイル、共通設定ダイアログでの変更を格納します。

**Comment by birdjumper** [comment]
@berryzplus またご返事ありがとうございました。
では再インストールします。
再インストールする時に、何か特別オプションを選びますか？（どこかでそんなん読んだ気がします。）
宜しくお願いします。

**Comment by berryzplus** [comment]
> 再インストールする時に、何か特別オプションを選びますか？（どこかでそんなん読んだ気がします。）

最後に表示される確認画面で「Virtual Store：無効」となるようにしてみてください。

**Comment by birdjumper** [comment]
ご返事ありがとうございましたです。インストールする時にそうします。

実は今日Sakuraを起動した時、英語メニューが出ました。

どうして分からへんですが、最近のWindowsアップデートが関係あるか、色んなアプリケーション関係設定ファイルを整理しながら、もっとステーブルスになったかなー。

今度更新しないといけない場合があったら、この情報をまた参考します。

これが他の英語（日本語も！）を話すユーザーを助けるなら、幸せになります。

色々皆さん、ありがとうございました。

**Comment by kengoide** [comment]
解決している様子なので close します。
