### ISSUE TITLE
リソース編集を行っただけでビルド時に関係ない compiletests が動いてしまう

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#1828]
## 問題内容

表題の通りです。

## 再現手順

- リソースファイル `sakura_core/sakura_rc.rc` を編集する
- Visual Studioでビルドする
- 下記のメッセージが表示されてビルドに時間が掛かる

<details>
<summary>メッセージ</summary>

```
1>  -- Checking clayoutint_can_not_be_additive_assigned_from_clogicint
1>  -- Checking clayoutint_can_not_be_additive_assigned_from_clogicint - done
1>  -- Checking clayoutint_can_not_be_subtractive_assigned_from_clogicint
1>  -- Checking clayoutint_can_not_be_subtractive_assigned_from_clogicint - done
1>  -- Checking clayoutint_can_not_be_added_by_clogicint
1>  -- Checking clayoutint_can_not_be_added_by_clogicint - done
1>  -- Checking clayoutint_can_not_be_subtracted_by_clogicint
1>  -- Checking clayoutint_can_not_be_subtracted_by_clogicint - done
1>  -- Checking clayoutint_can_not_be_assigned_from_clogicint
1>  -- Checking clayoutint_can_not_be_assigned_from_clogicint - done
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_less_than
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_less_than - done
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_less_or_equal
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_less_or_equal - done
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_greater_than
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_greater_than - done
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_greater_or_equal
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_greater_or_equal - done
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_equal
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_equal - done
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_not_equal
1>  -- Checking clayoutint_can_not_be_compare_with_clogicint_not_equal - done
1>  -- Checking clayoutint_can_not_be_assigned_to_int
```

</details>

## 再現頻度

常に再現する

## 問題のカテゴリ

- ビルドの問題
  - ローカルビルド

**Comment by berryzplus** [comment]
試しても再現しませんでした。

ソースにはビルド済みターゲットをビルドしない設定が入っています。
https://github.com/sakura-editor/sakura/blob/1c6bc820dce8c8397ecd33aec63dd75ea3dd0ca3/tests/compiletests.targets#L14

以下の入力ファイル群と出力ファイルのタイムスタンプを見比べて、出力側が新しければ再実行されないようなMsBuildの記述になっています。
https://github.com/sakura-editor/sakura/blob/1c6bc820dce8c8397ecd33aec63dd75ea3dd0ca3/tests/compiletests.targets#L7-L9

Visual Studio IDEからのビルドではMsBuildのビルド制御が100%は機能しないので絶対大丈夫とは言い切れませんが、自分が動かしてる限りでは大丈夫そうです。

困るようなら対策考えますがどうでしょう？

**Comment by beru** [comment]
うーん、今試してみたら再現しませんでした。報告した時には起きていたんですが…。

**Comment by berryzplus** [comment]
Visual Studio IDEからビルドするときはMsBuildのステータス管理とは別のビルドステータスを使っているようで、「ソリューションのビルド」と(プロジェクトの)「ビルド」で動きが違うことがあるようです。いまプロジェクトのビルドでも再現しないので察するに「実は初回ビルドだった」のではないかと思います。（あるある

**Comment by beru** [comment]
いや、リソースファイルを編集してビルドを繰り返すたびに同じメッセージ `-- Checking clayoutint_` が表示されてそこで毎回数秒程度時間が掛かっていたので、初回ビルドだけではなかったです。ただ再現しないので、変なもん食って幻でも見ていたんだろと仮に言われたとしても文句が言えない気もします。

**Comment by beru** [comment]
再現しないので閉じます。もし再現させる方法が分かったらOpenしなおします。
