### ISSUE TITLE
タブの描画・ホイールでの選択順序の問題

### ISSUE THREAD

**Issue by dep5** [sakura-editor/sakura#1845]
## 問題内容
タブバー表示時に操作に影響の出る問題が発生します。

## 再現手順
タブバーを表示します。

1. 新規タブを開きます。「(無題)数字」と表示されたタブが開きます。
タブをクリックすると「(無題)」と変わり数字が消えます。
（いくつか開いた後閉じると終了時に時間がかかっています。）

2. 「設定」「共通設定」「タブバー」「マウスホイールでタブ切替」を有効にします。
新規タブをいくつか開いた後、タブ上にマウスを移動し、ホイールを下に回します。
タブが切り替わるごとに上のようにタブのテキストが変化します。
今度はホイールを上に回すと最近開いたタブ2つだけが切り替わり続けます。
また下に回すと先ほどのタブだけ順序が変わってしまい、左から順番に開けなくなります。
上下に回しているうちに左から開くはずの順番がめちゃくちゃになってしまいます。
タブを5個開いたとしてホイールを
下に回す`1234512345…`
上に回す`3434343434…`
下に回す`1243512435…`
といった感じです

3. https://github.com/sakura-editor/sakura/issues/1844#issuecomment-1134149122
kazasakuさんの話とも似ているのですが
タブを切り替えると閉じたはずのタブが残っていたり（選択しても何も起きない）
タブを切り替えるごとにタブの表示順やタブの数が異なるということもありました。
…が、これは2/11以前からあったような気もします…

## 再現頻度
3はいつの間にかなっていますが、1と2は確実に起きます。

## 問題のカテゴリ
- プログラムの動作上の問題
  - ローカルビルド版

## 環境情報
- OS バージョン
 Windows 10
 Windows 8.1

- サクラエディタバージョン
 Ver. 2.4.2.0
- PC情報

**Comment by dep5** [comment]
`git reset`しながらさかのぼったところ
2022/2/11の変更でこの現象が起きているようです。
ためしに
```
cd mydir
powershell Invoke-WebRequest https://github.com/sakura-editor/sakura/pull/1794.patch -OutFile 1794.patch
git apply -R 1794.patch
```
としてビルドしたところ以上の症状はなくなりました。
PRのどの部分が影響しているのかまでは調べられませんでした。

**Comment by usagisita** [comment]
sakura_core\env\CAppNodeManager.cpp
BOOL CAppNodeGroupHandle::AddEditWndList( HWND hWnd )
・(   181,15   ): 		if( 0 == ::GetWindowLongPtr( hWnd, sizeof(LONG_PTR) ) )
・(   184,7    ): 			::SetWindowLongPtr( hWnd, sizeof(LONG_PTR) , (LONG_PTR)pShare->m_sNodes.m_nSequences );
hWndは編集ウィンドウなのでEditWndなのですが
HWND CEditWnd::_CreateMainWindow(int nGroup, const STabGroupInfo& sTabGroupInfo)
	wc.cbWndExtra		= 0;
1794で32バイトあったWndExtraが0にされてしまっているので、読み書きに失敗している、のでしょうね。

**Comment by dep5** [comment]
#1794 の変更を元に戻してしばらく使っていますが、1番目2番目の問題は解消し、
今のところ3番目の現象も起きていません。
もっと前からあったように思いましたが、これが原因だったんでしょうか…？

**Comment by dep5** [comment]
usagitaさん
詳しい説明ありがとうございます。
wc.cbWndExtraの値の変更の影響なのですね。
#1794 まるごと元に戻す必要は無さそうですね。
ビルドする時間ができたら試してみたいと思います。

kazasakuさん
保存時のタイトルについては気づかなかったです。
タブの問題と同時に修正されるといいですね。

**Comment by dep5** [comment]
テストしてみましたが、
window/CEditWnd.cpp の wc.cbWndExtra だけの変更でも
タブの描画は正常になるみたいですね。

作者の方の対応を待つことにします。

**Comment by dep5** [comment]
https://github.com/sakura-editor/sakura/pull/1850#issuecomment-1144647769 (レベル2) を適用して使っていますが、
ホイールを回した場合を含めて、すべての問題が解消していると思います。
