### ISSUE TITLE
Escでサクラエディタヘルプを終了する機能について

### ISSUE THREAD

**Issue by dep5** [sakura-editor/sakura#1890]
sakuraとpluginの全ページでitem.js が読み込まれています。
Escキーで画面を閉じ、chmでなければ目次へのリンクを表示する機能が実現されています。

chmはサポート終了したIEの機能で動いており、コンテンツを画像とテキストに限定するのも選択肢かと思います。
IEコンポーネントのサポートが終わったわけではありません。

1. Escキーでヘルプを閉じる機能は必要ですか？
2. 目次へのリンクはどうしたらいいですか？

いらなければ作業するつもりです。

**Comment by berryzplus** [comment]
1. はローカルで作業するとき便利です。
  人によってはESCを誤って押して「勝手に閉じられて困る」かも知れません。
  HTML Helpそのものについて「このまま使う？（≒廃止しない？）」の話があると思っています。
2. は[これ](https://sakura-editor.github.io/help/HLP000135.html)とか見てください。
  左上隅の`[目次]`リンクがスクリプトで生成されてます。
  実装が雑なので、削るとなると全ページに修正が発生します。
  あっても邪魔ではない気がします。

これね。
https://github.com/sakura-editor/sakura/blob/bdc9d6fd7ba04e4a34cd416966103fd861f86541/help/sakura/res/item.js#L26-L30

jqueryで書き直したほうが分かりやすくなると思いますが、ちょっとハードル高いと思います。

**Comment by dep5** [comment]
berryzplusさん
ありがとうございます。

この機能を削除してもよいかもと思いましたが、
便利に使われているということが分かりましたのでクローズします。
