### ISSUE TITLE
異体字（IVS）への対応

### ISSUE THREAD

**Issue by c-ysik** [sakura-editor/sakura#1899]
## 問題内容
現在 Sakura Editor 2.4.2 を使用していますが、文字列中に異体字（IVS が付与された文字）があると正字の後ろに豆腐文字（.notdef グリフ）が表示されてしまいます。
IVS に対応したグリフ（グリフがない場合は正字）を表示するようにしていただくか、せめて IVS コードにより表示される豆腐文字を表示せずに正字のみを表示するよう対応していただければと思います。

## 再現手順
IVS が付与された文字（「葛󠄀」「龍󠄁」「半󠄁」など）を入力する。

## 再現頻度
IVS を含む文字がある場合常に発生する。

## 問題のカテゴリ
- 仕様の問題
- その他の問題

## 環境情報
- OS バージョン
Windows 10 Pro 22H2 64bit

- サクラエディタバージョン
サクラエディタ32bit Ver. 2.4.2.6048 Appveyor (a3e63915b)
(GitHash a3e63915b3c3236a9f14fbb27a01cf7acb030f45)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2022/12/4 15:21:56

- PC情報
プロセッサ	Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz   3.19 GHz
実装 RAM	32.0 GB (31.8 GB 使用可能)
システムの種類	64 ビット オペレーティング システム、x64 ベース プロセッサ

## スクリーンショット
![IMG_20230110_135808](https://user-images.githubusercontent.com/46473628/211465684-be0329b7-535f-414c-a989-f9827373d5d7.png)

**Comment by berryzplus** [comment]
## 関連issue
* #595
* #1284

## 参考URL
* [Wikipedia 異体字セレクタ](https://ja.wikipedia.org/wiki/%E7%95%B0%E4%BD%93%E5%AD%97%E3%82%BB%E3%83%AC%E3%82%AF%E3%82%BF)

**Comment by t-tk** [comment]
通りがかりですが
異体字セレクタ対応 https://github.com/sakura-editor/sakura/issues/1214 のところにIssueが立っています。

**Comment by tats-u** [comment]
DirectWriteでないと対処できない問題ですか？現行のGDIでもいけますか？

**Comment by berryzplus** [comment]
IVSへの対応だけであればGDIでも「技術的に可能」と思われます（検証はしていません。）

Windows GDIのAPI関数には文字の代わりにフォントグリフを指定するモードがあるので対応可能と思われます。
WindowsにはUniscribeというUnicodeのコードポイント群を解析するためのAPIセットがあります。
Uniscribeを使うと、指定したUnicode文字列に対応するフォントグリフの配列を生成できます（ここが未検証。）

現代的な文字表示を行う場合にまずDirectWrite対応を検討するのは、カラー絵文字のフォントグリフを色付きで描画できるのがDirectDrawのみで、DirectWriteとDirectDrawの親和性が比較的高いためためと考えられます。

**Comment by tats-u** [comment]
DirectWrite/DirectDrawでもIVS対応にUniscribeの利用は必須ですか？

**Comment by berryzplus** [comment]
DirectWrite/DirectDrawでUniscribeを使う必要はないと思ってます。
同様に、GDI関数にも内部的にuniscribeを呼んでくれるものがあると思ってます。

**Comment by tats-u** [comment]
GDIでも対応→DrirectXxxでも対応と二度手間を強行するか、DirectXxxへの移行時についでにやるか・・・
当方Windows APIには詳しくないのでおいそれと手が出せそうにないのが残念なところです。

**Comment by berryzplus** [comment]
この辺も直さないとダメそう。
これは描画前に文字幅配列を生成するための関数の一部です。

https://github.com/sakura-editor/sakura/blob/d08365027b888d687030527409f86584dab1806e/sakura_core/view/CTextMetrics.cpp#L103-L106

IVS（異体字セレクタ）はサロゲートペアになるコードポイントなのでここを通ります。
通らないように修正してあげないと変な描画になります。

**Comment by tats-u** [comment]
> 以下のコードはサロゲートペアを上位サロゲートと下位サロゲートにぶった切らないための細工です。
これを参考にして「正字+IVSセレクタ」を一度に描画するように修正してやれば、「選択フォントによってはIVS文字も正しく表示できる」の状態になります。

1文字として描画させたいUTF-16コードポイントのまとまりを一気に突っ込めばOKならば、朗報ですね。絵文字などにも応用できそうです。（絵文字には👨‍👩‍👦‍👦（UTF-16：11文字 / UTF-32：7文字）などの化け物もいます。将来は独自実装はほどほどにしてICUなどを使わないと苦しくなりそうです）

> Windows 標準のフォントにもIVS未対応のものがある。

日本語フォントだとHG系だけですね。（厳密にはHG系はOffice付属のはず）わざわざ本ソフトのフォントに指定する変人はそうそういないでしょう。
MS系・BIZ UD系・UDデジ教・游系・メイリオ系の他の標準日本語フォント全部がAdobe Japan 1系のIVSに対応しています。（禰󠄀豆子・葛󠄀城市で確認）

**Comment by berryzplus** [comment]
カラー絵文字の描画にはDirectDrawが必要なので、応用と少し違うかも知れません。
一応、多言語対応のAPI [GetStringType](https://learn.microsoft.com/ja-jp/windows/win32/api/stringapiset/nf-stringapiset-getstringtypew) を使えば「結合文字かどうか？」の判定は可能です。

サクラエディタv1まで： レイアウトデータを作ってから描画する設計
サクラエディタv2から： レイアウトデータと呼称するものは作るが、描画やマウスオーバーで毎回計算する設計

「葛󠄀城市」の「葛󠄀」に複数のIVSが存在する件については「知らないフリ」で構わない認識です。
選択中のフォント名やフォントの対応IVSを画面のどこかに表示する対応は、いつか必要なのかも知れません。

個人的にはリボンが良いですが、リボン嫌いな民も多いからなぁ、という。
