### ISSUE TITLE
CIのArtifactsについて

### ISSUE THREAD

**Issue by dep5** [sakura-editor/sakura#1906]
## 問題内容

- Github ActionsとAppVeyor
Asm --- Release
Release-Asm.zipの中身がありません。
#286

- Github Actions
osが`windows-2019`と`windows-2022`の2つありJobsも8個あります。
osに合わせたVisual Studioのバージョン別にJobが用意されていると考えました。
　
Artifactsはどちらのosでビルドされたかわからないように思います。
（後でアップロードされた方で上書きしている？）
全種類アップロードするか、os情報のテキストをzipに入れるかしてもらえないですか？
　
そうかもと思っただけで、違っていたらすいません。
## 問題のカテゴリ

- ビルドの問題
  - Appveyor
  - Github Actions

**Comment by dep5** [comment]
フォーク先のGithub ActionsではJobsが7個同時に動くようなので
`windows-2022, Release, x64`版が後まわしになるので、
`Exe x64 Release`が`windows-2022`版のような気がしています。
見分け方がわからないので、気のせいかもしれません。

**Comment by berryzplus** [comment]
> * Github ActionsとAppVeyor
>   Asm --- Release
>   Release-Asm.zipの中身がありません。
>   [アセンブラ出力を有効にしませんか? #286](https://github.com/sakura-editor/sakura/issues/286)

アセンブラ出力はDebugだけじゃなかったでしたっけ？
ちょっと曖昧です。

> * Github Actions
>   osが`windows-2019`と`windows-2022`の2つありJobsも8個あります。
>   osに合わせたVisual Studioのバージョン別にJobが用意されていると考えました。
>   　
>   Artifactsはどちらのosでビルドされたかわからないように思います。
>   （後でアップロードされた方で上書きしている？）
>   全種類アップロードするか、os情報のテキストをzipに入れるかしてもらえないですか？

指摘通りのバグだと思います。
2 × 2 × 2 ＝ 8セットが4セット分しかない枠にアップロードされてます。
vs2022でのビルドをできるようにしたとき、テキトーにレビューしたのが原因です。
現状は、たまたま後に終わったビルドの内容で上書きされている状態です。

* #1486
で触れている通り、GHAの成果物はあんまり真面目に考えて作ってないのが実情だと思います。

**Comment by dep5** [comment]
berryzplusさん
コメントありがとうございます
#1486 とそこにある #1777 も含めて知りたかったことが書いてありました。


> アセンブラ出力はDebugだけじゃなかったでしたっけ？

PRによってはアセンブラ出力されているということですかね？
それならしょうがないですね。

> 2 × 2 × 2 ＝ 8セットが4セット分しかない枠にアップロードされてます。

ファイルサイズ的に問題なければ必要なセット分の枠が欲しいです。

**Comment by berryzplus** [comment]
## お気持ち
2つの問題を解決しないとcloseできないissueになっています。
問題が2つならissueを分けたいです。

過去のissueも複数の問題を含んだissueは放置される傾向にある気がします。

**Comment by berryzplus** [comment]
#1911 の対応ではダメでしょうか？

> * ASMの出力先パスを変更したのをzip生成バッチに反映していなかった不具合を修正します。
> * 成果物名が複数のVisual Studioバージョンによるビルドを考慮していないのに、複数バージョンでビルドしてしまっていた誤りを是正します。

**Comment by dep5** [comment]
対応が済んだようですのでクローズします
