### ISSUE TITLE
CSVを開いた時の動作が重くなった(2.4.2リリース版)

### ISSUE THREAD

**Issue by satakagi** [sakura-editor/sakura#1914]
## 問題内容
Ver2.4.2でCSVを開くと、それ以前の版と比べて動作が重くなりました

## 再現手順
添付画像の設定をしたあと、たとえば、こちらのCSVを開いてみます。
https://www.npa.go.jp/publications/statistics/koutsuu/opendata/koudohyou/9_koudohyou_rosen_kousokujidousya_jidousyasenyou.csv

## 再現頻度
カラム数が大きめのCSVで発生しているようです。

## 問題のカテゴリ
- プログラムの動作上の問題
  - 正式リリース版

## 環境情報
- OS バージョン
Windows11 Pro x86
- サクラエディタバージョン
 Ver. 2.4.2.6048 

## スクリーンショット
![image](https://user-images.githubusercontent.com/6793745/221067880-715ee74f-4437-45d7-8b3a-30dc23584082.png)

**Comment by beru** [comment]
自分もCSVファイルをダウンロードして設定して読み込んでCSV表示してみたんですが、どこらへんの動作が重くなったのか良く分からないです。

**Comment by berryzplus** [comment]
> カラム数が大きめのCSVで発生しているようです。

[Azure Monitor](https://learn.microsoft.com/ja-jp/azure/azure-monitor/app/app-insights-overview?tabs=net)のtracesログをエクスポートしたCSVファイルを開いて試してみました。

* tracesログは31カラムあります。
* **カラムの区切りを正しく認識できない** 事象を確認しました。
* **横スクロール時に固まる** 事象を確認しました。
* ファイルオープン時の操作遅延があるかどうかは判別できませんでした。

確認した2件の事象はいずれも不具合のように見えますが、
**横スクロール時に固まる** はv2.4.1では発生していなかったようです。

**Comment by beru** [comment]
[9_koudohyou_rosen_kousokujidousya_jidousyasenyou.zip](https://github.com/sakura-editor/sakura/files/10891450/9_koudohyou_rosen_kousokujidousya_jidousyasenyou.zip)

[9_koudohyou_rosen_kousokujidousya_jidousyasenyou.csv](https://www.npa.go.jp/publications/statistics/koutsuu/opendata/koudohyou/9_koudohyou_rosen_kousokujidousya_jidousyasenyou.csv) ファイルの列を複製して512列にしたcsvファイルを読んでみましたが、動作が重いという現象は確認出来ませんでした。

ただEndキーを押して行末に移動するとソフトが終了してしまう不具合を確認しました。デバッグして原因を調べてみると、`CRuler::DrawRulerBg` メソッドで nMaxLineKetas (10240) より keta の値が大きくなる為に結果的に負の値が size_t 型のローカル変数に代入され、極端に大きい値が `std::vector::resize` メソッドに渡されて落ちている事が分かりました。

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/1131125/222952183-9c6925e0-1c63-4210-a3b4-b3aaa95bc908.png)

</details>

**Comment by astanabe** [comment]
2.4.2のインストーラ版を使用していますが、CSV・TSVのファイルオープン、スクロールが極端に遅くなる現象がこちらでも発生しています。
2.4.1のインストーラ版では起きていません。
再現するCSVファイルを作成しましたので添付しました。
[hogehoge.csv](https://github.com/sakura-editor/sakura/files/11194484/hogehoge.csv)
どうやら、文字列の少ないセルと文字列の多いセルが入り混じっていると起きるようです。

**Comment by beru** [comment]
> 2.4.2のインストーラ版を使用していますが、CSV・TSVのファイルオープン、スクロールが極端に遅くなる現象がこちらでも発生しています。
> 2.4.1のインストーラ版では起きていません。
> 再現するCSVファイルを作成しましたので添付しました。
> [hogehoge.csv](https://github.com/sakura-editor/sakura/files/11194484/hogehoge.csv)
> どうやら、文字列の少ないセルと文字列の多いセルが入り混じっていると起きるようです。

デバッグしてみたところ、`CFigure_Comma::DispSpace` で `ExtTextOut` を呼び出す際に `szViewString` の文字数が 64 を超過すると `pMetrics->GetDxArray_AllHankaku()` で取得する領域の範囲外参照が発生する為問題に繋がるようです。 [link](https://github.com/sakura-editor/sakura/blob/9e8fa57da5823fc394a10dd666bc30b36a4b9167/sakura_core/view/figures/CFigure_Comma.cpp#L89-L102)

`CTextMetrics::m_anHankakuDx` の型は `std::array<int, 64>` なので。 [link](https://github.com/sakura-editor/sakura/blob/9e8fa57da5823fc394a10dd666bc30b36a4b9167/sakura_core/view/CTextMetrics.h#L123)

**Comment by kengoide** [comment]
範囲外参照は致命的ですね…。

`m_anHankakuDx` の中身は固定値です。余白＋コンマが64文字を超える場合は、バッファをその場で用意してその場で同値を書き込むように変更すれば範囲外参照は解決できます。
https://github.com/sakura-editor/sakura/blob/9e8fa57da5823fc394a10dd666bc30b36a4b9167/sakura_core/view/CTextMetrics.cpp#L65

今週末まで私用で動けないので来週に解消PRを出します（先に動いてくださる方がいらっしゃれば急ぎでレビューします）。

**Comment by berryzplus** [comment]
63文字までしか想定してない関数に
64文字以上渡した場合にメモリ確保するんです？

というツッコミをPR書いてしまう前に入れときます。

**Comment by beru** [comment]
試しに `CFigure_Comma::DispSpace` で `ExtTextOut` を呼び出す際の `lpDx` 引数を NULL に変えても特に問題は無さそうです。描画する文字列の内容が `,` の後に半角空白を追加しているだけだからですかね？

**Comment by berryzplus** [comment]
## なんとなく思っていること
* CEditViewにCSVモードが実装されているのは誤りなのではないか？
  * CEditView の役割　≒　プレーンテキストを表示して編集できるUIを提供する。
  * CSVモードの役割　≒　CSV(Character Separated Values)を表示して編集できるUIを提供する。

これは一般的なオブジェクト指向設計の指針[「単一責務の原則 Single Responsibility principal 」](https://ja.wikipedia.org/wiki/SOLID)に反している気がします。

もっとも、サクラエディタは基本的にC言語で書かれたプログラムなので、オブジェクト指向言語の設計指針に従っていないからと言って一概に「誤りである」とも言えないような気はします。

## で、どうするの？
妥当性を検証できる回答は提示できません。

これまで通り「やりたい人がやりたいように提案する」で進めて行ったらよいと思います。
