### ISSUE TITLE
文字コードの初期値をUTF-8にしてほしいです。。。

### ISSUE THREAD

**Issue by haya-ken** [sakura-editor/sakura#1917]
（自由記述）
・今のwindowsの文字コードは、UTF-8になっています！
・実は ”メモ帳” の文字コードもUTF-8に変わっています！
・それなので、サクラエディタの初期の文字コードも【UTF-8】にしてほしいです。

よろしくお願いします！

![_無題 - メモ帳 2023_03_19 日 12_57_20](https://user-images.githubusercontent.com/25399727/226152760-02465a8b-6fd0-4bb2-a2cd-6e98ba49a6d0.png)

**Comment by arigayas** [comment]
念のため質問です。
お使いになっているサクラエディタのバージョンは何でしょうか？

上書きのバージョンアップするとデフォルトの文字コードがUTF-8じゃないかもしれませんが、
真っさらなサクラエディタ(zip版)をダウンロードして解凍して実行すると、
最新バージョンならデフォルトの文字コードがUTF-8になっていると思います。
参照： #600 #604 #706 

何も設定を変更しない状態での最新バージョンのVer2.4.2のスクリーンショット
![image](https://user-images.githubusercontent.com/11251874/226155918-161d03ba-8750-440d-827e-1fe4875e46c3.png)

何も設定を変更しない状態での「名前を付けて保存」ダイアログボックス
![image](https://user-images.githubusercontent.com/11251874/226155972-81ffbc7f-3d31-4e61-baeb-5fad48eac12c.png)

**Comment by haya-ken** [comment]
さっそくの回答ありがとうございます！
私が使っているｖ2.4.1です。
最新だとUTF-8なんですね！
さっそくダウンロードしてみます。
ありがとうございました！

**Comment by arigayas** [comment]
文字コードの初期値がUTF-8でしたら、このIssueをCloseして欲しいです。
