### ISSUE TITLE
Vistaスタイルのファイルダイアログでファイルの作成確認が余計に行われる

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#1930]
## 問題内容

共通設定の編集の `Vistaスタイルのファイルダイアログ` にチェックを付けると、Common Item Dialog (IFileOpenDialog と IFileSaveDialog) が使われます。

そのダイアログでファイルを選択して開く際に、ファイルを選択するとファイル名の欄に選択したファイル名が入ります。

その後、ファイル名の欄に何か文字 (例えば `a`) を入力するとファイルを作成するかを確認するメッセージボックスが表示されます。

![image](https://github.com/sakura-editor/sakura/assets/1131125/fa09dc49-fc36-4151-8da7-9ace49af2e49)

またフォルダ移動時に、ファイル名の個所にそのフォルダに存在しないファイル名が入っていると同様のメッセージボックスが表示されます。

ファイルを作成する意図が無いのにも関わらず、いちいちこのメッセージボックスが頻繁に表示されると操作がしづらいので良くないです。

## 問題のカテゴリ

- プログラムの動作上の問題

## 環境情報
- OS バージョン

- サクラエディタバージョン

- PC情報

**Comment by berryzplus** [comment]
なんというか、既知のバグを報告しておきます。

既存のファイルダイアログには、上書き確認メッセージを表示するカスタムが施されているのですが、アイテムダイアログにはこれが移植されてないっぽいです。
https://github.com/sakura-editor/sakura/blob/efff59306719526df9aef089ebfd1d4e713635af/sakura_core/dlg/CDlgOpenFile_CommonFileDialog.cpp#L452

文字列リソース `STR_DLGOPNFL3`の定義が（おそらく）誤っており、新旧比較すると差になります。

誤： "名前を付けて保存"
正： "名前を付けて保存の確認"

これ直しても誰も嬉しくなさそうなので黙ってました。
アイテムダイアログに関しての説明では、「既存機能の一部が移植されていないかも」という話になると思います。

**Comment by berryzplus** [comment]
以下がcppで定義されているために、単体テストが記述不能である点が気になっています。

* `struct CDlgOpenFile_CommonFileDialog` 旧来のOFNダイアログ実装。
* `struct CDlgOpenFile_CommonItemDialog` Vista以降のアイテムダイアログ実装。

このプロジェクトで「エンジニアリングしたい民」はどうも自分だけのようなので、他の人が気にならないなら放置で良いと思っています。

**Comment by beru** [comment]
> 以下がcppで定義されているために、単体テストが記述不能である点が気になっています。
> - struct CDlgOpenFile_CommonFileDialog 旧来のOFNダイアログ実装。
> - struct CDlgOpenFile_CommonItemDialog Vista以降のアイテムダイアログ実装。

`tests/unittests/test-cdlgopenfile.cpp` のテストを増やしたいという事でしょうか？

Interface関数以外の内部実装の単位テストを細かく書いてしまうと、内部実装を調整した際に単体テストの保守も行う必要が出てくるので大変な気が個人的にします。ただ他の人が何かの理由でやりたいのであればあえて止めはしません。

`struct CDlgOpenFile_CommonFileDialog` と `struct CDlgOpenFile_CommonItemDialog` の定義をヘッダファイル (例えば `sakura_core/dlg/CDlgOpenFile.h` とか？)に引っ越しするとかですかね。

> このプロジェクトで「エンジニアリングしたい民」はどうも自分だけのようなので、他の人が気にならないなら放置で良いと思っています。

テストも自動化しないとですね。https://github.com/appium/appium-windows-driver を今度使ってみます。

**Comment by beru** [comment]
```
FOS_CREATEPROMPT
Value: 0x2000
Prompt for creation if the item returned in the open dialog does not exist. Note that this does not actually create the item.
```

この値が [CDlgOpenFile_CommonItemDialog::DoModalOpenDlgImpl1](https://github.com/sakura-editor/sakura/blob/5b6a9279db6a9910b742e6af43d2c2e7705bc378/sakura_core/dlg/CDlgOpenFile_CommonItemDialog.cpp#L614) で使われているのが、ファイルの作成確認が余計に行われる原因である事を確認しました。

**Comment by beru** [comment]
> なんというか、既知のバグを報告しておきます。
> 
> 既存のファイルダイアログには、上書き確認メッセージを表示するカスタムが施されているのですが、アイテムダイアログにはこれが移植されてないっぽいです。

把握していなかったので、上書き確認メッセージがどう異なるかを動作確認してみました。

### 既存のファイルダイアログ (実装 `CDlgOpenFile_CommonItemDialog`) の上書き確認メッセージ

![image](https://github.com/sakura-editor/sakura/assets/1131125/4c323a1f-4bba-40dd-ad88-e3400264195f)

### Vistaスタイルのファイルダイアログ (実装 `CDlgOpenFile_CommonItemDialog`) の上書き確認メッセージ

![image](https://github.com/sakura-editor/sakura/assets/1131125/7ca910fb-95e4-4fca-8e44-d075aaafcffe)

------

メッセージボックスのタイトルが異なりますね。berryzplusさんが書いたように "名前を付けて保存の確認" が正しいと思います。

他に気づいた点として、ファイルパスが既存のファイルダイアログはフルパスで表示されていますが、Vistaスタイルのファイルダイアログではファイル名だけが表示されています。

どちらも些細な点だと思うので更新しなくても良いと思いますが、仮に変更するとしたら `CDlgOpenFile_CommonItemDialog::OnOverwrite` に実装を追加すれば良さそうです。

https://github.com/sakura-editor/sakura/blob/1e920c7622ed400a7ebfe629d4fd0b54569dcc48/sakura_core/dlg/CDlgOpenFile_CommonItemDialog.cpp#L356-L361

**Comment by beru** [comment]
#1932 がmergeされてこのissueの問題は解消されたと思うのでcloseします。
