### ISSUE TITLE
丸カッコを含むURLの解釈が変

### ISSUE THREAD

**Issue by katahiromz** [sakura-editor/sakura#1933]
## 問題内容
Microsoft Learnなどの一部のサイトが半角丸カッコを含むURLを使用している。
現状のサクラエディタでは半角丸カッコを含むURLの解釈がうまく行かず、間違ったURLへのリンクになってしまう。

## 再現手順
半角丸カッコを含むURLを入力する。

## 再現頻度
常に再現する。

## 問題のカテゴリ

- 仕様の問題
- プログラムの動作上の問題
  - 正式リリース版
  - Azure Pipelines ビルド版
  - Appveyor ビルド版
  - ローカルビルド版

## 環境情報
- OS バージョン
Windows 10 Home 64bit
- サクラエディタバージョン
2.3.2.0
- PC情報
なし。

## スクリーンショット
なし。

**Comment by katahiromz** [comment]
URLの解釈については、おそらくRFC3986を採用する方が安全だと思われます。

**Comment by katahiromz** [comment]
すみません。間違えました。閉じます。

**Comment by berryzplus** [comment]
まぁ、面倒くさいですよね。
[WM_CREATE](https://learn.microsoft.com/ja-jp/windows/win32/winmsg/wm-create?redirectedfrom=MSDN&devlangs=cpp&f1url=%3FappId%3DDev16IDEF1%26l%3DJA-JP%26k%3Dk(WINUSER%252FWM_CREATE)%3Bk(WM_CREATE)%3Bk(DevLang-C%252B%252B)%3Bk(TargetOS-Windows)%26rd%3Dtrue)

RFC3986に従えば丸括弧は予約文字で、URLに使わないほうがよい文字に該当します。
https://www.asahi-net.or.jp/~ax2s-kmtn/ref/uric.html

なので、Microsoft learnのURLがおかしい、が結論になります。

とは言え、使い勝手が悪いのでなんとかしたい、はアプリ改善に至る重要な「気付き」だと思うので「Microsoft〇ね！」で終わるのも違うような気はします。

URL検出はサクラエディタ独自仕様が激しくて手を付けられない部分の1つですけどね。

**Comment by katahiromz** [comment]
丸カッコを使用していたのは、Microsoft Learnではなくて古いMSDNの方でした。訂正します。

**Comment by berryzplus** [comment]
貼ったURLはMicrosoft DocsサイトのWM_CREATEメッセージ解説ページです。

「URIパラメーターはURLとは違うんじゃぁ」と言われても寂しいですが、最新のURLでもパラメーター部分に丸括弧が含まれています。Outlookでもリンク検出がおかしいことはあるので、仕方ないと思っています。
