### ISSUE TITLE
Build RequirementsでVisual Studio 2022対応明記

### ISSUE THREAD

**Issue by tats-u** [sakura-editor/sakura#1944]
（自由記述）

サクラエディタはOSSであり、通常はCommunityが使用できない中・大企業でもCommunityを利用しての検証やソースビルドが可能なので、最新版の2022にしませんか？

> Sakura Editor をコンパイルするためには、 Community または Professional エディション以上の [Visual Studio 2017](https://visualstudio.microsoft.com/ja/vs/older-downloads/) または [Visual Studio 2019](https://visualstudio.microsoft.com/ja/downloads/) が必要です。

**Comment by pea-sys** [comment]
サクラエディタをコンパイルするために、Visual Studio 2019 Communityをインストールしようと思いましたが、
今はインストールできないようになっているように見えます。
新規でコントリビュートする方を募るために、バージョンアップすることに賛成します。

![ss](https://github.com/sakura-editor/sakura/assets/49807271/f449c5cf-31c0-4a09-9303-37334d19d445)

**Comment by pea-sys** [comment]
サクラエディタをコンパイルするために、Visual Studio Community 2019をダウンロードしようと思いましたが
現在はダウンロードできなくなっていそうです。VisualStudioのバージョンアップに賛成します。
![ss](https://github.com/sakura-editor/sakura/assets/49807271/67f8c853-643a-41af-93f9-7a196674173c)

**Comment by tats-u** [comment]
`git blame vcx-props\vcxcompat.props`したところ、<https://github.com/sakura-editor/sakura/commit/93cf3f3eacfed6a4d0a2c30d5445b53b2599db3c>で対応が入っていました。

**Comment by tats-u** [comment]
C++20以降に移行してほしい身としては対応していない2017はそろそろ切ってほしいところです
秋頃にはVS2025が出そうですし
