### ISSUE TITLE
ドキュメント類の整理やリンク切れの対策などを行う

### ISSUE THREAD

**Issue by kurages** [sakura-editor/sakura#1946]
先ほどPR出す際に何点か気づいたので起票しました

- ~~コントリビューター向けにCONTRIBUTING.mdを設置する~~
    - ~~[wiki](https://github.com/sakura-editor/sakura/wiki/11.SakuraEditor_PRGuide)に書いていても気付けないです（READMEに目を通してなかったせいですが）~~
    - ~~既存wikiへのリンクを張るだけでもGitHubが用意している方法で記載すると何倍も分かりやすくなります。(PR作成画面にリンクが表示されます)~~
- [wiki](https://github.com/sakura-editor/sakura/wiki/11.SakuraEditor_PRGuide)の下部リンクなど、リンクが切れてしまっているのでciでチェックするのが望ましいと思います
    - wikiだとci走らないっけ、、、？

**Comment by kurages** [comment]
.githubかdocsしか把握してなかったのでmoveしようとしましたがリポジトリルートでも表示されるって書いてますね
PR画面に表示されなくなったのかな:thinking:

https://docs.github.com/ja/communities/setting-up-your-project-for-healthy-contributions/setting-guidelines-for-repository-contributors

**Comment by kurages** [comment]
github actionは設定できるようですがwikiだとPRがないのでリンク切れの対策などが難しそうですね
案があれば実装してみます

**Comment by kurages** [comment]
ざっくり確認してwikiでリンク切れしてる部分について気づいている箇所を書いておきます

---

Home.md

チームはorgのメンバーでないと404になるようです。
```diff
- [sakura-developers](https://github.com/orgs/sakura-editor/teams/sakura-developers) に名前のある人がマージ権限を持ちます。
+ [sakura-developers](https://github.com/orgs/sakura-editor/people) に名前のある人がマージ権限を持ちます。
```

---

License.md

名前解決できなくなってしまってますが移行先はどこでしょうか、、、
```
## 過去の議論

過去の議論については以下のリンクを参照してください。

- http://sakura.qp.land.to/?Develop%2FLicenses
```

---

Download-Links.md

```diff
- - [ダウンロード(ポータル)](https://sakura-editor.github.io/download.html) ... 旧verのインストーラーはここに置いています。
+ - [ダウンロード(ポータル)](https://sakura-editor.github.io/old_download.html) ... 旧verのインストーラーはここに置いています。
```

---

11.SakuraEditor_PRGuide.md
"AppVeyor 関連について"は移行先が分からなかったです
```diff
-    - [AppVeyor 関連について ](https://github.com/sakura-editor/sakura/blob/master/appveyor.md)
+    - [AppVeyor 関連について ](https://github.com/sakura-editor/sakura/wiki/Appveyor)
-    - [Azure Pipeline 関連について](https://github.com/sakura-editor/sakura/blob/master/azure-pipelines.md)
+    - [Azure Pipeline 関連について](https://github.com/sakura-editor/sakura/wiki/azure-pipelines%E3%83%A1%E3%83%A2)

```

---
リリース時にやること.md

このリリース作業はなくなった？
```diff
  ### Web の更新

- - https://sakura-editor.github.io/download.html を更新する。
  - リポジトリは https://github.com/sakura-editor/sakura-editor.github.io です。
```

**Comment by kengoide** [comment]
ご確認ありがとうございます。変更内容が自明な Home.md と Download-Links.md に限り、取り急ぎご指摘通りに更新させていただきました。

**Comment by kengoide** [comment]
> License.md

いま確認したところ閲覧可能でした。そのままにしておきます。

**Comment by kengoide** [comment]
ご指摘いただいた箇所については全て修正したので一旦クローズさせてください。追加の提案があれば別途起票願います。
