### ISSUE TITLE
Visual Studio 2019以前をサポート外とする

### ISSUE THREAD

**Issue by tats-u** [sakura-editor/sakura#1954]
（自由記述）

関連：#1944 

#1952 でクローズ予定にされたので切り離します

2017を切るメリット・動機

- C++20・C17は2017に対応していない
- Express 2017 for Windows Desktopへの言及を不要化

2019を切るメリット・動機

- 今後C++23モードが入らない（2019のC++20モードは最後の16.11で追加された。2025が出るかその直前あたりに2022にC++23対応モードが入ることが期待できる）

よくある懸念

- ライセンス：[サクラの開発においてCommunity版は企業でも特例でOK](https://visualstudio.microsoft.com/ja/license-terms/vs2022-ga-community/)
- C++ランタイム：[2015以降のもののセットで配布されているので2022版だけ個別で・・・ということはない](https://learn.microsoft.com/ja-jp/cpp/windows/latest-supported-vc-redist?view=msvc-170)

**Comment by berryzplus** [comment]
WinUI3のプロジェクトテンプレートは規定でC++17対応になっていますが、準拠レベルをC++20にするとビルドエラーが出たような気がします。（要検証。）

近年のVCランタイムは Visual Studio 2015 互換 で、vs2017,vs2019,vs2022で作成したプログラムのためにランタイムDLLを追加する必要はない仕様になっています。今後どうなるか不明ですが「そろそろ打ち切られるかも？」と思ってます。

**Comment by tats-u** [comment]
> 準拠レベルをC++20にするとビルドエラーが出たような気がします

本当ならばちょっとまずいですね。検証が必要な点には変わりありませんが。

> 近年のVCランタイムは Visual Studio 2015 互換 で、vs2017,vs2019,vs2022で作成したプログラムのためにランタイムDLLを追加する必要はない仕様になっています。

メジャーバージョンが14のままですからね。今後は2017～2025（2028）セットになるかもしれません。
とはいえ.NET Framework 4系みたいにコードベース共通でターゲットバージョンによって細かい挙動を変えてたりするんでしょうかね。

**Comment by berryzplus** [comment]
@tats-u 
「現時点では不可能」の結論で一旦閉じませんか？

**Comment by tats-u** [comment]
@berryzplus タグをつけて必要時に再度開くならアリです。
タグだけつけて放置でも構いません。

**Comment by berryzplus** [comment]
> @berryzplus タグをつけて必要時に再度開くならアリです。 タグだけつけて放置でも構いません。

どんなタグでしょう？

仕組み上はLabelかprojectを割り当てできます。
既存のLabelに該当がなければ追加していいと思います。

ラベル「pending」を付加し、再開条件をコメントしたら一旦閉じる、とかですね。

**Comment by tats-u** [comment]
ラベルです。

> ラベル「pending」を付加し、再開条件をコメントしたら一旦閉じる、とかですね。

アリです。

**Comment by berryzplus** [comment]
ラベル追加しました。 https://github.com/sakura-editor/sakura/issues/labels

再開条件コメントして閉じておいてもらえるとありがたいです。

**Comment by tats-u** [comment]
WinUI3がC++20以降に対応するなど、VS2019を積極的に排除すべき要件が今後出てきたら再度開くものとします。
