### ISSUE TITLE
Shift-JISのうち、IBM拡張文字由来のローマ数字が正常に表示されない

### ISSUE THREAD

**Issue by kofrah** [sakura-editor/sakura#1959]
## 問題内容

- Shift-JISのうち、IBM拡張文字由来のローマ数字(文字コード:`FA4A` ~ `875D`)が正常に表示されません。　　
- NEC特殊文字由来(文字コード:`8754` ~ `FA53`)の方は正常に表示されます。
- v1.6.7のサクラエディタでは正常に表示されます。
- 現在のふるまいが正常（私の仕様読み落とし）でしたら申し訳ないです。。

## 再現手順

1. バイナリエディタ(Stirling)で、ローマ数字(IBM拡張文字)の文字コードが書かれたファイルを作成
2. サクラエディタ(v2.4.2)で開く
3. 正常に表示されない
## 再現頻度

必ず発生

## 問題のカテゴリ

- 仕様の問題
- プログラムの動作上の問題
  - 正式リリース版

## 環境情報
- OS バージョン

```
エディション	Windows 11 Home
バージョン	22H2
```
- サクラエディタバージョン

```
サクラエディタ32bit Ver. 2.4.2.6048 Appveyor (a3e63915b)
(GitHash a3e63915b3c3236a9f14fbb27a01cf7acb030f45)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V1916 WPR WIN601/I800/C000/N601
      Last Modified: 2022/12/4 15:21:56
```

## スクリーンショット

- バイナリエディタのスクリーンショット
![mojibake_ibm_binary](https://github.com/sakura-editor/sakura/assets/116234916/8d229668-4171-4a96-812d-13f3ef3dc4e3)

- サクラエディタのスクリーンショット
上...v2.4.2
下...v1.6.7
![mojibake_ibm](https://github.com/sakura-editor/sakura/assets/116234916/d93fa95f-825c-4334-a9eb-8bbed0eac9e7)

**Comment by berryzplus** [comment]
結論として、UNICODE版の仕様通りです。
個人的には仕様バグと考えていますが、形式的には「仕様通り」が正しいと思います。

* v1系の内部コードは Windowsコードページ932(Shift JIS) です。
* v2系の内部コードは UNICODE(UTF-16LEを独自拡張したもの) です。
* サクラエディタv2は Windowsコードページ を UNICODE に変換するとき、逆変換できるかどうかをチェックします。
* 逆変換で元に戻らない文字は 正しく変換できなかった文字 として独自方式のエンコードを行います。
* 正しく変換できなかった文字 は化けます。（独自方式エンコードのデコードを実装していないため。）

指摘された「正常に表示されない文字」は「Shift JIS → UNICODE → Shift JIS で元に戻らない文字」と考えられます。

と、ここまで書いて同じ説明を以前書いたことがあったのを思い出しました。
https://github.com/sakura-editor/sakura-editor.github.io/issues/74

IVS対応と似た理屈で多少の改善は可能かも知れません。

**Comment by kofrah** [comment]
承知しました。ご確認ありがとうございました！
仕様通りということで、本issueはcloseにさせていただきます。
