### ISSUE TITLE
githas.h <- version.h <- app_constants.h <- stdafx.h の依存を見直して不必要な再コンパイルを少なくする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#198]
https://github.com/sakura-editor/sakura/pull/193#issuecomment-401522679

`そもそも githash.h の影響範囲が大きすぎる (githas.h <- version.h <- app_constants.h <- stdafx.h) ので、別件としてインクルード場所をもう少し絞りたいと思いました。
`

app_constants.h で GSTR_APPNAME が定義されているが、
29 個の cpp ファイルで使用されている。

GSTR_APPNAME は以下で定義されている。

https://github.com/sakura-editor/sakura/blob/587069f36193f0bb8ebe16ff844b7dde09dd1e67/sakura_core/config/app_constants.h#L46-L57

ALPHA_VERSION が以下で定義されているので version.h に依存しているが、

https://github.com/sakura-editor/sakura/blob/587069f36193f0bb8ebe16ff844b7dde09dd1e67/sakura_core/version.h#L49-L51

ALPHA_VERSION を分離すれば、app_constants.h は version.h に依存する必要はない。

**Comment by berryzplus** [comment]
シンボル ALPHA_VERSION の役割を考えるとこのヘッダに移動ですかね。

https://github.com/sakura-editor/sakura/blob/587069f36193f0bb8ebe16ff844b7dde09dd1e67/sakura_core/config/build_config.h#L27

app_constants.h より前にインクルードされてますので。

https://github.com/sakura-editor/sakura/blob/587069f36193f0bb8ebe16ff844b7dde09dd1e67/sakura_core/StdAfx.h#L46-L52

**Comment by m-tmatma** [comment]
#203 で対応
