### ISSUE TITLE
sakura_lang のプロジェクトを Visual Studio 2017 に更新する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#20]
sakura_lang のプロジェクトを Visual Studio 2017 に更新する

また、sakura_vc2017.sln のソリューションに sakura_lang のプロジェクトを追加して
Appveyor のビルド対象にする。

**Comment by kobake** [comment]
`sakura_lang` が何者なのか実は把握していません……。把握後にどうするか考えようと思っていましたが、内容分かるようであればご解説いただけると助かります。

**Comment by m-tmatma** [comment]
> sakura_lang が何者なのか実は把握していません……。把握後にどうするか考えようと思っていましたが、内容分かるようであればご解説いただけると助かります。

https://github.com/sakura-editor/sakura/blob/master/sakura_core/CSelectLang.cpp#L121 (CSelectLang::InitializeLanguageEnvironment) で

sakura_lang_*.dll をロードしています。
sakura_lang のプロジェクトは sakura_lang_en_US.dll を生成します。

名前の通り、英語向けのリソース DLL だと思います。
指定した名前に一致する DLL があれば、リソースが各言語対応になるのだと思います。

**Comment by kobake** [comment]
#31 マージにより本 Issue も解決されました。
