### ISSUE TITLE
インストーラの UI を英語対応にできないか検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#209]
インストーラの UI を英語対応にできないか検討する

英語のリソースを含んでいるので、インストーラも英語対応するといいと思う。

### 参考

https://hibara.org/blog/2013/06/18/inno-setup-localization/

**Comment by m-tmatma** [comment]
添付の修正をするだけでもある程度英語化できるが、
結構日本語の部分がある。

[en.txt](https://github.com/sakura-editor/sakura/files/2155111/en.txt)

**Comment by m-tmatma** [comment]
テスト用のパッチ

[en2.txt](https://github.com/sakura-editor/sakura/files/2163305/en2.txt)

**Comment by KENCHjp** [comment]
@m-tmatma さん
このパッチって、TortoiceGitとかで右クリックで適用できるものっすか？

**Comment by m-tmatma** [comment]
パッチだと扱いにくいので PR 投げました。
#359

**Comment by KENCHjp** [comment]
見まーす。

**Comment by KENCHjp** [comment]
@m-tmatma さん、これみるときって、 @m-tmatma さんのリポジトリforkするのがいいのでしょうか？

**Comment by m-tmatma** [comment]
PR をとってくるだけでも、fork してもどちらでもいいです。

**Comment by KENCHjp** [comment]
PRを取るって技があるんですね。調べます。

**Comment by KENCHjp** [comment]
>PRを取るって技があるんですね。調べます。

これはでけた見たい。でも作ったインストーラーはなかなかまだバギーですね。
ひとまず英語OSダウンロード中です。

https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/

**Comment by KENCHjp** [comment]
環境できて、とりあえず作ったインストーラー動かすも、１点どうしようかと。
初期起動されたsakuraが日本語で起動するので、インストーラー側で対処するなら、
初期iniファイルを作成する位なのですが、この線で行くかどうか。。。

**Comment by berryzplus** [comment]
> 初期起動されたsakuraが日本語で起動する

sakura.iniに言語DLLのパスを書き込めば、初回起動から英語にできると思います。
英語インストーラが生成するiniに言語DLLのパスを含めるのはどうでしょうか？

たぶん @KENCHjp さんが書いたのと同じ意味だと思いますが。

**Comment by KENCHjp** [comment]
>英語インストーラが生成するiniに言語DLLのパスを含めるのはどうでしょうか？

その線ですよねやはり。
マルチユーザかシングルユーザかでどこにiniファイル書かれるかわかるんですよね。。。

**Comment by m-tmatma** [comment]
#359 がマージされたので閉じます。
