### ISSUE TITLE
artifacts のファイル名、フォルダ名の platform と configuration の順番等について検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#213]
https://github.com/sakura-editor/sakura/pull/199#issuecomment-402564293

ファイル名ソートの観点で俯瞰すると、以下のような命名のほうがより利便性は上がりそうにも思いました。

- `sakura-PR199-build328-29d15eb0-Win32-Release.zip`
- `sakura-PR199-build328-29d15eb0-x64-Release-alpha.zip`
- `sakura-PR199-build328-29d15eb0-Win32-Debug.zip`
- `sakura-PR199-build328-29d15eb0-x64-Debug-alpha.zip`

ただ、これ以上この話に時間使うのももったいない（早くこの ZIP 名が変わる対応を利用したい気持ちが強い）ので、このあたりの改善についてはやるとしたら別途での議論をしましょう。

https://github.com/sakura-editor/sakura/pull/199#issuecomment-402568893

これに関しては、検討はしました。
どちらがぱっと見た目でわかりやすいかという点で微妙かなと
思ったので入れてません。

ただ上記のようにも簡単に変更にできるようにはしています。
以下の行をバッチファイルの中で順番を入れ替えるだけで可能。

`set BASENAME=%BASENAME%-%platform%-%configuration% 
`

**Comment by kobake** [comment]
この Issue で挙げられているとおりの
`sakura-{PR番号}-{ビルド番号}-{Gitハッシュ}-{Platform}-{Configuration}[-alpha].zip` 形式に一票です。

他の方の意見も聞きたいです。

**Comment by m-tmatma** [comment]
#199 時点での仕様は

`sakura-{Platform}-{Configuration}{tagName}-{PR番号}-{ビルド番号}-{Gitハッシュ}[-alpha].zip
`

です。


- tagName: オプション (appveyor ビルドで tag がある場合のみ)
- PR番号   : オプション (appveyor ビルドで PR のみ)
- ビルド番号: appveyor ビルドのみ
- Gitハッシュ : appveyor ビルドのみ (ハッシュの先頭8文字)
- alpha : x64 ビルドのみ


`{tagName}` は tag 名のうち、スペースとスラッシュを アンダーラインに置き換えて 先頭に "tag_" をつけたものです。

例1 "`release/v1.2.3`" → "`tag_release_v1.2.3`"  
例2 "`release/v 1.2.3`" → "`tag_release_v_1.2.3`"

**Comment by m-tmatma** [comment]
### 備忘録

zip ファイルの名前を変えるためには、以下の修正も必要

https://github.com/sakura-editor/sakura/blob/ca0b56d0971efdc748489773cee577b6c220738a/appveyor.yml#L23-L24

**Comment by m-tmatma** [comment]
厳密に言えば、この issue のスコープではないが、

#199 の対応をしたあとで使ってみて
APPVEYOR_ACCOUNT_NAME も zip ファイル名に含めてもいいかなと思う。
(https://www.appveyor.com/docs/environment-variables/)

理由は、
PR ではないビルドの場合自分のアカウントの clone に対してビルドした場合と
 sakura-editor がブランチでビルドした場合とで zip ファイルで区別できないため。

APPVEYOR_ACCOUNT_NAME の値が "sakuraeditor" と等しい場合には
APPVEYOR_ACCOUNT_NAME の値を含めないという対応は可能。

**Comment by kobake** [comment]
アカウント名を入れるとしたら先頭ですかね。

- APPVEYOR_ACCOUNT_NAME の値が "sakuraeditor" と等しい場合には `sakura-*.zip`
- それ以外の場合には `{APPVEYOR_ACCOUNT_NAME}-sakura-*.zip`

みたいな感じが良いと思いました。

**Comment by m-tmatma** [comment]
https://ci.appveyor.com/project/m-tmatma/sakura/build/1.0.296
で試しに実装してみました。

試してみて以下のようにしたらいいんじゃないかと思いました。
(まだ実装してません)

| APPVEYOR_ACCOUNT_NAME | ファイル名、フォルダ名 |
----                    |---- 
| "sakuraeditor"        | sakura-{tagName}-{PR番号}-{ビルド番号}-{Gitハッシュ}-{Platform}-{Configuration}[-alpha] |
| 空 (ローカルビルド)   | sakura-local-{Gitハッシュ}-{Platform}-{Configuration}[-alpha] |
| 上記以外              | sakura-{APPVEYOR_ACCOUNT_NAME}-{tagName}-{PR番号}-{ビルド番号}-{Gitハッシュ}-{Platform}-{Configuration}[-alpha] |


{tagName}, {PR番号}, -alpha  はオプション


sakura で始まるほうがローカルで扱うときに扱いやすい。
ローカルビルドであることを local というキーワードで判断しやすくする
(ビルド番号がないことで区別も可能だがあったほうがわかりやすと思う。

- "sakura"
-  (オプション) "local" または APPVEYOR_ACCOUNT_NAME
-  (オプション) (tagのみ) tagName
-  (オプション) (PRのみ)  PR番号
-  (オプション) (appveyorのみ) ビルド番号
-  (オプション) (git 環境のみ) Gitハッシュ
-  Platform
-  Configuration
-  (オプション) (x64 のみ) alpha

**Comment by kobake** [comment]
ローカルビルドの場合、ビルド番号のところを「buildXXX」の代わりに「buildLocal」ってするのもアリなのではと思ったりしました。

**Comment by m-tmatma** [comment]
#234 で対応しました。
