### ISSUE TITLE
Vsプロジェクトファイルの文字コードはsjis？

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#23]
ファイル内で文字コードを指定できるのに標準と変えてあるように思っています。

Sjisでないとマズい理由があるんでしたっけ？

あとでもう少し詳しく書きますm(._.)m

**Comment by kobake** [comment]
たぶんですけど VS2017 版のプロジェクトファイルはぜんぶ UTF-8 になっているはず、、です（自動変換でそうなっているはず）。

漏れあったら教えてください。

**Comment by kobake** [comment]
ご確認ありがとうございます。
sakura_vs2017.sln もおそらくですけど BOM 無しの utf-8 な気がします（？）
旧形式のプロジェクトは #31 で削除対応しちゃってます。

**Comment by berryzplus** [comment]
了解しました。
