### ISSUE TITLE
英語表示したときの著作権表示について考える

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#233]
英語表示したときの著作権表示について考える

**Comment by m-tmatma** [comment]
英語表示したときに著作権者が、変わってしまう。
https://github.com/sakura-editor/sakura/pull/232#issuecomment-403255933

**Comment by m-tmatma** [comment]
案1
https://github.com/sakura-editor/sakura/pull/232#discussion_r200827418

**Comment by kobake** [comment]
#232 での議論も転記。

https://github.com/sakura-editor/sakura/pull/232#discussion_r200827253
```
-#define	S_COPYRIGHT	"Copyright (C) 2011-2017  by Lucien & Collaborators"
+#define	S_COPYRIGHT	"Copyright (C) 2011-2018  by Lucien & Collaborators"
```
@berryzplus
> PR内容とは関係ないですが・・・。
> いつかどこかで話さないといけないトピック。
> 
> 翻訳じゃなくて著作者変わっとるやんけ、という話。

　

@kobake
> 翻訳の場合、普通はどういうふうに書くのが一般的なんですかね

　

@m-tmatma
> http://www2e.biglobe.ne.jp/tis-russ/chosakuken.htm
> 翻訳は「二次的著作物」になりそうです。
> 
> https://www.office-furuki.info/copyright-beginners/二次的著作物の利用に関する原著作者の権利/

　

@kobake
> 今内容を把握。dll のほうの著作者かと思ってましたが、よく確認してみたらサクラエディタ本体ダイアログの Copyright が変わっちゃう所でしたね。たしかにこれは問題。（とはいえやはりどのような書き方が好ましいのか分かってない）

　

@KENCHjp
> http://d.hatena.ne.jp/sardine/20060912
> 
> Copyright of the original © 2004-2006 W3C® (MIT, ERCIM, Keio), All Rights Reserved. Translated by [ここに翻訳者名]. W3C liability, trademark and document use rules apply for the original and the translation."
みたいな？

**Comment by kobake** [comment]
ところで英語表示の件とは関係ない話なのですが、
日本語表示のほうの Copyright に表示されている Norio Nakatani さんというのは竹パンダさんとイコールですか？別人ですか？（経緯よく分かってないです）

**Comment by berryzplus** [comment]
> 日本語表示のほうの Copyright に表示されている Norio Nakatani さんというのは竹パンダさんとイコールですか？別人ですか？（経緯よく分かってないです）

オリジナルのソースコードに入っている名前と一致しているので同一人物の認識でした。
そういえばちゃんと誰かに訊いてみたことないです。

**Comment by berryzplus** [comment]
英訳の場合の著作権表記を本来どうすべきかについては、他のプロジェクトの例も参考にして決めたほうがいいと思っています。少なくとも「現状だと著作者が変わってしまっているように見える」というのは前々から抱いていた疑問です。

**Comment by kobake** [comment]
本名の中に "Take" って入ってたらもうちょっと根拠強まったんですけどねｗ
時間が経つと歴史って曖昧になりますね 😕

**Comment by kobake** [comment]
https://www.wdic.org/w/TECH/%E3%82%B5%E3%82%AF%E3%83%A9%E3%82%A8%E3%83%87%E3%82%A3%E3%82%BF

> 初代開発者 ‐ たけ(竹パンダ) クレジット上の本名 Norio Nakatani

このへんの書かれ方からしても同一人物であるっぽいこと伺えますね

**Comment by KENCHjp** [comment]
infoseekの掲示板だったかCGIで、げんたさんとかとやり取りしてた頃のログが誰かがどこかに転載していたような気がするんですが、見つけられない(笑)

**Comment by KENCHjp** [comment]
当時まだ、サクラエディタがサクラエディタって名前じゃなかったころに公開されてたソースにその著作者表記があったような。。。

**Comment by kobake** [comment]
cyclamen よりも前の掲示板があったんすねぇ。infoseek がいつの間にか Rakuten infoseek になっていて時代の変遷を感じます……

**Comment by berryzplus** [comment]
sourceforgeで管理されてる最古のsakura_rc.rcはoriginalブランチのもの。
そこではNorio Nakatani名義になってるようです。

[https://sourceforge.net/p/sakura-editor/code/HEAD/tree/sakura/branches/original/sakura_core/sakura_rc.rc](https://sourceforge.net/p/sakura-editor/code/HEAD/tree/sakura/branches/original/sakura_core/sakura_rc.rc)
> ProductName テキストエディタ SAKURA
> ver 1.2.20.2
> Copyright (C) Norio Nakatani

「昔は竹パンダ氏の公式ホームページがあったらしい」という話を見かけたことがありますが、自分はそのホームページを見たことないです。

本名に「たけ」が含まれない件について「旧姓」という発想があることを付記しときます。

**Comment by m-tmatma** [comment]
バージョンダイアログの著作権表示で、
リソースの著作権表示をそのまま表示せずに
translation という表示項目を別に作って
プログラム本体のものに通過する形で
表示するようにしたらいいように思います。

**Comment by KENCHjp** [comment]
昔InfoseekだかTrypodだかの無料ホームページで、本体と、ソースを公開してたんですよね、たけさん一人で。
そこに協力者ってかんじで、げんたさんが加わってしばらく二人でメンテしてましたかねぇ。
#途中、げんたさんがネガティブ発言してたけさん怒ってソース公開取りやめそうになったを「まぁまぁ」って私が止めて事なきを得るみたいな(笑)

たけさんが就活だかなんだかで、げんたさん中心にソース管理をsf.netに移して、それからしばらくげんたさんがメインで活動されてるころに、kobakeさん入ってって感じですかね。

私はv2の頃ちょうどサクラから疎遠になってて、最近仕事が一段落してきたので、そろそろまた協力できるかなってsf.netみたら、なんだか混とんとしているなって思ったところに、kobakeさんのGitHub移行の提案があったのでまた乗っからせていただいてます。

節目節目でなんか縁のある不思議なOSSです(笑)

**Comment by m-tmatma** [comment]
#315 で対応
