### ISSUE TITLE
ヘッダメイク。メイクファイルメイクのプロジェクトファイルの位置について

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#24]
Sakura配下に集めませんか？

Postbuildに細工すれば可能だと思います。

**Comment by kobake** [comment]
プロジェクトファイルの置き場所整理はしたいですね。
sakura リポジトリの中に sakura フォルダがあるのもなんか「違う」気がするのでそういうところも併せてちょっと整理したいです。

**Comment by berryzplus** [comment]
ファイル名変更を確認しました。まだ出先なんで、帰宅したら修正案をPRで送ります。

**Comment by kobake** [comment]
ご確認ありがとうございます。
#31 ではファイル位置の変更までは入れないつもりです。（これ以上変更を加えると PR のサイズが大きくなりすぎて良くないので）

ファイル位置の検討については help, macro, installer の統合も併せて考えたほうが良いところだと思ってます。

## 参考
- [開発・管理:リポジトリ構成の変更 - サクラエディタ - OSDN](https://osdn.net/projects/sakura-editor/forums/34093/39614/)

**Comment by berryzplus** [comment]
この件って #68 の完了待ちな認識でよいですか？

現状は ソリューションフォルダ＝sakuraフォルダ なので、 #76 の修正内容に影響を与える気がします。

* すぐにsakura配下に集める　→　sakura_lang_en_US.vcxprojが移動する
* 今回は移動を見送る　→　sakura_lang_en_USの出力先をソリューションフォルダ基準に変更する

**Comment by kobake** [comment]
自分は整理は必要と思ってますが、sakura 配下に集めるのが正解とは思ってなくて、まずは構成案をここの Issue 上で詰めるのが良いと思います。#68 のことは気にしなくて良いです。

**Comment by berryzplus** [comment]
#80 がマージされて気にならなくなったので閉じます。
