### ISSUE TITLE
Pull Request を送るときの注意点をまとめる

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#242]
Pull Request を送るときの注意点をまとめる

項目は以下のような感じ (以下の項目を Markdown or Wiki でまとめる)

項目
- 準備 (最初に一回だけ行うこと)
    - GitHub アカウントを作る
    - GitHub for Windows をインストールする
    - (オプション) Python をインストールする
    - clone する
    - appveyor アカウントを作る
    - appveyor アカウントに 'sakura' のプロジェクトを GitHub のプロジェクトの中から追加する

- 準備 (作業を開始する前に行うこと)
    - 自分の clone を最新の upstream に同期する
    - clone 上にリモートブランチを作成する

- 修正
    - 適用したい修正をローカルで行いテストして(リモートブランチに対応する)ローカルブランチにコミットする
    - 自分の clone のリモートブランチに push する
    - **自分の appveyor アカウントでビルドに通ることを確認する。**

- GitHub の Web site から PR を送る
    - マージを目的とした PR なのか、テストのための PR (= WIP [Work In Progress]) なのかの区別
    - 機能追加の場合
        - 追加する機能の説明
        - もし何かのトレードオフやデメリット等あればその説明
    - バグ修正の場合
        - 再現手順、発生条件等
        - バグの原因
        - バグの修正方法に関する説明
        - workaround なのか根本解決なのか等の位置づけ

**Comment by kobake** [comment]
Tips共有は良いと思いますけど、あんまりルールは厳しくしたくないです。AppVeyorとかもやりたい人だけ自分の作れば良いんじゃないですかね。PR時点でエラーには気付けるわけですし。

**Comment by kobake** [comment]
あと、基本的にテストのためのPRというのは自分は考えてないです。慣れてる人がそういうの作るのまでは否定しないですけど。

あくまでもWIPは作業途中の状態を示すために付けるのが原則で、作業完了したらWIP外してレビュー通すことが期待されます。

**Comment by kobake** [comment]
サクラエディタリポジトリに書くべきドキュメントはあくまでサクラエディタ独自のルールであって、それ以外の汎用情報を書く場所として使うのはちょっと違うのではないか、というのが自分の見解です。

でも頻繁にハマる人が出る手順があるのであれば wiki に tips としてメモ残すのも悪くはないと思います。が、それは原則から外れた例外対応である認識は持ってほしいです。

**Comment by kobake** [comment]
「プルリクエストの注意点」とは違いますが、挙げていただいた文章の中では「オプション) Python をインストールする」あたりの文面はサクラエディタ独自の文化ですので明文化するのは好ましいと思います。

**Comment by KENCHjp** [comment]
https://github.com/sakura-editor/sakura/wiki/11.SakuraEditor_PRGuide

作ってみました。

**Comment by KENCHjp** [comment]
>マージのとき複数の変更を１つにまとめる機能(-squash)があると思います。

私、その機能を単に知らないっすwww、ググったときにローカルの複数のコミットを一つにマージするってのは見かけたのですが、GitHub上で、マージするときにどうするんだろうと思いまして。。。

それはさておき、PRって基本的にはローカルでテストした結果の「完成品」かなとおもうので、
プチプチ小さく変更を重ねたいと思ってPR送ることはないんだと思いますが、
結果的にレビューする側の指摘対応等で、プチプチ小さく変更重ねてる状況なのかなと。
一つのPRのコミットの積み重ねの履歴に意味があるものはそのままでもいいかと思うのですけど、
大概はPR後のコミット履歴って必要になる事はないとおもうので最終的にはまとめる機能があればまとめたいなと思います。

**Comment by KENCHjp** [comment]
とはいえ、私はインストーラーしかいじってないので、本体側のコミッターの方のよしなに。

**Comment by k-takata** [comment]
GitHubのマージ時にsquashでマージしてしまうと、コミットの著者がマージボタンを押した人になってしまいませんでしたっけ。（実際に試したことがないので不明）

**Comment by berryzplus** [comment]
う、それは困る・・・（著者が変わる

**Comment by k-takata** [comment]
サンドボックスで試してからにしましょう。

**Comment by m-tmatma** [comment]
リポジトリの設定で、"Allow Merge Commits" だけ許可すればいいんじゃないかと思います。

<img width="771" alt="merge" src="https://user-images.githubusercontent.com/5567450/45925499-8e922a00-bf51-11e8-8a2f-5f45444bd9f7.png">

**Comment by m-tmatma** [comment]
例えば Merge Option を以下のように設定したら

<img width="758" alt="merge-option" src="https://user-images.githubusercontent.com/5567450/45925714-c4d1a880-bf55-11e8-8c2d-bc84ea4f0903.png">

以下のように "Create a merge Commit" しか有効にならなくできました。

<img width="1045" alt="merge-pull-request" src="https://user-images.githubusercontent.com/5567450/45925715-c8652f80-bf55-11e8-89bc-e75e5b2a3e48.png">

**Comment by m-tmatma** [comment]
#469 はしばらくマージせずにおいておきます。

**Comment by berryzplus** [comment]
マージ方法 | 効果 | メリット | デメリット
---- | ---- | ---- | ---- 
merge commits | 単純にマージする | 既定の動作だから文句が少ない | マージコミットが生成されるので変更内容がごちゃごちゃする
squash merging | コミットを1つにまとめる | 取り込まれた変更内容が1つになって分かりやすい | 著者が変わる？（未検証）
rebase merging | リベースしてからマージする | マージコミットが発生しないので何を変更したか分かりやすい | 著者が変わる？（未検証）

**Comment by m-tmatma** [comment]
`rebase merging` のデメリットは revert しにくいじゃないかと思います。

rebase してからマージするので、PR で複数の commit があると
どこからどこまでが PR の対象かわからなくと思います。

**予想です。検証したわけではないです。**

**Comment by berryzplus** [comment]
りょ。
マージ方法は決めなくても良さそうな気がしてきました。

コミット側は、何をしてるか分かるように細かくコミットを積んでく方式で異論ないです。

**Comment by m-tmatma** [comment]
公式ドキュメント
https://help.github.com/articles/about-merge-methods-on-github/

**Comment by KENCHjp** [comment]
https://github.com/sakura-editor/sandbox/pull/2

砂場にテストPRおいてみました。どなたかsquash mergingをば。

**Comment by KENCHjp** [comment]
あれ、たてつづけに、rebase merging のRP出来るかと思って積んだら、おかしくしちゃったT_T

**Comment by KENCHjp** [comment]
衝突回避しました。都合で、コメントが、rebase mergingになっちゃってます。すいません。

**Comment by k-takata** [comment]
> `rebase merging` のデメリットは revert しにくいじゃないかと思います。
> 
> rebase してからマージするので、PR で複数の commit があると
> どこからどこまでが PR の対象かわからなくと思います。

その通りだと思います。
利点は履歴が一直線になって見やすい点です。PR内のコミットが1つだけであれば、PRの対象も明確ですし。（マージコミットが作られないので、gitのlogからPR番号をたどるのは面倒かも）

rebaseしてマージの場合、コミットの著者はそのままですが、コミッターはボタンを押した人になります。GitHub上で見ると、2人のアイコンが表示されます。(例: https://github.com/vim/vim-history/commit/370b3440581a717e2f658b43f94c4abf2ccee3c6)

**Comment by k-takata** [comment]
> [sakura-editor/sandbox#2](https://github.com/sakura-editor/sandbox/pull/2)
> 
> 砂場にテストPRおいてみました。どなたかsquash mergingをば。

実験の結果は、squash mergingでも著者は変わらず、コミッターがボタンを押した人になったと言うことでしょうか。

**Comment by KENCHjp** [comment]
こんな感じ。
![default](https://user-images.githubusercontent.com/39618965/45926165-930f1080-bf5a-11e8-8821-90628ce3e2b7.PNG)

もう一個、PRつんでます。どなたか、rebase mergingをば。急ぎ過ぎたのでなんかへんになってるかもですが。
https://github.com/sakura-editor/sandbox/pull/3

**Comment by m-tmatma** [comment]
> 衝突回避しました。都合で、コメントが、rebase mergingになっちゃってます。すいません。

いい機会なので、`git rebase -i `の練習してみます?

`git rebase -i <変更したい commit の一つ前の commit hash>`
とやると、エディタが起動してくるので、エディタに対して
どう rebase するか指定するコマンドを指定します。

何のエディタを使うかは `git config --global core.editor` で設定できます。
私は `git config --global core.editor notepad `  で notepad を指定しています。

https://git-scm.com/book/ja/v1/Git-%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%9E%E3%82%A4%E3%82%BA-Git-%E3%81%AE%E8%A8%AD%E5%AE%9A

https://www.karakaram.com/git-rebase-i-usage

**Comment by KENCHjp** [comment]
>いい機会なので、git rebase -iの練習してみます?

いい機会かと思いますが、とりあえずここのissueとは別にやろうと思いますので進めてくださいませ。

**Comment by m-tmatma** [comment]
"Rebase and Merge" を選んだら以下メッセージが出て拒否されました。

```
This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch. 
```

**Comment by KENCHjp** [comment]
ああ、私が急ぎ過ぎたせいですかwww

**Comment by m-tmatma** [comment]
> ああ、私が急ぎ過ぎたせいですかwww

ただ、いいテストになりました。

**Comment by berryzplus** [comment]
たぶんリベース必要ないよ、って意味のメッセージではないかと。
コマンドラインで -f つけないといけないシチュエーションではリベースマージできないのかも。

**Comment by KENCHjp** [comment]
いったんとりけしました。

**Comment by berryzplus** [comment]
ちがうか。手動マージが必要だから無理、といってそうｗ

**Comment by berryzplus** [comment]
とくになにもメッセージ出ずに rebase merging できたみたいです。 sakura-editor/sandbox#4

**Comment by KENCHjp** [comment]
![default](https://user-images.githubusercontent.com/39618965/45926623-239c1f80-bf60-11e8-9084-9fb9c92ab6a8.PNG)

どっちも２回づつローカルでコミットしてるんですが、指定通り、squash mergingはひとまとまり、rebase mergingは直列で、アイコン二つづつ並んでますね。

**Comment by berryzplus** [comment]
結論的にはコレを見る、でいいと思います。
https://github.com/sakura-editor/sakura/wiki/11.SakuraEditor_PRGuide
