### ISSUE TITLE
旧 web site へのリンクを新 Web site に切り替える

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#26]
旧 web site へのリンクを新 Web site に切り替える

![version_info](https://user-images.githubusercontent.com/5567450/40781683-c2111cf4-6517-11e8-86ad-4d709538d1cd.png)

**Comment by m-tmatma** [comment]
#27 で対応

**Comment by m-tmatma** [comment]
修正後のスクリーンショットです。

![version_info2](https://user-images.githubusercontent.com/5567450/40782613-d9792c9e-651a-11e8-8e31-e36ddef61ad0.png)

**Comment by kobake** [comment]
#27 マージしたのでクローズします。ご対応ありがとうございました！
