### ISSUE TITLE
[仕様変更提案] ファイルの排他制御モードのデフォルトを 「排他制御しない」に変えませんか?

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#260]
ファイルの排他制御モードのデフォルトを 「排他制御しない」に変えませんか?

現状は `他プロセスからの上書きを禁止` (SHAREMODE_DENY_WRITE) になっていますが、
デフォルトを `排他制御しない` (SHAREMODE_NOT_EXCLUSIVE) に変えたいと思います。

#258  と同様に私は使用するときに、 `排他制御しない` に変更しているためです。

変更が必要な箇所は以下です。

https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/env/CShareData.cpp#L363

どう思いますか?

**Comment by KENCHjp** [comment]
>どう思いますか?

これは、今のサクラエディタの多数決な気がしますが、このデフォルト悪評って目にします。
私的には、

変えた方がいい

です。

**Comment by berryzplus** [comment]
同意。

タイプ別設定の改善と絡めたい気もしますが、排他制御を外すは文句なしです。
