### ISSUE TITLE
pre-build, post-build の Power Shell 対応

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#28]
.bat だと処理が冗長になりがちなので Power Shell スクリプトで pre-build, post-build を書けるように対応できないか検討中です。

## 検証中
- https://github.com/kobake/appveyor-test/commits/master … 検証のためコミット積み
- https://ci.appveyor.com/project/kobake/appveyor-test … AppVeyor 挙動の検証

https://ci.appveyor.com/project/kobake/appveyor-test/build/1.0.9
```
....
....
aaaaa
(ここにGitハッシュが出て欲しかったけど AppVeyor ビルドだと出ない。手元の VS2017 だと出る)
bbbbb
....
....
```

**Comment by m-tmatma** [comment]
これ、対応せずクローズでいいですか?

**Comment by berryzplus** [comment]
閉じて良いと思います。

たぶん今後、いまあるbatの処理をcmakeに巻き込む対応があると思っていて、
powershell化するのはその後になるのかな、と思っています。
そうすると、実際に行うpowershell化は当初検討していたのとは別物になるので、
残しておくとややこしい感じになりそうに思います。

**Comment by kobake** [comment]
閉じる意味あるか分からんですけど閉じたいなら閉じます
