### ISSUE TITLE
アセンブラ出力を有効にしませんか?

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#286]
アセンブラ出力を有効にしませんか?

以下で @berryzplus さんが文字コード変換で問題がないかの確認でアセンブラ出力を活用されました。
https://github.com/sakura-editor/sakura/pull/265#pullrequestreview-138741324
 
実際に生成されるコードを比較して確認すると心強いと思います。
なのでデフォルトで有効にしませんか?

昔、アセンブラ出力を行うとバイナリが生成されない仕様だったように思いますが、
15.7.5 で試すとアセンブラ出力もバイナリも生成されていました。

以下で設定できます。

![assember](https://user-images.githubusercontent.com/5567450/42972060-405184d0-8be9-11e8-899f-8a149822067b.png)

**Comment by m-tmatma** [comment]
asm ファイルも 別ファイルとして artifacts に含めようと思います。

zip 形式にすると win32 debug で 18MB ぐらい
7z 形式にすると win32 debug で 6 MB ぐらいなので
7z 形式にしようと思います。

7z 形式の欠点は (ローカルで試した限り) 
zip 形式では 8 秒で済んだのに対して
7z 形式では 圧縮に 47 秒ほどかかった。

**Comment by kobake** [comment]
良いと思います。

形式については自分としては容量よりも圧縮時間が短いことを優先したいです。
AppVeyor 上でどの程度かかるか分かりませんが、ローカルで試してもらった数字の差を見ても、あまり無視できる時間ではないな、と思いました。成果物4つできるわけですから、4倍の時間差になるわけですよね。
