### ISSUE TITLE
Cppcheck

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#296]
Cppcheck Version 1.84 を 109a963f0f45f0766bb0362219229606da75f303 の sakura_core フォルダ以下に対して掛けてみました。

処理結果が結構大きいので添付ファイルにします。容量は 211KB です。
[cppcheck_109a963f0f45f0766bb0362219229606da75f303.txt](https://github.com/sakura-editor/sakura/files/2216317/cppcheck_109a963f0f45f0766bb0362219229606da75f303.txt)

この中で対処した方が良いものについて優先度を付けてコード修正していくのはどうでしょうか？

例えば、`The scope of the variable 'foobar' can be reduced.` というのは変数のスコープを狭められますよ、という事なので恐らく修正しても特に害は無いと思います。他には例えばC++11 から言語仕様に入った `override` 指定子を使うようにするとかもあります。それ以外も色々ありますが大量なので１つのPRでカバーするのは厳しい気がします。

**Comment by berryzplus** [comment]
いいと思います。優先度はわかんないですけど、なんとなくで振ってみました。
[cppcheck.xlsx](https://github.com/sakura-editor/sakura/files/2216362/cppcheck.xlsx)
圧縮ファイル(xlsx)なんでファイルサイズは小さくなってますが、
@beru さんがアップしたファイルを整形して並べ替えただけです。

@m-tmatma さんが x64対応 で警告対策の準備を進められているので、どこかのタイミングで cppcheck を appveyor のチェックに組み込む対応も入れられそうな気がします。

**Comment by beru** [comment]
整形ありがとうございます。error > warning > performance > portability > style という優先度順のようですね。良いと思います。

cppcheck を appveyor のチェックに組み込むのは、コマンドラインの cppcheck は使った事が無いですが検出に結構時間が掛かるので注意が必要だと思います。

**Comment by beru** [comment]
> sakura_core/uiparts/CMenuDrawer.cpp (710) Array 'tbd[481]' accessed at index 481, which is out of bounds.

CMenuDrawer のコンストラクタ内の m_tbMyButton を設定するループの最後で `(tbd[i] == F_DISABLE)? 0 : TBSTATE_ENABLED` で参照しているところが問題のようです。tbd 配列を参照する際のインデックスに `i` が使われているので INDEX_GAP(1) のオフセット、つまり次の要素を参照してしまいます。ここは `tbd[i]` ではなくて、`funcCode` を使えば良い気がしますが。。

良く分からない点として、 `F_DISABLE` じゃなかったら `TBSTATE_ENABLED` を `TBBUTTON::fsState` に設定しますが、特に判定条件として `TBSTATE_ENABLED` を使っていないところです。

**Comment by beru** [comment]
> sakura_core/view/CEditView.cpp (590) Memory leak: hstr

`GlobalLock` が失敗した際に、`GlobalAlloc` で確保した領域を `GlobalFree` を呼び出して解放させる必要がありますね。こちらは修正した方が良いと思います。

**Comment by beru** [comment]
> sakura_core/_os/CDropTarget.h (172) Race condition: non-interlocked access after InterlockedDecrement(). Use InterlockedDecrement() return value instead.

メンバ変数 `m_lRef` の値を返すのではなくて、`InterlockedDecrement` の戻り値を返してくれと言っていますね。複数のスレッド/プロセスからの競合状態を避ける為のようですが、実際にそれが起こりうるのかはともかく、素直に指摘に従うので問題ない気がします。

**Comment by beru** [comment]
> sakura_core/typeprop/CDlgTypeAscertain.cpp (142) Resource leak: hFind

これは誤検知に思えます。for文の初期化式の中で少しごちゃごちゃ書きすぎですね。

**Comment by beru** [comment]
> sakura_core/util/tchar_printf.cpp (278) va_list 'tmp_v' used before va_start() was called.
> sakura_core/util/tchar_printf.cpp (280) va_list 'tmp_v' used before va_start() was called.

これらは誤検知だと思います。`va_start` を呼び出すのは、呼び出し元の関数の責務ですね。

**Comment by m-tmatma** [comment]
> どこかのタイミングで cppcheck を appveyor のチェックに組み込む対応も入れられそうな気がします。

#297 で PR 投げました。

**Comment by m-tmatma** [comment]
対応済み
