### ISSUE TITLE
デバッグコードが再入可能ではない

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#299]
デバッグコードが再入可能ではない

static な一時バッファを使っている。

https://github.com/sakura-editor/sakura/blob/b9ffcf3779a300b6bad4d570feb9b95cab61f174/sakura_core/debug/Debug2.cpp#L8-L19

https://github.com/sakura-editor/sakura/pull/265#discussion_r204725367

**Comment by berryzplus** [comment]
微妙なんすけど、この関数は汎用品じゃないので現状通りで問題ない認識です。

この関数を利用している箇所は２箇所あります。

1. 独自実装版 assert 関数の assertion failed 実装
1. 独自関数 assert_warning 関数( 停止しない assert )の assertion warning 実装

再入が問題になるのは、マルチスレッド環境で複数スレッドから関数を実行する場合です。
古典的な再入の定義は「割り込み」に絡んだ説明になりますが、
windowsでは割り込みはスレッド処理されるので、常にマルチスレッドの話になります。
（これはC言語コードであっても同様だったはず・・・。）

この関数の用途はデバッグ用に異常事態を検知することですが、
複数スレッドで同時に異常事態が発生するほど酷いコードなんでしたっけ？

実害はなさそうなんで、コーヒーブレイクネタかな、と思っています。

**Comment by m-tmatma** [comment]
直すのに手間かからないので直したらいいと思います。
使用するメモリは少ないので、単にローカル変数で定義すればいいです。

**Comment by berryzplus** [comment]
極論static外すだけ？

**Comment by m-tmatma** [comment]
そうです

**Comment by m-tmatma** [comment]
#301 マージした。
