### ISSUE TITLE
appveyor で master がビルドされないことがある

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#300]
appveyor で master がビルドされないことがある

https://ci.appveyor.com/project/sakuraeditor/sakura/branch/master
を見ると

https://github.com/sakura-editor/sakura/commit/b9ffcf3779a300b6bad4d570feb9b95cab61f174
に対するビルドになっているが、

それ以降のコミットで
https://github.com/sakura-editor/sakura/commit/5a60bab94cbdd71f0f58d28a1b3f67b8ee4b3936
(#265) など複数の PR をマージしているが

それらに対するビルドが走っていない。

**Comment by m-tmatma** [comment]
説明欄で PR 番号と commit Hash を間違えたので訂正

**Comment by m-tmatma** [comment]
appveyor の画面で "New Build" をクリックすると、最新の master に対してビルドが走った。
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.485

**Comment by m-tmatma** [comment]
[Scheduled builds](https://www.appveyor.com/docs/build-configuration/#scheduled-builds) の機能がworkaround にならないかと思ったが、

デフォルトではフリーアカウントが無効にされているみたいだ。
https://www.appveyor.com/blog/2017/11/08/sheduled-builds-for-free-accounts/

ただ必要性を説得できれば有効にはできるみたい。

**Comment by k-takata** [comment]
> ただ必要性を説得できれば有効にはできるみたい。

xx のデイリービルドに使いたいと言って有効にしてもらったことがあります。
（問題が頻繁に発生するのでなければ手動でいいのではと思いますが。）

**Comment by m-tmatma** [comment]
https://help.appveyor.com/discussions/questions/16419-always-build-closed-pull-requests

`Pull request (PR) build is build of "virtual merge" of changes made in head branch as if they merged into base branch (usually master). PR build answer the question "what if I merge those changes into master branch". If PR is closed, this usually means that answer to this question is not important anymore. So when AppVeyor notified that PR is closed (via webhook), AppVeyor cancels all running or queued builds for that PR. If you need PR builds to finish even when PR is closed, you use that setting.`


とあるので有効にしてみた。

![appveyor-build-closed-pr](https://user-images.githubusercontent.com/5567450/43206762-6809c7d6-9061-11e8-83bf-1d2c0d67f9eb.png)

**Comment by m-tmatma** [comment]
> とあるので有効にしてみた。

おっと、ページ末尾の `Save `を押してなかった。

**Comment by m-tmatma** [comment]
質問しました。
https://github.com/appveyor/ci/issues/2540

**Comment by m-tmatma** [comment]
↑ 設定を変更しても #302 のマージコミットがビルドされなかったからです。

**Comment by kobake** [comment]
すみません、これ以前に自分が WebHook のオプションをいじっていて、「Pushes Git push to a repository.」の項目を OFF にしていたことが原因な気がします。ON にし直してみます。

![](https://user-images.githubusercontent.com/2929454/43241724-c5f0d468-90d7-11e8-9b69-68de4fa1b0a2.png)

**Comment by kobake** [comment]
ON にしました。

**Comment by kobake** [comment]
何故これを OFF にしていたかというと、全てのプルリクエストで何故か二重に CI ビルドが走ってしまっているのが気になっていて、Pull requests オプション ON だけで十分に CI ビルドが走っているようだったので Pushes のオプションは OFF にしてしまっていました。

たぶん今回 Pushes を ON にすることにより、master ビルドは直る可能性がありますが、PR のビルドは二重に走ると思います。これはこれで少し困るので対策考えたいです。

**Comment by m-tmatma** [comment]
> たぶん今回 Pushes を ON にすることにより、master ビルドは直る可能性がありますが、PR のビルドは二重に走ると思います。これはこれで少し困るので対策考えたいです。

#307 でテスト用の PR 作ってみましたが、二重には走っていないようです。
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.510

**Comment by kobake** [comment]
二重に走るときと走らないときがあって、条件の切り分けがまだできてないです。今後、ビルドが二重に走るの見た方いれば教えていただければと。

**Comment by m-tmatma** [comment]
> ただ必要性を説得できれば有効にはできるみたい。
> 
> xx のデイリービルドに使いたいと言って有効にしてもらったことがあります。
> （問題が頻繁に発生するのでなければ手動でいいのではと思いますが。）

簡単に有効にしてもらえるみたいです。
https://srz-zumix.blogspot.com/2018/01/appveyor.html
https://help.appveyor.com/discussions/problems/9891-enable-scheduled-builds-support

**Comment by m-tmatma** [comment]
いまのところ master はちゃんとビルドされている。

**Comment by m-tmatma** [comment]
問題なさそうなので閉じます
