### ISSUE TITLE
Coverity Scan

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#308]
Coverity Scan を試す

- https://github.com/sakura-editor/sakura/pull/297#issuecomment-407781504
- https://scan.coverity.com/
- http://k-takata.o.oo7.jp/diary/2014-08.html#15
- https://codezine.jp/article/detail/7619
- https://stackoverflow.com/questions/47867222/appveyor-coverity-on-windows-with-c
- https://www.appveyor.com/docs/build-environment/#tools

**Comment by m-tmatma** [comment]
使用条件が記載されている
https://scan.coverity.com/faq#how-get-project-included-in-scan

**Comment by m-tmatma** [comment]
Using Coverity Scan with AppVeyor
https://thehermeticvault.com/software-development/using-coverity-scan-with-appveyor

**Comment by berryzplus** [comment]
↑簡単じゃないけど技術的に可能、と理解しました。

サクラエディタのドキュメントには「販売してはいけない」と取れる記載があるので、前提条件をパスできるか微妙かもと思っています。

ライセンスさえ守れば売るのも自由、というのが国際的に見たフリーソフトの定義なので。

売ったらあかんなら不自由だっていう…

**Comment by berryzplus** [comment]
興味ある方いなさそうなので閉じておきます。

必要あれば新たにissue立ててください。
