### ISSUE TITLE
appveyor で MingW ビルドする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#309]
appveyor で MingW ビルドする
https://www.appveyor.com/docs/build-environment/#mingw-msys-cygwin

#306　等で対応を進めているのでローカルビルドができるように
なったときに考える。

**Comment by berryzplus** [comment]
#349(#351) で gcc ビルドできる条件が確認できたら
googletest の appveyor.yml を参考に MinGW でのビルドができないか検討。
実装の手間を考えると一旦は Makefile のまま組み込むのが良さそう。

#46 を発展させて #12 (CMake対応) を完成させる、が簡単にできるなら
先にそちらを済ませて ```cmake -G "MinGW Makefiles"``` して
MinGW向け一時フォルダを用意するのがいい気がする。
現状ではビルドできても使えないので、配布は考えなくて良さそう。

**Comment by berryzplus** [comment]
クローズした #349 の話題はこちらに引き継ぎかな、と思っています。

 m_tmatma
> > MinGW向け特化のCMakeLists.txtを作る　→　 #46 をベースにすることで意外と簡単にできた。
> 
> #378 で最新をベースに cmake 用の対応をあげました。

正確には、ここに引き継ぐのは
 MinGW ビルドをどのように appveyor に組み込むか？
という話だと思っています。

MinGW 向けに CMakeLists.txt の完成度を上げておく話は別件かな？

単純に MinGW ビルドを appveyor に組み込む話だけでも、
本来はいろいろ考えることがあると思うんですが、
まずは「ビルドに組み込む」を最優先にしたいです。

----

ところで、MinGWビルドを appveyor に組み込む目的について話が出ていない気がします。
ぼくが主観的に「これが目的だ」と思っていることをちょっと書いておきます。

1. Makefileの保守をやめる　←コードベースを身軽にする
1. MakefileMakeの保守をやめる　←コードベースを身軽にする
1. C++規格への準拠度を「できるだけ」高める　←コードベースの「良さ」を担保する

けっこう消極的な理由で進めている作業です。
大事か大事じゃないかっていうと結構大事なことだと思っていますが。

**Comment by m-tmatma** [comment]
@berryzplus さん

これ残件は #591 だけかな?

**Comment by berryzplus** [comment]
> これ残件は #591 だけかな?

いったんそこで終わりでいいと思います。
本当はビルドさえできれば終わっていいと思っていたんですが、せっかくなのでテストを動かすとこまで出来るようにしておきたいです。

**Comment by m-tmatma** [comment]
#591 をマージしたので閉じます。
