### ISSUE TITLE
sakura-editor/sakura/installer/readme.txt を修正したいと思い立ったが・・・

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#328]
https://github.com/sakura-editor/sakura/blob/master/installer/readme.txt

の中身を現状に添わせたい。

GitHubだと、
https://github.com/sakura-editor/sakura/tree/master/installer
ここにも表示される。

基本的には、
https://github.com/sakura-editor/sakura/issues/67#issuecomment-397805421
ここで行われているようなことをやればいいと思っている。

readme.txtを見ると、

> set_time.js  SVNからチェックアウト後、キーワードファイルの更新日時を復元する

こんな事が書いてある。でもそのファイルが見当たらない？？？

ふと、installer作ろうって人はきっとGitHubは見れる人だし、
あえてreadme.txtっていらんのではないだろうかと思い始める。

https://github.com/sakura-editor/sakura#ci-build-appveyor

ここあたりに追記して、readme.txtは削除してはいかがでしょう？

**Comment by berryzplus** [comment]
> https://github.com/sakura-editor/sakura/blob/master/installer/readme.txt
> 
> の中身を現状に添わせたい。

いいと思います。たぶん、拡張子を.mdに変えるだけで markdown が使えるようになるので、今までより見やすくできる気がしています。
https://github.com/sakura-editor/sakura/blob/master/unittest.md

> ふと考える、installer作ろうって人はきっとGitHubは見れる人だし、
> あえてreadme.txtっていらんのではないだろうかと思い始める。
> 
> https://github.com/sakura-editor/sakura#ci-build-appveyor
> ここあたりに追記して、readme.txtは削除してはいかがでしょう？

詳細な話題は個別ファイルに書かれているのがベターだと思っています。
https://github.com/sakura-editor/sakura の実体は https://github.com/sakura-editor/sakura/blob/master/README.md なので、同じように sakura/installer/README.md を作ればいいような気がします。もちろん、topにリンクを加えるのには賛成です。

1. リネームして.md化
1. 内容を .md に合わせる
1. 内容を最新化する （#67の内容はここで入る）
1. sakura/README.md → sakura/installer/README.md のリンクを貼る

2.までは速攻でできそう。3はちょっと大変ってところですかねぇ。

**Comment by KENCHjp** [comment]
>同じように sakura/installer/README.md を作ればいいような気がします。もちろん、topにリンクを加えるのには賛成です。

なるほど、それはナイスアイデアですね。

**Comment by m-tmatma** [comment]
> 基本的には、
> #67 (comment)
> ここで行われているようなことをやればいいと思っている。

インストーラを作成するには build-all.bat を呼ぶか
build-all.bat で呼ばれているバッチファイルで build-installer.bat の部分までを順番に呼べば作成できます。(ローカルでビルドするときは zipArtifacts.bat は呼ぶ必要はない。呼んでもいいけど)

appveyor 対応するために全自動化したのでインストーラの作成自体はすごく簡単になっています。

> リネームして.md化
> 内容を .md に合わせる
> 内容を最新化する （#67の内容はここで入る）
> sakura/README.md → sakura/installer/README.md のリンクを貼る

やりましょうか?

**Comment by KENCHjp** [comment]
記載内容

1. ローカルでインストーラ作成テストをする方法について記載する
 正式リリースは、appveyorで作成されるものにしてもいいのかなと。
2. innosetupを用意する(innosetup-5.5.9-unicode.exe か innosetup-5.6.1-unicode.exe)
3. バイナリは、https://ci.appveyor.com/project/sakuraeditor/sakura からzipをダウンロードする。
4. 3. でダウンロードしたinstaller作成対象bit(32bit/64bit)用のバイナリを抽出
5. installer\sakura フォルダを作ってinstaller\sinst_srcの中身と、4. で抽出したバイナリをほおりこむ。
6. 対象のinstallerを作成

こんな感じかな。

**Comment by m-tmatma** [comment]
書く内容はインストーラに限定した方がいいですか？

それともビルド全体に対して書いて、その中の章で
インストーラに関して書いた方がいいですか？

appyeyor の説明にも内容的にかぶる部分があって
どうしようかな？と思ってます。

**Comment by KENCHjp** [comment]
@m-tmatma さん
ビルド全体を書くとappyeyor とドド被りな気がしております。
私が欲しかったのは、ローカルでインストーラーを作成する手順というよりは、
.issを修正するための環境を最小の手数で作る手順かと。
最終的に書きやすい方でお任せいたします。

**Comment by m-tmatma** [comment]
#334 を作りました。

**Comment by m-tmatma** [comment]
#337 でドキュメントを更新しました。

**Comment by m-tmatma** [comment]
#337 をマージ

**Comment by KENCHjp** [comment]
すいません、Ok.って言ったのですが、
readme.md
73行目(ごめんなさいリンクで引用できなかった)

>installer\sakura\keyword*.kwd

拡張子.kwd以外も入るのではなかろうかと。

**Comment by m-tmatma** [comment]
> 拡張子.kwd以外も入るのではなかろうかと。

#340 で対応しました。

**Comment by m-tmatma** [comment]
#340 をマージした
