### ISSUE TITLE
Markdown の整理

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#334]
Markdown の整理

- #329 の変更を反映する → #336
- https://github.com/sakura-editor/sakura/issues/328#issuecomment-412264790
- #333 → #337 
- https://github.com/sakura-editor/sakura/pull/319#issuecomment-412314968 → #341

**Comment by m-tmatma** [comment]
#337 でインストーラ関連のドキュメントを更新しました。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/blob/5ed795184b3beb7c3d6a07eab36152699e2fcc67/appveyor.md

で

`configuration ("Debug" または "Relelase)"`

となっている。Release のとこで " と ) が逆になっている。

→ #337 のマージ後に対応予定

**Comment by m-tmatma** [comment]
> Release のとこで " と ) が逆になっている。

Release になっていない。`Relelase` になっている。

**Comment by berryzplus** [comment]
> > Release のとこで " と ) が逆になっている。
> 
> Release になっていない。Relelase になっている。

う～む・・・対象2ファイル。コピペですなｗ
ここの ページの左上にある検索窓に Relelase って入れたら2件ヒットしました。

**Comment by m-tmatma** [comment]
> → #337 のマージ後に対応予定

#339 で対応

**Comment by m-tmatma** [comment]
#341 でビルド関連の説明を更新

**Comment by m-tmatma** [comment]
ひと通り完了
