### ISSUE TITLE
zip ファイルの圧縮、解凍方法について検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#348]
zip ファイルの圧縮、解凍方法について検討する

https://github.com/sakura-editor/sakura/pull/345#issuecomment-413247870

> 「bregonig.dllの解凍とタイムスタンプチェック」が「sakura.exeのビルド」と同等なのであれば「ビルド工程てやろうぜ？」になる気がします。どうでしょうか？

https://github.com/sakura-editor/sakura/pull/345#issuecomment-413334388

> ビルド工程でやるのはいいのですが、
> 一転気になるのは、ビルドに 7zip が必要になることです。
> 
> それさえクリアさらば、シンプルになっていいとは思います。
> 
> またバイナリの直接登録をなくせば、タイムスタンプチェックは無くしていいと思います。

https://github.com/sakura-editor/sakura/pull/345#issuecomment-413347820

> おそらくご存知かとは思いますが、以前公開用のzipを固めるのにwsh(jscript)つかってました。
> でもなぜかこのこ安定しません。
> 以下参考。
> http://daybydaypg.com/2018/05/24/post-1153/
> 
> Poweshellで扱えるようになってるようです。
> 以下参考、
> https://www.casleyconsulting.co.jp/blog/engineer/233/

https://github.com/sakura-editor/sakura/pull/345#issuecomment-413348372

> 一転気になるのは、ビルドに 7zip が必要になることです。
> 
>     それさえクリアさらば、シンプルになっていいとは思います。
> 
> ならばその方向(ビルド時にbregonig.dllを解凍)で考えてみませんか？
> 
>     ビルドに 7zip が必要になる
> 
> この点は必ずしも真ではないと思っています。
> 要するにzipアーカイブを解凍できるコマンドなら何でもよくて、たまたま7zipにしてるだけなので。
> この機会に他の方法がないのか検討してみましょう・・・。
> 
> zipの解凍をビルド工程に含めることで影響を受けるのは開発者とappveyorだけだと思っています。
> 仮に7zipが最良の方法だったとするなら「ビルドには7zipが必要」になるかも知れません。

**Comment by m-tmatma** [comment]
以下で powershell で圧縮解凍できた。

unzip.ps1

```
Param($Arg1,$Arg2)
Expand-Archive -Path $Arg1 -DestinationPath  $Arg2
```

unzip.bat

```
powershell -ExecutionPolicy RemoteSigned -File %~dp0unzip.ps1 %1 %2
```


zip.ps1

```
Param($Arg1,$Arg2)
Compress-Archive -Path $Arg2 -DestinationPath $Arg1
```

zip.bat

```
powershell -ExecutionPolicy RemoteSigned -File %~dp0zip.ps1 %1 %2
```

使い方


```
unzip.bat bron412.zip temp
zip.bat bron412-2.zip temp
```


- https://qiita.com/alchemist/items/e6706cd425f8f5e5032e
- https://cheshire-wara.com/powershell/ps-cmdlets/item-file/expand-archive/
- https://cheshire-wara.com/powershell/ps-cmdlets/item-file/compress-archive/

**Comment by m-tmatma** [comment]
#347 がマージされたら PR を出そうと思う。
appveyor での動作は未確認です。

**Comment by m-tmatma** [comment]
https://cheshire-wara.com/powershell/ps-help/compress-archive-help/ によると以下とある。
まあ問題となることはないと思う。

`Compress-Archiveは「.NET Framework」にある[System.IO.Compression.ZipArchive]ライブラリを使用してファイルを圧縮するため、 圧縮できる最大ファイルサイズは現在2GBです。
`

**Comment by m-tmatma** [comment]
Expand-Archive や Compress-Archive のような簡単な方法は用意されていないが、
ZipFile というクラスを使えば powershell で zip ファイルの中身を表示できそうな気がする。

https://dobon.net/vb/dotnet/file/zipfile.html#entries
http://tech.guitarrapc.com/entry/2013/10/07/083837

**Comment by m-tmatma** [comment]
powershell で zip ファイルの中身をみるのいけた。
でも実行は遅い気がする

listzip.ps1

```
Param($Arg1)

try
{
    Add-Type -AssemblyName "System.IO.Compression.FileSystem"
    
    $sourcezip = [System.IO.Compression.Zipfile]::OpenRead($Arg1)
    foreach($file in $sourcezip.Entries){
        Write-Host $file.LastWriteTime $file.Length $file.FullName
    }
    $sourcezip.Dispose()

}
catch
{
}
```


listzip.bat


```
powershell -ExecutionPolicy RemoteSigned -File %~dp0listzip.ps1 %1
```

実行例

```
listzip.bat bron412.zip
```

参考
http://tech.guitarrapc.com/entry/2013/10/07/083837
https://msdn.microsoft.com/ja-jp/library/system.io.compression.ziparchiveentry(v=vs.110).aspx

**Comment by berryzplus** [comment]
色々ありますねぇ・・・System.IO.Compressとか完全ドットネットじゃないですかｗ
「PowerShellでドットネットのクラスを使えるらしい」とは訊いていましたが本当に普通に使えるんですね。なまじDOS窓プログラミングに慣れ親しんでると損してる部分があるのかも・・・。

> でも実行は遅い気がする

csc.exeでビルドすれば・・・という冗談はおいておいて。

圧縮解凍が速いことは、7zipの売りの一つだった気がします。
気になるようなら「7zipを使う」でもいい気がします。

7zipっぽいパラメータで動くbat(or ps)を用意して、
7zipがある環境では7zipを使い、7zipがない環境ではスクリプトを使う・・・。

**Comment by m-tmatma** [comment]
#350 で両対応しました。

**Comment by m-tmatma** [comment]
#350 をマージ
