### ISSUE TITLE
sakura-developers チーム情報がチーム外からも見えるようにする

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#35]
https://github.com/orgs/sakura-editor/teams/sakura-developers
が何故かチーム外のユーザから見えない（404 not found になる）。
ここは見えるようにしたい（できるだけオープンにしたい）。

**Comment by berryzplus** [comment]
マジですか…道理で変更ツリーが見られないなと思っていました。

一応、変更内容はcommitのdiffで軽くチェック済みです。
気のせいだと思うんですけど、slnとvcxprojでPlatformの定義名が違っているような・・・

**Comment by KENCHjp** [comment]
＞https://github.com/orgs/sakura-editor/teams/sakura-developers
ここログインしてない状態でも見えるみたいです。
あと、
https://github.com/orgs/sakura-editor/people
ここ私しかプロジェクトにかかわってないように見えるのでぜひともPublicへ(笑)

**Comment by kobake** [comment]
あら、ほんとですね

private/public いじろうとしてみたのですが、パッと見では自分自身の設定しかいじれない？ように見えました。とりあえず自分自身の設定を public にしました。これで今2人体制になりました (笑)

今スマホなので、あとでPCで他の方の設定をいじれるかどうか調べてみます。もしかしたら個々に設定してもらう項目なのかも？と思ったりもしました。

**Comment by kobake** [comment]
> ＞https://github.com/orgs/sakura-editor/teams/sakura-developers
> ここログインしてない状態でも見えるみたいです。

うーん、自分のほうで見てみた感じだと、未ログイン状態で上記URLアクセスするとログインページに飛ばされました

**Comment by KENCHjp** [comment]
＞今スマホなので、あとでPCで他の方の設定をいじれるかどうか調べてみます。もしかしたら個々に設定してもらう項目なのかも？と思ったりもしました。

そのようですね。ゆくゆくは裏方に徹する人もいるかもですが今は露出増やしたいのでぜひとも皆様Publicへ(笑)

＞うーん、自分のほうで見てみた感じだと、未ログイン状態で上記URLアクセスするとログインページに飛ばされました

再度やてみたら、だめですね。ログインページにとばされちゃいました。
なんか変なクッキー残ってたのかもです。
失礼しました。

**Comment by KENCHjp** [comment]
ここで聞くことではないのかもしれませんが、
https://github.com/orgs/sakura-editor/people
この中で、名前だけの人と名前とアカウント名が表示されてる人がいますがこの違いってなんなんでしょう。。。

**Comment by m-tmatma** [comment]
> 気のせいだと思うんですけど、slnとvcxprojでPlatformの定義名が違っているような・・・
>って、全然違う話じゃんと気付いたことを追記しておきますｗ）

新しいチケットを作成するのもどうかと思うのでここで返信します。

Visual Studio の仕様だと思います。
試しに新しい C++ アプリのプロジェクトを作成すると
sln は x86 になって vcxproj は Win32 になります。

**Comment by kobake** [comment]
> https://github.com/orgs/sakura-editor/people
> この中で、名前だけの人と名前とアカウント名が表示されてる人がいますがこの違いってなんなんでしょう。。。

これは GitHub アカウントの [Public profile](https://github.com/settings/profile) で Name を設定しているかいないか、の違いですね。

Profile profile の Name にはフルネーム書く用途に使うことが多いですが、僕はアカウント名と同じものを設定しちゃってます。

**Comment by KENCHjp** [comment]
＞これは GitHub アカウントの Public profile で Name を設定しているかいないか、の違いですね。
そういうことですか。アカウント名を隠せるわけではないってことですね(笑)
了解しました。

**Comment by KENCHjp** [comment]
＞https://github.com/orgs/sakura-editor/teams/sakura-developers
こっちですが、自分でためしに作ってみたのですが、Visibleだと組織に属している人に存在及び中身が見える状態で、Secretは、存在すら見えない状態になりました。

>Visible Recommended
>A visible team can be seen and @mentioned by every member of this organization.
>
>Secret
>A secret team can only be seen by its members.

運営のやり取りをオープンディスカッションするのはOSDN側の方がいいかもですね。

開発にかかわることはGitHub,開発以外の運営や外部の人や利用者とのやり取り（質問や要望）はOSDNで受け取って、開発にかかわることはissuesに反映するって感じですかね。

**Comment by KENCHjp** [comment]
ちなみにですが、私のコンシューマー向けな拙作ソフトOSDNで公開してるのですが、回答済かどうか追っかけるのがつらかったので、機能要望や質問もOSDNのチケットに倒しちゃいました。OSDNのチケットはオープンにできて、新規投稿の場合はタイトルと、種類（バグか質問か要望かとか）を選んで内容書いてポストするだけなのでシンプル。
コンシューマー向けソフトなのですが、意外と皆さんチケット使ってくれます。

ただここだと、チケットとissuesのダブルメンテは避けたいので、OSDNのチケットのうち回答済とかissuesに投げたらもうクローズするって運用でしょうか。
ご参考でした。

**Comment by kobake** [comment]
> ＞https://github.com/orgs/sakura-editor/teams/sakura-developers
> こっちですが、自分でためしに作ってみたのですが、Visibleだと組織に属している人に存在及び中身が見える状態で、Secretは、存在すら見えない状態になりました。

なるほど……


> 運営のやり取りをオープンディスカッションするのはOSDN側の方がいいかもですね。

チーム情報はオープンにできない感じに見えますが、GitHub Issues 等の情報は全部オープンにできるので、これだけをもって OSDN 側に倒す理由にはならないな～と思いました。


> ちなみにですが、私のコンシューマー向けな拙作ソフトOSDNで公開してるのですが、回答済かどうか追っかけるのがつらかったので、機能要望や質問もOSDNのチケットに倒しちゃいました。OSDNのチケットはオープンにできて、新規投稿の場合はタイトルと、種類（バグか質問か要望かとか）を選んで内容書いてポストするだけなのでシンプル。
> コンシューマー向けソフトなのですが、意外と皆さんチケット使ってくれます。

なるほど～。
たしかにフォーラム形式だと、話が終わったスレッドと進行中のスレッドの区別付かないですね……。
今後はチケット式に倒していきたいです。


> ただここだと、チケットとissuesのダブルメンテは避けたいので、OSDNのチケットのうち回答済とかissuesに投げたらもうクローズするって運用でしょうか。

ダブルメンテは避けたいですね。
OSDNチケットの GitHub Issues より便利なところがあればOSDNチケット検討しますが、ぜんぶ GitHub 乗せのほうが楽な気がします。

OSDN領域はGitHub怖い人向けの救済場所として残しておくぐらいがちょうどいいのでは、というのが今の自分としての所感です。

**Comment by KENCHjp** [comment]
＞OSDN領域はGitHub怖い人向けの救済場所として残しておくぐらいがちょうどいいのでは、というのが今の自分としての所感です。

私も怖い人の一人です、でも、kobakeさんと同感で、ここは乗り越えた方がいいんじゃないかなとも思ってます。
情報が分散して収拾がつかなくなる懸念 or 情報が集まりにくくなる懸念はありますが、どちらが正解かはきっと「時」が解決するんじゃないかなと思います。

サクラエディタって、いい意味悪い意味含めて純粋なOSSだと思うんです。
最初の開発者含めてその時その時で貢献できる人が貢献できるとき力を注いで育っていく。
他のOSSってうっかりすると商用ソフトになってったりするところ、本当に有志だけで、それも中心人物がいない（いや変わっていく）OSSって他にあるのでしょうかね。

そして、統計とったわけじゃないですが、きっと日本で一番使われてるテキストエディタだと個人的に思っています。
今日、ここにいられることに幸せを感じれます。
余談でした。

**Comment by kobake** [comment]
> どちらが正解かはきっと「時」が解決するんじゃないかなと思います。

そですね、適宜、役目を終えた場所があれば順次閉鎖していくくらいの感じでやっていきましょう。

時代に応じてその時代に合った人が協力体制を作りやすい「場」を皆で維持していくのが大事かと思っています。今後ともお付き合いよろしくです！

**Comment by KENCHjp** [comment]
こちらは、sakura-developersは見せられない仕様ってことで、運営は専用リポジトリ＆チャットはDiscordでオープンなのでIssue的にはクローズですかね？

**Comment by kobake** [comment]
そですね、チーム情報はオープンにできない仕様っぽいので、本 Issue は「諦める」ということでクローズします

**Comment by m-tmatma** [comment]
> そですね、チーム情報はオープンにできない仕様っぽいので、本 Issue は「諦める」ということでクローズします

これ、いけますか?
https://help.github.com/articles/changing-team-visibility/

**Comment by KENCHjp** [comment]
![default](https://user-images.githubusercontent.com/39618965/44307696-dcab8f00-a3e1-11e8-8858-994d04df21f4.PNG)

とりあえず、設定変えてみました。

**Comment by KENCHjp** [comment]
@m-tmatma さん
やっぱダメそうです。

**Comment by m-tmatma** [comment]
ありがとうございます。了解です。

**Comment by m-tmatma** [comment]
GitHub のサポートに問い合わせた。
現状ではできないらしい。

> Thank you for getting back to us.
> > 
> >     Some members of the organization made the account settings to be public.
> >     But the list can't be accessible from non-members and visitors who are not
> >     logged in.
> 
> Teams can either be "visible", which means all organisation members can see them, or "secret", which means the team and its members are only visible to the members of that specific team and the organisation's owners.
> 
> You can read more about this here:
> 
> https://help.github.com/articles/changing-team-visibility/
> 
> It isn't possible to make a team and its members visible for GitHub users that are not members of the organisation. I'll record this as a feature request for our team!
> 
> I hope this helps clear things up, do let me know if you have any other questions.

**Comment by m-tmatma** [comment]
現状の仕様では無理なので閉じます。
