### ISSUE TITLE
HTML Help Workshop (Visual Studio 2017 のインストール)に関して

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#357]
HTML Help Workshop (Visual Studio 2017 のインストール) に関して

[build.md](https://github.com/sakura-editor/sakura/blob/62f742ca278224d848f21b1c5312d141b9ea70ce/build.md#html-%E3%83%98%E3%83%AB%E3%83%97%E3%81%AE%E3%83%93%E3%83%AB%E3%83%89%E3%81%AB%E5%BF%85%E8%A6%81%E3%81%AA%E3%82%82%E3%81%AE) には

`HTML Help Workshop (Visual Studio 2017 のインストールでインストールされます。)
`

とあるが、標準ではインストールされなかった。

**Comment by KENCHjp** [comment]
>HTML Help Workshop (Visual Studio 2017 のインストールでインストールされます。

とありますが、私の環境でVisual Studio 2017インストールして個別モジュール等見てもHTML Help Workshopが見当たらず。。。

2017から標準でインストールされなくなったって情報もあったのですが、私見落としてますかね？？？

**Comment by berryzplus** [comment]
html help workshopは個別で追加インストールが必要な認識です。
追記しといたほうが良さそうですね。

HTML Help Workshop and Documentation 1.32
https://www.microsoft.com/en-us/download/details.aspx?id=21138

仕組みがよく分っていませんが、
sandcastleというHTMLを入れると依存関係としてインストールされるようになってそうです。
https://github.com/EWSoftware/SHFB

**Comment by m-tmatma** [comment]
インストールのオプションによるのかもしれません
インストールのときにいくつかのオプションを設定してインストールしてます。

**Comment by KENCHjp** [comment]
@m-tmatma さん @berryzplus さん

なるほど、何かに引きずられて入るのかもしれませんね。

私個別にインストールしちゃいました。
もうちょっと調べてみます。

**Comment by KENCHjp** [comment]
一応今は公式は、

https://docs.microsoft.com/ja-jp/previous-versions/windows/desktop/htmlhelp/microsoft-html-help-downloads

ここみたいです。日本語用もあるもよう。

**Comment by KENCHjp** [comment]
>日本語用もあるもよう。

まちがえました、日本語ヘルプがあるだけでした。

**Comment by berryzplus** [comment]
> 一応今は公式は、
> 
> https://docs.microsoft.com/ja-jp/previous-versions/windows/desktop/htmlhelp/microsoft-html-help-downloads
> 
> ここみたいです。日本語用もあるもよう。

ここのサイトはサルベージされた過去ドキュメント置き場の認識です。
URLにあるとおり `previous-versions` です。

初期版 html help workshop はshiftjisを扱えなかったらしいです。
日本語を扱えるように改造したバージョンも過去には存在していた模様。

1.3とか1.4というのは htmlhelp.exe の規格バージョンみたいなもので、
vistaに搭載された htmlhelp.exe は 1.4対応 らしいです。

1.4規格に対応した SDK は存在せず、2012年にドキュメントのみ更新された模様。
結果として [1.3sdk + 1.4document](https://www.microsoft.com/en-us/download/details.aspx?id=21138)が最新・・・のはず。

sandcastle は html help を作るためのもので、microsoft傘下で開発されてたこともあるツールで
visual studio のプラグインとしても動作できる help エディタ。
ビルドシステムに html workshop を使うので、インストール時に依存関係でインストールできるようになってるっぽい・・・。

**Comment by KENCHjp** [comment]
>なってるっぽい・・・。

なるほどです。結局VS触りまくった挙句、わからず単体で落としちゃいました。。。

**Comment by m-tmatma** [comment]
> なるほど、何かに引きずられて入るのかもしれませんね。

どのオプションを有効にしたら、インストールされるのか調べようとしましたが、
C++ 関連の構成を無効にしても、削除されませんでした。

次回クリーンインストールする機会があったら調べようと思います。

あるいは誰か次にクリーンインストールする機会があったときに調べていただけるとありがたいです。

※ このチケットのタイトル変えました。

**Comment by KENCHjp** [comment]
>※ このチケットのタイトル変えました。

了解です。
クリーンインストールはいつでもできるので試してみます。

**Comment by KENCHjp** [comment]
どこに入っているか見つけました。

![1](https://user-images.githubusercontent.com/39618965/44616720-dc9f0980-a88f-11e8-8867-cf183a3872e2.PNG)
![2](https://user-images.githubusercontent.com/39618965/44616721-dd37a000-a88f-11e8-8252-919d1386892c.PNG)

**Comment by m-tmatma** [comment]
ありがとうございます。
マークダウンに追加していただけますか？

**Comment by KENCHjp** [comment]
#366 にて修正。

**Comment by KENCHjp** [comment]
![vsi](https://user-images.githubusercontent.com/39618965/44622575-012dcc80-a8f6-11e8-906a-14d8cd6dfac9.PNG)

説明用に画像作成。

**Comment by KENCHjp** [comment]
@k-takata さんから、この条件だけじゃ、HTML HELP Workshopが入らんってツイートがあったので、
reopenしました。
もうちょっと調べます。

**Comment by KENCHjp** [comment]
わかりました。
hhc.exeはコンパイラとのことで、
hhw.exe(ヘルプワークショップ本体)は入らないって事のようです。

なので、マークダウンの表現の、

HTML ヘルプのビルドに必要なもの
- HTML Help Workshop

ここを、

- HTML Help Workshop のhhc.exe

とかにしたほうがいいのかなと思いましたが、いかがでしょう？

**Comment by k-takata** [comment]
「HTML ヘルプコンパイラ (hhc.exe)」でどうでしょう？
あとは、ヘルプファイルを編集するなら HTML Help Workshop も必要になるかもということをどこかに書いたらどうでしょうか。

**Comment by KENCHjp** [comment]
@k-takata さん、どうもです。
それでいきましょう。で、以下デフォルトですが、
![default](https://user-images.githubusercontent.com/39618965/44627080-c0b86800-a962-11e8-9583-8c474c8e7e44.PNG)

「C++ に関する Windows XP サポート」もチェックが入ってないとコンパイルが失敗するようなので、こちらもオプション追加が必要の旨記載したほうがいいかなと。
ちょっと今日はもう時間的余裕がないので、来週にでも。

**Comment by KENCHjp** [comment]
閉じます！
