### ISSUE TITLE
cppcheck の結果を見やすく整形する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#368]
cppcheck の結果を見やすく整形したい。

現状では cppcheck は xml 形式で出力されているが、そのままでは結果を確認するのは困難なので
人が見て理解できる形式に整形して出力したい。

### 参考

https://github.com/danmar/cppcheck/tree/master/htmlreport

で以下コマンドを実行することにより、 html 化できる。
(ただ cppcheck のインストーラには含まれていないので cppcheck を clone する必要がある)

`python <path_to_script>\cppcheck-htmlreport --report-dir=<出力先ディレクトリ> --file=<xml ファイル名>
`
#### 事前準備

`pip install --user pygments
`

**Comment by berryzplus** [comment]
参照用の xslt ってcppchekの開発元では共有されてないんですか？
・・・って調べればすむ話ですね。
Excel2007以降ならxmlを直接開いて「表」として見ることが可能です。
「表」として見る、以上のことをやりたい場合に限定してツールが必要だと思ってます。

**Comment by KENCHjp** [comment]
極力デフォルトってことならば、

https://teratail.com/questions/66917

PowerShellっすかね。

**Comment by berryzplus** [comment]
visual studio の「エラー一覧」に出せると、
ダブルクリックでジャンプできたり「修正適用」のメニューが使えそう・・・みたいな感じがします。
既存プラグインとかないんでしょうか・・・

これどうですかね https://marketplace.visualstudio.com/items?itemName=Alexium.Cppcheckadd-in

**Comment by m-tmatma** [comment]
SonarQubeとCppcheckを連携させる
http://replication.hatenablog.com/entry/2019/01/27/223358

**Comment by m-tmatma** [comment]
関連 https://github.com/sakura-editor/sakura/pull/674

**Comment by kazasaku** [comment]
新しいバージョンのCppcheckならば、結果をHTMLで出せるようです。
https://srz-zumix.blogspot.com/2021/02/cppcheck-html-report.html

**Comment by kazasaku** [comment]
> SonarQubeとCppcheckを連携させる http://replication.hatenablog.com/entry/2019/01/27/223358

このブログで紹介されている設定項目がSonarCloudだと見つかりませんでした。

**Comment by berryzplus** [comment]
vs2017対応で取り込み済み。 https://github.com/sakura-editor/sakura/blob/master/parse-buildlog.py
vs2019には非対応。
Visual Studioの現行バージョンはvs2022なので既に微妙。

結局、ログ整形しても修正対応しないなら整形する意味はなくね？の一言に尽きると思っていて。

ということで一旦閉じてしまいます。

必要あれば新たにissue立ててください。
