### ISSUE TITLE
デフォルト値変更リクエスト「ファイル排他をしない」に変更

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#379]
現在デフォルト値がファイル排他するになっていますが、これをファイル排他しないに変更要望です。
意外とこれの「悪評」を身内でもネットでも見かけます。

**Comment by kobake** [comment]
同意に一票 👍

**Comment by m-tmatma** [comment]
#263 で対応済みのはずですが
なってないですか？

**Comment by KENCHjp** [comment]
おまじすか、失礼しました。
じゃ次期リリースでそうなるってことですね！
確認しますが、周りにも伝えます！！！
