### ISSUE TITLE
HTML Help 中のリンクを GitHub のものに変える

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#380]
HTML Help 中のリンクを GitHub のものに変える

### オンラインヘルプ

旧: http://sakura-editor.sourceforge.net/htmlhelp2/
新: https://sakura-editor.github.io/help/
参考: https://github.com/sakura-editor/sakura-editor.github.io/pull/22

変更が必要な箇所の例

https://github.com/sakura-editor/sakura/blob/4c58aeb2fda06c5bc966a14233fc99cde351f774/help/sakura/_RESOURCE/HLP_UR015.html#L275

### プロジェクトページ

旧: http://sakura-editor.sourceforge.net/
新: https://sakura-editor.github.io/

変更が必要な箇所の例

https://github.com/sakura-editor/sakura/blob/4c58aeb2fda06c5bc966a14233fc99cde351f774/help/sakura/_RESOURCE/HLP000001.html#L20

**Comment by m-tmatma** [comment]
オンラインヘルプの URL に関して参照している箇所は過去の履歴だから変更していいものかどうかどうしよう。

```
[仕様変更]<br />
<ul>
	<li>オンラインヘルプは http://sakura-editor.sourceforge.net/htmlhelp2/ を参照する (svn:1943 unicode:1621 ryoji)</li>
	<li>MRUに適用タイプ別設定を追加 (svn:1939 upatch:3315685 unicode:1582 wiki:Request/111 もか)</li>
	<li>マウススクロールでも少し滑らかにするオプションを適用 (svn:1916 unicode:1561 もか)</li>
</ul>

```

**Comment by KENCHjp** [comment]
>オンラインヘルプの URL に関して参照している箇所は過去の履歴だから変更していいものかどうかどうしよう。

＋蟹

変更しないに一票。

**Comment by beru** [comment]
先ほどマージしました。
