### ISSUE TITLE
installer\externals\bregonig\bron412.zip がビルド要件になっている件について

### ISSUE THREAD

**Issue by yoshinrt** [sakura-editor/sakura#388]
ビルド要件に `installer\externals\bregonig\bron412.zip` を置くこと，が追加されているようですが，build.md あたりにそのことが記載されていないようです．

個人的な希望ですが，上記をビルド要件にしてしまうより，bron412.zip の展開をインストーラビルド時に移動していただくほうが，コードデバッグ→ビルド時に毎回 zip 展開が発生しなくて良いと思うのですが，いかがでしょうか?

(すみませんリターンキーを押したら submit されてしまって，何度も記述修正入っています)

**Comment by berryzplus** [comment]
ビルド要件ではない認識です。
デバッグするとき便利だから解凍処理を組み込んだつもりです。
解凍処理が組み込まれていることにより、何も考えずにデバッグすると「正規表現あり」の状態でデバッグできるようになりました。「正規表現なし」のデバッグをしたい場合は、dllを削ってから実行すればよいと思っています。

**Comment by m-tmatma** [comment]
> ビルド要件に installer\externals\bregonig\bron412.zip を置くこと，が追加されているようですが，build.md あたりにそのことが記載されていないようです．

https://github.com/sakura-editor/sakura/tree/4c58aeb2fda06c5bc966a14233fc99cde351f774/installer/externals/bregonig

GitHub に bron412.zip の実体が登録されているので、ユーザーがわざわざ削除しない限りそこにあります。

**Comment by m-tmatma** [comment]
> 個人的な希望ですが，上記をビルド要件にしてしまうより，bron412.zip の展開をインストーラビルド時に移動していただくほうが，コードデバッグ→ビルド時に毎回 zip 展開が発生しなくて良いと思うのですが，いかがでしょうか?

ビルドするたびに展開するのが気になるのであれば zip を展開したDLL が
存在しないときのみ、展開するみたいな最適化はできると思います。

**Comment by yoshinrt** [comment]
一点目，bron412.zip がビルド要件になっているの件は私の勘違いでした．お騒がせしてすみません．

二点目，ビルド時に毎回 zip 展開が入る件は，処理が遅いのが気になっていたのですが，これも 7zip にパス通せば速くなるって書いてあったのに今気づきました．
まだ試していませんが，気にならない程度であれば毎回展開でも良いと思います．

というわけで，この issue は取り下げさせてください．

**Comment by m-tmatma** [comment]
> 二点目，ビルド時に毎回 zip 展開が入る件は，処理が遅いのが気になっていたのですが，これも 7zip にパス通せば速くなるって書いてあったのに今気づきました．
> まだ試していませんが，気にならない程度であれば毎回展開でも良いと思います．

手元の環境で試すと

bron412.zipを
7zip で解凍した場合            → 0.15 秒
powershell で解凍した場合 → 8 秒くらい
でした。

**Comment by berryzplus** [comment]
> powershell で解凍した場合 → 8 秒くらい

長っ！ｗ

初回ビルド時に csc.exe でpowershellの内容をコンパイルしたexeを作る、みたいな対応を
マジメに考えたほうがよいかも知れませんね。

個人的には HeaderMake.bat と githash.bat 、unzip.bat が出力するメッセージがやたらと長いことのほうが気になりました。何も変更がなくてもメッセージが出力されるのは精神衛生上よくないです。現状の出力を `--verbose` にして初回のみ詳細出力を行う仕様に変えたり、出力先が最新かどうかチェックしてメッセージを抑制する対応を入れたほうがよいかもしれません。

対応は気が向いたら、ということで :smile:

**Comment by m-tmatma** [comment]
> 初回ビルド時に csc.exe でpowershellの内容をコンパイルしたexeを作る、みたいな対応を
> マジメに考えたほうがよいかも知れませんね。

7zip を使うと速いので、単に 7zip をインストールしてもらえばいいだけだと思います。

**Comment by m-tmatma** [comment]
> 個人的な希望ですが，上記をビルド要件にしてしまうより，bron412.zip の展開をインストーラビルド時に移動していただくほうが，コードデバッグ→ビルド時に毎回 zip 展開が発生しなくて良いと思うのですが，いかがでしょうか?
> 
> ビルドするたびに展開するのが気になるのであれば zip を展開したDLL が
> 存在しないときのみ、展開するみたいな最適化はできると思います。

#390 を送りました。
