### ISSUE TITLE
ダイアログの表示位置が表示するたびにずれていく

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#397]
手元での再現方法

1. タスクバーを上または左に固定。
2. DIFFダイアログを表示して閉じる。
3. またDIFFダイアログを表示する。

タスクバーのサイズ分表示位置がずれる。

**Comment by m-tmatma** [comment]
確かに再現しますね。

**Comment by KENCHjp** [comment]
でも、優先度最弱でいいかと、画面からはみ出さなそうなので。

**Comment by berryzplus** [comment]
windowsの使い方としてレアだと思います。
面白パターンとして残しておいてもよいような気がしないでもない・・・。

----

ここがダイアログ位置の復元処理コードです。

https://github.com/sakura-editor/sakura/blob/e1bd5e37401e85d3a54636335c5c7e762cef51d5/sakura_core/dlg/CDialog.cpp#L232

本来このユーティリティ関数は、引数を3つとります。

https://github.com/sakura-editor/sakura/blob/e1bd5e37401e85d3a54636335c5c7e762cef51d5/sakura_core/util/os.cpp#L109-L114

3つめの引数も渡すようにして、
どこにタスクバーがあるか判定してあげればよいと考えられます。

**Comment by berryzplus** [comment]
> 私の会社のPCは、左なんですよね(笑)

昔、大学の図書館にNEXT端末が置いてあって、
そいつのタスクバーが右端だったのを思い出しました。
会社とかで使う端末は、いろんな事情で変わった設定になってることありますね。

**Comment by KENCHjp** [comment]
余談ですが自宅PCは右です。
NEXT Stepを真似たかったからではなく、
左上に初期画面がでるアプリと、
ノートPCの縦が狭いので右にせざるをえませんでした。

ごく初期の自宅PCは上でした。
Macを真似たかったからです。

ほとんど下にしたことがありません。。。

**Comment by m-tmatma** [comment]
#687 で対応を検討中だけど、4か月動きがない。

**Comment by beru** [comment]
#1711 が Merge されて対応が出来たと思うので Close します。
