### ISSUE TITLE
sakura_core/util/other_util.h にある auto_array_ptr も廃止して、std::unique_ptr で置き換える

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#400]
@beru  
https://github.com/sakura-editor/sakura/pull/396#issuecomment-417901154

> sakura_core/util/other_util.h にある auto_array_ptr も廃止して、std::unique_ptr で置き換えてしまって良いと思います。
> 
> 例えば、
> 
> auto_array_ptr<OneRule> test(new OneRule[1024]);
> 
> と書かれているのは、
> 
> auto test = std::make_unique<OneRule[]>(1024);
> 
> と置き換えられると思います。
> 
> 過去にやった事があるので別PRを作成しましょうか？
>

**Comment by beru** [comment]
#404 を作成しました。

**Comment by m-tmatma** [comment]
#404 がマージされた。
