### ISSUE TITLE
アウトライン解析ウィンドウのタイトルバーをマウスで動かすと表示されるドッキング位置の表示が高DPI環境でおかしい

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#406]
![test](https://user-images.githubusercontent.com/1131125/45036610-ec8cc980-b097-11e8-86e7-55c6fcc415a0.gif)

**Comment by beru** [comment]
この現象を改修するには、 `CDlgFuncList::Track` メソッド内で `WM_MOUSEMOVE` メッセージを扱う際のドラッグ中のドロップ先矩形の描画処理に手を入れる必要があると思いますが具体的にどう変更すれば直るのかは分かっていません。

**Comment by k-takata** [comment]
これ、わざわざ自前で枠線を描画してるんですか？
今時のWindowsってデフォルトではドラッグ中にウィンドウの中身を表示するようになってますが。
中身を表示させたくないならWindowsの設定でオフにした方がよいのでは…

**Comment by beru** [comment]
d930cdc355a7454920470c9367a4a53cca3bdb11 で実装されています。

ドッキング枠のプレビュー表示の関係で自前で描画してるんですかね。

Vista 以降は DWM が動作しているのでティアリングが軽減されましたが遅延が増えました。

**Comment by k-takata** [comment]
ああ、ドッキング対応のためですか。ただ、ドッキングもウィンドウの中身を表示しながらできるのであれば、その方がいいような気がします。

**Comment by berryzplus** [comment]
掲示板に有識者のものと思われる書込みがあったので転載。

> 363名無しさん＠お腹いっぱい。2018/09/06(木) 23:54:46.10ID:VTQu5CEm0
> Github Issuesの「アウトライン解析ウィンドウのタイトルバーをマウスで動かすと表示されるドッキング位置の表示が高DPI環境でおかしい」なんだけど、これってサクラに標準添付されてるはずの高DPI awareなsakura.exe.manifestファイル適用もせずに騒いでたりしない？ 

騒いでいる意識はないんですが、彼（？）の推察が当たってそうなので拾ってみます。
こっちに書いてくれればいいのに、とも思いますが人それぞれ色々事情もあるのかな。

書込みにある「標準添付されてるはずの(ry」とはこれと思われます。

https://github.com/sakura-editor/sakura/blob/4993b21e29b944be945b6e0cc1bcf57c0cdcf91e/installer/sinst_src/sakura.exe.manifest.v#L15-L19

manifestファイルというのは、win32サブシステムがプログラムを起動するときに、プログラムがサポートする機能を確認するために使う情報のことです。通常はプログラム内部に埋め込むものなのですが、サクラエディタのインストーラではwindows 9x系との互換性のために「exeの隣に置く」という方式で配布されているようです。

これはインストーラでインストールした場合にだけ適用される設定ファイルなので、
ソースコードをビルドして実行した場合には適用されない設定です。

つまり、どういうことかというと、
**高DPI対応アプリを示すマーカーを設定したら、この問題は発生しない可能性がある**
ということです。

manifest設定は、通常はexe内部に埋め込むものなので、
設定するとすれば vcxproj に書き込む内容になります。

チェックしてみたら、設定されていませんでした。
とりあえず、該当する設定を組み込むためのPRを投げておきます。

**Comment by k-takata** [comment]
そういえば、自分のところではHiDPIだけどちゃんと動いてるなーと思っていたのですが、manifestが置いてありました。

> windows 9x系との互換性のために「exeの隣に置く」という方式で配布されているようです。

manifestを埋め込んでいるとwin9xで動かないなんてことありましたっけ？
（単に当時は別ファイルにするのが楽だっただけではないかと。）

**Comment by berryzplus** [comment]
> manifestを埋め込んでいるとwin9xで動かないなんてことありましたっけ？
> （単に当時は別ファイルにするのが楽だっただけではないかと。）

騙されてた...orz

**Comment by k-takata** [comment]
Windowsでmanifestが使われるようになったのはXPのvisual style対応の時で、その後Vistaで実行権限の設定に対応したときに、XPでちゃんと動かないという問題が出たこともありましたが、確かXPの修正で直ったはず。XPより前はそもそもmanifestに対応していないので完全に無視されるはず。

もしかして、元々はvisual styleに対応するにはmanifestを置くようにガイドしてたんでしたっけ？

**Comment by beru** [comment]
@berryzplus さんPRありがとうございます。

**Comment by beru** [comment]
こちらは bug だったのかというとそうではないと思います。

**Comment by KENCHjp** [comment]
>こちらは bug だったのかというとそうではないと思います。

ユーザ視点で、この修正はchange logには並んでてほしいですね。
エンハンスかバグかは、バグよりな気がしますが。
