### ISSUE TITLE
ライセンスの話

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#41]
[OSDNフォーラム](https://osdn.net/projects/sakura-editor/forums/34093/39615/)から移行。この話は今後は GitHub Issues 側でやっていきましょう。

## 概要
ライセンスをどうするか。今のところ候補に挙がっているのは「zlib」「MIT」くらい。

## 関連スレッド
- http://sakura-editor.sourceforge.net/cgi-bin/cyclamen/cyclamen.cgi?log=data&tree=s8407
- https://osdn.net/projects/sakura-editor/forums/34093/39615/

**Comment by kobake** [comment]
https://osdn.net/projects/sakura-editor/forums/34093/39613/81367/
```
2018-05-28 21:57 berryzplus

・ライセンス明確化調査'
やっぱ公開した方がいいですよね。

UNICODE化した時点で
ソースコード全体が二次著作物になったと考えられるので、
ライセンス明確化の呼びかけ以前のもの(v1)についてだけ調査してます。
最終結論は前の掲示板に書いたほど明快にはなりませんでした。

そのうち公開しなきゃなと思っています。
```

https://osdn.net/projects/sakura-editor/forums/34093/39615/81372/
```
2018-05-29 11:23 kobake

zlib で問題ないかな～と思ってます。MIT でも良い気もします。
```

https://osdn.net/projects/sakura-editor/forums/34093/39615/81408/
```
2018-06-02 12:16 berryzplus

zlibで問題ないと思っています。

主な違い
・zlib　アプリでライセンス表示不要、原作者詐称禁止、改変物は原作と区別できなければならない。
　　https://ja.wikipedia.org/wiki/Zlib_License　https://www.zlib.net/zlib_license.html
・MIT　アプリでライセンス表示必須、詐称に関する定めなし、改変物に関する定めなし
　　https://ja.wikipedia.org/wiki/MIT_License
```

https://osdn.net/projects/sakura-editor/forums/34093/39615/81413/
```
2018-06-02 19:53 kobake

MIT についてはライセンス表示必須というよりはライセンスの分かるものを配布物に同梱、という解釈で良いかと。
```

**Comment by kobake** [comment]
[pluginリポジトリ](https://github.com/sakura-editor/plugin)部分の[ライセンスは GFDL になっている](https://github.com/sakura-editor/plugin/blob/master/help/Text/HLP_LISENCE.html)ようですが、ここはどうしましょうか。
メンテナンスしやすいように sakura リポジトリへ統合することを考えていますが、今のライセンス形態のままだとディレクトリ毎に異なるライセンスを適用するように文書を配置する必要が出てきます。

**Comment by kobake** [comment]
macroリポジトリも同様にGFDLになってました。これもsakuraリポジトリへ統合することを考えています。
https://github.com/sakura-editor/macro/blob/master/help/source/gfdl.html

**Comment by kobake** [comment]
helpリポジトリも同様にGFDL。同じくsakuraリポジトリへの統合を検討中。
https://github.com/sakura-editor/help/blob/master/_RESOURCE/HLP_LISENCE.html

**Comment by berryzplus** [comment]
GFDLの件、少し気になっていました。

zlib と GPL は互換性のあるライセンスなので
「基本zlib、一部zlib + GPL」は許容される認識です。
GFDLはドキュメント向けのライセンスなので同じ理屈が通るかどうか微妙な気がしています。

できれば詳しい方の意見をいただきたいところ。
OKだと思っていますが、あってます？的な・・・

**Comment by KageShiron** [comment]
根本的にサクラエディタ本体とヘルプ文章は独立した著作物なので独立してライセンスを指定できると思います。
GFDLのメリットは薄いので、変更できるならCC-BYやCC-0に変更した方がスッキリしそうではあります。(ただ、貢献者全員に許諾を得る必要があるなら、そこまでの手間を払う価値はなさそう)

そういえば、CHMヘルプもだいぶレガシー感がありますね・・・

**Comment by kobake** [comment]
サクラエディタ本体 … zlib
ヘルプ類 … GFDL

という感じにしますかね。

ちなみにインストーラが設置するファイル構成の全容をいまいち把握していなかったので、実際にインストーラを動かしてみてできたファイルの情報を以下にまとめておきました。
https://github.com/sakura-editor/sakura/wiki/PackageStructure

で、気になったのが keyword フォルダ配下のファイル群なのですが、これらは [installer リポジトリ](https://sourceforge.net/p/sakura-editor/code/HEAD/tree/installer/trunk2/) の sinst_src.zip というファイルに保管されていました。

これら keyword フォルダ配下のファイル群のライセンスをどうしたものか悩んでいます。（おそらくこれまではライセンス未定義の状態だった？）

> CHMヘルプもだいぶレガシー感がありますね・・・

レガシー感ありますね・・・
ユーザの使用状況知りたいですね・・・（皆活用してるんですかね）

**Comment by berryzplus** [comment]
> > CHMヘルプもだいぶレガシー感がありますね・・・
> 
> レガシー感ありますね・・・

ちょっと関係ない話ですが、モダンなヘルプってどんなんですかね？
gitのヘルプは設定によってWebヘルプになりますけどああいうの？
レガシー感あるねって感覚はなんとなく分かる気がするんですが、
それを認めても「じゃ、モダンって何？」の答えが出ませんでした。

MicrosoftがHtmlHelpの後継として出したのは Microsoft Assistance Markup Language というものな認識ですが、ほとんど普及してないような。自家製powershellのヘルプに使うアレですよね。外から持ってくるソフトのヘルプはchmかWebヘルプな気がします。

[sand castle](https://github.com/EWSoftware/SHFB)
オープンソース化していたことに今気付きました・・・

**Comment by berryzplus** [comment]
ライセンスの話ですが、ライセンスを宣言するファイルも入れるのがベターな気がしてきました。
zlibはバイナリ配布にライセンスを添付する必要がない認識ですが、あえていれましょう、という話。

あと、インストーラに含めて配布している bregonig.dll のライセンス.txtが足りてないようです。どちらかに決めてライセンス文を添付するか、両方のライセンス文を添付して選んでくださいとユーザに丸投げするか、いずれにしても配布するtxtが足りてないのを対処する必要がありそうです。
#66

**Comment by kobake** [comment]
配布パッケージにはライセンス文書は入れる、で良いと思います。入れない理由があんまりありません。

**Comment by KageShiron** [comment]
> モダンなヘルプってどんなんですかね？

Webヘルプだと思います。chmは **ネットに繋がない状況で止むを得ずみるヘルプ** という印象です。ただ、サクラエディタはネット接続が制限されるような会社で使われているという話もあるので、廃止すりゃいいというものでもないという微妙なところ・・・

htmlファイルをそのまま一緒に配布するというのも見かけはしますがchmと比べてメリットがあるかと言われると

> keyword フォルダ配下のファイル群

キーワードの羅列のみのファイルは創作性がない(=著作物ではない)ので適当に扱って問題なさそう。創作性がありそうなファイルも、更新も兼ねて著作権がなくなるレベルまで書き換えてしまっても良いかも・・・

(もちろん、貢献者さんへの感謝は忘れない前提で)

**Comment by kobake** [comment]
ふむふむ。雰囲気把握です。
キーワードについては（どういう理由か分かりませんが）リポジトリ上では zip になってて編集しにくいので、展開した形で今後は管理していきたいと思ってます。そうすると Pull requests 受け付けやすいので。
https://github.com/sakura-editor/sakura/tree/master/installer

**Comment by m-tmatma** [comment]
> ちょっと関係ない話ですが、モダンなヘルプってどんなんですかね？
> gitのヘルプは設定によってWebヘルプになりますけどああいうの？

Gitbook というサービスがあるみたいです。
https://gomachan46.gitbooks.io/how-to-use-gitbook/content/index.html
https://qiita.com/nekogeruge_987/items/46dfb552b33aac4ef9b0

Markdown でドキュメント書くみたいです

**Comment by m-tmatma** [comment]
リンク追加
https://dev.classmethod.jp/devenv/install-gitbook/
https://github.com/GitbookIO/gitbook

**Comment by KENCHjp** [comment]
モダンなヘルプですが、VB4ぐらいの頃からMicrosoftのヘルプと付き合っておりますが、
毎度ヘルプの構造が変わってしまうのを追っかけるオーバーヘッドに疲れ果てたので、
http://docwiki.embarcadero.com/RADStudio/Tokyo/ja/HTML_%E3%83%98%E3%83%AB%E3%83%97%E3%81%AE%E7%A8%AE%E9%A1%9E
結局素のhtmlファイル一個にまとめてしまいました。
ブラウザが入ってることが必須になってしまいますが、ブラウザの入ってないWindowsは存在しないかと思いますので。

**Comment by KENCHjp** [comment]
>サクラエディタ本体 … zlib
ヘルプ類 … GFDL

でlicensefileをインストーラーに入れますか？

**Comment by berryzplus** [comment]
> > サクラエディタ本体 … zlib
> > ヘルプ類 … GFDL
> 
> でlicensefileをインストーラーに入れますか？

本体のライセンスファイルって誰か作ったんでしたっけ？
「入れましょう」の前に作らないといけない認識です。
というか「ライセンスはヘルプに入れよう」という話があったような・・・。
（本体のライセンスはヘルプにあるのかも知れません。）

ヘルプのライセンス(GFDL)は本文にハードコーディングされています。
作らなくてよいし、同梱する必要もない認識です。

ヘルプにいれてしまうとパッとみてどこにあるかわからない、というのがデメリットですね。

**Comment by KENCHjp** [comment]
>というか「ライセンスはヘルプに入れよう」という話があったような・・・。

なるほど、ではそれでいきますか。
単体のファイルってどっかに公に配布されてるものあるのかしら。。。
単に「zlibです」って宣言すればいいのかな。。。

**Comment by KENCHjp** [comment]
#470 で、本件クローズでいいのかしら？

**Comment by KENCHjp** [comment]
一応、LICENSEファイルを同封して、READMEで宣言すればいいって認識かなと。

**Comment by beru** [comment]
配布パッケージにサクラエディタ本体のライセンス文書が含まれていないように見えます。

サクラエディタのヘルプ（sakura.chm）の「使用条件等」には、
> ・ソースコードの取り扱いについては、sakura.exeと同時に配布される文書によって、別途規定するものとします。

となっていて実行ファイルと同時に配布される別の文書ファイルがあるように説明されていますね。

**Comment by KENCHjp** [comment]
おっつ、インストーラーに入れないといけないんっすね。

**Comment by beru** [comment]
https://github.com/sakura-editor/sakura/issues/41#issuecomment-395107970 以降のコメントの流れだとそのようですね。

**Comment by beru** [comment]
というか1日ぐらい前に、berryzplus さんがコメント入れてますね。https://github.com/sakura-editor/sakura/issues/41#issuecomment-423791661

本体のライセンスに関する文言をヘルプに記載するのか、それとも別ファイルで本体と同梱するのか、ですね。後者だとしてもヘルプにライセンスファイル名が書かれていないので更新した方がベターだとは思います。

**Comment by beru** [comment]
リポジトリのルートフォルダに置くライセンスファイルですが、今現在ファイル名が `LICENSE` となっていますが、`LICENSE.txt` か `LICENSE.md` に変えた方が良いですね。そうする事で見え方が変わってきます。

https://help.github.com/articles/licensing-a-repository/#determining-the-location-of-your-license

**Comment by beru** [comment]
#475 を作ってライセンスファイルに拡張子を付けてみたんですが、
https://github.com/search?o=desc&q=license%3Azlib&s=stars&type=Repositories
で検索して見つけた https://github.com/uNetworking/uWebSockets/blob/master/LICENSE
を見ると別に拡張子が付いていなくても表示が変っていますね。

ライセンスファイルの中の記述の問題なのかな。。

**Comment by berryzplus** [comment]
> おっつ、インストーラーに入れないといけないんっすね。

ぼくの認識
GitHub上へのライセンスファイル追加の必要性：あり　（現状だとわかりにくかったから）
インストーラに同梱の必要性：なし　（ヘルプファイルに同梱されているから）

本来インストーラは、インストール時に EULA を表示すべきで、
今現在 EULA を表示すべきところで「？」な文書を表示していることは違う問題だと思います。
※ EULA ＝ [End User License Agreements](https://ja.wikipedia.org/wiki/%E3%82%BD%E3%83%95%E3%83%88%E3%82%A6%E3%82%A7%E3%82%A2%E5%88%A9%E7%94%A8%E8%A8%B1%E8%AB%BE%E5%A5%91%E7%B4%84)

「ライセンス」が指すものと「 EULA 」が指すものは似ているようで違う気がします。

**Comment by KENCHjp** [comment]
>インストーラに同梱の必要性：なし　（ヘルプファイルに同梱されているから）

了解です！

**Comment by beru** [comment]
ヘルプファイルのどこに（何が？）同梱されていますか？

**Comment by beru** [comment]
再度書きます。

サクラエディタのヘルプ（sakura.chm）の「使用条件等」には、
> ・ソースコードの取り扱いについては、sakura.exeと同時に配布される文書によって、別途規定するものとします。

となっていて実行ファイルと同時に配布される別の文書ファイルがあるように説明されています。

インストーラーにライセンスファイルを同梱しないのであれば、この記載を見直す必要があるように思います。

**Comment by berryzplus** [comment]
> ヘルプファイルのどこに（何が？）同梱されていますか？

ヘルプファイルに書いてないっすね。
あるとしたら[ここ](https://sakura-editor.github.io/help/HLP000004.html)。

https://github.com/sakura-editor/sakura/blob/52049dbd0594133a22192acb3a5d6a7bf4119030/help/sakura/_RESOURCE/HLP000004.html#L7

この一文をみる限りだと「ライセンス文書の同梱が必要」と読めます。
> ・ソースコードの取り扱いについては、sakura.exeと同時に配布される文書によって、別途規定するものとします。

「同梱文書が多いと面倒だからヘルプに記載するようにしよう」ってやり取りは一体どこにいったんだろう :smile:

**Comment by KENCHjp** [comment]
>「同梱文書が多いと面倒だからヘルプに記載するようにしよう」ってやり取りは一体どこにいったんだろう 😄

ま、決めちゃえばいいのかも。

**Comment by KENCHjp** [comment]
>LICENSEをそのまま使えればいいですが、英語文書って日本人読まないし(^-^;

確かに読まないですが^^;、原文が正しいので必ず原文を添付して日本語訳は参考程度って、この手の話では教わりますです。

最近テレビのマニュアル等にも最後の方にOSSのライセンス（英文）の全文がついてますよねぇ。

**Comment by berryzplus** [comment]
ではこっちでｗ

> https://ja.osdn.net/projects/opensource/wiki/licenses%2Fzlib_libpng_license
> この辺の日本誤訳を LICENSE.ja-JP とかで保存して入れる、というのが一案。

**Comment by m-tmatma** [comment]
> この辺の日本誤訳を LICENSE.ja-JP とかで保存して入れる、というのが一案。

`誤訳`?

**Comment by berryzplus** [comment]
> > この辺の日本誤訳を LICENSE.ja-JP とかで保存して入れる、というのが一案。
> 
> 誤訳?

のおおおおおおお :cry:

日本誤訳があるのは msdn ですよね。
zlib licenseの翻訳は誤訳じゃないと思ってます。

**Comment by jakenjarvis** [comment]
Python製の [Sphinx](http://sphinx-users.jp/gettingstarted/) というのがあります。
これだと、マークアップランゲージ（ [reStructuredText](https://quick-restructuredtext.readthedocs.io/en/latest/) ）でドキュメントを作成しておき、その後、ビルドしてHTMLページやPDF、EPUB（笑）などに出力できます。
確かCHMも出せたはず・・・あった [class sphinx.builders.htmlhelp.HTMLHelpBuilder](http://www.sphinx-doc.org/ja/stable/builders.html#sphinx.builders.htmlhelp.HTMLHelpBuilder) たぶんこれでいける。

> このビルダーは標準のHTMLビルダーと同じものを出力しますが、MicrosoftのHTML Help Workshopで使用できる、HTMLヘルプのサポートファイルも生成します。これらの入力をHTML Help Workshop上でコンパイルすると、CHMファイルが生成されます。

※そのreStructuredTextで記載したファイルなどを一式githubリポジトリにあげておき、AppVeyorでビルドして各種ドキュメントを成果物としてZIP同梱まで自動化できると思います。

**Comment by m-tmatma** [comment]
> Python製の [Sphinx](http://sphinx-users.jp/gettingstarted/) というのがあります。

#492 を作りました。

**Comment by KENCHjp** [comment]
@jakenjarvis さん、こちらにコメントしようとして放置してしまいました。
 reStructuredTextについては初めて知りました。markdownよりもより柔軟性があるけどシェアだけないって感じによめました。
学習工数が必要になりそうですが、他の成果物のメンテの工数との見合いでしょうか。
確かに、オンラインヘルプとローカルヘルプと、さらにWiki等を一つのリソースから生成できるのは楽できそうですね。

**Comment by m-tmatma** [comment]
> Python製の [Sphinx](http://sphinx-users.jp/gettingstarted/) というのがあります。

これに関しては、暇を見つけてこつこつ勉強しようと思います。
#492 にチケットがあります。

もともとの「ライセンスの話」は終わったと思うので閉じます。

**Comment by beru** [comment]
CHANGELOG.md を眺めててここに辿り付きましたが、enhancement かというと微妙な気がします。

**Comment by KENCHjp** [comment]
機能改善ではないので、とりましょう＜エンハンス。
