### ISSUE TITLE
エクスプローラの右クリックメニューに、『SAKURAでGrep』を追加する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#410]
現状ファイルに対して、『`SAKURAで開く`』という右クリックメニューが存在するが、
フォルダに対して右クリックしたときに、『`SAKURAで Grep`』という項目を追加して
右クリックしたフォルダを基準に grep ダイアログを開く機能を追加する。

### 必要なコマンドラインに関して

https://sakura-editor.github.io/help/HLP000109.html

| オプション | 説明 | 
|:-----------|:-----------|
|`-GREPMODE`  |grep モードで開く |
|`-GREPDLG`  |grep ダイアログを開く ( grep は走らせずに grep ダイアログが出るところで止める) |
|`-GFOLDER`  |grep のフォルダを指定する |
|`-GOPT` オプションで `S` と `P` を指定する | サブフォルダを対象にする。該当行を表示する |
|`-GCODE=99`  |文字コートの自動判定にする |

### シェル側の対応に関して

参考サイト (エクスプローラの右クリックメニューをカスタマイズする)
* http://ascii.jp/elem/000/000/953/953807/
* https://qiita.com/tueda/items/0036ee8e9280f70f04f0

以下のような内容で reg ファイルを適用したらフォルダの右クリックメニューに登録して 
grep ダイアログを表示できた。(**実際の変更では 『SAKURAでGrep』になります**)

[sakuraでgrep.reg.txt](https://github.com/sakura-editor/sakura/files/2357132/sakura.grep.reg.txt)
(適用するには拡張子 の ".txt" を取ってください。)

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\directory\shell\sakuraGrep]
@="サクラエディタでgrep"

[HKEY_CLASSES_ROOT\directory\shell\sakuraGrep\command]
@="\"C:\\Program Files (x86)\\sakura\\sakura.exe\" -GREPDLG -GREPMODE  -GFOLDER=\"%1\" -GOPT=\"S\""
```

### 対応

上記のレジストリキーをインストーラで書き込む

**Comment by m-tmatma** [comment]
#385 を実装するのなら `サクラエディタで Grep置換` も実装してもいいと思う。

**Comment by m-tmatma** [comment]
https://qiita.com/tueda/items/0036ee8e9280f70f04f0
で `何もないところを右クリックした時のメニューを追加する` にあるように

`HKEY_CLASSES_ROOT\directory\BackGround\shell\sakuraGrep` 以下にレジストリーキーを
追加することで、フォルダの何もないところで右クリックして、`サクラエディタで Grep`
を実装できた。

[sakuraでgrep-何もないところで右クリック.reg.txt](https://github.com/sakura-editor/sakura/files/2357216/sakura.grep-.reg.txt)
(適用するには拡張子 の ".txt" を取ってください。)

↓ 以下を reg ファイルとして保存するには UTF16 BOM 付きで保存してください。


```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\directory\BackGround\shell\sakuraGrep]
@="サクラエディタでgrep"

[HKEY_CLASSES_ROOT\directory\BackGround\shell\sakuraGrep\command]
@="\"C:\\Program Files (x86)\\sakura\\sakura.exe\" -GREPDLG -GREPMODE  -GFOLDER=\"%V`\" -GOPT=\"S\""
```

### 注意点

`-GFOLDER` の引数は `%1` ではなく `%V` です。

**Comment by m-tmatma** [comment]
> 上記のレジストリキーをインストーラで書き込む

以下に足せばいいと思う。

https://github.com/sakura-editor/sakura/blob/4aa227c4aec130e1faa6a0f7da47b23fa0ca0e31/installer/sakura-common.iss#L84-L95

**Comment by berryzplus** [comment]
「SAKURAで開く」なので
「SAKURAでGrep」がベターなのではないでしょうか。

大文字小文字、GrepとGREPとgrep。一般的なのはどれ？

**Comment by KENCHjp** [comment]
>「SAKURAで開く」なので

これでいいのか最近気になってます。
別Issueですね。

>大文字小文字、GrepとGREPとgrep。一般的なのはどれ？

考えたこともなかったけど、「Grep」でいいような。

**Comment by m-tmatma** [comment]
すみません。PR (#411) では『SAKURAでGrep』にしてました。
『SAKURAで開く』をコピーして修正して作ったので その流れで
自然に 『SAKURAでGrep』になりました。

**Comment by KENCHjp** [comment]
>自然に 『SAKURAでGrep』になりました。

一旦はいいかなと思います。Grep機能を呼び出すPRなので。「SAKURAで～」がいいのかは別かなと。

**Comment by m-tmatma** [comment]
#411 を更新しました。

**Comment by m-tmatma** [comment]
#411 で英語メニューに対応しました。

**Comment by m-tmatma** [comment]
マージしました
