### ISSUE TITLE
Grepのコマンドラインオプションを分かりやすくしたい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#419]
## このissueの目的

Grep関連のコマンドラインオプションにまつわる問題を整理する。

## 解決したい課題

Grepの除外ファイル・除外フォルダの指定方法が分かりづらい。
オンラインヘルプにも直接的な説明がないので、ほぼ誰も知らない機能になっている。
有用な機能なのでもっと簡単に使えるようにしたい。

## 事実確認

Grep関連オプションの指定方法が本当に分かりづらいのかどうか検証するため、
実装されているオプションの一覧とヘルプファイルの記載を比較してみます。

### 現状のGrep関連オプションの実装内容

現状(v2.3.2)のGrep関連オプションは下表の通りです。

オプション | Grep | 置換 | 効果
---- | ---- | ---- | ----
`-GKEY` | ○ | ○ | 検索パターンを指定
`-GREPR` | - | ○ | 置換パターンを指定
`-GFILE` | ○ | ○ | 対象ファイル、除外ファイル、除外フォルダを指定
`-GFOLDER` | ○ | ○ | Grep開始フォルダを指定
`-GOPT` | ○ | ○ | Grepオプションを指定
`-GCODE` | ○ | ○ | Grep文字コードを指定
`-GREPMODE` | ○ | ○ | 開始と同時にGrep実行
`-GREPDLG` | ○ | - | 開始時にGrepダイアログを表示

### 現状のヘルプファイルの記述内容

コマンドラインに関するヘルプ
https://sakura-editor.github.io/help/HLP000109.html

`-GFILE` の説明には、この項目が「除外ファイル、除外フォルダ」の指定に使える旨の記載がない。
`-GREPDLG` の説明には、この項目を「Grepダイアログ」の表示に使う旨の記載がある。

Grepダイアログに関するヘルプ
https://sakura-editor.github.io/help/HLP000067.html
(ファイル) の説明に、この項目が「除外ファイル、除外フォルダ」の指定に使える旨の記載がある。
この項目がコマンドラインオプション `-GFILE` に対応する旨の記載はない。

### 実装と記述を比較した結果の判断

分かりづらいと思います。
ヘルプに説明がないわけではありませんが、情報が分散していて関連を想像できないと思います。

### どうしたらよいか？

関連を想像できないのが問題ならば、リンクを貼ればよいと思います。
`-GFILE` とGrepダイアログ上の(ファイル)が同じ項目だと分かれば、
(ファイル)のところにはちゃんと説明がありますのでリンクで十分でしょう。

## 他issueとの関連

#75 で Grepダイアログの「除外ファイル・除外フォルダ」の指定方法を分かりやすくしたい、という課題が上がっています。#75 を解決するためのPRとして #403 が上がっています。
`-GREPDLG` が Grep置換 に対応してないことについて #385 で課題が上がっています。

#403 では `-GFILE` のオプション仕様の分かりづらさ対策として、
新オプションの追加が提案されています。

オプション | Grep | 置換 | 効果
---- | ---- | ---- | ----
`-GEXCLUDEFILE` | ○ | ○ | 除外ファイル `(!*.*)` を指定
`-GEXCLUDEFOLDER` | ○ | ○ | 除外フォルダ `(#*)` を指定

これらが指定された場合、一旦 `-GFILE` の先頭に結合されてから、
対象ファイル、除外ファイル、除外フォルダに再分解される仕様（オプションが増えること以外は従来通り）となるようです。
（ @m-tmatma さん、間違い、補足があれば追記をお願いします。）

**Comment by m-tmatma** [comment]
> #403 では -GFILE のオプション仕様の分かりづらさ対策として、
> 新オプションの追加が提案されています。

-GFILE の仕様のわかりずらさを改善するためではなく、
grep ダイアログでの `(ファイル)` の仕様のわかりづらさを改善するためのものです。
https://sakura-editor.github.io/help/HLP000067.html

コマンドラインオプションを追加したのは、grep ダイアログに新しい設定項目を追加したので
それに追従してコマンドラインで使用できるようにしました。

コマンドラインの変更は 主ではなく副です。

> これらが指定された場合、一旦 -GFILE の先頭に結合されてから、
> 対象ファイル、除外ファイル、除外フォルダに再分解される仕様（オプションが増えること以外は従来通り）となるようです。

 `-GFILE の先頭に結合` する訳ではありません。
`-GFILE  の内容`をパースして、要素に分解してその結果を内部クラスに格納します。
`除外ファイル` と `除外フォルダ` も同様に要素に分解してその結果を内部クラスに追加します。

以下を参照

https://github.com/sakura-editor/sakura/pull/403#issuecomment-419574020

**Comment by m-tmatma** [comment]
わかりづらさでいうと以下の Grepダイアログの説明も十分わかりにくい   :smile:
https://sakura-editor.github.io/help/HLP000067.html

コマンドラインオプションは、表で書いているので区切りがわかりやすいが、
https://sakura-editor.github.io/help/HLP000109.html

Grepダイアログの説明は区切りがどこなのかぱっと見た目わからない。

コマンドラインの説明の方は、『Grepに関するオプション』の表に
Grepダイアログでの対応項目を表す列を追加すればいいと思います。

どうように、grep ダイアログの説明を (表にした上で) 対応するコマンドラインオプションを
表す列を追加すればいいと思います。

相互リンクを、表の列の説明の部分とかに入れればいいと思います。

**Comment by berryzplus** [comment]
> コマンドラインオプションを追加したのは、grep ダイアログに新しい設定項目を追加したので
> それに追従してコマンドラインで使用できるようにしました。
> 
> コマンドラインの変更は 主ではなく副です。

コマンドラインオプションは、他プログラムとの連携で使えるものです。
システム開発の業界用語で言うと「外部I/F仕様」の一部になります。
一般的に外部I/F仕様は、内部設計の都合で変えてよいものじゃないと思います。

今回のケースで、コマンドラインに新オプションを追加する必然はありません。
UI項目追加による処理の追従は、既存オプションの組み合わせで実現できます。
あえてコマンドラインオプションを追加するには、それなりの動機が必要です。

> -GFILE の先頭に結合 する訳ではありません。

単純に、コードレビューしたら「そうした方がいいんじゃない？」という指摘になると受け止めてください。

**Comment by berryzplus** [comment]
> GUI 仕様とAPI 仕様を同等にする至極自然なことです。
> GUI 仕様でできることが、API 仕様でできないことは、API を使いたい人に取ってきわめてストレスになります。

もとのAPI仕様で実現できないなら、その説明で筋が通ってます。
今回のケースは変更前のAPI仕様で実現できます。

**Comment by berryzplus** [comment]
困難だけどできる、と、どうやってもできない、は違うと思います。

GUIで項目を追加したことにより、除外ファイルや除外フォルダを単独で指定できるようになるわけじゃないはずです。仕組み的に、Grep処理を行うためには、対象ファイル、除外ファイル、除外フォルダの3つが必要です。（DoGrepTreeのシグニチャ変えてるんでしたっけ？）

**Comment by ds14050** [comment]
一般論としては、GUI と CUI では最適な姿が変わってくるのが当然だと思います。つまり、GUI を変更したからコマンドラインにも変更を加えるのは**当然ではない**。

除外フォルダに単独のフィールドを与えたのは、内部設計(CGrepAgent::DoGrep の関数シグニチャ)から離れた GUI の最適化であったと思います。

GUI は常に眼前のユーザーを相手にしているために、わりあい自由に変更が可能だとしても、コマンドラインオプションはたとえばレジストリにオプションが記載されていたりするなど、比較すると融通が利きにくいといえます。

オプションを追加するときには問題が出ないとしても、削除はほぼ不可能です。同じことをする複数の方法があることは、わかりにくさにも繋がります。

コマンドラインオプションの追加を否定するわけではありませんが、それには別の議論が必要だと思います。とはいえ、コマンドラインオプションはヘルプを読まなければ記述できないのだから、ヘルプを拡充するだけで十分ではないかなとも思います。

**Comment by ds14050** [comment]
berryzplus さんと同じ勘違いを繰り返していた。内部仕様(CGrepAgent の公開インタフェイス)からがっつり変更されていた> #403。

**Comment by berryzplus** [comment]
> berryzplus さんと同じ勘違いを繰り返していた。内部仕様(CGrepAgent の公開インタフェイス)からがっつり変更されていた(予想外)> #403

マジですか・・・目的に疑問があるときは中身見ないので、実はまだ変更内容は見てなかったりします。

CGrepAgentはどうやってもテストできないクラスなので
なるたけ変更を加えない方法を探りたい感じです。
（もしかしてテストできるように変更してる？ならかなり嬉しい・・・）

**Comment by berryzplus** [comment]
#1116 を導入したことにより、コマンドラインの追加・変更はやりやすくなったかも知れません。

たぶん、根っこにあるのは「Grepの」じゃなくて「コマンドラインオプションが分かりにくい」ってことのような気がしています。色々考えてみた限り、この issue はまだ閉じられない気がしました。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394
