### ISSUE TITLE
エディタの各ドキュメントのタブ部分の右クリックメニューでエクスプローラを開く機能を検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#420]
エディタの各ドキュメントのタブ部分の右クリックメニューでエクスプローラを開く機能を検討する

Visual Studio 2017 のエディタでは、ドキュメントのタブ (ファイル名の表示される部分) の右クリックメニューで、ドキュメントの存在するフォルダを開く可能があるが、同様の機能が欲しい。

**Comment by arigayas** [comment]
_ユーザーが発言しても良いのかよくわかってませんが_
この機能は欲しいです。
ざっと確認したところ以下のテキストエディタで実装されていました。

- Notepad++
- Visual Studio Code

**Comment by ds14050** [comment]
ショートカットファイルの右クリックにならうと「ファイルの場所を開く」ですが、他のエディタはどうでしょうね。

**Comment by arigayas** [comment]
今日時点での最新バージョンのスクリーンショットです。


### Visual Studio Code 1.27.1
![image](https://user-images.githubusercontent.com/11251874/45255479-0b55cd80-b3c2-11e8-9c69-b4e019eec7a8.png)


### Notepad++ 7.5.8
![image](https://user-images.githubusercontent.com/11251874/45255501-51ab2c80-b3c2-11e8-8f66-4ea820962b79.png)

**Comment by beru** [comment]
| アプリ | 日本語 | 英語 |
|--|--|--|
| Visual Studio 2017 | このアイテムのフォルダーを開く(&O) |  &Open Containing Folder |

**Comment by berryzplus** [comment]
> ユーザーが発言しても良いのか

是非お願いします。

**Comment by arigayas** [comment]
わかりました。

**Comment by KENCHjp** [comment]
@arigayas さん、どなたでも発言Ok.ですどしどしお願いします。

**Comment by m-tmatma** [comment]
残件: 編集するウィンドウの中で右クリックした場合の対応
https://github.com/sakura-editor/sakura/pull/549#issuecomment-429667805

**Comment by m-tmatma** [comment]
> 残件: 編集するウィンドウの中で右クリックした場合の対応
> [#549 (comment)](https://github.com/sakura-editor/sakura/pull/549#issuecomment-429667805)

c63cf71db5d5379d22d170487d243d385457f381 で対応済み?

**Comment by berryzplus** [comment]
実は既に・・・ｗ

ただ、c63cf71 は初期値を設定してるだけなので、自分でカスタムメニューの設定を変えるか `sakura.ini` を再作成するまでは使えないです。いったん残件はなくなってますが、その部分が課題です。

新機能がメニューを変えるときの機能追随をどう考えるか、的なissueが立ってた気がします。
ここは閉じてもいいのかな？です。

**Comment by m-tmatma** [comment]
対応ありがとうございます。
閉じます。
