### ISSUE TITLE
build.md  の MingW のコンパイルに関する説明を更新する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#426]
#407 等の対応をして、build.md  の MingW のコンパイルに関する説明が古くなっているので更新する

**Comment by beru** [comment]
MinGW への対応は必須なのでしょうか？今現在の [README.md](https://github.com/sakura-editor/sakura/tree/470b8122dc0621732c945988dd7079b13c219289#build-requirements) には Visual Studio Community 2017 が必要と書かれていますが、MinGWについて書かれていません。

**Comment by berryzplus** [comment]
> MinGW への対応は必須なのでしょうか？

現状は必須。本質的には不要と考えています。

避けたいのは vc++ でしかコンパイルできない方言の強いコードです。
他コンパイラでもコンパイルできる一般的なc++コードになるように気を遣いたいです。
テストする他コンパイラがMinGWである必要は、ないと思っています。


いまMinGW対応を進めているのは、単にMakefileMake.exeを抹殺するために代替手段を提供したいという意図です。少なくともその話が終わるまではMinGW必須が続くと思っています。

**Comment by beru** [comment]
WindowsAPIべったりな実装なのでVisualC++じゃないコンパイラに対応する意義があるとは思えませんが、まぁあえて反対するのも野暮ってもんですね。。

**Comment by kobake** [comment]
実は自分もそれ思ってました。
が、自分の知らないメリットが実はあるのかなーとか想像しながら静観してます。

やりたい人がいて、それが他の方に害を及ぼさないのであれば反対はしません。メンテナンスコストが増える可能性についてのみ懸念はあります。
