### ISSUE TITLE
次期リリース機能選定

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#431]
今までのNext Releaseに向けての議論で目玉機能は以下二つだったかと思います。

- [ ] x64対応
- [x] Windows10対応

各々Issueを立てました。
現在進行中のIssue及びRPでNextReleaseに向けて必須なものは、看板のIn Progressへ追加してはどうかと思います。

他に、必須ではないがついかしてはどうかというものは、このIssueで検討し組み込む場合は、Issueたてて、In Progressへ順次追加ですかね。

**Comment by kobake** [comment]
https://github.com/orgs/sakura-editor/projects/1
カンバン貼っときます

**Comment by m-tmatma** [comment]
#326 を追加しました。
仕様をどうするかという話なので必要だと思います。

**Comment by arigayas** [comment]
![image](https://user-images.githubusercontent.com/11251874/49618991-0672db00-f9fe-11e8-9560-9916522b9071.png)
#683 のスクリーンショットを見て思ったのですが
次期バージョンの番号(2.4.0？)が決まっているのなら、
開発バージョンが
### sakura(Alpha Version) 2.3.2.0
となっているのは違和感(＊)があるので更新された方が良いと思いました。

(＊)違和感というのは、もうすでに2.3.2.0がリリースされているのに
このバージョン番号でアルファ版で開発がされていると勘違いさる可能性がある点です。

**Comment by m-tmatma** [comment]
> となっているのは違和感(＊)があるので更新された方が良いと思いました。

コメントありがとうざいます。

**お願い**

`確かメール通知であのコメントみたけど、どこに書いてあったかな?` と
探してチケット化するのが手間なので、独立したチケットにしていただけると助かります。

その上で、関連のある箇所のチケットに登録したチケット番号(#xxx)を書いていただくとありがたいです。
(xxx の部分が該当のチケット番号。そうすると自動的にハイパーリンクになります。)

単に質問だけのチケットでも要望でもいいです。
そのほうがスルーされて反応がないことも少なくなる(ゼロではない!)と思います。

**回答**

> (＊)違和感というのは、もうすでに2.3.2.0がリリースされているのに

これはローカルビルドのみです。
(つまり、自分でソースコードを取得して自分でビルドした場合です)

appveyor でビルドしたバイナリには末尾にビルド番号 (ビルドするたびにインクリメントされる数値)が入ります。(appveyor  は GitHub でソースコードをアップしたときに自動的にビルドしてくれるサービスです。)

例えば
https://ci.appveyor.com/project/sakuraeditor/sakura/build/job/sfrc57f1wya1it1j/artifacts
のビルドで artifacts をダウンロードするときに、build1324 という文字列が zip ファイル名に
入っているのを確認できます。

この 1324 という数値がビルド番号になりますが、バージョン番号の末尾にも使われます。
つまり、上記のバイナリの場合 2.3.2.1324 というバージョンになります。

appveyor でビルドしたバイナリは
異なるソースコードからビルドしたバイナリには必ず異なるバージョン番号が振られますし、
同じソースコードからビルドしてもリビルドした場合には異なるバージョンが振られます。

**Comment by berryzplus** [comment]
たぶん、`Alpha Version` の語感からくるズレの話をしてるんではないかな、と。

疑い）　sakura(Alpha Version) 2.3.2.xxxx
正？）　sakura 2.4 Alpha Version 2.3.2.xxxx

ということなのではないかと・・・。

そういわれてみればそれが正しいような気もします。

変えるのは（そんなに）難しくはないと思っています。
リリースするたびに Alpha の前の数字変えるの？という議論もあります。（変えればいい気がｗ

これに関しては意見、感想、いちゃもん、対案、それぞれ募集中って感じです。

**Comment by arigayas** [comment]
@m-tmatma さん
関係ありそうだなぁと思ってこのissueに書きました(汗)
あとで新たにissue登録しますね。

@berryzplus さんの推察通りです。
現行の表記）　sakura(Alpha Version) 2.3.2.xxxx
個人的にはこちら）　sakura 2.4 Alpha Version 2.4.0.xxxx

開発版で次のリリースバージョンの数字が決まった時点で
バージョンの数字は更新されるのが良いと思います。

**Comment by arigayas** [comment]
#685 を登録しました。

**Comment by KENCHjp** [comment]
本件一旦2.4.0ではx64対応はスライドWindows10はサポート対象（テスト対象）ということで。
x64は次バージョンにしましょう。
