### ISSUE TITLE
travis ci で cppcheck を実行出来ないか調査する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#432]
travis ci で cppcheck を実行出来ないか調査する
#427

**Comment by m-tmatma** [comment]
https://arne-mertz.de/2017/04/continuous-integration-travis-ci/
によると

```
install: 
  - sudo apt-get install -qq cppcheck
```

という処理で cppcheck をインストールするようだ。

**Comment by m-tmatma** [comment]
Travis-ci 関連の参考情報

- https://github.com/richelbilderbeek/travis_cpp_tutorial
- https://github.com/richelbilderbeek/cpp/blob/master/content/CppCppcheck.md
- https://github.com/richelbilderbeek/travis_qmake_gcc_cpp14_cppcheck/blob/master/.travis.yml

**Comment by berryzplus** [comment]
apt-getってやっぱりフリー版はlinuxのみですか...

**Comment by m-tmatma** [comment]
> apt-getってやっぱりフリー版はlinuxのみですか...

参考にしたサイトがそうなだけで windows もいけるみたいです。
https://docs.travis-ci.com/user/reference/windows/

ただ `Early adopters of our Windows environment` と書いてあるので、まだ実験的なものかもしれません。
https://docs.travis-ci.com/user/reference/windows/#support

**Comment by m-tmatma** [comment]
↑ ただ cppcheck を実行するという目的なら、OS は linux でも問題ないと思います。

**Comment by k-takata** [comment]
> という処理で cppcheck をインストールするようだ。

travisでは普通は、

```yaml
addons:
  apt:
    packages:
      - cppcheck
```

のようにsudoを使わずにパッケージをインストールします。sudoを使わない方が速いのです。ただ、インストールできるパッケージは許可されているものだけなので、もしcppcheckが許可されていないのであれば、許可するようにお願いするか、sudoを使わざるを得ません。

travisでWindowsは最近使えるようになったばかりなので、Linuxの方が情報も多くていいんじゃないでしょうか。

**Comment by m-tmatma** [comment]
travis で用意されている cppcheck は 1.61 だった。
https://travis-ci.org/m-tmatma/sandbox/builds/459304456

4年以上前 (ver 1.63 のリリースで 2014-01-04 ) のものを使っている。
https://sourceforge.net/p/cppcheck/news/

テストに使用した設定ファイルは
https://github.com/m-tmatma/sandbox/commit/ab4ccc9f9401de61e8b05c9e94bed4bfc815b9fb

**Comment by berryzplus** [comment]
> ↑ ただ cppcheck を実行するという目的なら、OS は linux でも問題ないと思います。

MinGW対応を引き継いだ理由の一つでもあるんですよね。
cross-GCC対応ならLinux環境しかないVMを使える可能性が残せるので。

**Comment by m-tmatma** [comment]
> これってもしかしてもう動きます？

はい。PR を投げました。
https://github.com/sakura-editor/sandbox/pull/8

> （なんかトリガになるキーワードなりを付けてpushするとビルドが走る？）

単に push する or PR を投げるだけです

該当のビルドです。
https://travis-ci.org/sakura-editor/sandbox/builds/459316224

@k-takata さんのビルドも、 `sudo apt-get install -qq cppcheck` も 試しましたが、
cppcheck のバージョンはどちらも `1.61` でした。

**Comment by m-tmatma** [comment]
> はい。PR を投げました。
> [sakura-editor/sandbox#8](https://github.com/sakura-editor/sandbox/pull/8)

PR の画面で `Show all Checks` をクリックすると appveyor と travis-ci の結果の
どちらを見るか選べます。

**Comment by berryzplus** [comment]
バージョンの話は、もしかするとdistの選択で利用できるもののバージョンが決まるからなのかもしれない、と思いました。`travis ci`のdistがどういう構成か分かりませんが`appveyor`と似た感じにベースパッケージを選択させてるんではないかと思うので。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/833 を対応したので閉じます。
