### ISSUE TITLE
タイプ別設定のカラーで強調キーワードの共通設定を押すと表示されるダイアログ表示でボタンが切れている

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#439]
![image](https://user-images.githubusercontent.com/1131125/45363886-ac879280-b613-11e8-8a8d-5d5e8836b88c.png)

ダイアログの下端にある `OK` と `キャンセル` ボタンが切れて表示されています。
OSのディスプレイ設定では 200% に設定しています。

**Comment by beru** [comment]
OSのディスプレイ設定が 100% だと切れないので、OS側の問題な気もします。。

**Comment by ds14050** [comment]
こういう過去がありますよ> [Sakura Editor / Code / Commit [r3879] Fix: 共通設定-ツールバーのリストボックスの高さが正しく設定されない](https://sourceforge.net/p/sakura-editor/code/3879/)

**Comment by beru** [comment]
スクリーンショットをぱっと見る限りではフォントサイズは悪くないように見えます。
ダイアログの縦幅はどうやって設定されているんでしょうね。

**Comment by ds14050** [comment]
このあたりではありませんか> https://github.com/sakura-editor/sakura/blob/749c669b0f153047768e78efc9664b016784a157/sakura_core/prop/CPropComKeyword.cpp#L109-L120

**Comment by beru** [comment]
おお、私のコードリーディング能力が低くて見つけられなかったのでありがたいです。
SetWindowPosの第6引数に `ボタンの下端 - ダイアログの上端 + 10` で指定していますね。

https://docs.microsoft.com/en-us/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows#updating-existing-applications

数値を 10 固定ではなくてDPIスケーリングに合わせるようにした方が良いですね。

**Comment by beru** [comment]
#443 が Merge されたのでこの Issue を Close します。
