### ISSUE TITLE
バージョンダイアログの "Share Ver" に関して

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#447]
バージョンダイアログの `Share Ver` で N_SHAREDATA_VERSION の値を表示しているが、

`Share Ver` が何を意味しているのかわからないので、`共有メモリのバージョン`とするか、
`N_SHAREDATA_VERSION` という内部で使用している名前をそのまま表示するとかした方がいいと思う。

**Comment by berryzplus** [comment]
`Share Ver` については「外部連携用のバージョン」という認識です。

サクラエディタは自分自身を複数起動するマルチプロセスアプリです。
自分自身と通信するにもプロセス間通信が必要になる都合で、内部定数を公開しています。


> Share Ver が何を意味しているのかわからないので、共有メモリのバージョンとするか、
> N_SHAREDATA_VERSION という内部で使用している名前をそのまま表示するとかした方がいいと思う。

自分なりに解釈してみました。

* バージョンダイアログの表示項目名がわかりにくくないか？
* 分かりやすい名前に変えたほうがいいんじゃないか？
* 適切な名前を選ぶのが難しければ、内部名を表示したらいいんじゃないか？

感じ方はひとそれぞれなので「なんとも」です。

* `Share Ver` でいいんじゃない？
* 十分意味が通ると思うので変えなくてよくない？
* `N_SHAREDATA_VERSION` を表示するは避けるべきです

`N_SHAREDATA_VERSION` を表示したら、「分かりにくくない？」→「名前変えましょう。」→「変えます。」→「内部に同じ文言があるのでついでに変えます」の流れになりそう。

変えたい、変えたくない、の中間をとって `ShareData Ver` にするのは許容です。

`Share` という名前は不適切なアプリを連想させるので表示するのをやめましょう、なら同意です。

**Comment by m-tmatma** [comment]
まず、この表示が誰のための表示かというのがポイントだと思います。

**Comment by m-tmatma** [comment]
> スクリプトマクロを組む人なら「最低限必要なバージョン」を確認するために使えるかもしれません。

- スクリプトマクロから取得できるのでしょうか?
- N_SHAREDATA_VERSION は共有メモリのバージョンだと思いますが、スクリプトマクロから見たときの仕様変更と連動しているのでしょうか?

**Comment by berryzplus** [comment]
> スクリプトマクロから取得できるのでしょうか?

まえに掲示板で見かけた気がするので「ある」前提で書きました。
いちおう書く前にちらっとCSMacroManager.cppを眺めた感じでは、なさそうでした。
ないと断言できるほどちゃんと見てません。

突っ込みの意図が見えませんが、どうしたいですか？

**Comment by m-tmatma** [comment]
> 突っ込みの意図が見えませんが、どうしたいですか？

開発者視点でも必要か? という確認です。

ユーザー視点で考えても、開発者視点で考えてもいらないのなら削除すればいいですし、
開発者視点で役にたつのなら、残してもいいですが、開発者以外のユーザーが混乱
しない表現にしたいです。

**Comment by berryzplus** [comment]
> 開発者視点でも必要か? という確認です。

アプリバージョンで確認できるので「不要」の認識です。

**Comment by m-tmatma** [comment]
#449 を投げました。

**Comment by berryzplus** [comment]
(`Share Ver` は バージョンダイアログから消えました。)

(表示してても実は使い道がない、というのが削除理由です。)

**Comment by kobake** [comment]
アプリバージョンが違ってもshareバージョンは同一というケースもありますけどね。終わった話なので構わんですが。

**Comment by ds14050** [comment]
以前は Share ver. が異なるサクラエディタを同時には起動できなかったはずで、その意味ではユーザー視点でも(よくよく詳しい人にとっては)意味がありました。今は異なる Share ver. のサクラエディタが共存できたと思ったので、用済みといえば用済みです。
