### ISSUE TITLE
exuberant ctags をインストーラに同梱したい

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#448]
exuberant ctags をインストーラに同梱したい

タグジャンプの機能は便利なので、インストーラでインストールしたときに
何もせずに使えるようにしたい。

http://hp.vector.co.jp/authors/VA025040/ctags/

ライセンスを見ると以下とあるので、再配布は問題ないはず。

`GNU General Public License Ver.3 (GPLv3) に従って複製、頒布、変更することができます。
`

**Comment by k-takata** [comment]
最近は [Universal ctags](https://github.com/universal-ctags/ctags) という後継があります。

**Comment by m-tmatma** [comment]
> 最近は [Universal ctags](https://github.com/universal-ctags/ctags) という後継があります。

http://hp.vector.co.jp/authors/VA025040/ctags/  には `exuberant ctags 日本語対応版` とあります。
`Universal ctags` は日本語対応しているか知ってますか?

**Comment by m-tmatma** [comment]
https://github.com/universal-ctags/ctags を見る限り、
まだリリースされたバージョンはなく、[絶賛開発中](https://hint.hateblo.jp/entry/2016/02/17/%E6%B0%97%E3%81%AB%E3%81%AA%E3%82%8B%E8%AA%A4%E7%94%A8) みたい。

**Comment by k-takata** [comment]
> `Universal ctags` は日本語対応しているか知ってますか?

exuberant ctags 日本語対応版が、何をもって日本語対応と言っていたのかは把握していませんが、Universal ctagsには入出力のエンコーディングを指定するオプションがあり、正しく指定すればShift_JISやEUC-JPのファイルも処理できます。

**Comment by m-tmatma** [comment]
> exuberant ctags 日本語対応版が、何をもって日本語対応と言っていたのかは把握していませんが、Universal ctagsには入出力のエンコーディングを指定するオプションがあり、正しく指定すればShift_JISやEUC-JPのファイルも処理できます。

サクラエディタ側で何かしないといけないことはありますか?

**Comment by k-takata** [comment]
> サクラエディタ側で何かしないといけないことはありますか?

サクラエディタがどのようにctagsを呼んでいるのかを知らないので分かりません。
ただ、u-ctagsはエンコーディングの自動判別といった気の利いたことはしませんので、正しいエンコーディングを指定して呼び出すということが必要になると思います。

一部のファイルだけエンコーディングを別のものにするといった細かい指定ができたかどうかは覚えていません。ファイルの種別単位で指定できたような気はしますが。

**Comment by m-tmatma** [comment]
> u-ctagsについてはいまのところどちらとも言えないです。
> 
> もとの ctags は安定版で既に開発が終了してる認識です。
> 継続して開発されているほうがいいような気がしますが、
> サクラエディタ側で追加対応が必要ならそこを手当てしてから同梱がいい気がします。

正式にリリースされてから `Universal ctags` を同梱でいいと思います。
今のうちは `exuberant ctags` を同梱して置けばいいと思います。

**Comment by k-takata** [comment]
日本語対応版の方は [`--jcode=ascii|sjis|euc|utf8`](http://hp.vector.co.jp/authors/VA025040/ctags/help_j.html) で日本語文字コードを指定するようですね。
u-ctagsは [`--input-encoding=encoding`](https://github.com/universal-ctags/ctags/blob/master/docs/news.rst#input-encoding-encoding-and-output-encoding-encoding), `--input-encoding-<LANG>=encoding` で入力エンコーディングを指定し、`--output-encoding=encoding` で出力エンコーディングを指定します。

これ以外の大きな差分は、[対応言語がかなり増えている](https://github.com/universal-ctags/ctags/blob/master/docs/news.rst#parser-related-changes)ことと、設定ファイルが `.ctags` から `.ctags.d/*.ctags` に変更になったことがあります。

**Comment by m-tmatma** [comment]
#451: exuberant ctags を組み込む PR
#454: Universal ctags を組み込む PR 
です。

どちらでもいけます。

**Comment by m-tmatma** [comment]
> #454: Universal ctags を組み込む PR

こっちを適用する場合はそれなりにテストが必要だと思いますが。

**Comment by m-tmatma** [comment]
> #454: Universal ctags を組み込む PR

こっちを採用したので 閉じます。
