### ISSUE TITLE
run-cppcheck.bat の実行に時間が掛かる

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#463]
build-all.bat でインストーラーを作成する際に cppcheck の実行に結構時間が掛かるのが気になります。
もうちょっとサクッといかないものかと…。

Windows だと start コマンドを使うと bg 起動が出来るようです。コマンドプロンプトの窓が新たに開かれそうな予感…。
https://tech.nikkeibp.co.jp/it/atcl/column/15/042000103/080600052/

**Comment by m-tmatma** [comment]
簡単なのは APPVEYOR のときにだけ実行するようにすればいいです。

https://www.appveyor.com/docs/environment-variables/

APPVEYOR のときは `APPVEYOR` という環境変数がセットされています。
ローカルで実行させたいときは、`APPVEYOR` をコマンドでセットするというものです。
ちょっとトリッキーですが。

わかりやすくするのだったら専用の環境変数を用意して、`APPVEYOR` がセットされていたら
それをセットするようにするというやり方があります。

**Comment by berryzplus** [comment]
> Cppcheck はソースコードにのみ依存していて他のビルド産物への依存はないため、バックグラウンドで実行してあとでログだけ回収しようとしました>master...ds14050:ConcurrentCppcheck

面白い思考実験だと思いました。しかも実現できたらかなりありがたいです・・・。

cppcheck　実は githash.h と funccode_enum.h の生成処理に依存。
helpファイルビルド　依存関係まったくナシ。
メインのビルド　依存関係なし。
インストーラのビルド　helpとメインのビルドに依存。

`start cmd /C` で走らせたバッチとの同期をいかに効率よく実現するかがカギなのかな、と思いました。ざっと見た感じ、同期自体はできそうなバッチになってると思います。効率よく、がカギ。

**Comment by ds14050** [comment]
結局エディタのビルドと並行するので CPU や IO が余っていないと取り合いになって効率が下がるんでしょうね。

githash.h と funccode_enum.h、funccode_define.h くらいならチェックが抜けていても気にしない性格です。そこを詰めようとしても面倒が勝ちます。

ヘルプのビルドは数秒で終わるので恩恵はないでしょう。#615 のコンソールログで「build-chm.bat」を検索するとわかります。

**Comment by berryzplus** [comment]
> 思考実験ではありません。動いています。

失礼。悪い意味で使った言葉じゃないです。気を悪くされたならごめんなさい。

> 結局エディタのビルドと並行するので CPU や IO が余っていないと取り合いになって効率が下がるんでしょうね。

`start` コマンドには優先度指定のオプションがあったはずです。
今調べてみたら `/LOW` と `/BELOWNORMAL` がそれっぽいです。
`cppcheck` を走らせるバッチの `start` コマンドにこれを指定してみたはどうでしょうか。

計っていませんが　ビルド時間　＞　cppcheck時間　なはずなので優先度を下げても大丈夫な気がします。ビルドを邪魔しないことで速くなるかも知れません。

**Comment by ds14050** [comment]
良い悪いではなく言葉の定義と正誤が問題です。

/LOW は IDLE と同じらしいのでずっと待たされそうです。/BELOWNORMAL を付けて
 master ブランチに rebase してみました。本当に効果があるのは #427 で言われているように他の CI を併用することなんでしょうね。

**Comment by m-tmatma** [comment]
appveyor で実行するのをやめました。
build-all.bat からも外しました。
閉じます。

#833 適用前 https://ci.appveyor.com/project/sakuraeditor/sakura/builds/23597175 → 48 min 57 sec
#833 適用後 https://ci.appveyor.com/project/sakuraeditor/sakura/builds/23615895 → 25 min 22 sec
