### ISSUE TITLE
性能強化案２ 並行処理の導入を検討する

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#467]
## 前置き

https://github.com/sakura-editor/sakura/issues/430#issuecomment-423569846

x64対応の過程で気付いた性能強化案の共有です。
やるかどうか、また、具体的にどうするかは別の話として、
これをやると何が嬉しいかについて書きます。

## 提案の内容

繰り返し処理の一部を並列化することにより、処理時間の短縮を図ります。

現在：　全ての処理が直列的に実行されるようになっています。
　↓
変更後：処理内容を整理して並列実行できる部分を並列化します。

## メリット

検索/置換、Grep/Grep置換、ファイルオープン/ファイル保存など、
サクラエディタの看板機能の大部分は並列化により高速化できます。

## デリット

現在のサクラエディタの処理構造は大きな処理ごとに大きな関数がある構造が基本です。
処理の並列化を行うためには処理単位を適切な位置で分割し、
役割分担できるように組み替える必要が出てきます。

## 対応計画

当面は計画なし :cry:

**Comment by KENCHjp** [comment]
チャレンジするのはとってもかっこいいしイイと思います。
(この仕事してて、かっこよさって必要ないかと思ってたのですが、とあるプロジェクトでUXやってるチームと仕事してて、かっこよさってモチベーションの一つになるんだなと思っております）

並列処理は実装もそうですが、テストも格段に複雑になっていくのと、発生する不具合も難解になっていく傾向にあるので、
開発メンバーの意思統一がより一層必要なのかというのが過去の経験からです。

とりあえず賛同の意思表示。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394
