### ISSUE TITLE
AppVeyor及びWin10でのバッチ内バッチ呼び出し

### ISSUE THREAD

**Issue by jakenjarvis** [sakura-editor/sakura#485]
手元の環境を作って、 [appveyor.yml](https://github.com/jakenjarvis/sakura/blob/90bb42807279501346f990b137bca1e0fac680d2/appveyor.yml) を手直しして、AppVeyorのDeployを試していたところ、ある不具合の原因に気が付きました。

「v2.3.2.0a」というタグを付けてビルドしたときに、zipArtifacts.bat でエラーが発生し、「Are you sure (Y/N)?」でビルド中に止まってしまう現象が起きました。

ビルドログは以下です。
https://ci.appveyor.com/project/jakenjarvis/sakura/build/1.0.2/job/j0g3df32aebeppxr

バッチ処理の該当箇所をローカルで簡易バッチを作成して試したところ、CMDでは動くけど、PowerShellでは動かないことがわかりました。（ログと同様の現象に見える）

簡易バッチは、以下のようなものを作りました。

## test.cmd
``` cmd
@echo off

set APPVEYOR_REPO_TAG_NAME=v2.3.2.0a

@echo checking APPVEYOR_REPO_TAG_NAME %APPVEYOR_REPO_TAG_NAME%
if not "%APPVEYOR_REPO_TAG_NAME%" == "" (
	@rem replace '/' with '_'
	set TEMP_NAME=%APPVEYOR_REPO_TAG_NAME:/=_%

	@rem replace ' ' with '_'
	set TAG_NAME=tag_%TEMP_NAME: =_%
)

echo %TAG_NAME%

echo -----
set BASENAME=sakura

@echo adding TAG_NAME
if not "%TAG_NAME%" == "" (
	set BASENAME=%BASENAME%-%TAG_NAME%
)
@echo BASENAME = %BASENAME%
```

## test2.cmd
``` cmd
@echo off
call test.cmd
```

これを、Windows10 64bitのcmd.exeで実行した場合
 * test.cmd --> 期待通り動作
 * test2.cmd --> ログと同じような不具合動作

になりました。

また、同環境のpowershell.exeで実行した場合
 * test.cmd --> ログと同じような不具合動作
 * test2.cmd --> ログと同じような不具合動作

となりました。

このことから、cmdのバッチファイルの中からcallで他のバッチファイルを呼び出すと、なぜかpowershellで実行されているように見えます。
ローカルのWindows10でこの挙動なので、AppVeyorも同様のことがおきていると思います。
（OSの設定画面で、コマンドプロンプトをpowershellに置き換える・・・みたいな設定があるので、ひょっとしたら、デフォルトコンソールがpowershellに固定されているのかもしれません）

appveyor.ymlでDeployするついでに修正しようかとも思ったのですが、どう直すべきか少々迷ったので、とりあえずご報告です。

**Comment by m-tmatma** [comment]
ありがとうございます。

直接の原因は判明していて、以下の部分の文字列置換処理がバグっているからです。

https://github.com/sakura-editor/sakura/blob/ec23dc76d7ae36cecf140f49c0107c1bfab0f0bc/zipArtifacts.bat#L52-L59

以下ブランチで修正中です。
https://github.com/m-tmatma/sakura/tree/feature/fix-artifact-name-with-tag

ただ期待通り動いていないので原因を調査中です。
https://ci.appveyor.com/project/m-tmatma/sakura/build/1.0.661

**Comment by m-tmatma** [comment]
以下が修正中のコードです。

https://github.com/m-tmatma/sakura/blob/5b18783028af7569353f3ffd9132ac33f5ad028c/zipArtifacts.bat#L52-L65

**Comment by m-tmatma** [comment]
> 以下が修正中のコードです。

参照しやすいように #486 で PR を投げました。

**Comment by m-tmatma** [comment]
> 直接の原因は判明していて、以下の部分の文字列置換処理がバグっているからです。

すみません。チケットの内容読んでませんでした。

**Comment by jakenjarvis** [comment]
@m-tmatma さん、確認ありがとうございます。
ただ、意図が伝わったのか、伝わらなかったのか・・・よくわからなかったです（笑）

で。個人的には、zipArtifacts.bat にバグがあるとは思っていません。cmd.exe上で動かす分には、該当箇所の置換処理が普通に動くからです。
ところが、バッチファイルをひとつ挟んでCallで呼び出すと、途端に動かなくなります。（たぶんこれが環境によっては動く環境があると思われる）

その動かなかったときの挙動が、powershell.exeでバッチファイルを動かしたときと同じ挙動に見えます。
なので、この問題は「OS等の環境依存の問題」との認識です。

（上記のtest.cmdについて、自分でもちょっとはまったのが、SETした変数をクリアしてなかったので、同じコマンドプロンプトの画面を開いたまま続けて実行すると、動いたように見えてしまうことがありました。注意してください）

ちなみに回避策の模索として、test2.cmdから「 `cmd /c test.cmd` 」で呼び出してみましたが、結果変わらずダメでした。「 `start /b test.cmd` 」も同じくダメ。（どっちにしろstartは非同期になってしまうと思うので、まずいかなーと思いますが）

とにかく、バッチファイルに少しの手を加えるだけの回避策があればいいのですが、私はそれを見つけられていません。

ローカルでのビルド環境を構築していないので、ローカルでは試していないのですが、AppVeyorだけでなく、様々な開発環境でビルドを通せるようにするとなると、バッチファイルでのビルドはそろそろ限界な気がします。（メンテナンスもバッチファイルは大変です・・・）
思い切ってpowershellに置き換えるか、AntとかMaven、Gradleのようなビルドツールを使ってはどうでしょうか。

あいにく私はJava/Androidで使われてるビルドツールしか知りません汗。上記「powershell、Ant、Maven、Gradle」のうちならGradleがおすすめです。（ただ、どれにしても学習コストが高いのが難点でしょうか）

**Comment by berryzplus** [comment]
@jakenjarvis さん
ご挨拶おくれました。たくさんの情報提供ありがとうございます。

windows 向けのビルドツールとしてはmsbuildというのがあるので、別ツールセットの導入はいまのところ考えていないです。(except: cmake)

ぼくも本来java屋なのでmaven化にはちょっとそそられてはいるのですが :smile:

なんとな～くの感想ですけど、`call` してる部分を `cmd.exe /C` に置き換えたらうまくいったりしませんかね。callが powershell で実行されている、というのであればcmdを指定したら解決するような。

**Comment by jakenjarvis** [comment]
こちらこそ、ご挨拶が遅くなりました。
私も最初にそう思って試してみましたが `cmd /c ` はダメでした。（上に書いたヨ！）
（ローカルのバッチファイルの時点でダメだったので、AppVeyorでの動作は確認してません）

callで本当にpowershellが動いているのかは、正直わからないです。が「そのように見える」というところです。

で、「ビルドツール」と一言でいうと、範囲が広かったですね（汗）
環境依存あたりを処理するような部分・・・えーと、依存関係の解決とかビルド環境構築、チェック機構あたりの部分です。（この説明でうまく伝わる気がしない。笑）

つまり私が言いたかったのは、 **msbuildよりももっと浅い層（バッチファイルで処理しているあたり）の置き換え** です。

バッチファイルの代わりに、powershellやpythonなどのスクリプト系言語で書いてもできるでしょうけど、見通しが悪くなるのはバッチファイルとさほど変わりません。

Java/Android界隈でGradleが選ばれた理由（AndroidStudioの標準ビルドシステムにGoogleが選んだ）は、「記述の少ない定義ファイルに見せかけ、かつ、プログラミング処理もガリガリかける柔軟性」を持った仕組みだからだと思っています。
（ただ、このプロジェクトでGradleを使うのは、正直厳しいかなとも思ってます。通りすがりの私が言ったところで・・・というのもありますネ^^;）
何か丁度いいツールがあればいいのですが・・・

ちなみにmavenはXMLベースで記述が多く、正直定義を作るのがしんどいです（笑）
そんなわけで、Javaでmavenかgradleかと問われれば、迷わずgradleを選びます。

**Comment by m-tmatma** [comment]
@jakenjarvis さん

> 私も最初にそう思って試してみましたが `cmd /c` はダメでした。（上に書いたヨ！）
> （ローカルのバッチファイルの時点でダメだったので、AppVeyorでの動作は確認してません）
> 
> callで本当にpowershellが動いているのかは、正直わからないです。が「そのように見える」というところです。

 #486 で修正できました。
原因は、環境変数の遅延展開をしていないからでした。(05c19a051824760134a6c8588429d3ee65c1dbf0 参照)

**Comment by m-tmatma** [comment]
> （ただ、このプロジェクトでGradleを使うのは、正直厳しいかなとも思ってます。通りすがりの私が言ったところで・・・というのもありますネ^^;）
> 何か丁度いいツールがあればいいのですが・・

ビルドツールにもとめる第一条件は `appveyor `で利用可能なことです。

サクラエディタでは、GitHub に push した時点で自動的にビルドが走って最低限の
チェックができるように、**無料で使える** クラウドベースの CI ツールを必要としています。
最初に、サクラエディタで CI を導入した時点で、Windows ベースで唯一利用可能な
 `appveyor ` を使用しています。

※ #446 で [Azure Pipelines](https://azure.microsoft.com/ja-jp/services/devops/pipelines/) を調べていて、 `appveyor ` を完全に置き換えられるのであれば、`Azure Pipelines` に乗り換えるかもしれませんが、今のところ、`appveyor ` で動作できることが必要です。

バッチファイルを頑張って使っている理由は、特に何もインストールしなくても動作するということと
`appveyor ` で動作する点です。

もともと一連のバッチファイルは、appveyor 上でのビルドを容易にして、簡単にローカル
でも再現できるようにするために作りました。

`appveyor ` で動作するという条件を満たしていて、既存の方法より優れていれば採用される可能性は
あります。`appveyor ` で動作できない場合、採用は難しいです。

**Comment by berryzplus** [comment]
> 私も最初にそう思って試してみましたが cmd /c はダメでした。（上に書いたヨ！）

ぐあｗ　書いてあったｗ　実はアフォなのがバレる・・・ :cry:
delayedExpansion を有効にしたら直ったみたいなので、なんか検討違いだったみたいですね。

> 何か丁度いいツールがあればいいのですが・・・

unix 系 autotools の 遺志 を継いだ cmake が単純でいいかなとは思ってますが、学習コスト高めです。
雰囲気的には python ベースのツールでいいのがあればそれになる気がしています。
あとはダークホース的に node.js 系のツールがあったら、jsonで設定できそうなんで簡単でいいかなぁ、とか :smile:

**Comment by jakenjarvis** [comment]
@m-tmatma さん、すみません。私の知識不足だったようです。環境変数の遅延展開なんて、初めて知りました。
ただ、手元のバッチファイルを同様に修正して試しているのですが、動かせてません（汗）

``` cmd
@echo off

set APPVEYOR_REPO_TAG_NAME=v2.3.2.0a

@echo checking APPVEYOR_REPO_TAG_NAME %APPVEYOR_REPO_TAG_NAME%
if not "%APPVEYOR_REPO_TAG_NAME%" == "" (
    @rem replace '/' with '_'
    set TEMP_NAME1=!APPVEYOR_REPO_TAG_NAME:/=_!
    @echo TEMP_NAME1 = !TEMP_NAME1!

    set TEMP_NAME2=!TEMP_NAME1: =_!
    @echo TEMP_NAME2 = !TEMP_NAME2!

    set TAG_NAME=tag-!TEMP_NAME2!
    @echo TAG_NAME = !TEMP_NAME2!
)

echo %TAG_NAME%

echo -----
set BASENAME=sakura

@echo adding TAG_NAME
if not "%TAG_NAME%" == "" (
    set BASENAME=%BASENAME%-%TAG_NAME%
)
@echo BASENAME = %BASENAME%
```

この出力結果が、手元だと、こうなってしまいます。

```
checking APPVEYOR_REPO_TAG_NAME v2.3.2.0a
TEMP_NAME1 = !TEMP_NAME1!
TEMP_NAME2 = !TEMP_NAME2!
TAG_NAME = !TEMP_NAME2!
tag-!TEMP_NAME2!
-----
adding TAG_NAME
BASENAME = sakura-tag-!TEMP_NAME2!
```

うちの環境がおかしいのかな・・・何かほかのせいにしたくなる・・・
これは何がおかしいのでしょう？；
後学のために、このあたり知りたいです。（もう少し、お付き合い頂けると嬉しいです）

-----

で、「ビルドツール」の言葉の範囲がいよいよ広範囲に解釈されている気がします。
たぶん３種類以上の機能が一つの言葉でおさまってる気がします。

 * 依存関係の解決を行い、ビルドを行う前準備をするビルドツール。
 * ソースコードから実行バイナリ形式に変換するビルドツール。
 * 成果物をテストするビルドツール。（必然的にソースコードから実行バイナリ形式に変換）

たぶんまだ役目があります。ものによって「カバーしている範囲が違う」ということですね。

私はAppVeyorをビルドツールとは認識してませんでした。いや、確かにビルドはするのだけれど・・・汗。

上記の会話では、CIツールを含めていませんでした。
なので、AppVeyorを入れ替えるような発言をしたつもりはありません。（誤解をといておきたい）
私が話題の対象としていたのは、「ビルドを行う前準備」の部分です。

-----
以下は、「成果物をテストするビルドツール＝CIツール」としての話です。

AppVeyorもTravisも、使えるツールは基本的に「なんでもOK」だと思っていいです。
ドキュメントに書かれているようなツール群は「初期セットアップ済み」という位置付けだと認識してます。なければダウンロードしてインストールしてしまえる環境なんです。（ただしインストールは全てコマンドで！）

なのでパッケージ管理ツールに登録されているようなコマンド一発でインストール可能なものは、ほぼ間違いなくインストールして使用可能です。仮想コンテナ環境内での管理者権限も与えられているハズです。
少なくともTravisのubuntu環境はそうでした。普通にsudo apt installで各種パッケージなどをインストールして使ってます。
パッケージ管理ツールは、Windowsにも [Chocolatey](https://chocolatey.org/) ってのがあります。
（Chocolateyは [AppVeyorにも初期セットアップ済み](https://www.appveyor.com/docs/windows-images-software/) で、 [sakuraエディタ](https://chocolatey.org/packages/SakuraEditor) も非公式でパッケージ登録されてます。知ってました？ぜひ公式登録してほしいところです！）
（MicrosoftもPackageManagementなるものを始めてますが、これはまだまだ使えたようなもんじゃありません。そのためWindowsでのアプリケーションパッケージ管理システムは現在Chocolatey一択ですが、アンインストールに難があるなど、これもまだLinuxのaptやyum、DNF等のパッケージ管理システムには遠く及ばない感触です。それ以外にdotNET環境の開発者向けパッケージはnugetが代表的ですね）

※Chocolateyの配布パッケージは社内端末配布向けにいくつか作ったことがあります。
※Azure Pipelinesは、ごめんなさい、私はまったく無知です。
※無料で使えることが前提なのは、もちろん理解しています。

-----

@berryzplus さん、おきにならさず（笑）
とりあえず、berryzplusさんには、このプロジェクトに関係なくgradleに触れてみてほしいと思いました。java屋さんなら多分気に入ります。

で・・・その他それっぽいのを検索してみましたが、以下はまったく知らないですし、責任持ちません！（これを評価する知識も持ち合わせていません汗）
https://ninja-build.org/
https://wiki.python.org/moin/WindowsCompilers
https://www.npmjs.com/package/windows-build-tools

また長文・・・ごめんなさい。

**Comment by k-takata** [comment]
@jakenjarvis `setlocal EnableDelayedExpansion` を呼んでいないように見えますが？

`if` とか `for` の中で条件に応じて環境変数を使いたいときには遅延展開が必要になることが多いですね。
ちなみに先日、遅延展開を有効にしたときに `!` を使いたくなったのですが `^^!` と書かないといけないようでハマりました。

**Comment by jakenjarvis** [comment]
@k-takata さん、ありがとうございます！動きました！
!での区切り記号を使うためには、 `setlocal EnableDelayedExpansion` が必要なのですね。勉強になります。

正直、今まで、ここまで複雑なバッチファイルを作ることになった（なりそうな）時点で、pythonとかwsh(vbs)とかで作ってたので、知らずに回避できてたようです。
