### ISSUE TITLE
python3でlog.xlsxが正常に出力できない

### ISSUE THREAD

**Issue by KageShiron** [sakura-editor/sakura#489]
python3でmsbuild-x64-Release.log.xlsxなどのファイルを作成するparse-buildlog.pyがエラーになります。
一応修正版は作成しました。
https://github.com/KageShiron/sakura/tree/fix/python-xlsx

しかし、出来上がるxlsxをエクセル(365最新版)で開くとエラーになります。python2で作ったものは大丈夫だし、修復を押せば一応開けはするのですが。

![image](https://user-images.githubusercontent.com/17571233/46143997-b7d6f100-c296-11e8-9fa2-21501b83f2c4.png)

ぐぐったらシート名にカッコが入ると悪いというのを見たので、264行目のカッコを消してみたのですが、だめでした・・・
```python
#			wsError.title = str(worksheetIndex) + "(" + code + ")"
+			wsError.title = str(worksheetIndex) + code
```

**Comment by m-tmatma** [comment]
#729 で PR 投げました。

**Comment by m-tmatma** [comment]
対応しました。
