### ISSUE TITLE
Pull Ruquest時のビルドが走っていないような・・・

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#49]
比較的軽い修正の詰め合わせ #48 のPRを送ったんですが、
appveyorのビルドが走っていないように見えます。
自リポジトリでのビルド確認はできているんですが、なんか微妙です。

**Comment by berryzplus** [comment]
関係ないけど、さっきから空投稿を繰り返しています。
"#"を入力した後にEnter Keyを押すとPostされてしまうIE11の挙動の謎。
単にテキストエリアからフォーカスが外れるからアクティブフォームのsubmitが反応してるだけのような気もしますが、空投稿は寂しい・・・。

**Comment by kobake** [comment]
あ、ちょっとwebhookの設定変えたせいっぽいです、直します

**Comment by kobake** [comment]
直しました！問題なければクローズお願いします。

**Comment by berryzplus** [comment]
確認できました。対応ありがとうございます。
