### ISSUE TITLE
サクラエディタの英語表記を考える

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#496]
サクラエディタの英語表記を考える

#491 でインストーラ中の サクラエディタの英語表記を `SAKURA Editor` としたが、
https://github.com/sakura-editor/sakura/pull/491#issuecomment-425697298 というコメントがあった。

`SAKURA Editor` がいいのか、`Sakura Editor` の方がいいのか、あるいは
それ以外何かあるのか考える。

**Comment by m-tmatma** [comment]
関連
https://github.com/sakura-editor/management-forum/issues/40

**Comment by beru** [comment]
個人的には Sakura Editor が良いと思いますが、こだわりは無いので SAKURA Editor でも良いと思います。

表記の統一に関してですが、

README.md の 最初の見出しが
```
# Sakura Editor
```
となっているので現時点の SAKURA Editor と一致しません。TOC (Table Of Contents) については VS Code の拡張で自動生成でしょうか。

あとこちらの Wiki http://sakura.qp.land.to/ の管理者がどなたか分かっていませんが、表記が統一されると良いなと思いました。

**Comment by KENCHjp** [comment]
>あとこちらの Wiki http://sakura.qp.land.to/ の管理者がどなたか分かっていませんが、表記が統一されると良いなと思いました。

掲示板をいじってるときにアカウント情報みつけたので直せそうです。
が、経緯的に過去のドキュメントはそのままでもいいところは無理に統一しないでもいいかなと思っております（あ、でも変えれそうなので、気運もりあがりましたらいつでもいけます！）

どちらかというとアプリの名称の揺れで困ったとの表記法の指針を決めたかったなと。

**Comment by m-tmatma** [comment]
`SAKURA Editor` と `Sakura Editor` だとソースコード上では `SAKURA Editor` の方が少数派みたい。

以下で検索できる。

`git grep "\bSAKURA\b"`
`git grep "\bSakura\b"`

**Comment by k-takata** [comment]
https://github.com/sakura-editor/sakura/pull/491#issuecomment-425697612
> https://talking-english.net/capital-letters/

そのサイトは私も見ましたが、それに倣うなら、文章の一部として書くなら原則 Sakura、ロゴやデザインやタイトルとしては SAKURA もありということになると思います。
（本文中で全部大文字は noisy だと言っていますね。）

**Comment by arigayas** [comment]
`SAKURA Editor` で統一になったのでしょうか？

**Comment by KENCHjp** [comment]
>SAKURA Editor で統一になったのでしょうか？

正式にはそうしましょうって感じで、厳密に一括置換しましょうって運びにはしてません。

**Comment by arigayas** [comment]
いずれ一括置換するのが良いと思います。
_定数にしていて簡単に変更出来るようになっているのでしょうか？_

**Comment by KENCHjp** [comment]
@arigayas さん、いつも貴重なご意見ありがとうございます。
今まで”表記”はこうしましょうって決めがなかったためか、あちこちで「揺れ」てるかと思います。
一括置換するのが正しいんでしょうけど、積極的に進めておりません、すいません。

英語名称を表す表記をとりあえず決めているのですが（日本語は「サクラエディタ」）、
積極的に置換しようと私から提案していないのは、これはプロジェクト総意ではなく個人的な意見ですけど、プログラム内でクローズせず、類似な文字として「タイトルバー文字列」「プログラム名、各種フォルダパス名」「インストーラー各種パラメータ」「エクスプローラーの右クリックメニュー」「各種ドキュメント内文字列」「URL」他、色々なところに似たような文字がでてくるのですが、全部「SAKURA Editor」にできるか、するべきかというと、出来ないところもあるかと思いまして五月雨式でしか動けないかなというのが消極的な理由です。

何かルール付けしたほうがいい時期なのかもしれません。

**Comment by arigayas** [comment]
以下の条件でZIPファイルでダウンロードしたソースコードをざっとGrepしてみたら1299ファイルありました・・・。
検索条件： sakura
除外ファイル：*.msi;*.exe;*.obj;*.pdb;*.ilk;*.res;*.pch;*.iobj;*.ipdb
除外フォルダ：.git;.svn;.vs;

一括置換だと置換したらいけない行も置換してしまったりする可能性があるから、
目視で確認しながらじゃないとって考えると容易に心が折れますね・・・。

**Comment by berryzplus** [comment]
やるならやるで進めてもいいと思っています。

grep置換は正規表現を使えるので、置換したいパターンか残したいパターンのいずれかを定義できれば、置換は安全に行えます。

「総意を待っていたらなんも動かない」ってのがぼくの感想です。とりあえず、2人以上が容認ならGOだと思ってます。

**Comment by KENCHjp** [comment]
@berryzplus さん、実行するのはあえて止める気は毛頭ないですが、極論すると、Issue１２９９件とかになっちゃうんじゃないかなとおもうとります。
例えば「sakura.iniをSAKURA Editor.iniにする？しない？」みたいな。考えすぎっすかね。
タイトルバー辺りはいいかもしれません、タイトルバーのWindow名とかで検索してるようなツールあったらとか考えてしまって。

**Comment by KageShiron** [comment]
ドキュメントの修正とかは急ぎではないので、サクラエディタに興味を持ってくれた人の初PR用とかに「簡単な作業」として残しおいてもいいかもしれません。

**Comment by arigayas** [comment]
> 例えば「sakura.iniをSAKURA Editor.iniにする？しない？」みたいな。考えすぎっすかね。
> タイトルバー辺りはいいかもしれませんが、タイトルバーのWindow名とかで検索してるようなツールあったらとか考えてしまって。

ユーザーが触れる事があるファイル名やURLと更新履歴以外が適用範囲かな？と思ってます。

* ファイル名やURL
  互換性のために変更しない方が問題が起こらないと思ったので。
* 更新履歴
  更新履歴の2.3.2.0以前の表記には触れないという事です。

**Comment by berryzplus** [comment]
> ドキュメントの修正とかは急ぎではないので、サクラエディタに興味を持ってくれた人の初PR用とかに「簡単な作業」として残しおいてもいいかもしれません。

一括置換は地味に難易度高いので初心者の方には無理かとｗ
ちなみに git clone したツリーでgrepしたら4,669件ヒットしました。

「やったらええんちゃう？」という気楽なノリなのは、
実際のところ 4,669通りのパターンがあるわけじゃなく、
分類したら十数種類にまとめられるはずだと思っているからです。

違うパターンが混じってるかもしれない300件をチェックするのと、
同じパターンだけ抽出した600件をチェックするの、どちらが気楽か？ということです。

一括置換で正規表現だとするとパターンの妥当性を重点的に見ればよいので、レビューはそんなに大変じゃないとも思っております。

**Comment by berryzplus** [comment]
結論は出てるので閉じてしまいます。

> > SAKURA Editor で統一になったのでしょうか？
> 
> 正式にはそうしましょうって感じで、厳密に一括置換しましょうって運びにはしてません。
