### ISSUE TITLE
GitHubのプロジェクト説明文について

### ISSUE THREAD

**Issue by jakenjarvis** [sakura-editor/sakura#500]
どうでもいいと言われそうな細かいことですが・・・

GitHubのプロジェクト説明文が現在、以下の内容になっています。
> SourceForgeから移行。VS2017ビルド確認済。

が、これは、プロジェクトの説明として不適切だと思います。

いつのころからか、ここに「カテゴリータグ」のようなものも付けられるようになっていますので、それを含めて修正を検討したほうが良いと思います。（英語で書くか、日本語で書くか、両方いれちゃうか、なども）

 - 説明文の言語（日本語、英語、日英両方）
 - カテゴリータグのキーワード（複数）
 - 説明文の文章

※BintrayのDeployをするために、GitHubのBintray連携をしてみたのですが、見事にこの説明文がBintrayに引き継がれて表示されたので、少し気になりました。

**Comment by beru** [comment]
@jakenjarvis さん

報告ありがとうございます。https://github.com/sakura-editor/management-forum/issues/40 を見ると @m-tmatma さんの方で既に修正されたようです。

もし問題が無ければ Close お願いします。

**Comment by m-tmatma** [comment]
> いつのころからか、ここに「カテゴリータグ」のようなものも付けられるようになっていますので、それを含めて修正を検討したほうが良いと思います。（英語で書くか、日本語で書くか、両方いれちゃうか、なども）

説明に関しては対応しましたが、タグに関しては対応してません。

例えば以下で、`static-analysis` とかついています。
https://github.com/facebook/infer

`static-analysis`  をクリックすると、そのタグがついているプロジェクトを列挙できます。
https://github.com/topics/static-analysis

サクラエディタでも何かタグつけてもいいかもしれません。

**Comment by beru** [comment]
タグというか Topics と表記されていますね。

- text-editor
- windows-desktop
- cpp

等はどうでしょうか？

**Comment by m-tmatma** [comment]
ライバル
https://github.com/atom/atom
https://github.com/Microsoft/vscode
https://github.com/vim/vim

ライバルではないけど mac 用のエディタ
https://github.com/coteditor/CotEditor

**Comment by m-tmatma** [comment]
> タグというか Topics と表記されていますね。
> 
>     * text-editor
> 
>     * windows-desktop
> 
>     * cpp
> 
> 
> 等はどうでしょうか？

上記に加えて以下のような感じ?

editor
text-editor
windows
windows-desktop
macro
bregonig
cpp

**Comment by beru** [comment]
良いんじゃないでしょうか。あと `sakura-editor` という Topic も既にあるようなので追加しても良いと思います。

**Comment by m-tmatma** [comment]
足しました。

**Comment by berryzplus** [comment]
> どうでもいいと言われそうな細かいことですが・・・
> 
> GitHubのプロジェクト説明文が現在、以下の内容になっています。
> 
> > SourceForgeから移行。VS2017ビルド確認済。
> 
> が、これは、プロジェクトの説明として不適切だと思います。

どうでもいいというか、***すっげー気になって***ました。
そして更にどうでもいいことですが、キリ番おめでとうございます :smile:

トピックの話 https://github.com/sakura-editor/sakura/issues/500#issuecomment-425720379
```
grep
regex
encoding
```
など追加してはどうでしょう。

encodingは今ちょっと微妙かも知れませんけど、看板機能だと思っています。

サクラエディタの競合は「秀丸」だと思います。
日本語が問題なく扱える、カスタマイズ可能な高機能エディタという分類です。
このカテゴリには、EmEditorとかK2Editorとかが属していると思います。

vscodeやvimと比較すると、色んな意味で勝負にならん気がするわけで :cry:

**Comment by jakenjarvis** [comment]
素早い対応ありがとうございます！
無駄に類似Issue量産してすみません。ただ、500もあったら、そりゃ読み切れませんって（笑）

とりあえず、改善されたのでクローズしますね。
また、修正、追加、削除などが必要に感じたときは、別Issueを立てるということで。

**Comment by KENCHjp** [comment]
>vscodeやvimと比較すると、色んな意味で勝負にならん気がするわけで 😢

すみわけだと思っております。
exe一本でCDに入れて持ち歩ける手軽な物書きツールって位置づけはありかなと。

**Comment by KENCHjp** [comment]
@berryzplus さん

>「それでいいんだっけ？」

たしかに。

ウインドウズ上で動く純OSSテキストエディタ

なかんじのかっちょえーコピーがほしい感じですかね？

**Comment by beru** [comment]
ポリコレ的には `OSDNから移行` が正しいですね。

**Comment by berryzplus** [comment]
> ウインドウズ上で動く純OSSテキストエディタ
> 
> なかんじのかっちょえーコピーがほしい感じですかね？

ここには組織の説明が入るんじゃないかなぁ、と思っています。
かっちょええコピーは `sakura-editor/sakura` のほうですね。
そっちは今のままでもいいかな（笑

**Comment by beru** [comment]
> ポリコレ的には `OSDNから移行` が正しいですね。

これは間違いでした。サクラエディタは sourceforge.net にホスティングされてました。

**Comment by berryzplus** [comment]
没案「サクラエディタv3制作委員会」

突っ込み待ち過ぎてどこから弄ったらいいか分からない感じが面白いかな、とか。

**Comment by KageShiron** [comment]
他のOSSから考えると、「サクラエディタの開発コミュニティ」とか「サクラエディタのメイン開発リポジトリ」的な説明を書くのが一般的っぽいですね

(そういえば、sakuraのMS Windowsという表記も最近はあまり見かけず、Microsoft WindowsかWindows 7以降みたいな書き方が多い気もします)

**Comment by KENCHjp** [comment]
>ここには組織の説明が入るんじゃないかなぁ、と思っています。

ああ、そういうことか。

じゃあ、入れたい素材としては、

どの組織にも属さない有志のサクラエディタ開発コミュニティ

的なかっちょいいコピーっすかね。

**Comment by KENCHjp** [comment]
>制作委員会のネタ感は惜しいですが

映画みたいっすね！

**Comment by m-tmatma** [comment]
> > サクラエディタ開発コミュニティ
> 
> じゃ、これ候補で、もうちょっと眠らせてから、異論なければ採用で。

変更しました。
https://github.com/sakura-editor

**Comment by berryzplus** [comment]
対応ありがとうございます。要望達成したので閉じます。
