### ISSUE TITLE
SonarLint を調べる

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#511]
SonarLint を調べる

https://www.sonarlint.org/visualstudio/

**Comment by berryzplus** [comment]
Visual Studio 2022だと

拡張機能 > 拡張機能の管理

で表示されるダイアログで `SonarLint` を検索してインストールできます。

https://marketplace.visualstudio.com/items?itemName=SonarSource.SonarLintforVisualStudio2022

サクラエディタに関するissueじゃないので閉じてしまいます。
