### ISSUE TITLE
artifacts のサイズ制限にかかってappveyor のビルドに失敗する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#514]
artifacts のサイズ制限にかかってappveyor のビルドに失敗する
`Maximum allowed artifact storage size of 50000 Mb will be exceeded.`

https://github.com/sakura-editor/sakura/pull/512#issuecomment-426099756

> AppVeyor が失敗するので[ログ](https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.930/job/6rku237voom83qjw)を見てみると
> 
> > Maximum allowed artifact storage size of 50000 Mb will be exceeded.
> 
> と最後に出ていました。

**Comment by m-tmatma** [comment]
https://help.appveyor.com/discussions/problems/10253-maximum-allowed-artifact-storage-size-of-1000-mb-will-be-exceeded
とりあえず、上限引き上げてもらえるみたい

**Comment by berryzplus** [comment]
うーむ。

> Ilya Finkelshteyn's Avatar Ilya Finkelshteyn on 27 Aug, 2018 08:58 PM
> Retention policy is now in place. Also default absolute limit is increased. If someone's artifacts collection pace is faster than artifact retention policy, please open a new issue describing your specific situation.

このレスを意訳すると、
‘古い成果物を削除する基準を見直してデフォの容量増やしたお。もし新しい基準よりも速いペースで成果物を作っていて困ったら新しいスレ立てて’

**Comment by berryzplus** [comment]
間違った

**Comment by berryzplus** [comment]
誰かissue立ててこないと対応してもらえない予感。

https://help.appveyor.com/discussions/problems?page

**Comment by m-tmatma** [comment]
急ぎであれば、問い合わせお願いします

**Comment by m-tmatma** [comment]
送りました。
https://github.com/appveyor/ci/issues/2672

**Comment by m-tmatma** [comment]
対応されたみたい。
https://github.com/appveyor/ci/issues/2672#issuecomment-426675946

master をリビルド中です。

**Comment by m-tmatma** [comment]
タイトル修正

**Comment by m-tmatma** [comment]
master のビルド通りました。
閉じます。

**Comment by m-tmatma** [comment]
↑ https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.934 です。

**Comment by m-tmatma** [comment]
再度サイズを拡張するようにお願いしました。
https://github.com/appveyor/ci/issues/2708

**Comment by k-takata** [comment]
20日ちょっとで20GB使い切っていることを考えると、半年なら180GBぐらい必要な計算になってしまいますね。

**Comment by KENCHjp** [comment]
まぁ、今の使い方は、極論すると、保有期間１日でもいいわけで、半年なんていらないんすよね。
CIで容量くってしまうなら、CIテストの時はDry Runするような仕組みがあってもいいかもですね。

**Comment by m-tmatma** [comment]
> artifacts を rotate するように依頼しましょうか？

artifacts の保持期間を短くするように依頼しておきました。
https://github.com/appveyor/ci/issues/2708#issuecomment-433042755

**Comment by KENCHjp** [comment]
>We extended your limit to 100Gb for now to unblock you, looking better solution.

100Gbになっちゃった。。。
今の使い方から言ったら超極論すると保存期間１日でもいいんだよね。。。

**Comment by m-tmatma** [comment]
> 再度サイズを拡張するようにお願いしました。
> [appveyor/ci#2708](https://github.com/appveyor/ci/issues/2708)

https://github.com/sakura-editor/sakura/pull/579#issuecomment-433217158
で通った。

**Comment by k-takata** [comment]
> looking better solution.

何らかの対策はすべきでしょうね。今のペースだとまた1ヶ月後にはいっぱいになるでしょうから。

**Comment by berryzplus** [comment]
アーティファクトの整理します？

当面「allのみ or 個別のみ」にする、とか。

x64版が欲しい人は自分でビルドしてる気配があるので、
x64版のバイナリはリリース目途が立つまで回収しない、とか。

**Comment by ds14050** [comment]
PR で作成されるアーティファクトの第一の目的はリリース代わりではなくデバッグだと思うんです。x64-Debug が一番バグを引き当てやすいかなと思って動作確認では最初に選んでいます。

**Comment by berryzplus** [comment]
ちゃんと見るときはPRブランチごとソースをフェッチしてDebugビルドするのでDebugのアーティファクトは不要と考えていました。x64については現状で試験提供の認識です。絶賛バシラー募集中ですが、自分でなりたいとは思っていません。

成果物を見るだけならwin32-Release派です。
実際に使われるバージョンにこそ対応する意味があると思うので。

**Comment by m-tmatma** [comment]
> 当面「allのみ or 個別のみ」にする、とか。

#587 で個別のみにしました。

**Comment by berryzplus** [comment]
#587 マージによって、生成されるバイナリ量が半分になりました。
従来の倍のペースでPRしない限り、当分は大丈夫ってことですね・・・。

artifactsの保持期間については、根本的に別なあり方を認めてもらったほうがいい気もしています。
こちら側の立場でラクなのは制限を越えたら古いものから削除、ですがそれは難しいのかしら・・・。

**Comment by m-tmatma** [comment]
恒例の時期がやってきました。
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/21088621/job/q5f33l77ws3x8vw4

10/26 ～ 12/19 の 54日間で 30GB 使ったことになる。
#587 でを入れたので、まあ予想通り。

**Comment by m-tmatma** [comment]
再度サイズ制限を拡張してもらえるように依頼しました。
https://github.com/appveyor/ci/issues/2708#issuecomment-448380582

**Comment by m-tmatma** [comment]
> 恒例の時期がやってきました。
> https://ci.appveyor.com/project/sakuraeditor/sakura/builds/21088621/job/q5f33l77ws3x8vw4
> 
> 10/26 ～ 12/19 の 54日間で 30GB 使ったことになる。
> #587 を入れたので、まあ予想通り。

対応してもらった。
リビルドかけた。

**Comment by m-tmatma** [comment]
失敗してた PR はすべてビルド通った。

**Comment by m-tmatma** [comment]
サイズ制限はアカウント単位らしい
https://github.com/appveyor/ci/issues/2789#issuecomment-450126241

**Comment by k-takata** [comment]
zip形式から7z形式に変えればさらに半分くらいに減るかもしれません。
（7zの圧縮は遅いので、ビルド時間は確実に延びますが。）

**Comment by k-takata** [comment]
やっぱりdoxygen要らないのでは？ｗ

**Comment by berryzplus** [comment]
doxygen生成のchmでかすぎ・・・
ソース触る人が地図代わりにできるように吐き出すものなので、
releaseには要らないのかも・・・とか言い出すとまた複雑な実行制御を組み立てる話にｗ
作り方だけ共有して、appveyorでは作らない、というのも選択なのかも知れませんね。

**Comment by ds14050** [comment]
>releaseには要らないのかも・・・とか言い出すとまた複雑な実行制御を組み立てる話にｗ

#626 の 98b0d81ce367481ede80aceed150c3893786dc25 を思い出してくださいね。

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/issues/514#issuecomment-448381050

> 再度サイズ制限を拡張してもらえるように依頼しました。
> [appveyor/ci#2708 (comment)](https://github.com/appveyor/ci/issues/2708#issuecomment-448380582)

[19 Dec 2018](https://github.com/sakura-editor/sakura/issues/514#issuecomment-448381050)
から半年以上たっている。

当時と比べて開発スピードは格段に下がっているが(ビルドされる頻度が下がっているが)、
7 か月発生していないので閉じます。
