### ISSUE TITLE
Universal ctags の最新版を取り込む

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#515]
Universal ctags の最新版を取り込む

サクラエディタのリリース時点での 最新版の Universal ctagsを取り込む
(#450 での残件を別チケットに分離)

最新版は
https://github.com/universal-ctags/ctags-win32
(https://github.com/universal-ctags/ctags-win32/releases)
から入手できます。

**Comment by KageShiron** [comment]
// メモ
リリースビルドはAPIから簡単に取得できます。
https://developer.github.com/v3/repos/releases/

https://github.com/universal-ctags/ctags/issues/1038
> Much more manual page updating are needed for releasing.

とのことなので、正式版リリースにはまだかかるかもしれません。正式版が出るまでは自動更新は先送りで良さそう。

**Comment by m-tmatma** [comment]
また更新してもいいと思う。

**Comment by m-tmatma** [comment]
最新は
https://github.com/universal-ctags/ctags-win32/releases/tag/2020-01-12%2Ffeffe43a

**Comment by m-tmatma** [comment]
#1156 作成しました。

**Comment by berryzplus** [comment]
#1156 マージ済みなので閉じてしまいます。
