### ISSUE TITLE
共通設定のツールバー画面のリスト表示の項目の高さが表示スケール 100% の場合に不十分

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#519]
#513 の変更で、高DPI環境でちょうど良い表示になるように 18 という高さから変更したのですが、表示スケール 100% の場合に不十分な事に気付きました。

| 変更前 | 変更後 |
|--------|---------|
| ![image](https://user-images.githubusercontent.com/1131125/46538764-cacd6f00-c8ef-11e8-8c11-9862b47a43ea.png) | ![image](https://user-images.githubusercontent.com/1131125/46538777-d28d1380-c8ef-11e8-88a9-fd2e1977b779.png) |

アイコン表示する事も考えて高さを決めないといけないですね。

**Comment by berryzplus** [comment]
なんかおかしいですね

**Comment by berryzplus** [comment]
たぶん `calc.GetTextHeight()` がフォントの高さだけを返してるのが原因では？と思いました。

```c
  			int nFontHeight = calc.GetTextHeight();  
- 			nListItemHeight = 18; //Oct. 18, 2000 JEPRO 「ツールバー」タブでの機能アイテムの行間を少し狭くして表示行数を増やした(20→18 これ以上小さくしても効果はないようだ)  
+ 			nListItemHeight = nFontHeight + DpiScaleY(2);  
```

このコード、よく見ると変なコメントが付いてますね

> Oct. 18, 2000 JEPRO
> 「ツールバー」タブでの機能アイテムの行間を少し狭くして表示行数を増やした
> (20→18 これ以上小さくしても効果はないようだ)  

このコメントを鵜呑みにすれば単に `std::max(18, nFontHeight + DpiScaleY(2))` とすれば足りることになりますが、検証しとらんです。

**Comment by beru** [comment]
その方法でもこの不具合は直ると思いますが下記のような方法が、アイコンの高さが変った場合でも確実で良いと思います。

```cpp
std::max(nFontHeight, GetSystemMetrics(SM_CYSMICON)) + DpiScaleY(2)
```

**Comment by berryzplus** [comment]
いったんそれで :smile:
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getsystemmetrics

こっちのバージョンとどう違うのかイマイチ把握できてないですが、
HighDPI対応バージョンのコードと未対応バージョンのコードを同じノリで書けるようにラッパーを用意できたらいいなと考えてます。
https://docs.microsoft.com/en-us/windows/desktop/api/winuser/nf-winuser-getsystemmetricsfordpi

**Comment by beru** [comment]
紹介された URL の解説を読んでみました。

`GetSystemMetrics` は引数による DPI 指定は無いですがプライマリモニタの DPI を使うみたいですね。Single とか System DPI とかいう表記があります。Vista からみたいです。

`GetSystemMetricsForDpi` はユーザー側で任意の DPI 指定が出来る関数で Per-Monitor DPI の時に使うみたいです。Windows 8.1 からみたいです。

ラッパーに関しては日本では吉幾三が元祖ぐらいの事しか知らないのであまりコメント出来ません。

**Comment by beru** [comment]
#520 を Merge したので Close します。
