### ISSUE TITLE
Python のアウトライン解析をデフォルトで使えるようにする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#52]
Python のアウトライン解析は実装されていて、拡張子 py　に対して
アウトラインの解析方法で、Python を設定すると使えるが
デフォルトでは使えないようになっているので、
初期状態でも使えるようにする。

**Comment by m-tmatma** [comment]
InitTypeConfigImp というメソッドで初期化していると思われる。
しかし、CType_CorbaIdl.cpp と CType_Python.cpp と CType_Erlang.cpp では
 InitTypeConfigImp がない。

https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Asm.cpp#L36
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Awk.cpp#L29
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Basis.cpp#L30
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Cobol.cpp#L34
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Cpp.cpp#L52
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Dos.cpp#L29
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Html.cpp#L38
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Ini.cpp#L31
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Java.cpp#L34
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Others.cpp#L28
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Pascal.cpp#L31
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Perl.cpp#L36
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Rich.cpp#L32
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Sql.cpp#L33
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Tex.cpp#L36
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Text.cpp#L42
https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Vb.cpp#L36

**Comment by m-tmatma** [comment]
例えば cpp 用の CType_Cpp は以下の感じ

https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType_Cpp.cpp#L52-L69

**Comment by m-tmatma** [comment]
以下の部分に python 用のキーワードを追加して、実際のキーワード配列も同時に追加する必要がある

https://github.com/sakura-editor/sakura/blob/757d43bbd1dec174de540aabb25c287db874ad81/sakura_core/types/CType.cpp#L111-L143

**Comment by m-tmatma** [comment]
https://www.programiz.com/python-programming/keyword-list

によると以下を実行するとキーワードの一覧を取得できる。

```
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyword
>>> print (keyword.kwlist)
['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']
```

```
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyword
>>> print (keyword.kwlist)
['and', 'as', 'assert', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'exec', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'not', 'or', 'pass', 'print', 'raise', 'return', 'try', 'while', 'with', 'yield']

```

**Comment by berryzplus** [comment]
導入にあたって、反対する理由がないです。
他と同じノリで導入する感じならPRしてもらえれば基本入れる流れで確認するつもりです。

Pythonを動かして有効なキーワードを列挙して・・・なノリだと仕様＆設計からになるので時間がかかりそうです。

ていうか、ユニコード化の続きはどうするんだろう・・・。

**Comment by m-tmatma** [comment]
ロジック自体は実装されているみたいですが、
なぜかいくつかの処理が足りないようです。
