### ISSUE TITLE
メモリ確保失敗時の挙動について調査する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#53]
メモリ確保失敗時の挙動について調査する

**Comment by berryzplus** [comment]
# # 結論
落ちます。

通常、 `new` が失敗すると `std::bad_alloc` が発生します。
サクラエディタは基本的に例外処理をしていないので
キャッチされない例外ハンドラの実装により`std::terminate`されます。(落ちます。)

一部コードで利用されている `new(std::nothrow)` が失敗すると戻り値は NULL になります。
サクラエディタは基本的にNULLチェックをしていないので
確保失敗したメモリを参照した時点で Access Violation が発生してプログラムが落ちます。

## 参考
https://docs.microsoft.com/ja-jp/cpp/cpp/new-operator-cpp?view=vs-2019
https://docs.microsoft.com/ja-jp/cpp/c-runtime-library/reference/set-new-handler?view=vs-2019
