### ISSUE TITLE
size_t → int への不要なキャスト (CProfile::_WriteFile)

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#531]
size_t → int への不要なキャスト (CProfile::_WriteFile)

https://github.com/sakura-editor/sakura/blob/72c87d521f0301a9bda813764355ced7dccdd9bc/sakura_core/CProfile.cpp#L296-L301

nSize  を size_t で定義すればキャストしなくてすむ

あるいは C++11 で可能な foreach の構文を使えばインデックス自体をなくせる
http://nonbiri-tereka.hatenablog.com/entry/2014/06/16/134931

**Comment by berryzplus** [comment]
「不要なキャスト」という言い方をすると、`for (int i = 0; i < (int)nSize; i++)` はイディオムなのでキャストがいらないわけではないと思っています。通常nSizeはsize_tで定義すべきものなのでキャストしないと変な警告出ます。キャストに関しては「必要」だと思います。

ここに関していうと、行データを作って行単位に書き込むのではなく、書込むデータ（「行データ＋改行」×行数）を用意して、ドンと一括で書き込むほうが速いはずです。

たしかこれ、CランタイムでもC++標準でもない独自実装だったと思うので、書込み単位に満たないサイズの書込み命令も書きに行っちゃう作りだったような気がします。

**Comment by m-tmatma** [comment]
もちろん i も size_t にする前提です

**Comment by berryzplus** [comment]
> もちろん i も size_t にする前提です

**必要ですか？**ってのを毎回考えないといかんと思っとります。
前に書きましたがindexは64bit対応にする必然がありません。
`for(int i=0`を変える必然はないってことです。

`for (int i = 0; i < (int)nSize; i++)` の `(int)` はあるべきです。

CProfileが扱うファイルは基本的に小さなファイルなので、
必ずしも2億行をこえる想定は要らないと思ってます。

**Comment by KENCHjp** [comment]
>**必要ですか？**ってのを毎回考えないといかんと思っとります。

ちょっとだけ横から質問です。
不必要な修正は不要ではないかというのが前提にあるかと思いますが、
それ以外に変えないメリットはありますでしょうか？
例えば、消費メモリが少ないとか、CPU利用率が少ないとか。

ようは変える必要があるか、変える必要がないところは変えないのもありますが、
変えてはいけない理由があるところが皆無または限定的かつ明示であれば、
変えなかった理由を「毎回かんがえる」よりはいっそ変えちゃうほうが安定・安全なのではないかなと、今後処理を追加する場合とか。

すいません、中身わかってなくて書いてるので的外れであればスルーしてください。

**Comment by m-tmatma** [comment]
このチケットには x64 のラベルはつけてませんし、64bit 対応という点で言えば、必須ではないです。

元々 size_t のデータを int で扱おうとしているので、キャストが必要になっています。
それを全部 size_t に統一すれば必要なキャストをなくせるという話です。

キャストはどうしても必要な場合にするのがいいという一般的なコーディング上の原則だと思います。

**Comment by berryzplus** [comment]
@KENCHjp さん
> 不必要な修正は不要ではないかというのが前提にあるかと思いますが、
> それ以外に変えないメリットはありますでしょうか？
> 例えば、消費メモリが少ないとか、CPU利用率が少ないとか。

しなくていい修正は要らん、で同意です。

`int`を`size_t`に変えないメリットとして、単純に消費バイト数が少ない、というのをあげられます。
`int`は4バイト、`size_t`は8バイト(x64の場合)です。
型と実行速度の関連については色々ややこしい法則があります。
https://teratail.com/questions/105014

`for (int i = 0; i < (int)nSize; i++)` のパターンには使い方が2つあります。
* 回数を数えるカウンタとして使う(N回繰り返しを実装する場合）
* 配列の添え字にする（N番目の要素に処理を行う場合）

カウンタとして使う `i` の型は自由に変えちゃっていいと思ってます。
配列の添え字として使う `i` の型を `size_t` にするのは疑問ありです。

配列の添え字を `size_t` にするということは、
`int` では表現できないサイズに対応させる、ということです。
`int` で表現できるサイズとは 31bit 整数値、2億です。
`size_t` に変えるとすると 32bitで4Giga(4億)まで扱えるようになります。
`size_t` に変えるとすると 64bitで172億Gigaまで扱えるようになります。

ただし、添え字が本当に「配列の添え字」であるならsize_tに変える意味はありません。
32bitで `new char[4Giga]` は必ず失敗します。
64bitで `new char[172億Giga]` は必ず失敗します。

意味がある場合も確かにあります。
単純置換に反対なのは現状のコードは`size_t`にしてもほぼ意味がないためです。

**Comment by beru** [comment]
ここは `size_t` にした方がコードが自然になると思います。

実行速度の話であれば、ループカウンタの型にこだわる前にまずは `CTextOutputStream::WriteString` の実装を改善するべきだと思います。

話題は変わりますが書き込みエラーとかをチェックしていないのが気になります。。

**Comment by berryzplus** [comment]
> 実行速度の話であれば、ループカウンタの型にこだわる前にまずは CTextOutputStream::WriteString の実装を改善するべきだと思います。

そうですね。
その通りだと思います。

> ここは size_t にした方がコードが自然になると思います。

vectorを配列のようにアクセスしようとするから話がおかしくなってるだけな気が。

```c++
for (auto line : vecLine) {
    // 出力  
    out.WriteString(line.c_str());  
    out.WriteString(L"\n");  
}
```
とすれば配列添え字の型は登場せず、キャストの問題もなくなるような。

**Comment by KENCHjp** [comment]
>32bitで new char[4Giga] は必ず失敗します。
>64bitで new char[172億Giga] は必ず失敗します。

おお、なんとなく理解できました。
数字であればよい箇所の実装が何種類もあるのは混乱を招くのではないかとの懸念だったのですが、
数字であればいい箇所と、intでなければならない箇所は違うということですね。

**Comment by m-tmatma** [comment]
> `int`を`size_t`に変えないメリットとして、単純に消費バイト数が少ない、というのをあげられます。

そこの部分は違うと思います。

CProfile.obj でバイナリサイズを比較しました。

size_t に変えたコード : 414,106 バイト
現状のコード              : 414,111 バイト

64bit のデータを 32bit に変換することにより、余計な処理が入ってデータサイズは逆に増えています。

メモリに大量のデータを置くなどした場合は、確かに 32bit の方がメモリを節約できると思いますが、
レジスタで処理できるものに関してはサイズは増えないと思います。

**Comment by m-tmatma** [comment]
> とすれば配列添え字の型は登場せず、キャストの問題もなくなるような。

はい。説明欄に末尾に一応ちょこっと書いてます。

**Comment by m-tmatma** [comment]
> 配列の添え字を `size_t` にするということは、
> `int` では表現できないサイズに対応させる、ということです

それは違うと思います。単純に型を合わせるだけです。

**Comment by berryzplus** [comment]
> 単純に型を合わせるだけです。

分からなくなりました。

配列の添え字型を `size_t` にしたい、というのは
型を unsigned に揃えたい、というだけですか？もしかして。

**Comment by m-tmatma** [comment]
> 配列の添え字型を `size_t` にしたい、というのは
> 型を unsigned に揃えたい、というだけですか？もしかして。

ではないです。
`vecLine.size()` の型が、`size_t` なのでループ変数も `size_t` にするという意味です。
仮に `vecLine.size()` の型が `int` なら `int` でいいです。

**Comment by berryzplus** [comment]
なんとなく言ってる意味がわかりました。
`vecLine.size()`の値域とは関係なく、純粋に型を合わせるべき、と言ってるわけですね。
本当に純粋に、キャストしないで済むように定義をかえるだけと。

ならば問題ないかな、と思いました。

**Comment by beru** [comment]
> > ここは size_t にした方がコードが自然になると思います。
> 
> vectorを配列のようにアクセスしようとするから話がおかしくなってるだけな気が。
> 
> ```c++
> for (auto line : vecLine) {
>     // 出力  
>     out.WriteString(line.c_str());  
>     out.WriteString(L"\n");  
> }
> ```
> 
> とすれば配列添え字の型は登場せず、キャストの問題もなくなるような。

`std::vector` 使っているのに Array subscript operator で配列っぽくアクセスする書き方がおかしいと言われるのも酷だと思います。そういう記述を狩っているとしまいには

- プリミティブ型の使用禁止
- 例外安全の保障
- 僅かでも時間が掛かる処理は非同期記述に
- template metaprogramming記述の推奨

等と要件が増えて行って Better C 的なぬるま湯な世界に留まれなくなるので static おじさんとしては肩身が狭いです。

**Comment by m-tmatma** [comment]
閉じます
