### ISSUE TITLE
プルリクエストの設定変更

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#54]
プルリクエストの設定変更しませんか?
https://dev.classmethod.jp/tool/github/protect-branch/

以下のオプションを有効にするのがいいと思います。

- "Require pull request reviews before merging"
- "Dismiss stale pull request approvals when new commits are pushed"
- "Require status checks to pass before merging"

コードレビューに関してこんな機能があるようです。
https://blog.github.com/2016-12-07-introducing-review-requests/

**Comment by kobake** [comment]
良いと思います。

ただ、今は割とアクティブに皆が動いているので良いですが、時期によってはコアメンバーの応答が少なくなることもある可能性があります。そのときには適宜設定をオフにしなおして自己マージするみたいな感じの運用でカバーも自分は許容するスタンスです。

自分以外の人が Branch の Protect 設定いじれるかどうかの確認もしておきたいので @m-tmatma さんもしくは他のどなたかで Protect 設定いじってみてもらって良いでしょうか。いじる内容は挙げていただいた3点で良いと思います。

**Comment by kobake** [comment]
ご対応ありがとうございます。

以下は #57 ですが、うまく動いているように見えます。

<img width="595" alt="block" src="https://user-images.githubusercontent.com/2929454/40953785-3ab652a8-68bc-11e8-94fa-89fb0fe4d87e.png">

誰かが approve すれば Merge できるようになるはずで、それが確認できたらこの Issue もクローズしましょう。

**Comment by m-tmatma** [comment]
> 変えてみました。

ありがとうございます。

> 以下は #57 ですが、うまく動いているように見えます。
> 誰かが approve すれば Merge できるようになるはずで、それが確認できたらこの Issue もクローズしましょう。

マージしました。

> 自分以外の人が Branch の Protect 設定いじれるかどうかの確認もしておきたいので @m-tmatma さんもしくは他のどなたかで Protect 設定いじってみてもらって良いでしょうか。

私のアカウントでは設定はできないできないようです。

**Comment by kobake** [comment]
> > 自分以外の人が Branch の Protect 設定いじれるかどうかの確認もしておきたいので @m-tmatma さんもしくは他のどなたかで Protect 設定いじってみてもらって良いでしょうか。

> 私のアカウントでは設定はできないできないようです。

なるほど。。ご確認ありがとうございます。
@KENCHjp さんが設定できたのはたぶん Organization Owner だからですね。
狙ったわけではないですが、Member と Owner の挙動の違いも確認できて良かったです。

プロジェクト設定は頻繁にいじるものではないので、今のところはこの体制で大丈夫かと思っています。

## sakura-editor.github.io リポジトリのほうの対応
sakura-editor.github.io についても以下2点の Protectd branch 設定入れておきました。

- Require pull request reviews before merging
- Dismiss stale pull request approvals when new commits are pushed

CI は組み込んでないので、Require status checks to pass before merging の設定はオフのままにしてあります。

**Comment by KENCHjp** [comment]
実施エビデンス
修正前
![githubbefore](https://user-images.githubusercontent.com/39618965/41144038-724b12cc-6b36-11e8-870e-312162572d10.PNG)

修正後
![githubafter](https://user-images.githubusercontent.com/39618965/41144043-76523d8c-6b36-11e8-9d48-f064704e0539.PNG)

**Comment by kobake** [comment]
共有ありがとうございます！
