### ISSUE TITLE
appveyorビルドがpythonのエラーで失敗してしまう

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#541]
ここのじゃなくてcloneリポジトリの話なんですが表題の現象が起きています。

https://ci.appveyor.com/project/berryzplus/sakura/builds/19402136/job/cq706ehci9p0fyy9

コミットID: 8d6fc7e9892a5cc4770da7bce9f144709b469d0f (ここの現masterと同じ値)
単にcloneしてるだけのブランチなので不思議です。

この状態だと新しいPullRequestを作成できないので
なる早で原因究明して対処したいです。
（ @m-tmatma さんにお願いするしかないんですが :smile: ）

ありえる「原因」として以下３つを想定しています。
1. sakura-editor/sakura の appveyor 設定が変わった。
2. checkEncodingに何らかの不具合がある。
3. appveyor のVM環境に不具合がある。

issue立てるのは発生事象の共有が目的です。
原因が3.でない限り、現状だれもPRを作れないはずなので。

**Comment by m-tmatma** [comment]
ローカルでも再現しますね。

```
C:\gitwork\temp>git clone -q --branch=feature/appveyor_test https://github.com/berryzplus/sakura.git sakura2

C:\gitwork\temp>cd sakura2

C:\gitwork\temp\sakura2>checkEncoding.bat
skip installing chardet
---- start python checkEncoding.py ----
adding C:\Users\mtmat\AppData\Roaming\Python\Scripts to PATH
fatal: bad sha1 reference origin/master
Traceback (most recent call last):
  File "checkEncoding.py", line 107, in <module>
    count = processFiles(getDiffFiles())
  File "checkEncoding.py", line 88, in processFiles
    for file in files:
  File "checkEncoding.py", line 54, in getDiffFiles
    mergeBase = getMergeBase()
  File "checkEncoding.py", line 47, in getMergeBase
    output = subprocess.check_output('git show-branch --merge-base origin/master HEAD')
  File "C:\Python27\lib\subprocess.py", line 223, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command 'git show-branch --merge-base origin/master HEAD' returned non-zero exit status 128
error checkEncoding.py

C:\gitwork\temp\sakura2>git remote -v
origin  https://github.com/berryzplus/sakura.git (fetch)
origin  https://github.com/berryzplus/sakura.git (push)
```

sakura editor のアカウントのビルドでは
https://ci.appveyor.com/project/sakuraeditor/sakura/build/job/tjsa7wn2ow4s82v5

以下のようなコマンドが実行されています。

```
git clone -q https://github.com/sakura-editor/sakura.git C:\projects\sakura
git fetch -q origin +refs/pull/540/merge:
git checkout -qf FETCH_HEAD
call checkEncoding.bat
```

問題のビルドでは以下のエラーが出ていて、sakura editor のアカウントのビルドでは出てない。

`fatal: bad sha1 reference origin/master`

結論的には、checkEncoding.py で対応できないケースがある感じです。
ただ、通常の PR 自体は問題なさそう。

ブランチ指定で clone しているから `origin/master` が参照できなくて失敗しているように見えます。

この `feature/appveyor_test` はどのように作ったのですか?

**Comment by m-tmatma** [comment]
sakura editor のアカウントでの PR のビルド自体も成功している。
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/19400358

**Comment by m-tmatma** [comment]
checkEncoding.py は特に変更せずに さっき私のアカウントで #524 のブランチを
master に対して、 rebase してビルドしたもの。
https://ci.appveyor.com/project/m-tmatma/sakura/builds/19415712/job/bh3kgxtniiex7j0a

→ 問題なくビルドできている。

**Comment by m-tmatma** [comment]
一応、 #542 で `origin/master` が存在しない場合に処理をスキップするようにしました。

**Comment by berryzplus** [comment]
調査ありがとうございます。

ぼくがmasterブランチを削ってるのが原因だった感じですかね。

普通に出勤日なのでレビューは夕方になると思います。対策見つかって良かったです。

**Comment by berryzplus** [comment]
上げてもらったPRの対応で問題が解消することを確認できました。
ありがとうございます。
このissueも目的を果たしたので閉じます。
