### ISSUE TITLE
アウトライン解析の「更新」のアイコンが「Windows」マークなのは直感的じゃないので変えて欲しい

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#543]
![image](https://user-images.githubusercontent.com/11251874/46842446-920a2a00-ce08-11e8-9120-6180e6d19612.png)
_#539 で「アウトライン解析」のウィンドウをドッキング出来ることを知ったのですが_

ドッキング時に「アウトライン解析」の「更新」のアイコンとして
「Windows」(Win3．1かWin95のロゴ？)マークが表示されるのですが
このアイコンでは直感的じゃないので
Webブラウザのような更新マークにするのが良いと思います。

- ![image](https://user-images.githubusercontent.com/11251874/46842770-7e5fc300-ce0a-11e8-989c-62a39e29589d.png) ← Firefox 60.2.2esrの更新アイコン
- ![image](https://user-images.githubusercontent.com/11251874/46842783-99cace00-ce0a-11e8-847f-d599970afdca.png) ← Internet Explorer 11 の更新アイコン
- ![image](https://user-images.githubusercontent.com/11251874/46842803-aea76180-ce0a-11e8-9c89-72f5e44ed062.png) ← Microsoft EdgeHTML 17.17134の更新アイコン

**Comment by m-tmatma** [comment]
新しくアイコン作るなら SVG で作りたい。
SVG ならいろんな解像度のアイコンに変換できる。

**Comment by berryzplus** [comment]
いいと思います。

ここの更新アイコンに限定した話、エクスプローラーのアイコンを流用するのがux的にベターだと思いますけど。

**Comment by arigayas** [comment]
![image](https://user-images.githubusercontent.com/11251874/46993328-98224280-d149-11e8-9a78-17d05abc77d6.png)

アイコンを作成しないで使うとしたら赤枠で囲ったアイコンでしょうか？

**Comment by berryzplus** [comment]
違うような気がしますが、それも選択肢です。

Windowsで提供されてるものはなるたけ使いまわしたい考えです。

**Comment by arigayas** [comment]
webフォントを使えたら良い感じのがあるんですけどねぇ
https://fontawesome.com/icons?d=gallery&q=reload
![image](https://user-images.githubusercontent.com/11251874/47018072-de4dc500-d18e-11e8-9278-44b8c8977f05.png)

**Comment by berryzplus** [comment]
使おうと思ってたアイコンが見つからなくてシュン・・・としてたんですが、
既存コードが描画しているアイコンを探して、衝撃の事実に辿り着きました。

更新ボタンに使われているウインドウズアイコンに見えるものの正体はこれです。
![2018-10-16 2](https://user-images.githubusercontent.com/3253151/47026415-57a1e380-d1a0-11e8-8b6e-032735cece2e.png)

文字を描画することでボタンを表現し、
実際のボタン処理は自前で実装する、
という荒業が使われとります。

これにより、リソース使用量を数MB単位で節約できるはず・・・ローテクだけど絶技 :sob:

ちなみに×ボタンと▼ボタンはこっちのフォントになるようです。
赤いのが使ってるやつ。緑のやつはなんか気になったやつ・・・。

![2018-10-16 1](https://user-images.githubusercontent.com/3253151/47026649-ea428280-d1a0-11e8-8e4c-aaf2380515e4.png)

ついでで更新ボタンっぽい文字も見つけたので貼ってみます。
（いや、むしろこれが本題なんですがｗ）
![2018-10-17](https://user-images.githubusercontent.com/3253151/47027188-f11dc500-d1a1-11e8-968c-6489f7026c4c.png)


実際のソースコードはこんな感じになっていて、
仮に `Webdings` を使って書き換える場合には改修は瞬殺で終わる気配です :sob:

https://github.com/sakura-editor/sakura/blob/2792c08740a003ef44fc1206884c3b2e476acffb/sakura_core/outline/CDlgFuncList.cpp#L3302-L3309

Webフォントも捨てがたいんですよねぇ・・・。

**Comment by arigayas** [comment]
_いつかやるかもしれないサクラエディタで使っているアイコンの総入れ替えを検討するまでは_
とりあえずこの「0x71」にするので良いと思いますw

**Comment by beru** [comment]
DirectWrite を使って Unicode の絵文字の 🍥 を描画する事を考えていました…。

**Comment by ds14050** [comment]
>DirectWrite を使って Unicode の絵文字の 🍥 を描画する事を考えていました…。

それは編集領域を最初にやってください。待ってる人がいっぱいいます。縦方向のアンチエイリアスも、カラー絵文字も。

でも Mac の Mojave は色にじみの出るアンチエイリアスをやめたらしいですね。アウトラインからビットマップへの切り替えなどと同じく、低解像度ディスプレイ向けの妥協技術であったと。

**Comment by arigayas** [comment]
Merged　になったからCloseしても良いのでしょうか？

**Comment by KENCHjp** [comment]
思う存分Closeお願いします！

**Comment by arigayas** [comment]
Merged　になったから Close します。
