### ISSUE TITLE
開く(ドロップダウンメニュー)に「履歴の管理」を追加して欲しい

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#550]
![default](https://user-images.githubusercontent.com/11251874/46915734-89714980-cfea-11e8-86c9-96b55bdc63c0.png)
「最近使ったフォルダ」の上か下に「設定(O)」→「履歴の管理」で表示される「履歴の管理」を追加して欲しいです。
![image](https://user-images.githubusercontent.com/11251874/46915788-89be1480-cfeb-11e8-8316-b5625fbabb4e.png)

「設定(O)」→「履歴の管理」という位置にあるため、
この機能を知るのに2chで履歴の消し方の質問を見るまで数年は知りませんでした。

**Comment by berryzplus** [comment]
ここのメニュー、設定で弄れなかったんですね。
そういえばなんか特殊な実装になってた気がします。

・・・出来たんでPR出しときます :sob:

**Comment by arigayas** [comment]
ありがとうございます！！

**Comment by arigayas** [comment]
Mergeされたから閉じますね。
