### ISSUE TITLE
`ファイルの場所をコマンドプロンプトで開く`、および、`ファイルの場所をPowerShellで開く` を検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#556]
`Notepad++ 7.5.8`　ではタブメニューに`ファイルの場所をコマンドプロンプトで開く`という項目がある。
#420　に加えて追加を検討する。

https://github.com/sakura-editor/sakura/issues/420#issuecomment-419648537

**Comment by ds14050** [comment]
「Command Prompt Here」として知られていた機能で、Windows Vista では「コマンド ウィンドウをここで開く」として標準搭載されました。調べると Windows 95 の PowerToys までさかのぼれるようです。最近は Shift の同時押しが必要だったり、PowerShell に置き換えられたりしているのでしょうか。自分もよく使う機能ですし、開発者(想定ユーザー？)向けでいいと思います。メニューアイテムとして存在してさえいれば、自分で右クリックメニューなど他の場所に追加することもできますし。

**Comment by berryzplus** [comment]
…(￣ー￣)ふぉ。

フォルダを開く実装のshellexecuteのパラメータをちょっと変えれば実現できそうでした。

**Comment by m-tmatma** [comment]
@berryzplus さん

#549 を対応されたのでこちらも対応お願いできますか?

**Comment by m-tmatma** [comment]
#603 を作成しちゃいました。

@berryzplus さん
着手してたらごめんなさい。

**Comment by jakenjarvis** [comment]
個人的な希望です。
「コマンドプロンプトを出したいケース」と、「PowerShellを出したいケース」があります。

そこで提案ですが、それぞれ２つのメニューを追加するというのはどうでしょうか？
また、PowerShellがインストールされていない場合は、PowerShell側のメニュー自体を消して、コマンドプロンプトのメニューだけにしてしまってもよいかもしれません。
（どこでPowerShellのインストール状況を判断するのか調査が必要ですが・・・）

**Comment by berryzplus** [comment]
> どこでPowerShellのインストール状況を判断するのか調査が必要

windows7 以降は標準搭載らしいです。
https://ja.wikipedia.org/wiki/PowerShell

**Comment by arigayas** [comment]
PowerShell、使わないから削除したことはあります。
私のような人がいると思うのでちゃんとチェックは必要だと思います。


コントロール パネル\すべてのコントロール パネル項目\プログラムと機能
![image](https://user-images.githubusercontent.com/11251874/48298974-77ab9500-e509-11e8-9482-36a281023645.png)

**Comment by berryzplus** [comment]
> PowerShell、使わないから削除したことはあります。
> 私のような人がいると思うのでちゃんとチェックは必要だと思います。

了解です。

コマンドの活性制御をする関数があるので、powershellのコマンドだけ独自にインタープリタが存在するかチェックさせればよさそうです。

**Comment by k-takata** [comment]
PowerShellがインストールされている環境では、powershell.exeにPATHが通っている気がします。

**Comment by m-tmatma** [comment]
それなら `where powershell.exe` で存在確認したらいいですね。

**Comment by k-takata** [comment]
SearchPathでしょうか。
https://msdn.microsoft.com/ja-jp/library/cc429699.aspx

**Comment by m-tmatma** [comment]
> SearchPathでしょうか。
> https://msdn.microsoft.com/ja-jp/library/cc429699.aspx

いけました。
ret が 0 かどうかチェックすればいけます。

```
TCHAR szFileBuff[MAX_PATH];
LPTSTR lpFilePart = NULL;

DWORD ret = SearchPath(
	NULL,      // 検索パス
	_T("powershell.exe"),  // ファイル名
	NULL, // ファイルの拡張子
	MAX_PATH, // バッファのサイズ
	szFileBuff,     // 見つかったファイル名を格納するバッファ
	&lpFilePart   // ファイルコンポーネント
);

```

**Comment by m-tmatma** [comment]
#603 待ち

**Comment by m-tmatma** [comment]
> 個人的な希望です。
> 「コマンドプロンプトを出したいケース」と、「PowerShellを出したいケース」があります。

#623 で powershell で開く機能を実装しました。

> PowerShell、使わないから削除したことはあります。
> 私のような人がいると思うのでちゃんとチェックは必要だと思います。

powershell  が見つからない場合には、メニュー項目をグレーアウトします。

**Comment by m-tmatma** [comment]
対応完了
#567 #607 が残件
