### ISSUE TITLE
HeaderMakeのメッセージ出力も英語化する？

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#56]
ログ全体をチェックしていて気付きました。
HeaderMakeのメッセージ出力も化けています。
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.84#L458

自動生成ファイルをリポジトリから外す対応により上書きが発生しなくなったため、
初回メッセージは消えていました。
* #31 HeaderMake が生成するファイル (Funccode_define.h, Funccode_enum.h) をリポジトリから除外 86d411f

MakefileMakeについてはCMakeによる代替の可能性が出てきている認識です。
HeaderMakeについても代替案があるかも知れません。

* enumとdefineの定義を共用できるようにdefineマクロで工夫する、みたいなのをWebで見かけたことがあります。

MakefileMake同様に対応する( https://github.com/sakura-editor/sakura/pull/44 )か、
あえてこのままとするか判断が必要と思います。

**Comment by kobake** [comment]
以下PRで英語対応しました。

- HeaderMake出力メッセージの英語化 #57

> HeaderMakeについても代替案があるかも知れません。

あるような気がします……。要検討。
ちなみにこのHeaderMakeってもともと自分が作ってたんですねぇ……。ソースコード先頭に自分の名前があるのを見て思い出しました（うろ覚え）。

**Comment by berryzplus** [comment]
英語化対応と #57 のマージを確認したので閉じます。
https://ci.appveyor.com/project/sakuraeditor/sakura/build/1.0.86
