### ISSUE TITLE
通常のソリューションのコンパイル前に tests\build-and-test.bat でビルドするとコンパイルエラーになる

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#561]
通常のソリューションのコンパイル前に tests\build-and-test.bat でビルドするとコンパイルエラーになる

```
sakura_core\func\ckeybind.h(19): fatal error C1083: include ファイルを開けません。'Funccode_enum.h':No such file or directory 
[tests\build\Win32\unittests\tests1.vcxproj]
```

手順
1. #560 を適用しておく
2. `git clean -xfd` でクリーン環境にする
3. `tests\build-and-test.bat Win32 Release` を実行する

3 の前に  `build-sln.bat Win32 Release` を実行するとビルドは通る

**Comment by m-tmatma** [comment]
cmake 用のブランチ (#378) に入れている HeaderMake によるヘッダの生成処理が
master には入っていないから発生する。

**Comment by ds14050** [comment]
バグというラベルが付いていますが、テストはテスト単体でビルドしたいということでしょうか。通常のソリューションのプロジェクトのひとつとしてテストのビルドを組み込んでしまうと、いいことがあります。あるいは CMake でエディタとテストのビルドを統合するのでも同じです。

----

このファイルを見てください。

https://github.com/sakura-editor/sakura/blob/ad7db01a8ffd0375fc5194dc9c40145ce51ea2ec/tests/unittests/code-util_string_ex.cpp#L27

テストファイルはすべてひっくるめてコンパイルされてリンクされます。引用したコメントの内容を注意深く守ることもそうですが、テストを書く度にこのようなファイルが必要とされることに無理があります。

考えてください。テストを追加したらテスト対象が被っていて競合しました。競合を解消すると、他のテストに依存する不完全なテストになります。そうしてこうしてテストが増えるにつれ、抜き差しならない依存関係の団子ができあがっていきます。

ソリューションの一部として、同じコンパイラとコンパイルオプションでサクラのソースとテストのソース(それと googletest)が順番にコンパイルできると、コンパイル済みの .obj ファイルが流用できます。切り取ったソースコードではなく、コンパイルされた、エディタとなるオブジェクトコードがテストできます。

----

テストをビルドする一環としてサクラの全ソースコードを再コンパイルしてテストコードにリンクした例です。

https://ci.appveyor.com/project/ds14050/sakura-clone/builds/19636777/job/qbocbbogw862cgiq

うっかりして間違ったテストを書いたので赤背景でログが止まっていますが、テストの実行は済んでいます。コミットID(6d27a775)をクリックしてもらうと CMakeLists.txt に加えた変更と、tests/unittests/code-util_string_ex.cpp なしでテストが実行されていたことがわかります。

「[We do not recommend using GLOB to collect a list of source files from your source tree](https://cmake.org/cmake/help/v3.0/command/file.html#command:file)」と CMake のドキュメントに書かれていることそのままの乱暴なやり方ですし、同じソースファイルを２度コンパイルしているのがとんでもない無駄です。Job がテストを実行して失敗するまでにかかった時間を見てください。

----

コンパイル済みの .obj ファイルを流用した例です。

https://ci.appveyor.com/project/ds14050/sakura-clone/builds/19643655

プロジェクトファイルの設定を手作業で CMakeLists.txt に反映しているのが問題ですが、向かう先が行き止まりではないことは実証できたと思います。

----

エディタとテストはほとんどのソースコードを共有できます。主な違いはエントリポイントが WinMain かテストランナーかです。

エディタのビルドが先でもテストのビルドが先でも構いませんが、後の方のビルドが先のビルドの結果を利用できると無駄がありません。そういう方向を目指してエディタの(ソースではない)コードをテストにリンクしましょう。テストを書くのが簡単になります。

----

この Issue との関わりですが、CMake 統合がまだ先である現状では、テストはエディタのビルドに依存したいということです。エディタ→テストの順でビルドして、エディタのオブジェクトコードをテストにリンクしたいということです。なので解決すべきバグではないと思っています。

**Comment by ds14050** [comment]
Microsoft のドキュメントです。

「[通常、独自のプロジェクト内のコードもテストするコードと同じソリューションでテストします。 新しいテスト プロジェクトをセットアップして構成するには、C/C++ 用の単体テストの作成に関するページを参照してください。](https://docs.microsoft.com/ja-jp/visualstudio/test/how-to-use-microsoft-test-framework-for-cpp?view=vs-2017)」

「[テスト コードがテスト対象プロジェクト内の関数にアクセスできるようにするには、テスト プロジェクト内のプロジェクトへの参照を追加します。 ソリューション エクスプローラーでプロジェクト ノードを右クリックして、[追加] > [参照] を選びます。](https://docs.microsoft.com/ja-jp/visualstudio/test/writing-unit-tests-for-c-cpp?view=vs-2017)」

**参照を追加します** **参照を追加します** **参照を追加します** **参照を追加します**

参照……どこ……？

**Comment by ds14050** [comment]
>**通常のソリューションのコンパイル前に** tests\build-and-test.bat でビルドすると

という部分を読み違えていたかもしれません。

通常のソリューションをコンパイルせずに、テストのビルドを成功させたいという意図があるのだと自分は考えていました。

そうではなく、テストに関係する依存関係が正しく設定されていないから tests\build-and-test.bat を起点にしたビルドが失敗するので直そう、というのがこの Issue の目的だった可能性に気がつきました。

だったら失礼しました。それは解決すべき問題ですし、なんならエディタへの依存も設定してほしいというのが自分の立場です。

**Comment by m-tmatma** [comment]
テスト用の cmake プロジェクトでは、説明欄に記載の `Funccode_enum.h` 等の生成ルールがありません。
通常のソリューションをビルドしたら、 `Funccode_enum.h` 等のファイルは生成されますが、
テスト用の cmake プロジェクトをビルド、実行するのに sakura エディタ本体のビルドは必要ないはずのものです。

clone したてのときに、テスト用のプロジェクトをビルドしたいだけなのに sakura エディタ本体を
ビルドしなくてもいいようにするのが目的です。

**Comment by berryzplus** [comment]
相変わらず、メインで使ってるマシン(win8.1+IE11)からレビューコメントへの返信ができんです・・・。

ちょっと気になりました。

> clone したてのときに、テスト用のプロジェクトをビルドしたいだけなのに sakura エディタ本体を
 ビルドしなくてもいいようにするのが目的です。

テスト用のプロジェクトをビルドすると、sakuraエディタ本体もビルドされる、でいいですよね？
現状は、テスト用をビルドする前に、本体のビルドを叩く必要があるのを、
テスト用だけビルドすればうまいことやってくれるようにしたい、ですよね？
（うまいことやる＝sakura本体をビルドする）

目指したい将来のカタチは @ds14050 さんが書かれているふうです。
テスト対象コード(=.obj)は「できれば」本物を使いたいです。
（スタブを使わないとテストできないロジックもありえますのですべてがすべて「本物を使う」にはならないとも思っています。）
