### ISSUE TITLE
「バージョン情報」のURL部分にマウスカーソルを持っていったときの背景色が長い

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#563]
「バージョン情報」のURL部分にマウスカーソルを合わせた時に
「背景色」と「クリックが可能な領域」が長いのが気になりました。

![image](https://user-images.githubusercontent.com/11251874/47217042-02edab00-d3e2-11e8-8c92-9ad9a9856874.png)

ソースコードをGitHubからzipでダウンロードして数時間前にビルドしてみました。

**Comment by arigayas** [comment]
![image](https://user-images.githubusercontent.com/11251874/47217334-0170b280-d3e3-11e8-862a-d2f12bef181b.png)
もしかすると「背景色」と「クリックが可能な領域」は最新のリリースバージョンのままなのかな？

**Comment by berryzplus** [comment]
バージョンダイアログのリンク `CUrlWnd` は先人による自作実装です。
以前は「こんなもん自作するとかありえね～」と思ってました。 -> [Sys Link](https://docs.microsoft.com/en-us/windows/desktop/controls/syslink-overview)
現在は「『味』として残してもいいかな～」と思ってます。

事象の原因はいくつかあります。

1. ダイアログリソース作成時に、コントロールサイズを設計してない
2. 初期表示時に、描画するリンクテキストにサイズを合わせていない
3. テキスト描画時に、背景色透過を指定している
4. 背景描画時に、テキスト表示域と関係なく、領域全体を塗り潰している

対策を打つとしたら 2. の部分だと思います。
他の原因は常識的な設計だと思います。

不足している処理を足せば、現象は消えます。
修正量は多くないので、あとで修正パッチを書いてみます。

**Comment by arigayas** [comment]
修正が比較的簡単なようで良かったです。

**Comment by berryzplus** [comment]
いや、簡単では・・・ｗ

**Comment by arigayas** [comment]
失礼いたしました(汗)

**Comment by beru** [comment]
#566 で解消されたので Close します。

**Comment by arigayas** [comment]
修正お疲れさまでした。

![image](https://user-images.githubusercontent.com/11251874/49111765-679b0000-f2d4-11e8-8069-91c713d8f1ab.png)
