### ISSUE TITLE
機能追加したときの既存 sakura.ini の扱いに関して

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#567]
#549 の 「ファイルの場所をエクスプローラーで開く」が対応されたが、
既存の sakura.ini を使う場合にはこの機能は有効にならない。

せっかく機能を実装しても、以前のバージョンから使っているユーザーは
自分で設定しないと追加した機能が使えない。

既存ユーザーが何もしなくても新機能を使えるようにするか、
あるいは使い方のドキュメントを整備するのを検討する。

**Comment by KENCHjp** [comment]
こういう新規追加機能って、iniファイルのバージョンが古かったら、有効にしてもいいんじゃないかとちと思います。
不要な人はオフにすればいいわけで。

**Comment by m-tmatma** [comment]
タイトル変更しました。

**Comment by berryzplus** [comment]
既に話が終わっているように見えるので閉じてしまいます。

新規ini項目を作ったときの初期値をどうするか？
　⇒　新規ini項目を作る人が決めてよい。
　　　デフォルトがオンになるように構成したとしても、オフにしたらいいだけなので気にしない。

というか、追加する機能によりどうしたらよいかは違うと思うので、仕様説明に書いてもらうのがよいと思います。
