### ISSUE TITLE
APPVEYOR_PULL_REQUEST_NUMBER_LABEL ではなく APPVEYOR_PR_NUMBER_LABEL の名前にした経緯を markdown に残す

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#577]
#569  で APPVEYOR_PULL_REQUEST_NUMBER_LABEL ではなく APPVEYOR_PR_NUMBER_LABEL の名前
にした経緯を appveyor.md の markdown に残す

https://github.com/sakura-editor/sakura/pull/569#discussion_r226846528

> 違った。これはシンボル名が長すぎる懸念があって、使ってなさそうなので削ってみたものです。
> [362d060](https://github.com/sakura-editor/sakura/commit/362d06008c7b6942630e6cc1647a00b0e4e77413)
> 
> こういうエラーが出てました。
> 
> ```
> identifier truncated to 'APPVEYOR_PULL_REQUEST_NUMBER_LA'
> ```
> 
> `APPVEYOR_PULL_REQUEST_NUMBER_LA` に切り詰められた、ということは、
> サフィックス `_LABEL` が `_LA` になったということなので、
> サフィックス `_INT` も危ないのかな、という発想です。

https://github.com/sakura-editor/sakura/pull/569#discussion_r226851156

> なぜ `APPVEYOR_PULL_REQUEST_NUMBER_LABEL` ではなく
> `APPVEYOR_PR_NUMBER_LABEL` という名前にしているのかの
> 経緯を markdown に残しておいた方がいいと思います。

**Comment by m-tmatma** [comment]
4cc8280b1c432e323ce22cc74b13374e6df19941 のコミットログ参照

**Comment by berryzplus** [comment]
issue立てありがとうございます :cry:

**Comment by m-tmatma** [comment]
#821
#1183
#1184
#1185
#1186
#1187

で変数名を変更したので必要なくなった。
