### ISSUE TITLE
[WIP] .win2k環境は本当に用意出来ないのかやってみる。

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#58]
検証記録用です。

**Comment by berryzplus** [comment]
#40 windows 2000の話はこちらで。

**Comment by berryzplus** [comment]
うーむ。かなり最近普通にインストール出来た人がいるっぽい。

https://plaza.rakuten.co.jp/spectra/diary/201702090000/?scid=wi_blg_amp_diary_next

**Comment by berryzplus** [comment]
うちのhypervでは無理でした。

**Comment by berryzplus** [comment]
VMWareでなら用意できそう、という結論になりそうなので一旦閉じます。
windows2000稼働環境が用意できるとなると、サポートOSをどうするかの考え方が違ってきます。

ちなみにこの話、windows98の勘違いだったようです。
しかもCPU制約は2GHzで、パッチを当てて回避可能、とのことでした。
http://userweb.alles.or.jp/chunichidenko/mycpu605.html
http://blog.livedoor.jp/blackwingcat/archives/1855346.html

サクラエディタ 1.x系の保守を現代で行う方法はないものかと
2年くらい前から95/98/Me/2000の稼働環境作成に何度か挑戦しています。
記憶が確かなら、windows95+dosboxの組合せ以外は
各種主要VMでインストール不可または起動できないという症状になった気がします。

VMWareなんてメジャーなもの、試してないわけないんだけどなぁｗ
週末にでももう一度リトライして、それはそれとして結果報告あげたいと思ってます。

**Comment by kobake** [comment]
自分の環境では以下が動きました。

- VirtualBox 5.2.6 r120293
- Windows 2000 Professional SP4
- sakura_install2-2-0-1.exe

<img width="515" alt="win2000sakura" src="https://user-images.githubusercontent.com/2929454/40980471-667e9c86-6913-11e8-91cf-17abc020ae9f.png">

本体動作自体は苦労なく行けました。

が、SSL 通信がうまくいかず繋がらないサイトが多く、そのあたりではちょっと困ったということを報告しておきます（Windows Update のサイトにも github にも sourceforge にも繋がらないので、手動で sakura_install2-2-0.1.exe をファイル転送して実行したら動きました）。
