### ISSUE TITLE
`if %ERROR_RESULT% neq 0` を `if errorlevel 1` にするか検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#586]
`if %ERROR_RESULT% neq 0`  を  `if %errorlevel% 1` にするか検討する

**Comment by m-tmatma** [comment]
参考サイト
https://blogs.msdn.microsoft.com/oldnewthing/20080926-00/?p=20743

**Comment by m-tmatma** [comment]
なお以下はエラー時の戻り値の仕様が違うので変更できない。
https://github.com/sakura-editor/sakura/blob/ad611b404befd856bea1978be3c542d3714ab5cc/build-chm.bat#L7-L9

**Comment by k-takata** [comment]
> なお以下はエラー時の戻り値の仕様が違うので変更できない。

`if not errorlevel 1` でいいはず。

**Comment by berryzplus** [comment]
「０以外」と「１以上」を同一視してよいものか、
通常は「よい」だと思いますが、悩むところです。

全部自分で作ったバッチで、自分は負数の戻り値を使わない、と断言できるならよいです。
扱うものが自分で作ったバッチじゃないので、一個ずつ仕様を確認しないといけない。

ぼくは、0～255以外の戻り値は極力使わないようにしています。
むかし、とあるUNIX環境でmoduleが返した-1が255に見えたことがあって、
戻り値に負数や `unsigned char` の範囲を超える値を使うのが怖いからです :sob:

気になったのでwindowsシェルがどんな値を返せるか調べてみました。
少なくとも `signed int` の範囲であれば負数も含めて返せるようです。

```cmd
cmd /k
exit /b -65536
echo %errorlevel%
```

hhcの戻り値については @k-takata さんの指摘のようにすればよいと思います。
適切なパラメータを指定した場合には「1=成功 or 0=失敗」となることが分かっているので、
「１以上じゃない場合」をエラーとすればよいと思います。

**Comment by m-tmatma** [comment]
#584 と一緒に対応してしまえばいいかと思います。

**Comment by ds14050** [comment]
>ぼくは、0～255以外の戻り値は極力使わないようにしています。
むかし、とあるUNIX環境でmoduleが返した-1が255に見えたことがあって、
戻り値に負数や unsigned char の範囲を超える値を使うのが怖いからです 😭

サンプル提供ありがとうございます。「[コレクション](https://github.com/sakura-editor/sakura/pull/552#discussion_r225550049)」に加えておきました。

**Comment by berryzplus** [comment]
一応、これシェルの話です。
main関数に限った話なんで、普通の関数では普通の戻り値使ってます:smile:

**Comment by ds14050** [comment]
そう。バッチにはバッチの作法があります。XP で使っていた xcopy が Vista になって robocopy に置き換えられたんですが、そのリターンコードがビットフラグで系統立てられており、バッチでフラグを取り出すサンプルまで提供されていました。

「[Robocopyの戻り値を知りたい - 履歴](http://d.hatena.ne.jp/sikakura/20110127/1296102650/)」

**Comment by m-tmatma** [comment]
#590 を作成しました。

**Comment by m-tmatma** [comment]
#590 をマージしたのでクローズ。
