### ISSUE TITLE
独自フォント作りませんか？(改行記号などの特殊文字の描画方法に関する話)

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#588]
サクラエディタでは、改行記号などの特殊文字の一部をGDI描画によって実現しています。
これがどうも遅いらしいです。
https://github.com/sakura-editor/sakura/issues/445#issuecomment-421557794

描画処理の置き換えについては、以前からぼんやりと考えていました。
ビットマップであらかじめ作成したイメージをペタッと貼る方法なら速いんじゃないか、とか。

先日対応したアウトライン解析ウインドウの処理で、
特殊フォントを使って図形描画を行う方法に気付きました。
https://github.com/sakura-editor/sakura/issues/543#issuecomment-430279162

必要な図形のみを定義したフォントファイルなら、あまり大きくはならないと思います。
描画命令が1度で済むようになる分、描画速度は向上するはずです。

現在すでに使っている特殊フォントの名前は `windings` `webdings` などです。
この流れでいくと、独自フォントの名称候補は `sakuradings` になるかと思います。

まだ企画段階のネタですがご意見あればお聞かせください。

**Comment by berryzplus** [comment]
認識してる特殊記号はこんな感じです。

名前 | 記号 | 説明
---- | ---- | ----
CR改行 | ↙ | 左肩下がりの矢印
LF改行 | ↓ | 下向き矢印
CRLF改行 | ↲ | 下方向左折れ矢印
タブ記号 | ^ | ハット記号（設定で選択可能）
半角スペース | - | 英子文字`o`の下半分

見て分かる通り、半角スペース以外は既存グリフに似た図形が存在します。

似た図形ではなく、現状の描画をそのまま引き継いだほうがよい気がするので「独自フォント」の話をしてます。

あと、[制御記号](https://ja.wikipedia.org/wiki/%E5%88%B6%E5%BE%A1%E6%96%87%E5%AD%97)関連も描画できるたらいいなぁ、と考えております。

従来の描画方式だと、表示できない文字は ・ だったり ? だったりに置き換えられてしまうので。

**Comment by ds14050** [comment]
>あと、制御記号関連も描画できるたらいいなぁ、と考えております。
>
>従来の描画方式だと、表示できない文字は ・ だったり ? だったりに置き換えられてしまうので。

応用が利くのはとてもいいですね。ただ、(ビットマップではなく)ベクタ画像以外の選択はないと思います。

**Comment by berryzplus** [comment]
全角空白（▢）の存在を忘れていました :sob:

**Comment by berryzplus** [comment]
> 半角スペースは ␣ (U+2423)？

あざっす。もうちょっと探してみます。

なんとなく「既存フォントで現状を置き換える」でもいい気がしてきました。

半角/全角とか等幅/可変とかは、いったんは「都合のいいフォントを見繕って固定」で試してみるところからかなぁ、と思っています。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394
