### ISSUE TITLE
tmpファイルがいっぱいあるのですが・・・

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#589]
sak684.tmp
↑
こんな感じの189kbぐらいのファイルが何年も前から、800個ぐらいsakura.exeの場所に溜ってるんですが、
消してもよいもの？

**Comment by KENCHjp** [comment]
よく見たら近年のファイルはなかったです。

**Comment by berryzplus** [comment]
> 消してもよいもの？

良いと思います。

ファイル名のパターンが、一時ファイル生成用のランタイム関数を使った場合と一致しています。
先頭3文字を指定してファイル名をランダム生成させ、".tmp"をくっ付けた名前に見えます。

ソースコードをgrepしてみたところ、まさしくそういう処理がありました。

https://github.com/sakura-editor/sakura/blob/353584cb4e573219af79b057ec8abb4fac472f74/sakura_core/CProfile.cpp#L238-L249

そのファイルの正体はおそらく `sakura.ini` です。
現状の最新モジュールが初回に生成する `sakura.ini` のサイズは `105KB` です。
設定やら最近使ったファイルが追加されていくので、そんくらいのサイズが実用だと思います。

似たような処理が他にもあったかどうかは知りません。
確かめる手段は「SAKURAで開く」ですｗ
`sakura.ini` であれば、先頭行にそう書いてあるはずなんで。

**Comment by KENCHjp** [comment]
了解です。
では消しますです。
