### ISSUE TITLE
Organization, Team の管理者について

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#59]
## 管理者を2人に増やします
- Organization の Owner (sakura-editor の管理者)
- Team の Maintainer (sakura-developers の管理者)

について、これまでは kobake が1人で受け持つ体制でやっていましたが、これらの管理者は常に2人程度いるのが好ましいかと思っています。管理者が1人だとその1人の連絡がとれなくなった場合にいろいろ困るので。

で、これは自分の独断で恐縮なのですが、 @KENCHjp さんを上記2か所の管理者として設定しました。サクラエディタとの付き合いが最も長く信頼できるというのが理由です。

## Organization の Owner について
[sakura-editor Organization](https://github.com/sakura-editor) の様々な設定ができます。実はあんまりいじりません。他の人を Owner に指名する権利も持ちます（Owner は複数人設定可能です）。

## Team の Maintainer について
[sakura-developers Team](https://github.com/orgs/sakura-editor/teams/sakura-developers) のチーム自体の設定（あまりいじらない）や、メンバー追加ができたりします。他の人を Maintainer に指名する権利も持ちます（Maintainer は複数人設定可能です）。

## 管理者としての心構え（？）
- 常に2人以上の管理者がいる状態を維持するのが好ましいです。
- 安全のため、2FA（二段階認証）を設定しておくのが好ましいです。

※というか 2FA は本当は管理者に限らず皆が設定しておくのが本当は好ましいですが今のところはスルーしてます。

@KENCHjp さん、責任を負担させるようですみませんが、支障なければよろしくお願い致します。
対応難しそうであれば今でも後でも辞退いただいて構いません。

## 今後の話
自分自身が割と飽きっぽいというか現実での環境をころころ変える性質なもので、たぶんどこかのタイミングで本業に忙殺されるなどの理由で疎遠になる可能性高いです。

あ、kobake 消えたな、って思ったら管理者もう1人増やしてください（すみません）。

**Comment by KENCHjp** [comment]
@kobake さんへ　はい私でよければ携わらせていただきます。
ただGitHubが今回の参加で初めてなのと、そもそもコミッターではないので開発にかかわることやジャッジにはほとんど貢献できないかもしれませんが、管理者じゃないと触れないGitHubの機能のところとか何かあった時の交通整理はできるかと思いますので、管理者というよりは皆さんを支える立場として振る舞う気持ちでおります。
よろしくお願いします。

**Comment by kobake** [comment]
@KENCHjp ありがとうございます。こういう大人な対応ができるところも管理者に指名させていただいた理由のひとつです。心強いです 🙏 

本 Issue については何か意見ある人のために1日程度残しておいて、特にコメント付かなければ Close します。

**Comment by KENCHjp** [comment]
2FAは自宅に帰ってから設定します。

**Comment by kobake** [comment]
Close します～
