### ISSUE TITLE
単体テストコードで NOMINMAX を定義しているのを削除する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#592]
単体テストコードで NOMINMAX を定義しているのを削除する

以下で定義されている。

https://github.com/sakura-editor/sakura/blob/df4ab03ae5b18e455c0a096dbdc4b3b9780bf261/sakura_core/StdAfx.h#L20-L21

以下で改めて定義しなくていいはず。

https://github.com/sakura-editor/sakura/blob/df4ab03ae5b18e455c0a096dbdc4b3b9780bf261/tests/unittests/test-int2dec.cpp#L4

https://github.com/sakura-editor/sakura/blob/df4ab03ae5b18e455c0a096dbdc4b3b9780bf261/tests/unittests/test-is_mailaddress.cpp#L3

以下で NOMINMAX に対する二重定義の警告になっている。
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/20001880/job/lk1mmxfimfku4a25

**Comment by m-tmatma** [comment]
以前は permalink をチケットに貼り付けたら、該当ソースがインラインで
表示されていたが、展開されなくなっている。(単なるリンクになっている)

**Comment by berryzplus** [comment]
> 以前は permalink をチケットに貼り付けたら、該当ソースがインラインで
表示されていたが、展開されなくなっている。(単なるリンクになっている)

すごく便利だったし、カッコよかったのに、埋め込まれなくなるとは残念 :sob:

**Comment by berryzplus** [comment]
本件についてはMinGWのビルド設定の問題なので、別な回避策の検討が必要かと思います。

端的にいうと、指摘のcppは`StdAfx.h`をインクルードしとらんのです。
ビルド設定のほうで強制的に`StdAfx.h`を差し込んでいるから出力された警告な認識です。

`#define`を外すべきなのか、`#ifndef`でくくるべきなのか、微妙なところです。
作成者の意図としては「`#ifndef`でくくる」がベターな気がします。

**Comment by ds14050** [comment]
ビルド設定で StdAfx.h を差し込んでいるというのがどの部分かわかりません。StdAfx.h.gch を利用してコンパイルされたエディタの .o ファイルをリンクしていることが影響しているのでしょうか。

**Comment by berryzplus** [comment]
> ビルド設定で StdAfx.h を差し込んでいるというのがどの部分かわかりません。

あれ？なんでだ？

ある.cppをコンパイルするとき、
ヘッダに対応するgchがあればそれが使われる、
というのがgccのコンパイル済みヘッダーの仕組みだったような。

パスにgchがあったら、それが優先して使われる？
そう言えば以前調べたとき、何か複雑な仕様も解説も見たような気が、しないでもない・・・

**Comment by m-tmatma** [comment]
> 以前は permalink をチケットに貼り付けたら、該当ソースがインラインで
> 表示されていたが、展開されなくなっている。(単なるリンクになっている)

質問しました。
https://github.com/sakura-editor/management-forum/issues/46

**Comment by k-takata** [comment]
> GitHub は HTML タグの中身としてあり得るか(limits, algorithm)、あり得ないか(gtest/gtest.h)によってアングルブラケットの扱いを変えているようです。

GFMで \<limits\> と書きたければ `\<limitis\>` と書けばよいです。

**Comment by ds14050** [comment]
ありがとうございます。しかしエスケープは嫌いなんです。プレインテキストをいい感じに解釈してくれるのがマークダウンをはじめとする軽量マークアップ言語の存在意義だと考えているので、解釈エラーに対応してテキストをマークダウンに与えるソーステキストに変換するつもりがないんです。面倒くさい人間ですね。

**Comment by berryzplus** [comment]
> パスにgchがあったら、それが優先して使われる？
> そう言えば以前調べたとき、何か複雑な仕様も解説も見たような気が、しないでもない・・・

1. `g++ (options...) -c StdAfx.h` とすると `stdAfx.h.gch` が生成される
2. g++の実行時、出力パスから `*.gch` が検索される
3. 見つかったgchの中からコンパイルオプションが一致しているgchが使われる

という流れになっているらしいです。

「テストプログラムではそもそもプリコンパイル済みヘッダーを使ってないから関係なくね？」というのが、このissueを久しぶりに開いて得た感想です。
