### ISSUE TITLE
HTML ヘルプ中に記載のあるビルドに必要なものが古い

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#598]
HTML ヘルプ中に記載のあるビルドに必要なものが古い

https://github.com/sakura-editor/sakura/blob/6e1fc6b7ba2c12bb75851c79963891f82dca8e71/help/sakura/_RESOURCE/HLP000112.html#L24-L34

**Comment by KENCHjp** [comment]
いま、人募集をOSDNに掲載してますが、こういう細かい気配りしてくれる人ほしいすうねぇ。
実装できるメンバーは実装に集中してほしいっす。

**Comment by m-tmatma** [comment]
#605 を投げました。

**Comment by m-tmatma** [comment]
マージしました
