### ISSUE TITLE
ビルド要件の精査と記述

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#6]
Visual Studio Community 2017 インストール時に Windows SDK を入れておかないとビルド通らない（当然といえば当然だけど README に明記はしたほうが良い情報）。

他、諸々ビルド要件について精査して README に書いておく。

## 参考事例
https://twitter.com/arigayas/status/998445467418574848
この例では Windows SDK 8.1 で通っているけど、このあたりのバージョン挙動についても調べておきたい。

**Comment by arigayas** [comment]
Twitterの画像を見に行くのが手間なので貼付けます。

以前、他のオープンソフトプロジェクトをビルドする時に
「Windows XP Support for C++」が必要ですと
教えてもらったので、このスクリーンショットだと
「C++に関するWindows XP サポート」にチェックが入ってます。

![vs2017_](https://user-images.githubusercontent.com/11251874/40295313-cbcf650e-5d13-11e8-8032-a7ad58b99ce0.jpg)

**Comment by kobake** [comment]
なるほど！追加情報ありがとうございます！
けっこう考えるところ多いですね。

Win10でビルドしたexeがWinXPで動くかどうかとか、網羅的にやろうとするとなかなか大変そう…。
地道に情報集めていきます…!!

※場合によってはサポートを切り捨てるOSも今後出てくると思います（そのために古いバージョンの実行ファイルの配布は残しておく）

**Comment by arigayas** [comment]
Visual Studioがインストールされていないまっさらな環境で
ビルド環境構築を試さないと他に必要なものがあるかどうかわからないですね。

_しかし私の手持ちの環境では、まっさらな環境はもう用意できません_

**Comment by kobake** [comment]
大丈夫です！基本的に報告のあったものから順次対応という感じで考えています！
いろんな人からのケース報告を待つことにします！

動作の再現性＞＞＞＞＞＞ビルドの再現性

ってことで、どちらかというとビルド環境よりも動作環境の検証を優先して考えているので、実は本 Issue の対応優先度は低めです。でも忘れないように Issue 化してます（ちょっとこの Issue の粒度は大きすぎるので、後々分割予定）。

**Comment by kobake** [comment]
今のところいただいた情報をもとに README に情報を追記しました。
このあたりは今後ビルドでコケる人からの報告をいただくたびに Issue 化して随時 README に追記するスタンスで行こうと思います。

**Comment by berryzplus** [comment]
いまさらですが、追加情報です。

現状では 「Windows 8.1 SDK と UCRT SDK」も必須のようです。
MsBuildの PlatformSDK を探しに行く機構が SDK バージョンを要求していて、
何も指定しない場合 8.1 を入力したのと同じ動きをするようです。

https://github.com/sakura-editor/sakura/issues/6#issuecomment-390576546
このスクショではチェックが入ってますね・・・

最新版 vs2017 をクリーンインストールする機会があって、ビルドできなくて地味に焦りました。

**Comment by m-tmatma** [comment]
> 現状では 「Windows 8.1 SDK と UCRT SDK」も必須のようです。
> MsBuildの PlatformSDK を探しに行く機構が SDK バージョンを要求していて、
> 何も指定しない場合 8.1 を入力したのと同じ動きをするようです。

PR 可能だったらお願いします。

**Comment by m-tmatma** [comment]
これは #518 の適用で完了ですか?

**Comment by berryzplus** [comment]
yesです。閉じておきますね。
