### ISSUE TITLE
「エクスプローラーで開く」、「コマンドプロンプトを開く」等のコマンドのアイコンを対応する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#607]
「エクスプローラーで開く」、「コマンドプロンプトを開く」のコマンド等のアイコンを対応する

https://github.com/sakura-editor/sakura/pull/603#pullrequestreview-173653455

- [x] 「エクスプローラーで開く」
- [x] 「コマンドプロンプトを開く」
- [x] 「powershellで開く」
- [x]  「このファイルのフォルダ名をクリップボードにコピー」 #1166

#1137 これのおかげで作業しやくすなったはず。

**Comment by berryzplus** [comment]
「powershellで開く」も同時にできたら嬉しいです（笑

**Comment by m-tmatma** [comment]
説明欄およびタイトルを変更しました。
 #608 を登録したのでまだ増えるかもしれません。

**Comment by berryzplus** [comment]
アイコン画像募集します。

とりあえず、ダミーアイコンで実装側だけ作りますんで、それっぽいアイコンを作ってみたい方がいればこの辺に貼ってください。

要件：
サイズは 16x16 
色深度は 16色(4bit)

この画像の空いてるところをテキトーに見繕ってはめ込むイメージになります。
![image](https://raw.githubusercontent.com/sakura-editor/sakura/master/resource/mytool.bmp)

余裕があれば256色(8bit)のバージョンも作っていただけると嬉しいです。
ここでの募集期限は 12/6(金) くらいを目途にしたいです。
要望がなかった場合、ぼくがテキトーに作る予定の怪しげアイコンが採用されます :sob:

**Comment by berryzplus** [comment]
作って試してみたら「管理者で開く」が別コマンドになってるのに気付いたので、
作成したアイコンは3つでなく5つになりました。

管理者権限が必要であることを示す「盾」のアイコンは、本来別の方法で表示させるものなんですけど、今回はとりあえずの対応なので別アイコンとして実装しています。「盾」アイコンのちゃんとした実装も、いずれはやりたいと思っています。

**Comment by berryzplus** [comment]
#680 をマージしました。

**Comment by m-tmatma** [comment]
#718 の対応が必要

**Comment by m-tmatma** [comment]
> 管理者権限が必要であることを示す「盾」のアイコンは、本来別の方法で表示させるものなんですけど、今回はとりあえずの対応なので別アイコンとして実装しています。「盾」アイコンのちゃんとした実装も、いずれはやりたいと思っています。

#732 で登録しておきました。

**Comment by berryzplus** [comment]
#1803 のマージにより、タスクリストを消化できたのでクローズします。
