### ISSUE TITLE
ファイルの場所を管理者としてコマンドプロンプトを開く、に対応する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#608]
ファイルの場所を管理者としてコマンドプロンプトを開く、に対応する

#549 に加えて、管理者権限のコマンドプロンプトがあると便利だと思う。

https://clown.hatenablog.jp/entry/20110524/uac

にあるように sakura.exe とは別に requireAdministrator を設定した exe を
別に用意してそれを ShellExecute で起動する (上記サイトでは ShellExecuteEx とあるが
ShellExecute でもいいと思う)

powershell も対応してほしい、という話になると思うが、
通常版の powershell がまだ未検討なので、またあとで考える。

**Comment by m-tmatma** [comment]
なお、該当プログラムは CUI アプリとしてではなく GUI アプリで実際の UI なしで作る予定。
理由は、エラーなどで MessageBox を表示させてとき CUI アプリだとコンソール画面が出るので
sakura.exe から呼ばれる exe としてブサイクだから。

**Comment by KENCHjp** [comment]
>GUI アプリで実際の UI なしで作る予定。

管理者権限は結構センシティブなので、悪用されないように要注意ってかんじですかね。
どうやって悪用するかは思いもつきませんが。

**Comment by berryzplus** [comment]
UAC周りは色々とごちゃごちゃしてますね。

> 管理者権限のコマンドプロンプトがあると便利だと思う。

まずこれは賛成です。

前提として「管理者権限のコマンドプロンプト」は気軽に使えるべきではありませんが、
サクラエディタを使う人の大半はレガシーコマンドが実行できる環境を必要する人な気がします。
「実装すべきじゃない」と突っ撥ねるよりは、やったほうがいいと思います。

> sakura.exe とは別に requireAdministrator を設定した exe を
別に用意してそれを ShellExecute で起動する

この実現方法はやーです（笑

oleVerbに"runas"を指定してあげれば普通にcmdを管理者権限で起動できたような。
（ちょっと未確認ですが）

**Comment by KENCHjp** [comment]
> >管理者権限のコマンドプロンプトがあると便利だと思う。
> まずこれは賛成です。

Me To.

>この実現方法はやーです（笑

Me To.

でも出来るのかなぁ。。。

**Comment by m-tmatma** [comment]
別アプリから cmd.exe を管理者権限で実行するのは出来ました。
sakura.exe からは確認してないですが。

**Comment by m-tmatma** [comment]
> oleVerbに"runas"を指定してあげれば普通にcmdを管理者権限で起動できたような。
> （ちょっと未確認ですが）

"runas" で管理者権限で起動はできました。
しかし、ShellExecute の第四引数は効かないみたいで `/k cd ` が必要みたいです。

**Comment by berryzplus** [comment]
そのあたりは柔軟に対応でｗ

ネットワークドライブのことを考えると `/k pushd path/to/open` のがいいように思います。

そういえば、cdコマンドってドライブ変えられましたっけ？

```cmd
C:\Windows\System32> cd N:\共有フォルダ
C:\Windows\System32> N:
N:\共有フォルダ> cd C:\Windows
N:\共有フォルダ> C:
C:\Windows> pushd N:\共有フォルダ
N:\共有フォルダ> _
```

みたいな動きになるような。

**Comment by m-tmatma** [comment]
#617 で対応

**Comment by m-tmatma** [comment]
↑チケット番号間違えたので修正
