### ISSUE TITLE
MinGW のバイナリを appveyor の成果物に含めるのを検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#614]
MinGW のバイナリを appveyor の成果物に含めるのを検討する

MinGW の動作確認をするためには、自前でビルドする必要があり、敷居が高い。
現状で MinGW のビルドをしているので artifacts に含めるだけなので、
ビルド時間はそんなに増えないはず。

**Comment by ds14050** [comment]
いいと思います。固める前の Debug 版 sakura.exe は 67 MiB くらいありますが、9 MiB くらいまでは縮められるようです。

zipArtifacts.bat を修正の上、MinGW ビルドでも呼び出すようにするのですよね。

**Comment by ds14050** [comment]
揃えるからにはパスは `%PLATFORM%/%CONFIGURATION%` です。

**Comment by berryzplus** [comment]
Appveyor のビルドから MinGW ビルドのタスクは既に除外されているので、このissueは閉じてしまいます。
