### ISSUE TITLE
サクラエディタを新規インストールするとツールバーが空っぽの状態で表示される

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#616]
build 845 (0deee7221f952fb0dba4f084c1fb86fff6abaa92) までは問題無いようです。
build 847 (836430e4c6cb24acff020970055c67f85a7f9ee8) から問題が有るようです。
https://github.com/sakura-editor/sakura/commits/master?after=efcaef1436281a5255f258ecc246f449164ddf74+244

**Comment by beru** [comment]
2.3.2.845 と 2.3.2.847 ではインストール後の設定ファイルの内容が結構異なりますね。。

**Comment by beru** [comment]
https://github.com/sakura-editor/sakura/commit/2bdab8a15ad1fa6725e8bc2571727b22a9865779

自分が入れたツールバーの更新を早める変更のせいで、設定ファイルを書き出す際にツールバーの内容が空になってしまってるのかもですね。。

**Comment by KENCHjp** [comment]
>build 847 (836430e) から問題が有るようです。

まさかのワシ？...

本体はいじってないのですが、影響あるとすると、Iniファイルを先に作っちゃうのが影響しているのかもですね。。。

**Comment by KENCHjp** [comment]
あれ、でも英語OSの時しかiniファイル先に作らなかったかと。。。

**Comment by beru** [comment]
0c2cbd157fd38a9f63d728e6d34a42450d6e697a はOK
2bdab8a15ad1fa6725e8bc2571727b22a9865779 はNG

でした。原因は不明ですが、2bdab8a15ad1fa6725e8bc2571727b22a9865779 の `installer/sakura-common.iss` の変更内容を revert してから installer を作ると症状が消えます。

なおアンインストール後に、`%APPDATA%/sakura` フォルダも削除してからインストールして確認しています。

**Comment by beru** [comment]
https://github.com/sakura-editor/sakura/commit/dc00a3ae4738387c507b19b55115d35b4b96f010#diff-3beb5e0d41ad2281f359783beb6fb433R185

https://github.com/sakura-editor/sakura/blob/b0fd1ab07c52c440729ca08ea6f0eb36cfbcc95a/installer/sakura-common.iss#L252

現時点の master (efcaef1436281a5255f258ecc246f449164ddf74) でも、`installer/sakura-common.iss` の 
`[Ini]` セクションをコメントアウトしてビルドしたインストーラーだと問題が起きないので、Iniファイルを先に作ってしまうのが影響しているみたいですね。メカニズムは分かりません。。

**Comment by berryzplus** [comment]
issue 立てありがとうございます。
コメントさるべーじ。

https://github.com/sakura-editor/sakura/commit/dc00a3ae4738387c507b19b55115d35b4b96f010#r31069565

どうやら「既存iniがあると初期化がうまくいかない」という不具合が顕在化したもののようです。

**Comment by berryzplus** [comment]
https://github.com/sakura-editor/sakura/issues/616#issuecomment-439525265
> 2.3.2.845 と 2.3.2.847 ではインストール後の設定ファイルの内容が結構異なりますね。。

この事象がよく分っていないです。
初回起動直後同士で比較した違い、という意味であれば納得なんですが。

**Comment by beru** [comment]
> [#616 (comment)](https://github.com/sakura-editor/sakura/issues/616#issuecomment-439525265)
> 
> > 2.3.2.845 と 2.3.2.847 ではインストール後の設定ファイルの内容が結構異なりますね。。
> 
> この事象がよく分っていないです。
> 初回起動直後同士で比較した違い、という意味であれば納得なんですが。

発言が不正確でした。初回起動直後、が正しいです。

**Comment by beru** [comment]
そもそも何でインストール時に設定ファイルを作成するようにしたんでしょうか？
サクラエディタ側が初期ファイル作ってくれるなら、インストーラーでは作らなくて良いような。。

**Comment by beru** [comment]
設定ファイルの `[Common]` セクションの `szLanguageDll` のエントリ初期値を設定するためのようですね。

英語UIを使いたい人は日本語表示のサクラエディタの設定画面のウィンドウのプロパティシートの言語の設定を任意でJapaneseからEnglishに選択してもらう運用にすれば何も問題が無いと思います。

**Comment by KENCHjp** [comment]
>そもそも何でインストール時に設定ファイルを作成するようにしたんでしょうか？

英語OS上でインストールするときに自動で英語表記になるようにインストーラーで対応しました。
実装側で英語がどうか判断してIniファイル作成するようになれば、インストーラーでの対応は不要かと思いますが、英語インストーラー対応の時の対応方法は上記の通りの対応となったため
インストーラー側でiniファイル作成してます。

**Comment by beru** [comment]
英語OS上でインストールした場合に自動で英語表記にするという要件を無くすのはどうでしょうか？

**Comment by KENCHjp** [comment]
>設計的に仕様を変えて「保留」に戻すのが妥当なのかな～と思っています。

このままリリースにまでたどり着くならインストーラー側でiniファイル作らないようにするのが最善策なのかなと思いますが、とりあえずこのIssueはカンバンに貼り付けていったん、どう実装するか（インストーラ側でどうにか改善するか本体側をどうにかするか）要検討っすかね。

**Comment by beru** [comment]
#620 で本体側で新規インストール後の設定ファイルかどうかを判定するようにしてみました。
ただ結構判定方法がいい加減なので危ないかも知れません。

新規インストール後の設定ファイルのみに使われる何か特別なエントリを用意するのも手かもしれないですね。

**Comment by KENCHjp** [comment]
>新規インストール後の設定ファイルのみに使われる何か特別なエントリを用意するのも手かもしれないですね。

そうですね。
インストーラーだけが設定するエントリを設けるとインストーラーと連携してexe側も修正要なので、exeだけが設定するエントリを設けるのがexeでクローズして良さげかも。それがなければインストーラーで設定したiniファイルと判断するみたいな。

**Comment by berryzplus** [comment]
おおう。似た提案が既にされてたｗ

https://github.com/sakura-editor/sakura/pull/620#issuecomment-439662146

exe側に「設定リセット」用のエントリを作って、インストーラではそれを書くようにする、というプランです。exe側にリセットボタンを付けるかどうかは相談・・・。

**Comment by beru** [comment]
> > 新規インストール後の設定ファイルのみに使われる何か特別なエントリを用意するのも手かもしれないですね。
> 
> そうですね。
> インストーラーだけが設定するエントリを設けるとインストーラーと連携してexe側も修正要なので、exeだけが設定するエントリを設けるのがexeでクローズして良さげかも。それがなければインストーラーで設定したiniファイルと判断するみたいな。

exe だけが設定する（新規の）エントリを設けてそれがなければインストーラーで設定したiniファイルと判断して設定をリセットする方法だと、バージョンアップして過去の設定ファイルで起動したら設定が初期化されないか心配です。

**Comment by KENCHjp** [comment]
>過去の版の設定ファイルにはこれから追加する新規エントリは存在しない筈なので。

なるほど。それはそうですね。

ま設計なのでどうやるかですが、インストーラーで、バージョン情報も合わせて書き込むとか、、、

いや、やっぱり明確に「インストーラーで初期値設定しました」をわかるエントリ設けるのが明快ですね。

**Comment by KENCHjp** [comment]
>exe側に「設定リセット」用のエントリを作って、インストーラではそれを書くようにする、というプランです。exe側にリセットボタンを付けるかどうかは相談・・・。

これと同義ですね。

**Comment by beru** [comment]
「インストーラーで初期値設定しました」エントリを付けるとしたら、それは設定ファイルを新規作成した場合のみにするべきだと思いました。古いバージョンのサクラエディタを使っているユーザーがバージョンアップの為に新しいインストーラーを使う事も有ると思うので。

**Comment by KENCHjp** [comment]
これはクローズでいいかしら？

**Comment by beru** [comment]
そうですね、クローズで問題ないはずなのでクローズしておきます。
