### ISSUE TITLE
サクラエディタではアクセスキーに大文字/小文字の区別がありません。

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#624]
表示テキストが大文字表記になってるので、システムから送られてくる文字を大文字に変換して当て込んでいます。
このままだと `P + P` でpsを開く、`P + ↓ + P`で管理者psを開くになります。

_Originally posted by @berryzplus in https://github.com/sakura-editor/sakura/pull/623_

**Comment by m-tmatma** [comment]
コマンドプロンプトを開く、コマンドでも同じ  (#603, #618)

**Comment by berryzplus** [comment]
high dpi 対応のついでで検討したcmenudrawerの改修検討案があるので、そのうち出します。

cmenudrawer::onmenucharという関数がその部分。
冒頭で謎の変換処理と大文字化をやっています。

https://github.com/sakura-editor/sakura/blob/ace82c2d80a2ca97af6c73d6f6984aa07a4cd5f4/sakura_core/uiparts/CMenuDrawer.cpp#L1593-L1599

文字コードが空白より前ってのは制御文字なので、if文の前半は謎です。
そして、半角アルファベットでない文字をtoupperしたときの挙動は保証されていません。

**Comment by m-tmatma** [comment]
キーがかぶっているの、およびかぶっているのを assert 等で検出できるようにしたいと思います。
コマンドプロンプトの方でも同じ問題があるので、それも一緒に検討したいです。

**Comment by ds14050** [comment]
自信がないのですがこれってメインメニューやコンテキストメニューの話ですか？ キーがかぶっている場合はキーを押す毎にサイクリックに項目が選ばれるものではないのでしょうか。つまりキーかぶりは想定内。

**Comment by berryzplus** [comment]
> このままだと P + P でpsを開く、P + ↓ + Pで管理者psを開くになります。

これが間違ってるのかな。
正しくは `P Enter` でpsを開く、`P P Enter`で管理者psを開く。
ローカルでやってた改善案と挙動が混じった。。。＿|￣|○

**Comment by berryzplus** [comment]
> メニューのアクセスキーで大文字小文字を区別しないのはWindowsの仕様だと思いますが、何を問題としているのでしょうか。

これが結論ですね。閉じておきます。
