### ISSUE TITLE
appveyor.yml で test_script を調査する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#628]
appveyor.yml で `before_test` および `test_script` を調査する
https://www.appveyor.com/docs/appveyor-yml/

テスト用のビルド、実行で `build_script` を使っているが、
`before_test` および `test_script` を使えないか検討する。

https://github.com/sakura-editor/sakura/blob/ace82c2d80a2ca97af6c73d6f6984aa07a4cd5f4/appveyor.yml#L13-L19

~~おそらくこれを使えば、ビルドとテストを分離できるので、テストが失敗しても~~
~~artifacts の収集には影響しないんではないかと思う。~~ 
(↑ テストに失敗したときのartifacts の収集は  #632  参照)

**Comment by m-tmatma** [comment]
> テストスクリプトの最後に無条件で `exit 0` するとどうかなあとは思っても試してはいません。

それだと、テストに失敗しても気づかないのでよろしくないと思います。

**Comment by ds14050** [comment]
Tests タブがありますよ？ Job 一覧画面で気がつけるかどうかは未確認ですが。

@berryzplus さんは Console タブにテスト結果を表示するのもやめる予定だそうです。exit 0 する前に１行だけ echo しましょうか。

**Comment by m-tmatma** [comment]
それは、自分でちゃんとチェックするという前提なので、ci の価値がだいなしになります。
ビルド、あるいはテストに失敗した時にメール通知して、マージをブロックすることが重要です。

**Comment by ds14050** [comment]
>それは、自分でちゃんとチェックするという前提なので、ci の価値がだいなしになります。
>ビルド、あるいはテストに失敗した時にメール通知して、マージをブロックすることが重要です。

これは正しい。ぐうの音も出ません。

しかしそうなると artifacts 以外のものを利用しなければテスト結果ににかかわらずに生成物を手に入れる方法はないと思います。

テストに通らなかった生成物をなぜ手に入れたいのか、そのうちの何を手に入れたいのか、から問い直す必要があるのではないでしょうか。

**Comment by ds14050** [comment]
自分の場合はテストに通らなかった原因を探るためにテストプログラムが手元に欲しいと思いました。あっ、

**Comment by m-tmatma** [comment]
> おそらくこれを使えば、ビルドとテストを分離できるので、テストが失敗しても
> artifacts の収集には影響しないんではないかと思う。

これを使うと、テストの準備のコードとテストの実行コードをわかりやすく書くことは
できるが、artifacts の収集を実行させることはできなかった。

ただ、テストコードをわかりやすく書くことはできると思う。

テストに失敗した場合に、artifacts を収集できるようにする件は  #632 で扱う。
このチケットは、`before_test ` および  `test_script` に関して扱う予定。

**Comment by berryzplus** [comment]
結果が正常の場合のログは要らんと考えています。

ここのCI環境はまだ軌道に乗ってるとは言いえないと思っています。
なので、現状では正常ログも必要と考えています。

「処理結果＝正常」と言ってるログがなんかおかしい、
そういうのを潰しきってからがCIだと思っています。

> それは、自分でちゃんとチェックするという前提なので、ci の価値がだいなしになります。
> ビルド、あるいはテストに失敗した時にメール通知して、マージをブロックすることが重要です。

だから、これはよく分からんのです。
自分でチェックする必要のあるものが残っている状態は、まだ開発中だと思うんです。
本流の開発が終わったあとも、継続的に品質担保を行っていくのがCIです。
本流の開発が終わっていないものは、開発者がローカルでビルドテストすべきです。
CIでは「前回はビルド成功、テストも成功」というのが前提にあるんです。

必要な出力は「OK」か「NG」かだけです。

結果がＯＫのときのログは誰も見ません。
だから、コンソールに詳細なログを出す必然はないと思います。

結果がＮＧのときのログは、何がＮＧなのかを調べるために使います。
これには詳細なログが必要です。

たぶんいまＯＫのときにも出てるログは、
詳細ログとして必要な情報をカバーするために出しているものだと思います。
現状は「処理結果ＯＫ」と出てても本当にＯＫか怪しい部分があるので必要と考えています。
将来的には「処理結果ＯＫ」と出すなら詳細ログは表示しないくらいが理想だと思っています。

単体テストの実行ログは詳細ログだと思います。
このテストの仕組み自体がごく最近できたものなので（間違ってＮＧをＯＫとしないか怪しいので）、当面はＯＫのときもテスト結果は表示すべきだと考えています。

ビルドかテストが失敗したら、関係する人は詳細ログを入手して原因を調査します。
今後、ビルド環境が安定してＣＩとして確立できた暁には、成功時のテストログはコンソールから削ってしまってよいと思っています。

**Comment by berryzplus** [comment]
> 自分の場合はテストに通らなかった原因を探るためにテストプログラムが手元に欲しいと思いました。

これはどうなんだろう？と思いました。

ローカルで動くプログラムが動かないのは環境要因だと思います。
現状ではまだテスト環境を作り切れていないので、必要なライブラリにパスが通っていないことも考えられます。（gtestの場合、埋め込まない限りdllが必要だったりします。）

少なくとも１度は成功、からの変更で問題が出ないことを担保する仕組みがCIだと思います。
ここのCI環境には、まだまだCI以前な問題が残っていると予想しています。
まぁ、焦らずぼちぼち解決していければいいな、と思っております。

**Comment by m-tmatma** [comment]
私は、テストプログラム自体は特に必要ないですが、
ローカルではテストできない CI に関係する処理を書いているときに
何かうまく動いていないときの調査用に中途半端でも artifacts が
あると便利だと思いました。

**Comment by m-tmatma** [comment]
> 今後、ビルド環境が安定してＣＩとして確立できた暁には、成功時のテストログはコンソールから削ってしまってよいと思っています。

何のために削りたいですか?

**Comment by berryzplus** [comment]
> 今後、ビルド環境が安定してＣＩとして確立できた暁には、成功時のテストログはコンソールから削ってしまってよいと思っています。
> 
> 何のために削りたいですか?

コンソールに出す情報はサマリでよいと考えるからです。
CI環境の存在意義は、本流開発完了後の追加開発の省力化だと思っていて、
見る必要のない情報は出力すべきでないと考えています。

前回ログと今回ログを突き合わせて、ＯＫかＮＧか判定する作業は、本流開発時には必要ですが開発が終わったら要らないと思っています。詳細ログを毎回だして、何か変わったことがないかチェックするようなCI環境もありますが、そういう環境では「ログに時刻を出さない」とか一致確認をしやすいような工夫がなされるものだと思っています。

いまappveyorに出してるログは、純粋な詳細ログで調査に使える内容だと思います。
ビルド＆テストともに問題なしの状況では使い道のないログだと思っています。
逆に、何のために正常時の詳細ログをコンソールに出したいのか知りたいです。

**Comment by m-tmatma** [comment]
基本的にログは動いている、いないに関わらず常に出しておくものと考えます。

問題ないように見えていても、後で問題があることがわかるということもあります。
そのときにすべてのビルドで詳細なログが利用可能だと、どのビルドで問題が
発生していたかを少ない手間で手かがりを見つけることができます (できる可能性があります)。

ただ画面に出力する量が多すぎると扱いが難しくなるので、多すぎる分を
ファイルにリダイレクトして、artifacts に含めるという対応でもいいと思います。

画面とに出力するメリットはいちいちダウンロードしなくてもいいので簡単に確認できることです。
多すぎる確認が難しくなりますが、コンソールのログをファイルとしてダウンロードできるので、artifacts に含めるよりはお手軽に扱えると思います。

**Comment by jakenjarvis** [comment]
単純に、テストの結果がどうであろうと、「必ず出力する先」と、「テストの結果がOKだった場合のみ出力する先」を、あらかじめ決めておくだけの話ではダメなのでしょうか？
当然、それぞれ出力する内容が異なっていてもOKだと思います。（ログが必要、不要など）

appveyorは、複数のartifactsの条件付き出力に対応できるので、なぜ「一つの出力先」に拘るのか、よくわかりません。（以前から別のIssueでも問いかけてるけど、だれも答えてくれないし・・・）

**Comment by m-tmatma** [comment]
> （以前から別のIssueでも問いかけてるけど、だれも答えてくれないし・・・）

多分みんな気づいてない、または、忘れているのだと思います。
しばらく待っても反応ないときは、該当のチケットに状況確認のコメントをしていただくのがいいと思います。

**Comment by berryzplus** [comment]
あらためて眺めてみると、本題と関係ないことばっかり話してますね（反省

> 基本的にログは動いている、いないに関わらず常に出しておくものと考えます。

誤解はないと思いますが、ぼくもそう考えています。
違いは「コンソール」に出すかどうかの1点で、ファイルには残すべきと考えています。
現段階ではコンソールにも出すべき、というのはおんなじだと思ってます。

本題についての見解は https://github.com/sakura-editor/sakura/pull/634#issuecomment-442843404 に書いた通りで、「現状では必要ない」と考えています。あっちが閉じられてるから一旦了解でよいかな？

検討する価値がなかったとは思ってなくて、また必要になったらそのときに再検討すればよいのかなと思ってます。ぶっちゃけ、ぼくもこれ使えるんじゃないかと思ってましたし :sob:

> appveyorは、複数のartifactsの条件付き出力に対応できるので、なぜ「一つの出力先」に拘るのか、よくわかりません。（以前から別のIssueでも問いかけてるけど、だれも答えてくれないし・・・）

この件は、まだ出力先の精査ができるほど成果物がまとまってなくて、
今時点では何もできないからだと思います。

というわけで、一旦これ閉じま～す :smile:
