### ISSUE TITLE
appveyor でテストに失敗した場合でも artifacts を収集できるようにする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#632]
appveyor でテストに失敗した場合でも artifacts を収集できるようにする。
https://github.com/sakura-editor/sakura/issues/628#issuecomment-440504687

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sandbox/pull/7
でテストに失敗した場合でも artifacts の収集を行う実験に成功した。
技術的に実現できそう。

ポイントは、`appveyor PushArtifact <file_name>` のコマンドをビルド、テスト用のバッチファイルの中から実行すればよい。

参考:
https://www.appveyor.com/docs/packaging-artifacts/#pushing-artifacts-from-scripts

**Comment by m-tmatma** [comment]
ワイルドカードは使えないみたい。
https://ci.appveyor.com/project/sakuraeditor/sandbox/builds/20491766/job/7xtoquaji6my6gk9

**Comment by berryzplus** [comment]
あらためて見直してみて「何故そうしたいのか？」が分からんことに気付きました。

```
この PR の目的が達成される。
 　　　　↓
テストで何らかのNGが見つかったビルドのバイナリが「ダウンロードできる」ようになる。
```

こうなると嬉しいこと（＝メリット）があるから、そうしたいって issue なんだと思います。
問題のあるバイナリを公開することは、それ自体がデメリットだと思います。
ただ、デメリットを上回るようなメリットがあるならやってもええかな？とも思いますけれど。

テストで何らかのNGが見つかったのなら、そのバイナリはダウンロードできるべきでないと個人的には思います。
無論、テストのほうが誤ってる場合は除く :smiley:

**Comment by berryzplus** [comment]
興味ある人も居ないようなので閉じておきます。

必要あれば新たにissue立ててください。
