### ISSUE TITLE
#636 のマージ後に unittest が走らなくなっている

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#646]
#636 のマージ後に unittest が走らなくなっている
https://github.com/sakura-editor/sakura/pull/636#issuecomment-441433523

#636 のマージ前には `tests\build\Win32\bin` が存在しなかったので 以下の pushd が失敗していた。

https://github.com/sakura-editor/sakura/blob/102dd9873f4d7958b887f777336709143159f55b/tests/run-tests.bat#L8-L12

ディレクトリの移動に失敗していたので
`tests\run-tests.bat` がたまたま `build\Win32\unittests\Win32\Release\tests1.exe` を
見つけることができた。

しかし、googletest 側の何らかの変更の影響で  `tests\build\Win32\bin` が存在するようになり
pushd が失敗しなくなったので、テスト用の実行ファイルが存在しない  `tests\build\Win32\bin` の
ディレクトリに pushd してテストを見つけられなくなった。

googletest の更新は直接の原因ではない。

なお、pushd するパスの誤りを修正した #633 の PR を先ほどリビルドかけたが、
テストは実施されている。

修正方法に関しては、#633 より、こちらのチケットに書くのがいいと思います。
#633 以外の修正方法もあり得るからです。

#### まとめ

- #633 とりあえずの修正方法
- #648  再発防止策

**Comment by berryzplus** [comment]
暫定で直す方法があるなら、とりあえずそれ入れてからあるべき方法を考えたいです。

さっきみたらテスト結果26って出てた気がするけど今どっちなんだろ・・・

**Comment by m-tmatma** [comment]
> 暫定で直す方法があるなら、とりあえずそれ入れてからあるべき方法を考えたいです。

ではそれで。

> さっきみたらテスト結果26って出てた気がするけど今どっちなんだろ・・・

どのビルドの話ですか?

**Comment by m-tmatma** [comment]
再発防止策のために #648 を作成しました。

**Comment by berryzplus** [comment]
> > 暫定で直す方法があるなら、とりあえずそれ入れてからあるべき方法を考えたいです。
> ではそれで。

忘れるといかんのでapproveだけ出してきました。

> > さっきみたらテスト結果26って出てた気がするけど今どっちなんだろ・・・
> どのビルドの話ですか?

もしかしてローカルは関係ない？
https://ci.appveyor.com/project/berryzplus/sakura/builds/20534378

最新ベースのブランチのつもりだったんですが・・・

**Comment by berryzplus** [comment]
単に最新master取り込めてない気配↓　tests26件と出ている
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/20536156

**Comment by m-tmatma** [comment]
説明欄にまとめを追記

**Comment by m-tmatma** [comment]
#633 をマージしたのでとりあえず解消した。

**Comment by berryzplus** [comment]
対応終わったので閉じます。
残件は適切な既存issueで継続されます。
