### ISSUE TITLE
Common File Dialog の代わりに Common Item Dialog を使用する

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#652]
Windows Vista 以降から提供されているもので、これに切り替える事で使い勝手が良くなると思います。

https://msdn.microsoft.com/en-us/library/windows/desktop/bb776913%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#api

**Comment by berryzplus** [comment]
是非やりたいと思っております。

導入にあたっての障害は、利用するためのエントリポイントが異なる点と、
サクラエディタのファイルダイアログにはカスタムコントロールが存在する点だと思っています。

あまり踏み込んだ話を書いてやりづらくなるとアレなので進め方はお任せします:smile:

**Comment by m-tmatma** [comment]
説明欄にあるサイトのサンプルはすごい深いインデントになっている。
https://msdn.microsoft.com/en-us/library/windows/desktop/bb776913%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396#usage

※ `深いインデント`って変換しようとしてら、`不快インデント`が最初に変換候補に出た。😄

**Comment by m-tmatma** [comment]
全然関係ないけど気になったので調べてみた。

URL にある `MSPPError=-2147217396` で `-2147217396` は 0x8004100c なので
https://docs.microsoft.com/en-us/windows/desktop/wmisdk/wmi-error-constants
によると

```
WBEM_E_NOT_SUPPORTED
    2147749900 (0x8004100C)
    Feature or operation is not supported.
```

という意味みたい。

**Comment by KageShiron** [comment]
> 深いインデント

リソースの開放の都合もあるとはいえ、early returnしてほしい 😅

**Comment by berryzplus** [comment]
> 深いインデント

C言語 にもコピペできるように書いてあるから仕方ないのかな、と。
c++で書くとクラス前提になっちゃうのでサンプルに適さないというか。

**Comment by beru** [comment]
こちら着手しました。年明けにはPR出せるようにします。

**Comment by berryzplus** [comment]
#716 がマージされているので閉じてしまいます。

**Comment by beru** [comment]
@berryzplus 

そろそろVistaスタイルのファイルダイアログをデフォルトで有効化しようと思いますがどうでしょうか？
