### ISSUE TITLE
bregonig.dll に perl_license.txt と perl_license_jp.txt を同梱する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#66]
bregonig.dll のライセンスに関して以下を見ると
https://github.com/sakura-editor/sakura/wiki/PackageStructure

bsd_license.txt があったので BSD ライセンスなのかなと思ったのですが、

[正規表現ライブラリ bregonig.dll の 9. ライセンス](http://k-takata.o.oo7.jp/mysoft/bregonig.html#SCT-9.) を見ると
 `bregonig.dll は、正規表現ライブラリとして Oniguruma (Onigmo) を使用しており、Oniguruma (Onigmo) は BSD ライセンスとなっています。` とあります。

これは、bregonig.dll が依存している `Oniguruma (Onigmo)` というモジュールが
 BSD ライセンスなのであって、bregonig.dll 自体は `Perl と同じライセンス、すなわち GPL と Artistic License のどちらか` のように見えます。

なので perl_license.txt や perl_license_jp.txt を同梱する必要があるのではないですか?

→ @k-takata さんから回答いただいたので同梱します。

**Comment by berryzplus** [comment]
ご本人に聞いて見るのが一番なんですが、迷惑になってもいけないような。

https://github.com/k-takata/bregonig

たかたさんのライセンス原文を見る限り、追加のライセンス文書を添付すべきだと思います。

**Comment by m-tmatma** [comment]
> ご本人に聞いて見るのが一番なんですが、

そう思いますが、まずは経緯を知っている人はいるかの確認です。

**Comment by kobake** [comment]
経緯知らないです

**Comment by m-tmatma** [comment]
> たかたさんのライセンス原文を見る限り、追加のライセンス文書を添付すべきだと思います。

同梱するようにしましょう。

**Comment by k-takata** [comment]
> これは、bregonig.dll が依存している Oniguruma (Onigmo) というモジュールが
> BSD ライセンスなのであって、bregonig.dll 自体は Perl と同じライセンス、すなわち GPL と Artistic License のどちらか のように見えます。

その解釈で合っています。

> なので perl_license.txt や perl_license_jp.txt を同梱する必要があるのではないですか?

それが望ましいです。

**Comment by k-takata** [comment]
過去ログを見ると、微妙に違うこと言っていました…。
http://sakura-editor.sourceforge.net/cgi-bin/cyclamen/cyclamen.cgi?log=dev&v=4882

げんたさん
> 2) その際パッケージにはバイナリのみ含めても問題ないでしょうか．
>    ライセンスファイルなど併せてパッケージに含めるべきファイルはありますか．
> bregonig.dllのライセンスについてはヘルプファイルに含めてもらおうかなとも思っています．

K.Takata
> 問題ありません。
> オリジナル版の Bregexp.dll と同じように扱っていただければよいかと。

ライセンスファイルの内容がヘルプファイルに含まれているのであれば、単体のライセンスファイルを同梱しないという選択肢もありです。

**Comment by m-tmatma** [comment]
# 124 で同梱する実験に成功した

**Comment by KageShiron** [comment]
今後、同梱するツールやライブラリが増えてきたときに(ctags,diff,migemo...)ライセンスファイルがたくさんになってしまい、不便かと思います。

ヘルプファイルにまとめた方が良いかと思います。

**Comment by kobake** [comment]
ライセンス情報をまとめるのには同意です。

形式としてはヘルプ内でも良いですけど、license.txt みたいなファイル作ってそこに列挙する感じでも良いと思っています。

**Comment by m-tmatma** [comment]
> ライセンス情報をまとめるのには同意です。

ライセンスをまとめるかは別途検討するとしてとりあえず、
暫定的に perl_license.txt と perl_license_jp.txt を同梱する対応しておきますか?

**Comment by beru** [comment]
これって bug なんでしょうか？

**Comment by arigayas** [comment]
bug よりは document でしょうか？

**Comment by KENCHjp** [comment]
bugをプログラム不具合と狭義にとらえるとバグではないっすが、
あまり厳密性を求めないのもこのプロジェクトのやんわりしたルールなので、
不都合とか不手際をbugラベルにする動機もすてがたいですが、
これをchangelogに拾われるとこまるので、ciかマネージメントをつけたくなりますね。
