### ISSUE TITLE
背景画像に対して透過効果を出来るようにして欲しいです

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#665]
@arigayas  

https://github.com/sakura-editor/sakura/issues/659#issuecomment-443426998

> 別のissueとして登録した方が良いと思いますが
> 背景画像に対して透過効果を出来るようにして欲しいです。

@beru 

https://github.com/sakura-editor/sakura/issues/659#issuecomment-443463489

> 自分もそれは思った事があります。あとターミナルエミュレータとかでよくありますが背景を透過させて後ろのウィンドウの内容が透けて見えたりとか、実用性は微妙な気がしますが出来ても良いと思います。

**Comment by beru** [comment]
背景画像の透過ですが簡単に実現出来そうなことが分かりました。

BLENDFUNCTION::SourceConstantAlpha の値で画像の透過度を調節出来るようです。
0 の時に透明で 255 で不透明。

もし #683 が merge されたら、別のPRで設定画面の変更も含めて対応しようと思います。

なお、エディト領域のウィンドウ自体が透過して後ろのウィンドウの内容が透けて見えるようにするには、WS_EX_LAYERED を指定してから UpdateLayeredWindow を使えば出来るようです。しかし WM_PAINT に頼れなくなるようなのでそうすると結構大きな改造が必要そうでしんどい気がします。。

**Comment by berryzplus** [comment]
参考情報を追記しときます。

サクラエディタのウインドウ構造はこうなっています。
・CEditWnd ・・・ タイトルバーを表示する、ルートのフレームウインドウ
　┗CSplitterWnd ・・・ ウインドウ分割を実現するウインドウ
　　┗CEditView ・・・ ビュー、エディタ部分のウインドウ、表示してなくても5つのインスタンス

透過実装を行う場合、少なくともこの3つのウインドウクラスに対して変更が必要です。
レイヤーという言い方だと3層構造になので各層を透過させないといかんです。


現状の `WM_PAINT` は更新領域の情報を部分的にしか使っていないので、
そのあたりを改修する必要があると思われます。

* 更新矩形 ・・・ 更新対象のRECT(矩形)、既存コードで既に部分的に考慮されている
* 更新領域 ・・・ 更新対象のREGION(矩形とは限らない)

**Comment by beru** [comment]
あらら、、透過ウィンドウの実現は厳しそうですね。

**Comment by beru** [comment]
背景画像に限らないウィンドウ自体の透過表示については別Issue #691 で扱う事にしましょう。

**Comment by beru** [comment]
#704 を merge したので close します。
