### ISSUE TITLE
「ファイルのプロパティ」ダイアログのエディットコントロールにTabStopを付ける

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#667]
> 
> 1. サクラエディタでファイルを開いた状態で `Alt+Enter` で
> 2. ファイルのプロパティが開かれるのでスクリーンショットのように選択して `Ctrl+C` でコピーしてます。

自分もそうしています。わざわざそうせずともまんまのコマンドがメニューにもあるしショートカットキーも標準で割り当てられてますがそんなに使う頻度が高くないので暗記してなくて使えていません（というか最近入ったみたいですね）。

惜しむらくは Alt + Enter キー押しで表示されるファイルのプロパティ画面の情報表示するエディットコントロール（ID : `IDC_EDIT_PROPERTY`）の Tabstop が False になっているのでタブキーを押してもフォーカスが合わない事です。なのでファイルのプロパティ画面を開いてもキーボード操作だけでパスのコピーが出来ない。。

_Originally posted by @beru in https://github.com/sakura-editor/sakura/issues/658#issuecomment-443464341_

**Comment by beru** [comment]
#670 を merge したのでこの issue は close します。
