### ISSUE TITLE
Installer を作成してみる

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#67]
Installer を作成してみる

Inno Setup は以下から入手できる。
http://www.jrsoftware.org/isdl.php

最終的には appveyor でビルドしたいが、その準備作業です。

## 2018/6/8 追記

appveyor には innosetup-5.5.9-unicode.exe がインストールされている。
- https://www.appveyor.com/docs/build-environment/#tools
- appveyor/ci#2421

→　なので  innosetup-5.5.9-unicode.exe を使う

## 2018/6/16 追記

Inno Setup 5 のコマンドラインでのコンパイル方法
http://www.jrsoftware.org/ishelp/index.php?topic=compilercmdline

http://www.jrsoftware.org/isdl.php で innosetup-5.6.1-unicode.exe が公開されているが、
https://www.appveyor.com/docs/build-environment/#tools では更新されていない。

**Comment by kobake** [comment]
> Inno Setup は以下から入手できる。
> http://www.jrsoftware.org/isdl.php

innosetup-5.5.9.exe と innosetup-5.5.9-unicode.exe どちらを使うのが良いか迷ってます。

AppVeyor で使える InnoSetup が（UNICODE とは明記していないことから、おそらく）innosetup-5.5.9.exe 相当のものなのかな、と想像しており、前者で検証するのが良いのかな、となんとなく思っています。

参考：
https://www.appveyor.com/docs/build-environment/
InnoSetup 5.5.9 (C:\Program Files (x86)\Inno Setup 5)

**Comment by m-tmatma** [comment]
> AppVeyor で使える InnoSetup が（UNICODE とは明記していないことから、おそらく）innosetup-5.5.9.exe 相当のものなのかな、と想像しており、前者で検証するのが良いのかな、となんとなく思っています。

質問しました。
appveyor/ci#2421

**Comment by KENCHjp** [comment]
回答ありましたが、Unicodeのようですね。
最近はマルチリンガルなインストーラーが多くて、何も明記がないと基本的にはUnicode対応しているものが多いように思います。

**Comment by m-tmatma** [comment]
> 質問しました。
> appveyor/ci#2421

説明欄に追記しました。

**Comment by m-tmatma** [comment]
https://www.appveyor.com/ のサイトは https://github.com/appveyor/website で管理されているらしい。

> https://www.appveyor.com/docs/build-environment/

のページは以下に対応する。(上記のページの一番下に書いてある)
https://github.com/appveyor/website/blob/master/src/docs/build-environment.md

**Comment by m-tmatma** [comment]
インストーラを作る手順
1. innosetup-5.5.9-unicode.exe をダウンロードしてインストールする。
   (http://www.jrsoftware.org/isdl.php で innosetup-5.6.1-unicode.exe が 2018-06-14 に
   公開されているがまだ appveyor では更新されていないみたい。2018-06-16 現在)
2. 既存のインストーラでインストールされるファイル (C:\Program Files (x86)\sakura) をまるごと installer にコピーする。
3. sakura.exe.manifest をコピーする。
4. sakura.exe.manifest をそれぞれ sakura.exe.manifest.v と sakura.exe.manifest.x に名前変更する
5. "C:\Program Files (x86)\Inno Setup 5\ISCC.exe" installer\sakura.iss を実行する
6. installer\Output\sakura_install2-1-1-2.exe ができる。

Inno Setup 5 のコマンドラインでのコンパイル方法
http://www.jrsoftware.org/ishelp/index.php?topic=compilercmdline

**Comment by m-tmatma** [comment]
appveyor で試しにトライしてみます。

bregonig.dll の管理方法が決まっていないので
とりあえず、sakura のリポジトリに登録する方法で
WIP の PR を出すことを目標になってみます。

**Comment by m-tmatma** [comment]
> 最終的には appveyor でビルドしたいが、その準備作業です。

#124 で appveyor でビルドできることを確認しました。

**Comment by m-tmatma** [comment]
一つのインストーラで x86, x64 の両方に対応するのが技術的に可能っぽい。
https://stackoverflow.com/questions/4833831/inno-setup-32bit-and-64bit-in-one

以下のようにしたらいいんじゃないかな

1.  appveyor.yml で platform のところで独自定義で例えば `both `を定義する
2.   `both `が指定されていたら`Win32`と `x64 `の両方をビルドする
3.  インストーラには両方のバイナリを含める
4.  インストーラが起動している OS によって `Win32`と `x64 ` をインストーラが自動的に選択して、インストールする

https://github.com/sakura-editor/sakura/blob/2b7920e5e03993fca0a430d81b8d40bad8404a8a/appveyor.yml#L13-L15

**Comment by m-tmatma** [comment]
> 一つのインストーラで x86, x64 の両方に対応するのが技術的に可能っぽい。

sakura.iss は x86 用、x64 用、両対応用の 3種類を用意すればいいと思う。

**Comment by KENCHjp** [comment]
innosetup-5.6.1-unicode.exe だと、issがエラーになっちゃいます。sendtoがなくなってる模様。何か対象OSを指定したりとかして解消できるのかもしれませんが、とりあえず速報。

**Comment by m-tmatma** [comment]
> innosetup-5.6.1-unicode.exe だと、issがエラーになっちゃいます。sendtoがなくなってる模様。何か対象OSを指定したりとかして解消できるのかもしれませんが、とりあえず速報。

#129 で登録しました。

**Comment by m-tmatma** [comment]
対応は完了した。
