### ISSUE TITLE
ダイアログの表示位置が開くたびにずれていってしまう

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#671]
https://egg.5ch.net/test/read.cgi/software/1495286392/345 より転載
> diff画面を開くたびにdiff画面がどんどん右に移動していきます。 
> Windowsのタスクバーを左に配置しているせいかもしれません。タスクバーの幅くらい移動するので。

https://egg.5ch.net/test/read.cgi/software/1495286392/347 より転載
> diff画面だけではなく他のダイアログ画面でも発生しました 
> 原因はタスクバーの事を考慮しないで表示位置を計算してるためのようです 
> タスクバーを上に置くと下に、左に置くと右に移動していきます

**Comment by KENCHjp** [comment]
あれ、これ立ててたような・・・

**Comment by beru** [comment]
#397 が既に立っていましたね。指摘ありがとうございます。それでは Close します。
