### ISSUE TITLE
「簡易リビルド」機能が非推奨になったことへの対応

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#676]
さっき sakura.sln をクリーンビルドして気付きました。
最近の変更で [-Gm](https://docs.microsoft.com/ja-jp/cpp/build/reference/gm-enable-minimal-rebuild?view=vs-2017) オプションが非推奨になったみたいです。

ログに警告が増えてます・・・。

```cmd
>cl : Command line warning D9035: option 'Gm' has been deprecated and will be removed in a future release
```

注：最新版(v15.9.3)の挙動です。appveyor のビルドで発生していたかどうかは見ていませんが、appveyorのvs2017は15.8だったはずなので発生しないんじゃないかと思います。

[リリースノート](https://docs.microsoft.com/ja-jp/visualstudio/releasenotes/vs2017-relnotes)にそれらしき記載はありませんが、ドキュメント側の更新日付が新しいので最近投入された変更と考えられます。

対象は `headermake` と `makefilemake` です。
緊急じゃありませんが、appveyorのvsバージョンが上がった時にビックリするのもあれなので、なんとなく対応方向を考えときたい感じです。

**Comment by berryzplus** [comment]
マズいとこ(タイトル)を誤字ってたので修正 :sob:

**Comment by ds14050** [comment]
チラ見して理解したところでは /Gm オプションというのは、ヘッダファイルが更新された場合でも再コンパイルが必要ない場合があるから独自のメタデータを参照して判断するよ、ってなオプションみたいですね。

ちょっとしたずるというかビルド時間最小化に貪欲だったというか、今ではインクリメンタルビルド、パラレルビルドという真っ当な代替手段で間に合うからそっちを使えと。

HeaderMake も MakefileMake も完成したプロジェクトですからオプションを取り除いてもなんの影響もないのではないでしょうか。
