### ISSUE TITLE
Issue・Pull Requestのテンプレート機能

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#69]
Issue・Pull Requestのテンプレート機能を使いませんか?
https://qiita.com/nyamogera/items/3fe6985b45fbd5377184

**Comment by kobake** [comment]
Issues, PR のレベルにばらつきが出るようであれば統制のためにテンプレート活用する価値はあると思います。今の時点ではそれほど困ってないので別に無くても良いかな、と思っています。

**Comment by m-tmatma** [comment]
> が、今の時点では自分はそれほど困ってないので別に無くても良いかな、と思っています。

問題が起こって、後でテンプレートが必要だと思って作る場合、
混沌とした状態になった issue/PR が乱立している状態なはずなので、
既存の issue/PR の整理に苦労しませんか?

困っていない状態で対処したほうが効果が高いと思います。

**Comment by kobake** [comment]
乱立とはいっても加速度的に issur/PR の数が増えることはないでしょう。

むしろいくつか具体的な問題点が観測されている時期に考えたほうが確実に効果のある対処を考えやすく合意もとりやすいです。今の時点からあれこれ思索を巡らせても検討外れになりそうで躊躇してます。

これはプログラミングにおいてもよくある話で、将来の可能性を憶測で考えすぎて作られたプログラムがフットワークを阻害するばかりで特にの益もないということはしばしばあります。

**Comment by KENCHjp** [comment]
「守れないルールが増えるのはルールが無いことよりも悪い」というのは持論でございまして、ルールが足かせになって活動が停滞する懸念はkobakeさんと同意。

ただGitHub超初心者の私としては、最低限なにかきゃいいんだっけみたいなことになるので、雛形あると書きやすいなぁと思いました。

なので厳密に守る守らないというのも議論の余地はあるかと思いますが、統制というと言葉は強いですけどレベル合わせのいみでテンプレートあると私みたいなものはたすかるかなと。
まずはテンプレートの使い方から勉強ですけど。

**Comment by kobake** [comment]
テンプレート導入で敷居が下がるなら良いですね。

sandbox というリポジトリを作成し、そこにちょっとだけ Issue テンプレート入れてみました。
https://github.com/sakura-editor/sandbox

Issue テンプレートの内容は以下から見れます。sakura-developers のユーザは誰でも書き換えられます。実験場なので好きに master をいじってしまっても良いです。
https://github.com/sakura-editor/sandbox/tree/master/.github/ISSUE_TEMPLATE

Issue テンプレートにより、Issue 作成時に以下のような選択肢が表示されるようになります。
https://github.com/sakura-editor/sandbox/issues/new/choose
<img width="466" alt="issue-template" src="https://user-images.githubusercontent.com/2929454/41143158-433a070c-6b33-11e8-8e7a-8bb266f5e7d6.png">

「バグ報告」については環境情報を必ず記載してもらう意味で有用だと思いました。
https://github.com/sakura-editor/sandbox/blob/master/.github/ISSUE_TEMPLATE/1_bug.md

「機能要望」「その他」については、ちょっと何の項目を入れれば良いのか迷いました。これだけだとテンプレートの意味あるのかどうか微妙です。
https://github.com/sakura-editor/sandbox/blob/master/.github/ISSUE_TEMPLATE/2_feature.md
https://github.com/sakura-editor/sandbox/blob/master/.github/ISSUE_TEMPLATE/3_other.md

**Comment by KENCHjp** [comment]
なかなかいいですね。
でも驚いたのは、画像がドラックドロップできることにおどろきました。
先の設定変更したエビデンスの画面ハードコピー残してあるのですが貼り付けられますね。

**Comment by kobake** [comment]
画像貼り付け方法などのTipsが自然に共有されるのは良いですね。

テンプレート内容精査しきれたら本リポジトリにもテンプレート適用してみるのは選択として良いと思います。

**Comment by m-tmatma** [comment]
#757 で issue template を適用

**Comment by m-tmatma** [comment]
対応済み。
