### ISSUE TITLE
Visual Studio 2019 ビルドに対応する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#698]
# Visual Studio 2019 ビルドに対応する

#694 でビルドエラーが修正されているみたいだが、
継続的に appveyor でビルドが通ることを保証できるようにしたい。

appveyor のイメージは利用可能になっている。
[Visual Studio 2019 Preview 1.1](https://github.com/appveyor/ci/issues/2759)
[Update to Visual Studio 2019 Preview 3](https://github.com/appveyor/ci/issues/2869)

## 対応時期

#653 対応後

## 対応が必要なタスク

- [ ] appveyor.yml で `image: Visual Studio 2019 Preview` の指定を追加する。
- [ ] msbuild.exe を探すスクリプトで Visual Studio 2017 を決め撃ちしている部分を 2019 と両対応できるようにする
- [ ] cmake 関連のプロジェクト生成時に Visual Studio 2017 を決め撃ちしている部分を 2019 と両対応できるようにする

## 複数の image 指定

image は以下のように複数指定できる。

https://www.appveyor.com/blog/2018/04/25/specialized-build-matrix-configuration-in-appveyor/

### 留意事項

全ての構成を VS2017 と VS2019 のイメージでビルドに時間がかかるので構成を絞る必要がある。

**Comment by KENCHjp** [comment]
>全ての構成を VS2017 と VS2019 のイメージでビルドに時間がかかるので構成を絞る必要がある。

どこかの時点で、スパッと切り替える方向にしてはどうでしょう。時期的には来年かな。。。

**Comment by berryzplus** [comment]
反対する理由はないんですけど、「みんなで人柱路線」で行くんでしたっけ？

**Comment by KageShiron** [comment]
どうしても2019の機能が必要とかでなければPreviewが外れてからのほうが無難な気がします。

**Comment by beru** [comment]
対応は急がずに正式リリースされてから検討するくらいで良い気もします。
あくまで過去のバージョンの傾向ですが週刊くらいな勢いで更新されたりするので、自分には使っていない関係のない機能の更新のために大量のDLがされて、`またかよ…` という気分を継続的に毎週のように味わいたい方に大変お勧めです。

**Comment by m-tmatma** [comment]
単に appveyor であらかじめ対応を準備しておくイメージです。
ただあまり反応が、よろしくないので別に急いでません。
WIP の PRはなげてもいいかもしれませんが。

**Comment by m-tmatma** [comment]
[cmake の visual studio 対応](https://cmake.org/cmake/help/git-stage/generator/Visual%20Studio%2016%202019.html) は [3.14](https://gitlab.kitware.com/cmake/cmake/issues/18689) で入るみたい。

appveyor には [CMake 3.13.3](https://www.appveyor.com/docs/windows-images-software/#tools) がインストールされている。

visual studio 2019 は おそらく [4/2 までにリリースされそう](https://www.softantenna.com/wp/software/visual-studio-2019-on-april-2/)

**Comment by m-tmatma** [comment]
https://github.com/Microsoft/vswhere/wiki/Find-MSBuild によると
vs2019 から MSbuild のパスはメジャーバージョンのかわりに Current を使うようになるらしい。

`C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Current\Bin\MSBuild.exe`

**Comment by m-tmatma** [comment]
Visual Studio 2019 RC をインストールする方法
https://rksoftware.hatenablog.com/entry/2019/02/28/210734

**Comment by m-tmatma** [comment]
タイトル変更

**Comment by m-tmatma** [comment]
https://github.com/sakura-editor/sakura/pull/832

**Comment by m-tmatma** [comment]
https://github.com/appveyor/ci/milestone/143
に https://github.com/appveyor/ci/issues/2907 が設定されている。

**Comment by m-tmatma** [comment]
## Azure Pipelines

https://docs.microsoft.com/ja-jp/azure/devops/pipelines/agents/hosted?view=azure-devops
では `Visual Studio 2019 Preview on Windows Server 2019 (windows-2019)` となっている。

- https://github.com/Microsoft/azure-pipelines-image-generation
- https://github.com/Microsoft/azure-pipelines-image-generation/blob/master/images/win/Vs2019-Server2019-Readme.md

## Appveyor

CMake 3.14 への更新
https://github.com/appveyor/ci/issues/2891

Visual Studio 2019 への更新
https://github.com/appveyor/ci/issues/2907

**Comment by m-tmatma** [comment]
#931 を登録した。

**Comment by berryzplus** [comment]
#938 の検証結果 https://ci.appveyor.com/project/sakuraeditor/sakura/builds/24972147

現在 vs2017 で 6ビルド 走らせているので、
単純に多重化すると12ビルド走ることになります。

甘めに見て1ビルドあたり5分程度かかるので12ビルドだと1時間を超えてしまいます。
パラレルに実行数を増やせる Azure PipeLines では問題になりませんが、
Appveyorでは「どのビルドを走らせるか？」を精査する必要がありそうです。

この issue とは直接関係なさそうですが、
MinGW向けを Azure PipeLines で走らせる方法（≒Appveyorから外す方法）の模索も、
ぼちぼち始めておいたほうがよい気がしてきました。

CI環境のチューニングは楽しいんですが、アプリ的には何にも変わらないのがジレンマです...orz

**Comment by m-tmatma** [comment]
> 甘めに見て1ビルドあたり5分程度かかるので12ビルドだと1時間を超えてしまいます。
> パラレルに実行数を増やせる Azure PipeLines では問題になりませんが、

- appveyor では VS2017 のみでいいと考えています。
- Azure PipeLines では VS2017 と VS2019 を走らせるつもりです。
- ver 2.5.0 のタイミングで Azure PipeLines  の VS2019 ビルドをリリースするようにしたいと思ってます。

**Comment by m-tmatma** [comment]
最初は appveyor で VS2019 を走らせようと思ってましたが、
Azure PipeLines が使えるようになってきたので、appveyor はとりあえず VS2017のままで
いいと考えています。

**Comment by m-tmatma** [comment]
> CI環境のチューニングは楽しいんですが、アプリ的には何にも変わらないのがジレンマです...orz

キュリオシティ・ドリヴンという考え方があります。
https://eshima.info/archives/2015/06/curiositydriven.php

楽しいことはいいことです。

**Comment by berryzplus** [comment]
既に対応してるので閉じてしまいます。
