### ISSUE TITLE
ラベルを使いませんか?

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#70]
ラベルを使いませんか?
http://azunobu.hatenablog.com/entry/2015/09/22/143811

**Comment by kobake** [comment]
個人的には付けても付けなくてもどちらでも良いくらいの運用で良いかなーと思っています。

将来的には重要な Issue が分かりやすいようにラベル付けることは考えています。

**Comment by m-tmatma** [comment]
x64 を作ってみました。
https://github.com/sakura-editor/sakura/labels/x64

**Comment by kobake** [comment]
デフォルトで入っている使わなそうなラベルを削除しました。
必要なものだけ随時追加していくようにしましょう。

**Comment by m-tmatma** [comment]
label `license` を足しませんか?

**Comment by m-tmatma** [comment]
label `installer` を足しませんか?

**Comment by kobake** [comment]
必要と判断したラベルは好きに足してしまって良いです。事後申告で。
後から煩雑になってきたな～と感じるタイミングがあったらそのときに突っ込みます。

迷いがあるようなものがあれば事前相談くらいの感じで良いかと。

**Comment by kobake** [comment]
めちゃくちゃ増やしましたね。目がチカチカしません？

**Comment by m-tmatma** [comment]
フィルタリングしやすいかと

**Comment by m-tmatma** [comment]
さらに　CI (appveyor 関連) も足しました。

**Comment by kobake** [comment]
CI 追加は良いと思います。
他ラベルについては今はノーコメントで。

ラベル多すぎるとラベル選ぶときに迷うというデメリットがあります。

**Comment by KENCHjp** [comment]
GitHubの習慣なのかもしれませんが、ちかちかするぐらいいろんな話がごっちゃにポストされてるのもどうかなって思っとります、純粋にここには、sakura.exeの話題だけになればあまりLabelでちかちかしなくて、たとえば、Installの話は、
https://github.com/sakura-editor/installer/issues
こっちにいれればここでは話さなくていいんじゃねとか。
Web運用系の話は、
https://github.com/sakura-editor/sakura-editor.github.io/issues
こっちじゃねとか。
ただあっちこっち見ないといけなくなるのでしょうかねそうすると。
一覧でみるにはここに全部書いてあって、適切にLabelがついててふるいにかけられるほうがいいかもしれませんが、今のところ気づいた人がちまちまLabelつけてても廻る範囲かなって思います。

**Comment by kobake** [comment]
あ、すみません、installer については sakura 側に統合されたのでリポジトリは消しちゃうつもりでしたが単に消し忘れです。
作業効率を考えて web と bregexp 以外のリポジトリは sakura に集約しちゃう方針なのです。

**Comment by kobake** [comment]
自分の考えとしては、今の時期は移行直後なので例外として issues ポコポコ立ってますが、平常運転時にはそこまで様々なカテゴリの話が乱立しないと思っています。出てくるのはだいたいバグ報告か機能追加でしょう。それ以上細かい粒度のラベリングは不要と考えています。

CI は別軸なので残すの良いと思いますが、management 的なラベルに吸収するくらいでも良いと思っています。

**Comment by KENCHjp** [comment]
@kobake さんへ、なるほどです。
このあたり使い分けとかまだ探り探りなので、吸収させていただきますです。

**Comment by kobake** [comment]
とりあえずラベルは既に運用開始されているのでこの Issue の Close 条件はほぼほぼ満たされていると思います。

が、この Issue を Close したとして、今後の「こういうラベル追加しました」みたいなちょっとした連絡はどこに書くのが適切ですかね。ラベル追加に限らずちょっとした連絡全般を書く場について。

いくつか案は出しておきますが、もっと良い案あればください。

- (案1) この Issue を残し続ける … ずっと残り続ける Issue は嫌。そもそも本来の Issue の用途と違う。
- (案2) Team Discussion で連絡する … Team 所属外の人に情報が見えないのは微妙。できる限り情報はオープンにしたい。
- (案3) OSDNフォーラムで連絡する … せっかく開発者コミュニケーションが GitHub に集約されつつあるのに OSDN 側に場を分散するのはちょっと嫌。
- (案4) [Slack](https://sakura-editor-slack.herokuapp.com/) で連絡する … Slack 参加者以外に伝わらないのは微妙だが、一応誰でも参加できる場ではある。
- (案5) 諸連絡用のリポジトリを作って例外的にそこの Issues を連絡掲示板的用途として使う … あんまりそういうの見たことないですが。sakura リポジトリの Issues を汚すよりはマシ。
- (案X) 他、もっと良い案あればください。

ちなみにこれが「仕事」であれば僕は (案4) を採用します。

**Comment by KENCHjp** [comment]
Slackって後から参加しても過去にさかのぼれるでしたっけ。
Team Discussionは役割がかぶりますよねぇ。同じ理由でOSDNはもうエンドユーザとの情報交換にしぼったほうがいいきがしています（あっちの会議室の開発管理フォーラム消してもいいかなと、開発メンバーもOSDNにアカウント無い人もいますし）
通知って意味なら、Notificationsに表示される何かであればなんでも良い気がしてるのですが、そもそも未読を０にしない人もいるみたいだし。。。
Issueはやっぱりそこに的があると当てたくなるのが性（サガ）なので、消したいですよね。
うちの会社メンバー（仕事場がバラバラ）だと、チーム共通のグランドルール掲示板（ポータルRedmineだったり、客先だとExcelだったりします)でWhat's Newお知らせ＆MLへメール流すです。

掲示板っていうとここだとWikiっすかね、Wikiページの更新をウォッチしてNotificationsとかに表示されるといいのかな。
Issueって運用系ってあまり混ざらない方がいいのかなってのも同意です。

**Comment by k-takata** [comment]
> Slackって後から参加しても過去にさかのぼれるでしたっけ。

無料だと遡れる期間だか件数だかに制限があります。

**Comment by kobake** [comment]
Discord も良さそうです。Slack ライクなインターフェースのオープンなチャット場。
↓は試しに作ってみたサクラエディタチャンネルです。
https://discord.gg/MTWB4ut
名前だけ入力すれば即入室可能。追加でメールアドレスとパスワードを登録するとスマホアプリからも操作可能。Slack よりも参入ハードル低そう。

ログは無期限保存の模様。情報源は reddit ですが。
https://www.reddit.com/r/discordapp/comments/6vu7mz/for_how_long_are_chat_logs_saved/

Gitter はちょっと触ってみたのですが個人的には画面がゴチャゴチャしていて初見としてはちょっと抵抗ありました。慣れの問題だと思いますが。

**Comment by KENCHjp** [comment]
Slack引っ越しですかね？
Discordでもいいかもしれませんが、さすがにおなか一杯気味なので、
情報交換専用リポジトリ作ってでIssueで通知でもいいかなぁなんて。
名前は、ryouzanpakuとかtoranoanaとかtreasureboxでもいいですが、べたにinformationっすかね。

**Comment by kobake** [comment]
Discord はあくまでもひとつの検討材料としての実験場です。

リポジトリでやるとしたら名前は
`information`
`forum`
`discussion`
あたりですかねぇ

**Comment by kobake** [comment]
今話している本題ではないのですが、ちょっとしたつぶやきの場としてチャットは運用続けていきたいと思っています（今は Slack ですが Discord のほうが良さそうであればそっちに引っ越しも検討）

**Comment by KENCHjp** [comment]
はい、この前はチャットで助かりましたのであったほうがうれしいです。

**Comment by KageShiron** [comment]
Team Discussionは一般公開できないのか・・・

Slackはかなりクローズドなので、Discordの方がマシだとは思います。
なんか、もっと簡単な(ROMや通りすがりの人にも優しい)チャットツールの選択肢はないものか・・・

**Comment by kobake** [comment]
すみません、もともとの Issue の本題から逸れすぎたので別 Issue を立てました。
本 Issue はラベルの話ということで運用が始まった以上は帰着したのでクローズします。

掲示板・チャットの運用についての話は以下 Issue に場を移しましょう。

- 管理・運用向け掲示板の運用場所の検討 #142
- チャット運用場所の検討 #143
