### ISSUE TITLE
インストーラで「SAKURA EditorでGrep」メニューの追加 にショートカットがない

### ISSUE THREAD

**Issue by takke** [sakura-editor/sakura#703]
新規にインストールしてみたところ、下記のように `「SAKURA EditorでGrep」メニューの追加` の後ろに (&G) のようなショートカットが付いていないのがちょっぴり気になりました。

![2018-12-14_10h24_51](https://user-images.githubusercontent.com/73930/49977880-608a1800-ff8b-11e8-9fb7-40b9bef10d21.png)

- 試したインストーラ
  - https://ci.appveyor.com/project/sakuraeditor/sakura/branch/master/job/yxavla3ydrwhoa7t/artifacts
- 関連Issue
  - https://github.com/sakura-editor/sakura/issues/410
- 環境
  - Windows 10 Pro 18.03 英語版 (←日本語設定に変えたのであまり関係ないと思いますが) / VMware

**Comment by takke** [comment]
実際にその右クリックメニューにも付いてなかったです。

![2018-12-14_10h35_35](https://user-images.githubusercontent.com/73930/49978110-51579a00-ff8c-11e8-9f95-d1be078dd67b.png)

「SAKURA Editorで開く」には付いてるので付けたほうがいいのかなぁ、と思いました。

![2018-12-14_10h36_20](https://user-images.githubusercontent.com/73930/49978096-3c7b0680-ff8c-11e8-8d0b-0e8459bc2bd6.png)

**Comment by KENCHjp** [comment]
キーはGがいいでしょうか。

**Comment by ds14050** [comment]
G の文字があるのだから (G) を付加する必要はありませんが、そうしたいですか？

**Comment by takke** [comment]
従来との統一感で言えば
「SAKURA &Editor で開く」メニューの追加
ではなく
「SAKURA Editor で開く」メニューの追加(&E)
になっているので (G) を付加するほうがいいのかなと思いました。

**Comment by ds14050** [comment]
そうしたいのですね。

リソースを英語にしたときに `File(&F)` みたいなメニューにしてしまって、日本人はそれが当たり前だと思っているのですが、他では実はそうではないので指摘が入って `&File` に修正したという経緯が過去にあったように記憶しています。

(G) に違和感がないようなので、日本人にはやはりそちらの方が馴染むのかもしれませんね。選んでそうすることに問題はありません。

**Comment by berryzplus** [comment]
日本語版しか使わない人から見たら、
途中の文字に振られていても気付かないんじゃないかと思いました。

せっかく作業するなら後付けの「(G)」が良いと思います。

`Git For Windows` の `Git Bash Here` にアクセスキー振られてないことが何気に衝撃でした。

**Comment by berryzplus** [comment]
> 日本語は、末尾に「(&G)」、英語は「&Grep」

それでいいです。

**Comment by m-tmatma** [comment]
#705 を作成しました。

**Comment by takke** [comment]
確認しました。
下記の通りいい感じなので閉じておきます。
ありがとうございました。

- 日本語版Windows10
![2018-12-15_17h44_07](https://user-images.githubusercontent.com/73930/50041147-679c4d80-0093-11e9-97be-6001246ee820.png)
![2018-12-15_17h44_55](https://user-images.githubusercontent.com/73930/50041149-6d922e80-0093-11e9-9a23-cc0d8b4c0c1c.png)

- 英語版Windows10 (Gキー押下で該当項目が反応することを確認済み)
![2018-12-15_17h39_24](https://user-images.githubusercontent.com/73930/50041141-54897d80-0093-11e9-9e44-7b0352170986.png)
![2018-12-15_17h40_12](https://user-images.githubusercontent.com/73930/50041143-581d0480-0093-11e9-864c-6cd7a8f2b80f.png)
