### ISSUE TITLE
ファイルツリーからファイルツリー設定を開いた後に閉じてファイルツリーも閉じるとエディタじゃないウィンドウに切り替わる

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#708]
# 手順
- メニューの検索からファイルツリーを選ぶ
- 設定ボタンを押してファイルツリー設定を開く
- ファイルツリー設定画面を閉じる
- ファイルツリーを閉じる
- 閉じる前に背面にエディタのウィンドウが表示されていても、それではないウィンドウに切り替わる

ファイルツリーがノンモーダル表示なのが関係しているんでしょうか？

**Comment by berryzplus** [comment]
#1649 と同件ですが、向こうのほうがより具体的に事象を説明できているように思いますので、こちらを閉じておきます。
