### ISSUE TITLE
GSTR_APPNAME の実際の値が変更されても GSTR_APPNAME を使用しているソースの再コンパイルが走らないようにする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#709]
`2.4.0.0-dev` のバージョンを導入する前の準備として
GSTR_APPNAME をマクロから関数に変える。

GSTR_APPNAME はマクロで定義されていて、いろんなソースコードから呼ばれている。
このため GSTR_APPNAME に appveyor の変数を元に値を変える対応をすると
commit のたびに githash.h が毎回更新されて、余計なビルドが走るようになってしまう。

このため GSTR_APPNAME の値を更新してもリンクだけが走るようにして、再コンパイルが
走らないようにする。

関連:  #685

**Comment by berryzplus** [comment]
こんな感じの実装イメージであってます？

```c++
// 元の定義 /sakura_core/config/app_constants.h
//#define GSTR_APPNAME    (_GSTR_APPNAME_(_T))

// 関数宣言を追加して定義をすり替える
const TCHAR* GetAppName( void );
#define GSTR_APPNAME    GetAppName()

// 実体を別ファイルcppに書いておけば、中身が変わってもリンクするだけでＯＫ
const TCHAR* GetAppName( void )
{
	return _GSTR_APPNAME_( _T );
}
```

変更前は `TCHAR[]` の文字列リテラルなんで `const TCHAR*` だと意味が変わります。
`GSTR_APPNAME`に関して、文字列リテラルの特性を活かしたコードはないようなので、
変更して問題ないと思います。

`GSTR_APPNAME` を「関数名」に変えたいって話だったら、チェックするのがめんどいので(ry

あとは、実行時に関数呼出をおこなうことによるオーバーヘッドをどう捉えるかなのかな。

**Comment by m-tmatma** [comment]
> GSTR_APPNAME を「関数名」に変えたいって話だったら、チェックするのがめんどいので(ry

確かに手間ですね。

> あとは、実行時に関数呼出をおこなうことによるオーバーヘッドをどう捉えるかなのかな。

目的は GSTR_APPNAME の定義が、githash.h に依存することになっても再コンパイルが
走らないようにすることなので、関数でなくても、グローバル変数を参照するように
するのでもいいですね。

こんな感じ?

どっかの cpp ファイル (WinMain.cpp など)


```
#define _GSTR_APPNAME_(TYPE)  _APP_NAME_(TYPE) _APP_NAME_2_(TYPE) _APP_NAME_3_(TYPE)

const TCHAR g_szGStrAppName[]  = (_GSTR_APPNAME_(_T)   );
const CHAR  g_szGStrAppNameA[] = (_GSTR_APPNAME_(ATEXT));
const WCHAR g_szGStrAppNameW[] = (_GSTR_APPNAME_(LTEXT));
```

app_constants.h


```
extern const TCHAR g_szGStrAppName[];
extern const CHAR  g_szGStrAppNameA[];
extern const WCHAR g_szGStrAppNameW[];

#define GSTR_APPNAME    g_szGStrAppName
#define GSTR_APPNAME_A  g_szGStrAppNameA
#define GSTR_APPNAME_W  g_szGStrAppNameW
```

**Comment by m-tmatma** [comment]
タイトルを目的に合わせて修正しました。

**Comment by m-tmatma** [comment]
> 目的は GSTR_APPNAME の定義が、githash.h に依存することになっても再コンパイルが
> 走らないようにすることなので、関数でなくても、グローバル変数を参照するように
> するのでもいいですね。

#710 を投げました。
