### ISSUE TITLE
sakura/sakura_core/Funccode_x.hsrc での定義値の間違いを検出できる仕組みを検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#736]
sakura/sakura_core/Funccode_x.hsrc での定義値の間違いを検出できる仕組みを検討する

https://github.com/sakura-editor/sakura/pull/718#issuecomment-450465690

> F_COPYDIRPATH の定義値がまずいみたいです。
> F_COPYDIRPATH = 32820 なのでメニュー項目に追加されないみたいです。

https://github.com/sakura-editor/sakura/pull/718#issuecomment-450515598

> > **F_COPYDIRPATH の定義値がまずいみたいです。**
> 
> おおお、知らなかったです。メニュー項目のIDは、`F_MENU_FIRST` 以上、`F_MENU_NOT_USED_FIRST` 未満にする必要があるんですね。デバッグビルドだと自動的に検出してくれると良いですねぇ。

**Comment by m-tmatma** [comment]
理想は HeaderMake でヘッダを生成するときに自動で検出してコンパイルエラーにしたい。
あるいは googletest で単体テストを書いて、appveyor で失敗させるでもいい。

**Comment by berryzplus** [comment]
この issue って初めて見たんですけど、必要ですかね？

ここにある説明を理解できる人には要らん機能だと思います。
https://github.com/sakura-editor/sakura/blob/17bcab72eac7647cd8b7424db92aa4f87b9aff97/sakura_core/Funccode_x.hsrc#L10-L14

説明があっても、理解しようと思って読まなきゃ分からんこともあります。

「気付かなかった」を素直に認めて、今度やるときに頭の片隅においておけばよい話だと思います。

というわけで、閉じてしまいます。
