### ISSUE TITLE
トップディレクトリのファイルを整理する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#740]
トップディレクトリのファイル数が多くなってきたので、整理する

https://github.com/sakura-editor/sakura/pull/826#issuecomment-479873527

> > もっと理想を言えば、appveyor と共通で利用するバッチ類を `ci` ディレクトリに、appveyor のものを `ci/appveyor` ディレクトリに
> 
> まあ、ぼちぼちと考えます。

**Comment by kazasaku** [comment]
一旦ここにもまとめておきます。次の通り移動・編集を行いました。
- #1630
    - appveyor.md → ci/build-batchfiles.md
    - azure-pipelines.md → ci/azure-pipelines/azure-pipelines.md
    - ci-build.md → ci/build-envvars.md
- #1654 
    - unittest.md → tests/unittests.md

このほか、以下に示すファイル移動を予定しています
- addDoxygenFileComment.bat → 廃止
    - 内容が `python addDoxygenFileComment.py %~dp0/sakura_core` だけで、必要性を感じませんでした。
- addDoxygenFileComment.md → tools/addDoxygenFileComment.md
- addDoxygenFileComment.py → tools/addDoxygenFileComment.py
- create-big-file.md → tools/create-big-file.md
- create-big-file.py → tools/create-big-file.py
- remove-redundant-blank-lines.md → tools/remoe-redundant-blank-lines.md
- remove-redundant-blank-lines.py → tools/remoe-redundant-blank-lines.py

**Comment by berryzplus** [comment]
> このほか、以下に示すファイル移動を予定しています
> 
> * addDoxygenFileComment.bat → 廃止
>   
>   * 内容が `python addDoxygenFileComment.py %~dp0/sakura_core` だけで、必要性を感じませんでした。
> * addDoxygenFileComment.md → tools/addDoxygenFileComment.md
> * addDoxygenFileComment.py → tools/addDoxygenFileComment.py
> * create-big-file.md → tools/create-big-file.md
> * create-big-file.py → tools/create-big-file.py
> * remove-redundant-blank-lines.md → tools/remoe-redundant-blank-lines.md
> * remove-redundant-blank-lines.py → tools/remoe-redundant-blank-lines.py

ツール系のpythonスクリプトをtoolsフォルダに入れるのは良いと思います。

tools配下に各ツールごとのフォルダを切るか切らないかを悩んでいました。

あと、pyファイルを移動するときに出る SonarCloud 警告（Bugsレベル）をどうするか。
  - ファイルを触るなら修正するのが「筋」です。
  - ファイルを修正するならテストを用意するのが「筋」です。

  そんなことやってると配置換えできない気がするので、どこかで妥協するんだろうな、と思っていますが。

**Comment by kazasaku** [comment]
> tools配下に各ツールごとのフォルダを切るか切らないかを悩んでいました。
> あと、pyファイルを移動するときに出る SonarCloud 警告（Bugsレベル）をどうするか。

今のところフォルダは切らないつもりでいます。

検証用リポジトリを作成して SonarScan を実行してみましたが、Bugs **タイプ** の issue は検出されませんでした。
Code Smell タイプのものは大半が「関数・変数の名称がコーディング規約に違反している」ことへの指摘でした。
https://github.com/kazasaku/sakura-local/pull/2#issuecomment-832430002

**Comment by berryzplus** [comment]
> 検証用リポジトリを作成して SonarScan を実行してみましたが、Bugs **タイプ** の issue は検出されませんでした。

すみません、勘違いだったようです。
https://sonarcloud.io/project/issues?id=sakura-editor_sakura&languages=py&resolved=false&types=CODE_SMELL

CodeSmells129件なので、CやHTMLと比べると全然たいしたことないですが、どっかで対応しないといけない気はします。

**Comment by kazasaku** [comment]
過去のやり取りを見ていくうち、 remove-redundant-blank-lines は CodeFactor の無効化した警告に対応するために用意されたものであることがわかりました。
1. #719 空行の削除対応を実施（この時に空行を削除するスクリプトを作成）。
2. #724 前回対応時に実施しなかったものを対応しようとした（→可読性を悪化させる変更だったため同意を得られず）。
3. #728 閉じ波括弧直前の空行も対象に加え、実際に除去した。
4. #959 CodeFactor による空白・空行の警告を無効化した。

この経緯から、このスクリプトはもはや不要と言えるような気がします。

**Comment by berryzplus** [comment]
しまった。ツール名.mdじゃなくてreadme.mdのほうが都合が良さそうっす。

**Comment by kazasaku** [comment]
改めて見たら、途中から会話が全然噛み合っていないように見えてショックでした。

## 現時点での考え
1. 無くても良いスクリプト・バッチは削除して、保守対象を削減したいです。
2. 移動は対象のCodeSmell対応が終わってから一括で行います。
3. フォルダ分けはファイル移動PRにて階層と名称を例示した上で改めて確認を取ります。

`addDoxygenFileComment.bat`と、remove-redundant-blank-linesはこの第1項より削除したいものとしてカテゴライズされています。

**Comment by kazasaku** [comment]
続行不可能と判断し廃案とします。

**Comment by berryzplus** [comment]
トップディレクトリにディレクトリが多いのが気になりだしたので re-open します。

現時点でトップに存在するディレクトリについて「その気になれば削除できるか？」の観点で「○/×」付けてみました。

|ディレクトリ名|削除できる？|説明|
|--|--|--|
|.github|×|GitHub Actionsのワークフローが入っている|
|ci|○|CIで使うツールや説明が入っている|
|externals|×|プロジェクト外のリソースが入っている|
|HeaderMake|○|ビルドツール HeaderMake が入っている|
|help|×|HTMLヘルプのソースが入っている|
|installer|×|インストーラーのソースが入っている|
|resource|○|アイコンやビットマップなど、プログラムに埋め込むファイルが入っている|
|sakura|○|MSVCのプロジェクトファイルが入っている|
|sakura_core|×|プログラムソースが入っている|
|sakura_lang_en_US|○|英語リソースが入っている|
|sakura_lang_zh_CN|○|中国語リソースが入っている|
|tests|○|テストが入っている|
|tools|×|ツール類が入っている|
|vcx-props|○|Visual Studioのマルチバージョン対応に使うファイルが入っている|

実際の削除検討はディレクトリ別に sub-issue を起こすのがよいと思います。

**Comment by berryzplus** [comment]
ディレクトリレベルの整理について、なんとなく方向性が見えてきたので
ファイルレベルについても「その気になれば削除できそう」をissue化しておきます。

**Comment by berryzplus** [comment]
やり切ったのでクローズします。
