### ISSUE TITLE
grep で 除外ファイル、除外フォルダが効かない

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#743]
grep で 除外ファイル、除外フォルダが効かない

~~通常のビルドしたバイナリ単体だと、うまく動作するが、~~
~~インストーラでインストールした環境だとうまく除外フィルタが機能しない。~~

## 再現手順 (2019/01/03 更新)

1. sakura.exe のコマンドライン引数にファイルパスを指定して起動する
2. メニューから grep を選ぶ
3. `条件` に検索キーワードを、指定して、`フォルダ` に検索フォルダを指定して検索する。

**Comment by m-tmatma** [comment]
1. サクラエディタをアンインストール
2. サクラエディタをインストール
3. 起動一発目に除外条件を全く変えずに grep

で発生するみたいです。

**Comment by m-tmatma** [comment]
一回 grep した後、再度 grep する場合には発生しません。
初回がまずいみたいです。

**Comment by beru** [comment]
なんだか再現性が微妙ですね。こちらでアンインストールしてからインストールしましたが再現させる事が出来ませんでした。

アンインストールしても `%appdata%/sakura/sakura.ini` ファイルは削除されないので手動で削除してから試しても同じでした。

検索対象の適当なダミーのファイルやフォルダをzipで圧縮したものと、Grep条件入力のスクリーンショットを用意していただけると、他の人も同じ条件で再現確認がしやすいので助かります。

他に再現する人が現れたりとか、原因が既に判明した、とかであれば不要だと思います。

**Comment by m-tmatma** [comment]
以下で再現するのがわかりました。

1. サクラエディタをインストーラでインストールする
2. サクラエディタに txt ファイルを関連付けている状態にする
3. **既存のテキストファイル (例えばデスクトップにおいたファイルなど)をダブルクリックして開く**
4. メニューから grep を選ぶ
5. `条件`(検索キーワードという意味です)、`フォルダ`を設定して grep を行う。

※ `除外ファイル`、`除外フォルダ`は変更してもしなくても関係ないみたいです。
※ 通常のビルドしたバイナリ単体で試すときは、直接 exe をダブルクリックして開いていました。
※ インストールしたバイナリでも直接 exe をダブルクリックして開いた場合は発生しませんでした。

**Comment by beru** [comment]
これから再度確認しますが、アンインストールしてからインストールというのは必須な手順なのでしょうか？
設定ファイルを削除しても同等なのではないかと思いますが、ユーザー寄りの手順にしているのでしょうか。。

**Comment by beru** [comment]
こちらでも再現しました。インストール直後の起動とかは関係ないようです。

**Comment by m-tmatma** [comment]
更に確認しましたが、インストールバージョンでなくてもいいです。
既存のテキストファイルを引数に指定して `sakura.exe` を起動するだけで発生します。

**Comment by beru** [comment]
`CViewCommander::Command_GREP` で今のEditViewにGrep結果を表示**しない**場合に、`CControlTray::DoGrepCreateWindow` を呼び出しますが、そこでコマンドライン文字列を作る処理でローカル変数 `cmWorkExcludeFile` と `cmWorkExcludeFolder` に設定した除外ファイルと除外フォルダの情報が使われていないのが原因のようです。

**Comment by beru** [comment]
コマンドラインオプションに関する修正は berryzplus さんの要望で取り消していますね。
自分がレビューしましたがこの問題が出る事に気づけませんでした。

現状の ファイルパターンの仕様の枠内で何とか対応する (https://github.com/sakura-editor/sakura/pull/403#issuecomment-425632933) か、もしくはやっぱりコマンドラインオプションを復活させるか、自分が思い浮かぶのはその二手くらいです。

**Comment by m-tmatma** [comment]
> もしくはやっぱりコマンドラインオプションを復活させるか、自分が思い浮かぶのはその二手くらいです。

#750 で 9fe9fa9e4295dac384be83d91d730fc60fc1a013 を revert した PR を作成してみました。
これで期待通り動作しています。

**Comment by m-tmatma** [comment]
説明欄に再現手順を記載しました。

**Comment by m-tmatma** [comment]
閉じます

**Comment by m-tmatma** [comment]
revert したので再オープンする

**Comment by m-tmatma** [comment]
通常、十分遭遇する可能性のある不具合なので、リリースブロッカーという認識です。
すぐにリリースしない可能性は高いですが。

**Comment by berryzplus** [comment]
残件は #769 に引き継ぎ・・・。

**Comment by m-tmatma** [comment]
#753 で #750 を revert していて、対策をしていないので現状発生する。

**Comment by m-tmatma** [comment]
↑ grep は動いている?
grep 置換は問題があるのは確認。(32f03fd8dcf3986770b27bb7ebe38bd1235ab304)

**Comment by m-tmatma** [comment]
#1210 で対処済み
