### ISSUE TITLE
appveyor.yml のコマンド実行処理をリファクタリングする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#748]
appveyor.yml のコマンド実行処理をリファクタリングする

現状 appveyor.yml でコマンド実行する場合、以下のように `cmd: >-` という記述を使っている。

https://github.com/sakura-editor/sakura/blob/6622eb9f860b3798748bd92ae1035a66fec427f3/appveyor.yml#L19-L25

しかし、この記述だと、コマンドとコマンドの間に空行がないと正しく動かない。

https://github.com/sakura-editor/sandbox/pull/12
で試したところによると単にコマンドを一行ずつ書いて、`-` で始まるようにしたら
見やすいし書きやすいので  `cmd: >-` の表記をやめる。

また `-`  を使うとバッチファイルを呼ぶときにいちいち call を使わなくてもいいのでシンプルになる。

**Comment by m-tmatma** [comment]
#747 の後にやろうと思います。

**Comment by m-tmatma** [comment]
以下のようなイメージ

```
build_script: 
    - checkEncoding.bat
    - build-all.bat %PLATFORM% %CONFIGURATION%
    - tests\build-and-test.bat %PLATFORM% %CONFIGURATION%
```

**Comment by ds14050** [comment]
これは手近な appveyor.yml から抜き出したものですが、こういう書き方もあります。

```
test_script:
- cmd: |
    "%SAKURA_TEST%" --gtest_list_tests
    "%SAKURA_TEST%" | tests\test_result_filter_tell_AppVeyor.bat
```

>また - を使うとバッチファイルを呼ぶときにいちいち call を使わなくてもいいのでシンプルになる。

バッチファイルに書いたのと同じ一連のコマンドとして実行されるか、独立したインタープリタで実行されるかという違いみたいです。AppVeyor にしかわからないことですが。

**Comment by m-tmatma** [comment]
`cmd: >-` にも以下のメリットがあった。

以下のように if 文で複数行にまたがる処理を実行したい場合

```
if not defined SECURE_VAR1 (
   echo SECURE_VAR1 is not defined
)
echo test
```

`cmd: >-` を使うと if 文で括弧を使える。

```
- cmd: >-
    if not defined SECURE_VAR1 (
       echo SECURE_VAR1 is not defined
    )

    echo test
```

これは空行がコマンドの区切りと認識されるので、複数行にまたがるコマンドを記述できる
ということみたい。

`- cmd: |` だと各行が1コマンドと扱われるので、複数行にまたがるコマンドを記述できない。
これは単に `-' でも同様

**Comment by m-tmatma** [comment]
↑ 訂正

**Comment by m-tmatma** [comment]
`- cmd: |` を使って #751 を作成しました。

**Comment by ds14050** [comment]
call を省きたいという理由で `-` を並べてもいいと思うんです。先のコメントの後半はそういうつもりで言及しました。

「コマンドとコマンドの間に空行がないと正しく動かない」という制限を感じつつ `cmd: >-` と書いていると知って、そうではない書き方があるということを書いたつもりです。

あとは全体が何行になるかということからバランスをとったり、気分次第でも、自由に書けばいいんです。

YAML について調べたときは「[プログラマーのための YAML 入門 (初級編)](https://magazine.rubyist.net/articles/0009/0009-YAML.html)」が一番わかりやすかったと記憶しています。

**Comment by m-tmatma** [comment]
> call を省きたいという理由で `-` を並べてもいいと思うんです。先のコメントの後半はそういうつもりで言及しました。

最初は '-' の方がいいかな? と思ってたんですが、
https://github.com/sakura-editor/sandbox/pull/12 でいろいろ試して
`- cmd: |` だとバッチファイルで書くのと全く同じにかけて便利なのでそうしました。

**Comment by ds14050** [comment]
他人を忖度するのではなく自分でそう決めたということを知って安心しました。
