### ISSUE TITLE
grep/grep 置換で除外ファイル、除外フォルダを指定できるようにする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#75]
## grep/grep 置換で除外ファイル、除外フォルダを指定できるようにする

https://sakura-editor.github.io/help/HLP000067.html 
(旧: http://sakura-editor.sourceforge.net/htmlhelp2/HLP000067.html)

には以下のように書いてある。

- ファイルパターンの先頭に!を付ける(例: !*.obj)と，そのパターンに当たるファイルをGrep対象から外します。
- ファイルパターンの先頭に#を付ける(例: #*.svn)と、そのパターンに当たるサブフォルダをGrep対象から外します。(sakura:2.1.0.0以降)
- 指定位置にかかわらず除外指定は検索指定より優先されます． 
- 何も指定しない場合は、「*.*」を指定したことになります。

しかし、ほとんどの人はこの機能の存在を知らない。(私も含めて)

簡単に、除外指定できるようにする。

## 以下サンプル (位置はずれている部分がありますが、サンプルなのでご容赦ください)

![grep-dialog](https://user-images.githubusercontent.com/5567450/41192507-a18b2244-6c39-11e8-8d66-8a01c97e3feb.png)

![grep-dialog-en](https://user-images.githubusercontent.com/5567450/41192509-a4fc9552-6c39-11e8-9cc1-79e03c15dd81.png)

## 以下 grep ダイアログのリソースのみ変えた差分

[diff.txt](https://github.com/sakura-editor/sakura/files/2087015/diff.txt)

**Comment by m-tmatma** [comment]
対応するのは 64bit 対応終わった後かな

**Comment by m-tmatma** [comment]
とりあえず PR #403 を投げました。
日本語版のダイアログのスクリーンショットに関しては PR 中の HTML ヘルプの中に
png で入っています。

**Comment by m-tmatma** [comment]
除外フォルダでは `.git;.svn;.vs` 、除外ファイルでは、`*.exe;*.obj;*.pdb;*.ilk`
とか初期値で入れておくと便利かなとも思いますが、
現状では空の場合に、何も初期値は入れていません。

**Comment by m-tmatma** [comment]
> 日本語版のダイアログのスクリーンショットに関しては PR 中の HTML ヘルプの中に
> png で入っています。

↓ 以下です。チケットに張っているのとほぼ変わりません。

- https://github.com/sakura-editor/sakura/blob/21f3c327211aa69a38c468a09f660ec217d61cf8/help/sakura/_RESOURCE/images/Grep.png
- https://github.com/sakura-editor/sakura/blob/21f3c327211aa69a38c468a09f660ec217d61cf8/help/sakura/_RESOURCE/images/GrepReplace.png

**Comment by m-tmatma** [comment]
> 対応するのは 64bit 対応終わった後かな

まだ時間かかりそうなので対応してみた。

**Comment by m-tmatma** [comment]
> 除外フォルダでは .git;.svn;.vs 、除外ファイルでは、*.exe;*.obj;*.pdb;*.ilk
> とか初期値で入れておくと便利かなとも思いますが、
> 現状では空の場合に、何も初期値は入れていません。

最新の PR で入れました。
初期値として、何を入れたらいいかありましたら、コメントお願いします。

**Comment by ds14050** [comment]
除外したいものの条件を考えてみました。

1.  興味や編集の対象ではない。

ことがまず前提としてあって、そのうえで、

2-1. 頻繁に検索結果にまぎれこんでノイズになる。
2-2. ファイル数が多く検索時間を無駄に費やす。

ことが理由になるのかな、と。

.git は .git/objects のファイル数が問題になり(2-2)、.svn は中に含まれるワーキングコピーの複製が頻繁に検索にマッチすることと(2-1)、やはりファイルの多さが問題になる(2-2)のだと思いました。

1 にはユーザーから隠されていて関知しないファイルや多くのバイナリファイルが当てはまります。

.git や .svn はプログラムが管理する領域で、基本的にユーザーの興味の対象ではありません。

.exe、.obj、.pdb といったバイナリファイルを除外したいのは、内部のテキスト部分が関数名による GREP にマッチしてしまうからではないかと思いました。

----
desktop.ini はどうかと一応考えてみましたが、2 の条件に該当しませんでした。

**Comment by beru** [comment]
拡張子の `.bak` も除外の初期値に入っていると良いなと思います。
WinMergeで編集して保存するとバックアップファイルが作られて grep に引っかかることが多いので。

**Comment by beru** [comment]
フィルタ文字列のプリセット機能って無いみたいですね。
自分のニーズに合わせて用意してメモしておいたのをコピペすれば良いのかもしれませんが。

履歴機能はあるみたいなので長年同じ環境で使っていればあまり困る事は無いのかもしれませんね。

**Comment by m-tmatma** [comment]
> 1 にはユーザーから隠されていて関知しないファイルや多くのバイナリファイルが当てはまります。

別件とはなりまりますが、隠しフォルダおよびバイナリファイルを無視するというオプションが
あってもいいのかもしれません。

隠しフォルダはすぐに判定は可能だと思いますが、
バイナリファイルかどうかの判定は調査がいりますが。

**Comment by arigayas** [comment]
バイナリファイルといえば画像ファイルも入りますよね？
`.png` `.gif` `.jpeg` `.jpg` `,ico` `.bmp`
がパッと思い付きました。

あと`.exe` 関連で言えば `.dll` も含まれると思います。

**Comment by beru** [comment]
思い付きですが、 `.gitignore` に書かれているのを除外できる機能があると便利かもしれません。

**Comment by KENCHjp** [comment]
こちらもクローズ？

**Comment by m-tmatma** [comment]
これは残件ありで中途半端な状態です

**Comment by KENCHjp** [comment]
了解です。

**Comment by berryzplus** [comment]
残件の issue を close したのでこれも閉じておきます。
