### ISSUE TITLE
sakura.exe と sakura_lang_en_US.dll の生成フォルダをソリューションフォルダをもとに決める

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#76]
sakura.exe と sakura_lang_en_US.dll の生成フォルダはプロジェクトのフォルダをもとに決められるが、
ソリューションフォルダをもとに決める。

プロジェクトのフォルダをもとに成果物が生成されるので、sakura_lang_en_US.dll が別のフォルダに
作成されるので英語リソースのテストをするのに手間がかかる。

**Comment by m-tmatma** [comment]
#72 の後に対応する

**Comment by berryzplus** [comment]
OutDirを変更するならIntDirもソリューション基準にしませんか？

appveyorには影響ありませんし、気分的なものなのでどちらでもいいですがこんな感じ。
<IntDir>$(SolutionDir)$(Configuration)\$(ProjectName).obj\</IntDir> 

あと、出力先にプロジェクト名＋.dll(exe)で出したい場合、OutputFileは省略可能です。
行を削ってしまえば、今後メンテしなくてよくなるメリットがあります。

**Comment by kobake** [comment]
新規プロジェクトを作ったときのデフォルト設定が今の (Visual Studio Community 2017 の) 推奨なのかな、と思っています。

試しに新規プロジェクト作ってみましたが、以下のようになりました。

- Output Directory: `$(SolutionDir)$(Platform)\$(Configuration)\`
- Intermediate Directory: `$(Platform)\$(Configuration)\`
- Output File: `$(OutDir)$(TargetName)$(TargetExt)`

**Comment by m-tmatma** [comment]
> あと、出力先にプロジェクト名＋.dll(exe)で出したい場合、OutputFileは省略可能です。

sakura_lang_en_US はプロジェクト名 ≠ ファイル名なのでそこも変えたほうがいいと思います。
ただその場合別の PR、チケット にしたほうがいいと思います。

**Comment by m-tmatma** [comment]
> Output Directory: $(SolutionDir)$(Platform)\$(Configuration)\
> Intermediate Directory: $(Platform)\$(Configuration)\
> Output File: $(OutDir)$(TargetName)$(TargetExt)

そうですね。x64 対応するときに、$(Platform) が入っていると
x86 と x64 でフォルダ構成が対象になるので扱いやすいと思います。

Intermediate Directory はかぶらなければどこに作ってもいいと思います。

HeaderMake.exe と MakefileMake.exe の生成場所はソリューション直下ではなく
各ビルド構成毎にちがうフォルダにしたいと思います。


#24 で見直してもいいと思います。

**Comment by berryzplus** [comment]
> sakura_lang_en_US はプロジェクト名 ≠ ファイル名なのでそこも変えたほうがいいと思います。

ボケてました。

**Comment by kobake** [comment]
#80 でざっくり対応中です。
Configuration 名が今は Win32 になっているのですが、appveyor.yml に合わせて x86 に変更します？（とくにこだわりはないです）

**Comment by kobake** [comment]
> Configuration 名が今は Win32 になっているのですが、appveyor.yml に合わせて x86 に変更します？（とくにこだわりはないです）

Platform 名の間違いでした

**Comment by m-tmatma** [comment]
#79 がマージされた。

**Comment by m-tmatma** [comment]
> sakura_lang_en_US はプロジェクト名 ≠ ファイル名なのでそこも変えたほうがいいと思います。

#82 で対応
