### ISSUE TITLE
ユーザーの導線を増やす

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#760]
## 要望機能
ユーザーの導線を増やすように何か対策を入れるのはどうでしょうか？（management-forum 向きな話題かもしれないです）

例えば下記のような方法でです。

- github の Issue へのリンクを用意する
#757 で Issue の template が追加されたので思いつきました。github のアカウントが必要なので、確認メッセージボックス表示を出してから飛ぶようにした方が良いかもしれないですね。

- twitter の [ハッシュタグを指定してツイートできるリンクを設定する](http://kokushin.hatenablog.com/entry/2016/04/19/%E3%83%8F%E3%83%83%E3%82%B7%E3%83%A5%E3%82%BF%E3%82%B0%E3%82%92%E6%8C%87%E5%AE%9A%E3%81%97%E3%81%A6%E3%83%84%E3%82%A4%E3%83%BC%E3%83%88%E3%81%A7%E3%81%8D%E3%82%8B%E3%83%AA%E3%83%B3%E3%82%AF%E3%82%92)
githubよりtwitterの方が一般ユーザーには馴染み深いでしょうか。

- サクラエディタふぁんくらぶ へのリンクを載せた wiki ページへのリンクを用意

余計だと思われかねない項目ではあるので少し抵抗感は有りますね。悲観的な想像すると、導線経由で来る要望がこの機能の廃止しかなかったら徒労に終わってしまいますが…。

**Comment by KageShiron** [comment]
VSCodeのフィードバックボタンみたいな機能はあっても良さそうですね。
<img width="523" alt="image" src="https://user-images.githubusercontent.com/17571233/50834672-0caafd00-1398-11e9-9139-19d64ce54ffb.png">

我々が作るとついエンジニアよりになってしまいますが、twitterで検索して見ると小説書きとかテキストビューアとか色々な使い方してる人がいるのでいろんな感想ご意見を集めたい

**Comment by berryzplus** [comment]
似たような issue が過去にあった気がして過去ログ漁ってきました・・・ 

#74 (ちょっと違う

「visual stdio の send feedbackってカッコいいですよね（パクりませんか？」という書き込みをどこかでした覚えがあるんですが見つかりませんでした。

某掲示板が今以上に過疎るのはなんだか寂しいです。

**Comment by berryzplus** [comment]
興味ある人も居ないようなので閉じておきます。

必要あれば新たにissue立ててください。
