### ISSUE TITLE
WinMainのコメントが実態とズレてる件をどうにかしたい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#762]
動作にはなんの影響もないんですが、前からかなり気になっております。

このコメントと実動作が合ってない、ということを言ってます。

https://github.com/sakura-editor/sakura/blob/b3cc5ae82306ed76f9b5536c1e05260c769a8ef5/sakura_core/_main/WinMain.cpp#L66-L73

書かれていることを表にまとめるとこうなります。

起動順 | どうなる？ | 作成するProcessインスタンス
-- | -- | --
1つ目 | コントロールプロセスとなる | CControlProcessクラス
2つ目以降 | エディタプロセスとなる | CNormalProcessクラス

実体はどうかというと、こうなっています。

パラメータ | どうなる？ | 作成するProcessインスタンス
-- | -- | --
`-NOWIN`指定がある | コントロールプロセスとなる | CControlProcessクラス
`-NOWIN`指定がない | エディタプロセスとなる | CNormalProcessクラス

`-NOWIN`指定とは、コントロールプロセスを起動するための[コマンドラインオプション](https://sakura-editor.github.io/help/HLP000109.html)です。
つまり、1つ目のプロセスでも `-NOWIN`指定がなければエディタプロセスになります。

これだけのためにPRするのもなんか違う気がするので、問題提起だけにしときます。

**Comment by beru** [comment]
そのコメントは [r54](https://sourceforge.net/p/sakura-editor/code/54) で追加されてました。
`CProcessFactory` とかが作られる前の昔々の実装はコメントのようになっていたのかもしれないですね。

**Comment by m-tmatma** [comment]
#764 を投げました。

**Comment by berryzplus** [comment]
#763 でダラダラ書いてるんですけど、
たぶん、-NOWIN か -WQ が指定されている場合にコントロールプロセスを起動する感じにするのがいいのではないかと思っています。

-WQはコントロールプロセスの保存機構を使ってsakura.iniを出力します。

段階的にやらんとぐちゃぐちゃしそうなので #764 はそのまま GO でいいと思ってます。
