### ISSUE TITLE
grep の除外指定の残件

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#768]
#758 の残件
https://github.com/sakura-editor/sakura/pull/758#pullrequestreview-192009333

**Comment by berryzplus** [comment]
> 個人的には、「除外ファイル＆除外フォルダ」の問題としての残課題が３件あると思ってます。
> ・空白を含むパターンを指定できるようにする
>  ・ファイル、除外ファイル、除外フォルダすべて指定した場合のGrep実行前振り分け
>  ・ファイル、除外ファイル、除外フォルダすべて指定した場合のGrepダイアログ表示前振り分け

#769 を投げました。

**Comment by berryzplus** [comment]
#1210 のマージにより、残件は消化されたと思うので閉じておきます。
