### ISSUE TITLE
ツールバーの「Grepアイコン」と「アウトライン解析アイコン」の間に区切り線を入れるのはどうでしょうか？

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#772]
## 要望機能
検索関連とアウトライン解析の機能って別のような気がするので
間に区切り線を入れるのはいかがでしょうか？

## スクリーンショット
![image](https://user-images.githubusercontent.com/11251874/51424962-05e27c80-1c19-11e9-815b-3cf19e07317e.png)

カスタマイズしたスクリーンショット
![image](https://user-images.githubusercontent.com/11251874/51424985-61146f00-1c19-11e9-86f8-d4667743cc61.png)

**Comment by m-tmatma** [comment]
#773 で実装してみました。

**Comment by arigayas** [comment]
実装が速過ぎて笑いましたww

**Comment by berryzplus** [comment]
「ダメだぁっ！」とは思ってないんですが要りますか？

ここは設定でどうとでもなる部分なので、勝手に変えたらええやん、と思う部分と、
設定ファイルの値も使いやすくなるように少しずつ見直していったほうがいいのかな、と思う部分があって「やりたい人がやったらええんちゃう？（他人任せ」な感じになってます。

PRを見たら分かるかも知れないんですが、ツールバーに区切り線を入れるときの決まりみたいなものがあって、それをペペッとコピペしただけの内容です。実装的に問題がないであろうことはほぼ間違いありません。

いまんとこ、この変更が要るのかどうかが落ちてなくてとどまってる感じです。
もうちょい考えたいです。

**Comment by m-tmatma** [comment]
設定で変えられる部分でも、デフォルトで対応してると
わかりやすいと、思います。

**Comment by arigayas** [comment]
> 設定で変えられる部分でも、デフォルトで対応してると
> わかりやすいと、思います。

同意です。

区切り線があると「グループが違う」って視覚的にわかるので、
デフォルトで明示されているのが良いと思い提案しました。

**Comment by m-tmatma** [comment]
> #773 で実装してみました。

マージしました。

**Comment by arigayas** [comment]
ローカルにてビルドした物が要望通りになりました。
作業していただきありがとうございました。
