### ISSUE TITLE
PowerShellによる圧縮/解凍を廃止したい

### ISSUE THREAD

**Issue by KageShiron** [sakura-editor/sakura#788]
PowerShellによる圧縮/解凍機能を廃止する

7zを必須でインストールしてもらう。または、7zをレポジトリに同梱する。

## 理由
#787 に関で、アーカイブへのファイル追加と、ファイルリストからのアーカイブ作成をしたい。PowerShellで同様のことを実装するのが面倒。

7zのみ対応にしたほうが今後も様々な手間を回避できると思います。

**Comment by berryzplus** [comment]
この提案を前に進めたくなってきました。

## 支持する理由

1. appveyor上で、7zip は [cinst 7zip](https://chocolatey.org/packages/7zip.install) されています。
2. azure pipelines上で、7zip は cinst 7zip されています。
3. 開発者がローカルで cinst 7zip するのが「大変か？」というと[そうでもありません](https://chocolatey.org/docs/installation#installing-chocolatey)。

**Comment by berryzplus** [comment]
この提案を前に進めたくなってきました。

## 支持する理由

1. appveyor上で、7zip は [cinst 7zip](https://chocolatey.org/packages/7zip.install) されています。
2. azure pipelines上で、7zip は cinst 7zip されています。
3. 開発者がローカルで cinst 7zip するのが「大変か？」というと[そうでもありません](https://chocolatey.org/docs/installation#installing-chocolatey)。

**Comment by berryzplus** [comment]
興味ある人も居ないようなので閉じておきます。

必要あれば新たにissue立ててください。
