### ISSUE TITLE
googletest による単体テストで MingW のビルド構成で pacman の導入を検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#799]
## 要望機能

googletest による単体テストで MingW のビルド構成で pacman の導入を検討する

https://github.com/msys2/msys2/wiki/Using-packages
https://mikoto2000.blogspot.com/2018/08/msys2-google-test.html

## 元ネタ

https://github.com/sakura-editor/sakura/pull/796#issuecomment-471139825

> MinGW側のgoogletest取得をpacman利用に変えたいです。
> pacmanはmsys2のパッケージ管理機構で、NuGet同様ビルド済みライブラリを取得できる仕組みです。

**Comment by berryzplus** [comment]
既に導入済みなので閉じてしまいます。

ちなみにぼく個人としては、パッケージ利用はやめたほうがいい、と考えを改めています。

詳細は後日、MinGW版テスト用Makefileの導入提案で説明します。
