### ISSUE TITLE
 MinGW によるビルド手順を文章化する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#800]
## 要望機能

MinGW によるビルド手順を文章化する

以下に少し説明があるが、もっと詳しく書いたほうがよい。
https://github.com/sakura-editor/sakura/blob/a722f9c86f2860606b3f9e7dc79bb169294cfaea/build.md#MinGW-w64-%E3%83%93%E3%83%AB%E3%83%89

**Comment by berryzplus** [comment]
目的が

**Comment by berryzplus** [comment]
ドキュメントの目的が違うような気がします。

手順としてはコマンドプロンプトから build-all MinGW Debug で、それ以上の詳細はありません。これで分からなければ諦めてもらった方が良いです。

前提となる想定ビルド環境msys2について一切触れられてない(これ書いた時点から変わっているのが反映されていない) のが気になっています。

前提条件を整えないと、手順があっても動かないので。

**Comment by m-tmatma** [comment]
ビルド手順というか、環境構築法です。

**Comment by berryzplus** [comment]
とりあえず最新の環境構築方法っす。

1. powershellの管理者コンソールを立ち上げます。
1. 以下のコマンドで `chocolatey` をインストールします。  
`Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))`
1. 以下のコマンドで `msys2` をインストールします。  
`choco install msys2 --params "/InstallDir:C:\msys64"`
1. powershellの管理者コンソールを閉じます。
1. cmdプロンプトを立ち上げます。
1. 以下のコマンドで mingw-w64 をインストールします。  
`C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-make"`
1. 以下のコマンドで googletestのパッケージ をインストールします。  
`C:\msys64\usr\bin\bash --login -c "pacman -S --noconfirm mingw-w64-x86_64-gtest"`

**Comment by k-takata** [comment]
いくつか思う点としては、

* chocolatey を既にインストールしている人は `choco` でインストールするのが楽かもしれないが、そうでない人にとっては、公式のインストーラーを使った方が分かりやすいのではないか。
* MSYS2 をインストールした後は、コマンドプロンプトではなく MSYS2 の端末から `pacman` を実行した方が楽ではないか。
* MSYS2 をインストールした後は、`pacman -Syuu` を実行してパッケージを更新した方がよいのではないか。(choco だとそこまでやってくれる？)
* サクラエディタは 64bit 版は Alpha 版という扱いなのに、MinGW は 64bit 版を前提とするのか。
  - 64bit/32bit 版両方をインストールするなら [pacboy コマンド](https://qiita.com/k-takata/items/04d252c464986d6280a6)が楽。

といったところでしょうか。

**Comment by berryzplus** [comment]
意外と `ドスタンダードな方法で msys2 の MinGW-w64 を入れてもらえばオッケーっす。手順詳細はそのへんググってください。gtest のパッケージも入れといてください。` みたいなざっくり手順のほうがよいのかも知れないです。




> * chocolatey を既にインストールしている人は `choco` でインストールするのが楽かもしれないが、そうでない人にとっては、公式のインストーラーを使った方が分かりやすいのではないか。

書いてるコマンドラインは公式に書いてあるやつです。
細かく書かずに「公式見て」のが親切なのかも・・・。

> * MSYS2 をインストールした後は、コマンドプロンプトではなく MSYS2 の端末から `pacman` を実行した方が楽ではないか。

書いたコマンドラインは前に azure pipelines で使ってたコマンドラインです。
よく見るとそういう手順になってるっす・・・。

> * MSYS2 をインストールした後は、`pacman -Syuu` を実行してパッケージを更新した方がよいのではないか。(choco だとそこまでやってくれる？)

やってくれます。逆に、パッケージ更新を無効にするオプションがあるっぽいです。
https://chocolatey.org/packages/msys2

> * サクラエディタは 64bit 版は Alpha 版という扱いなのに、MinGW は 64bit 版を前提とするのか。
>   * 64bit/32bit 版両方をインストールするなら [pacboy コマンド](https://qiita.com/k-takata/items/04d252c464986d6280a6)が楽。

デフォルトインストールの `MinGW-w64` の gcc が x86_64 向けコードを生成するからです。
`実は x86 向けコードも生成できまっせ` なんてことは知らないことにしています。
ぶっちゃけ `MinGWが Alpha 扱いなのは x86_64 だからじゃない` っす。

**Comment by k-takata** [comment]
> 意外と `ドスタンダードな方法で msys2 の MinGW-w64 を入れてもらえばオッケーっす。手順詳細はそのへんググってください。gtest のパッケージも入れといてください。` みたいなざっくり手順のほうがよいのかも知れないです。

それも1つの手でしょう。

> デフォルトインストールの `MinGW-w64` の gcc が x86_64 向けコードを生成するからです。

そんなことはありません。
`C:\msys64\mingw32\bin\gcc.exe` (`mingw-w64-i686-gcc`) は i686 向けのコードを生成しますし、`C:\msys64\mingw64\bin\gcc.exe` (`mingw-w64-x86_64-gcc`) は x86_64 向けのコードを生成します。MSYS2 としてはどちらがデフォルトということはなく、ビルドするターゲットに合わせたシェルを使うように言っています。そうすれば適切な版の gcc にパスが通ります。

で、`mingw-w64-i686-gcc` と `mingw-w64-x86_64-gcc` の両方を同時にインストールするなら、
```
pacman -S mingw-w64-i686-gcc mingw-w64-x86_64-gcc
```
のようなやたら長いコマンドを入力する必要はなく、
```
pacboy -S gcc:m
```
でできます。64bit/32bit の gcc, make, gtest を全部入れるなら、
```
pacboy -S gcc:m make:m gtest:m
```
です。(gcc-libs は gcc を入れれば入ります。)

**Comment by berryzplus** [comment]
> そんなことはありません。

ふむ、ではそういうことで。

`MinGW-w64` の `gcc` なので当然 `x86_64` がデフォルトだろう、という程度でそう書きました。
実はあんましこだわらないです。
