### ISSUE TITLE
外部モジュール(bregonig.dll とか)の管理方法を検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#81]
外部モジュール(bregonig.dll とか)の管理方法を検討する

**Comment by berryzplus** [comment]
bregonig.dll は appveyor から wget できそうな気がします。

migemoとかppaはどうなのかよく分かっていませんが、
SakuraDownと似た方式にすればかき集めてこれるんではないかと。

リストがあるならそれを元に wget してもいいかも知れません。

**Comment by k-takata** [comment]
bregonigは https://bitbucket.org/k_takata/bregonig/downloads/ に置いてあるものが公式バイナリです。
appveyorには置いていません。（appveyorのartifactsは、半年しか保持されなくなった点にも注意。）

**Comment by m-tmatma** [comment]
> bregonig.dll は appveyor から wget できそうな気がします。

外部ソースに依存すると外部ソースが利用できない or できなくなると
インストーラを作成できなくなるので外部モジュール管理用のリポジトリを作って
git submodule で参照したらいいのではないかと思ってます。

**Comment by m-tmatma** [comment]
最初は、外部ファイルを展開して登録するのを
想定していたので、git submodule で登録するのが
いいと思ったが、zip のまま登録するのなら
直コミットでもいい気がします。

**Comment by KENCHjp** [comment]
外部ファイルは展開して直コミットでいいかなと思っているのですが、いかがでしょう？
管理用リポジトリを外に作メリットがあまり見出せなくて。
複数プロジェクトにまたがって使うとかあれば別なのかもしれませんが。

**Comment by KENCHjp** [comment]
#41 の下の方に話題がありますが、sinst_src.zipも全部展開たほうがいいかなと、keywordも差分管理したほうがいいかとおもってます。

**Comment by m-tmatma** [comment]
> sinst_src.zipも全部展開たほうがいいかなと、keywordも差分管理したほうがいいかとおもってます。

sinst_src.zip は自前のプロジェクトで管理するものだし、
テキストファイルなので展開して登録でいいと思うのですが、

外部ファイルに関しては、元ファイルをアーカイブのまま登録して
展開して使うとタイムスタンプを保持できてメリットが
あるんじゃないかと思います。

DLL などのバイナリファイルだとタイムスタンプって
結構意味があると思います。

**Comment by KENCHjp** [comment]
@m-tmatma さん
>展開して使うとタイムスタンプを保持できてメリットが
>あるんじゃないかと思います。

なるほどです。コミッターというかリソース管理って観点だとそれがいいですね。
単純に運用チーム目線だと、チェックアウトしてすぐパッケージ作成にとりかかえるのを、いったん解凍とか入るなって思ったのですが、まぁバッチ化してればあまり問題ないかもですね。

**Comment by berryzplus** [comment]
コミットログみた感じだと、
zip化した理由はタイムスタンプがずれるのを嫌ったため
と読み取れます。

そういえば TortoiseSVN だとcheckout時のタイムスタンプは現在時刻になったような。
時代が変わってますねぇ・・・
sinst_src.zip は展開してコミットでいいと思います。
現状どうなってるかウォッチできてません。

> zip のまま登録するのなら直コミットでもいい気がします。

展開するなら submodule で参照するカタチになりますが、
サブモジュールは自動更新にならなかったり面倒くさそうだなぁ・・・とGit詳しくない人が言うｗ

appveyor は 7zip の利用実績があるようなので、zipの展開処理に不安はないと思っています。
とくに理由がなければ外部の配布物は、展開せずにコミットがいいような気がします。

**Comment by m-tmatma** [comment]
> そういえば TortoiseSVN だとcheckout時のタイムスタンプは現在時刻になったような。
> 時代が変わってますねぇ・・・

クライアント側の設定で
`use-commit-times = yes`
を設定すればチェックアウトしたときにタイムスタンプを維持してくれます。

ただそれだとクライアント側の設定に依存するので
以前 "svn:use-commit-times" というプロパティを設定されたファイルに対して
チェックアウトしたときに、コミット時のタイムスタンプを維持する機能を
subversion に追加する patch を送ったことがあります。

https://groups.google.com/forum/#!topic/subversion-development/hWFQcN38n0M

このときは、提案が成功しなかったです。というか途中で断念したように思います。

**Comment by berryzplus** [comment]
> https://groups.google.com/forum/#!topic/subversion-development/hWFQcN38n0M
> このときは、提案が成功しなかったです。というか途中で断念したように思います。

こ、これは！・・・お疲れ様でした。

レビューコメントめちゃくちゃ読みづらいですね。
表示のされ方によるところも大きいと思うんですが、
そもそも何を言ってるのか分からない部分が多々あります。

ああ、英語読む気ないとかそういう話じゃないですよｗ

どうして欲しいか分からないレビューコメントは辛いですね。
反面教師と考えなきゃいけないのかな、と思います。

全然関係ないんですけど、 MinGW 向けツールのうち windres のための改造は、
本家GCC(MinGW64/MinGW32/CygWin)に還元したほうがよいような気がしています。
優先度は思いっきり低いんですが、精神的ハードルは思いっきり高いというやっかいな案件。

**Comment by k-takata** [comment]
> * ctags.exe

Exuberant Ctagsは更新されなくなって久しいですが、後継の[Universal Ctags](https://ctags.io/)の開発が進められています。Windows版のデイリービルドは以下で公開しています。
https://github.com/universal-ctags/ctags-win32
（Universal Ctagsの正式リリースはまだ出ていませんが。）

「更新があれば手動追加で良さそう」という点には同意ですが。

**Comment by m-tmatma** [comment]
> bregoni.dll

これはインストーラに入れときたいです。

理由は

- 既存のインストーラに含まれている
- 多くの人が正規表現を使う(と思う)

**Comment by KENCHjp** [comment]
＠KageShiron さんの「再配布すればよさそう」はインストーラーに含んで配るっていみじゃないのでしょうか？
ユーザーが任意にダウンロードしてもらうっていみじゃなくて。
ただバージョンアップを自動で追尾しなくてもいいのではって意味で。

**Comment by m-tmatma** [comment]
#133 で sinst_src.zip を展開して登録するようにしました。

**Comment by m-tmatma** [comment]
> ＠KageShiron  さんの「再配布すればよさそう」はインストーラーに含んで配るっていみじゃないのでしょうか？

「再配布」とあるからそうですね。

**Comment by KENCHjp** [comment]
>これはインストーラに入れときたいです。

これを私がふかよみしすぎたようです。
失礼しました。

**Comment by m-tmatma** [comment]
- #133: sinst_src.zip を展開して登録する
- #136: bregonig.dll のバイナリを追加する

**Comment by KENCHjp** [comment]
@KageShiron さんまとめて頂きましたが、確かにdiff.exeは入れたいですね。
ctags.exeと同じような感じでいけそうですかね？

**Comment by m-tmatma** [comment]
> @KageShiron さんまとめて頂きましたが、確かにdiff.exeは入れたいですね。
> ctags.exeと同じような感じでいけそうですかね？

入手先はありますか?

**Comment by KageShiron** [comment]
#477で止まってますね・・・
入手先が確定できれば、プルリク作ってみます

**Comment by KageShiron** [comment]
だんだんバッチが複雑になってきたので、もう展開するメリットのほうが大きい気がします。タイムスタンプについても、必要ならPEヘッダーのTimeDateStampを見ればいいのでは？と思ってます

**Comment by m-tmatma** [comment]
> だんだんバッチが複雑になってきたので、

バッチファイル分割すればいいのでは?

**Comment by berryzplus** [comment]
現状

No | 場所 | 説明 | 今はいってるもの
-- | -- | -- | -- 
1 | https://github.com/sakura-editor/sakura/tree/master/installer/externals | インストーラに同梱する外部リソース | bregonig, ctag
2 | https://github.com/sakura-editor/sakura/tree/master/externals | ビルド時に使う外部リソース | cppcheck, doxygen
3 | https://github.com/sakura-editor/sakura/tree/master/sakura_core/extmodule | 外部ライブラリをつかうための定義・実装 | bregonig, htmlhelp, migemo

3だけ種類が違うんだけど、全体把握には必要なはず。

**Comment by ds14050** [comment]
>だんだんバッチが複雑になってきたので、もう展開するメリットのほうが大きい気がします。

#630 「インストーラの同梱ファイルの調整」にも関係することですが、@KageShiron さんのために zipArtifacts.zip を書き直しています(嘘です)。

(特に目的を定めずに)書き直しているのは本当で、こんな感じになりました>https://github.com/sakura-editor/sakura/compare/master...ds14050:re_zA.bat

zipArtifacts.txt という３カラムの TSV ファイルで管理するので、バッチの読み書きは(デバッグする時以外は！)不要です。

**Comment by KageShiron** [comment]
展開したパターンのPRを作ろうとしてたものの、忙しくて時間が取れず💦
展開すればディレクトリごとコピーするだけなので、100行以上バッチを削除できて簡潔になると思ってます

余談ですが、Find-*系のバッチは↓にある%~$PATH:1みたいな変数展開で非常に簡潔に検索できそう・・・と気づきました
http://capm-network.com/?tag=Windows%E3%83%90%E3%83%83%E3%83%81%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E5%A4%89%E6%95%B0

動きそうならこちらも後でPR出す予定なものの、リアルがいそがし・・・😢
https://gist.github.com/KageShiron/137e436cc22096e21257a606b5e3a159

**Comment by ds14050** [comment]
>100行以上バッチを削除できて簡潔になると思ってます

簡潔さは大事です。いかに書かないかに頭を絞るべきなんです。すべてをコードで表現すればすべてがスペシャルケースとなり、最大限の自由とカオスと非線形に膨れあがる複雑さの前にプログラマは早晩敗北してしまいます。

**Comment by ds14050** [comment]
Find-*系のバッチは(マナー違反だとは思いますが)標準インストールパスを狙い撃ちにしています。PATH 環境変数は役に立たないでしょう。

**Comment by m-tmatma** [comment]
> zipArtifacts.txt という３カラムの TSV ファイルで管理するので、バッチの読み書きは(デバッグする時以外は！)不要です。

この新しいバッチをメンテするのが大変そうです。非常に難解です。

**Comment by ds14050** [comment]
>この新しいバッチをメンテするのが大変そうです。非常に難解です。

書いた自分はそうは思いませんが、そうですよねえ。それがビックリマークが付いている所以です。>「デバッグする時以外は！」

**Comment by ds14050** [comment]
zip ファイルをフォルダ扱いしてコピー元に指定できる機能なんてのもあってイチオシなんですけどね……(未練があるようだ)。

**Comment by ds14050** [comment]
最初の計画は「[new subroutine: Set_BASENAME](https://github.com/sakura-editor/sakura/commit/0e9198e0a23041b876a05c6982f8d7228eef0493)」だけでした。

**Comment by m-tmatma** [comment]
現在、バイナリを installer\externals に登録する形で運用している。

**Comment by m-tmatma** [comment]
> 現在、バイナリを installer\externals に登録する形で運用している。

現状これで運用していて問題出ていないのでクローズします。
何かあればチケット登録すればいいかと思います。
