### ISSUE TITLE
引数が 4つのバージョンの IsMailAddress の単体テストを追加する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#811]
## 要望機能

引数が 4つのバージョンの IsMailAddress の単体テストを追加する

https://github.com/sakura-editor/sakura/pull/808#discussion_r268408603

`単体テストを復活する事自体は良いと思いますが、試験している関数が offset 引数が無い方だけというのが気になりました。まぁでも間接的には試験している事になるし、offset 引数を指定した場合のテストのバリエーションは後から追加すれば良いのかもしれませんね。`

**Comment by ds14050** [comment]
他人事ではないので最低限ですがテストを用意してみました。>#823

**Comment by m-tmatma** [comment]
マージされたのでクローズ
