### ISSUE TITLE
和暦の出し方（覚書）

### ISSUE THREAD

**Issue by KENCHjp** [sakura-editor/sakura#827]
サクラエディタの日付の挿入で和暦を挿入する書式があるので試してみました。v2.3.2.0です。
[設定]-[共通設定]-[書式]-[日付書式]
デフォルトは、

yyyy'年'M'月'd'日('dddd')'

かな、[編集]-[挿入]-[日付挿入]すると、

2019年4月3日(水曜日)

と挿入されます。書式を、

yyyy'年('gg')'M'月'd'日('dddd')'

とすると、

2019年(西暦)4月3日(水曜日)

あれ？？？
ヘルプに
>gg 「平成」などの時代を示す文字列。ロケールの CAL_SERASTRING が使われます。
>日付がこの情報を持たないときは、無視されます。

とあるので何か設定が足りない模様。
Windows10の[コンパネ]-[地域]-[形式] 例のところの[追加の設定]ボタンおして「形式のカスタマイズ」の[日付]タブの[カレンダー]のところにカレンダーの種類ってのがあってそこに[西暦(日本語)」なる文字が。
![sakura1](https://user-images.githubusercontent.com/39618965/55443688-a4626500-55ee-11e9-966f-0f55e096afe4.png)

そこを和暦に変更。

![2](https://user-images.githubusercontent.com/39618965/55443689-a75d5580-55ee-11e9-86ed-7bdbffc4910d.png)

再度日付挿入すると、

31年(平成)4月3日(水曜日)

なんとか和暦表示されました。なんかまだよく理解できていないようなのですが、ググっても実装寄りの情報しか出てこないのでひとまず集めた情報Issueへ覚書しておきます。

**Comment by berryzplus** [comment]
C言語のロケールは実装依存の「枠」を提供する可能なんで、書いたコードが実際どう動くかはベースになってるライブラリに依存するんですよね。

サクラエディタの場合、Windows API(NLS)を直呼びしてるんで、本来はWindowsの設定を無視して任意の出力(和暦も)を得ることが出来るんですが、以下略。

話は変わりますが先日、新元号が発表された時、とあるライブラリにadding Japanese new eraってコミットが入って吹きました。

Win nlsがレイワに対応するのはいつかな…

**Comment by KENCHjp** [comment]
>Win nlsがレイワに対応するのはいつかな…

レジストリいじると今すぐでも対応できそうですが、
https://qiita.com/oruponu/items/cc75e19bca39985e64dc
次回のWindowsUpdateあたりで取り込まれるのかな。。。
これ先走りすぎて、元号のところに？？って出ちゃう不具合がでて元に戻ったってやつですね。

**Comment by berryzplus** [comment]
.NET 3.5以前(windows server2008相当)までは、和暦の表記はベタ書きになってたみたいですね。

.NET 4.0以降(windows7以降)ではOSのサービスパック（？）の一部として提供されるようになってて、.NET frameworkもそっちを参照するようになってるみたいです。（だからwin10の先走った更新で影響が出た。

新元号は、日本のIT業界から見ると windows2008server(.NET 3.5) をリプレースする口実になるかも知れない、という変な話・・・

こまかい新機能がどうの、って話には興味をもってくれないとしても、「新元号が出せません」といえばきっと食い付いてくれる。これぞ嘘も方便(ｷﾗﾝ

**Comment by KENCHjp** [comment]
覚書なのでクローズします。
