### ISSUE TITLE
SonarQube Cppcheck Plugin を調査する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#840]
## 要望機能
[SonarQube Cppcheck Plugin](https://github.com/SonarQubeCommunity/sonar-cppcheck) を調査する

関連: 

- #674
- #368
- https://github.com/sakura-editor/management-forum/issues/59

**Comment by m-tmatma** [comment]
メモ
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Code-checkers
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/Extending-the-code-analysis

**Comment by kazasaku** [comment]
sonar-cppcheckは、"SonarQube 6"で廃止されたAPIを使用しているため、古いSonarQubeでしか利用できないようです。
https://github.com/SonarQubeCommunity/sonar-cppcheck/issues/6#issuecomment-377563241

**Comment by berryzplus** [comment]
SonarQubeはサーバアプリの名前
SonarCloudはクラウドサービスの名前

いずれもSonarScannerというクライアントアプリが解析したデータを受信して結果表示を行うものです。
だから、同じだと思っていても間違いではないです。
まぁ、別モノなんですけど（笑

**Comment by kazasaku** [comment]
sonar-cxxだとcppcheckの結果を取り込めるそうですが、このプラグインはSonarCloudでは使えないっぽいです。
https://github.com/SonarOpenCommunity/sonar-cxx/wiki/sonar.cxx.cppcheck.reportPaths
https://github.com/SonarOpenCommunity/sonar-cxx/issues/1302

**Comment by berryzplus** [comment]
興味ある人も居ないようなので閉じておきます。

必要あれば新たにissue立ててください。
