### ISSUE TITLE
インストーラの内部の文章の句点を「，．」から「、。」に

### ISSUE THREAD

**Issue by arigayas** [sakura-editor/sakura#841]
### 使用したバージョン：sakura_install2-4-0-1699-x86.exe
「このソフトウェアは「テキストエディタ(共同開発版)」を改称したものです．
商用・非商用を問わず無償で利用できますが，ソースコードの著作権は各箇所を記述した人が留保しています．
このソフトウェアは無保証です．」

普段、句点に「．」を使っているのは、あまり見ないので違和感を覚えました。
あと上記の文以外では「。」を使っているので統一感がないのも違和感があります。
なので「。」を使うようにするのはいかがでしょうか？

## スクリーンショット
![image](https://user-images.githubusercontent.com/11251874/55724477-747bed00-5a46-11e9-9144-84e626ba7b2f.png)

**Comment by takke** [comment]
気になりますよね。新規ユーザーが最初に見る画面に違和感があるのはちょっと、と私も思います。
そのインストール前にみるであろう、Webサイトのトップは変えたので（ダウンロードページは未）、変えていいように思います。

バージョン情報の枠の中も同様の句読点なんですがそこはその性格的にあえて変えてないのかなと思いました。

**Comment by arigayas** [comment]
![image](https://user-images.githubusercontent.com/11251874/55726698-641a4100-5a4b-11e9-8676-1a1276ff9875.png)
「バージョン情報」の枠の中も同じ文章なんですね。

「インストーラ」の句点を「．」から「。」に変更されたら、
「バージョン情報」の枠の中の文章も変更されることを期待してしまいますね。

**Comment by takke** [comment]
お、中身も一緒なんですね。

**Comment by berryzplus** [comment]
異論ないっす。

これ形の変更であれば、簡単にレビュー通ると思いますよ。
反対する人がいたとしても、ぼくが気付けば approve しちゃうと思います。

何気に読点が「，」なのも気になるんですよね。
「著作権を留保します」とか「無保証です」とか、気になる点はたくさんあるんですよね。

著作権は、人権みたいなもので、主張しなくても当然に尊重されるべきものです。
「主張しなければ気にしなくていいよね」って発想は BLACK なので、ミルクぶっかけましょう。

無保証って言い方は、以前から気になっています。
「このソフトウェアを使用したことにより発生した損害に対して、開発者はいかなる責任も負いかねます。」を縮めて「無保証」と言ってるんでしょうが、だいぶ印象が違う気がします。

まー、細かく言い出すとキリ無いんですが、気付いたところから改善を試みていくのはアリなのかな～と思っています。

**Comment by arigayas** [comment]
> 何気に読点が「，」なのも気になるんですよね。

気が付いていなかったです。
読点を「、」に変更するissueを立てます？
それとも一緒に読点も「、」変更するようにタイトルを変更するのもアリだと思います。

**Comment by ds14050** [comment]
「あまり見ないから」が理由になると考えるのは視野が狭いだけですが、自分は「、。」派なので異論はありません。

**Comment by arigayas** [comment]
タイトルを変えました。

**Comment by berryzplus** [comment]
PR は権利だと思うので、ぼく的には「待ち」です。

**Comment by KENCHjp** [comment]
http://www2.chokai.ne.jp/~assoonas/UC408.HTML

この辺ですかね。

**Comment by berryzplus** [comment]
> http://www2.chokai.ne.jp/~assoonas/UC408.HTML
> 
> この辺ですかね。

見解が添えられてないのでなんとも言えんのですが、引用URLはは「読点の代わりにカンマを使っても良い」

**Comment by arigayas** [comment]
上記の文以外では「、。」を使っているので統一感がないのも違和感があるのですが、
それでもCloseなのでしょうか？

**Comment by berryzplus** [comment]
失礼バグった。

**Comment by arigayas** [comment]
びっくりしましたｗ

**Comment by berryzplus** [comment]
iphoneの操作ミスでcloseしちゃって、気付かないことが結構よくあるんです。
とりあえず代行でPR投げときますわ・・・。

**Comment by arigayas** [comment]
ありがとうございます。

**Comment by berryzplus** [comment]
#842 マージしました。

今回「変更ファイル２つ」としましたが、「インストーラで表示するものとまったく同じ文書を表示したい」の意図でリソースがコピられていると考えると、コピペではなくファイルを直接リソースに埋め込むのがいいんじゃないかな、と思っています。現物を埋め込む仕様にすれば更新忘れのリスクをなくせます。「標準メニュー（？）」に使ってる独自リソース定義の手法を使えば、「ファイルそのもの」をリソース化することが可能になります。プログラム側に手をいれないといかんのが実施にあたっての障害になるかな・・・。

句読点以外の変更については、いまいま気力がないので後の人に任せたいと思います。

**Comment by arigayas** [comment]
PR作業お疲れさまです。

### 確認したバージョン： sakura_install2-4-0-1765-x86.exe

インストーラの文章が変更されている事を確認しました！

![image](https://user-images.githubusercontent.com/11251874/56040589-b02df400-5d71-11e9-9aa5-05c3bd072368.png)

しかし、諸事情で 「バージョン情報」の文章が変更されているか確認は出来てません。


> 今回「変更ファイル２つ」としましたが、「インストーラで表示するものとまったく同じ文書を表示したい」の意図でリソースがコピられていると考えると、コピペではなくファイルを直接リソースに埋め込むのがいいんじゃないかな、と思っています。現物を埋め込む仕様にすれば更新忘れのリスクをなくせます。「標準メニュー（？）」に使ってる独自リソース定義の手法を使えば、「ファイルそのもの」をリソース化することが可能になります。プログラム側に手をいれないといかんのが実施にあたっての障害になるかな・・・。

変更するファイルを1つに統合？するissueは別に立ててやるのが妥当だと思うのでCloseしますね。
