### ISSUE TITLE
Win32 Release に LargeAddressAware が入っている理由を調べる

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#85]
Win32 Release に LargeAddressAware が入っている理由を調べる

- https://github.com/sakura-editor/sakura/blob/1633967231258415934b7705e8ca66d24807fdec/sakura/sakura.vcxproj#L75
- https://msdn.microsoft.com/ja-jp/library/wz223b1z.aspx
- https://github.com/sakura-editor/sakura/pull/84#discussion_r194255446

**Comment by kobake** [comment]
このへんで入ったみたいです。
05605204138f13ff7326a2c76e885539b3a4dce2
```
commit 05605204138f13ff7326a2c76e885539b3a4dce2
Author: uchi5537 <uchi5537@users.sourceforge.net>
Date:   2008-08-02 15:53:38 +0000

    Keep:リソースの整理等

    git-svn-id: https://svn.code.sf.net/p/sakura-editor/code/sakura/branches/unicode2@1423 f7ce1907-e4c7-47ca-9f76-12c87ed2c91c
```

**Comment by m-tmatma** [comment]
説明欄の3番めのリンクに関して Tips のページを作りました。

- https://github.com/sakura-editor/sakura/wiki/GitHub-Tips
- https://github.com/sakura-editor/sakura/wiki/GitHub-Tips:-レビューコメントに対するリンクを取得する方法

**Comment by berryzplus** [comment]
## 結論
入れるとメリットがあるフラグだから。

## 説明
既に書いてあるんですけど、このフラグを指定すると32bitの認識限界4GBまでのメモリを扱えるようになります。

32bitOSで動作させる分にはあまり意味のない指定ですが、
64bitOSで動作させる場合には 2GB を超える 32bit size_t のフル領域を扱えるようになるのでメリットがあります。
