### ISSUE TITLE
Vistaスタイルのファイルダイアログ使用時に名前を付けて保存の文字コードセット, 改行コード, BOM指定が有効に動作しない

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#873]
## バグ内容

Vistaスタイルのファイルダイアログ使用時に、名前を付けて保存の文字コードセット, 改行コード, BOMの指定を行っても反映がされない。

## 再現手順

元々文字エンコーディングがSJISのファイルを開いて、SJISでは記録できない文字を入れて保存しようとすると警告が発生する。名前を付けて保存で文字コードセットに UTF-8 を指定しても、保存時の警告が表示されてしまう。

## 再現頻度

毎回

## 環境情報
- OS バージョン

- サクラエディタバージョン

- PC情報

サクラエディタ   v2.4.0.1625 64bit dev Alpha Version
(GitHash 083f208d04e2305794deef05eba1abc2b111844c)
(GitURL https://github.com/sakura-editor/sakura.git)

      Compile Info: V_A641916 WPR WIN601/I800/C000/N601
      Last Modified: 2019/2/5 16:20:56

## スクリーンショット

![image](https://user-images.githubusercontent.com/1131125/56866608-22f7ca00-6a16-11e9-81a0-68af10f1dd31.png)

**Comment by berryzplus** [comment]
> beru self-assigned this Apr 28, 2019 

よろしくお願いします。

**Comment by beru** [comment]
#874 を Merge したので Close します。
