### ISSUE TITLE
SonarQube 対応を入れたが appveyor ビルドがこけている

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#878]
## バグ内容
#510, #674 で SonarQube 対応を入れたが appveyor ビルドがこけている

## 再現手順
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/24167955

**Comment by m-tmatma** [comment]
以下で環境変数 SONAR_QUBE_TOKEN で判断している。

https://github.com/sakura-editor/sakura/blob/30e020c13e44a064b3e9510f6f1f58095e713c48/build-sln.bat#L48-L54

appveyor の設定で SONAR_QUBE_TOKEN を定義していたので SonarQube の解析が走るが
azure pipelines とは違って、`choco install "msbuild-sonarqube-runner" -y` を実行していないので
解析に失敗する。

**Comment by m-tmatma** [comment]
appveyor の設定で SONAR_QUBE_TOKEN  等の環境変数の定義を削除して、
リビルドかけた。

https://ci.appveyor.com/project/sakuraeditor/sakura/builds/24168614

**Comment by m-tmatma** [comment]
これ azure pipelines 側でもあかん気がする。
SONAR_QUBE で切り替えたつもりだったが、実際には SONAR_QUBE_TOKEN で切り替えていた。
つまり、通常のビルドでも SonarQube が走る。

**Comment by berryzplus** [comment]
> これ azure pipelines 側でもあかん気がする。
> SONAR_QUBE で切り替えたつもりだったが、実際には SONAR_QUBE_TOKEN で切り替えていた。
> つまり、通常のビルドでも SonarQube が走る。

枝タスクのconditionでスケジュール実行かどうかを見ているから実害はないのでは？と思ったりするけど調べてみないと分からない雰囲気ですね。

**Comment by berryzplus** [comment]
build-wrapperがないからコケるのか。

**Comment by m-tmatma** [comment]
> > これ azure pipelines 側でもあかん気がする。
> > SONAR_QUBE で切り替えたつもりだったが、実際には SONAR_QUBE_TOKEN で切り替えていた。
> > つまり、通常のビルドでも SonarQube が走る。
> 
> 枝タスクのconditionでスケジュール実行かどうかを見ているから実害はないのでは？と思ったりするけど調べてみないと分からない雰囲気ですね。

azure pipelines の 設定で SONAR_QUBE_TOKEN は常に定義されているので
通常の VS2017 の JOB のビルド走った時に build-sln.bat を使ってビルドしているので
SonarQube の解析が走ってしまう。

Fork からの PR では SONAR_QUBE_TOKEN の値は無効なので SonarQube は走らないですが
master にマージされたビルドでは SONAR_QUBE_TOKEN  が有効なので通常の JOB で
SonarQube が走ります。

**Comment by m-tmatma** [comment]
#879 で修正 PR を送りました。

**Comment by m-tmatma** [comment]
> appveyor の設定で SONAR_QUBE_TOKEN 等の環境変数の定義を削除して、
> リビルドかけた。
> 
> https://ci.appveyor.com/project/sakuraeditor/sakura/builds/24168614

これはパスしました。

**Comment by m-tmatma** [comment]
#879 をマージしました。
