### ISSUE TITLE
 Azure Pipelines で EXEとInstallerのzipのmd5ファイルの生成に失敗している。

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#885]
## バグ内容
Azure Pipelines で EXEとInstallerのzipのmd5ファイルの生成に失敗している。
#829 で appveyor を対応したが、Azure Pipelines での生成に失敗している。

以下のエラーで失敗している。

```
find: '/v': No such file or directory
find: '/v': No such file or directory
find: 'MD5': No such file or directory
find: 'CertUtil': No such file or directory
find: '/v': No such file or directory
find: 'MD5': No such file or directory
find: '/v': No such file or directory
find: 'CertUtil': No such file or directory
```

## 再現手順
https://dev.azure.com/sakuraeditor/sakura/_build/results?buildId=303
など #829 以降の azure pipelines の VS2017  の JOB の `Zip files for artifacts` の step

## 再現頻度
100%

**Comment by berryzplus** [comment]
issue 立てありがとうございます。
「何故失敗しているか？」の心当たりはありますでしょうか？

エラーメッセージを見る限りでは「 for 文の usebackq オプションを付け忘れてコマンドラインが正しく解釈されていないなどの要因」が考えられますが、内容を理解してない人が調査するより分かっている人が原因調査するほうが解決に至るまでの時間を短縮できるように思います。

一切コード見てない奴がそれを書くなよ・・・というツッコミは後回し :smile:

**Comment by takke** [comment]
調べます。Windows Server 2016 で find コマンドがうまく動いていないような感じですね。

**Comment by takke** [comment]
azure-pipelines の `vs2017-win2016` イメージで `where find` してみると、
```
C:\Program Files\Git\usr\bin\find.exe
C:\Windows\System32\find.exe
```
ということで、git の find が使われてしまうのでエラーになっていました。

**Comment by m-tmatma** [comment]
#888 で対応された
