### ISSUE TITLE
VS2017 と VS2019 のどちらをビルドに使うか判定見直し

### ISSUE THREAD

**Issue by beru** [sakura-editor/sakura#889]
この対応なんかおかしいぞ・・・と思ったのでとりあえずコメントします。

何がおかしいか。

お題：vs2017とvs2019の両方をインストールしたマシンでビルドエラーになる。
　　↓
対策：vs2017のMsBuild.exeを探すようにバッチを改修すればよい。
　　↓
実態：vs2019のMsBuild.exeがある場合はvs2019のMsBuild.exeを使うように変更している。

・・・違うぞ。現状はvs2017でやるってことになってるのだから。
vs2019をインストールしていようとしていまいとvs2017を使うべき。（暴論

闇雲に「vs2019を使いたい」を認めないわけじゃなくて、
そういう使い方をしたいなら「その提案」があってしかるべきと言ってるだけ。

実際、vswhereにはvs2017のインストールパスを捜索せよ、と命じることができるわけで、
vs2019のvswhereにはvs2019のMsBuild.exeを捜索せよ、と命じることができるわけで。
※vswhereもアップグレードで機能強化された。

というわけで、使いたい人はvs2019を使えるように、を考慮した上で、
何も指定しなければ強制的にvs2017のMsBuild.exeを使うようなPRを投げようと思っております。

_Originally posted by @berryzplus in https://github.com/sakura-editor/sakura/pull/832#issuecomment-487710449_

**Comment by beru** [comment]
https://github.com/sakura-editor/sakura/pull/832#issuecomment-487934210

> 考えてるフローは以下のようなものです。
> 
> ```
> if 「vs2019を使いたいフラグ」が未定義:
>     vs2017のMsBuildを使う
> elif vs2019がインストールされている:
>     vs2019のMsBuildを使う
> elif vs2017がインストールされている:
>     vs2017のMsBuildを使う
> else:
>     ビルドしない、エラーとする
> ```

バッチファイルはちゃんと確認していないですが、

> if 「vs2019を使いたいフラグ」が未定義:
>     vs2017のMsBuildを使う

だと vs2017がインストールされてるかの確認が無いです。

先にVS2017以降のVSがインストールされてるかの確認を分けて記述する方がシンプルになるかもしれません。

> 現状、「vs2019だけをインストールしている場合」には `VS2019を使いたいフラグ` を定義しない限りビルドできませんが、それでいいんだっけ？と思ってPRを保留している感じです。

CLIからバッチ経由でビルドする場合の話だと思いますが（あまりちゃんと話を追えていない…）、実装されたバッチのように環境変数を参照するなりコマンドライン引数を見るなりで良いと思います。

VS2019を使いたいフラグというより latest を使うフラグの方が名前として良いかも知れないと思いました。

あとなんか色々バッチファイルの中で判定するより、vs2017でビルドするのと vs2019 でビルドするのでバッチファイル自体を別々にするのだといけないんだろうか…と思いました。

**Comment by berryzplus** [comment]
issue立てありがとうございます。

だいたいまとまってきたのでappveyorのビルド確認が終わり次第PRにしたいと思っています。

> あとなんか色々バッチファイルの中で判定するより、vs2017でビルドするのと vs2019 でビルドするのでバッチファイル自体を別々にするのだといけないんだろうか…と思いました。

CIに組み込んでビルドチェックをするためには、同じバッチを使いまわすほうが都合がいいんだと思います。この辺、任せっきりなのでよくわかっておりませんが、自分が環境組むとしたら使いまわす構成にすると思います。

> VS2019を使いたいフラグというより latest を使うフラグの方が名前として良いかも知れないと思いました。

`USE_LATEST_MSBUILD` に変えようと思ってます。

```
if マシンにvs2017がない OR 環境変数USE_LATEST_MSBUILDが定義されている:
    vswhereで最新版のvs付属msbuildを探して使う
```

MsBuildの探索ロジックは `tools/find-tools.md` に載っていたので、レビューのときはそっち見てイメージ掴んだほうがやりやすいのかな？と思っています。

**Comment by berryzplus** [comment]
#892 をマージしたので閉じます。
