### ISSUE TITLE
.editorconfig で指定する拡張子を増やす

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#890]
## 要望機能
.editorconfig で指定する拡張子を増やす

https://github.com/sakura-editor/sakura/blob/d74c8cfccfb6a7795d1bca0b5f245ba8e21bd813/.editorconfig

.md と .yml と .py は対象にしたい

**Comment by m-tmatma** [comment]
.md で　trim_trailing_whitespace は false にする
(markdown では末尾に空白を入れることで改行の意味になるので)

**Comment by berryzplus** [comment]
興味ある人も居ないようなので閉じておきます。

必要あれば新たにissue立ててください。
