### ISSUE TITLE
SDLチェックを有効にすることにより発見された変数の未初期化の問題を修正する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#896]
## バグ内容
SDLチェックを有効にすることにより発見された変数の未初期化の問題を修正する

https://github.com/sakura-editor/sakura/pull/893#issuecomment-488269229

https://ci.appveyor.com/project/sakuraeditor/sakura/builds/24222808 (7997c9b9631d780d1b43bbbf16579767a079c47b) で以下のようなビルドエラーになっている。

- c:\projects\sakura\sakura_core\cgrepagent.cpp(1134): error C4703: potentially uninitialized local pointer variable 'type' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\cgrepagent.cpp(1694): error C4703: potentially uninitialized local pointer variable 'type' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\cmd\cviewcommander_diff.cpp(228): error C4703: potentially uninitialized local pointer variable 'typeMini' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\cmd\cviewcommander_grep.cpp(86): error C4703: potentially uninitialized local pointer variable 'pConfig' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\cmd\cviewcommander_settings.cpp(180): error C4703: potentially uninitialized local pointer variable 'pConfig' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\creadmanager.cpp(56): error C4703: potentially uninitialized local pointer variable 'type' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\dlg\cdlgopenfile_commonfiledialog.cpp(889): error C4703: potentially uninitialized local pointer variable 'type' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\dlg\cdlgopenfile_commonitemdialog.cpp(709): error C4703: potentially uninitialized local pointer variable 'type' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\env\cdoctypemanager.cpp(62): error C4703: potentially uninitialized local pointer variable 'mini' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\env\cdoctypemanager.cpp(92): error C4703: potentially uninitialized local pointer variable 'mini' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\recent\cmrulistener.cpp(84): error C4703: potentially uninitialized local pointer variable 'type' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\typeprop\cdlgtypeascertain.cpp(120): error C4703: potentially uninitialized local pointer variable 'type' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\typeprop\cdlgtypelist.cpp(328): error C4703: potentially uninitialized local pointer variable 'type' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\typeprop\cdlgtypelist.cpp(418): error C4703: potentially uninitialized local pointer variable 'typeMini' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\typeprop\cdlgtypelist.cpp(526): error C4703: potentially uninitialized local pointer variable 'typeMini2' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\typeprop\cdlgtypelist.cpp(595): error C4703: potentially uninitialized local pointer variable 'typeMini' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\view\ceditview_diff.cpp(527): error C4703: potentially uninitialized local pointer variable 'typeMini' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]
- c:\projects\sakura\sakura_core\cmd\cviewcommander_grep.cpp(86): error C4703: potentially uninitialized local pointer variable 'pConfig' used [C:\projects\sakura\tests\build\Win32\unittests\tests1.vcxproj]

## 再現手順
複数個所で変数が未初期化のままになる。
具体的にどのような問題として顕在するかは未調査

## 再現頻度
未調査

**Comment by berryzplus** [comment]
この件、調べてみました。

実は、警告の要因はぜんぶ同じでした。

警告メッセージでは多種多様な変数名が報告されているので様々な要因があるのかと思っていましたが、単に書きっぷりに統一感がないだけでした。

- 関数 `CDocTypeManager::GetTypeConfigMini` に渡す(out)ポインタ引数を初期化していない。
  - out引数に渡す変数を初期化しないのは「誤り」じゃない気もする。
- 関数 `CDocTypeManager::GetTypeConfigMini` の戻り値をチェックしていない。
  - 成否を返す関数の戻り値をチェックしないのは「誤り」だと思います。
  - 「仕様上失敗しない」ならシグニチャを変えるべきだと思います。

これが問題の関数。
https://github.com/sakura-editor/sakura/blob/8371639bd1242c3566c18bddc72b3c25260fe1c2/sakura_core/env/CDocTypeManager.cpp#L130-137

visual c++やgccが問題を正しく検出できてない理由があるとすれば、
この関数の第2引数の特殊性にその原因があるような気がします。
（ぶっちゃけ、型の記載がc++仕様に則っていないだけかも知らんです。

`const STypeConfigMini** type`

素直に読むと、「`STypeConfigMini`構造体へのポインタを指す変更不可のポインタ」です。

しかし、この引数はout引数なので「変更不可のポインタ」ではありません。
これは、「変更不可の`STypeConfigMini`構造体を指すポインタを指すポインタ」です。

`using TypeConfigMiniPtr = const STypeConfigMini*;`

とでもしたら正確に表せるのかも知れませんが、やり方が色々ありそうで会話するのがメンドクサイ感じに思っています。
