### ISSUE TITLE
リンカオプションのOSの最低バージョンを指定する

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#897]
この変更は inno setup のアップグレードと関係なく、「やっとくほうが親切」な対応だと思います。何故かというと、exe本体が利用できる windows api のバージョンを指定するプリプロセッサで `win7(ver6.1)` を指定しているからです。つまり、ver5 OS を使った場合には、ここを変えなくてもどこかで動かせない機能がでてくるということです。分かっているなら最初からインストールできないようにしてあげるのが親切な気はします。

https://github.com/sakura-editor/sakura/blob/f9f23a31d96e08733558cbb82edcc711b530d5df/sakura/sakura.vcxproj#L93

細かいことを言うと横展開で「変えといたほうが親切」な設定項目が他にもあるんですけど、「inno setup 6 を使うためには変更しないといけない」という説明だと少し意味が違う気がしました。

_Originally posted by @berryzplus in https://github.com/sakura-editor/sakura/pull/884_

`細かいこと` の詳細共有です。

リンカオプション [`/SUBSYSTEM`](https://docs.microsoft.com/ja-jp/cpp/build/reference/subsystem-specify-subsystem?view=vs-2019) には最低バージョンを指定することができます。

この「最低バージョン」について、これが具体的にどういう効果を持つのか、実はよく分かっていません。リンカのオプションなので、プログラムローダーをどう組み込むかに影響してきそうに思えますが、生成されるexeにはバージョン情報が付かない気がします。

設定なしの場合のデフォルト値は `6.0(=vista)` になっています。ちょっと前までは `5.0(=win2k)` だった気がしますが、いつの間にか変わっております。ここに **`6.1(=win7)`を指定することができる** という話です。

方策として2通り考えられます。
* よく分らないものは設定しない ⇒ 6.0据え置き
* 設定できるなら設定しよう ⇒ 6.1に更新

具体的な効果が分かればもうちょっと前に進む感じの議論になるかもしれないので、とりあえず共有します。

**Comment by beru** [comment]
Visual Studio でプロジェクトのプロパティ画面の左側でLinkerのSystemを選んだ後に、右側のSubSystemで Console や Windows を選択できますがここのプロパティの事でしょうか？

そこで最低バージョンを指定出来ないのなら、GUIから指定出来ない非一般的な項目、という事で積極的に指定するのはどうなんだろう…、、って思います。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394
