### ISSUE TITLE
[x64対応] (未着手) 0x7fffffff を超えるポインタのエミュレート

### ISSUE THREAD

**Issue by kobake** [sakura-editor/sakura#91]
何かしらの方法でメモリ確保時のポインタが 0x7fffffff を超えるような状況を作り出して動作を確かめたい。

※この Issue 対応は kobake がやるとは限らないです。誰か着手する人がいましたら、この Issue のタイトルを `(着手済)` に変更してください。

**Comment by m-tmatma** [comment]
```
#include "stdafx.h"
#include <stdlib.h>

int main()
{
	char * p = (char*)malloc(10);
	printf("p = %p\n", p);
	free(p);
	return 0;
}
```

のようなコードで、

`p = 00000224422A5900
`

という出力になりました。

個別に確認するのは時間がかかりそう。

**Comment by berryzplus** [comment]
「大きい」の意味が unsigined long long の値が大きいの意味であれば、virtuallallocで開始アドレスを指定すればいけるような気がします。やってる時間がなさそうなので、参考資料になりそうなもの探してみました。

大容量メモリの扱いに関する資料
http://www.atmarkit.co.jp/ait/articles/1006/03/news093_2.html

x64のメモリマップに関する資料
https://qiita.com/kimuraya/items/1c9023d2bc27ecaed259

**Comment by berryzplus** [comment]
これ、閉じておきますね。(経緯は #1394 参照)

たぶん、`0x7fffffff を超えるポインタ` という表現は、次のような大前提から来てるように思います。
- ポインタとは、メモリアドレスを表す数値である。
- 数値なんだから当然、int型にキャストできる。
- intの最大値は 0x7fffffff までだから、`キャストして使ってたら大変だ。`

実際数値なので、ポインタを数値として扱うこと自体は間違いじゃないっす。
でも「当然、int型にキャストできる」ってのは間違いだと思います。
`ポインタの指す値が int型に収まるならint型にキャストしてもいいよ` ってだけだと思います。
