### ISSUE TITLE
v2.4のヘルプ キーワード検索画面のリストが文字化けしている

### ISSUE THREAD

**Issue by dot3h** [sakura-editor/sakura#922]
sakura_install2-4-0-1699-x86.exe をインストールしたところ、
メニューの [ヘルプ] -> [ヘルプキーワード検索] で表示されるヘルプ画面にて、
リストの内容が文字化けしていました。

使用環境は以下の通りです。
* エディション　Windows 10 Home 64bit
* バージョン　1809

## v2.2

![sakura_v2 2_help](https://user-images.githubusercontent.com/3514664/58271382-e45ff000-7dc6-11e9-8d6f-9884cbc90bbb.png)

## v2.4

![sakura_v2 4_help](https://user-images.githubusercontent.com/3514664/58271395-e9bd3a80-7dc6-11e9-90a3-67e22fd45c9c.png)

ご確認をよろしくおねがいします。

**Comment by KENCHjp** [comment]
@dot3h さん、ご報告ありがとうございます。確認します。

**Comment by berryzplus** [comment]
最新版ビルドの成果物でも化けているのを確認しました。
https://ci.appveyor.com/project/sakuraeditor/sakura/branch/master/job/8by7wywp086d0p12/artifacts

開発環境を整えた端末でビルドしたchmファイルは化けないので、  
CI環境の言語が英語なのが影響していると考えられます。

**Comment by m-tmatma** [comment]
> CI環境の言語が英語なのが影響していると考えられます。

間違いなさそうです。(035981a8b054dee2a060ee836c598314c0303bed で確認しました)

1. https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ で `MSEdge on Win10 (x64) Stable 1809` をダウンロード
2. Virtual Box で [仮想アプライアンスのインポート](https://docs.oracle.com/cd/E26217_01/E35194/html/qs-import-vm.html)
3. Visual Studio 2019, 7 zip, Git, python をインストール
4. build-chm でビルド
5. sakura.chm を開く
6. 文字化けを確認

**Comment by m-tmatma** [comment]
これの出番かな?

https://github.com/sakura-editor/sakura/issues/906#issuecomment-495930649

> AppLocaleはWindows10では使えないようですが、
> 
> https://pooi.moe/Locale-Emulator/
> 
> というのがあるようです。ただしExplorerのContext Menuから使うUIになっていてコマンドラインから使うやり方はサイトを見てもよくわかりません…。
> 
> 追記：コマンドラインでも使えるようです。
> https://github.com/xupefei/Locale-Emulator/blob/0bb4a81091d294166aa7a29955378b0e5aa38f8b/LEProc/Program.cs#L56

**Comment by berryzplus** [comment]
> これの出番かな?

https://github.com/sakura-editor/sakura/issues/922#issuecomment-495958960 で検証したVirtualBoxに入れてみて、化けなくなったら「使える」認定な流れだと思います。

あとは Locale Emulator をappveyor、Azule Pipelinesに持ってく方法ですが、たぶん色々あるのでまずは使えるかどうかの確認が先かな？と思ってます。  
（git cloneしてビルド、installerのdownload、chocolateなどのパッケージ管理で(ry...

**Comment by berryzplus** [comment]
ちょっとググったらパッケージがあったのでとりあえず報告。
https://chocolatey.org/packages/locale-emulator

**Comment by berryzplus** [comment]
@m_tmatmaさん
> 3.Visual Studio 2019, 7 zip, Git, python をインストール

HTML Help Workshopってどうしました？
vs2019installerからpython, gitは入れられたけど、
7zip, tortoiseGit, HTML Help Workshopは個別に落としてきました。
vs2017 では何かのオプションを付けると入ったみたいですが探せなくて・・・。

**Comment by m-tmatma** [comment]
c++ 関連の開発オプションをセットしてインストールしました

**Comment by berryzplus** [comment]
> c++ 関連の開発オプションをセットしてインストールしました

どれ～～～？ｗ

などという、しょーもないやり取りを避けるためのmarkdownドキュメントだと思っとります（ｷﾘｯ

**Comment by m-tmatma** [comment]
> HTML Help Workshopってどうしました？
> c++ 関連の開発オプションをセットしてインストールしました

`HTML Help Workshop` はインストールしていなくて hhc.exe を使っているだけです。

**Comment by m-tmatma** [comment]
> 間違いなさそうです。([035981a](https://github.com/sakura-editor/sakura/commit/035981a8b054dee2a060ee836c598314c0303bed) で確認しました)
> 
> 1. https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/ で `MSEdge on Win10 (x64) Stable 1809` をダウンロード
> 
> 2. Virtual Box で [仮想アプライアンスのインポート](https://docs.oracle.com/cd/E26217_01/E35194/html/qs-import-vm.html)
> 
> 3. Visual Studio 2019, 7 zip, Git, python をインストール
> 
> 4. git clone https://github.com/sakura-editor/sakura.git
> 
> 5. build-chm でビルド
> 
> 6. sakura.chm を開く
> 
> 7. 文字化けを確認

https://github.com/sakura-editor/sakura/wiki/%E8%8B%B1%E8%AA%9E%E3%81%AE%E3%83%86%E3%82%B9%E3%83%88%E7%92%B0%E5%A2%83

に仮想環境の構築のページを追加しました。

**Comment by berryzplus** [comment]
https://github.com/sakura-editor/sakura/issues/922#issuecomment-495964658
書いていませんでしたが「LocaleEmulator」を使って、英語OSのコマンドプロンプト(=cp437)からsakura.chmをビルドして文字化けがおきないことを確認しました。

「LocaleEmulator」はGUIアプリなので、このままCI環境で流用するのは難しいです。
CI環境対応向けのパッチを書いてみようと思ってますが、運用で使えるか微妙・・・。

**Comment by m-tmatma** [comment]
#971 がマージされたら解消する予定

**Comment by berryzplus** [comment]
#971 マージしました。

この issue 解消のためには、GitHub Release のモジュール更新が必要なのかな？と思っていますが、モジュール更新については別に https://github.com/sakura-editor/management-forum/issues/72 があるので結論はそちらに任せていい気もします。

マージ後にビルドしたバージョンは以下からダウンロードできます。
これをもってこの issue は close として良いかも知れません。
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/26280954
https://ci.appveyor.com/project/sakuraeditor/sakura/builds/26280954/job/0fjpsehxkx19k3ys/artifacts

**Comment by KENCHjp** [comment]
これ、いよいよ完了でいいんでしたっけ？、リリースに向けて動き出してよい？ @berryzplus さん

**Comment by berryzplus** [comment]
進めて良いと思います。

これに関しては、Azure pipelinesでのビルドが実現できてないですが、appveyorは行けてるからいいのかな、です。

**Comment by KENCHjp** [comment]
>進めて良いと思います。

了解です。
じゃあ、今度の連休か、即位の礼あたりでベータ版作成動き出しましょうか。
動いて問題があればまた考えましょう。
