### ISSUE TITLE
.gitignore の中身をソートする

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#926]
.gitignore の中身をソートする

現状、登録順に規則性がないので、ソートして登録する。

## 対応時期

#923, #924, #925 のマージ後

**Comment by berryzplus** [comment]
いいんじゃないかと思います。

> .gitignore の中身をソートする
> 
> 現状、登録順に規則性がないので、ソートして登録する。

違ってたらゴメンですが、こんな感じのissueと理解しました。

 - そもそもgitignoreとは？
   - gitで履歴管理しないファイルを定義するためのもの。
     - ワイルドカードで無視するパターンを列挙して定義する。
     - GUI上では`無視リスト`と表記される。
     - GUI上では`無視`すると追加or変更しても色が付かない。
   - gitの`無視リスト`管理方法は [3パターン](https://git-scm.com/docs/gitignore) ある。
     - 「無視リスト」を共有したい場合 ⇒ `.gitignore` を使う。
     - ローカルルールを定義したい場合 ⇒ `.git/info/exclude` を使う。
     - 個人設定を定義したい場合 ⇒ `%USERPROFILE%/.config/git/ignore` を使う。
 - 課題の内容
   - gitignoreの登録順に規則性がないのを何とかしたい
 - gitignoreに規則性がないと困ることは？
   - 見た目がダサい。
   - 「無視リスト」に入れてない生成ファイルを見落とす恐れがある。
     - レビュー時に`これ何？`と訊けるので実害はなさげ。
 - gitignoreに規則性を持たせて困ることは？
   - たぶん、ない。
 - 対策の提案
   - gitignoreの登録内容をソートする

**Comment by m-tmatma** [comment]
> 違ってたらゴメンですが、こんな感じのissueと理解しました。

この通りです。
