### ISSUE TITLE
[x64対応] (未着手) DWORD_PTR, INT_PTR, LONG_PTR の変数の変数名に関して検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#93]
[x64対応] DWORD_PTR の変数の変数名に関して検討する

https://github.com/sakura-editor/sakura/pull/89#discussion_r194280548

**Comment by berryzplus** [comment]
実施するなら _PTR 系全部を対象にご検討いただけませんか？

INT_PTR, LONG_PTRなど。全部x64化で32bit⇒64bitになると思いますので。

**Comment by m-tmatma** [comment]
> 実施するなら _PTR 系全部を対象にご検討いただけませんか？

タイトル変えました。
PR は分けたほうがいいかもしれませんが。

**Comment by m-tmatma** [comment]
C:\Program Files (x86)\Windows Kits\10\Include 以下にある標準のヘッダは
特に DWORD_PTR とわかるような変数名つけてないですね。
INT_PTR や LONG_PTR も同様

**Comment by kobake** [comment]
> C:\Program Files (x86)\Windows Kits\10\Include 以下にある標準のヘッダは
> 特に DWORD_PTR とわかるような変数名つけてないですね。
> INT_PTR や LONG_PTR も同様

確かに……。これめちゃくちゃ気持ち悪いですね……。

**Comment by kobake** [comment]
https://github.com/search?o=desc&p=4&q=DWORD_PTR&s=indexed&type=Code

ざっくり GitHub 上のコードを眺めた感じだとプリフィックスを付けないケースが多いように感じました。

**Comment by berryzplus** [comment]
この件ってどうなってるんでしたっけ？
気にしなくていい、って結論にする認識でOK？

**Comment by k-takata** [comment]
ハンガリアン記法はもはや下火なのでは？
`***_PTR` 用の公式なプレフィックスは存在しないと思います。

**Comment by kobake** [comment]
> ハンガリアン記法はもはや下火なのでは？

これには同意です。

ただ、ハンガリアン記法なコードが残っていることについては自分としては直しても放置でもどっちでも良いと思っています。

ただ、`DWORD_PTR dwData;` みたいな宣言はちょっと見逃せないなーって思ってます。これじゃ宣言部見ずに利用部だけ見ると DWORD 型だと勘違いされてしまいそうなので。（https://github.com/sakura-editor/sakura/pull/89#discussion_r194280548 で指摘したところ）

もしかして自分が知らないだけで DWORD_PTR  型の変数のプリフィックスを `dw` にするような慣習ってあったりするんですかね。

**Comment by berryzplus** [comment]
一括対応は不要、の結論で閉じておきます。

必要なら新しくissue立ててください。
