### ISSUE TITLE
find-tool.bat で Visual Studio 2017 か Visual Studio 2019 かを指定するようにしたい。

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#931]
## 要望機能

#892 で find-tool.bat で最新版の Visual Studio か Visual Studio 2019 かを指定するようにしたが、 #698 の 実現のために Visual Studio 2017 か Visual Studio 2019 かを指定するようにしたい。

## 背景

#698: `Visual Studio 2019 ビルドに対応する`  を対応しようとしたが、

以下のように cmake のビルドに失敗している。
https://m-tmatma.visualstudio.com/sakura/_build/results?buildId=366

これは https://cmake.org/cmake/help/v3.14/generator/Visual%20Studio%2016%202019.html
にあるように `Visaul Studio 2019` でビルドする場合 cmake の `-G` に `Visual Studio 16 2019` を指定する必要があるためである。

`Visaul Studio 2019` の イメージの場合  `Visaul Studio 2017` はインストールされてない。
`Visaul Studio 2019` のイメージでもビルドできるようにしたい。

## 現状

以下の部分で `Visual Studio 2017` の msbuild.exe のパスを検索している。

https://github.com/sakura-editor/sakura/blob/035981a8b054dee2a060ee836c598314c0303bed/tools/find-tools.bat#L98-L111

以下の部分で 最新の Visual Studio (現在のところは `Visual Studio 2019`) の msbuild.exe のパスを検索している。

https://github.com/sakura-editor/sakura/blob/035981a8b054dee2a060ee836c598314c0303bed/tools/find-tools.bat#L117-L122

## 問題点

- latest のバージョンは現在は VS2019 だが、将来は変更になる可能性がある。
- cmake で latest という指定ができないので、Visual Studio に対してのみ、latest という指定をした場合、将来的に VS2019 以降のバージョンが出た場合に、再現性の低いコードになってしまう。(VS2021 とか出た場合に latest は VS2021 の意味になるが、cmake は依然として VS2019 を参照しようとする。)

## #698 の 実現方法の提案

1. 最新の Visual Studioを探さずに、`Visual Studio 2019` のバージョンを指定して `msbuild.exe` を探す

```
for /f "usebackq delims=" %%a in (`"%CMD_VSWHERE%" -version [16^,17^) -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe`) do (
    set "CMD_MSBUILD=%%a"
    exit /b
)
```

2.  `USE_LATEST_MSBUILD` を廃止して、`SELECT_VSVERSION` のような変数を導入する

https://github.com/sakura-editor/sakura/blob/035981a8b054dee2a060ee836c598314c0303bed/tools/find-tools.bat#L113-L115

3. `SELECT_VSVERSION` の値が未定義の場合 → VS2017 を使う
4. `SELECT_VSVERSION` の値が 2017 の場合 → VS2017 を使う
5. `SELECT_VSVERSION` の値が 2019 の場合 → VS2019 を使う
6. `CMAKE_GENERATER_VERSION` という環境変数を導入する
    1. VS2017 を使う場合 → `CMAKE_GENERATER_VERSION` に [Visual Studio 15 2017](https://cmake.org/cmake/help/v3.14/generator/Visual%20Studio%2015%202017.html) に設定する。
    2. VS2019 を使う場合 → `CMAKE_GENERATER_VERSION` に [Visual Studio 16 2019](https://cmake.org/cmake/help/v3.14/generator/Visual%20Studio%2016%202019.html) に設定する。
7. `sakura/tests/create-project.bat` で `%CMAKE_GENERATER_VERSION%` を `-G` の引数に渡す
https://github.com/sakura-editor/sakura/blob/035981a8b054dee2a060ee836c598314c0303bed/tests/create-project.bat#L52

**Comment by berryzplus** [comment]
了解です。いいと思います。
別案として **CMake で `-G "Visual Studio*"` するのをやめる** 、というのを考えてました。

もうだいぶ放置してますが、 #796 `vsソリューションにテストプロジェクトを取り込みたい` を実現したら「テストのCMakeをやめる」をやれそうな気がしています。テストプロジェクトに sakura.vcxproj に入れたpropertyの細工を入れておくことでvs2017/vs2019の両対応にできます。tests1.vcxprojの手メンテが必要になるので「え～～」がありそうなのがネックです。

CI全体としてはこんな感じにできたらいいな、と思っています。

環境 | ビルド方式 | 用途
-- | -- | -- 
Win32(MSVC) | sakura.sln | リリース用(appveyor,Azule Pipelines)
x64(MSVC) | sakura.sln | リリース用(appveyor,Azule Pipelines)
MinGW | CMake(MinGW Makefiles) | 検証用(appveyor⇒廃止)
MinGW | CMake(Ninja) | 検証用(新設⇒appveyor)
MSVC | CMake(Ninja) | 検証用(新設⇒Azule Pipelines)

CMake(Ninja)をPRできるまでにはまだだいぶかかりそうなので、  
先行で入れられそうな改善には協力していきたいと思っています。

**Comment by m-tmatma** [comment]
> 別案として **CMake で `-G "Visual Studio*"` するのをやめる** 、というのを考えてました。

それだと、VS2017, VS2019 が両方インストールされている環境で困ります。

**Comment by berryzplus** [comment]
> > 別案として CMake で -G "Visual Studio*" するのをやめる 、というのを考えてました。
> 
> それだと、VS2017, VS2019 が両方インストールされている環境で困ります。

両方インストールされた環境でも困らないように考慮できます。
find-tools.bat に関しては #892 の対応で既に vs2017 と 最新vs(=vs2019) の並存に対応しています。
vcxproj に関しては #866 で vs2017 と vs2019 の並存に対応する方法が確立してると思っています。

**Comment by berryzplus** [comment]
既に指定できるようになっているので閉じてしまいます。
