### ISSUE TITLE
#918 で Pull Request Template を導入したが、画面いっぱいになって誰も読まない

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#932]
## 問題内容

#918 で Pull Request Template を導入したが、画面いっぱいにコメントがあふれる。
これでは邪魔なだけで誰も読まない。

## 再現手順

#918 導入後に Pull Request の作成画面を出す

## 再現頻度

100 %

## 問題のカテゴリ

- その他の問題 (GitHub 関連)

## スクリーンショット

<img width="779" alt="pull-request-problem" src="https://user-images.githubusercontent.com/5567450/58379025-62dfac00-7fd8-11e9-8e1f-8b2d79705d4d.png">

**Comment by berryzplus** [comment]
説明自体はわかりやすいと思ったんですけどねぇ :cry:

この辺の末尾空白は、ないほうが見やすいと思いました。

```
<!-- 1. これまでの作業内容を別ブランチに push すれば多くの場合、一部を再利用できます。                                     -->
<!-- 2. これまでの経緯を知らない人でもレビューに参加しやすくなります。                                                     -->
<!-- 3. 新たな PR 作成時にまとめを書くことで PR 作成者の頭の整理ができます。                                               -->
<!-- 4. PR マージ後に見るときに関係していない人が理解しやすくなります。                                                    -->
```

使ってみてフィードバックしていくやり方はアリだと思っています。

**Comment by m-tmatma** [comment]
一行ずつコメント開始タグ、終了タグを書かないようにすると改善するかも
