### ISSUE TITLE
Azure Pipelines 環境で test_result_filter_tell_AppVeyor.bat で 標準エラーにメッセージが出力される

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#935]
## 問題内容
Azure Pipelines 環境で test_result_filter_tell_AppVeyor.bat で 標準エラーにメッセージが出力される

## 再現手順
VS2019 用のイメージでビルドを実行する
VS2017用のイメージでも発生しているが、標準エラー出力のエラーを画面にエラーと表示しないみたい。

## 問題内容

コード的には意図的に出力しているが、CI 環境を appveyor しか想定していないため発生している。
Azure Pipelines 上では単に混乱を招くだけなので、エラーが出ないようにする必要がある。

## 再現頻度
100%

## 問題のカテゴリ
- ビルドの問題
  - Azure Pipelines
  - ローカルビルド (appveyor の実行ファイルがない環境で発生する)

## 参考URL

https://m-tmatma.visualstudio.com/sakura/_build/results?buildId=381

## スクリーンショット

```
Submodule 'tests/googletest' (https://github.com/google/googletest.git) registered for path 'googletest'
Cloning into 'D:/a/1/s/tests/googletest'...
test_result_filter_tell_AppVeyor.bat: `appveyor` command was not found. This filter does nothing effective.
```

<img width="1288" alt="appveyor-not-found" src="https://user-images.githubusercontent.com/5567450/58423331-cdbfde80-80cf-11e9-9d16-346ec3824227.png">

**Comment by berryzplus** [comment]
> コード的には意図的に出力しているが、CI 環境を appveyor しか想定していないため発生している。
> Azure Pipelines 上では単に混乱を招くだけなので、エラーが出ないようにする必要がある。

「なので、Azure Pipelines上で動かすためのバッチを書きます。」になるんですかね。

本来的にappveyor環境で動かすためのバッチなので、
appveyor環境以外で動かしたときの警告はstderrに出しましょう、と指摘上げた気がします。
appveyorの環境変数をセットせずにローカルで動かしたらすぐに分かるように、という意図で。

next action
1. このまま放置
2. Azure Pipelinesで都合のいい感じに新バッチを作る
3. AppveyorとAzure Pipelinesの間を取った形に現状を作り変える

**Comment by berryzplus** [comment]
補足） #952 の対応内容は https://github.com/sakura-editor/sakura/issues/935#issuecomment-500216448 でいうところの「3.AppveyorとAzure Pipelinesの間を取った形に現状を作り変える」でした。

「とくに問題なし」だとぼくは思っています。
