### ISSUE TITLE
Visual Studio のインストールオプションを設定ファイルとしてエクスポートして共有する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#936]
## 要望機能

Visual Studio のインストールオプションを設定ファイルとしてエクスポートして共有する

## 参考 URL

https://stackoverflow.com/questions/52946333/how-to-extract-currently-installed-visual-studio-component-ids
https://docs.microsoft.com/ja-jp/visualstudio/install/import-export-installation-configurations?view=vs-2019
https://devblogs.microsoft.com/setup/configure-visual-studio-across-your-organization-with-vsconfig/

**Comment by m-tmatma** [comment]
上記サイトで Visual Studio 2019 の場合に、ソリューションを開いたときに
足りないコンポーネントをインストールできる機能はすごく有用だと思う

**Comment by m-tmatma** [comment]
上記サイトで例として示されているファイル
https://github.com/microsoft/vswhere/blob/develop/.vsconfig

**Comment by m-tmatma** [comment]
コマンドラインからインポート、エクスポートできるみたい
https://docs.microsoft.com/ja-jp/visualstudio/install/command-line-parameter-examples?view=vs-2019

**Comment by m-tmatma** [comment]
インストールに関するコマンドラインオプション
https://docs.microsoft.com/ja-jp/visualstudio/install/use-command-line-parameters-to-install-visual-studio?view=vs-2019

**Comment by berryzplus** [comment]
これって「実現できた」と思っています。

vs2019でソリューションを開くと「なんか出る」ので
まだ改善の余地がありそうですが、
いったんcloseでよいと思います。
