### ISSUE TITLE
Appveyorのロケール設定を復活したい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#954]
## 目的
HTML Helpの文字化けを解消するために、
```
Set-WinSysLocale ja-JP
Restart-Computer
```
を復活できないか検討したいです。

## 経緯
現在、[v2.4.0のリリースに向けた作業](https://github.com/sakura-editor/management-forum/issues/72)を進めています。
CI環境でビルドしたCHMヘルプのキーワードが化けていることが分かっていて、目下リリースに向けた「大きな課題」となっています。
⇒「#922 v2.4のヘルプ キーワード検索画面のリストが文字化けしている」

原因は、appveyorのロケールが`en-US`にだからです。
何故`en-US`なのかというと、ビルド速度改善のために`ja-JP`に変える処理を削ったからです。
⇒「#482 appveyorでロケール設定するのをやめる」

## 他の解決策は？
LocaleEmulatorというアプリが存在します。Windowsアプリのプロセス起動の仕組みに介在し、対象のアプリを任意のロケールで起動できるツールです。これがそのまま使えれば良かったのですが、appveyor上ではうまく動作しませんでした。改造してとりあえず動くようにすることはできますが、デバッグや動作保証ができない種類のツールなので、運用に組み込むのは不可能だと思っています。

ぼく「エロい人（２ちゃん語）」とよく言いますが、「エロい人」の本当の意味は「偉い人」じゃないです。本来「エロい人」ってのは「尻」が好きな人のことを指します。「尻」ってのも隠語ですが、これはシリアルキーとかプロダクトキーのことです。バイナリに含まれるシリアルキーをあらゆる手段を使って見つけ出すスペシャリスト、それが「エロい人」です。

[LocaleEmulator](https://github.com/xupefei/Locale-Emulator-Core)には本物の「エロい人」が使う高度な技術が含まれています。この種のコードをレビューできる人がこの世に存在するとも思えないくらいの異常なレベルの技術が含まれています。１週間くらい触ってみた感覚で、半年もあればデバッグ可能なアプリに作り替えられそうだと思っていますが、それをここのプロジェクトのビルドに転用できるかどうかは別問題です。転用は現実的に難しいと思っています。

## ロケール設定を復活させると遅くなるんじゃないの？

ビルド時間はまた遅くなると思います。
ロケール変更とシステム再起動のための2分は、日本語のHTML Helpをビルドするために必要な時間なので仕方ないと思います。必要ならケチってはいかんような気がします。「無駄に」時間を消費しているなら削減を考えないといかんですが、必要なんであればそれはキッチリ時間をかけてやればいいと思います。

**Comment by m-tmatma** [comment]
ロケールの変更が必要なのは、chm のビルドだけなので
ロケールの変更をした上で chm のビルドをして、
そのジョブの成果物をアプリとか、インストーラのビルドで
流用する形にしたいです。

そうすることで、ビルド時間が伸びるのを軽減できます。
やり方は調査が必要ですが。

**Comment by berryzplus** [comment]
取りうる方向性を３つに絞ってみるとこんな感じです。

作戦名 | 内容 | メリット | デメリット
-- | -- | -- | --
原点回帰 | Set-WinSysLocaleを復活させる | Windows的に正規の方法です。 | ロケール変更には再起動が必要で、再起動には時間がかかります。「git cloneがたまに失敗する問題」が再発する懸念があります。
朝令暮改 | HTML Helpをやめる | ヘルプ提供方式の主流です。 | ヘルプコンテンツの見直しが必要です。オフラインヘルプが必要な人向けの代替を考える必要があります。
勇往邁進 | hhc.exeを日本語で実行します。 | ヘルプについて変更せずに進めることができます。 | ツールの開発に長い時間を要します。開発が可能だったとして、技術的にエロすぎてレビューできないので、安定性の面で不安があります。

個人的には「原点回帰」の一択なんじゃないかと思っています。
「朝令暮改」は既出の話題ですが「移行期間なしで切り替える」の前提で考えると解決策になるように思っています。
「勇往邁進」はぼくが趣味で続けますが、趣味は趣味で終わらせていいように思っています。

**Comment by berryzplus** [comment]
https://github.com/sakura-editor/sakura/issues/954#issuecomment-508259347
> ロケールの変更が必要なのは、chm のビルドだけなので
> `（途中省略）`
> そのジョブの成果物を`（途中省略）`流用する形にしたいです。

特定のビルド成果物を「ネットワーク上のどこか」に保存しておき、その成果物に依存するビルドでは「ネットワーク上のどこか」にある成果物を取ってくる仕組みを作るってことですかね？

「ネットワーク上のどこか」の候補には、Azureストレージを推したいと思っています。
基本的に無料で扱えることと、格納＆取得にかかるコードが簡単に実装できることが理由です。

どのアカウント使うかは相談しないといかん気もしますけどね。

**Comment by m-tmatma** [comment]
> 特定のビルド成果物を「ネットワーク上のどこか」に保存しておき、その成果物に依存するビルドでは「ネットワーク上のどこか」にある成果物を取ってくる仕組みを作るってことですかね？

Jenkins ではある JOB (ここでは JOB A と呼びます) の成果物を別の JOB  (ここでは JOB B と呼びます) の成果物の入力にできる仕組みがあります。

JOB A のビルドに成功したら JOB B のビルドをするという設定をする
あるいは
JOB B のビルドをする際には、JOB A を事前にビルドするという設定をしたうえで
JOB A の成果物を JOB B を流用する

ということができるので、それを想定したのですが、
ちょっと探した限りでは見当たらなかったです。

このような仕組みが使えない場合、単純に (ビルドが終わった時に appveyor に up されて、通常ユーザーがダウンロードされる) artifact を web 経由で取得したらいいと思います。
https://www.appveyor.com/docs/api/samples/download-artifacts-ps/

**Comment by m-tmatma** [comment]
> このような仕組みが使えない場合、単純に (ビルドが終わった時に appveyor に up されて、通常ユーザーがダウンロードされる) artifact を web 経由で取得したらいいと思います。
> [appveyor.com/docs/api/samples/download-artifacts-ps](https://www.appveyor.com/docs/api/samples/download-artifacts-ps/)

※ 別件ですが、メモ
Azure Pipelines で成果物をダウンロードする方法がある模様
https://docs.microsoft.com/ja-jp/azure/devops/pipelines/tasks/utility/download-build-artifacts?view=azure-devops

**Comment by berryzplus** [comment]
> ただしそもそも locale の設定はできないが

#446 Azure Pipelines を調査する のリストで取消線になってるのは、「やってみたけどできなかった」って意味なんですね。

Azure と名前が付いていても pipelines と VMs はベツモノだっていう・・・
Azure でロケール依存のビルドを実現するには専用 VM を用意しないといけない感じなのかな？
すでに別issueで質問投げてるようにも見えましたが・・・。

**Comment by m-tmatma** [comment]
> Azure でロケール依存のビルドを実現するには専用 VM を用意しないといけない感じなのかな？

Microsoft の VM では無理で、セルフホストだとできるようです。

**Comment by berryzplus** [comment]
`Set-WinSysLocale` を復活させる作戦は Azure PipeLines では使えないとなると、
「LocaleEmulatorの改造ツールは現実的にレビュー不可能」のほうに対策すべきなのかな。

レビュー不可能だと思っている理由は、LocaleEmulatorを構成する技術領域があまりにも広すぎると感じたからです。

技術領域をせばめていけば、ある時点から「レビュー不可能」は「レビュー可能」に変わる気がします。カーネルモードとか、明らかに使わない部分をはがして行ったらなんとかならないか？というアプローチが考えられます。

LocaleEmulatorは元々、中国の好青年が日本のエロゲをプレイするために色んなものをかき集めて作り上げたマッシュアップツールのようです。エロゲのために作られたってところがポイントです。

多彩なグラフィックで魅せる日本のエロゲとHHC.exeのようなコンソールアプリでは、ロケールを変えるために必要な労力が全然違います。コンソールアプリを日本語で動かすほうが、作業量は少なく済みます。

LocaleEmulatorをappveyorで動かすではなく、LocaleEmulatorを参考にHHC.exeを日本語ロケールで動かすを目標にすれば、普通のプログラマーが理解できる程度の少ない技術で仕上げられそうです。

最近はpenテストって、プログラムの脆弱性耐性を検査するプロテスターを雇う現場も増えてきました。自分は良識あるプログラマーだからと「エロい技術」に無関心でいられた時代は、もしかしたらもう終わってるのかも知らんです。

レビュー可能なエロツールを目指して、hhc.exeの日本語起動ツールを作ってみようと思っています。

**Comment by KENCHjp** [comment]
纏めてくださったので、周回遅れでもなんとか追いついてみました。

原点回帰 ... 問題点が再燃しそうですが現時点これが正解かも。
朝令暮改 ... この方向に行きたいが色々と方針決めなきゃですね。
勇往邁進 ... ここは面白そうですが潰しが効かなさそう（派生物はどこかでやくにたつかもですが）＆OSが変わったりすると労力大変そう

基本的にはhtmlのみの「朝令暮改」でオフラインでもブラウザが入ってないWindowsはないとおもうので参照もできるかなとおもいます。

が、「原点回帰」が今は一番取りやすい選択肢なのかと思います。
一つ思い付きですが、話の途中に出てくる「JOB A の成果物を JOB B が流用する」がいいのかなと。

ヘルプは、ホームページリソースと同じく、人が意図的に修正しないと普段のソースのコミットの時には変更されてないものだと思うので、ヘルプのみの別リポジトリ作ってコンパイルしておく(chmファイルコミットする？）
インストーラーのmakeの時にはそのchmを取ってくるってことをすれば、普段のプログラム側のビルド時間は削減できるのかなとか。

技術的にできるのかは調べれてないですが。

**Comment by berryzplus** [comment]
> 技術的にできるのかは調べれてないですが。
> これできると、朝令暮改に移行するまでは、ヘルプのみappveyorでコンパイルしてプログラムは Azure Pipelinesでビルドってこともできるのかなとか。

じゃあそれでｗ
そっちのプランのほうがリードタイムが短いように思いました。

appveyorにブラウザからアクセスする分には、ビルドが全部終わってなくても、既にビルドが終わった分の成果物は先にダウンロードできています。バッチでも同じことができそうな気がします。どんな条件で成果物を絞り込めばよいか明確になるようにビルド手順を設計してやればよいはずです。

ここの先頭に `HtmlHelp（仮）` とかを追加するのはどうでしょう？
https://github.com/sakura-editor/sakura/blob/2ea6f75b0ad0303d2609a7f3f5094b4134cf98b7/appveyor.yml#L8-L12

appveyorでは、特定の構成の処理を個別に定義できます。
`HtmlHelp（仮）`をビルドする構成だけ、ロケール変更して再起動するって芸当が可能です。
全体的にc++のビルドとはやること違うので、全ステップ個別実装としてもいい気がしています。
ビルドは定義された順にシーケンシャル（順次）に実行されるので、先頭で実行すれば後続ビルドでは成果物を利用できる状態になっているはずです。

HHC.exeにはデバッグビルドの機能がないので、configurationはReleaseのみになると思ってます。実行するジョブのレシピはcmake化しておくべきだと思いますが、Debugビルドは想定していないです。

パッケージを作る処理で、
「最新ビルドのHtmlHelp - Releaseの成果物」
をダウンロードするわけです。

appveyorは色んなapiを公開しているので、条件に合うファイルのパスを問い合わせることはおそらくたやすいはず・・・（調べてないっす。

appveyorのAPIを叩いたりzipのダウンロードを実現するために、バッチの実装言語は`cmake on powershell` がいいんじゃないかと思っています。

いちおう今日から3連休・・・。

**Comment by berryzplus** [comment]
成果物を取得するためのapiが存在しているみたいです。
https://www.appveyor.com/docs/api/samples/download-artifacts-ps/

マニュアルはありませんが、普通のRESTメソッドっぽいです。

appveyorでカレントビルドの成果物を得る分には、そんなに難しくはなさそう。

azule pipelinesから参照する想定だと、いくつか決め事作る必要があります。
appveyor⇔azule pipelines間で「外部システム連携」させるわけですから。

【決めないといけないこと】
・azure pipelinesのビルドで常にインストーラを作るか？　←　いらない
・インストーラを作る際に参照するhelp成果物は「最新」でよいか？　←　「masterの最新」がいいはず
・ブランチビルドのときも同じでよいか？　←　対応するブランチの最新がベター

**Comment by m-tmatma** [comment]
azure pipelines でのビルドはそのまま独立させておき、
appveyor の成果物を利用するというようなことはしないほうがいいと思います。

> このような仕組みが使えない場合、単純に (ビルドが終わった時に appveyor に up されて、通常ユーザーがダウンロードされる) artifact を web 経由で取得したらいいと思います。
> [appveyor.com/docs/api/samples/download-artifacts-ps](https://www.appveyor.com/docs/api/samples/download-artifacts-ps/)

これはあくまでも、appveyor でのビルド時間が長くなるのを防ぐためのアイデアであって
azure pipelines での利用は想定していないです。

**Comment by berryzplus** [comment]
いったん、HtmlHelpのビルドを分離して、独自に成果物を作るところまでやって見ました。
https://ci.appveyor.com/project/berryzplus/sakura/build/job/s0ibf5x2gfiwqfau
https://ci.appveyor.com/project/berryzplus/sakura/build/job/s0ibf5x2gfiwqfau/artifacts

めんどくさいのは主にここからっす。

----

> これはあくまでも、appveyor でのビルド時間が長くなるのを防ぐためのアイデアであって
> azure pipelines での利用は想定していないです。

ありゃ？
azure pipelinesは再起動ができないのでhelpのビルドが行えないと判明した認識です。
appveyorの成果物の流用をしないと、azure pipelinesではインストーラを作れないはずです。

雰囲気、azure pipelinesをメインにしたい感じに受け取っていたのでちょっと意外なコメントでした :smile:

**Comment by m-tmatma** [comment]
> azure pipelinesは再起動ができないのでhelpのビルドが行えないと判明した認識です。
> appveyorの成果物の流用をしないと、azure pipelinesではインストーラを作れないはずです。

appveyor の助けなしに azure pipelines 単体でビルドできないのであれば、
まだ実験段階という扱いにして、azure pipelines ではビルドはするけど
バイナリは使わない想定です。

Azure Pipelines で GitHub アカウントのログインに関して、具体的なタイムラインはないという
回答をいただいていましたが、( https://github.com/sakura-editor/sakura/issues/446#issuecomment-440807357 , https://github.com/sakura-editor/sakura/issues/446#issuecomment-441011542 )

現在は対応されています。
https://github.com/sakura-editor/sakura/issues/446#issuecomment-492809379

対応するタスクとしては積まれているようなので少し待てば対応してくれるんではないかと思っています。
https://github.com/sakura-editor/sakura/issues/446#issuecomment-510069438

Azure は AWS に追いつくように気合を入れているみたいなので、
ユーザー要望はがっちり取り入れていくんではないかと期待しています。

**Comment by m-tmatma** [comment]
参考
https://news.mynavi.jp/article/itmarket-1/

**Comment by berryzplus** [comment]
## 経過報告
技術的にウラがとれました。
https://ci.appveyor.com/project/berryzplus/sakura/builds/25962702/job/c5ie16j08np4qvv4

問題だらけなので PR する前に調整が必要な気がしています。

まー最大の問題は、何が問題なのか説明するのがめんどくさい、ことなんですけども :sob:

**Comment by berryzplus** [comment]
テストプロジェクトの組込も作業してみました。
https://ci.appveyor.com/project/berryzplus/sakura/build/job/serb2c0tpy5h18rx

説明がめんどくさい理由
* 元が結構「えいやっ！」なので、現状整理のために本題の前に準備が要りました。本来これらはコミットを分けて個別に議論すべきだと思っています。しかし、いざ各個別にPRを出すとなるとかなりめんどくさいです。
* 今回、先行でHTML Helpを作るPlatformを新設します。何で新設？って質問が来そうで(以下同文。
* 新設Platformの名前は既存バッチのタスクラベルから採りました。分かりづらいって意見を出した上で代案の提示なしとか、普通にありそうで(以下同文。
* 新設PlatformのConfigurationはReleaseのみとします。Debugも欲しいって言われそうで(以下同文。
* Debug構成でChmを作らない関係で、Debug構成ではインストーラと配布用Zip（Devじゃないほうのexeが入ってるzip）を作らないようにしました。これに関してはChmがなくてもzipは作るんだ！という方向性もアリだと思っていて、仮置きの仕様だと思っています。
* Release構成のビルドでは、build-chm.batのタイミングで既に完了しているBuildChmの成果物の場所を REST API で問い合わせ、ダウンロード＆zip解凍を行って「あたかもその場でビルドしたかのような状態」にして処理を抜けます。chmのビルドにはロケール変更が必要なので、もちろんその場ではビルドしないんですが、そういう風に組むことで後続処理を変更しなくてよいようにしています。「問題だらけ」といってるのは主にこの辺のことです。とりあえず「こうすればできる」の形を作りましたが、懸念事項がたくさんあります。その懸念事項を書き出したら収拾が付かなくなりそうで(以下同文。
* そもそもの話として、appveyorの成果物をAPI経由でダウンロードするにはアカウントが必要です。今回は「とりあえず」のgmailアカウントでダミーユーザーを作って対応しました。ユーザーを作って「書込み権限なし、参照のみ」という権限を割り当て、そいつのAPI Tokenを使って成果物ダウンロードを実現しています。このアカウントは共用にしていいと思っているんですが、よく考えると資産を共有する方法って今まであんまりなかった気がするわけで、その辺をあらためて議論しないといかんなぁと思うと(以下同文。

で、次のアクションですが、諦めて PR 作成になるのかな？と思っています。
「めんどくさいです。」とばかりも言ってらんないので :sob:

**Comment by KENCHjp** [comment]
なるほど、某夢の国と同じく、ずっと暫定構築状態かもしれませんが、
とりあえずAppveyorを二つに分ける手もあるってことですね。

**Comment by berryzplus** [comment]
衝撃の事実！

> •~~そもそもの話として、appveyorの成果物をAPI経由でダウンロードするにはアカウントが必要です。~~

API tokenは項目必須だけど、ダウンロード時にはブランクが許可されるっぽい。

ここの前提が覆るとだいぶ気楽になれます... :smile:
