### ISSUE TITLE
Azure Pipelines のビルド完了を GitHub 上で通知したい

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#973]
## 要望機能
Azure Pipelines のビルド完了を GitHub 上で通知したい

## 背景

appveyor では https://github.com/sakura-editor/sakura/issues/957#issuecomment-508958513 の設定を行うと、Pull Request のビルド完了時に https://github.com/sakura-editor/sakura/pull/956#issuecomment-508990429 というような通知を GitHub に自動で書き込んでくれる。

このような通知を Azure Pipelines でも行いたい。

## 状況

しかし、この機能は Azure Pipelines では現在対応していない。
Azure Pipelines でこの機能に対応されたら対応する。

https://github.com/sakura-editor/sakura/issues/446#issuecomment-510651592

> I have another question.
> 
> Appveyor can notify completion of builds with the following setting.
> [#957 (comment)](https://github.com/sakura-editor/sakura/issues/957#issuecomment-508958513)
> 
> This is a message written by AppVeyorBot.
> [#956 (comment)](https://github.com/sakura-editor/sakura/pull/956#issuecomment-508960408)
> 
> Azure pipelines has notification settings ([docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-team-notifications?view=azure-devops](https://docs.microsoft.com/en-us/azure/devops/notifications/howto-manage-team-notifications?view=azure-devops))
> 
> But I didn't find how to do the same as appveyor.
> 
> [azure-pipelines-bot](https://github.com/azure-pipelines-bot) exists.
> So I guess it can possible on Azure Pipelines too.
> 
> If so, could you tell me how?

https://github.com/sakura-editor/sakura/issues/446#issuecomment-510852682

> Not possible today. We post Checks to GitHub, and don't have a mechanism to make azure-pipelines-bot post a comment. That's a good idea, though. @davidstaheli for future consideration.

## 関連チケット

#957

**Comment by berryzplus** [comment]
現状無理だって結論が出てるので、いったん閉じてしまいます。
再開できるような新情報が出たらそのときに re-open したらいいと思います。
