### ISSUE TITLE
REST APIとの通信にリトライ機能を付けたい

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#977]
> Service unavailableで失敗の事象を確認。
> 
> 対策しなきゃ…
> 
_Originally posted by @berryzplus in https://github.com/sakura-editor/sakura/pull/971#issuecomment-515831102_

ネットワーク通信なので「あるかもな～」と思いつつ、**面倒だからサンプルのままやってしまえ**と放置して導入してみたら、「案の定問題が起きました。」というお話です。

----

## 目的

REST APIがコケたときリトライするようにすることで、appveyorが過負荷になってもビルドが失敗しないようにしたいです。

## カテゴリ

- CI関連
  - Appveyor

## 背景

#971 で HTML Help のビルド成果物をダウンロードする処理を組み込みました。

先に挙げた appveyor のビルド結果リンクは、 #971 マージ後のものです。
x64 - Release ビルドの途中、REST API が Service UnAvailable を返したことにより異常終了しています。

ネットワーク通信を行うプログラムでは、相手先サーバーの過負荷や通信エラーを考慮して「リトライ」を組み込むのが定石なんですが、#971 で投入したダウンロードスクリプトではリトライを行っていませんでした。

「リトライを入れたい」自体に異論はないと思っています。

**再試行回数2回、再試行までの待機時間10秒くらい** を考えていますが、なんとなくこの辺すごくモメそうなので先に数字を書いてみます。「多く、短く」派と「少なく、長く」派に分かれるのかな？

## 参考資料

* https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6
* https://note.mu/artrigger_jp/n/n0795148b062d

## 次アクション

ビルドの成否に影響がある案件なので、明日には見切りで PR 入れる感じのスケジュール感でいきたいです。明日ってのは今夜(7/31PM)のことですが :smile:

**Comment by KENCHjp** [comment]
細かいことはさておきまして、通信経路の不安定さだとすれば、多く短くかなと思うのですが、相手の負荷だとすれば、相手がどれぐらいの時間の処理を行っているかかなと思うので、
もうちょっと間隔あけてもいいのかなと（ああ、定量的ではない・・・）
再試行３回の待機時間２０秒で１分リトライ、いかがでしょ？

**Comment by m-tmatma** [comment]
https://blog.hashihei.com/2019/02/02/tcp%E3%81%AE%E5%86%8D%E9%80%81%E6%99%82%E9%96%93%E3%81%AB%E3%81%A4%E3%81%84%E3%81%A6/

TCP の再送のように、リトライ間隔を
再試行のたびに二倍していくとやり方も
あります。

**Comment by berryzplus** [comment]
マニュアルの見方がよく分ってないかも知れません。
https://ci.appveyor.com/project/berryzplus/sakura/builds/26377459/job/1xv46vohpbaemh2b

**そんなパラメータねーよ！**と怒られてる雰囲気ですが、マニュアルで見るとそういう名前のパラメータがあるように見えるわけで・・・。

**Comment by berryzplus** [comment]
原因判明！
•https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/invoke-restmethod?view=powershell-6 ←これ :smile: 

`powershell 6` インタープリタの実行ファイル名は `powershell.exe` ではなく、
`pwsh.exe` になるらしいです。`powershell -v 6` ってやってみたけど動かんかったです。

https://win.just4fun.biz/?PowerShell/Windows10%E3%81%ABPowerShell%20Core%206.x%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB%E3%81%97%E3%81%A6%E3%81%BF%E3%81%9F
