### ISSUE TITLE
Appveyor で MinGW ビルドが失敗する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#979]
## 問題内容
Appveyor で MinGW ビルドが失敗する

https://ci.appveyor.com/project/sakuraeditor/sakura/build/job/qiic2dej9f2dbyg7

```
79: g++ -finput-charset=utf-8 -fexec-charset=cp932 -I. -DWIN32 -D_WIN32_WINNT=_WIN32_WINNT_WIN7 -D_UNICODE -DUNICODE -DNDEBUG -O2  ../HeaderMake/HeaderMake.cpp -o ../HeaderMake/HeaderMake.exe -static-libgcc
80: ../HeaderMake/HeaderMake.cpp:80:6: error: ambiguating new declaration of 'void fopen_s(FILE**, const char*, const char*)'
81:   80 | void fopen_s(
82:      |      ^~~~~~~
83: In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h:1395,
84:                  from ../HeaderMake/HeaderMake.cpp:57:
85: C:/msys64/mingw64/x86_64-w64-mingw32/include/sec_api/stdio_s.h:541:27: note: old declaration 'errno_t fopen_s(FILE**, const char*, const char*)'
86:   541 |   _CRTIMP errno_t __cdecl fopen_s(FILE **_File,const char *_Filename,const char *_Mode);
87:       |                           ^~~~~~~
88: mingw32-make: *** [Makefile:458: ../HeaderMake/HeaderMake.exe] Error 1
89: mingw32-make: Leaving directory 'C:/projects/sakura/sakura_core'
90: error 1 errorlevel 2
91: error build-gnu.bat       
92: Command exited with code 1
```

https://ci.appveyor.com/project/sakuraeditor/sakura/builds/26404372
ではビルドに成功している

ビルド環境が変わった?

## 再現手順
Appveyor で MinGW ビルドする

## 再現頻度
100%

## 問題のカテゴリ

- ビルドの問題
  - Appveyor

## 環境情報
Appveyor

**Comment by berryzplus** [comment]
環境差異によるものです。
対策は検討済みです。

https://dev.azure.com/berryzplus2019/sakura/_build/results?buildId=63

**Comment by berryzplus** [comment]
出先なので端折りますが、azure pipelinesにmsys2を入れた時に起こるビルドエラーの対策として、appveyorの環境を最新版にしたうたえで対策を入れる準備をしていました。

最新化するまでもなく勝手にバージョン上げられてしまったようですが。

**Comment by berryzplus** [comment]
まだ「出先」なんですが、ネタが揃ってるので具体的な対策についてコメントします。

[これ](https://github.com/sakura-editor/sakura/blob/c6910b0c1c105270fbe752214e4787805e8fa378/HeaderMake/HeaderMake.cpp#L80-L87)がエラー原因です。
独自定義関数 `fopen_s` のシグニチャが[CRTの標準関数](https://ja.cppreference.com/w/c/io/fopen)と被っているためにエラーになっています。

```
void fopen_s( 
   FILE** pFile,
   const char *filename,
   const char *mode 
)
{
	*pFile = fopen(filename, mode);
}
```

SUPERうんこ対応でエラーをつぶすには、戻り値を標準関数に合わせてやればよいです。
※標準のセキュア対応版 fopen の戻り値は errno_t です。

個人的には、この機会に古い基準で書かれた記述を全廃したいです。

----

https://github.com/sakura-editor/sakura/blob/c6910b0c1c105270fbe752214e4787805e8fa378/HeaderMake/HeaderMake.cpp#L67

MSVC向けの記述です。
ここの記述は本質的に2択(MSVC or MINGW-W64 GCC)ですが、この一文も #if でくくるのが分かりやすい気がします。

https://github.com/sakura-editor/sakura/blob/c6910b0c1c105270fbe752214e4787805e8fa378/HeaderMake/HeaderMake.cpp#L77-L78

MINGW-W64 GCC向けの記述です。
defineしてundefしてdefineする構造になっていて、紛らわしい印象を持っています。
MSVC版とMINGW-W64 GCC版を一目で比較できる位置に移動したいです。

https://github.com/sakura-editor/sakura/blob/c6910b0c1c105270fbe752214e4787805e8fa378/HeaderMake/HeaderMake.cpp#L50-L55

不要です。
定義する意味はないので削除したほうがよいと思います。

https://github.com/sakura-editor/sakura/blob/c6910b0c1c105270fbe752214e4787805e8fa378/HeaderMake/HeaderMake.cpp#L70-L75

不要です。
MINGW-W64 GCCにはこれらのマクロ、関数のテスト済み実装が存在します。

https://github.com/sakura-editor/sakura/blob/c6910b0c1c105270fbe752214e4787805e8fa378/HeaderMake/HeaderMake.cpp#L90-L99

不要です。
ビルド対象環境が多いと話がややこしくなるので、ここのプロジェクトではVS2017より古いコンパイラでのビルドをサポートしないことになっています。
VS2017のMSVCにはこれらのマクロ、関数のテスト済み実装が存在します。

----

上記を勘案して対策PRを作ると https://github.com/berryzplus/sakura/commit/dca429e13fa18a222190a0b5d35961b1db1933ef になると思います。
これは https://github.com/berryzplus/sakura/tree/pendings/azule_pipelines_test の一部で、MinGWビルド を azure pipelines に引っ越しさせる対応の一環として準備していたものです。

PRの体裁を整えられるほどの余裕もないので、とりあえず情報だけ出しとく感じです。

**Comment by m-tmatma** [comment]
> SUPERうんこ対応でエラーをつぶすには、戻り値を標準関数に合わせてやればよいです。
> ※標準のセキュア対応版 fopen の戻り値は errno_t です。
> 
> 個人的には、この機会に古い基準で書かれた記述を全廃したいです。

いいと思います。
