### ISSUE TITLE
appveyor の clone パスを標準に戻す

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#98]
appveyor の clone パスを標準に戻す

#43 の対応のために、appveyor の clone パスを変更した。
https://github.com/sakura-editor/sakura/blob/84349f44349126a52cb5b67c311b4fd70d38346c/appveyor.yml#L3

しかし、効果がないことがわかったので標準に戻す

ビルドしてできた pdb ファイルには絶対パスが含まれているので
毎回パスが変わらないのが望ましい。

#43 の対応のために #96 で workaround を入れた。

**Comment by kobake** [comment]
#99 マージ完了
