### ISSUE TITLE
PREPROCESSOR マクロの必要性に関して検討する

### ISSUE THREAD

**Issue by m-tmatma** [sakura-editor/sakura#982]
PREPROCESSOR マクロの必要性に関して検討する

https://github.com/sakura-editor/sakura/blob/44da318f1ed6d31c6749e28b358de873018ad54d/HeaderMake/HeaderMake.cpp#L60-L64

https://github.com/sakura-editor/sakura/pull/981#discussion_r310355983

> 
> 
> > このdefine、意味があるんでしょうか？
> 
> 使っているので、「意味はある」と思っています。
> 
> https://github.com/sakura-editor/sakura/blob/c6910b0c1c105270fbe752214e4787805e8fa378/HeaderMake/HeaderMake.cpp#L244-L248
> 
> `PREPROCESSOR` 定義の端っこが見切れてしまっていますが、末尾は `%s` になっています。
> コマンド文字列 `$"cl.exe /EP {in_file}"` を [`_popen` 関数](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/popen-wpopen?view=vs-2019) に食わせてます。
> 
> MSVC版では `cl.exe /EP Funccode.hsrc` がプリプロセッサ起動コマンドですが、
> GCC版では `gcc.exe -x c++ -E Funccode.hsrc` がプリプロセッサ起動コマンドになります。
> 
> Funccode.hsrcのレベルだとプリプロセッサの挙動は変わらないので、あえてcl.exe一択にしてもいい気はします。
> が、そこに手を入れると変な問題が起きそうなので、そこの仕様には突っ込まない方向でいきたいです。

**Comment by k-takata** [comment]
> このdefine、意味があるんでしょうか？

`PREPROCESSOR` マクロが定義されても使われていないと勘違いしての発言だったような気がするので、閉じてしまおうと思います。
