### ISSUE TITLE
find-tools.bat の `"%CMD_GIT%"` を活用する

### ISSUE THREAD

**Issue by berryzplus** [sakura-editor/sakura#984]
メモ）すっかり忘れていましたが、ここ `"%CMD_GIT%"` に書き換えるべきですね :cry:
**※このPRには混ぜないでほしいです。**

_Originally posted by @berryzplus in https://github.com/sakura-editor/sakura/pull/955_

issue #900 とも関連します。
あまり重要度が高くなく、放置しとくと忘れる可能性が高いので issue にしときます。

**Comment by m-tmatma** [comment]
git コマンドでパスが通ってない状態でインストールすることないので
対応しなくていい気がする。

**Comment by berryzplus** [comment]
モチベーションが尽きたので閉じてしまいます。 #1394
